### ISSUE TITLE
Dates change appearance when formatted as link

### ISSUE THREAD

**Issue by mwandelt** [espocrm/espocrm#1002]
Date fields placed in list layouts change their appearance when they are formatted as links. The localization settings for date format and timezone are ignored, and they are displayed as timestamp (YYYY-MM-DD HH-II-SS) in UTC. While the format change is obvious and tolerable the silent timezone change is not, because the user gets no hint about it.

**Comment by yurikuzn** [comment]
Thanks for reporting.

Fix: https://github.com/espocrm/espocrm/commit/9de7105cdef07ee6575e890ddf797ca087cc88d6
