### ISSUE TITLE
Duration not displayed in list view

### ISSUE THREAD

**Issue by mwandelt** [espocrm/espocrm#1003]
When placing the duration field of an event entity (i.e. call) in a list layout the values will not be shown. Only after selecting "View" from the context menu of a row the value for that particular record becomes visible.

UPDATE: The duration becomes visible when placing also the dateEnd field in the list view.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/a80d847f442c77449bcf4b34718117a89bb94368
