### ISSUE TITLE
Email confidentiality (access to all my private emails)

### ISSUE THREAD

**Issue by Grahamrich1** [espocrm/espocrm#1008]
Whilst testing 5.3.2,  I created a contact with my own email address.  When I synced emails all of my emails became available for viewing for all users view history in my contact.  I added one of the other users in the business and I was able to see their emails in their history.  Is there a way to prevent the use of an internal email address to avoid this.  I tried filtering internal emails but this doesn't capture email that have an external contact on the "to" list.

**Comment by bandtank** [comment]
You can do this with teams and roles (ACL), but I've found it to be very
hard to know for sure if emails are still private. I have not migrated my
users' email accounts to EspoCRM yet due to this concern.

**Comment by loreahlie11** [comment]
You are probably seeing them because you are a system admin?  Try logging in as a user without admin roles and see if they are visible?  If they are then you can set the role permissions for email visibility to "own" in the role which you are setting the permission.
