### ISSUE TITLE
Need to integrate Error Tracking Software with EspoCRM

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1018]
Checking espocrm/data/logs is well and good, but it's not good enough as the maintainers of EspoCRM don't get notified immediately when the error occurs.

I would recomend [Sentry.io](https://sentry.io/welcome/). It's free and very easy to integrate.

CRM has become a very critical part of each and every industry. If anything goes down in CRM then it becomes a big problem. So, all the errors which can take down the system should be notified immediately. Sentry is one of the best ways to do it.

**Comment by theBuzzyCoder** [comment]
People can host it in their system. If someone doesn't want to host Sentry, they can sign up

**Comment by beppe9000** [comment]
see this: https://hamstersoup.wordpress.com/2006/05/12/ftptail/
