### ISSUE TITLE
portal documents only selected for created_by_id

### ISSUE THREAD

**Issue by khyoz** [espocrm/espocrm#1019]
When a document is created and attached to a user (portal user), field assigned_user_id is correctly filled into the table `documents`. Howewer, document is not listed when we try to display documents from a folder. 
When I look into the database with phpmyadmin....table `documents`
If we change the field `created_by_id` with the value of the portal (`assigned_portal_id`) then document is listed.
That means, in portal, the query seems to be wrong and select should add a (or `assigned_user_id` = portal connected user id) condition
let me know if you need further details.

**Comment by yurikuzn** [comment]
Assigned user is not taken into account in Portal. By design.

**Comment by khyoz** [comment]
thanks for explanations....I let a [link](https://forum.espocrm.com/forum/bug-reports/41655-portal-documents-only-selected-for-created_by_id-1019) to answer in the forum for people who want to understand
