### ISSUE TITLE
Email interactions with customer

### ISSUE THREAD

**Issue by fabioce** [espocrm/espocrm#102]
Hello,
I'm using the 3.9.2.
I'm reached to create a case from email account polling and to automatically send answer to sender.

Now when I add comment or I close the case, no emails where sent to my customer (sender) to advice that the case is working or closed.

Why?
Thanks

**Comment by yurikuzn** [comment]
Hi

It's not designed to do it. You can:
* Write a hook (needs a little programming skills) to send email when status gets changed to 'Closed'.
or
* Use Workflow feature from Advanced Pack to do the same but through UI.
