### ISSUE TITLE
Shared Calendar can bypass ACL restriction

### ISSUE THREAD

**Issue by vdbemden** [espocrm/espocrm#1021]
Hi, 
I was using the new function in Roles "user permission" to display shared calendar team by team when I saw something strange : 
A user from a team can see meeting names from other teams.

In details : 
Let's say a User#1 is in team A and User#2 is in team A AND team B.
If the User#2 is attending to a meeting for team B, the User#1 can see it in his shared calendar.
It seems that it's because #1 and #2 are in the same team although the meeting isn't for the team A...

I was expecting that User#1 wouldn't see anything from team A cause I restricted it in the ACL Rules...

Thanks for your help

**Comment by yurikuzn** [comment]
Hi,

Access to records is contolled not by 'user permission'. It's controlled by a read access level to Meeting scope.

**Comment by vdbemden** [comment]
Hi, 
That's what I expect
But then how can you explain that I have meetings in the shared agenda that I can't browse (Error 403) ?
My read access level to Meeting scope is set to "Team" and I can see meetings in the agenda that are not relevant to my team (although the concerned user is in my team but the concerned meeting is not).

**Comment by yurikuzn** [comment]
You are right. I thought ACL is applied. Here is the fix: https://github.com/espocrm/espocrm/commit/cf5202a0651cc1ff17b6d4fbefa264c2bf34d1cc

**Comment by vdbemden** [comment]
Thanks for the fix !
