### ISSUE TITLE
Group Account Emails from other teams are shown in stream (including their subject), should be hidden

### ISSUE THREAD

**Issue by coanco** [espocrm/espocrm#1026]
The situation:

- We have a setup where we have two group email accounts set up. One for "the team", one for "the managers". Each is set up to be owned by a specific team ("employees" and "managers", respectively).
- Under Administration->Roles, the rights for email are set to: "Access:enabled | Create: no | Read: team | Edit: team | Delete: no", there is no setting available for "Stream". Group Email Account Permission is set to "no".

Witnessed behaviour:
- In the "Email" view, everything is fine, only managers see the emails pulled in through the "the managers" group mail account.
- In the stream, however, _everyone_ sees the emails listed that are pulled in for the manager team.
- Clicking on the email brings (rightfully) a 403

Expected behaviour:
 - in the stream, emails for a team sent to a group mail account should not be visible to users who are not explicit members of that team, even if they e.g. follow a person CC'ed on the email. 

We are rather sure that our configuration is clean, so we see this as an issue, because the subject of an email 
a) often holds privileged information and
b) can not be controlled by the recipients, here being the managers.
So an email coming in saying "Your requested drug test results for employee Marcus Miller" or "Urgent: law suit filed by competitor X" should definitely not be in _everyone_'s stream.

Does that sound understandable? :)
Thanks!

**Comment by yurikuzn** [comment]
Hi,

It's a known issue. Planned to be fixed soon.

**Comment by coanco** [comment]
Thanks a lot! You're doing amazing work :) 
PS: I hope this doesn't reopen the issue
