### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#1031]
Hi

I'm receiving Cors errors when trying to create an entity from a form I created. I have set the Access-Control-Allow-Origin header, but it's still not working:

![image](https://user-images.githubusercontent.com/7330170/45209888-638bb300-b28e-11e8-80f3-696bbdd395ce.png)

Kind regards

**Comment by Sloff** [comment]
This issue is also present with the new lead creation api

**Comment by yurikuzn** [comment]
Hi,

This seems is not an issue in EspoCRM.

**Comment by Sloff** [comment]
[This](https://github.com/espocrm/espocrm/issues/141#issuecomment-408702387) alteration resolves my issue.

The top portion is implemented on the server, which I can do, but the bottom portion is within EspoCRM code.

The problem is that EspoCRM doesn't respond with a 200 status when the pre-flight OPTIONS request is made by the browser, it responds with a 401

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1046

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/2755
