### ISSUE TITLE
$this->getEntityManager( in a hook

### ISSUE THREAD

**Issue by samanthaworri** [espocrm/espocrm#1034]
how can i access getEntityManager() in a hook?

i have the following in my hook code but application gives error 500 when i save an instance of the entity
```
<?php

namespace Espo\Custom\Hooks\Areportingr;

use Espo\ORM\Entity;

class nameXbsave extends \Espo\Core\Hooks\Base
{
	public static $order = 1;
	public function beforeSave(Entity $entity,  $foreign, array $options = array())
	{
		
		$recordId = $entity->get('id'); 
		$contId = $entity->get('contact'); 
		$desctemp='Contact ID'.$contId
		$entityManager = $this->getEntityManager();
		$contactX = $entityManager->getRepository('Contact')->get($contId);
		$fieldEmailIsSet = $contactX->has('emailAddress'); 
				
		if($fieldEmailIsSet){
			$descemail = $contactX->get('emailAddress');
		}
		

		$entity->set("description", $desctemp);
```

**Comment by yurikuzn** [comment]
Looks fine for me. I'd check whether $contactX is not null after fetching.

Check your logs for more detail error message.

**Comment by yurikuzn** [comment]
Before save function is defined not properly.

See: https://github.com/espocrm/espocrm/blob/master/application/Espo/Hooks/Common/NextNumber.php#L61

**Comment by samanthaworri** [comment]
@yurikuzn thank you. $contId = $entity->get('contact');  doesn't asign anything $contId is null\empty.

contact is a field resulted from a linking my custom entity to Contact entity. 
I must be using wrong statement to get the value of a linked field?
