### ISSUE TITLE
Login with local Espo-User when LDAP is Active (Portal & Main not working)

### ISSUE THREAD

**Issue by deliciousbob** [espocrm/espocrm#1047]
Hallo Espo Community,
I'm not sure if that is a feature or a bug, but let me describe my situation:

I'm trying to login with User-Accounts from LDAP and from local created Espo-Users.
I want to create a User-Portal for users without LDAP Login.

User is a Poral-User and has rights for the Portal,
when i try to login with this User and LDAP Auth. is activated, i cannot login.
> [2018-09-20 08:36:41] Espo.ERROR: LDAP: Authentication failed for user [testuser], details: user is not found. [] []

When Auth. is changed to ESPO, the Login works correct.

When i try to Login with the **local Espo** "Administrator" User, the login works perfectly, eaven when LDAP-Auth. is activated.

**Is it possible to use both Login forms:**
 1. For example first look after a LDAP User when LDAP Auth. is active 
 2. If user is not found in LDAP -> Check User in local EspoDB
 3. if no user found -> "Auth Error"

Thank you very much
Kind regards
Robert

**Comment by tmachyshyn** [comment]
Hi deliciousbob,

Currently, portal user should be defined in LDAP server. We are planning to add such possibility in the next release. Using both forms is impossible. Only admin users can use Espo Auth when LDAP is enabled.

**Comment by deliciousbob** [comment]
Thank you for reopening my post and for putting it on the release goal for v. 5.4.4.
It would be an great advantage and would give tons of posibilities by letting non AD users (like non computer users inside a company and customers or vendors) work on one platforms together! 
Thank you for your great work. I've build up Ms Dynamics CRM for a Company and i can say this CRM can replace Microsoft CRM by 95%. I realy love testing it for different usecasesand and we consider going live with it :)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/158cdd27bca1c718bc1ee2e65378e9d84aa780ab

**Comment by srudkowski** [comment]
Hi, I will be grateful for information whether this functionality has been implemented in Espo and works in version 7.3.2? I have a similar need to login a local user who is not in LDAP with LDAP authentication enabled. Login only works for users with administrative privileges. I will be grateful for the information.

Best regards
Slawomir
