### ISSUE TITLE
How to give the user the authority to create the Team and User?

### ISSUE THREAD

**Issue by xiaoluhong** [espocrm/espocrm#1048]
Version 5.4.3

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/20707603/45826615-6626e780-bd27-11e8-9075-587ca50e3b63.png">

Hi,

When I set role permissions for a regular user (not a system administrator), I cannot set create team and user permissions. Is this designed like this? Or is my use incorrect.

My usage scenario is that the system administrator is only responsible for environment setup and system maintenance. The application administrator is responsible for the later application operations (such as adding teams, users, etc.), so I need to add team and user creation privileges to the application administrator.

**Comment by yurikuzn** [comment]
Hi,

Only admin can do it by design.

**Comment by xiaoluhong** [comment]
Can ordinary users add this permission? Or say have to be an administrator to have this authority? thank you.

xiaoluhong@rancher.com

________________________________
收件人: Yuri Kuznetsov <notifications@github.com>
发送时间: 星期四, 九月 20, 2018 23:46
收件人: espocrm/espocrm
抄送: Xiaolu Hong; Author
主题: Re: [espocrm/espocrm] How to give the user the authority to create the Team and User? (#1048)


Hi,

Only admin can do it by design.

―

**Comment by yurikuzn** [comment]
Not supported. You need to make some customization to have this.

**Comment by xiaoluhong** [comment]
thanks.
