### ISSUE TITLE
LDAP username is case sensitive

### ISSUE THREAD

**Issue by richbailey** [espocrm/espocrm#1049]
This is very unusual and impossible for users in companies where AD / LDAP usernames often have inconsistent capitalisation.

**Comment by tmachyshyn** [comment]
Hi,
It's a bug. It will be fixed in the next release. Thanks for reporting.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/5ae0b5a3f24c3363ba5a75f9c0ebf706d985b0b5
