### ISSUE TITLE
Currency fields formatting problem

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#105]
currency fields should show two digits after the decimal point.

![screen shot 2016-02-12 at 13 50 24](https://cloud.githubusercontent.com/assets/7381617/13008766/3c32e788-d190-11e5-8b4d-461177f318c3.png)

I had a look at fields/float.js and fields/currency.js and can fix this if you suggest the best way - have currency.js redefine formatNumber() ?

**Comment by yurikuzn** [comment]
I will look. It would be good to show nothing if empty or >=2 digits if not empty.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/de6cc1f9bb370ce2df78a9bf3f7fc7173d16603b
