### ISSUE TITLE
External email client mailto

### ISSUE THREAD

**Issue by OlofBailey** [espocrm/espocrm#1050]
Ability to se a system wide preference to use an external email client. It’s currently per user but I’d expect this to be a system wide preference in most organisations.

**Comment by beppe9000** [comment]
Also this needs the opposite, to force all mailto: links to the internal client. Right now on list views clicking an email address opens the external client.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1135
