### ISSUE TITLE
Blank calendar

### ISSUE THREAD

**Issue by vdbemden** [espocrm/espocrm#1053]
Hi, 

Sometimes the calendar get blank unexpectedly.
The only solution I found was to refresh the page until the calendar works again.
If it could be ok for a normal user, it's quite painful for an automatic user.
Have you some idea about why it's happening and how it can be solved?

Thanks in advance, 

Loïc

![image](https://user-images.githubusercontent.com/20713639/45941946-b086bd80-bfe0-11e8-9892-159185449698.png)

**Comment by yurikuzn** [comment]
Hi Loïc,

What browser? Does it happen only with Calendar Dashlet?

**Comment by vdbemden** [comment]
Hi, 
Thanks for the quick answer.
I'm using Firefox and it happens and the tv uses Chromium (on raspberry pi) and it happens too.
As the bug appears randomly, I can't say if it appears also on the Calendar page.
I think I've also seen it on the page but I can't say it for sure.

**Comment by yurikuzn** [comment]
Do you have the latest EspoCRM version?

**Comment by yurikuzn** [comment]
Could you provide the error from the browser console when this happens again?

**Comment by yurikuzn** [comment]
Seems the version is not 5.4.*.  Try to upgrade to 5.3.6 or 5.4.3.

**Comment by vdbemden** [comment]
Ok, I'll try to update the version and I'll keep you inform if the bug happens again with more information.
Thanks !
