### ISSUE TITLE
Linked list filter, search and sort option & hide/expand tab/list

### ISSUE THREAD

**Issue by deliciousbob** [espocrm/espocrm#1055]
Hallo,

I worked several years as a Microsoft Dynamics CRM Administrator and i must say, you did a great job creating this wonderful web application! So thank you very much for your great work!!
ATM I'm testing the posibilities with EspoCRM and ... unfortunetly you always compare your new love to your EX ;-) you know what i mean... 

I miss some features that could enhance working with linked-lists in CRM and it would be great to have them in this great application:
-     Possibility to filter and search in linked lists from other Entities
         (For example the sales opportunities on the customers page)
-     Especially if you have several hundret or tousend entries in an linked list, it 
        would be great to have the ability to search directly on that page.
-     Sort colums by name / number / date 
-     And filter on selection fields or status fields (to show for example only only active)

As I added several Linked Entity lists on the Customer, i sometimes do not want to show all lists or all Tabs on the first view (for some users it can be too much information at once) It would be very nice to have an 

-    **ability to expand or hide an Tab or an linked list**

(only show the title and to view more informations click on the expand icon). It should be an predifined option on the layout management to standard hide or open the tab or the linked entity list.

![espo-crm-list-search-filter](https://user-images.githubusercontent.com/13135271/45979674-21b18980-c050-11e8-8fd0-179e3c4cba97.jpg)

I think that these enhancements could help to find information easier and quicker, esspecially if the customer is on the phone... I know that you can filter and search on any entity in the enities list, but it would be very useful to have equal features on the linkes-list.
It would be realy great to see these features sometime in the future.
Thank you very much for your great work!
Best regards from an Austrian fan :)
Robert

**Comment by yurikuzn** [comment]
The ability to search in linked lists will be available in 5.5.0.

**Comment by yurikuzn** [comment]
Search is supported. With the bottom panel tab support, the ability to hide is not that needed anymore.
