### ISSUE TITLE
[Feature suggestions]  Multiple list views per entity (predefined colums & filters per list)

### ISSUE THREAD

**Issue by deliciousbob** [espocrm/espocrm#1056]
Hallo EspoCRM Team,

I thought about another great thing for using your great Tool:
Something that is very common in MS CRM are **predefined lists per Entity**.

For example the sales Team want only to see their customers with the delivery adresses as a column and the annual sales. But the Marketing wants to see only Customers with an approval to contact by E-Mail and they need to have the collums business type and preference type shown in that list directly.

That's why it would be extremly useful to have different predefined list views per entity:
- **Admins should have the ability to add different list views (also in small lists / linked lists) and define one default list for all users. A user can then change his prefered list by selecting it as "my default view"**
- **Every of these lists could include different colums and predefined filters.**
- **The user can then change the list as needed. (like an drop down option list) and the items as well as the Colums in the List will then change. Additional filtering is it is already possible.**

In MS CRM there is even the **posibillity for users to create their own list by simply adding or deleting colums and adding new filters from existing lists and save the list view as their own**.
These lists are only shown per user but they can even **share it to other users or teams**.

Thank you very much! 
Best regards
Robert

**Comment by kdrabant** [comment]
Missing that too.
For me it doesnt need to be as complex as it is in MSCRM, but it would be great to have it in a basic form.

Best regards
Kevin

**Comment by yurikuzn** [comment]
Showing/hiding columns is possible in v8.1. Regarding having stored views, I ruminated about it before, I'm more inclined to not having this feature at the moment.
