### ISSUE TITLE
[Feature suggestions] Extended Search on linked entity fields & Save Option

### ISSUE THREAD

**Issue by deliciousbob** [espocrm/espocrm#1057]
Hallo EspoCRM Team,

sorry for adding so much feature suggestions atm, but i really love your CRM and want to make it eaven more usable for anyone. One thing that might be extremly handy would be an

**extended search function including fields of linked entities.**

This could be verry useful if you want to filter some special customers that have the same characteristics and for example had an issue with payment and you created a case for every issue per customer... you could then export the list for further processing or directly mass update the filtered cases including your special customers. 
An further ability would be to create an marketing campaign (send an E-Mail) including all customers in certain case types in certain areas of the country (part of the postal code for example).
An ability to save these applied filters would be great. In that case you could use it in the future again.
(including ability to delete and edit the self created filter)

The mokkup does the summ-up:
![espo-crm-extendedsearch fw](https://user-images.githubusercontent.com/13135271/45983401-ab675400-c05c-11e8-898d-f40361a55312.png)

Thank you very much!
Best reagards
Robert

**Comment by yurikuzn** [comment]
You can create Foreign field in Entity Manager and then add these fields to Filters in Layout Manager.

**Comment by deliciousbob** [comment]
Good morning Yuri :) thank you for the Info, i didn't recognice the "Save Filter" under the dropdown menue 👍  
But I could not get the fields of foreign fields, i can only filter for a certain customer, but i cannot go deeper. I can also select multiple customers if i the account filter "is any of" and filter in the Search Popup, but if I select like all of my the 650+ Customers that have the same postal code, it only adds me the selected once. As we changed the list items to 10, it would take me 65 times to klick "show more" and then add all 650+ Customers to the filter.
It would be easier and more intuitive to select additional fields from the related entity.
For example to have "Account" as it is on "Add Fields" and additionaly "Account - related fields" to select on the "Add Fields" Drop-Down. Adding Filters Fields multiple times would be also necessary in that case.

**Comment by yurikuzn** [comment]
You can create a foreign 'Postal Code' field that will represent account.addressPostalCode then use this field in Search.

**Comment by deliciousbob** [comment]
Hallo Yuri, sorry but my example was very bad, because postal code is no separate field.
It is not about one field is about having posibility to search on separate fields without selecting specific entries. Hope you can understand what i mean.
Best regards Robert

**Comment by yurikuzn** [comment]
I don't understand, since there is no need to select specific records in the way I proposed.

**Comment by deliciousbob** [comment]
There is no need for a new feature? Pretending there is no need for such a feature is kind of narrow-minded don't you think ? There could be a need for that and i made enough examples for that above... 
But it was only a suggestion... I like your CRM and only want to contribute helping making it even better.

**Comment by yurikuzn** [comment]
Your comment https://github.com/espocrm/espocrm/issues/1057#issuecomment-424223408 made me to think that you didn't get the point of related fields.

It's supposed that the list of available filters is limited by those admin specified. If admin wants users be able to search by account's postal code, one creates a foreign field. For more complex search there is Reports feature.

**Comment by yurikuzn** [comment]
If you really need those fields you can create a few foreign fields for case entity. This will make trick. Just little more configuration for admin.
