### ISSUE TITLE
 3.9.2-to-4.0.0-beta.1 rebuilding app

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#106]
After upgrading 3.9.2-to-4.0.0-beta.1 I cannot rebuild app:
Fatal error: Cannot use object of type stdClass as array in ...\espocrm\htdocs\application\Espo\Core\Utils\Database\Schema\rebuildActions\Currency.php on line 45

**Comment by yurikuzn** [comment]
In data/config.php change currencyRates from object to regular array. This is the bug we need to fix.

**Comment by yurikuzn** [comment]
fix: https://github.com/espocrm/espocrm/commit/d54ccb0c9e47882924ae2e24db44e3ab7881d91e
