### ISSUE TITLE
Portal Users unable to see emails in the stream

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#1064]
I believe this might be related [this](https://github.com/espocrm/espocrm/issues/1033) thread

**Comment by yurikuzn** [comment]
I believe portal users weren't able too see notes about emails in stream before. Unless they have an access to Emails scope.

**Comment by Sloff** [comment]
They do have access to the email scope(Read: Account), and they were previously able to see the emails in the stream
-------- Original Message --------

**Comment by Sloff** [comment]
So there is no way for them to see it in the stream anymore?

**Comment by yurikuzn** [comment]
You can fix here: https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Stream.php#L1392

by changing to $this->getAclManager()->getLevel($user, $scope, 'read') !== 'own'
