### ISSUE TITLE
Roles Management; scope and field level problem.

### ISSUE THREAD

**Issue by voluse** [espocrm/espocrm#1067]
Hi;

Roles got two type of problems that I faced.
____

First scenario;
We got; 
Entity1, Entity2, User1

**The relationships;**
Entity1 one-to-many Entity2

**Roles;**
User1 for Entity1 
Create: No | Read: All | Edit: No | Delete: No
User1 for Entity2
Create: Yes | Read: All | Edit: All | Delete: No

In this scenario User1 can create Entity2 from Entity2's main page like ({basepath}/#Entity2).
But User1 can not create Entity2 from Relationship Panel which is located Entity1's main page. On the relationship panel "plus" icon that for create not exist.

When you set roles like;

User1 for Entity1 
Create: No | Read: All | **_Edit: All_** | Delete: No
User1 for Entity2
Create: Yes | Read: All | Edit: All | Delete: No

"plus" icon appears and can usable.

We can bypass this problem with,
**Roles**
User1 for Entity1 
Create: No | Read: All | **_Edit: All_** | Delete: No
**Field Level**
Field1: Read: Yes | Edit: No
Field2: Read: Yes | Edit: No
.
.
(etc.)

You have to set all Field Level roles edit permissions one by one. Unfortunately User1 still can see "Edit" button on top of the record, because It has Scope Level permission.
_____

Second scenario;

We got;
Entity1, Field1, User1

Roles;
User1 for Entity1 
Create: Yes | Read: All | Edit: All | Delete: No
**Field Level**
Field1: Read: Yes | Edit: No

When User1 want to create Entity1, Field1 becomes "read-only". 

In this option shouldn't be like, User1 can create Field1? Then can not edit after create.
____

I know it was a little bit longer. Through the feedbacks and comments EspoCRM will be more efficient and stronger than ever.

Thanks again!

**Comment by yurikuzn** [comment]
Hi,

Both scenarios are how they was intentionally designed.
