### ISSUE TITLE
About Documentation...

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1072]
in phpstorm i can't get autocomplete, because of dependency injection code must be type-hinted by documenting it with php-doc style comments

**Comment by yurikuzn** [comment]
Do you mean your are lacking hinting for protected methods link `getMetadata`, `getServiceFactory`, `getEntityManager` etc, returning injected objects ?

**Comment by beppe9000** [comment]
@yurikuzn Yes, also the "go to definiton" function and member/field auto-completion.

@bandtank I don't think a bunch of comments can be so dangerous (phpstorm also supports [meta documentation](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata) in separate files). So why re-invent the wheel everytime one wants some docs? Better to have documentation upstream for future users too.

**Comment by m-hcb** [comment]
It is a terrible idea unless you decide to start doing it for yourself.

**Comment by xurizaemon** [comment]
@m-hcb @bandtank I don't see why the hostility to inline documentation - can you expand on your reasons?

IMO It's a good suggestion, and docs are a healthy indicator for good projects. It might be a lot of work, but I'd think you'd want to support @beppe9000 to contribute to this ... rather than resisting it?

**Comment by yurikuzn** [comment]
I wouldn't like to have boilerplate code documented, like this:
```
/**
 * Returns EntityManager.
 *
 * @return \Espo\Core\ORM\EntityManager
 */
protected function getEntityManager() {
    return $this->getInjection('entityManager');
}
```

**Comment by yurikuzn** [comment]
php now supports type constraints, we will stick to it rather than comments.

**Comment by beppe9000** [comment]
The main point of this issue was actually the problem of loss of type information and the resulting difficulty of static analysis when string-based DI is involved.
