### ISSUE TITLE
Shared Calendar can bypass again ACL restriction

### ISSUE THREAD

**Issue by vdbemden** [espocrm/espocrm#1074]
Hi, 

It seems like Issue #1021 is active again...
I did install the fix by hands and it worked but it seems like the last updates broke it in some way...

Thanks for your help

**Comment by yurikuzn** [comment]
Hi,

I don't have this issue in an upgraded instance.

**Comment by vdbemden** [comment]
My bad, I had a custom Activities.php file.
I don't even know how it could work the first time...
Maybe the cache was the problem.
Sorry for the inconvenience and thanks for the answer
