### ISSUE TITLE
Ability to specify email notification for individual users

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1077]
Right now notifications via email are in Administration > Notifications.

Some users want notification via email while others don't. If we could configure this for individual users like in preferences, it would be great.

**Comment by yurikuzn** [comment]
It's possible for users to enable/disable `Email notifications upon assignment`, `Email notifications about posts and status updates` and `Email notifications about mentions in posts` in Preferences. If enabled in Administration.
