### ISSUE TITLE
Associate actions from relationship panels

### ISSUE THREAD

**Issue by asfourco** [espocrm/espocrm#1087]
### Issue
* Clicking on actions, e.g., on email address of a contact in an Opportunity View will open a create email dialogue and associate the Account of the contact as the parent.
* Clicking on the '+' of an Opportunity in the relationship panel of an Account View will open a create new opportunity dialogue ... without associating with the Account as a parent

### Expected behaviour
* When creating an email, it is expected that the parent of the email would be the Opportunity.
* When creating a new Opportunity from the relationship panel of an Account view be associated as a child opportunity of that account.

**Comment by yurikuzn** [comment]
> Clicking on the '+' of an Opportunity in the relationship panel of an Account View will open a create new opportunity dialogue ... without associating with the Account as a parent

Actially it associates.

**Comment by yurikuzn** [comment]
I will look into. Thanks.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1091
