### ISSUE TITLE
Multiple Kanban Boards in module

### ISSUE THREAD

**Issue by swordsreversed** [espocrm/espocrm#1089]
I was previously using Pipedrive but it lacked extensibility. One feature I liked was multiple Sales Pipelines (kanbans) for its Opportunity view. Would this be possible in Espo? Where in the code would i look to work on this?

**Comment by yurikuzn** [comment]
Hi,

Code: https://github.com/espocrm/espocrm/blob/master/client/src/views/record/kanban.js
