### ISSUE TITLE
Is fuzzy matching supported?

### ISSUE THREAD

**Issue by xiaoluhong** [espocrm/espocrm#1090]
Does search support fuzzy search? For example, if a customer name is ABCDE, you only need to search for CD or DE to match the corresponding customer name. thanks.

**Comment by yurikuzn** [comment]
Yes. Wildcard * can be used. https://github.com/espocrm/documentation/blob/master/user-guide/text-search.md

**Comment by xiaoluhong** [comment]
Can fuzzy search be set by default without adding * manually？
