### ISSUE TITLE
Import Bug Mapping List

### ISSUE THREAD

**Issue by kdrabant** [espocrm/espocrm#1095]
Hello,

if you try to import a .CSV and in the first row is a column which doesnt contain data, you wont get a mapping list.

EspoCRM\client\src\views\Import\step2.js
Line 137

```
$select = this.getFieldDropdown(i, d.name);
$cell = $('<td>').append($select);
$row.append($cell);

var value = d.value; <---------------------------------------- Line 137
if (value.length > 200) {
value = value.substr(0, 200) + '...';
}

$cell = $('<td>').css('overflow', 'hidden').html(value);
$row.append($cell);
```

Please Change: 
`var value = d.value;`
To
`var value = String(d.value);`

Best regards

**Comment by yurikuzn** [comment]
Thanks for reporting.

https://github.com/espocrm/espocrm/commit/18859963e54103a670fc593335ba8904b56f9d50
