### ISSUE TITLE
Navbar dropdown not working on iPad

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#1098]
Hi

When touching the ellipse on an iPad it does not bring up the menu with additional options

**Comment by yurikuzn** [comment]
Hi Sloff,

Any help with fixing is appreciated.

**Comment by yurikuzn** [comment]
Please could you also check whether other dropdown menus are working.

**Comment by Sloff** [comment]
Will do 👍

**Comment by yurikuzn** [comment]
Unfortunately, I have no clue how it can be fixed.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/983dc7c37678fe3e13d7882e7d4f3c9c4ee1dc0c
