### ISSUE TITLE
Dynamic Default Value

### ISSUE THREAD

**Issue by shefi** [espocrm/espocrm#1099]
Feature suggestion.

It would expedite the productivity if Default Values would allow for dynamic values.

For example:
We have Lead with the field name equal to "John Doe" and opportunity amount equal to "$100".
On field Name of entity Call we could set the default value like so: "Call {{lead.name}} for {{lead.opportunityAmount}}"

So, when clicking Schedule Call on the Lead activities, the form would show up with the name field filled like so: "Call John Doe for $100".

**Comment by yurikuzn** [comment]
This can be achieved with before-save scripts and workflow tools.
