### ISSUE TITLE
Problem with z-index on iPad in portrait mode.

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#11]
When using on a tablet with media-queries of width 768px the drop downs are rendered below the main body elements.

**Comment by yurikuzn** [comment]
Seems it works after one of bootstrap upgrades.

**Comment by alasdaircr** [comment]
Awesome

On 20 Apr 2015 16:43, Yuri Kuznetsov <notifications@github.com> wrote:

Seems it works after one of bootstrap upgrades.
