### ISSUE TITLE
Removing entity cleanup

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#111]
Handling of Entity removal may have a cleanup issue :
- if the deleted entity has a relation, the relation is still referenced to in the entitydef of the related entity
- the deleted entity is still available in the relationsship layout of the related entity
- if the deleted entity was on the 'quickCreateList', it is still there. 

Rebuilding app does not fix this. (v4 beta)

**Comment by yurikuzn** [comment]
If we will remove relations it will be impossible to restore it if remove was accidental. That's why we don't do it.
