### ISSUE TITLE
create custom button

### ISSUE THREAD

**Issue by orbMing** [espocrm/espocrm#1115]
hi, 
so basically i'm new in espocrm. so, i ned to create a ticketing system for the company. but we need customize a bit to meet the demands. one of our problem is, how to create custom button and secondly, how to transfer data from table(entities) to another table(entities). i have create a custom entities and we need to transfer the data from the table based on the ID.

**Comment by yurikuzn** [comment]
Hi,

For developer help I recommend using our forum: https://forum.espocrm.com/forum/developer-help.

Sorry, but I have no ability to provide help.
