### ISSUE TITLE
One field Quick-Edit does not check requirements on other fields

### ISSUE THREAD

**Issue by deliciousbob** [espocrm/espocrm#1118]
Hallo,
I just found a strange behaving with required fields.
I have a rule if the field "Solution" is not Empty -> SolutionType & SolutionText = Required
That works well if i edit the case, but if i edit only the one field (with the pen symbol beside the field) it will not recognice the required fields and i can save the change without chaching the required fields.
What do you think about that behavior is that normal ?

Thank you very much!
Kind regards Robert

Here the example:
![2018-11-13 14_49_20-haltbarkeit zu kurz - hirzinger robert belegschaft - 13](https://user-images.githubusercontent.com/13135271/48417946-57bbe180-e754-11e8-83b1-38915b53765c.png)

![2018-11-13 14_50_05-haltbarkeit zu kurz - hirzinger robert belegschaft - 13](https://user-images.githubusercontent.com/13135271/48417960-5ee2ef80-e754-11e8-9b7b-b5ddef588002.png)

![2018-11-13 14_50_17-haltbarkeit zu kurz - hirzinger robert belegschaft - 13](https://user-images.githubusercontent.com/13135271/48417963-61dde000-e754-11e8-8f1a-b7e814bd0fa3.png)

**Comment by yurikuzn** [comment]
Hi,

I know about this. No solution for now. You can disable inline edit for the field. See 2nd post: https://forum.espocrm.com/forum/general/30977-remove-edit

**Comment by yurikuzn** [comment]
In 5.5.0 version it will be possible to disable 'inline edit' through Administration > Entity manager.
