### ISSUE TITLE
MassEmail settings not being fully populated from SMTP account

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1119]
Reporting a couple of potential bugs regarding mass emails

1. When I select a mass mail account the `Reply-To` and `Reply-Name` fields are not inherithed from the group email.
2. if `reply-to` and `reply-name` are empty in mass email espo won't use the fields from the group mail settings
3. if a `from-name` is specified for the mass email, it will not override the one in the group mail settings
4. in my tests the `reply-to name` is never sent. don't know if it's my config (hostgator smtp and gmx recipient)
5. in one case the `from-name` itself was never sent (an email campaign with mass email with `from-name` set using an SMTP with `from-name` set). can't reproduce this, tough.
6. in the details view shows the system email smtp instead of the correct one (i don`t know if this is an UI glitch or the actual value was changed).

ps. / 7. can I mark the system smtp as *NOT* usable for mass emails? I would like choose a default SMTP for mass emails, but leaving only one options seems good too.

*Sorry for this mess but I didn't want to spam the issues :)*

**Comment by yurikuzn** [comment]
Hi,

I don't have time now, very busy. Just to inform.

**Comment by yurikuzn** [comment]
6 item will be fixed.

**Comment by beppe9000** [comment]
> Hi,
> 
> I don't have time now, very busy. Just to inform.

Yeah sure, I'm just reporting :)

**Comment by yurikuzn** [comment]
Item 2: https://github.com/espocrm/espocrm/issues/1550

**Comment by yurikuzn** [comment]
Item 3: https://github.com/espocrm/espocrm/issues/1551
