### ISSUE TITLE
Display readable date format according to selected date format.

### ISSUE THREAD

**Issue by miwalter** [espocrm/espocrm#112]
The german dates (dd.mm.yyyy) are not shown correctly in list views and detail views.

E.g. shown is "Okt 02, 2014". It should be "02.10.2014" or "02. Okt. 2014".

**Comment by yurikuzn** [comment]
Not sure about dots. Why not "02 Okt", "02 Okt, 2014"

**Comment by miwalter** [comment]
Fyi: Usually in germany the date format is formatted as "d.m.y" or "d. mmm. y", in PHP you could use:
             $dateText = date("d.m.Y);
or          $dateText = date("d. M. Y);

**Comment by yurikuzn** [comment]
We don't use php for front end. All render in javascript.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/bd4a78467671840150185436c2dc073a2f4b804f
https://github.com/espocrm/espocrm/commit/c306af8b4c0d70baa9e090b66e2766dab6b1e825
