### ISSUE TITLE
Upload multiple documents at once.

### ISSUE THREAD

**Issue by mmuejde** [espocrm/espocrm#1122]

**Comment by mmuejde** [comment]
![screenshot 2018-11-16 at 16 15 39](https://user-images.githubusercontent.com/24757679/48629915-26911a80-e9bb-11e8-89e4-66711ca80049.png)

**Comment by yurikuzn** [comment]
By design document record can have only one file. I'd recommend creating another entity type with attachment multiple field or add another attachment multiple field to Document entity type. Sorry for late reply.
