### ISSUE TITLE
[Advanced Pack] Create a Workflows for Process User Tasks not possible

### ISSUE THREAD

**Issue by deliciousbob** [espocrm/espocrm#1125]
Hallo EspoCRM-Team,

i wanted to start a Workflow every time a Solution is made on a **Process User Task**, but it is not possible to select a Process User Task as an Entity in the Workflow.
Can you please help me with that problem ?

Thank you very much!
Kind regards Robert

**Comment by yurikuzn** [comment]
Hi Robert,

Please use a customer portal for issues related to advanced pack.
