### ISSUE TITLE
Printing to PDF: Ability to loop through link-multiple collection

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1126]
Example, printing contact names and roles of an opportunity:
```
{{#each contacts}}
    Name: {{name}},
    Role: {{opportunityRole}},
    Contact's Account Type: {{account.type}}
{{/each}}
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/fd5dfd769a0af3490a6bfa3d2925bd31baa7f80f

**Comment by emillod** [comment]
@yurikuzn hmm now i find out that, after update i can't generate any PDF files.... Any ideas?
