### ISSUE TITLE
Unchecking "For all team users" in Group Email Account does not revert permissions

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1128]
It leaves team users with all the current emails of the group account in their inbox.

**Comment by yurikuzn** [comment]
It should not revert.

**Comment by beppe9000** [comment]
If that's intentional how do I remove the emails from the team users without deleting them?

**Comment by yurikuzn** [comment]
Such an ability is not available. Maybe will be added in future. Relation is stored in email_user table.

**Comment by beppe9000** [comment]
Thanks, I'll use that.
