### ISSUE TITLE
Tooltips not displaying proper message

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1130]
### Preview
![screenshot from 2018-11-26 15-10-46](https://user-images.githubusercontent.com/12890064/49005853-be49f200-f18d-11e8-9435-0af185e5e594.png)

### Entity Manager
![screenshot from 2018-11-26 15-11-22](https://user-images.githubusercontent.com/12890064/49005861-c43fd300-f18d-11e8-8748-15bfafbee0d0.png)

**Comment by yurikuzn** [comment]
Can't reproduce.

**Comment by karthik-uc** [comment]
I think it's just happening in my office machine. I tried the same in my home and it worked fine. Sorry for the inconvenience.
