### ISSUE TITLE
ERROR: Undefined field $id when field is disabled

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1134]
## Problem code

https://github.com/espocrm/espocrm/blob/5.4.5/application/Espo/Services/Record.php#L332

```php
if ($entity->hasAttribute($nameField) && $entity->hasAttribute($idField)) {
     $id = $entity->get($idField);
}
```

## Error Location

https://github.com/espocrm/espocrm/blob/5.4.5/application/Espo/Services/Record.php#L337

```php
// If above condition fails to execute, Espo.NOTICE: E_NOTICE: Undefined variable: id is thrown
$scope = $defs['entity'];
if (!empty($scope) && $foreignEntity = $this->getEntityManager()->getEntity($scope, $id)) {
    $entity->set($nameField, $foreignEntity->get('name'));
}
```

### Error Log

```json
{
"code":8,
"message":"Undefined variable: id",
"file":"/www/espocrm/application/Espo/Services/Record.php",
"line":337
}
```

## Reason

Because I have disabled account entity and while doing getEntity for lead it fails as there is no attribute called createdAccountId.

## Reproduction of error

- Change espocrm/data/config.php log_level from WARNING to DEBUG
- Disable Accounts in Entity Manager
- Try calling `getEntity` Service for lead.

## Suggested fix

```php
if ($entity->hasAttribute($nameField) && $entity->hasAttribute($idField)) {
     $id = $entity->get($idField);
} else {
     continue;
}
```

**Comment by karthik-uc** [comment]
Same is possible when this is done in `entityDefs.Lead`

```json
"createdOpportunity": {
            "customizationDisabled": true,
            "disabled": true,
            "layoutDetailDisabled": true,
            "layoutMassUpdateDisabled": true,
            "skipOrmDefs": true,
            "type": "link",
            "view": "crm:views/lead/fields/created-opportunity"
}
```

**Comment by yurikuzn** [comment]
Thank you for reporting. Fix: https://github.com/espocrm/espocrm/commit/c0bede16704a4041f7f1e85c2d7e2533a9dfec5d
