### ISSUE TITLE
add a check box to settings to force SSL in the web application

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1137]
I think adding a script (controlled by its own checkbox in settings) to the web app script initialization that redirects to https is a good idea.

**Comment by yurikuzn** [comment]
I don't like the idea. This should be controlled by a server rather then application.

**Comment by bandtank** [comment]
I agree. This is not a good idea for many reasons.

**Comment by beppe9000** [comment]
well then, server side ftw
