### ISSUE TITLE
PDF: improve error handling for Enum fields

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1139]
I put an Enum field in a template like this `Status: {{parent.enumStatus}}`, fetched the pdf and it was and empty page. Nothing found in the logs. I don't know why it crashed.

So there is some issue with enums (removing all enum placeholders let the pdf print), but a more serious problem is that if one placeholder has issues like this the whole pdf generation fails.

**Comment by yurikuzn** [comment]
I can't reproduce.

**Comment by beppe9000** [comment]
My case is a Meeting with a parent of type Lead. The Lead has a custom Enum field setup like this:
![image](https://user-images.githubusercontent.com/6625123/49658304-072d6080-fa42-11e8-990a-4d4e18c4735e.png)

When I put `{{parent.funzione}}` in the template for printing it returns zero size to the http response.

**Comment by beppe9000** [comment]
Ok, let me know what is needed to troubleshoot this when you can.
