### ISSUE TITLE
Address field: Support different formats.

### ISSUE THREAD

**Issue by miwalter** [espocrm/espocrm#114]
The german address field order is usually

"Street"
"Zip" "City"

**Comment by yurikuzn** [comment]
Do you mean both detail and edit view?

**Comment by miwalter** [comment]
Detailview. I tried adding the address-field to the listview: The information is not shown at all, I have to add the single fields (e.g. zip, street, city). Should I open another issue about that?

**Comment by yurikuzn** [comment]
No need to open another.
