### ISSUE TITLE
Issues with upgrade from 5.3.6 to 5.4.5

### ISSUE THREAD

**Issue by emillod** [espocrm/espocrm#1142]
Hello. 
I'm trying to upgrade my ESPO. I was upgrading espo from 5.0.5 version so i already passed upgrades:
EspoCRM-upgrade-5.0.5-to-5.1.2
EspoCRM-upgrade-5.1.2-to-5.2.5
EspoCRM-upgrade-5.2.5-to-5.3.6
And now i have issue with upgrade-5.3.6-to-5.4.5
Everything is ok till i click "upgrade". After that i have just error about issues with rebuilding. I find those errors in log directory:
> [2018-12-11 20:20:41] Espo.ALERT: Rebuild database fault: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1283 Column 'message_id' cannot be part of FULLTEXT index' in /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:699 Stack trace: #0 /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(699): PDO->query('CREATE FULLTEXT...') #1 /home/crm/public_html/application/Espo/Core/Utils/Database/Schema/Schema.php(196): Doctrine\DBAL\Connection->executeQuery('CREATE FULLTEXT...') #2 /home/crm/public_html/application/Espo/Core/DataManager.php(95): Espo\Core\Utils\Database\Schema\Schema->rebuild(NULL) #3 /home/crm/public_html/application/Espo/Core/DataManager.php(62): Espo\Core\DataManager->rebuildDatabase(NULL) #4 /home/crm/public_html/application/Espo/Core/Upgrades/Actions/Base.php(635): Espo\Core\DataManager->rebuild() #5 /home/crm/public_html/application/Espo/Core/Upgrades/Actions/Base/Install.php(95): Espo\Core\Upgrades\Actions\Base->systemRebuild() #6 /home/crm/public_html/application/Espo/Core/Upgrades/ActionManager.php(84): Espo\Core\Upgrades\Actions\Base\Install->run(Array) #7 /home/crm/public_html/application/Espo/Core/Upgrades/Base.php(85): Espo\Core\Upgrades\ActionManager->run(Array) #8 /home/crm/public_html/application/Espo/Controllers/Admin.php(96): Espo\Core\Upgrades\Base->install(Array) #9 /home/crm/public_html/application/Espo/Core/ControllerManager.php(118): Espo\Controllers\Admin->postActionRunUpgrade(Array, Object(stdClass), Object(Slim\Http\Request)) #10 /home/crm/public_html/application/Espo/Core/Application.php(227): Espo\Core\ControllerManager->process('Admin', 'runUpgrade', Array, '{"id":"5c101c00...', Object(Slim\Http\Request)) #11 [internal function]: Espo\Core\Application->Espo\Core\{closure}() #12 /home/crm/public_html/vendor/slim/slim/Slim/Slim.php(1210): call_user_func_array(Object(Closure), Array) #13 /home/crm/public_html/vendor/slim/slim/Slim/Slim.php(1356): Slim\Slim->applyHook('slim.before.dis...') #14 /home/crm/public_html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #15 /home/crm/public_html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #16 /home/crm/public_html/application/Espo/Core/Utils/Api/Auth.php(121): Slim\Middleware\MethodOverride->call() #17 /home/crm/public_html/application/Espo/Core/Utils/Api/Slim.php(125): Espo\Core\Utils\Api\Auth->call() #18 /home/crm/public_html/application/Espo/Core/Application.php(88): Espo\Core\Utils\Api\Slim->run() #19 /home/crm/public_html/api/v1/index.php(33): Espo\Core\Application->run() #20 {main}  Next exception 'Doctrine\DBAL\DBALException' with message 'An exception occurred while executing 'CREATE FULLTEXT INDEX IDX_SYSTEM_FULL_TEXT_SEARCH ON `email` (name, body_plain, from_string, reply_to_string, from_name, message_id, message_id_internal)':  SQLSTATE[HY000]: General error: 1283 Column 'message_id' cannot be part of FULLTEXT index' in /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91 Stack trace: #0 /home/crm/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(702): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(PDOException), 'CREATE FULLTEXT...', Array) #1 /home/crm/public_html/application/Espo/Core/Utils/Database/Schema/Schema.php(196): Doctrine\DBAL\Connection->executeQuery('CREATE FULLTEXT...') #2 /home/crm/public_html/application/Espo/Core/DataManager.php(95): Espo\Core\Utils\Database\Schema\Schema->rebuild(NULL) #3 /home/crm/public_html/application/Espo/Core/DataManager.php(62): Espo\Core\DataManager->rebuildDatabase(NULL) #4 /home/crm/public_html/application/Espo/Core/Upgrades/Actions/Base.php(635): Espo\Core\DataManager->rebuild() #5 /home/crm/public_html/application/Espo/Core/Upgrades/Actions/Base/Install.php(95): Espo\Core\Upgrades\Actions\Base->systemRebuild() #6 /home/crm/public_html/application/Espo/Core/Upgrades/ActionManager.php(84): Espo\Core\Upgrades\Actions\Base\Install->run(Array) #7 /home/crm/public_html/application/Espo/Core/Upgrades/Base.php(85): Espo\Core\Upgrades\ActionManager->run(Array) #8 /home/crm/public_html/application/Esp... [] []
> [2018-12-11 20:20:41] Espo.ERROR: Database rebuild failure, details: Error while rebuilding database. See log file for details.. [] []
> [2018-12-11 20:20:47] Espo.ERROR: API [POST]:/:controller/action/:action, Params:Array (     [controller] => Admin     [action] => runUpgrade ) , InputData: {"id":"5c101c00c9d75"} - Error occurred while EspoCRM rebuild. [] []
> [2018-12-11 20:20:47] Espo.ERROR: Display Error: Error occurred while EspoCRM rebuild., Code: 500 URL: /api/v1/Admin/action/runUpgrade [] []

**Comment by yurikuzn** [comment]
Hi,

What MySQL version do you have?

**Comment by emillod** [comment]
Hi Yuri! Thanks for fast reply! 
In my hosting panel shows version for that database 10.1 but i'm not sure if that's correct

**Comment by yurikuzn** [comment]
Try to disable fulltext for your entity type that have message_id column or remove message field from text filters.

**Comment by yurikuzn** [comment]
We didn't support MariaDB (you have it) before 5.5.0. But I guess problem is not with it.

**Comment by emillod** [comment]
Can you tell me more about solutions? Which will be small demage for my instance? 
How can i remove message field from text filter? I mean, i think that i know how to remove field from text filter, but i don't know which i should remove :)

**Comment by yurikuzn** [comment]
Remove message_id from text filters of Email. custom/Espo/Custom/metadata/entityDefs/Email,json.

You have message_id field in text filters.

**Comment by yurikuzn** [comment]
Or: Administration > Entity Manager > Emails > edit .

**Comment by emillod** [comment]
Hmm after that i'm not able to open any website of CRM.. So i need to restore CRM, right?...

**Comment by yurikuzn** [comment]
1. remove messageId from filters.,
2. run `php rebuild.php`

**Comment by yurikuzn** [comment]
File `custom/Espo/Custom/metadata/entityDefs/Email,json`.
Param `textFilterFields`. You need to remove `messageId`.

**Comment by emillod** [comment]
I already find that in files! And also i already upgraded my espo! I really love your support! THANKS ♥
Can i also have another question about espo? Or i need to create another question?

**Comment by yurikuzn** [comment]
You're welcome.

Better to create another issue or a topic on the forum in the apropriate directory.

**Comment by emillod** [comment]
OK because i just want to know why in one of entities right sidebar is under stream like on the screen.. but maybe it's not urgent.. 
![image](https://user-images.githubusercontent.com/17282191/49830111-88615c00-fd90-11e8-8628-0bb067cc0056.png)

**Comment by emillod** [comment]
@yurikuzn hmm now i find out that, after update i can't generate any PDF files.... Any ideas?
