### ISSUE TITLE
Issue with generating PDF files

### ISSUE THREAD

**Issue by b1f17773** [espocrm/espocrm#1143]
Hello, i don't know why, but after upgrade to the newest version i can't generate PDF files. When i click print to PDF my Espo opening new card and i see just white website. 
I also checked logs but nothing about PDF.. Any ideas why? or how can i debug that problem?

**Comment by yurikuzn** [comment]
Hi,

I have no idea. Here is starting point for debugging: https://github.com/espocrm/espocrm/blob/master/application/Espo/EntryPoints/Pdf.php#L40
