### ISSUE TITLE
Email/Phone field: Audited parameter

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1144]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/419faa2a471cbc3cc4bcb3d2791d168fd34b5c4f

**Comment by rodrigoscoelho** [comment]
I can't add an Telephone field on 5.5.1, it doesn't show as Field Options.

**Comment by yurikuzn** [comment]
Hi Rodrigo,

Phone and Emails fields couldn't be created since we rolled out Entity Manager. 

You can create new entity of Person or Company types that contain the phone field.
