### ISSUE TITLE
Introduce "_setName()" override for middleName as default input to Name for German / Dutch

### ISSUE THREAD

**Issue by tvld** [espocrm/espocrm#1145]
We need to make Espo usefull in Germany & Netherlands with middleName(s). 

Is it enough to add a field "middleName" with Entity Manager in Contact and override the php file ``/application/Espo/Core/Entities/Person.php`` ? (see also [forum](https://forum.espocrm.com/forum/feature-requests/21033-addition-of-middle-name?p=44052#post44052))

```php
namespace Espo\Core\Entities;

class Person extends \Espo\Core\ORM\Entity
{
    public function _setLastName($value)
    {
        $this->setValue('lastName', $value);

        // replacing code to update the name field into one generic function
        _setName();
    }

    public function _setFirstName($value)
    {
        $this->setValue('firstName', $value);

        _setName();
    }

    // new function to set the name based on lastName, firstName and the NEW middleName fields
    public function _setName()
    {
        $firstName = $this->get('firstName');
        // @TODO: should we also test existence of middleName field to avoid errors ???
        $middleName = $this->get('middleName');
        $lastName = $this->get('lastName');

        $name = '';
        if (!empty($firstName)) {
            $name = $firstName . ' ';
        }
        if (!empty($middleName)) {
            $name = $name . $middleName . ' ';
        }
        if (!empty($lastName)) {
            $name = $name . $lastName;
        }

        $name = trim($name);
        $this->setValue('name', $name);
    }
}
```

**Comment by yurikuzn** [comment]
I think you need to override this: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Database/Orm/Fields/PersonName.php#L82

You can create custom class `\Espo\Custom\Core\Utils\Database\Orm\Fields\Person` in `custom/Espo/Custom/Core/Utils/Database/Orm/Fields` directory.

**Comment by tvld** [comment]
So my suggestion won't work?

Because what you are saying is a bit too complex for me with my current knowledge of the system... 

Any other, easier way to get ``firstName + middleName + lastName``  when we need a full name ?

![screenshot from 2018-12-12 21-04-24](https://user-images.githubusercontent.com/986182/49895898-0f2a3d80-fe52-11e8-9ad9-1bd2466dc082.png)

**Comment by rodrigoscoelho** [comment]
We have the same use here on Brazil.

Em qua, 12 de dez de 2018 às 18:08, Tom <notifications@github.com> escreveu:

**Comment by yurikuzn** [comment]
> So my suggestion won't work?

It does not suffice.

1. Add `middle` here: https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/metadata/fields/personName.json#L17
2. Customize entity class name.
3. Customize https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Database/Orm/Fields/PersonName.php#L82

**Comment by beppe9000** [comment]
@yurikuzn if I add `_getName` function to Person the column sorting wouldn't work and contain `None` for all entries. Why is that? Could you link me to `_get` and `_set` documentation ?

**Comment by tvld** [comment]
We tried but due to lack of knowledge we did not dare to change the Espo code itself... 
Still looking for solution for Espo to deal correctly with names in Holland and German...))

**Comment by beppe9000** [comment]
The code in the first post should be good. I did a similar thing with Contacts. In this case the process should be more or less this:
Ensure Person has a `middleName` field.
Then make `\custom\Espo\Custom\Entities\Person.php` with the code from the first post (with minor change):
```
namespace Espo\Custom\Entities;

class Person extends \Espo\Modules\Crm\Entities\Person
{
    public function _setLastName($value)
    {
        $this->setValue('lastName', $value);
        _setName();        // replacing code to update the name field into one generic function
    }

    public function _setFirstName($value)
    {
        $this->setValue('firstName', $value);
        _setName();
    }

    // new function to set the name based on lastName, firstName and the NEW middleName fields
    public function _setName()
    {
        $firstName = $this->get('firstName');
        // @TODO: should we also test existence of middleName field to avoid errors ???
        $middleName = $this->get('middleName');
        $lastName = $this->get('lastName');

        $name = '';
        if (!empty($firstName)) {
            $name = $firstName . ' ';
        }
        if (!empty($middleName)) {
            $name = $name . $middleName . ' ';
        }
        if (!empty($lastName)) {
            $name = $name . $lastName;
        }
        $name = trim($name);
        $this->setValue('name', $name);
    }
}
```
This should work. In my case I had inverted name and surname and ordering wouldn't work. As a workaround I created another field that mirrors the name to be used as sorting column in list view. I don't think this is your case, tough.

**Comment by beppe9000** [comment]
The final `name` is changed only when one of the parts is updated.
`salutationName` is read as a string in my espo... so it should not be a problem.

**Comment by MicKress** [comment]
Hi, I updated the name, but nothing happened. I think perhaps it is a problem with personName.php. I don‘t know how I have to change PersonName.php#L82.

**Comment by MicKress** [comment]
Hi, I changed the mentioned files, but it is not working. PersonName.php, PersonName.json and I defined a custom class. But still „name“ in list or in header is only firstName + lastName. Does anybody has an idea? Regards Michael

**Comment by tvld** [comment]
I gave up myself, limiting the use case of Espo to countries without mandatory middle names... )  

Please realize that my code at the top, was just a guess-timate from my PHP experience but without in-depth knowledge of Espo itself... @yurikuzn comments were appreciated but too cryptic for myself ;)

**Comment by MicKress** [comment]
Hi, so do I. I‘m not very experienced, but the code you posted makes sense for me. EspoCRM is a really great system, but I think for me too complex. I will use it „out of the box“. Thank you.

**Comment by tvld** [comment]
@MicKress Thank you as well...
We also think ESPO is one of the best, if not the best, CRM for us. Despite very few items on our wish-list, we recommend it to everybody !

**Comment by MicKress** [comment]
So think I. Its a really fast and customizable system, I have a lot of respect for yuri and his team ... If I find a solution, I will post it here ...

**Comment by rodrigoscoelho** [comment]
Other problem I'm having related to this is that when adding an user,
coming from an email, espocrm is treating all names as first name and only
the last one as last name.

It should be inverse, at least here on Brazil. All other names besides
first name should be treated as last name.

Enviado utilizando um Galaxy S9...

Em seg, 11 de mar de 2019 07:59, MicKress <notifications@github.com>
escreveu:

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1557
