### ISSUE TITLE
Export/Send email to xslx feature not working in reports

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1149]
I have narrowed to problem down to `Espo\Services\Record::export`

Export to csv is working.

Throws Internal Server Error

**Comment by yurikuzn** [comment]
Please use our forum or custom portal for features of extensions.

**Comment by yurikuzn** [comment]
Do regular export work?

**Comment by karthik-uc** [comment]
Yes, @yurikuzn It is not working. That's why I mentioned that I have narrowed it down to `Espo\Services\Record::export`

**Comment by karthik-uc** [comment]
Well, I worked in standard setup. But in docker setup it wasn't working. Will check and let you know if it's issue from my side

**Comment by karthik-uc** [comment]
I am getting "Error 500" message in UI

This is where i found it was not working, not sure why?
espocrm/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php
```php
$zip->addFromString('[Content_Types].xml', $this->getWriterPart('ContentTypes')->writeContentTypes($this->spreadSheet, $this->includeCharts));
```

Couldn't catch Exception or ErrorException or Error. No logs either.

**Comment by karthik-uc** [comment]
I check php logs and found out that \XMLWriter class was not present. Then I realised that I was not having `php7-xmlwriter` and `php7-xmlreader` modules installed in my docker.

**Comment by yurikuzn** [comment]
Are both libs needed? Or only xmlwriter suffice? I want to add to dependency for installation process but don't want to add excessive libs. Thanks.

**Comment by karthik-uc** [comment]
Let me check and tell you.
