### ISSUE TITLE
3.9.2-to-4.0.0-beta.1 Bitnami stack updater fails

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#115]
Cloud version 3.9.2 installed from 
https://digitalocean.bitnami.com/vms/new?image_id=EToai8E
installs and runs fine.

Upgrading with EspoCRM-upgrade-3.9.2-to-4.0.0-beta.1.zip fails : 

Error: Permission denied for
application/Espo/Core/defaults/layout,
application/Espo/Modules/Crm/Business/CaseDistribution,
client/modules/crm/src/views/dashlets,
client/res/templates/admin/settings,
client/res/templates/dashlets/options,
client/res/templates/notifications,
client/src/views/notifications,
html,
main.html,
api/v1/portal,
application/Espo/Acl,
application/Espo/Controllers,
application/Espo/Core/Acl,
application/Espo/Core,
application/Espo/Entities,
application/Espo/EntryPoints,
application/Espo/Hooks/Common/Notifications.php,
application/Espo/Hooks/Note/Notifications.php,
application/Espo/Jobs/Cleanup.php,
application/Espo/Modules/Crm/Acl,
application/Espo/Modules/Crm/Business/Distribution/CaseObj,
application/Espo/Modules/Crm/Business/Distribution/Lead,
application/Espo/Modules/Crm/Business/Event/Invitations.php,
application/Espo/Modules/Crm/Business/Reminder/EmailReminder.php,
application/Espo/Modules/Crm/Controllers,
application/Espo/Modules/Crm/Entities,
application/Espo/Modules/Crm/EntryPoints,
application/Espo/Modules/Crm/Jobs/ControlKnowledgeBaseArticleStatus.php,
application/Espo/Modules/Crm/Repositories,
application/Espo/Modules/Crm/Resources/i18n/en_US,
application/Espo/Modules/Crm/Resources/i18n/uk_UA/InboundEmail.json,
application/Espo/Modules/Crm/Resources/layouts/Account/filters.json,
application/Espo/Modules/Crm/Resources/layouts/Call/filters.json,
application/Espo/Modules/Crm/Resources/layouts/Case/relationships.json,
application/Espo/Modules/Crm/Resources/layouts/Contact/filters.json,
application/Espo/Modules/Crm/Resources/layouts/Document,
application/Espo/Modules/Crm/Resources/layouts/KnowledgeBaseArticle,
application/Espo/Modules/Crm/Resources/layouts/KnowledgeBaseCategory,
application/Espo/Modules/Crm/Resources/layouts/Meeting/filters.json,
application/Espo/Modules/Crm/Resources/layouts/Opportunity/filters.json,
application/Espo/Modules/Crm/Resources/layouts/TargetList/filters.json,
application/Espo/Modules/Crm/Resources/layouts/Task/filters.json,
application/Espo/Modules/Crm/Resources/metadata/app,
application/Espo/Modules/Crm/Resources/metadata/clientDefs,
application/Espo/Modules/Crm/Resources/metadata/dashlets,
application/Espo/Modules/Crm/Resources/metadata/entityDefs,
application/Espo/Modules/Crm/Resources/metadata/scopes,
application/Espo/Modules/Crm/SelectManagers,
application/Espo/Modules/Crm/Services,
application/Espo/Notificators/Email.php,
application/Espo/ORM/DB,
application/Espo/ORM,
application/Espo/Repositories,
application/Espo/Resources/i18n/en_US,
application/Espo/Resources/i18n/tr_TR/Global.json,
application/Espo/Resources/i18n/uk_UA,
application/Espo/Resources/layouts/Attachment/list.json,
application/Espo/Resources/layouts/Email,
application/Espo/Resources/layouts/Note,
application/Espo/Resources/layouts/Portal,
application/Espo/Resources/layouts/Preferences,
application/Espo/Resources/layouts/Role/detail.json,
application/Espo/Resources/layouts/Settings,
application/Espo/Resources/layouts/User,
application/Espo/Resources/metadata/app,
application/Espo/Resources/metadata/clientDefs,
application/Espo/Resources/metadata/dashlets/Stream.json,
application/Espo/Resources/metadata/entityDefs,
application/Espo/Resources/metadata/fields,
application/Espo/Resources/metadata/scopes,
application/Espo/Resources/metadata/themes,
application/Espo/SelectManagers,
application/Espo/Services,
client/css,
client,
index.php,
install/core/afterInstall/records.php,
reset.html

**Comment by yurikuzn** [comment]
Seems file permissions issue. Change them
