### ISSUE TITLE
Fiscal Year and Quarter filters for opportunity dashles

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1151]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/35076148cc91e5ff4d2ab68f2b03e9b2104b6ead

**Comment by OlofBailey** [comment]
@yurikuzn when trying to apply this within /#Admin/userInterface we get:

"Date From is required" and "Date To is required".
