### ISSUE TITLE
Error attaching images to template & email template

### ISSUE THREAD

**Issue by asfourco** [espocrm/espocrm#1152]
## Issue
I'm getting the following error when inserting images in the template creator page:

Error: Espo.ERROR: Display Error: Field type 'text' is not allowed for Inline Attachment., Code: 500 URL: /api/v1/Attachment 

## Steps to reproduce:
1. Go to templates
2. Click on 'Create template'
3. In the body section, click on the image symbol to attach a picture
4. In the new dialogue click on 'choose image' button and select file

### Result:
In the data/logs/espo*.log the error appears, and sometimes on screen.

See attached animated gif.

![espocrm_attach_picture](https://user-images.githubusercontent.com/2145422/50184022-a0862d80-02f2-11e9-9162-e4fbb2e7747b.gif)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/b333fd677205ae260cee2be09469195102d0c0a6
