### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#117]
The same as in-app notifications.

**Comment by david-strejc** [comment]
Are actually email notifications working?

I've received email test, but I want to receive also deadlines and alerts from Espo CRM.

Is this possible?

**Comment by yurikuzn** [comment]
Out-of-the-box there are email notifications about assignment and mention (new). Also we will add notifications about status updates and posts.

Fore more complex notifications you can use workflow feature. There is an ability to send email upon some condition met or on scheduled basis.

**Comment by rodrigoscoelho** [comment]
Hi Yuri, is that possible to send an email when using the workflow NOTIFY USER feature? It is only notifying, but not sending email.

Are you sure we really have to create a template and ask to SEND an email??? (using advanced package here)

**Comment by rodrigoscoelho** [comment]
Hi Yuri, is this the way it should work?
