### ISSUE TITLE
Search by foreign fields is not working

### ISSUE THREAD

**Issue by barwi** [espocrm/espocrm#1170]
Foreign fields on custom (user created) regular links is not working in search filter. On entity's detail/list view it shows correct foreign data. Using it in filter produces 500 error on server: Mysql Column not found. 

In previous versions it was ok and now in 5.5.1 is broken.
Reproduce:
1) Create new link Opportunity -> User, for example
2) Create new foreign field on Opportunity using this link to user's Title
3) Add this new field to filter list in Opportunity entity layout
4) Use this field to search any Opportunity record with any condition

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/be73390fde142132945a74b0299cf38d505a8798
