### ISSUE TITLE
Type changing from double to integer after saveEntity()

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#1178]
When I save a value using a controller method, which calls the `saveEntity` method of the `EntityManager` class, the value appears to be changing from `double` to `integer. See below:

```
In the controller:
    foreach($inpData->Modified as $row) {
      $td = $em->getEntity('TimesheetData', $row->id);

      $GLOBALS['log']->error('before update',[$td->get("total"), gettype($td->get("total"))], []);
      $this->updateRow($td, $row);
      $GLOBALS['log']->error('after update',[$td->get("total"), gettype($td->get("total"))], []);

      $em->saveEntity($td);
      $GLOBALS['log']->error('after save',[$td->get("total"), gettype($td->get("total"))], []);

      $tx = $em->getEntity('TimesheetData', $td->id);
      $GLOBALS['log']->error('after second fetch',[$td->get("total"), gettype($td->get("total"))], []);

      $tx = $em->getEntity('TimesheetData', $row->id);
      $GLOBALS['log']->error('after third fetch',[$tx->get("total"), gettype($tx->get("total"))], []);
    }
```
```
In the hook:
  public function beforeSave(Entity $en, array $options = array()) {
    $ts = $this->getAndCheckTs($en);

    if($en->isNew()) {
      $this->setupNew($en, $ts);
      $e = $this->checkNewTdSavable($en);
    } else {
      $e = $this->checkExistingTdSavable($en);
      $GLOBALS['log']->error("en final", [$en->get("total")], []);
    }   

    if(count($e)) throw new Error(implode("\n", $e));

    $GLOBALS['log']->error("total value at end of beforeSave hook", [$en->get("total"), "Type = " . gettype($en->get("total"))], []);
  }
```

Here's the log:
```
[2019-01-04 23:05:25] Espo.ERROR: before update [10,"double"] []
[2019-01-04 23:05:25] Espo.ERROR: after update [10.8,"double"] []
[2019-01-04 23:05:25] Espo.ERROR: en final [10.8] []
[2019-01-04 23:05:25] Espo.ERROR: total value at end of beforeSave hook [10.8,"Type = double"] []
[2019-01-04 23:05:25] Espo.ERROR: after save [10,"integer"] []
[2019-01-04 23:05:25] Espo.ERROR: after second fetch [10,"integer"] []
[2019-01-04 23:05:25] Espo.ERROR: after third fetch [10,"double"] []
```

As you can see, the value changed to an `integer` at the end and the value was truncated from `10.8` to `10`. The database field is a double:
```
'total', 'double', 'YES', '', '0', ''
```

Any ideas? The same thing happens if I skip the beforeSave hook entirely. I think it may have something to do with the incoming data being the wrong type (it may be a string in some cases). I tried casting the value to a float, but that didn't seem to help.

**Comment by bandtank** [comment]
I managed to figure out that the end of my comment was correct: the values were being sent as strings instead of doubles. Once I forced the client to send every value as a double (`Number(value)`), it started to work as expected. However, that doesn't make a lot of sense because the values are shown correctly in the log statements. What's going on here?

**Comment by yurikuzn** [comment]
I have no clue why it's happening. Maybe it's how mysql is returning values when the same SELECT query run twice. Sort of caching.

**Comment by yurikuzn** [comment]
Hope this should not be happening now as lot of things were refactored since then.
