### ISSUE TITLE
Two-level menu.

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [espocrm/espocrm#1181]
If it were possible to add items one to another, it would be nice.
And just as it would solve the problem with long names.

**Comment by Pomazan-Bogdan** [comment]
![image](https://user-images.githubusercontent.com/696713/50736385-a8d0da80-11c5-11e9-9461-9aadd4d187c0.png)

**Comment by yurikuzn** [comment]
There's a 3rd party extension: https://treolabs.com/store/espocrm-2-level-navigation.

Two level menu is not planned to be implemented in EspoCRM.
