### ISSUE TITLE
Access to API for reading without authorization

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [espocrm/espocrm#1182]
There is a need to access data without authorization, to read by API
Implement now without a "demo" user with the desired relay is not possible.

**Comment by yurikuzn** [comment]
I don't want having the ability to read data w/o authorization. I suggest using API user (since 5.5.0 version).

**Comment by yurikuzn** [comment]
You can also utilize a custom entry point that allows an access w/o authorization, like https://github.com/espocrm/espocrm/blob/master/application/Espo/EntryPoints/LogoImage.php#L39
