### ISSUE TITLE
Import: Can't specify values for Created By and Created At fields

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [espocrm/espocrm#1183]
subj

![image](https://user-images.githubusercontent.com/696713/50736516-22b59380-11c7-11e9-9cc7-10e2bd5c0e2c.png)

**Comment by yurikuzn** [comment]
I can't reproduce.

**Comment by Pomazan-Bogdan** [comment]
Select 
createdById or createdByName

**Comment by yurikuzn** [comment]
Reproduced. Thanks.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c2c98db80efc8ac6bb40b31a641317c3c08aa669
