### ISSUE TITLE
Relationship select/add buttons missing sometimes

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#1187]
One of my users is not able to see the Select and Add buttons in every relationship panel intermittently. A hard refresh always fixes it and it's only one user who has run into this issue. I have verified the problem in Chrome, Chrome Private, Edge, Edge Private, and I have reset the user's teams/roles/permissions in addition to clearing the browser's cache and the CRM's cache. It is still happening and I can't figure out why.

I have special clientDef JSON definitions for a handful of entities in the relationship panel to hide the select button, but I don't think that's a problem because it works for everyone else. It also works for this user after a hard refresh and the Chrome console doesn't report any errors or issues. I looked in the HTML for the panel and the button is completely gone - the element isn't in the HTML DOM at all until the refresh happens. Then it's where it should be.

See below for the issue. This is after using the CRM for a while:
![screenshot from 2019-01-08 10-51-52](https://user-images.githubusercontent.com/1170415/50849342-fcf9cd00-1333-11e9-821d-153c4950e1bc.png)
and this is after a hard refresh:
![screenshot from 2019-01-08 10-52-16](https://user-images.githubusercontent.com/1170415/50849343-fcf9cd00-1333-11e9-8619-b029b648181e.png)

This is in EspoCRM 5.3.6.

**Comment by yurikuzn** [comment]
Fixed in 5.5.0.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c0719694ba7e24233f97281dd73fa12fd2f5a482#diff-84f124babfad10aae8b31e00f63cc84f

**Comment by bandtank** [comment]
@yurikuzn  Thank you. Sorry - I looked through the release notes for future versions, but I didn't see this commit. I will upgrade as soon as I can.
