### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by goodkiller** [espocrm/espocrm#119]
Hi,

Please add PHP7 support also. In PHP7 are some reserved names like "Bool" and "Int". So we'll get following errors:

Fatal error:  Cannot use 'Bool' as class name as it is reserved in /application/Espo/Core/Utils/Database/DBAL/FieldTypes/Bool.php on line 34
Fatal error:  Cannot use 'Int' as class name as it is reserved in /application/Espo/Core/Utils/Database/DBAL/FieldTypes/Int.php on line 34

Is it possible to fix it ASAP?

**Comment by yurikuzn** [comment]
Try this https://github.com/espocrm/espocrm/commit/6d674c007e124ee3e409ad5a94a987a6798c904e

**Comment by goodkiller** [comment]
Thanks it's helped me a bit but now I'll get another error:

Fatal error:  Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException(
) must be an instance of Exception, instance of Error given in /var/www/vhosts/crm.globalreader.eu/vendor
/monolog/monolog/src/Monolog/ErrorHandler.php:122
Stack trace:
#0 [internal function]: Monolog\ErrorHandler-&gt;handleException(Object(Error))
#1 {main}
  thrown in <b>/var/www/vhosts/crm.globalreader.eu/vendor/monolog/monolog/src/Monolog/ErrorHandler.php on line 122

**Comment by yurikuzn** [comment]
Quick fix in vendor/monolog
https://github.com/Seldaek/monolog/commit/b941eac988decda854947b297c8357c5dac612e8

**Comment by goodkiller** [comment]
Now error dissapeared put POST output is empty: POST /install/index.php 200 OK
Input was: action=buildDatabse

**Comment by yurikuzn** [comment]
One more issue for php7 compatibility: https://github.com/espocrm/espocrm/commit/82162e4fe60854da049985b304f5adf79f2db1a2

Regarding installation it seems not related to php7 since we tested and it worked fine. Maybe some problem with file permissions or server configuration?

**Comment by yurikuzn** [comment]
We tried to install on php 7 and there were no problems. You can check the error log.

**Comment by goodkiller** [comment]
It's fixed for now with 4.0.3 version.

**Comment by tannakartikey** [comment]
@yurikuzn  is it good to use with PHP 7.0 in production?

**Comment by yurikuzn** [comment]
@tannakartikey 
Yes.
