### ISSUE TITLE
ScheduledJob: possibility to run job ad hoc.

### ISSUE THREAD

**Issue by Hofundur** [espocrm/espocrm#1194]
There should be extra button in ScheduledJob named "Run job" with one of two solutions:
- In new view (or small view) should shows all jobs, with buttons "Run once";
- or after clicking that button, should appear dropdown list with all jobs, after clicking one, confirmation dialog should be showned.

New run should me queue into next cron run.

**Comment by yurikuzn** [comment]
Scheduled Job is scheduled. Sorry, I don't want add such a feature.

**Comment by bandtank** [comment]
This would be cool to have, but you can also do it pretty easily via CLI:

Put this file in the root directory of EspoCRM:

```
<?php

include "bootstrap.php";

$options = getopt(null,array("class:"));

$app = new \Espo\Core\Application();
$app->runJob($options['class']);
```

You can call a job with `php runJob.php --class "path\\to\\class\\file.php"`. I do this all the time and it works pretty well. I may have made changes to `application\Espo\Core\Application.php` to support this, but I can't remember off the top of my head.

**Comment by yurikuzn** [comment]
> In all systems ...

Sorry, not an argument for me. It's usual to hear it in feature requests but when I check out other systems, it turns out opposite. EspoCRM is bloated with features, team is not so big to support more and more features.

I suggest your creting custom UI to run your jobs.

**Comment by Hofundur** [comment]
I like your solution, because it is very elastic, but i think there are missing some futures like that. I will try write some code and send you pull request to make it possible.

**Comment by Hofundur** [comment]
@yurikuzn, i won't write public my name, so i cant agree your CLA, so i cant make PR.
Heres a files with solution. I made new item in dropdown item in Job details. I added service, and needed add new column to 'jobs' table to be resist of markJobsFailedByPeriod when job is inactive. What i didnt done, is make messages translable.
If you found it usefull, feel free put it in code.

[runOnce.zip](https://github.com/espocrm/espocrm/files/2752576/runOnce.zip)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1239
