### ISSUE TITLE
Barcode field

### ISSUE THREAD

**Issue by akafester** [espocrm/espocrm#1196]
Support for an entity field that can show a barcode.
For example: https://github.com/lindell/JsBarcode

**Comment by deliciousbob** [comment]
This would be a great extention for the PDF creation module (to Print a Code on Invoices or Orders)

**Comment by hturkoz** [comment]
Hi,
SVG is missing for PDF, then this too is a handlebars-helper-svg requirement for that.
[handlebars-helper-svg](https://github.com/aredridel/npm-handlebars-helper-svg)
👍

**Comment by yurikuzn** [comment]
Handlebars is not used for PDF printing.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/d770dd26e0f00a745eddca504e4ebb80e8cd02ae

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/fe36d049af2f8554f5eff6d31bc6b5fbbb58a43f

**Comment by yurikuzn** [comment]
Documentation: https://github.com/espocrm/documentation/blob/master/administration/fields.md#barcode
