### ISSUE TITLE
vulnerability report contact information

### ISSUE THREAD

**Issue by adamyala** [espocrm/espocrm#1197]
Could a contact medium be added to the README so folks can repot vulnerabilities they might find?

I may have found one and I'd like to disclose it to the maintainers instead listing details in a public issue.

**Comment by yurikuzn** [comment]
Hi Adam,

Could you please contact at https://www.espocrm.com/support/ or use 'leave message' on the website. 

Thanks

**Comment by adamyala** [comment]
Ty @yurikuzn ! I'll draft up a report on how to recreate and send it there.

**Comment by yurikuzn** [comment]
HI @adamyala 

Have you sent a report? We didn't receive. Thanks.
