### ISSUE TITLE
CleanUp Job: remove messages relationships 

### ISSUE THREAD

**Issue by Hofundur** [espocrm/espocrm#1198]
When job cleanup is running, should be more tables purged:
**email_email_address** - should be all rows where email_id = removedEmailID:
```
$sqlDel = "DELETE FROM email_user WHERE email_id = ".$pdo->quote($id);
$pdo->query($sqlDel);
```

or simpler:
$sqlDel = "DELETE FROM email_user WHERE email_id NOT IN ( select * from (
   SELECT id FROM email WHERE deleted = 0) t
   )";
$pdo->query($sqlDel);

**email_address** - should be removed all rows which are not in email_email_address and not in entity_email_address:
$sqlDel = "DELETE FROM email_address WHERE 
id NOT IN ( select * from (SELECT email_address_id  FROM email_email_address  WHERE deleted = 0) t) AND
id NOT IN ( select * from (SELECT email_address_id FROM entity_email_address WHERE deleted = 0) t)";
$pdo->query($sqlDel);

**Comment by yurikuzn** [comment]
I don't think cleaning up email_address is a good idea because one may refer to it somehow in customization.

**Comment by yurikuzn** [comment]
Since then we have Administration > Email Addresses > select *Orphan* filter. This allows removing email addresses not linked with anything.
