### ISSUE TITLE
Portal: Bad server response

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#120]
I tried with upgrade and tried with a fresh 4.00 download but the result is the same "bas server response"
when it came to this link `{site_root}/api/v1/Portal/?maxSize=20&offset=0&sortBy=name&asc=true` some errors occurs:
<hr>
( ! ) Strict standards: Declaration of Espo\Repositories\Portal::afterSave() should be compatible with Espo\Core\ORM\Repositories\RDB::afterSave(Espo\ORM\Entity $entity, array $options = Array) in C:\wamp\www\crm\EspoCRM4\application\Espo\Repositories\Portal.php on line 37
Call Stack
#	Time	Memory	Function	Location
1	0.0005	247088	{main}( )	..\index.php:0
2	0.0056	603800	Espo\Core\Portal\Application->__construct( )	..\index.php:38
3	0.0418	4824864	Espo\ORM\EntityManager->getEntity( )	..\Application.php:48
4	0.0418	4824960	Espo\ORM\EntityManager->getRepository( )	..\EntityManager.php:144
5	0.0418	4825072	Espo\Core\ORM\RepositoryFactory->create( )	..\EntityManager.php:162
6	0.0418	4825176	Espo\ORM\RepositoryFactory->create( )	..\RepositoryFactory.php:38
7	0.0421	4825984	class_exists ( )	..\RepositoryFactory.php:50
8	0.0421	4826320	spl_autoload_call ( )	..\RepositoryFactory.php:50
9	0.0421	4826368	Composer\Autoload\ClassLoader->loadClass( )	..\RepositoryFactory.php:0
10	0.0423	4826504	Composer\Autoload\includeFile( )	..\ClassLoader.php:301
11	0.0425	4838792	include( 'C:\wamp\www\crm\EspoCRM4\application\Espo\Repositories\Portal.php' )	..\ClassLoader.php:412

( ! ) Fatal error: Uncaught exception 'Espo\Core\Exceptions\NotFound' in C:\wamp\www\crm\EspoCRM4\application\Espo\Core\Portal\Application.php on line 51
( ! ) Espo\Core\Exceptions\NotFound: in C:\wamp\www\crm\EspoCRM4\application\Espo\Core\Portal\Application.php on line 51
Call Stack
#	Time	Memory	Function	Location
1	0.0005	247088	{main}( )	..\index.php:0
2	0.0056	603800	Espo\Core\Portal\Application->__construct( )	..\index.php:38

**Comment by yurikuzn** [comment]
You can disable E_STRICT for php error reporting.

**Comment by yurikuzn** [comment]
BTW api url should be {site_root}/api/v1/Portal/{portalId}/...

**Comment by ayman-alkom** [comment]
I made it and the no warning nowm but the  `Fatal error: Uncaught exception 'Espo\Core\Exceptions\NotFound` is still existing

**Comment by ayman-alkom** [comment]
> BTW api url should be {site_root}/api/v1/Portal/{portalId}/...
In fact I took this `{site_root}/api/v1/Portal/?maxSize=20&offset=0&sortBy=name&asc=true`  from the chrome dev tools by following the network section in devtools

**Comment by yurikuzn** [comment]
Something with mod rewrite. Do you use apache server?.

**Comment by ayman-alkom** [comment]
yes I am

**Comment by ayman-alkom** [comment]
`Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12 Server at kobitmobil.com Port 80`

**Comment by 3ruce** [comment]
Same problem here - shared host with Apache

**Comment by yurikuzn** [comment]
Help wanted. Can't reproduce on our servers.

**Comment by 3ruce** [comment]
What kind of help are you thinking of? Log files attached but I don't think there's anything too relevant in there. The large file was due to a permissions error prior to upgrade which once fixed, the upgrade ran smoothly...

[logs.zip](https://github.com/espocrm/espocrm/files/152866/logs.zip)

Do you want ftp access/details of versions of LAMP etc?

**Comment by yurikuzn** [comment]
Can you run portal with url YOUR_ESPOCRM_URL?entryPoint={portalId} ?

**Comment by yurikuzn** [comment]
You also can try this fix: https://github.com/espocrm/espocrm/commit/03454bc30957afa5c5440894100ef757915b9bef

**Comment by 3ruce** [comment]
>Can you run portal with url YOUR_ESPOCRM_URL?entryPoint=portal&id={portalId} ?

Still gives Bad Server Response

**Comment by yurikuzn** [comment]
Did you try the fix from my previous comment?

**Comment by 3ruce** [comment]
not yet - I'll see to ask the website host to change the permissions on the file first - are permissions on that file important btw?

**Comment by yurikuzn** [comment]
Not important.

**Comment by 3ruce** [comment]
ok - thanks - I'll let you know...

**Comment by 3ruce** [comment]
Yeah, that new file has sorted it - I'm in now - thanks!

**Comment by yurikuzn** [comment]
@ayman-alkom , Could you also check it please?

**Comment by ayman-alkom** [comment]
Hi @yurikuzn 
unfortunately it didn't work, I will explain the points:
<hr>

> BTW api url should be {site_root}/api/v1/Portal/{portalId}/...

as I said I picked up my posted url from the devtools of chrome, but I noticed something [here ](https://github.com/espocrm/espocrm/blob/03454bc30957afa5c5440894100ef757915b9bef/application/Espo/Core/Portal/Application.php#L44) 
when I print the value of `$portalId` it is in my case:
```php
    string '?maxSize=20&offset=0&sortBy=name&asc=true' (length=41)
```
yes it seems that the issue is may related to the {portalid} must be passed to the URL as you said.
but I don't have any portal record yet, I even try to access the the index page thet means that there is no portal id yet

when I passed a random portal id empty page came

**Comment by ayman-alkom** [comment]
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught exception 'Espo\Core\Exceptions\Error' with message 'Portal id was not passed to ApplicationPortal.' in C:\wamp\www\crm\application\Espo\Core\Portal\Application.php on line <i>48</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Espo\Core\Exceptions\Error: Portal id was not passed to ApplicationPortal. in C:\wamp\www\crm\application\Espo\Core\Portal\Application.php on line <i>48</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>247504</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp\www\crm\api\v1\portal\index.php' bgcolor='#eeeeec'>..\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0064</td><td bgcolor='#eeeeec' align='right'>604472</td><td bgcolor='#eeeeec'>Espo\Core\Portal\Application->__construct(  )</td><td title='C:\wamp\www\crm\api\v1\portal\index.php' bgcolor='#eeeeec'>..\index.php<b>:</b>38</td></tr>
</table></font>

**Comment by ayman-alkom** [comment]
> Can you run portal with url YOUR_ESPOCRM_URL?entryPoint=portal&id={portalId} ?

404

**Comment by yurikuzn** [comment]
You need to have a portal record, add some portal user to that portal. In portal record you will see the URL how to access the portal. Can you confirm you have it done?

**Comment by ayman-alkom** [comment]
> You need to have a portal record, add some portal user to that portal. In portal record you will see the URL how to access the portal. Can you confirm you have it done?

The question is how to create a portal record if I can't access the portal index page or create page.
I made a new user and checked `is_portal` field, and no portal record created.
I came to the user portal panel where I had to select a portal for this user but the same error 'bad response'

**Comment by yurikuzn** [comment]
Can you access Administration > Portals and create portal there?

**Comment by 3ruce** [comment]
Yeah, you need to make the Portal via the Admin section first

![portals-01](https://cloud.githubusercontent.com/assets/1258786/13459156/02bda3f8-e072-11e5-9fab-40b18d69a71b.png)

Then click create

![portals-02](https://cloud.githubusercontent.com/assets/1258786/13459161/08ebe172-e072-11e5-9ba9-cc642b5af065.png)

Then enter the details you want

![portals-03](https://cloud.githubusercontent.com/assets/1258786/13459166/11470d92-e072-11e5-8096-c36beb404632.png)

**Comment by ayman-alkom** [comment]
> Can you access Administration > Portals and create portal there?
No I can't

**Comment by yurikuzn** [comment]
> No I can't
What error do you see when you open Administration > Portals? Is anything in browser console?

**Comment by ayman-alkom** [comment]
when I go to **Administrator > Portal** it says    `Bad Server response`, the same message when I got to **Administrator > Portal > create**

**Comment by ayman-alkom** [comment]
OK, I noticed something:

when I request `{site_root}/api/v1/Portal` 

1. it is redirect to `{site_root}/api/v1/Portal/` adding **/**
2. so it expects to have a `portalId` forced whereas it empty 

But when I request  `{site_root}/api/v1/Task` for example no redirect happens and the result comes as an array

**Comment by yurikuzn** [comment]
{site_root}/api/v1/Task doesn't matter until we haven't figure out why it doesn't open Administration > Portal. Can you find out what error occurs once you get Bad Server Response?

**Comment by ayman-alkom** [comment]
I rebuilt and the problem is the same.
the errors is:
<table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5">
<span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught exception 'Espo\Core\Exceptions\Error' with message 'Portal id was not passed to ApplicationPortal.' in C:\wamp\www\crm\application\Espo\Core\Portal\Application.php on line <i>48</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Espo\Core\Exceptions\Error: Portal id was not passed to ApplicationPortal. in C:\wamp\www\crm\application\Espo\Core\Portal\Application.php on line <i>48</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>247504</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp\www\crm\api\v1\portal\index.php' bgcolor='#eeeeec'>..\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0064</td><td bgcolor='#eeeeec' align='right'>604472</td><td bgcolor='#eeeeec'>Espo\Core\Portal\Application->__construct(  )</td><td title='C:\wamp\www\crm\api\v1\portal\index.php' bgcolor='#eeeeec'>..\index.php<b>:</b>38</td></tr>
</table>

**Comment by ayman-alkom** [comment]
I tried to explane it but it seems I couldn't 
I tried to say that a **redirect** happens when I request  {site_root}/api/v1/Portal to {site_root}/api/v1/Portal/
but any other request like {site_root}/api/v1/{OtherEntity} not redirects

**Comment by yurikuzn** [comment]
I got confused. v1/Portal/ wedirect won't work properly until you create at least one portal record. If you have no portal record portal should not work. So we need to find out why you can't create Portal record. Administration > Portals. You get Bad Server Response. It means some errors occurs. They should be logged in your apache los.

**Comment by yurikuzn** [comment]
Now i got. It's issue only in wondows. Cased by case insensitivity.

**Comment by ayman-alkom** [comment]
that's good news

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/3460931fba6a02451063cf3018f1e80ef36a81f4
