### ISSUE TITLE
country, city selection from list in accounts and contacts.

### ISSUE THREAD

**Issue by tomaspar** [espocrm/espocrm#1201]
when users are allow to enter country and city (address) as text there are a lot of mistype errors. can you do it dropdown or selector from list?

**Comment by yurikuzn** [comment]
I have one idea. I'll take a look.

**Comment by yurikuzn** [comment]
Will be possible to specify city list manually in data/config.php

```
'addressCityList' => ['London', 'New York'],
```

https://github.com/espocrm/espocrm/commit/783adab8a5642fe22e6d9221d755516562a019c7

**Comment by bandtank** [comment]
Thanks. This will be very helpful. What will happen if an entity has a misspelled address after the change?

**Comment by yurikuzn** [comment]
Nothing. It's a suggestion list. Custom values can be specified.
