### ISSUE TITLE
look for custom defined functions in \Espo\Core\Formula\FunctionFactory::create

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1203]
https://github.com/espocrm/espocrm/blob/117084f8359eeea7432c3d9d58bbbabf256220cb/application/Espo/Core/Formula/FunctionFactory.php#L60-L76

There should be a fallback for custom defined functions i believe either after row 71 or after row 74:
```
if(!class_exists($className))$className='\\Espo\\Custom\\Core\\Formula\\Functions\\'.$name.'Type';
```

**Comment by yurikuzn** [comment]
Custom functioms can be defined in metadata.

**Comment by beppe9000** [comment]
How do I define a function that is in `/custom` ?

**Comment by yurikuzn** [comment]
I updated the documentation. It was badly written. https://github.com/espocrm/documentation/blob/master/development/new-function-in-formula.md

Please let me know if anything in documentation is wrong.

**Comment by beppe9000** [comment]
That explains it! 👍
BTW in the new docs you forgot the `__` at the end of `__APPEND`
