### ISSUE TITLE
Formula: record\exists and record\count

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1204]
`record\count('Opportunity', 'accountId=', id, 'stage=', 'Closed Won')`

`record\count('Opportunity', 'amountConverted>', 1000)`

`record\exists('Lead', 'emailAddress=', fromAddress)`

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/af991b4008122c14ce30542d69de959c0e101d42

**Comment by rodrigoscoelho** [comment]
Great Yuri. You are the best.!!!!
_______________________________________




*Rodrigo Sírio Coelho*

*Engenharia / Aimsun*

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807


Em sex, 18 de jan de 2019 às 09:48, Yuri Kuznetsov <notifications@github.com>
escreveu:

**Comment by rodrigoscoelho** [comment]
Yuri, does these formulas works with FILTER, like the sumrelated and countrelated? Thanks.

**Comment by yurikuzn** [comment]
No, it does not.

**Comment by rodrigoscoelho** [comment]
When using Formula "wizard", these new formulas are not showing as an option.

**Comment by beppe9000** [comment]
> When using Formula "wizard", these new formulas are not showing as an option.

They probably forgot to update the metadata. My 2 cents about it is that in many cases it is probably redundant... the insert template could be moved to the php funtion class, and the function name inferred by the path.

Same for themes and many other things.

**Comment by yurikuzn** [comment]
> It would be great to extend the same PDF Placeholders to Email Templates....
Oh.. no... Sorry. Too much work for me.

**Comment by rodrigoscoelho** [comment]
I have no idea. Just thought that you already wrote a lot of programming lines implementing this for PDF and would be an easier adaptation for email. And I think email is even more important (more used) than PDF.

Common Yuri, you have to clone yourself.... :)

**Comment by yurikuzn** [comment]
No. It can be one more nightmare (what I've been having regularly since 2014). Email Templates will work as they work now. I don't want to touch i.

**Comment by beppe9000** [comment]
Maybe by creating a crash course pages that describe in detail how all of espo's achitecture and internal code work from a technical point of view could enable others to better debug and contribute code. I feel that the developer docs make a lot of assumptions on what we actually know of the code. ;)

**Comment by yurikuzn** [comment]
I literally have no time to do it. But it's possible to comprehend the architecture w/o a documentation just reading the code.

**Comment by beppe9000** [comment]
> I literally have no time to do it. But it's possible to comprehend the architecture w/o a documentation just reading the code.

Maybe it could be crowd-sourced with the wiki pages? They are easy to edit and a mere well-written paragraph on each a core concept may save newbies a lot of time that is lost by trying to figure out how everything works (front end comes to mind). Anyways it's something that will eventually occur by itself once a lot of people start using espo... 👍

**Comment by yurikuzn** [comment]
I don't belive that crowd-sourced concept will work at this moment. Community is not big enough . It's on github https://github.com/espocrm/documentation/blob/master/development/metadata.md so everybody can PR.

**Comment by beppe9000** [comment]
I see. The wiki pages feature of github makes it easier to contribute rather than a PR I think, so maybe a wise move could be to switch to wiki for the docsumentation.

**Comment by bandtank** [comment]
I would be more likely to contribute to the wiki than a PR as well. PRs are more effort for contributors and Espo maintainers I think.
