### ISSUE TITLE
Formula: custom directory

### ISSUE THREAD

**Issue by hturkoz** [espocrm/espocrm#1213]
Dear Yuri and EspoCrm teams,

a must have core formula is NumericVal :  return preg_replace("/[^0-9]/", "", $value); 
but, in the documentation I have found (I think with my skill) some mistake : 

why new formula must be in core directory and not in custom ? 
the custom formula.json must be : 
`
{
	"functionList": [ 
		"__APPEND__",
        {
            "name": "string\\numericVal",
            "insertText": "string\\numericVal(STRING)"
        }
    ]
}
`
otherwise we loose all core formula. 
the important key is "__APPEND__"  and it's not specified in documentation.
maybe I am wrong, it's my skill so, my apologies :)

Regards

**Comment by yurikuzn** [comment]
Hi,

That's not the latest doc. See updated https://github.com/espocrm/documentation/blob/master/development/new-function-in-formula.md

**Comment by rodrigoscoelho** [comment]
Can you share this formula with espocrm?
Maybe Yuri can merge it on the master.

Thanks

Enviado utilizando um Galaxy S9...

Em dom, 27 de jan de 2019 20:01, Hanefi Turkoz <notifications@github.com
escreveu:

**Comment by hturkoz** [comment]
Hi, 
it's really simple, just follow any formula and documentation and return the function :  return preg_replace( $pattern , $replacement, $string);

`
<?php
/************************************************************************
 * This file is part of EspoCRM.
 *
 * EspoCRM - Open Source CRM application.
 * Copyright (C) 2014-2018 Yuri Kuznetsov, Taras Machyshyn, Oleksiy Avramenko
 * Website: http://www.espocrm.com
 *
 * EspoCRM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * EspoCRM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with EspoCRM. If not, see http://www.gnu.org/licenses/.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "EspoCRM" word.
 ************************************************************************/

namespace Espo\Custom\Core\Formula\Functions\StringGroup;

use \Espo\Core\Exceptions\Error;

class PregReplace extends \Espo\Core\Formula\Functions\Base
{
    public function process(\StdClass $item)
    {
        if (!property_exists($item, 'value')) {
            throw new Error();
        }
        
        if (!is_array($item->value)) {
            throw new Error();
        }
        
        if (count($item->value) < 2) {
            throw new Error();
        }
        
        $pattern = $this->evaluate($item->value[0]);
        $replacement = $this->evaluate($item->value[1]);
        $string = $this->evaluate($item->value[2]);
        // "/[^0-9]/"
        return preg_replace( $pattern , $replacement, $string);
    }
}

`

`
{
	"functionList": [ 
		"__APPEND__",
        {
            "name": "string\\pregReplace",
            "insertText": "string\\pregReplace(PATTERN, REPLACEMENT, STRING)"
        }
    ],
    "functionClassNameMap": {
        "string\\pregReplace": "\\Espo\\Custom\\Core\\Formula\\Functions\\StringGroup\\PregReplace"
    }
}
`

**Comment by rodrigoscoelho** [comment]
where did you publish it?

Thanks
