### ISSUE TITLE
Fix calendar title on Persian language

### ISSUE THREAD

**Issue by SaeedHashemi** [espocrm/espocrm#1214]
Please change this scope 
`"lists": {
    "dayNames": [
      "یکشنبه",
      "دوشنبه",
      "سه شنبه",
      "چهارشنبه",
      " پنجشنبه",
      "جمعه شنبه"
    ],
    "dayNamesShort": [
      "یکشنبه",
      "دوشنبه",
      "سه شنبه",
      "چهارشنبه",
      " پنجشنبه",
      "جمعه شنبه"
    ],
    "dayNamesMin": [
      "یکشنبه",
      "دوشنبه",
      "سه شنبه",
      "چهارشنبه",
      " پنجشنبه",
      "جمعه شنبه"
    ]
  }`
to 
`"lists": {
    "dayNames": [
      "یکشنبه",
      "دوشنبه",
      "سه شنبه",
      "چهارشنبه",
      " پنجشنبه",
      "جمعه",
      "شنبه"
    ],
    "dayNamesShort": [
      "یکشنبه",
      "دوشنبه",
      "سه شنبه",
      "چهارشنبه",
      " پنجشنبه",
      "جمعه",
      "شنبه"
    ],
    "dayNamesMin": [
      "یکشنبه",
      "دوشنبه",
      "سه شنبه",
      "چهارشنبه",
      " پنجشنبه",
      "جمعه",
      "شنبه"
    ]
  }`

on this address [espocrm/application/Espo/Resources/i18n/fa_IR/Global.json](url)

**Comment by yurikuzn** [comment]
Thanks, 

Should I fix

BTW you can modify language at https://poeditor.com/projects/po_edit?id_language=126&id=58283

**Comment by SaeedHashemi** [comment]
Thanks,
I fixed it, on page [espocrm/application/Espo/Resources/i18n/fa_IR/Global.json](url)
