### ISSUE TITLE
IFrame with variable being passed from Account/Contact

### ISSUE THREAD

**Issue by OlofBailey** [espocrm/espocrm#1219]
Feature request:

Its been in Sugar since day dot and used by many people to surface contextual data within CRM pages. 

For example we store our accounts system Account_ID as a variable within each account. This is passed to a dashlet within the account view page which then presents order history, status etc. It's the quickest way of integrating various systems.

**Comment by yurikuzn** [comment]
The idea seems to be reasonable. But I'm not sure that integrating system in such a way is good. Everybody who know the URL would be able to access data.

Now, it's relatively easy to create a custom panel will very little JS code and JSON metadata.
