### ISSUE TITLE
Cases: Knowledge base case emails not copying body

### ISSUE THREAD

**Issue by tonybyng** [espocrm/espocrm#1223]
Hi

If I am handling a case and I realise the answer is in a knowledgebase article, I can find the knowledgebase article at the bottom of the case screen and choose the "Send in Email" option. This creates a new email for the case and fills in the subject line based on the knowledgebase article name but the body content does not come across. I assume it's meant to ? To remove the possibility of it being some issue on my installation (which I thought it might be), I've confirmed it happens on the espocrm demo online too

To reproduce, go to http://demo.espocrm.de/advanced/#Case/view/53203b9428fe4 and you will see a knowledgebase article linked to the case. Choose the "Send in Email" dropdown and a new email will start without the content from the article. (not sure how quick your demo data is wiped tho!)

Tony

**Comment by yurikuzn** [comment]
Hi Tony,

Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/e48fa00893de0cf87d9a988011a9ebad7d175da6
