### ISSUE TITLE
$field name is Array in \Espo\Modules\Advanced\Core\Workflow\Utils::getFieldType 

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1224]
No idea why, but I get this in one of my workflows.
$fieldName = Array (     [0] => parentId     [1] => parentType )

`Espo.WARNING: E_WARNING: Illegal offset type in isset or empty {"code":2,"message":"Illegal offset type in isset or empty","file":"/home3/r7t8n3t0/public_html/crm/VDF/application/Espo/Modules/Advanced/Core/Workflow/Utils.php","line":315,"context":{"entity":"[...`

**Comment by yurikuzn** [comment]
Please use our forum or customer portal for issues related to extensions.

**Comment by beppe9000** [comment]
ok
