### ISSUE TITLE
Unable to load a vendor library for custom module

### ISSUE THREAD

**Issue by arkadywtf** [espocrm/espocrm#1225]
I've installed [ramsey/uuid](https://github.com/ramsey/uuid) in my custom module path. When I try to use the package
```php
use Ramsey\Uuid\Uuid;
```
I get an error `Espo.ERROR: Uncaught Exception Error: "Class 'Ramsey\Uuid\Uuid' not found"`

Here's my `autoload.json` file

```json
{
    "Ramsey\\Uuid\\": "application/Espo/Modules/MyModule/vendor/ramsey/uuid/src"
}
```

What am I doing wrong?

**Comment by bandtank** [comment]
Did you clear the cache?

**Comment by yurikuzn** [comment]
Maybe you should try

"RamseyUuid": : "application/Espo/Modules/MyModule/vendor/ramsey/uuid/src"

I'm surprised that we have an ability to define custom vendor in modules. I forgot. Cool.

**Comment by arkadywtf** [comment]
@bandtank hey, yes I did. I've run it through xDebug and it seems the method `initAutoloads()` is actually loading the file. That is why I am thinking maybe I incorrectly referencing my package.

@yurikuzn thanks, I will try that and let you know.

**Comment by yurikuzn** [comment]
We're going to add this format supported:

{
    "psr-4": {
          "Ramsey\\Uuid\\": "application/Espo/Modules/MyModule/vendor/ramsey/uuid/src"
    }
}

**Comment by arkadywtf** [comment]
Wow, that's great! I'm looking forward then for future releases.

**Comment by yurikuzn** [comment]
Already implemen
