### ISSUE TITLE
JS/CoinMiner.AH issue

### ISSUE THREAD

**Issue by SaeedHashemi** [espocrm/espocrm#1233]
Hi, ESET smart security show this alert
[https://cdn.pbrd.co/images/I0VuZK9.jpg?o=1](url)

![coinminer](https://user-images.githubusercontent.com/2914999/52689993-75762e00-2f71-11e9-8405-8a86d4c7390a.JPG)

JS/CoinMiner.AH

how can I remove this Trojan from this crm scripts!!!??

**Comment by yurikuzn** [comment]
Hi,

I think EspoCRM has nothing to this issue.

**Comment by SaeedHashemi** [comment]
But ESET alert frequently for this page and URLs

**Comment by SaeedHashemi** [comment]
![coinminer](https://user-images.githubusercontent.com/2914999/52694241-431efd80-2f7e-11e9-999e-6889298bf6c7.JPG)

when refresh home page occurs this issue

**Comment by SaeedHashemi** [comment]
![coinminer](https://user-images.githubusercontent.com/2914999/52694378-c2143600-2f7e-11e9-815c-1af8ba2e3f1f.JPG)

**Comment by SaeedHashemi** [comment]
![coinminer](https://user-images.githubusercontent.com/2914999/52695026-aa3db180-2f80-11e9-9776-abb6821cd0bd.JPG)

**Comment by SaeedHashemi** [comment]
![coinminer](https://user-images.githubusercontent.com/2914999/52695169-0accee80-2f81-11e9-90ad-c228cb117e5e.JPG)

**Comment by SaeedHashemi** [comment]
![coinminer](https://user-images.githubusercontent.com/2914999/52695375-96467f80-2f81-11e9-842e-79a3b3422c02.JPG)

here is response of this URL,

**Comment by SaeedHashemi** [comment]
Please find and remove this coin mining Trojan from source of ESPO CRM

**Comment by yurikuzn** [comment]
Are you sure the trojan is in EspoCRM source? It's a quite serious allegation. Why do you think it's in EspoCRM source rather that only on your server?

**Comment by SaeedHashemi** [comment]
Yes, I'm sure, because there are more than 50 websites on the server, and this website only has this problem
After loading the page, this address wastes from the outside and adds to the website
Using the hardware resources of others to earn money is a non-professional principle

**Comment by yurikuzn** [comment]
Can you please point out me to the trojan in our sources? I can't find it.

**Comment by SaeedHashemi** [comment]
![coinminer](https://user-images.githubusercontent.com/2914999/52696409-38fffd80-2f84-11e9-9eed-a8acb6c83357.JPG)

You can see here

**Comment by SaeedHashemi** [comment]
![52695169-0accee80-2f81-11e9-90ad-c228cb117e5e](https://user-images.githubusercontent.com/2914999/52696462-5765f900-2f84-11e9-8761-32830f6ec610.jpg)
and here

**Comment by yurikuzn** [comment]
It's files on your server. It's not the source code.

**Comment by yurikuzn** [comment]
Where did you get EspoCRM source?

**Comment by SaeedHashemi** [comment]
![52695169-0accee80-2f81-11e9-90ad-c228cb117e5e](https://user-images.githubusercontent.com/2914999/52696647-bfb4da80-2f84-11e9-8480-c5a206eb6096.jpg)

you can see here too

**Comment by yurikuzn** [comment]
I think your server is affected rather then our source code.

**Comment by SaeedHashemi** [comment]
![ssl](https://user-images.githubusercontent.com/2914999/52696805-2e923380-2f85-11e9-9fcd-27bc2d7975cd.JPG)

Also you can see here too, I downloaded the source from you official web site [https://espocrm.com](url)

**Comment by yurikuzn** [comment]
You accusing us having a trojan w/o any viable evidence. I think you have a virus on your server. Please investigate it deeply. I have no time for it. Sorry.

**Comment by SaeedHashemi** [comment]
![ssl](https://user-images.githubusercontent.com/2914999/52698273-68186e00-2f88-11e9-850c-602395350c51.JPG)

**Comment by SaeedHashemi** [comment]
![ssl](https://user-images.githubusercontent.com/2914999/52698776-76b35500-2f89-11e9-9dd1-b192f4b51dd7.JPG)

**Comment by SaeedHashemi** [comment]
I found the problem!!
On server installed NOIP application, this was my problem.
I apologize for the misconception.

**Comment by rodrigoscoelho** [comment]
I have espocrm since 2016 and never was detected virus here.

Probably local virus.

Enviado utilizando um Galaxy S9...

Em qua, 13 de fev de 2019 06:48, Saeed Hashemi <notifications@github.com>
escreveu:

**Comment by SaeedHashemi** [comment]
Yes, I found problem, On server exist NOIP App, I scanned fully with ESET on server
Also I apologize for the misconception.
And thank you for your response.

**Comment by yurikuzn** [comment]
No problem.
