### ISSUE TITLE
Console: Ability to run specific job

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1239]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/dcbdf94023f538d7536ec2765eb2512ec46947fc

**Comment by bandtank** [comment]
Love it. This is huge.

**Comment by rodrigoscoelho** [comment]
Yes, great.
And even better to know that Yuri is listening the users!. 😀
_______________________________________




*Rodrigo Sírio Coelho*

*Engenharia / Aimsun*

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807


Em sex, 15 de fev de 2019 às 11:28, Anthony Andriano <
notifications@github.com> escreveu:
