### ISSUE TITLE
Multi-Enum: 'Display as Label' param and option colors

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1240]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/68dfa92425f49e52bdd8f49ad18e1f731a736712

**Comment by bandtank** [comment]
Does this only apply to multi-enums or will enums also be able to use colors/styles?

**Comment by rodrigoscoelho** [comment]
I have an idea.

Why not changing the PANEL color/type (Important, info, etc) based on a
condition.
Like, if the bill is due, the PANEL type is DANGER. If is ok, NORMAL.

What do you think Yuri?


_______________________________________




*Rodrigo Sírio Coelho*

*Engenharia / Aimsun*

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807


Em sex, 15 de fev de 2019 às 12:18, Anthony Andriano <
notifications@github.com> escreveu:

**Comment by yurikuzn** [comment]
> Does this only apply to multi-enums or will enums also be able to use colors/styles?
For enums it done since 5.5 version.

**Comment by bandtank** [comment]
I missed the memo. Sorry and thanks!
