### ISSUE TITLE
Ability to disable/enable open tracking in mass email

### ISSUE THREAD

**Issue by synnack** [espocrm/espocrm#1241]
Tracking URLs is illegal without explicit consent in the EU. Please disable this by default or at least give an option to disable it.

**Comment by synnack** [comment]
This piece of code is relevant.
The campaign Id is checked twice for some reason, and tracking is *ALWAYS* added, even though it's illegal to do so in Europe.

File application/Espo/Modules/Crm/Services/MassEmail.php, around line 387:
~~~
        if ($massEmail->get('campaignId')) {
            if ($emailData['isHtml']) {
                if ($massEmail->get('campaignId')) {
                    $body .= '<br>' . $trackOpenedHtml;
                }
            }
        }
~~~

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/41a3e7eaa3a845ca22c39f62349e3ce04c8928a5
