### ISSUE TITLE
IMAP 2-way sync of more folders than inbox

### ISSUE THREAD

**Issue by kuttnerd** [espocrm/espocrm#1242]
As a normal user, I want to have sent mails in sync, too so that the whole communication is available in espoCRM.

For keeping the communication (inbox+sent, ideally archived and deleted, too) in espoCRM visible, it would be great if there may be a 2-way sync of mails (personal and group mailboxes), so that sent mails via mailclients would also be visible in the cases or mailbox in espoCRM. Is this feature planned or not relevant?

**Comment by yurikuzn** [comment]
What prevents from syncing sent folder now?

**Comment by kuttnerd** [comment]
Yes, the "sent"-folder gets synced but the sent messages land in the inbox, which is a bit confusing. settings (personal mailbox in espocrm) are like following:
![image](https://user-images.githubusercontent.com/8133239/52902716-f012a800-3214-11e9-972c-990af2f0799b.png)
Is there a way to adjust the config/mail-routing in espocrm? btw many thx for your blazing fast responses and sorry for bothering you @yurikuzn > next time forum first

**Comment by yurikuzn** [comment]
I think emails from IMAP Sent folder fall into EspoCRM Inbox folder because FROM email address doesn't match with any of email addresses of your User record. If you add that email address to your email address list (Email field of User record) it should work.

**Comment by kuttnerd** [comment]
aww right, great! many thx for the hint, i thought that this has been set.

**Comment by kuttnerd** [comment]
once again just a short follow-up to this issue:
is it on purpose that the status of mails doesn't get synced? i.e. mails have been moved to trash or flagged as important. If a mail has been deleted in the IMAP mailbox/espocrm, it's not deleted on the other platform/vice versa.

**Comment by yurikuzn** [comment]
Yes. Folders in EspoCRM has nothing to IMAP folders. EspoCRM doesn't have IMAP client.
