### ISSUE TITLE
Group Email Account: 'Keep Fetched Emails Unseen' parameter

### ISSUE THREAD

**Issue by rsolvang** [espocrm/espocrm#1243]
On shared email accounts, emails are marked as read on the IMAP server when they are fetched by EspoCRM. On personal email accounts there is an option to "Show fetched emails as unread" – which works great. This option is missing on the shared email accounts.

The problem this causes is that I do not receive notifications from the email client on my phone, as all new emails are marked as read by EspoCRM as soon as they are fetched. It would be great if the option "Show fetched emails as unread" would be available also for shared email accounts!

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/a59825a79bb18e2fad01988f020387843b864612

**Comment by rsolvang** [comment]
Great, that was fast!
