### ISSUE TITLE
Password change allowed for non-admin users if LDAP auth is used

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#1245]
If a user has been created / authenticated against LDAP it should be possible to change the password thru the Espo UI or at least the password change dialog should be disabled for users authenticated by LDAP.
At the moment an LDAP authenticated user can change it's (internal stored) password which will have no effect.

**Comment by yurikuzn** [comment]
Thanks. Done: https://github.com/espocrm/espocrm/commit/cca4aa7f6f823381c341d51eea40c7db9943bf77
