### ISSUE TITLE
use guid instead of custom generateId

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#125]
At the moment the id is a varchar(24) and generated by code:
`Util.php:    public static function generateId()`
This makes it very hard for integration scenarios direcly on db level like complex imports or the coexistense with other applications sharing the same db schema.
using GUIDs (varchar(32)/com_create_guid) for the id would solve the issue.

**Comment by yurikuzn** [comment]
You can just increase lengths of  id columns in db.
