### ISSUE TITLE
Ability to add custom key value pairs into espocrm/data/config.php from UI

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1253]
This is needed because sometime we need to add our own keys to config when integrating with some third parties and would be great if we could add this feature.

Most of the users/admins will not have access to backend or terminal to modify config.php and it's also error prone when someone does change config.php using text editors.

**Comment by yurikuzn** [comment]
One more way to break the application and more requests for help to us. Not sure.

You can create a field for settings entity type manually and put it on the layout.
