### ISSUE TITLE
Search by phone in Global search

### ISSUE THREAD

**Issue by Cri00** [espocrm/espocrm#1255]
Hello!

It will be a great feature for increasing productivity and customer care if the global search could also search by phone number.

Thanks!

**Comment by yurikuzn** [comment]
Hi,

Actually it's supposed to be able to search. 

https://github.com/espocrm/documentation/blob/master/user-guide/text-search.md#global-search

Administration > Entity Manager > Edit specific entity type > Text Filter Fields.

**Comment by Cri00** [comment]
You are right. Thank you very much!
