### ISSUE TITLE
Console: Upgrade command

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1256]
Automatically upgrades EspoCRM to the next available version.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/e38f967b1b4b91cc4791a8147d93ccce1ea0592c

**Comment by bandtank** [comment]
Cool. This is interesting. What happens if you decide to rollback?

**Comment by yurikuzn** [comment]
User will need to confirm before upgrade starts. There is no way to rollback after upgrade is done. And never was.
