### ISSUE TITLE
Document viewer

### ISSUE THREAD

**Issue by jaime-ez** [espocrm/espocrm#126]
Guys, congratulations, looks like a great CRM.
But I think it needs a document viewer for attachments. Any plan to include one or some advice on where to tackle that problem and start contributing?
Thanks

**Comment by yurikuzn** [comment]
Hi

We thought about it but didn't planned. Actually it doesn't looks as an easy thing to do.

**Comment by Whrealty** [comment]
i am working to implement this
https://mozilla.github.io/pdf.js/

**Comment by yurikuzn** [comment]
Nice lib. I will take a look as well. Thanks.

**Comment by ayman-alkom** [comment]
Hi @yurikuzn 
I found a simple solution, look at @ http://officewebviewer.com/ it is as simple as generate a link to open the document
some link like this:
https://view.officeapps.live.com/op/view.aspx?src=somelink

I tried with the download link but it didn't worked, it's something related to the headers maybe but I am not sure.

I test to host my file on the disk where as it has a link and worked fine

whats do you think about it

**Comment by ayman-alkom** [comment]
Hi @yurikuzn , I didn't hear from you

**Comment by yurikuzn** [comment]
I couldn't sort out. Can you describe how this could be integrated with EspoCRM?

**Comment by ayman-alkom** [comment]
We can binifit from  **officewebviewer** by the following:

- in the document view page we will add a link named 'Explore Online' for example
- this link is formatted as this: https://view.officeapps.live.com/op/view.aspx?src=`my-doc-link`

I tested it by using the download link that is available already in the espocrm, but didnt worked.
the solution is to provide a link that contain the extention

**Comment by rodrigoscoelho** [comment]
Great idea.

Email enviado usando um celular....

Em 15/08/2016 13:19, "Ayman Alkom" <notifications@github.com> escreveu:

**Comment by yurikuzn** [comment]
How this can be automated? How crm will upload file to the service?

We'd like to rely on 3rd servicse as little as possible in EspoCRM out-of-the-box.

**Comment by ayman-alkom** [comment]
no need to upload the document to the sevice, just provide a link to the espocrm document.

As a test I hosted the uploaded document on my server and simply called the service URL suffixed with the document link

They use the CURL or somthing like it

**Comment by ayman-alkom** [comment]
for example we have this link 
http://www.myserver.com?entryPoint=download&id=57736e91010244bbc

we just need it as the following:

http://www.myserver.com/download/57736e91010244bbc.docx

**Comment by yurikuzn** [comment]
Document is not available for world w/o username and password (basic authorization).

**Comment by ayman-alkom** [comment]
this will be opened in the same window, and the credentials are available

**Comment by ayman-alkom** [comment]
for sharing it I think that we may provide a token for every document, that may works instead of auth maybe.
just an idea

**Comment by yurikuzn** [comment]
Maybe. We must think about it.

**Comment by nishan56838** [comment]
@yurikuzn  any workaround on this Document viewer option. I think this is very useful function. Please have look into this.
