### ISSUE TITLE
Export PDF

### ISSUE THREAD

**Issue by gundogduyakici** [espocrm/espocrm#1265]
I can export the list in xls and csv format. But I want to get export as Pdf. This is a shortcoming.
Can we produce a solution for this ?

**Comment by yurikuzn** [comment]
No, We have an extremely lot of work to do. Maybe someone could develop an extension?

**Comment by gundogduyakici** [comment]
I'm working on that right now. I'll give it to you when it's over.

**Comment by yurikuzn** [comment]
You can do it as an extension (free or paid).

**Comment by yurikuzn** [comment]
I believe an additional export type can be added w/o modifying any existing espocrm file.

**Comment by gundogduyakici** [comment]
Okay, Can you give me a hint about this ?

**Comment by yurikuzn** [comment]
Sorry, I'm too busy.

**Comment by gundogduyakici** [comment]
Okay @yurikuzn, I will inform you.

**Comment by gundogduyakici** [comment]
Hi @yurikuzn,
It ends in a few days. Should I share it as a module or how ?

**Comment by yurikuzn** [comment]
Hi,

As you wish. You could publish it on github if you like.

**Comment by gundogduyakici** [comment]
I've sent the files to PDF export. Please check.

**Comment by gundogduyakici** [comment]
I've sent the files to PDF export. Please check.

Image: [https://i.ibb.co/CsbynNR/pdf-fw.png](url)

**Comment by gundogduyakici** [comment]
I've sent the files to PDF export. Please check.

Image: https://i.ibb.co/CsbynNR/pdf-fw.png

**Comment by o-data** [comment]
Hi Yuri, just browsing through old issue. Is there a reason why the Pull Request doesn't get review/accepted?

#1266

**Comment by yurikuzn** [comment]
From the user perspective it may seem that we should accept everything, from the developer perspective it's not so,
