### ISSUE TITLE
Feature request: search for existing duplicates

### ISSUE THREAD

**Issue by OlofBailey** [espocrm/espocrm#1272]
Ability to run the same duplicate logic on the existing data and then merge detected duplicate accounts or contacts etc. Could be a reporting function.
If everyones data is like ours every day duplicates are created due to careless users and administrators need a way of periodically cleansing the data.

**Comment by yurikuzn** [comment]
Unfortunately, using the same logic as for create/edit is not possible by design.

JFI, one can utilize a report tool from the advanced pack for duplicate searching. See an example on our live [demo](https://www.espocrm.com/demo/): Reports > Duplicates.
