### ISSUE TITLE
EspoCRM doesn't work with Caddy

### ISSUE THREAD

**Issue by whalehub** [espocrm/espocrm#1274]
I'm using the webserver/reverse proxy Caddy and can't seem to get EspoCRM to work with it. After setting up the connection to MySQL and confirming that all components are available and all permissions are correct, I get the following error message:

```
API Error: EspoCRM API is unavailable.
Possible problem: disabled Rewrite Module. Please check and enable Rewrite Module in your server (e.g. mod_rewrite in Apache) and .htaccess support.
```

![chrome_2019-03-16_13-18-00](https://user-images.githubusercontent.com/44198148/54475125-fed98400-47ed-11e9-8e51-f82cf9eeee4a.png)

**Comment by whalehub** [comment]
@mholt Is there an equivalent to Apache's rewrite module in Caddy?

**Comment by mholt** [comment]
Yes: https://caddyserver.com/docs/rewrite

**Comment by gundogduyakici** [comment]
Problem not EspoCRM, your server. Please ask forums such as Stackoverflow. @whalehub

**Comment by yurikuzn** [comment]
I have never tried to EspoCRM on Caddy, so can't help. Any success?

**Comment by whalehub** [comment]
I opted to use EspoCRM within a Docker container instead.

**Comment by eymen-elkum** [comment]
Hello guys, I managed to run EspoCRM on Caddy and here is the config:

```
# extension.host
extension.host {
    encode zstd gzip
    import set-log extension.host

    tls "/Applications/ServBay/ssl/private/tls-certs/extension.host/extension.host.crt" "/Applications/ServBay/ssl/private/tls-certs/extension.host/extension.host.key"

    import canonical-path

    handle_path /client* {
        root * /Users/eymenelkum/Work/CRMProjects/crm-extensions/client
    }

    handle_path /api/v1/* {
        try_files {path} /api/v1/index.php
    }

    handle_path /portal/* {
        try_files {path} {path}/ /portal/index.php?{query}
    }

    handle_path /api/v1/portal-access/* {
        try_files {path} /api/v1/portal-access/index.php
    }

    root * "/Users/eymenelkum/Work/CRMProjects/crm-extensions/public"

    route {
        import php-rewrite-default 8.2
    }

    file_server
}

```
