### ISSUE TITLE
Typo in variable name in LeastBusy class

### ISSUE THREAD

**Issue by MaMuk** [espocrm/espocrm#1276]
Just a quick heads up. I have found two typos, while glancing over the code:
the files are: 

- application/Espo/Modules/Crm/Business/Distribution/CaseObj/LeastBusy.php
- application/Espo/Modules/Crm/Business/Distribution/Lead/LeastBusy.php

Line 79 and Line 80 respectively
`$min = $clunt;`
Both should be
`$min = $count;`

Found in 5.5.6

**Comment by yurikuzn** [comment]
Thankshttps://github.com/espocrm/espocrm/commit/c923134b972c2793ff289ea73432f09e83cbea33
