### ISSUE TITLE
Stored XSS vulnerabilities in EspoCRM 5.5.6

### ISSUE THREAD

**Issue by MaMuk** [espocrm/espocrm#1280]
[removed]

Is there a reason why input is not escaped? This should mitigate the risk further and is standard practice when dealing with XSS attacks

**Comment by yurikuzn** [comment]
Will be fixed. Thanks.

We don't escape input. Only output.

**Comment by MaMuk** [comment]
Great to hear.

But when it comes to not escaping input, I know that it is common, but it is not best practice in my opinion. You don't always have control over how the data is printed in a web application and it is easy to forget to escape stored values even in code you control.
Maybe it's something to consider in the long run.

Best regards.

**Comment by yurikuzn** [comment]
Right. All xss that have been found before, were caused by js code that generates HTML, that is not supposed to be done by design. We must use templates, but sometimes use js for some (often not not justifiable) reason.
