### ISSUE TITLE
Regular user can't change a custom email field on EspoCRM 5.6

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#1285]
Hi, I created a custom field on Entity emails, named Analysed. (binary). It works exactly as expected when using an Admin user. But, when using a regular user, even with all permissions, everytime it edit that attribute, it shows like SAVED and on screen, but when you refresh the screen, the attribute is exactly as before.
Other attributes like Parent, etc. can be changed by the same user, without problems.

I recorded a video, but, since it has proprietary info of the company, I can't publish it here. If necessary, I can share it with you.

![image](https://user-images.githubusercontent.com/6912410/55505476-9251e800-5629-11e9-8b6c-6571f59ba91b.png)

**Comment by rodrigoscoelho** [comment]
No error on LOG files. No workflow related to it.

**Comment by rodrigoscoelho** [comment]
@yurikuzn ??

**Comment by yurikuzn** [comment]
yuri is extremely busy

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Email.php#L62

**Comment by yurikuzn** [comment]
You can add your custom fields (attributes) to the list.

**Comment by rodrigoscoelho** [comment]
> yuri is extremely busy

I know. But you are the only one that knows the insides of the code. That kind of answer you just gave, would not be possible without your superior knowledge. Thank you so much for your time.

**Comment by rodrigoscoelho** [comment]
For your information. It worked as expected. I did it on /custom/Espo/Custom/Services/Email.php

Thanks.
