### ISSUE TITLE
404 Error in json.

### ISSUE THREAD

**Issue by Riyazkhan14** [espocrm/espocrm#1287]
I am using it on IIS but there is no display except footer. when I see in inspect element- network I found json not loading it shows 404 error. I am attaching a screenshot. please solve the problem.
![error espo](https://user-images.githubusercontent.com/21050074/55686679-cad32800-5981-11e9-97c1-ff801c7f0e5d.JPG)

**Comment by AshEllis93** [comment]
Was there a solution to this issue, I'm experiencing the same on a fresh install on IIS.

Root directory: public
Alias: client
URL Rewrite working.
PHP working.
All perquisites met and MySQL installed and tables present.
![EspoCRM](https://user-images.githubusercontent.com/54539019/178074063-29306f9d-c0df-464a-93a7-50d50d060b32.png)

**Comment by yurikuzn** [comment]
Espo currently is not shipped with configured URL rewrites for IIS. The number of IIS users is very very low.

Try to configure in these files:

* `web.config`
* `public/api/v1/web.config`
* maybe need also to create `public/web.config`. 

If you find a solution please let me know, or create a pull request.

**Comment by AshEllis93** [comment]
Evening Yuri,

I've managed to find a solution which works, mainly the web.config file and the in-built MIME types seem to be fighting against each other, the below edit in the web.config file sorted everything.

        <staticContent>
            <remove fileExtension=".tpl" />
            <mimeMap fileExtension=".tpl" mimeType="text/plain" />
            <remove fileExtension=".json" />
            <mimeMap fileExtension=".json" mimeType="application/json" />
            <remove fileExtension=".woff" />
            <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
        </staticContent>

Seems counterintuitive to remove the MIME's just to re-add them, probably be better to remove the 3 above MIME extensions from the website but this edit to the web.config can at least be distributed.

Let me know if there is more I can do to help.

**Comment by yurikuzn** [comment]
So these changes was enough to make espo work?

**Comment by AshEllis93** [comment]
They were yes.

All in all, as long as the following is installed/setup it works fine on IIS:
- URL Rewrite installed.
- PHP file setup inline with existing Installation Instructions (Albeit a few entries aren't listed in the PHP file).
- Default Document: Index.php must be added into IIS.
- Website MUST be setup to have the ROOT directory as public and an ALIAS of Client.
- Web.Config setup with the previous posts additions.

I'll create a pull request and amend the Web.Config, would an IIS guide be beneficial?

**Comment by yurikuzn** [comment]
You can create PR if you like. I can apply these changes either, no problem for me.

Having guidelines in the docs would be good. Just like we have for apache and nginx.

**Comment by AshEllis93** [comment]
Already done, awaiting approval from yourselves.

I'll look at adding the guidelines, I think it would be beneficial for the Microsoft users among us.

Thanks for your help Yuri! 👍

**Comment by AshEllis93** [comment]
Sorry Yuri,

Next IIS (Perhaps) related issue, trying to Import data results in the following:

espocrm 'uploadfile' does not exist in controller 'import'.

I'll raise this as a bug tomorrow unless you think there's an easy fix?

Cheers!

**Comment by yurikuzn** [comment]
Please no need to raise it as a bug. It must be an IIS specific issue. The functionality works. If you find a solution please let the community know.

**Comment by AshEllis93** [comment]
No problem Yuri,

Here's the exact error message(s) associated with this issue (with printTrace enabled).

[2022-07-10 08:34:57] ERROR: (404) Action GET 'uploadFile' does not exist in controller 'Import'.; GET /Import/action/uploadFile; line: 92, file: C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\Api\ActionProcessor.php :: 
#0 C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\Api\RequestProcessor.php(136): Espo\Core\Api\ActionProcessor->process('Import', 'uploadFile', Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) 
#1 C:\inetpub\wwwroot\EspoCRM\applicatore\Api\Requestion\Espo\Core\Api\RequestProcessor.php(111): Espo\CProcessor->proceed(Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) 
#2 C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\Api\RequestProcessor.php(82): Espo\Core\Api\RequestProcessor->processInternal(Object(Espo\Core\Api\Route), Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) 
#3 C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\Api\Starter.php(103): Espo\Core\Api\RequestProcessor->process(Object(Espo\Core\Api\Route), Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) 
#4 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(43): Espo\Core\Api\Starter->Espo\Core\Api\{closure}(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) 
#5 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\Routing\Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) 
#6 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Psr7\Request)) 
#7 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) 
#8 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\Routing\Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) 
#9 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\Routing\RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Psr7\Request)) 
#10 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request)) 
#11 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner)) 
#12 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\Middleware\ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) 
#13 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) 
#14 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) 
#15 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) 
#16 C:\inetpub\wwwroot\EspoCRM\vendor\slim\slim\Slim\App.php(199): Slim\App->handle(Object(Slim\Psr7\Request)) 
#17 C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\Api\Starter.php(79): Slim\App->run() 
#18 C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\ApplicationRunners\Api.php(49): Espo\Core\Api\Starter->start() 
#19 C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\Application\RunnerRunner.php(85): Espo\Core\ApplicationRunners\Api->run() 
#20 C:\inetpub\wwwroot\EspoCRM\application\Espo\Core\Application.php(81): Espo\Core\Application\RunnerRunner->run('Espo\\Core\\Appli...', NULL) 
#21 C:\inetpub\wwwroot\EspoCRM\public\api\v1\index.php(37): Espo\Core\Application->run('Espo\\Core\\Appli...') 
#22 {main} [] []

In which file would I need to check the CASE of 'import'?

I agree but if we can iron out these few issues we could add to the installation guide for IIS and hopefully community support could take it from there?

**Comment by yurikuzn** [comment]
It's 100% configuration issue. The request method should be POST, but interpreted as GET by the webserver for some reason.

**Comment by AshEllis93** [comment]
Do you know where abouts in the file structure I could amend this manually to test?

**Comment by yurikuzn** [comment]
Use the search on Github (the top-left corner). Try an `uploadFile` keyword.

**Comment by AshEllis93** [comment]
It's strange, the Network header is showing POST but the error log showing GET.

Other than the Import functionality everything else seems to work perfectly, I may need to use XAMPP for the time being.

Is it worth a post in the community forum to see if anyone else has any suggestions?

![image](https://user-images.githubusercontent.com/54539019/178141157-04f7e207-5c11-4307-bc69-982d0baa65e2.png)

**Comment by yurikuzn** [comment]
I recall there was a similar issue posted on the forum. I don't know how it went though.

**Comment by AshEllis93** [comment]
I tested using Postman with the BASIC auth and when using POST it works as expected (I get the attachment ID returned back too), Could the following article have any input?

https://github.com/postmanlabs/postman-app-support/issues/450

Summary: Trailing slashes or re-directs can strip out the POST request and convert it to a GET request.

**Comment by AshEllis93** [comment]
Sorted Yuri,

PHP's temporary directory for HTTP uploaded files was set to its default which IIS didn't have permission to access, I temporarily set the below in the php.ini file and the .csv uploaded as expected:

upload_tmp_dir = C:\inetpub\wwwroot\EspoCRM\data\upload

Could you add a note onto the following link to perhaps inform the user to set the path to somewhere with permissions or to give the correct permissions to the temp directory?

https://docs.espocrm.com/administration/server-configuration/

**Comment by yurikuzn** [comment]
Rather in a separate dedicated article for IIS. It's used by less than 1% of our users. This info is not needed to be in the main server configuration article. We can end up to add all possible nuances of PHP configuration making the article so big so nobody would read it.
