### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by uok** [espocrm/espocrm#129]
Thanks for this great CRM application!

please implement automatic forwarding HTTP -> HTTPS if site url has https prefix and user opens HTTP version or add an option to enter site url with option "https" during setup and e.g. add to .htaccess
```
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
```

**Comment by yurikuzn** [comment]
Hi

Not sure if it's good to modify .htaccess upon installation. It can be implicit for some. I think for those who use https wouldn't be a problem to edit it manually.
