### ISSUE TITLE
compliance with RFC4180 and CSV validation during import

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1296]
I've had many cases where an import gets stuck because of CSV formatting errors. There are many open source algorithms out there to ensure CSV files are properly formatted according to the proper [RFC (4180)](https://www.ietf.org/rfc/rfc4180.txt) and would certainly be useful to be warned of such errors (verbosely!) before even getting to step 2 of the import process.

Troubleshooting an aborted background import is pretty annoying.

**Comment by yurikuzn** [comment]
We don't upload the file until Run in clicked., hence processing before is not a desired option. Or process it in the browser by a user's request.

> There are many open source algorithms out there to ensure CSV files are properly formatted

Please let me know which exactly.
