### ISSUE TITLE
Portal bad username and passwors

### ISSUE THREAD

**Issue by tomaspar** [espocrm/espocrm#1297]
After upgrade CRM to 5.6.1   +  Advanced Pack 2.3.0 portal users can't login any more. bad username or password. Password reset didn't help at all.

**Comment by tomaspar** [comment]
jquery-2.1.4.min.js:4 GET /api/v1/App/user 401

**Comment by tmachyshyn** [comment]
It works fine for me. Could you check your log files, https://www.espocrm.com/documentation/administration/troubleshooting/.

**Comment by tomaspar** [comment]
It's because update overwrite  .htaccess file content where portal redirections are set for custom domains. After restore previous file problem disappear, but it's bad behaviour of update to lost portal settings during update.
