### ISSUE TITLE
LDAP authentication not working with espocrm

### ISSUE THREAD

**Issue by zeeshanaziz01** [espocrm/espocrm#130]
I have configured espocrm on **centos 6.2 **  and enable to get login with the admin user & password successfully. But when i enabled** ldap authentication** from administration i am unable to login with the specified user in the active directory. I tried using **sAMaccount **name in username field suggested by this post
https://github.com/espocrm/espocrm/issues/74
but it doesn't work..
If you required anything it would be provided...
Any help in this regard would be highly appreciated anxiously waiting for your response.

**Comment by jaiabishek** [comment]
hi,
The LDAP  connection works with CN .ie. Full Name of the user, but it doesnt work with the other attributes like mail or sAMaccount, 
i tried to change the field in Ldap.php but the LDAP stopped working i am not able to login.

Immediate response would be appreciated.

**Comment by tmachyshyn** [comment]
Pretty busy this month. Pull request is appreciated. We are using Zend\Ldap for LDAP authorization http://framework.zend.com/manual/2.2/en/modules/zend.ldap.introduction.html. Actually, it was tested on OpenLDAP server. It can be tested on Active Directory if somebody will provide a test access for it.

**Comment by hi-ko** [comment]
@jaiabishek I fixed it in LDAP.php by putting the required parameters to the config.
s. https://github.com/espocrm/espocrm/pull/159

In LDAP config I used 
    ldapAccountCanonicalForm' => 'Principal'
to allow the user to be stored anywhere in the AD structure
