### ISSUE TITLE
Make url rewriting an option

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1301]
I believe one of the goal of any development effort of a php website is to be able to easily host it (for development purposes) out of the box with the internal php web server (or any other http+php server that isn't necessarily apache or nginx).

To do so I propose to add a setting to use GET parameters globally for frontend and api when active, instead of relying on url rewriting in the `.htaccess`.

This is not really an high-priority thing, I just posted it here so that it's not forgotten when the appropriate time for things like this comes.

One cool thing could be auto-discovery of url rewriting support and using it if possible without intervention needed.

**Comment by yurikuzn** [comment]
It's unlikely that we ever do it. Result doesn't worth efforts.
