### ISSUE TITLE
FieldManager fontend does not remove all fields

### ISSUE THREAD

**Issue by jurkov** [espocrm/espocrm#1307]
I noticed a bug in the frontend of the FieldManager. If you add the address field to your new Entity and remove this address field again, all subfields like street, city, ... will persist. Only after a Reload/Clear Cache they are removed from the frontend.

As far as i could find our it's the line 55 of client\src\views\admin\field-manager\list.js
```
delete data['entityDefs'][this.scope]['fields'][field];
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/7c3f7dd49419e998bdb76430f692eff7eb6b5ba1
