### ISSUE TITLE
Campaigns administration

### ISSUE THREAD

**Issue by tomaspar** [espocrm/espocrm#1313]
I have one issue, or don't have idea how to proper use Campaigns. 
As example we'll run summer campaign -30% of product A. 
The issue: to reach different audiences we'll use different channels like targeted  e-mail, newsletter, TV promotions, e-shop discount and etc for the same campaign. In current scenario for each "Campaign Activity" we need to create separate campaign. Actually it's the same campaign, just different activities will be used.
Some explanation https://crmbook.powerobjects.com/basics/marketing/campaigns-and-quick-campaigns/

**Comment by karthik-uc** [comment]
@yurikuzn  Having documentation on how to use campaigns and target lists effectively would really good.
