### ISSUE TITLE
Mail readable issue

### ISSUE THREAD

**Issue by tomaspar** [espocrm/espocrm#1321]
Some e-mails are shown in strange and not easy readable manier, as in MS Outlook and other mail client they looks like regular one.

Some example:
From: Davids <xxxx@xxxxx.xx>
Date Sent: 2019-05-28 16:20
Subject: (No Subject)
To: yyyyyy

  44$3aa3cb30$a
        f       eb6190$@xxxxx.xx> <VI1PR0901MB1438FB40207D9A710DE8A268BA1E0@VI1PR0901MB1438.eurprd09.prod.outlook.com>,<006b01d51557$3eccb9c0$bc662d40$@xxxxx.xx> <VI1PR0901MB1438264BEA3CC3E5F1B89E33BA1E0@VI1PR0901MB1438.eurprd09.prod.outlook.com>
In-Reply-To: <VI1PR0901MB1438264BEA3CC3E5F1B89E33BA1E0@VI1PR0901MB1438.eurprd09.prod.outlook.com>
Subject: RE: For customers B2C | last update regarding phone and partners| version 4
Date: Tue, 28 May 2019 16:19:41 +0300
Organization: EasyIT
Message-ID: <007301d51558$038a2c70$0a9e8550$@xxxxx.xx>
Content-Type: multipart/related;
        boundary="----=_NextPart_000_0074_01D51571.28DFC8E0"
X-Mailer: Microsoft Outlook 16.0
Thread-Index: AQE4wIvFE0EE3RkGFKdal1iiiNZ/bgEUEgY4AbyqYbECgOwpwAKA5rkXAWHr4bQCMkP69QE1O7U5AkiUR58B3r7MBwIsckL+AlmAU+8C1g1mfwFeDf9bAgOugPEB3sD/JQC0YtgfAZkj1uEC7hbFgaakU3OQ
Content-Language: lv
X-OutGoing-Spam-Status: No, score=0.6
X-AuthUser: xxxx@xxxxx.xx
Return-Path: xxxx@xxxxx.xx
X-MS-Exchange-Organization-ExpirationStartTime: 28 May 2019 13:19:57.5359
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 2:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id:
 8278f300-08ec-4e85-42bc-08d6e36f2e31
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 05842fb4-f1b5-4ca6-95b6-84676b74648e:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-Forefront-Antispam-Report:
 CIP:23.83.214.98;IPV:NLI;CTRY:;EFV:NLI;SFV:NSPM;SFS:(2980300002)(428003)(199004)(189003)(61296003)(336012)(229853002)(53946003)(236005)(6306002)(54896002)(54556002)(45080400002)(606006)(71636004)(46816001)(3450700001)(733005)(356004)(446003)(74482002)(486006)(44736005)(14444005)(66574012)(30864003)(6666004)(36756003)(476003)(126002)(11346002)(2616005)(956004)(71366001)(15650500001)(1096003)(84326002)(26005)(246002)(7066003)(71190400001)(2420400007)(5660300002)(43066004)(16586007)(36916002)(7596002)(9786002)(102836004)(7826002)(7636002)(76176011)(53546011)(33964004)(53386004)(6246003)(1420700001)(84116003)(15974865002)(50226002)(45776006)(790700001)(6966003)(6916009)(86362001)(8676002)(16003)(966005)(36906005)(91146002)(569006);DIR:INB;SFP:;SCL:1;SRVR:HE1PR0901MB1435;H:ladybird.maple.relay.mailchannels.net;FPR:;SPF:None;LANG:lv;PTR:ladybird.maple.relay.mailchannels.net;A:1;MX:1;
X-MS-Exchange-Organization-AuthSource:
 DB3EUR04FT010.eop-eur04.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-PublicTrafficType: Email
X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: FlexTransport
X-MS-Office365-Filtering-Correlation-Id: 8278f300-08ec-4e85-42bc-08d6e36f2e31
X-Microsoft-Antispam:
 BCL:0;PCL:0;RULEID:(2390118)(7020095)(4652040)(5600148)(711020)(4605104)(4709054)(8001031)(1414054)(49563074)(71702078);SRVR:HE1PR0901MB1435;
X-MS-TrafficTypeDiagnostic: HE1PR0901MB1435:
X-MS-Exchange-PUrlCount: 15
X-MS-Oob-TLC-OOBClassifiers: OLM:134;
X-MS-Exchange-Organization-SCL: 1
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 28 May 2019 13:19:56.7052
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 8278f300-08ec-4e85-42bc-08d6e36f2e31
X-MS-Exchange-CrossTenant-Id: 05842fb4-f1b5-4ca6-95b6-84676b74648e
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: HE1PR0901MB1435
X-MS-Exchange-Transport-EndToEndLatency: 00:00:04.4688030
X-MS-Exchange-Processed-By-BccFoldering: 15.20.1922.000
X-Microsoft-Antispam-Mailbox-Delivery:
        ucf:0;jmr:0;ex:0;auth:0;dest:I;ENG:(20160514016)(750119)(520011016)(944506303)(944626516);
X-Microsoft-Antispam-Message-Info:
        yr4DCWNFptGMIm9cE0Xo7PpCVMHRvyQV2t2Clodxv4eyjmDdaCZ44tW6XPuXMe/XMogdWKRTHMDuyRFnCDuHIZ93pjFUYPqf7ip7LsE2Fj4TSY1GHMd/0mvbjzTEIjYNvAJ8jB+flJvVSO+lZHagALKp8+5bFkjoC3SxCUXW0JM+PCepr2kg4FlsdVrgcXB4mB1ywvHcvjIDH+MKlUCELYwvYWolZCm/YuxO1sNZFgz8b8i82fvfWxqeybfe6/xVLcl7jpp+26+LnH/7nV7Cxt+rPVJuuqn4uxCzOu/m2zOZ7yLRZmgarOgmvmMpqcWZfJug61TPw4I2tO8co5pbMyWBDL6/Rn05uQtkuapgsRXstKbfcdrRADR0dACwf02eHimg9QyuyXfC0Rroe5tHl7GQrNfPzGSr3dUkG/LGE6LLbuAMNibrWh1QgPExYmbKzLrWGZCfQ7/XS5hQKb+Ss04A8tQAjgtmiC0U6aKafDoDP/q/cO1DqNXPk7ceZYSaOE0M1TZqpSYeuh6Td/ChqzzJqzSMACMRfR7bWLGVrgETEbkwx5tom5rWnORZKkVZiRAJ0yIeoxk3L206b0k6U40Zgr/o9EzobB8meYGQhUWvZbxxB7qQjg6jlJZkeen6yd11WuDbaHTopgn0GLCuEeYHUhiSFv9R6r6WkI1m57YB11DpnIowg6L20EuNDlks3gxlHaMYp0CnziJKWqLShtS3AnOLuQIi1PmOFL4QthngwA+0u8Luchd6Qm5ndBsgxHif7r9OEm31WNbJdAa8NhduVF2S0j7v8OpGwD9UCFsn7+52Tw8HVarkJMJTYyKlp5eTG22dw2Vyt9EbdWxh6hI+0bweftm1fEyski3+pLy+p5bDu+D+u3RuDhBvD4G4Om8hvAyxof5WXfGoteYzq4ULUftx4xsIElv+bbF5JMqZUX5VlFqqoVdDB7gL7N9oq1EFGy/jeNycA3vhgRYueg==

------=_NextPart_000_0074_01D51571.28DFC8E0
Content-Type: multipart/alternative;
        boundary="----=_NextPart_001_0075_01D51571.28DFC8E0"

------=_NextPart_001_0075_01D51571.28DFC8E0
Content-Type: text/plain;
        charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

Es sa=C5=86=C4=93mu jaunu lietot=C4=81ju un paroli, neesmu v=C4=93l =
p=C4=81rbaud=C4=ABjis.

Bet k=C4=81da b=C5=ABtu Velve MS Tehnolo=C4=A3iju klienta cena?

=20

Ar cie=C5=86u,

D=C4=81vids Kesners

=20
........"

**Comment by yurikuzn** [comment]
If you could provide original contents of some of those problem emails it would be helpful, Thanks.
