### ISSUE TITLE
API Dates issue

### ISSUE THREAD

**Issue by tonybyng** [espocrm/espocrm#1323]
Hi

Im using the API to pass through data from our main website. I have a datetime field in EspoCRM which records the time the user last logged in to our website.  Im passing through "2019-06-02 15:02:37" which is the current British Summer Time time as a string in the API call. When I view the record within EspoCRM, it shows as 16:02:37.  Espo Is set to "Europe/London" but its as if the API is configured to expect UTC rather than abiding by the setting in the main system and so is adding an hour on. Is there a setting somewhere to get the API to use BST or do I need to convert all dates to UTC before I pass them over the API ?

**Comment by yurikuzn** [comment]
Hi,

No. Only UTC is supposed to be used in API.
