### ISSUE TITLE
InboundEmail test email is wrong

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1329]
I sent a test email from a group account but I got a bizarre problem.

This is the configuration:

![image](https://user-images.githubusercontent.com/6625123/59684075-9ed1ef80-91d9-11e9-9e8d-4747e7626cb7.png)

![image](https://user-images.githubusercontent.com/6625123/59684108-ab564800-91d9-11e9-89f1-b58dd71c1245.png)

I sent myself a test email and this is what the sender looked like in my mail software...
It showed `HR Management <wrong@example.com>` and **no** `Reply To: replyto@example.com`.

The `wrong@example.com` is never defined in the InboundEmail entity. It's another email address we use as "reply to" when doing mass emails and in its own InboundEmail entity.

Here are the headers of the test email...

```
Return-path: <wrong@example.com>
Received: from vps.example.com ([185.247.117.26]) by mx-ha.gmx.net (mxgmx017
 [212.227.15.10]) with ESMTPS (Nemesis) id 1MfId7-1iFHRd2wJf-00gp3P for
 <me@me.com>; Tue, 18 Jun 2019 14:01:10 +0200
Received: from example.com ([185.247.117.26]:36010) by blah.com
 with esmtpa (Exim 4.92) (envelope-from <wrong@example.com>) id
 1hdCnV-0000D2-QF for me@me.com; Tue, 18 Jun 2019 12:01:09 +0000
Date: Tue, 18 Jun 2019 14:01:09 +0200
From: "HR Management" <wrong@example.com>
Sender: wrong@example.com
To: me@me.com
Subject: EspoCRM: Test Email
Content-Type: text/plain; charset="UTF-8"
Message-ID: <e2abecc0c2c38a0005e4737a38951268/1560859269/6573@espo>
X-Get-Message-Sender-Via: vps.example.com: authenticated_id: proper@example.com
X-Authenticated-Sender: vps.example.com: proper@example.com
Envelope-To: <me@me.com>
```

I find such a "leakage of settings" very strange 😓. If someone could point me to where the headers are actually set in the code I would try to debug it on my system.

**Comment by beppe9000** [comment]
I actually tested the email and the sender problem is just an issue of the `[TEST]` button.
Regular outbound emails seem to respect settings but the `Reply-To` header is not set tough.

**Comment by yurikuzn** [comment]
The functionality was rewritten since. If the issue ever occurred, it's likely to be resolved now.
