### ISSUE TITLE
record validation via GUI

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1330]
(enhancement)
Please provide some way to add record level validation that will:
- evaluate an expression
- if expression is false, show notification

Suggested location :  Entity manager -> formula
Suggested method :  formula 
Example : entity\Validate(EXPRESSION, MESSAGE)
eg : entity\Validate( (id > 100 &&code =="ET" , "You cannot have more than 100 in ET");

Related issue : #1226

**Comment by yurikuzn** [comment]
This can cover
This will allow using reg exp for validation.
https://github.com/espocrm/espocrm/issues/2013
https://github.com/espocrm/espocrm/issues/2014

Formula has nothing to with UI. It's server-side.

**Comment by analystcmyk** [comment]
Thank you, nicely implemented
