### ISSUE TITLE
Email Address is Opted Out should be a separate field

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1331]
Phone has separate field called do not call as a separate field view
Email has Email Address is Opted out in the same field view as email.

Need to keep it consistent. Either keep both separate or keep both together.

**Comment by yurikuzn** [comment]
There is.

'Do not call' is a legacy field.

**Comment by yurikuzn** [comment]
EmailAddressIsOptedOut and PhoneNumberIsOptedOut.
