### ISSUE TITLE
New API route documentation

### ISSUE THREAD

**Issue by swordsreversed** [espocrm/espocrm#1332]
Hi, I couldn't find this covered in the Documentation, i had to search through a few different threads in the forum til i found the right solution.

I'd be happy to add a PR if you think it would be helpful.

**Comment by yurikuzn** [comment]
Hi,

What exactly do you mean by 'API route'?

**Comment by swordsreversed** [comment]
eg, if i wanted to create an url/api endpoint that i can consume in another application:

```
/api/v1/reports/action/properties

```

**Comment by yurikuzn** [comment]
I added 2 days ago this example: https://github.com/espocrm/documentation/blob/master/development/api-action.md

**Comment by swordsreversed** [comment]
oh great! thanks.
