### ISSUE TITLE
UUID as ID?

### ISSUE THREAD

**Issue by pomazanbohdan** [espocrm/espocrm#1334]
in order that the data could be used transparently in other systems, can make an option, use the UUID for id?

**Comment by yurikuzn** [comment]
It will require to increase a size of all id columns. We can't afford such a change.

You can create a separate field for this purpose.

**Comment by Pomazan-Bogdan** [comment]
Optional in the configurator?

**Comment by b1f17773** [comment]
We have same problem.. We created hook which create uuid in field uuid. After few month we decided that we want to minimize requests to db based on uuid, so we created another entity. This new entity match uuid from new entity with espo id in other entities. But we're using espo also with our external services so we need more then usual user of espo :)

**Comment by di-rect** [comment]
I just ran into this issue as well and I'm sure all ID's should be stored as binary UUID's.

You will never run out of ID's and also queries are much faster.

It would be best if this will be migrated, which is very much possible to do so, also on running systems, for files, etc.

**Comment by yurikuzn** [comment]
What exact issue you run into? Migrating all to UUIDs way not an easy task. One can do it for own system, but when you have 1000s of instances that you don't have control and don't know how they are used, it's another story. Likely, we will never do it.

You can customize it to use UUID, as of v7.4 it will be easier to do.

**Comment by yurikuzn** [comment]
Bind your custom IdGenerator implementation [like so](https://github.com/espocrm/espocrm/blob/7.3.2/application/Espo/Binding.php#L223). The only thing that is hardcoded is column length, set to 24 (it will be configurable as of v7.4). And you will have UUIDS.

**Comment by yurikuzn** [comment]
In v7.4 it will be possible to enable UUID. More in [docs](https://github.com/espocrm/documentation/blob/master/docs/development/metadata/app-record-id.md).

I did some tests of UUID data type (available in MariaDB as of  v10.7), for all IDs on the instance with a lot of data and didn't notice any performance improvements compared to the default VARCHAR(17).
