### ISSUE TITLE
command.php upgrade is disabling Cron, Cache, etc.

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#1335]
When upgrading using command.php via console, it works as expected, but the Espocrm is not re-enabling the cron, cache and is maintaining the Maintenance Mode checked.

**Comment by yurikuzn** [comment]
Do you mean that if Maintenance Mode was 'off' it becomes 'on' after uprgade?

**Comment by tmachyshyn** [comment]
It works fine for me. What EspoCRM version do you use?

**Comment by rodrigoscoelho** [comment]
> Do you mean that if Maintenance Mode was 'off' it becomes 'on' after uprgade?

Yes. I think it should be ON when upgrading, and OFF after finished.

The same with Cache. It turns Cache OFF, and doesn't activate it again.
The same for Cron....

**Comment by rodrigoscoelho** [comment]
5.6.3

**Comment by tmachyshyn** [comment]
Also tested on 5.6.3.
It returns the previous state of these options. So, if the Maintenance Mode is enabled before upgrade, it will be enabled after upgrade too. Please manually change the Maintenance Mode, Cron, Cache and test it again.

**Comment by rodrigoscoelho** [comment]
Will do that on the next release. Now it is already with the latest version.
Thanks
/
By the way, this is the second time it happens with me. Any chance to be
because of my language definition? (Portuguese).

Em qui, 27 de jun de 2019 às 10:04, Taras Machyshyn <
notifications@github.com> escreveu:

**Comment by tmachyshyn** [comment]
Also works fine with Portuguese. If you have a test environment, you can change the `version` in data/config.php and try it again.

**Comment by yurikuzn** [comment]
Must be already fixed.
