### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by emillod** [espocrm/espocrm#1337]
Hello
i found out that everyone can open website without log in and check informations about Espo..
http://demo.espocrm.de/advanced/api/v1/Settings
There should be some kind of authentication which will be deny access to people without account.

**Comment by yurikuzn** [comment]
It's known. The limited set of parameters are listed.

**Comment by emillod** [comment]
Is there any chance to hide list of entities, version and etc?

**Comment by yurikuzn** [comment]
I don't recommend hiding version.

You can try to add to your config:

```
'userItems' => [
   'tabList'
]
```

**Comment by emillod** [comment]
Ok so if i add those parameters to config file in ftp i'll be able to hide some elements?

**Comment by yurikuzn** [comment]
Why not to try. I'm not sure at this moment.

**Comment by yurikuzn** [comment]
Here is the default list: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/defaults/systemConfig.php#L217

You need to add these items too.

**Comment by emillod** [comment]
OK, i'll try

**Comment by hturkoz** [comment]
worked for me ;) 
Many thanks for reporting and for Yuri for solution.... this is important to know.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f624bdef5c5e708a789a3421e11be290f9c451df

**Comment by emillod** [comment]
@yurikuzn why you don't recommend hiding version?
