### ISSUE TITLE
Overflow menu has overflown and can't scroll

### ISSUE THREAD

**Issue by tonybyng** [espocrm/espocrm#1341]
Ive started to create several Entities as EspoCRM will be the back end to our business. Ive got 8 entity types listed as part of the main menu and all the other items are in the ellipsis menu. If I make the window as big as possible I can see 26 Entities in the menu but I know there are a few off screen that I cant see but there is no scroll ability on the menu itself and if I scroll down the page to see other page content,  the menu doesn't scroll with it.  Multi level menus would be brilliant but just the ability to be able to see them all would be a start

Thanks

**Comment by tonybyng** [comment]
I've solved it, although there is probably a better solution.

`.navbar-nav>li>.dropdown-menu {
     overflow-y: scroll;
     height: 400px;
}`

means that the overflow menu appears but  is restricted to 400px high but then i get a scrollable  list of menu items within that.

**Comment by yurikuzn** [comment]
Thanks for reporting. Here's the fix: https://github.com/espocrm/espocrm/commit/574513a9c874be1b98b2f0d237e94ef63200dd49
