### ISSUE TITLE
Foreign enum field not having options

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#1345]
Foreign enum field can be added as a filter, but when trying to add filter with such field no enum entries are listed and can not be used.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/502cfc8d76df066345a4c7993fc92b33d91b9025

You will need to recreate the field.

**Comment by rodrigoscoelho** [comment]
Any other file we could edit manually to avoid recreating the field?? thanks Yuri.

**Comment by yurikuzn** [comment]
Yes. entityDefs file in custom metadata. Change "view" parameter the same way as in the commit.

**Comment by rodrigoscoelho** [comment]
Thanks

Em qui, 11 de jul de 2019 às 13:40, Yuri Kuznetsov <notifications@github.com>
escreveu:

**Comment by rodrigoscoelho** [comment]
When do you expect to launch this "bugfix". If I change it now, I will have
problems, probably, since the view is not defined correctly.


Em qui, 11 de jul de 2019 às 13:40, Yuri Kuznetsov <notifications@github.com>
escreveu:
