### ISSUE TITLE
Selectable type "Link Parent" in fields/links

### ISSUE THREAD

**Issue by byyiro** [espocrm/espocrm#1348]
Need selectable "Link Parent" field for non-coders administrators.

**Comment by rodrigoscoelho** [comment]
Great request...

Enviado utilizando um Galaxy S9...

Em sex, 12 de jul de 2019 05:23, byyiro <notifications@github.com> escreveu:

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1530
