### ISSUE TITLE
Email Print proper frame button

### ISSUE THREAD

**Issue by RCFilm** [espocrm/espocrm#135]
If you print from the current email entity it prints the outer frame please implement a print button to the interframe

**Comment by PanuWeb** [comment]
Hello

Today for the first time I found the need to print an email and I find this problem.

I was researching some solutions such as printing only the content of the iframe, but the header is necessary. Also the possibility to break the iframe in several pages, but without finding an easy and universal solution.

It is also necessary to hide the buttons: Reply, edit, etc.

It is not urgent but it would be interesting to implement a general print media CSS to be able to print any system screen.

For the moment I copy the content of the email and paste it in the text editor.

Regards!

**Comment by yurikuzn** [comment]
This commit https://github.com/espocrm/espocrm/commit/c9ca3a497f65c0c3f6ea5a0f914aa9c080ccb8fd improves printing emails. Not ideally but better than it was.

**Comment by o-data** [comment]
I see yuri closing many old #issue, hopefully this one next!

**Comment by yurikuzn** [comment]
There's a workaround. Click on the email body > Ctrl + A (selects all) > Right click  > Print.

I'm not sure I would like adding a separate print button.

**Comment by yurikuzn** [comment]
Added a dropdown menu action: https://github.com/espocrm/espocrm/commit/fc72d847da0eac0bff8deead408f33130536e18d

**Comment by Kharg** [comment]
> I see yuri closing many old #issue, hopefully this one next!

can you see the future? 🤣

**Comment by o-data** [comment]
Only 3 files to edit, I think I will manual patch this one issue!
