### ISSUE TITLE
Click on Call title in Stream should open panel

### ISSUE THREAD

**Issue by tvld** [espocrm/espocrm#1355]
In **Accounts**, both in _Stream_ as in the _History side panel_, I would suggest clicking on the title of a call would open a panel and not open a complete new  page as it does now. Just works quicker to stay on the Account page

By the way: If you click _View_ in History it does open the panel, but in that case I would not mind going to new page...

**Comment by tvld** [comment]
Actually I noticed that same improvement can be made in Knowledge base:

![Screenshot from 2019-08-09 10-55-48](https://user-images.githubusercontent.com/986182/62767408-e1ef6700-ba94-11e9-9fd3-27cfb80df0e5.png)

**Comment by yurikuzn** [comment]
I'm not sure. It's a matter of preference.

**Comment by tvld** [comment]
Maybe... but usually quick action should open quick screen, and two step action full screen... 

At least that is how I see it  ...))

**Comment by tvld** [comment]
But will close... as a "feature" does not deserve ticket here ;-)

**Comment by yurikuzn** [comment]
Personally I prefer redirecting to detail view. Not sure how it's better to do. Maybe configurable per entity type, but not sure whether it's reasonable.

**Comment by tvld** [comment]
Point is we:

1 - open an account when client calls us
2 - quickly scan it's history, for example to find information about a certain call the contact is referring to. Now we can not really do that quickly as it involves juggling with browser windows. 

Hence our desire to switch the two actions

**Comment by tvld** [comment]
Ah.. maybe good idea, if indeed possible: In configuring entity type url, we could be allow click to:

1 show quick panel
2 show full form in same browser window
3 open new window with full form

**Comment by yurikuzn** [comment]
In History panel, you can click on phone icon for quick view.

**Comment by tvld** [comment]
Oops... just tried and that works... we never saw that :+1:

ok, good thank you ))
