### ISSUE TITLE
case updated date not updating when email comes in

### ISSUE THREAD

**Issue by tonybyng** [espocrm/espocrm#1368]
Hi

When a case is created/updated itself, then the create/updated dates will get set, but if an incoming email is an update to a case, because the case record itself is not being touched, the date is not being updated, so I could have a customer email me about a case and I know the email has just come in but when I go to the cases page, Im looking half way down the page (sorted by modified at), even though when I then click on the case, the history then shows that an email has just come in a few moments ago

Also, in that general area, when you tick boxes at the side of the cases for multi actions, the actions dropdown doesnt actually include a close option - you have to go into each case individually and click close. Not a major issue but just something Ive seen. The main issue is the date not updating when an email comes in.

**Comment by yurikuzn** [comment]
Hi,

When an email comes, it should not update case record. It's how it designed and we can't break it. You can customize (w/ workflows or a hook) so that it will update some custom date field. I close, since it's not a bug.
