### ISSUE TITLE
Uncaught Exception Error: "Class 'Espo\Controllers\Forbidden' not found"

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1371]
Uncaught Exception Error: "Class 'Espo\Controllers\Forbidden' not found" at /www/espocrm/application/Espo/Controllers/ScheduledJob.php line 37 {"exception":"[object] (Error(code: 0): Class 'Espo\\Controllers\\Forbidden' not found at /www/espocrm/application/Espo/Controllers/ScheduledJob.php:37)"}

**Comment by karthik-uc** [comment]
https://github.com/espocrm/espocrm/pull/1372

**Comment by yurikuzn** [comment]
Thanks.
