### ISSUE TITLE
Make use of Redis/RabbitMQ with celery to run background jobs instead of database

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1373]
# Problem

Right now the jobs are being run by database. The problem with this is the cron should pick up the task and time lag is atmost 1 minute. However, when you integrate with applications like Adobe Sign where users/UI are dependent on jobs which happens via API requests you can't have 1 minute delay.

# Suggestion

Use Redis/Rabbitmq to manage queues and tasks in queues
Use celery to add task into queue which can immediately picked up by celery worker.

When API calls are made, only task is added. When the task is completed, a webhook will be called to notify that the task is completed.

**Comment by karthik-uc** [comment]
https://www.php.net/manual/en/book.gearman.php

**Comment by yurikuzn** [comment]
Check this: 

You can setup daemon: https://github.com/espocrm/documentation/blob/master/administration/jobs.md#setting-up

**Comment by yurikuzn** [comment]
You can also add a job to separate queues, that won't be limited by max job number per execution by setting queue param.

```
$em->createEntity('Job', [
    'serviceName' => 'Test',
    'methodName' => 'test',
    'data' => $data,
    'queue' => 'q0',
]);
```

q0 - means that it will be run in a queue that is processed as often as possible, and processes in big batches
q1 - means that it will be run once a minute, and processes in big batches

**Comment by yurikuzn** [comment]
You will be able to  call a webhook (from the next 5.7.0 version) in the your job method.

**Comment by yurikuzn** [comment]
I recommend trigger a websocket event once job is done, and catch it on frontend.

1. Make a API call, subscribe to websocket event.
2. API creates a job.
3. Job is processed and websocket event triggered.
4. Frontend catches the event.

**Comment by karthik-uc** [comment]
@yurikuzn Thank you for the information. Really helpful

**Comment by karthik-uc** [comment]
I am calling Webhook to a different server itself. This is not used for frontend.
