### ISSUE TITLE
Install EspoCRM on Windows Server 2019, IIS

### ISSUE THREAD

**Issue by ThePaterino** [espocrm/espocrm#1375]
Hello folks,

I tried to install EspoCRM in a fresh installation of Windows Server 2019, but after I configured the IIS and gave the IIS permissions on EspoCRM folder I get the following problem:

![EspoCRM](https://user-images.githubusercontent.com/53569893/62299275-ed2f0b00-b474-11e9-94fe-f310d91bbbc0.PNG)

I can click the start button, but it doesn't direct me to the next phase of the installation.

I got PHP 7.3 running on this machine, but also tried older versions.

Best regrads
Patrick

**Comment by tmachyshyn** [comment]
I think, you have the same problem, https://forum.espocrm.com/forum/installation-and-upgrade-help/2340-installation-issue?p=2364#post2364.

**Comment by ThePaterino** [comment]
Funny stuff. 

I deleted the preconfigurated mime-types and added .config under Request Filtering. The installation started with an error message that he can't add another .config. So I deleted the one I added and afterwards the installation started as intended.

Thanky you for your help.
