### ISSUE TITLE
Ability to highlight leads/opportunities based on certain fields in list view

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1377]
# Problem

It is easy for agent to identify the priority leads/opportunities based on colors. Highlighting a row in the list view would be a good feature so that agent can be prompted to pick those leads first.

Also add a priority field for agents to work based on lead priority

**Comment by yurikuzn** [comment]
You can use "Display as Label" parameter for enum fields with a specific color.

**Comment by karthik-uc** [comment]
FYI, I saw this feature on salesforce.

**Comment by karthik-uc** [comment]
I know. That is for a field. I am saying that you should highlight entire row rather than a field. It would be much better that way.

**Comment by yurikuzn** [comment]
In my opinion one field is enough to highlight.
