### ISSUE TITLE
ACL: Allow followers to view records

### ISSUE THREAD

**Issue by alichter1** [espocrm/espocrm#1380]
User following record should be able to view followed record when permission set to own,

Scenario:
User with permission on Tasks set to Team, creates a task and assigns the task to user outside of team, with setting set to follow created records.
Expected results:
He should be able to view his followed tasks,
Actual Results:
Currently if ACL for Tasks is set to own, he cannot view his followed tasks.

**Comment by yurikuzn** [comment]
The fact of following should not effect on permission.u

**Comment by yurikuzn** [comment]
I'd recommend to customize SelectManger and Acl classes for Task entity type. 

1. Create a file `custom/Espo/Custom/Acl/Task.php`

```php
<?php
namespace Espo\Custom\Acl;

class Task extends extends \Espo\Core\Acl\Base
{
    public function checkIsOwner(\Espo\Entities\User $user, \Espo\ORM\Entity $entity)
    {
         return $entity->get('assignedUserId') === $user->id || $entity->get('createdById') == $user->id;
    }
}
```
2.  Create a file `custom/Espo/Custom/SelectManagers/Task.php`

```php
<?php
namespace Espo\Custom\SelectManagers;

class Task extends \Espo\Modules\Crm\SelectManagers\Task
{
    protected function accessOnlyOwn(&$result)
    {
        $result['whereClause'][] = [
            'OR' => [
                'assignedUserId' => $this->getUser()->id,
                'createdById' => $this->getUser()->id,
            ]
        ];
    }
}
```

**Comment by alichter1** [comment]
Thanks for your quick response,
I implemented your recommended customization, but still doesn't show up in tasks,
If clicking on task from stream he can access it,

**Comment by yurikuzn** [comment]
I modified code above to support team level access.

Another solution:

You can create one-user teams for every user. And make this team default for them.

**Comment by alichter1** [comment]
Works like a charm!
Thank You
