### ISSUE TITLE
Fresh install problem with 5.6.9

### ISSUE THREAD

**Issue by bennouchy** [espocrm/espocrm#1384]
Hello,

I am trying to do a fresh install 5.6.9 on a web hosting provider (PHP 7.3)
I am stuck on the database configuration step, but I guess it comes from errors I can see in the console on the first step of the installation (language selection)

Every js library returns a 404 because the path "/espocrm/install/client/lib' instead of '/espocrm/client/lib'.
The 'install' directory is in the path, but I am not skilled enough to go further.

EDIT : Could be link to my hosting provider settings

**Comment by tmachyshyn** [comment]
The 404 errors just warning errors. This does not affect on your problem with database. Please check if you have lined your database user to your database.

**Comment by bennouchy** [comment]
Thanks for the answer.

As I suspected, it was the firewall option of my hosting provider that was the problem. The SQL transactions were blocked because of a bad score regarding their owasp security rules.
