### ISSUE TITLE
Couldn't Login After 5.6.9 Upgrade due to Mapper.php

### ISSUE THREAD

**Issue by dustyhansen** [espocrm/espocrm#1385]
Upgraded via the UI to 5.6.9 from 5.6.8 and was unable to login after upgrade due to "Bad Server Error". The log showed the following:

Espo.ERROR: Uncaught Exception Error: "Call to undefined method Espo\ORM\DB\Query\Mysql::buildJoinConditionsStatement()" at /opt/lampstack-7.3.7-1/apps/espocrm/htdocs/application/Espo/ORM/DB/Mapper.php line 1051 {"exception":"[object] (Error(code: 0): Call to undefined method Espo\\ORM\\DB\\Query\\Mysql::buildJoinConditionsStatement() at /opt/lampstack-7.3.7-1/apps/espocrm/htdocs/application/Espo/ORM/DB/Mapper.php:1051)"} []

When I replaced Mapper.php with the old version I was able to login just fine.

**Comment by yurikuzn** [comment]
Could you attach your application/Espo/ORM/DB/Query/Base.php file. Or check whether it is exactly the same as https://github.com/espocrm/espocrm/blob/stable/application/Espo/ORM/DB/Query/Base.php

**Comment by dustyhansen** [comment]
It appears there are differences.

[Base.zip](https://github.com/espocrm/espocrm/files/3482772/Base.zip)
