### ISSUE TITLE
Lead Capture: Lead not created if duplicate contact exists

### ISSUE THREAD

**Issue by dustyhansen** [espocrm/espocrm#1387]
I have two Lead Capture forms built, both of them have the "Duplicate Check" checkbox unchecked/disabled. Both forms seem to reject leads that have a duplicate email address. The lead is shown in the log, but the "Is Lead Created" checkbox is unchecked and no lead is created. I was able to circumvent this behavior by commenting out the section of code that checks for duplicates, however the 5.6.9 upgrade replaced my file and the issue still persists, so I thought I would report it.

**Comment by yurikuzn** [comment]
There are multiple ways how lead capture can be configured. To save my time, can you provide all parameters of your Lead Capture record.

**Comment by dustyhansen** [comment]
![lead capture](https://user-images.githubusercontent.com/53882827/62728282-038f1680-b9e1-11e9-9ca9-aecece7a0666.png)

**Comment by yurikuzn** [comment]
Thanks. Weird, I belive I tried with the same param 2 days ago and it worked.

**Comment by dustyhansen** [comment]
This was a problem for me in 5.6.8 and 5.6.9, but the good news is that in 5.6.9 it shows in the log as a duplicate. The last version I had to guess that was the problem.

**Comment by yurikuzn** [comment]
The problem happens when duplicate contact exists or only duplicate lead exists?

**Comment by dustyhansen** [comment]
The issue I am having is that it will not create a lead when there is a contact with the same email. I did not test it with duplicate leads.

**Comment by yurikuzn** [comment]
That is what I needed to know.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3d1f632a731420b686207b6d588ee71c9640c706
