### ISSUE TITLE
Email: Reply working not properly if email is sent not from a primary user address

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1388]
# Email Reply-To and Reply-To-All Issues

**Please see how gmail works when you click reply or reply to all for a sent email and received email and the behaviour should be same in espocrm also**

## Our Settings

We have group email accounts but no personal emails. Our emails have following purpose i.e. sales and support. Support email creates case. Sales emails either attaches email to lead or creates a lead and attaches email to it. Let's say my sales email, is sales@abc.com and support emails is support@abc.com.

### Problem-1

- I received an email to sales@abc.com.
- If i clicked reply to all, the cc is added as sales@abc.com, the "From" is "sales@abc.com". 

#### Expected

Reply-to-all should avoid automatically adding the From address into cc. Also, Reply-to-all should avoid automatically adding group emails to cc.

## Problem-2

- I sent an email to a client say yuri@gmail.com from sales@abc.com
- I didn't receive a response from yuri for a week. Now, I would want to follow up with yuri. So, I click on reply to the same email because I am following up. 
- On reply, the To box is filled with sales@abc.com
- On reply-to-all, The To box is filled with sales@abc.com, the cc box is filled with sales@abc.com and yuri@gmail.com

#### Expected

- On reply, To box should be yuri@gmail.com
- On reply-to-all, To box should be yuri@gmail.com, cc should still be empty.

**Comment by yurikuzn** [comment]
It works fine if you send from a personal email address.

> Reply-to-all should avoid automatically adding group emails to cc.
Sometimes we need group email address added to CC. Disabling will make problems.

**Comment by yurikuzn** [comment]
Could you apply this fix https://github.com/espocrm/espocrm/commit/20139a88afc13043a668ebd415ce43b51f4ce73a and let me know whether it solved your problem.

**Comment by karthik-uc** [comment]
@yurikuzn 

In my opinion, when someone needs it, they should added it explicitly. However, if you strongly feel that it's required then could you please add a setting called "do not add group emails to cc" to disable this feature. 

If the default behaviour of a mailer is consistent for group emails and personal emails, it helps.

**Comment by karthik-uc** [comment]
@yurikuzn Thanks for the quick fix. I will try it out and let you know

**Comment by karthik-uc** [comment]
@yurikuzn 

Needs little more changes.

On Reply: When the status is Sent, it should auto fill the the To address box from sent mail's to address. Right now, it's empty.

On reply-to-all: When the status is Sent, it fills the the To address box from sent mail's to address. However, it also fills the cc address box with the sent mail's to address box.

**Comment by yurikuzn** [comment]
We can't take into account 'status' field. Email can be sent from 3rd party app, and imported, email can't be replied by another user. EspoCRM is not an email client.

**Comment by yurikuzn** [comment]
Group email accounts should have shared SMTP and accessible for users. Then it should work.

**Comment by beppe9000** [comment]
I suggest integration with Roundcube to manage emails
