### ISSUE TITLE
Integrate with one-login

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1389]
https://onelogin.com/

Since using CRM's usually involves more than one software, it would be really helpful if we could have one-login for all.

**Comment by beppe9000** [comment]
Can't OAuth be used with that?

**Comment by mbeinder** [comment]
Would love to see configurable OAuth with OpenID Connect! Specifically and Okta Integration would be great!

**Comment by BlueBeN82** [comment]
Would also be great with KeyCloak :)

**Comment by beppe9000** [comment]
If a standard is added then interoperability benefits are for all.

**Comment by mbeinder** [comment]
I recommend SAML!

**Comment by mbeinder** [comment]
> Would love to see configurable OAuth with OpenID Connect! Specifically an Okta Integration would be great!

My recommendation is now SAML!

**Comment by beppe9000** [comment]
is there any simple saml php implementation? could you link to it ?

**Comment by mbeinder** [comment]
I'm not aware of any SimpleSAMLphp implementation for EspoCRM. I was just recommending SAML since it seems to be the most widely used.

**Comment by beppe9000** [comment]
I mean what can we use to self-host a lightweight identity provider in php that would work out of the box wih espo ?

**Comment by beppe9000** [comment]
> I'm not aware of any SimpleSAMLphp implementation for EspoCRM

There is this dude from the past... https://forum.espocrm.com/forum/developer-help/41519-help-submitting-saml-integration

**Comment by mbeinder** [comment]
> I mean what can we use to self-host a lightweight identity provider in php that would work out of the box wih espo ?

I'm not aware of an out of the box solution for espo. Espo is actually my legacy system and I'm running most of my new stuff on HubSpot.

My rough thoughts would be to build a small application that can set the authentication cookie for espo and not run identity yourself. I'm only familiar enough with SimpleSAMLphp to set it up as a service provider and not as an IDP.

**Comment by chaitanya-uc** [comment]
> Would also be great with KeyCloak :)

@yurikuzn any plans on adding this feature? Would really love if an interface can be provided.

**Comment by yurikuzn** [comment]
No plans.

**Comment by yurikuzn** [comment]
OIDC authentication is planned.
