### ISSUE TITLE
Can't login after upgrade

### ISSUE THREAD

**Issue by b1f17773** [espocrm/espocrm#1390]
Hello,
i don't know why but after upgrade to the newest version we can't log in to EspoCRM. We already tried to log in from many browsers and devices. We also check logs - there is no error.
In chrome console we have "app.js:616 GET https://domain.com/api/v1/ 401". 
When we trying to log in through web giu we have only error "Auth error"

**Comment by yurikuzn** [comment]
Hi,

Do you have windows server?

**Comment by b1f17773** [comment]
No, Linux :)

**Comment by b1f17773** [comment]
Here you have screenshot from command line, where i upgrated Espo:
https://i.imgur.com/xepM9S2.png

**Comment by b1f17773** [comment]
Here you have logs from today, but nothing from time when we tried log in.
```
[2019-08-10 11:45:51] Espo.ERROR: Uncaught Exception ParseError: "syntax error, unexpected ''grandTotalAmountCurrency' (T_ENCAPSED_AND_WHITESPACE), expecting ')'" at /data/cache/application/ormMetadata.php line 33216 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected ''grandTotalAmountCurrency' (T_ENCAPSED_AND_WHITESPACE), expecting ')' at /data/cache/application/ormMetadata.php:33216)"} []
[2019-08-10 11:46:02] Espo.WARNING: Cron is not run because it's disabled with 'cronDisabled' param. [] []
[2019-08-10 11:46:09] Espo.ERROR: ACL GlobalRestricton: Bad data fetched from cache. [] []

```
I also upgrated today SalesPack to the newest version.

**Comment by yurikuzn** [comment]
Try commenting out this line: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Auth.php#L329

**Comment by b1f17773** [comment]
@yurikuzn - yep, now i can log in.
In my file this line was #270 :) So that's all? My Espo after this change will be still secure?

**Comment by yurikuzn** [comment]
I have a bad time now.

**Comment by b1f17773** [comment]
@yurikuzn what do you mean by telling my that i have bad time now?

**Comment by yurikuzn** [comment]
I have big problems with this issue.

**Comment by b1f17773** [comment]
Maybe there is only issue with my instance..

**Comment by yurikuzn** [comment]
Do you have php 7.3?

**Comment by b1f17773** [comment]
@yurikuzn yep - that's right, 7.3

**Comment by rodrigoscoelho** [comment]
Upgraded to 5.6.11 here. Everything working OK.

Enviado utilizando um Galaxy S9...

Em sáb, 10 de ago de 2019 13:14, b1f17773 <notifications@github.com>
escreveu:

**Comment by b1f17773** [comment]
OK guys, thanks for informations. After upgrade to 5.6.11 everything is ok. Do i need to uncomment this line which i commented 2 days ago?

**Comment by yurikuzn** [comment]
No need to uncomment since upgrade did it too.

**Comment by b1f17773** [comment]
@yurikuzn thank you for your help
