### ISSUE TITLE
Import UI Issue

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1391]
&amp; is showing up

<img width="1231" alt="Screenshot 2019-08-11 at 8 46 37 PM" src="https://user-images.githubusercontent.com/4988946/62835726-3eab7700-bc79-11e9-9047-bf024ed92e18.png">

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/d5ee599f9fdb6c1aef63f09d59461e51d2378816
