### ISSUE TITLE
Import should use bulk insert

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1393]
Currently, import uses saveEntity which creates single row insert at a time. 

## Problem

If I am importing say 100,000 `lead`, for example, which contains `emailAddresses` and `phoneNumbers`

- 100,000 insert queries to insert lead
- 100,000 insert queries to insert emailAddresses
- 100,000 insert queries to insert phoneNumbers
- 100,000 insert queries to insert entity_email_address
- 100,000 insert queries to insert entity_phone_numbers

Total of 500,000 insert queries are needed to be run ignoring the inserts for process history records, relations etc... This makes import painfully slow.

My research on speed on inserts is here: https://stackoverflow.com/a/57452308

Proposed: Use bulk insert with multiple rows

Example,

```sql
Insert into `lead` (first_name, last_name) values 
('a', 'b'),  -- row 1
('c', 'd'),  -- row 2
('e', 'f');  -- row 3
```

For bulk update use `case` keyword.

Example,

```sql
update `lead` set first_name = (
  CASE id
    WHEN '5f232342d' THEN 'a'
    WHEN '243242dsf' THEN 'b'
  END
  ) WHERE id IN ('5f232342d', '243242dsf');
```

FYI, you need to think about how `beforeSave`, `afterSave` and hooks will work also

**Comment by yurikuzn** [comment]
Can't do it because of hooks.

**Comment by yurikuzn** [comment]
When run by cron it's not such a big deal.

**Comment by theBuzzyCoder** [comment]
Question: Can't you write a separate hooks for `bulkSave` and `bulkUpdate`? Is it something we can do?

**Comment by theBuzzyCoder** [comment]
> When run by cron it's not such a big deal.

It's a really big deal for my company because lot of our sales campaigns runs via CRM. Sometimes we have large target audiences that we need to reach out to in very short amount of time. Some of our clients refer lot of people and we try to reach out to them before certain time after which reaching out to them reduces sales by a big scale.

**Comment by yurikuzn** [comment]
I don't think it's a solution to have `bulkSave` hooks. It's feasible to make mass insert used but it will required a lot of work and testing. Can't do it in the nearest future.

**Comment by yurikuzn** [comment]
I recommend you to make cron run more often that once a minute. E.g. every 10 seconds.

**Comment by yurikuzn** [comment]
Did you try with 'execute in idle' and 'silent mode' checked. How much time it takes to import?

**Comment by theBuzzyCoder** [comment]
Understood. I will take this up and try to solve it on my own. When I have a solution, I will give it to you for code review.

> I recommend you to make cron run more often that once a minute. E.g. every 10 seconds.

This will not help because a single csv file will contain like 100,000 entries and single php cron.php will try to import all 100,000 entries. I can split the csv and import multiple but then I could run into the out of memory issue if I run too many jobs also.

**Comment by theBuzzyCoder** [comment]
> Did you try with 'execute in idle', 'skip searching for duplicates' and 'silent mode' checked. How much time it takes to import?

Yes. Without any extensions installed it took over 5 hours for 61,000 entries.

**Comment by yurikuzn** [comment]
Import should not take a lot of memory. 100,000 should not cause run out of memory.

**Comment by yurikuzn** [comment]
How much time when it run by cron (in idle)?

**Comment by yurikuzn** [comment]
It should be the matter of minutes, not hours.

**Comment by theBuzzyCoder** [comment]
Well, how much RAM do you think espocrm should have?

> How much time when it run by cron (in idle)?
Definitely took over 5 hours and still didn't finish 100,000 entries when I have only 3 fields first_name, last_name and email
<img width="1161" alt="Screenshot 2019-08-12 at 12 03 59 PM" src="https://user-images.githubusercontent.com/4988946/62848439-54f91780-bcf9-11e9-80ef-7a87c42f5152.png">
<img width="1161" alt="Screenshot 2019-08-12 at 12 04 14 PM" src="https://user-images.githubusercontent.com/4988946/62848441-5591ae00-bcf9-11e9-9235-dea39f9eb2ee.png">

**Comment by yurikuzn** [comment]
> RAM do you think espocrm should have?

I'm not sure. It depends on how you use it. I don't think it's important for import.

**Comment by yurikuzn** [comment]
It's way too much. I imported (with a custom script, not a bulk insert) about 230,000 leads with email addresses and it took me less than 15 minutes.

**Comment by theBuzzyCoder** [comment]
Can you please tell me what did you do? So, that I can use it

**Comment by yurikuzn** [comment]
Maybe it's because your tables are huge? Though I don't think it should affect on insert time.

**Comment by theBuzzyCoder** [comment]
I had empty espocrm database when I started import. I don't have any other databases in mysql

**Comment by theBuzzyCoder** [comment]
Have you configured mysql's settings or something? Or is it standard settings that comes along with mysql

**Comment by yurikuzn** [comment]
I populated database with the a random data. It also assigned teams, that is also quite expensive operation.

```php

include "bootstrap.php";

$app = new \Espo\Core\Application();

$entityManager = $app->getContainer()->get('entityManager');
$user = $entityManager->getEntity('User', 'system');
$app->getContainer()->setUser($user);

$allTeamIdList = [
	'5c5ddfc067713366e',
	'5c5ddf9183570bc5c',
	'5c5dcc24ebb494bf0',
	'5c5dcc1f2792eddff',
];

$dateList = [
	'2018-10-01 10:00:00',
	'2018-11-01 10:00:00',
	'2018-12-01 10:00:00',
	'2019-01-01 10:00:00',
	'2019-02-01 10:00:00',
];

$targetNumber = 30000;

$i = 1;
while (true) {
	$record = $entityManager->getEntity('Lead');
	$teamIdList = [];
	$teamCount = random_int(1, count($allTeamIdList));

	while (count($teamIdList) < $teamCount) {
		$teamIndex = random_int(0, count($allTeamIdList) - 1);
		$teamId = $allTeamIdList[$teamIndex];
		if (in_array($teamId, $teamIdList)) continue;
		$teamIdList[] = $teamId;
	}

	$emailAddress = randomString(8) . '@example.com';

	$record->set([
		'lastName' =>  base64_encode(random_bytes(8)),
		'teamsIds' => $teamIdList,
		'emailAddress' => $emailAddress,
		'testDate' => $dateList[random_int(0, 4)],
		'opportunityAmount' => 100.00,
		'opportunityAmountCurrency' => 'USD',
	]);
	$entityManager->saveEntity($record, ['silent' => true]);

	if ($i === $targetNumber) break;
	$i++;
}


echo "Number created: $i";


function randomString($length = 6) {
	$str = '';
	$characters = range('a','z');
	$max = count($characters) - 1;
	for ($i = 0; $i < $length; $i++) {
		$rand = mt_rand(0, $max);
		$str .= $characters[$rand];
	}
	return $str;
}
```

**Comment by yurikuzn** [comment]
> Have you configured mysql's settings or something? Or is it standard settings that comes along with mysql

No. It was kind of standard settings.

**Comment by theBuzzyCoder** [comment]
Is duplicate check expensive? I think I added duplicate check.

**Comment by yurikuzn** [comment]
Very expensive I believe.

**Comment by theBuzzyCoder** [comment]
Is it possible to add a feature called de-duplicate entries, so that we can insert by skipping duplicate checks and then select all entries and do a de-duplicate?

I know there is merge but, merge can be done only when the duplicate entries are known to user. If user doesn't know how many duplicates are there, it's a little difficult to merge.

**Comment by yurikuzn** [comment]
It's planned for future to add the ability to search for duplicates among existing records, but it won't be soon.
