### ISSUE TITLE
addJoin, leftJoin and join methods should prevent code from join a table more than once in SQL

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1394]
## Problem

I was trying to use list reports with workflow's assignment rules. In list report, I added fields assignedUser for lead. Now, I used this report to decide the assignment logic. It gave me that non-unique table. When I checked the sql it had two assignedUser joins. Turns out someone else also makes call to addJoin. It was the assignment rule logic.

**Comment by yurikuzn** [comment]
If recommend checking using hasJoin method.

**Comment by yurikuzn** [comment]
And always specify alias.

**Comment by karthik-uc** [comment]
@yurikuzn This issue didn't occur due to custom code. This happened when using reports and workflow assignment rules together. This should be an internal check in espocrm.

**Comment by yurikuzn** [comment]
That means there is an issue in reports or workflows. Can you advice how to reproduce?

**Comment by yurikuzn** [comment]
What report parameters.

**Comment by karthik-uc** [comment]
I will let you know here shortly. Let me type it out.

**Comment by yurikuzn** [comment]
I think I found the problem.

**Comment by karthik-uc** [comment]
BPM:
```
When Lead is Created,
If user has account name
Apply assignment rules, round robin for team-1 with list report: assignment for organization
otherwise
Apply assignment rules, round robin for team-1 with list report: assignment for individual
```

```
Report: assignment for organization
Type: List
Entity: Lead
Columns: Name, Assigned User, Created At, Account Name
Filters: Account name is not empty
Order by: Created At Desc
```

**Comment by yurikuzn** [comment]
Thanks.
