### ISSUE TITLE
Audit's should notify users only when required

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1397]
## Problem

Ideally, the field audits are used to track what happened in the record. It should not notify people because it just causes noise (too many notifications on every minor update).

## Suggestion

- The audit should just track when the field updates happened. 
- Add new option called `notifyOnChange` in `entityDefs` which will create notifications.

**Comment by yurikuzn** [comment]
I don't like the idea. It breaks and complicates the logic how notifications work.
