### ISSUE TITLE
Case merging issue

### ISSUE THREAD

**Issue by tonybyng** [espocrm/espocrm#1400]
Hi

I have 2 cases that were merged together and someone replied via email through to the case that was merged into the other case and consequently didnt get allocated to a case at all.  Does the system record the cases that have been merged somewhere so when an email comes in it can assign it to the right case by checking and seeing the id doesnt exist but then checking a historic list that says it was merged with a different id (even if I do it with an on save email hook rather than you changing code) ? Is the information available ? Thanks

**Comment by yurikuzn** [comment]
Hi,

An email contains a case id in 'References' header. Since case is removed (after a merge), received email can't be related to any record. Information about merge is not stored anywhere.

**Comment by tonybyng** [comment]
Hi
Thanks for the quick reply. Is there any way I can  identify with a hook when the merge happens so i can store the "before and after" case ids in a new entity? Then when an email comes in, on the "before save" i can see  that the case id its associated with is deleted and that will tell me to look at the log I create to pick up the correct parent id ?

**Comment by yurikuzn** [comment]
There is no hook, but there's afterMerge method that you can define in your custom Case's service class.

https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Record.php#L2396

**Comment by tonybyng** [comment]
As long as I can figure things out, that looks like it might just do what I need it to. Many thanks.

**Comment by tonybyng** [comment]
@yurikuzn Many thanks. That seems to be working. Im using the afterMerge to store the id's of any cases that were merged along with the details of the new "master" and when an email comes in and the case id for the email cant be found, i check the merge table and if i find it there, i swap the parent and it seems to be working ! Well happy !
