### ISSUE TITLE
How to send attachment through API?

### ISSUE THREAD

**Issue by b1f17773** [espocrm/espocrm#1406]
Hello
can anyone show me how can i send PDF file using PHP to EspoCRM through API? 
I can't find any examples in documentation or on forum

**Comment by yurikuzn** [comment]
Hi,

I recommend opening borwser console > network tab. Upload an attachment somewhere in EspoCRM (e.g. in Stream) and see what requests is sent to backend. You will need to replicate that request(s). Note, that there is an ACL check not allowing to create attachment to the record user doesn't have an access to.
