### ISSUE TITLE
Custom Person Entity & Case Email Functionality

### ISSUE THREAD

**Issue by dustyhansen** [espocrm/espocrm#1411]
I created a new custom person entity. 

I then created a many-to-one relationship between this entity and cases, essentially making a new contacts entity for a different use case.

When I have a case with a person entity record identified/linked to the record, I am not able to send an email to that person via the case. The "To:" field is blank, even though there is an email address populated on the person record.

**Comment by rabiibrahimi** [comment]
did you check if the entity person has an email saved on its record.

**Comment by yurikuzn** [comment]
Implemented: https://github.com/espocrm/espocrm/commit/fabaccd3da2f37acf42e6efd4876392adf2f760e
