### ISSUE TITLE
Portal Roles Broken for Custom Entities

### ISSUE THREAD

**Issue by dustyhansen** [espocrm/espocrm#1412]
I have custom entities created that have relationships back to the contact entity.

I have the portal role setup to allow read access of that entity for records in which I am a contact. 

When I log into the portal as that contact, none of those records are displayed. The only way to see records for custom entities appears to be to allow "read all".

**Comment by yurikuzn** [comment]
You can check how it works: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/AclPortal/Base.php#L182

**Comment by yurikuzn** [comment]
I don't think it's broken.

You can customize ACL to suit your needs: https://github.com/espocrm/documentation/blob/master/development/acl.md#portal-acl

**Comment by yurikuzn** [comment]
If you renamed just label -- not possible.

**Comment by yurikuzn** [comment]
I tested custom entity and it worked fine.
