### ISSUE TITLE
IMAP with zimbra fails

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1417]
I see that espocrm always uses 'LOGIN' to do the login. My zimbra server needs 'AUTHENTICATE' since it's the only method enabled in capaabilities. I think email settings should be more similar to standard desktop clients that allow to choose the proper authentication method.

**Comment by yurikuzn** [comment]
IMAP or SMTP?

**Comment by beppe9000** [comment]
I'm only using IMAP in this case, but selection of the authentication method should be made available for both imho. Or made automatic based on server capabilities.

The connection test for imap in espo fails, but I was able to connect with telnet like this:

```
* OK IMAP4 ready
d0 capability
* CAPABILITY ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE IMAP4rev1 LIST-EXTENDED LITERAL+ MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN AUTH=PLAIN STARTTLS
d0 OK completed
a0 authenticate
a0 BAD invalid command
D1 AUTHENTICATE PLAIN
+
A13g317r3h1798rh193rh9137rh97139r1h3r791h3r97h1397=
D1 OK [CAPABILITY IMAP4rev1 ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST] AUTHENTICATE completed
* BYE store002.vodafone.nanosoftcloud.it Zimbra IMAP4rev1 server closing connection


```

**Comment by yurikuzn** [comment]
Zend Mail lib, that we use, doesn't support other than login mechanism.

**Comment by beppe9000** [comment]
the [docs ](https://docs.zendframework.com/zend-mail/transport/smtp-authentication/#connection_class)say it supports `PLAIN` login `Zend\Mail\Protocol\Smtp\Auth\Plain`

**Comment by yurikuzn** [comment]
SMTP, not IMAP.

**Comment by beppe9000** [comment]
isn't it the same ?

**Comment by yurikuzn** [comment]
It's not the same.

**Comment by yurikuzn** [comment]
Command `grep -R '\\Imap' application` gave me results

```
application/Espo/Services/EmailAccount.php:        $storage = new \Espo\Core\Mail\Mail\Storage\Imap($imapParams);
application/Espo/Services/InboundEmail.php:        $storage = new \Espo\Core\Mail\Mail\Storage\Imap($imapParams);
application/Espo/Services/InboundEmail.php:        $storage = new \Espo\Core\Mail\Mail\Storage\Imap($imapParams);
application/Espo/Services/InboundEmail.php:        $storage = new \Espo\Core\Mail\Mail\Storage\Imap($imapParams);
application/Espo/Services/InboundEmail.php:        $storage = new \Espo\Core\Mail\Mail\Storage\Imap($imapParams);
application/Espo/Core/Mail/Mail/Storage/Imap.php:class Imap extends \Zend\Mail\Storage\Imap

```

**Comment by beppe9000** [comment]
Can I override `application/Espo/Core/Mail/Mail/Storage/Imap.php` with the `custom` folder ?

**Comment by yurikuzn** [comment]
Please look into the code. I provided the list of files

**Comment by yurikuzn** [comment]
Maybe you need to override Service class in custom.

**Comment by beppe9000** [comment]
I would override `\Espo\Services\EmailAccount::getStorage` method to use a subclass of `\Espo\Core\Mail\Mail\Storage\Imap` that uses a subclass of `\Zend\Mail\Protocol\Imap` that I modified to do `PLAIN` auth instead of `LOGIN` based on host name.

**Comment by beppe9000** [comment]
In the end I deployed a proxy since I never got the code below to work...

`<?php

    namespace Zend\Mail\Protocol;

    class PlainImap extends Imap
    {
        public function login($user, $password) {

            if (mb_strtolower($user) === 'me@me.me') {
                $r1 = $this->requestAndResponse('AUTHENTICATE', ['PLAIN'], true);
                $ld = base64_encode("\0" . $user . "\0" . $password);
                return $this->requestAndResponse($ld);
            }

            return $this->requestAndResponse('LOGIN', $this->escapeString($user, $password), true);
        }
    }
`
