### ISSUE TITLE
add new task fails 

### ISSUE THREAD

**Issue by Idyahiaa** [espocrm/espocrm#1419]
hello everyone  ,
can you help me to resolve this problem Please 

when i add the function "Multiple Assigned Users" according to this tuto https://github.com/espocrm/documentation/blob/master/administration/multiple-assigned-users.md it works with existing taks i can assign task to multiple user but when i
i want to add a new task it give me this error "Erreur 400 bad request " and the record is not added

thank you

**Comment by yurikuzn** [comment]
I think it was a required field check. It must be printed in log. Need to uncheck "Required" field for Assigned User field in entity manager.
