### ISSUE TITLE
Possibility to edit a date and hour on stream

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#142]
It would be good to add the possibility to change the date and hour of a posted stream note. Like we can do on zurmo.

**Comment by yurikuzn** [comment]
We don't think that we need this feature.

**Comment by rodrigoscoelho** [comment]
@yurikuzn 
The stream is indexed by the date and hour of post. right? 
Sometimes, you would like to post something that happened last day, and this is not possible.
Maybe would be good to have this possibility. 

In my case, I work with consultancy, not Marketing and Sales, so, I use the Stream to post everything I did on that possible project. Some times I write something from last week today, just to maintain the chronology.

Is it possible to reconsider?

**Comment by yurikuzn** [comment]
Stream record list is sorted by internal autoincrement number, not by date. It's a blocker for this feature.
