### ISSUE TITLE
How to wipe informations from other entities

### ISSUE THREAD

**Issue by b1f17773** [espocrm/espocrm#1420]
Hello
how can i decide which entity have fields which should be wiped, for example tasks?

**Comment by yurikuzn** [comment]
I recommend posting our forum. And explain more explicitly.

**Comment by b1f17773** [comment]
@yurikuzn  i already added post, and i didn't have any reply https://forum.espocrm.com/forum/developer-help/47236-how-to-mark-text-area-field-available-for-erase
