### ISSUE TITLE
Invalid escaping chars in menu

### ISSUE THREAD

**Issue by alefbt** [espocrm/espocrm#1421]
After update 5.6.10~ appears escaping issue. 

in translation file po there is translation that include character `"` (Example: `ab"c`)
it should appear on menu or content lables as `ab"c`
but currently it appears as `ab&quot;c`

There are some languages that use `"` as symbol for acronyms

**Comment by yurikuzn** [comment]
The last version is 5.6.12. Does this issue appear in the last version?

**Comment by alefbt** [comment]
Unfortunately, yes.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/83fa22852afcd380a3553fde7bbde496a1369c56
