### ISSUE TITLE
Convert Lead: Duplicate check

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1422]
Problem:

As of now convert lead doesn't do duplicate checks in contact.

If one agent creates contact and lead gets captured by some other means and lead is converted by another agent then, new contact gets created instead of updating the existing one.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/ec4e86c3320ed0699513f948150d9398d3c2602d
