### ISSUE TITLE
api response only max 200 results

### ISSUE THREAD

**Issue by h133gqa** [espocrm/espocrm#1424]
Hi, 
we have an installation with about 400 contact entries, but we can't use the API as we always get only 200 results maximum. 
Is there a way to increase the payload result from API? 

thanks, Andy

**Comment by yurikuzn** [comment]
Hi Andy,

Parameter 'recordListMaxSizeLimit' in data/config.php

https://github.com/espocrm/espocrm/blob/f8d9548ed5747cebb61423a9993ceb9a537c3c86/application/Espo/Core/Controllers/Record.php#L133

How I found it. I used github search with `200` keyword.

**Comment by yurikuzn** [comment]
But I'd recommend using `offset` and `limit` params doing multiple requests.
