### ISSUE TITLE
Erasing attachments

### ISSUE THREAD

**Issue by b1f17773** [espocrm/espocrm#1427]
Is there any chance to use erasing mechanism regarding to attachments? 
Attachments usualy store some personal informations. It will be great to erase them in some cases.

**Comment by yurikuzn** [comment]
Administration > Attachments.

If you remove record, all related attachments will be removed by cleanup job after some period of time.

**Comment by b1f17773** [comment]
For example i want to erase data from entity CASE. Is there any chance to erase everything(also related attachments) by only erasing record in cases entity?

**Comment by yurikuzn** [comment]
I'm not sure, hope all will be removed eventually by cleanup. I need to read code to answer. I have no time.

**Comment by b1f17773** [comment]
Can you check that for me for example in next week?

**Comment by yurikuzn** [comment]
Why not checking it by yourself? 

https://github.com/espocrm/espocrm/blob/master/application/Espo/Jobs/Cleanup.php#L189

**Comment by yurikuzn** [comment]
Attachments will be removed.
