### ISSUE TITLE
Currency Rates Fixed for a Date

### ISSUE THREAD

**Issue by velirs** [espocrm/espocrm#1429]
When we use Multi Currency, Currency Rates Change may affect all Opportunity, I guess

Can we have a Currency Rates; for a Date to Date ? 
or how the currency Rate works ?

**Comment by yurikuzn** [comment]
Actually an opportunity record is not affected. Just a calculation of the converted (to default) value is affected. You can convert currency to the default after a while (it will be possible automatically with workflow) or have another field where you will copy converted value with formula.

Assume you have created a field `amountConvertedLocked`.

Formula (before save script):
```
amountConvertedLocked = amountConverted;
amountConvertedLockedCorruncy = 'USD';
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/documentation/blob/master/administration/currency.md
