### ISSUE TITLE
What is the default ordering of entities returned by a find operation?

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1430]
I am implementing a multiple-run scheduled job so I need to be able to pause and resume. 

**What is the default ordering of entities when returning data for a `$repository->find();` call?**

I think the order here takes a lot of time when `ELEMENTS_PER_CYCLE` is big, so I wanted to remove it if the default ordering is consistent between runs:
`$jobEntities = $repo -> order('createdAt', 'ASC') -> limit($offset, ELEMENTS_PER_CYCLE) -> find();`

**Is it safe to rely on the default ordering like this ?**
`$jobEntities = $repo -> limit($offset, ELEMENTS_PER_CYCLE) -> find();`

<hr>

**PS: If I store an offset for subsequent runs, how can I handle the deletion of entities?**

If my saved offset is 10 because it parsed 10 entities but one is deleted I would end up skipping the 11th entity.

I can fetch deleted entities too (`where(['withDeleted'=>true])`) to ignore that, and then check every entity for `deleted==false`. Yet, this moves the problem to when the cleanup cron job will be run, resulting in my job to suffer the same issue as before... making this ugly.

<hr>

Is there any Espo job I can take inspiration from ?

Thanks for all

**Comment by yurikuzn** [comment]
There's no default order there. It's like making SQL SELECT request w/o ORDER statement.

You need to add an INDEX for created_at column. In entityDefs you can set  `"index": true`. If query will still be executing slow, you will need to explicitly with the param `useIndexList`.
```
->find(['
    'useIndexList' => ['createdAt']
']);
```

Where createdAt is INDEX name.

**Comment by beppe9000** [comment]
I will do that. As for the other problem do you have any insight?
