### ISSUE TITLE
Email: Storing sent emails on IMAP not working

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1456]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/29bec8fcd661892d3805821bde1a37c68414925b

**Comment by simpt0ms1** [comment]
hello  yurikuzn i've been trying to contact you, do you have an e-mail? i've tried contacting you at yuri@letrium.com but it was no longer active.
