### ISSUE TITLE
Why keep User entity ACL hardcoded ?

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1458]
I see [here](https://forum.espocrm.com/forum/developer-help/37851-creating-and-editing-user-without-giving-administration-access) that extensive modification is needed to treat users as a normal entity. A more reasonable alternative could be to have a boolean setting in the config.php file to toggle that.

I believe the only thing that should be kept hardcoded is that users must be admin to edit other admins or change admin status of users.

What seems most unusual to me is for that to be hardcoded in the client as well.

**Comment by yurikuzn** [comment]
User is not a normal entity. User doesn't have assigned user, user doesn't have teams.

You always can customize ACL, It's simple.
