### ISSUE TITLE
Ability to define favicons and meta description in themes json files

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1459]
https://github.com/espocrm/espocrm/blob/48652e35eef2d2fa2548806ee03d437d807f75ba/html/main.html#L9-L14

Managing favicons and description like css files in themes would allow to make those modifications in a upgrade safe way. And if not specified they should default to their current values.

**Comment by yurikuzn** [comment]
WIll be possible to define in metadata: https://github.com/espocrm/espocrm/commit/575cdf8f5b8eff2277604af3eb7566b8aead69d9

Not in theme.

**Comment by beppe9000** [comment]
great! as long as they can defined in custom 👍
