### ISSUE TITLE
logo fallbacks should be loaded from theme for consistency

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1466]
https://github.com/espocrm/espocrm/blob/814f79d53bfcfec8c06489896469e3230b921c11/client/src/views/login.js#L59-L65

it should fall back to theme defined logo like this:

https://github.com/espocrm/espocrm/blob/ea15452db47da8b7373c6c37c222cc0ed9dcf27d/client/src/views/site/navbar.js#L176

**Comment by yurikuzn** [comment]
Metadata is not available on a login a screen. I don't consider it as a problem.

**Comment by beppe9000** [comment]
If no logo is explicitly set there will be different logos.

**Comment by yurikuzn** [comment]
Yes. I know. It's how i supposed it to be.

**Comment by yurikuzn** [comment]
Logo in theme was for another purpose. To fit into smaller space for vertical navbar theme.

**Comment by beppe9000** [comment]
Thanks now it's more clear
