### ISSUE TITLE
Possibility to Clone (duplicate) a record

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#147]
Hi,

It would be good to have the possibility to clone or duplicate a record. Like a Project (custom entity), we sometimes need to start a new project (new record) using another one as template.

The same could be useful for Opportunities....

**Comment by yurikuzn** [comment]
It's already implemented for some entities. E.g. Meetings, Calls. You can try to replicate it for your entities.

**Comment by rodrigoscoelho** [comment]
I couldn't find it. 
I looked at espocrm/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Call.json but didn't find it.

Is it in a PHP file? 

Thank @yurikuzn

**Comment by yurikuzn** [comment]
client/modules/crm/src/views/task/record/detail.js

or 

views/record/detail.js

duplicateAction: true

**Comment by yurikuzn** [comment]
In the next major release it will be available for all entity types by default.
