### ISSUE TITLE
Issue with upgrade 

### ISSUE THREAD

**Issue by b1f17773** [espocrm/espocrm#1476]
Hello.
I have problem with upgrade EspoCRM from 5.5.6 to 5.6.14.
In logs i have only this:
```[2019-10-19 17:49:00] Espo.ERROR: Database rebuild failure, details: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away. [] []
[2019-10-19 17:49:20] Espo.ERROR: API [POST]:/:controller/action/:action, Params:Array (     [controller] => Admin     [action] => runUpgrade ) , InputData: {"id":"XXXXXXXXXX"} - Error occurred while EspoCRM rebuild. [] []
[2019-10-19 17:49:20] Espo.ERROR: Display Error: Error occurred while EspoCRM rebuild., Code: 500 URL: /api/v1/Admin/action/runUpgrade [] []```

**Comment by b1f17773** [comment]
Update take like 10 minutes, and i have in web gui error "Error: Error occurred while EspoCRM rebuild."
After i reloaded website, i still see 5.5.6 version

**Comment by b1f17773** [comment]
Also when i tried to use ssh command: php command.php upgrade, i saw this error:
```Fatal error: Call to undefined method Espo\Core\Application::runCommand() in /home/emillod/domains/biuro.emillo.pl/public_html/command.php on line 39```

**Comment by b1f17773** [comment]
Also when i tried to use ssh command `php command.php upgrade`, i saw this error:
```Fatal error: Call to undefined method Espo\Core\Application::runCommand() in /home/XXXXXX/domains/XXXXXXXXXXXXXXX/public_html/command.php on line 39```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/documentation/blob/master/administration/upgrading.md#upgrade-from-cli

The second line: "Available from version 5.6.0."

**Comment by b1f17773** [comment]
@yurikuzn ok - my mistake, i can't update through API - no problem. But still, i can't update through web gui. **Can you help me?**

**Comment by b1f17773** [comment]
@yurikuzn i tried another method from this turorial and i still have error:
```
php73 upgrade.php ./EspoCRM-upgrade-5.5.6-to-5.6.14.zip
Current version is 5.5.6
Start upgrade process...
Error: Error occurred while EspoCRM rebuild.
```

**Comment by tmachyshyn** [comment]
@b1f17773 Please go to Administration > Rebuild and check if rebuild is successful. If not, check a log file for details.

**Comment by b1f17773** [comment]
@tmachyshyn  i already did that. I can rebuild and clear cache from web gui, but i still can't upgrade espo to the newest version..

**Comment by tmachyshyn** [comment]
> @yurikuzn i tried another method from this turorial and i still have error:
> 
> ```
> php73 upgrade.php ./EspoCRM-upgrade-5.5.6-to-5.6.14.zip
> Current version is 5.5.6
> Start upgrade process...
> Error: Error occurred while EspoCRM rebuild.
> ```

What error logs while this upgrade?

**Comment by b1f17773** [comment]
@tmachyshyn in CLI i have:
```
Current version is 5.5.6
Start upgrade process...
Error: Error occurred while EspoCRM rebuild
```
in logs i see:
```
[2019-10-21 07:53:32] Espo.ERROR: Database rebuild failure, details: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away. [] []

```

**Comment by tmachyshyn** [comment]
Try to increase your MySQL limits.

**Comment by b1f17773** [comment]
Are you sure that this is a problem? I have on the same hosting another instance of EspoCRM with the newest version and there is no problem with updates or mysql limits..

**Comment by tmachyshyn** [comment]
I think, it's the problem of your MySQL. Please use our forum for such problems.
