### ISSUE TITLE
Bug with HTTPS

### ISSUE THREAD

**Issue by b1f17773** [espocrm/espocrm#1477]
I don't know why but despite the fact that in config file i entered url of EspoCRM with prefix https://, i still can login to EspoCRM using http.

Please fix this, because there should be some additional rule which will require encrypted connection if it's possible. I'm using simple `.htaccess` rule, but i need to add this every time after update. It's really annoying.

.htaccess rule:
```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by yurikuzn** [comment]
It's not a bug.

**Comment by yurikuzn** [comment]
You can move your rule out of .htaccess. Don't change .htaccess.

**Comment by b1f17773** [comment]
Where i can move out of .htaccess this rule?

**Comment by bandtank** [comment]
Your webserver’s configuration should be handling this. Apache, for example, should route http requests to https based on a site configuration.
