### ISSUE TITLE
API Error: EspoCRM API unavailable.

### ISSUE THREAD

**Issue by Mysticsam** [espocrm/espocrm#148]
I am trying to install EspoCRM.
I am using FreeBSD 10.3 with apache 2.4 php 5.5 mysql 5.5. 
Now am getting this error :

API Error: EspoCRM API unavailable.
Possible problems: disabled "mod_rewrite" in Apache server, disabled .htaccess support or RewriteBase issue.
Do only necessary steps. After each step check if the issue is solved.

1. Enable "mod_rewrite". To do it run those commands in a Terminal:

a2enmod rewrite 
service apache2 restart

2. Enable .htaccess support. Add/edit the Server configuration settings (apache2.conf, httpd.conf):

<Directory /PATH_TO_ESPO/>
 AllowOverride All
</Directory>

Afterwards run this command in a Terminal:

service apache2 restart

3. Try to add the RewriteBase path, open a file api/v1/.htaccess and replace the following line:

# RewriteBase /

To

RewriteBase /api/v1/

Because a2enmod doesn't exist anymore as of Apache 2.4 i cant do the first step but i have done all others and it still doesn't work. 

Do i have to have Apache 2.2 to be able to install this?

**Comment by tmachyshyn** [comment]
Did you do all there steps?

**Comment by drewcaplan** [comment]
Did you ever get this fixed? I am experiencing the same issue.

**Comment by karCrasche** [comment]
Any hints on how to get this resolved and move on with the installation?

**Comment by karCrasche** [comment]
To move forward, I edited the apache2.conf and changed AllowOverride none to AllowOverride All and this allowed me to move forward.
Very frustrating and probably not the right solution.
/etc/apache/apache2.conf
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
