### ISSUE TITLE
To add the possibility to add a follower... 

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#149]
It would be great to have a possibility to add an user to follow an opportunity, for example. 
At least when you comment something on the stream, informing a username (@username), to add him as follower automatically. 
Maybe only some group of users could add a new follower.

**Comment by yurikuzn** [comment]
Users might be displeased if somebody managed what they need to follow. It would require sort of ajustable control level to allow/restrict such an ability.
