### ISSUE TITLE
export Report as XLS fails when 2FA enabled

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1491]
Example : GET https://......?entryPoint=download&id=5db8503c0ee53eb66

Results in :  HTTP 401 with payload : {"status":"secondStepRequired","message":"enterTotpCode","view":null,"token":null}

**Comment by yurikuzn** [comment]
Does a regular export (from the list view) work?

I could not reproduce the issue yet.

**Comment by relyd** [comment]
Strange : I run two instances (copy) at 5.7.6 : 
both have TOTP enabled.

Both send same request to  : POST /api/v1/Report/action/exportList HTTP/1.1
and one returns 
  HTTP/2.0 401 Unauthorized , x-status-reason: second-step-required
the other instance returns
  200 OK

The not working instance has mailchimp extension active (1.04)
2FA has been disabled and enabled again.

Thank you for any pointer

**Comment by yurikuzn** [comment]
Does a regular export (from the list view) work?

**Comment by relyd** [comment]
No 
Request URL: /api/v1/Account/action/export
Request method:POST

Leads to 
?entryPoint=download&id=5db939ccb6a81878f with a 404

Testing a bit further this behaviour also happens also to users that did not set up 2FA, so I am forced to disable 2FA for now.

**Comment by yurikuzn** [comment]
> Testing a bit further this behaviour also happens also to users that did not set up 2FA, so I am forced to disable 2FA for now.

I don't understand.

**Comment by relyd** [comment]
What I mean is that even for users that did not yet activate 2FA the behavior is the same and the download of the export fails. 
Checking the https://myhost/#Attachment shows the export file has been generated:
https://myhost/#Attachment/view/5db939ccb6a81878f

**Comment by yurikuzn** [comment]
We always recommend checking server and espo log.

**Comment by analystcmyk** [comment]
Cannot reproduce in later versions, please close.
