### ISSUE TITLE
Dynamic extra field like the ones on "Email" and "Phone"

### ISSUE THREAD

**Issue by ciucaadrian11** [espocrm/espocrm#1492]
Hello dear,

Please help me in my request. I have no knowledge of development and I am new to using espocrm but I like very much this software. I use free version of software. I have not bought any package.
I would like to know how to have "Adding Button" to add dynamic extra field like the ones on "Email" and "Phone". I want to be able to add extra field under "varchar" and "Date" and of course to be recorded to db.

It is there someone who has the necessary files with the codes/scripts? and where I have to place those files.

Thank you in advance for your support!
![image](https://user-images.githubusercontent.com/57172223/67843428-9fbe4a80-fb04-11e9-8d3c-1156c1e8b6dc.png)

**Comment by yurikuzn** [comment]
Hi,

It's not simple to do. For varchar I recommend using Array field instead.

**Comment by ciucaadrian11** [comment]
Thank you for the answer. I used Array. After I have introduced the values as in bellow example>

Value 1
Value 2
Value 3

and after I save the form, the values appear in string: ex VALUE 1, VALUE 2, VALUE 3.

It is there an option to appear the values below one another like?:
VALUE 1
VALUE 2
VALUE 3

Thank you very much for support!
