### ISSUE TITLE
runAs for API user

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#1494]
When integrating EspoCRM into other apps using the REST-API one could only configure fixed roles for access control. This limits the use cases in real live since in many cases the application accessing the API acts for a specific end user which is already authenticated somewhere else.
It would enable real live application integration if a API user could be allowed/enabled to send the user name with the request should runAs (downgrade). Otherwise API integration could not benefit from the permission and team concept defined in EspoCRM.

**Comment by yurikuzn** [comment]
I don't like the idea. One users -- one permissions. I don't see any problems with this.

**Comment by hi-ko** [comment]
But how should  an application enforce the permissions for a request on behalf for an end user if the app only has authentication for it's own api user?

**Comment by hi-ko** [comment]
application=backend application. UI/client integration is not sufficient for backend processes.

**Comment by yurikuzn** [comment]
If we ever implement this, it definitely should not be an ability to run as another user.

**Comment by hi-ko** [comment]
that's the way other enterprise apps work. What's your suggestion to integrate services to call the REST API on behalf for an end user?

**Comment by hi-ko** [comment]
We already discussed an Espo specific integration implementing something like a "getAuthTokenForUser()" and to pool these tokens for _every_ user involved in calls on the other service but I don't like this approach either ...

**Comment by hi-ko** [comment]
so what is your point / what are your concerns stating: 

> it definitely should not be an ability to run as another user

That's the way how enterprise apps implement authorization for service/API integration. Of course it should require some hardening like limiting runAS for specific Tokens, IPs configured in server files not writable by espo etc. to avoid attack vectors over http.

**Comment by yurikuzn** [comment]
You want to have single API user to be able to run as multiple regular users? This users will represent users of the application?

**Comment by yurikuzn** [comment]
Or you want to have a few users with different roles? And the problem that in this case you will need to store an API Key for each.

**Comment by hi-ko** [comment]
I'm not sure if I got your question.

> You want to have single API user to be able to run as multiple regular users? 
exactly

> These users will represent users of the application?

These users, the API user wants to runAs on behalf, will represent SSO users (which means one app trusts the other app). Since some permissions are granted to the user it may not be sufficiant to configure roles on the fly. The requirement is meant as:
The end user authenticated somewhere in the enterprise infrastructure needs to run something in the backend of another appliacation (app-B) with the _authorization_ for this end user, although app-B has only api-user authentication with username "app-B".

**Comment by yurikuzn** [comment]
You can create a custom implementation for Hmac authentication class: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Authentication/Hmac.php

create `\Espo\Custom\Core\Utils\Authentication\Hmac` class in custom folder.

$request object is passed into login method. You can pass username in some header and then fetch it from $request. Then return $user.

**Comment by hi-ko** [comment]
as you wrote this creates _authentication_ to solve e.g. #1493
It may be a work around to authenticate _every_ request coming from another app on behalf of a real user (generating thousands of auth tokens in espo) but I would prefer a method to downgrade _authorization_ from an admin user to a "real" user. So authentication is some admin but permissions, roles are taken from the provided runAs user.

**Comment by yurikuzn** [comment]
This would require a lot of changes in the application. That will be difficult and risky to break something.

**Comment by hi-ko** [comment]
I understand your concern but this prevents application integration where end user permissions should be enforced (which I asume should be the default). This means as long there is no implementation for runAs every application accessing the espo REST-API has to authenticate for every end user the request is done on behalf implementing some new Hmac authentication. To avoid thousands of tokens in Espo this application should cache and reuse tokens returned by the user login.

**Comment by yurikuzn** [comment]
Api user doesn't use tokens. Only api key and api secret passed in header. It's quite secure.

**Comment by yurikuzn** [comment]
Using admin user for API requires -- this is what I wouldn't recommend doing.

**Comment by hi-ko** [comment]
That's the discussion we had in the [forum](https://forum.espocrm.com/forum/developer-help/52534-runas-on-rest-api-with-api-user) but doesn't help us for a solution if _user_ permission / authorization is required which I guess is expected for many integration scenarios.
Imagine you limit e.g. the access on entity cases

- visibility for teams
- updateable for the assigned user

If the another app want's to update the status or to add a relation the role or team will not allow to do this or even worth: how to enforce the visibility on cases for users of other teams not granted on that case? To configure teams and roles on api-user doesn't solve this.

That's the reason why I think the only (expensive) option by today is to implement a new method to create an authentication (token) as admin for a real user and to cache/use/manage these tokens depending on the user you want the _authorization_ for and run the request from the other app with the user token.

**Comment by hi-ko** [comment]
Customized authentication is a work around which will enforce authentication for every request since every application api request could be for another user (if authentication is not cached for every user by the appliaction using the api). Don't you think this is an issue?

**Comment by bandtank** [comment]
I’ve wondered about this as well. I don’t use the API user because I want Espo to enforce permissions and rules automatically. The API user doesn’t know which user is attempting to access information, so it doesn’t limit what can be queried as far as I can tell. I pass user credentials/tokens to the API for each user from a custom application, so the roles, teams, etc. are enforced.

Maybe I am misunderstanding the point of the API user, but I don’t really see a reason to use it at the moment. Everything in a CRM has permissions and the API user doesn’t have a way to know about them.

**Comment by yurikuzn** [comment]
* API Users do have roles (and permissions), the same way as regular users have. Only *own* level permission doesn't work for them.
* API Users are not available in the system for things like assignment, mentions etc. They are listed separately.
* API User do have support HMAC authentication that it more secure than passing user/password through the net.
* API Users supports webhooks. Regular users don't.

**Comment by bandtank** [comment]
I saw that in the release and it makes sense, but I still don't understand why I would use the API user. My users login to a custom application and then fetch their own data. The API user doesn't limit the data to what they can see, which means I have to do it for them. It makes more sense to me to have the user login as himself because Espo will take care of the data automatically based on roles, permissions, etc.

**Comment by yurikuzn** [comment]
For your case there's no reason to use.

**Comment by yurikuzn** [comment]
> Customized authentication is a work around which will enforce authentication for every request since every application api request could be for another user (if authentication is not cached for every user by the appliaction using the api). Don't you think this is an issue?

There will be api key & secret stored in your application. When you make a request to EspoCRM, you will add a custom header with a user name. For Hmac authorization there will no auth token be returned by API request. Only one request, all authentication data withing this single request.

**Comment by yurikuzn** [comment]
Through, I didn't test it, not 100% there won't be any problems.
