### ISSUE TITLE
Container: Preload on application start

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1495]
# Problem

I want to add custom listeners when the application starts and these listeners basically listen to different types of events/signals like errors. When an error occurs the listener notifies me through any communication channel like email, slack or anything else.

# Suggest

```php
class Container
{
  public function __construct()
  {
    $this->preload();
  }

  public function preload()
  {
    $preloadList = $this->get('metadata')->get(['app', 'preload']);
    foreach ($preloadList as $preloadItem) {
      $this->get($preloadItem);
    }
  }
}
```

`metadata/app/preload.json`

```json
{
    "errorEventManager"
}
```

**Comment by karthik-uc** [comment]
`metadata/app/preload.json`

```json
{
    "errorEventManager",
}
```

**Comment by karthik-uc** [comment]
An example for this is sentry

```php
require_once __DIR__ . "/vendor/sentry/sentry/lib/Raven/Autoloader.php";
Raven_Autoloader::register();

$sentryDsn = $app->getContainer()->get("config")->get("sentryDsn");

if ($sentryDsn) {
    $client = new Raven_Client($sentryDsn);
    $client->setRelease(Raven_Client::VERSION);

    // For explicilty capturing exceptions
    $GLOBALS['sentry'] = $client;
    $logLevel = $app->getContainer()->get('config')->get('logger.sentryLevel', 'NOTICE');
    $logLevelCode = $GLOBALS['log']::toMonologLevel($logLevel);

    $handler = new \Monolog\Handler\RavenHandler($client, $logLevelCode);
    $handler->setFormatter(new \Monolog\Formatter\LineFormatter("%message% %context% %extra%\n"));
    $GLOBALS['log']->pushHandler($handler);

    $GLOBALS['log']->pushProcessor(function ($record) {
        return $record;
    });
}
```

**Comment by yurikuzn** [comment]
I'd recommend using ZMQ and running daemon that will listen to signals.

**Comment by yurikuzn** [comment]
Anyway, the ability to autoload was in my mind a few times before. I always found that this approach was not the best for those cases I had, and I opted to other solutions. Maybe I will add it, I need to investigate and think it over first.

**Comment by karthik-uc** [comment]
Thanks for the suggest. If you could share an example of how ZMQ or daemon can be used in this scenario, that would be really helpful!

**Comment by yurikuzn** [comment]
This is how websocket work in EspoCRM. You can search with 'websocket' keyword here on github.

**Comment by karthik-uc** [comment]
@yurikuzn I still prefer preload because in the above code which I put for sentry, I just had to add a handler to `$GLOBALS['log']`. And whenever `$GLOBALS['log']->error()` is called it will just report the error to sentry. Also, you do `$GLOBALS['log'] = $this->getContainer()->get('log');`. This can be a preload functionality as you've to load it everytime a container is created!

With ZMQ and daemon, on the otherhand, I need to write a listener first. Then I need to write a pusher that pushes information the socket.

**Comment by yurikuzn** [comment]
`application/Espo/Resources/metadata/app/containerServices.json`

```json
{
    "someName": {
        "className": "\\Espo\\Custom\\Core\\Utils\\SomeName",
        "dependencyList": ["config", "metadata"],
        "preload": true
    }
}
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1531

**Comment by theBuzzyCoder** [comment]
@yurikuzn Thanks for deploying it at the earliest. It is a big help for us.
