### ISSUE TITLE
Cannot Create API User

### ISSUE THREAD

**Issue by mbeinder** [espocrm/espocrm#1499]
I just updated to version 5.7.6 and am now trying to experiment with webhooks. However to do so I needed to create a new API user for testing. Now I cannot create an API user as the request is sent but no response is sent back to the frontend.

I also cannot create any new entries in all of my entities.

**Comment by yurikuzn** [comment]
We always recommend checking logs first https://github.com/espocrm/documentation/blob/master/administration/troubleshooting.md

**Comment by mbeinder** [comment]
I re-ran the update script and everything seems to be working normally now.
