### ISSUE TITLE
Iframe dashlet

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1500]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c4bfa05e2fb5c493427aa7d09bb67b801584686a

**Comment by OlofBailey** [comment]
Is it possible for this to replicate the Sugar capability where the Iframe element can be used within entities and element variables can be passed to the IFrame URLs?

**Comment by yurikuzn** [comment]
No.

**Comment by jackwharrison** [comment]
Does this still exist? I can no longer see it available

**Comment by yurikuzn** [comment]
Yes. 
![image](https://github.com/user-attachments/assets/ee27cbb1-14cf-448a-874b-a726c9c01c97)

**Comment by jackwharrison** [comment]
I am on 8.2.5 and do not see it:
![image](https://github.com/user-attachments/assets/e118141e-0c6c-4d80-a57c-265c7696a337)

**Comment by yurikuzn** [comment]
Something with your instance. Maybe missing source files. I recommend using forum for more help. It's off topic here.

**Comment by bandtank** [comment]
@jackwharrison This is from 8.4.0:

<img width="274" alt="image" src="https://github.com/user-attachments/assets/2176e9b8-ed9f-4615-ab21-05890fb15997">

There must be something in your configuration that is preventing the iframe from being displayed.
