### ISSUE TITLE
Imap first fetch trouble on a clean installation

### ISSUE THREAD

**Issue by Niocnam** [espocrm/espocrm#1503]
It's seem there is a little bug on a clean installation.

Imap inbox are not fetched from mail server until they are.

In /application/Espo/Services/EmailAccount.php and /application/Espo/Services/InboundEmail.php

`if (!empty($lastUID) && !$forceByDate) {
                $idList = $storage->getIdsFromUID($lastUID);
            } else {
                $fetchSince = $emailAccount->get('fetchSince');
                if ($lastDate) {
                    $fetchSince = $lastDate;
                }
                $dt = null;
                try {
                    $dt = new \DateTime($fetchSince);
                } catch (\Exception $e) {}
                if ($dt) {
                    $idList = $storage->getIdsFromDate($dt->format('d-M-Y'));
                } else {
                    return false;
                }
            }
`
$idList is empty in this case.

Silly Workaround : 
Change in /application/Espo/Core/Mail/Mail/Storage/Imap.php

`    public function getIdsFromDate($date)
    {
	return $this->protocol->search(array('ALL'));
//        return $this->protocol->search(array('SINCE "' . $date . '"'));
    }

`

**Comment by yurikuzn** [comment]
It worked with 1000nds different IMAP servers. It's not a bug.

**Comment by yurikuzn** [comment]
Maybe your IMAP server doesn't support SINCE parameter.

**Comment by frosty22** [comment]
I have same problem. After few hours, I found solution:

return $this->protocol->search(['SINCE ' . $date]);

**Comment by yurikuzn** [comment]
>  I found solution:

Could you elaborate more please?

**Comment by frosty22** [comment]
I cannot fetch emails from IMAP server of our provider (Seznam.cz - it is a large provider in czech, milions of users). I found in log:

> ERROR: JobManager: Failed job running, job '62ec3b0dae22f5ab6'. Job CheckEmailAccounts 62ec2bb5dc6dc34c0: [0] Return value of Espo\Core\Mail\Mail\Storage\Imap::getIdsSinceDate() must be of the type array, bool returned; at /www/hosting/crm-hrackomat.cz/www/application/Espo/Classes/Jobs/CheckEmailAccounts.php:61. [] []

By trial and error, I found that when using quotes, the server will not accept it. However, according to rfc3501, the quotes are not necessary as it is not a multi-word phrase. So a valid date is e.g. "22-Jul-2012" with or without the double quotes. Unfortunately this imap server only supports unquoted. 

I dont know why.
