### ISSUE TITLE
Add one-to-one  and zero-to-one links to entity manager link types

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1507]
I think both of these types of link should be available in the link type list.

### One-To-One
I think this is the same as hasOne / belongsTo links that are defined in code but not in client
So we have Left.relatedName, Left.relatedId, Right.relatedName and Right.relatedId

### Zero-To-One
This is monodirectional in that the link field is defined only on the leftmost entity.
So only the leftmost entity would have: Left.relatedName and Left.relatedId

**Comment by bandtank** [comment]
Parent/Child would also be very useful to have in the GUI. Maybe it’s been added since I last checked, but I thought I’d mention it just in case.

**Comment by rodrigoscoelho** [comment]
I agree.

This would be very useful.

Enviado utilizando um Galaxy S9...

Em qui, 14 de nov de 2019 10:46, Anthony Andriano <notifications@github.com>
escreveu:

**Comment by yurikuzn** [comment]
One-to-one will be added. https://github.com/espocrm/espocrm/issues/1511

**Comment by bandtank** [comment]
Is parent/child hard to add in the GUI? It’s not a big deal to do via code. I’m just curious.

**Comment by yurikuzn** [comment]
Yes. Parent-to-child is a challenge to make UI simple.
