### ISSUE TITLE
Group Inbound Email with problem

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#151]
It is not possible to add an email account to group inbound email.

**Comment by yurikuzn** [comment]
More details please.

**Comment by rodrigoscoelho** [comment]
When trying to create a new Group Inbound Email Account, It is returning an error when saving, the records doesn't show on the email lists. On the Mysql, the register is created, but apparently missing some fields.

**Comment by yurikuzn** [comment]
We can't reproduce. Check you error logs.

**Comment by rodrigoscoelho** [comment]
Where should I check it? Thanks

Email enviado usando um celular....

Em 01/07/2016 05:56, "Yuri Kuznetsov" <notifications@github.com> escreveu:

**Comment by yurikuzn** [comment]
* apache error log
* data/logs/

**Comment by rodrigoscoelho** [comment]
[2016-07-04 17:30:10] Espo.ERROR: CronManager: Failed job running, job
[577a9ca42170a6103]. Error Details: SQLSTATE[HY000]: General error: 1267
Illegal mix of collations (utf8_general_ci,IMPLICIT) and
(utf8_unicode_ci,IMPLICIT) for operation '=' [] []
[2016-07-04 17:30:11] Espo.ERROR: API [GET]:/:controller, Params:Array (
  [controller] => InboundEmail ) , InputData:  - SQLSTATE[HY000]: General
error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and
(utf8_unicode_ci,IMPLICIT) for operation '=' [] []
[2016-07-04 17:30:11] Espo.ERROR: Display Error: SQLSTATE[HY000]: General
error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and
(utf8_unicode_ci,IMPLICIT) for operation '=', Code: HY000 URL:
/espocrm/api/v1/InboundEmail?maxSize=100&offset=0&sortBy=name&asc=true [] []
[2016-07-04 17:31:01] Espo.ERROR: API [GET]:/:controller/:id, Params:Array
(     [controller] => InboundEmail     [id] => 577a9d549a37d0f9e ) ,
InputData:  - SQLSTATE[HY000]: General error: 1267 Illegal mix of
collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for
operation '=' [] []
[2016-07-04 17:31:01] Espo.ERROR: Display Error: SQLSTATE[HY000]: General
error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and
(utf8_unicode_ci,IMPLICIT) for operation '=', Code: HY000 URL:
/espocrm/api/v1/InboundEmail/577a9d549a37d0f9e [] []
[2016-07-04 17:31:05] Espo.ERROR: CronManager: Failed job running, job
[577a9ca42170a6103]. Error Details: SQLSTATE[HY000]: General error: 1267
Illegal mix of collations (utf8_general_ci,IMPLICIT) and
(utf8_unicode_ci,IMPLICIT) for operation '=' [] []
[2016-07-04 17:31:07] Espo.ERROR: API [GET]:/:controller, Params:Array (
  [controller] => InboundEmail ) , InputData:  - SQLSTATE[HY000]: General
error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and
(utf8_unicode_ci,IMPLICIT) for operation '=' [] []
[2016-07-04 17:31:07] Espo.ERROR: Display Error: SQLSTATE[HY000]: General
error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and
(utf8_unicode_ci,IMPLICIT) for operation '=', Code: HY000 URL:
/espocrm/api/v1/InboundEmail?maxSize=100&offset=0&sortBy=name&asc=true [] []

**Comment by rodrigoscoelho** [comment]
Based on these logs, I can't see any problem. Any other idea?

Email enviado usando um celular....

Em 04/07/2016 14:32, "rodrigoscoelho" <notifications@github.com> escreveu:

**Comment by yurikuzn** [comment]
I have no idea.

**Comment by rodrigoscoelho** [comment]
Found the problem. It was a bad table on mysql. Fixed it. 
Please close this.
