### ISSUE TITLE
Auditing related records

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1512]
Feature Suggestion : allow "Audited" flag to be set on Link Multiple field types.

Example : Account has 1:N relation with orders. 

Setting the Audited flag on Account-Orders would add a stream record when a new order is added/(un)linked to the account

**Comment by yurikuzn** [comment]
Isn't it available? When you edit relationship there should be auditable checkboxes.

**Comment by relyd** [comment]
ok correct, it is indeed not on the Field definition level but assigned on the Relation definition level. Thank you for pointing that out.
