### ISSUE TITLE
Webhook trigger in workflows

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#152]
I've checked out your workflows Advanced plugin at demo site.

What I only miss is trigger for webhook with variables. (Calling REST API of other services)

Is it possible to make this feature?

**Comment by yurikuzn** [comment]
We planned to add an ability to call own service in workflow in the near future. Didn't consider about calls to external apis directly. We need think first.

**Comment by david-strejc** [comment]
If it can be simply webhook it is enough - but webhook with variables will be much better ;-)

**Comment by yurikuzn** [comment]
This is related to advanced pack, not this repository. We've already planned to implement it.

**Comment by XVincentX** [comment]
@yurikuzn Was this feature developed? I'd love to use it!

**Comment by yurikuzn** [comment]
No.

**Comment by XVincentX** [comment]
Thanks — is there any plan or any snippet we can use to implement it?

It’d unleash really interesting opportunities,

V.

**Comment by yurikuzn** [comment]
No plan yet, we have too many things to do.

**Comment by XVincentX** [comment]
Ok never mind — thanks for being so prompt in the reply!

V.

**Comment by XVincentX** [comment]
For the sake of information, I resolved by making EspoCRM sending an email with the data I need to [Zapier parser](https://parser.zapier.com) and then automating the rest of my workflow using Zapier.

I hope to help somebody with this.
