### ISSUE TITLE
`$GLOBALS['log']` needs more configurability

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1526]
## Description

Currently, we can only set few options in our logs. The problem is that we cannot use it in a way where it is most helpful for our tech stacks.

## My Scenario

I am using docker with kubernetes for espocrm where logs are piped to stdout using StreamHandler. From kubernetes, I am sending these logs to fluentbit and from fluentbit to elastic search and elasticsearch to kibana where I can view logs very efficiently.

I am also using `\Monolog\Handler\RavenHandler` for sentry

The problem I am facing is that I have to write regex to parse these logs. What I would like to do is get the logs in JSON.

So, `$GLOBALS['log']->error('message', context)` should give me a `JSON` rather than text.

## Requirements

I have two requirements

1. Ability to add custom `Formatter`, `Handler` and `Processor`
2. Ability to add multiple `Handlers` and `Formatter`
    1. One for logs which I can check over time (non critical logs) which stays in logging systems like kibana or file like data/logs/espo.log
    2. One for sentry that notifies me through email/slack/spectrum any other messaging system everytime critical error occurs

## Proposed Solution

`config.php` should allow adding different formatter present in `vendor/monolog/monolog/src/Monolog/Formatter` folder

`config.php` should allow adding different `processors` and `handlers` present in `vendor/monolog/monolog/src/Monolog/Handler` and `vendor/monolog/monolog/src/Monolog/Processor` respectively

### How to implement?

Just like how you've implemented `emailParser` in `config.php`.

File: `application/Espo/Services/EmailAccount.php`
Line: 276
Function: `fetchFromMailServer`

This is very helpful for a CRM's admin

**Comment by tmachyshyn** [comment]
I will investigate such possibility

**Comment by karthik-uc** [comment]
Thanks @tmachyshyn. That implementation would be a big help. Since you're investigating logs related bugs there are other bugs raised by me which is closely related to this bug

**Comment by karthik-uc** [comment]
Related:

https://github.com/espocrm/espocrm/issues/1495

**Comment by yurikuzn** [comment]
These are not bugs. https://en.wikipedia.org/wiki/Software_bug

> A software bug is an error, flaw or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.

**Comment by beppe9000** [comment]
What is the earliest point in code execution that can be customized in `/custom` ?
I think this issue could be solved by allowing user code to be run just after the `log` variable is assigned.

**Comment by karthik-uc** [comment]
@beppe9000 Surely we can add custom code! 

@yurikuzn I meant issue not bug.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1861

BTW global log is phased out in favor of using dependency injection to pass the log service.
