### ISSUE TITLE
Formula: record\relationColumn & record\updateRelationColumn functions

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1527]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/0f9281812db520b6c29631c99f4a7dfdb7d36c09

**Comment by simpt0ms1** [comment]
hey yurikuzn i've been trying to contact you, do you have an e-mail, i tried contacting you at yuri@letrium.com but it is no longer active.

**Comment by ayman-alkom** [comment]
@simpt0ms1 you may try from here:

https://www.espocrm.com/contacts/
