### ISSUE TITLE
The API call which is made to get relationship layout is throwing E_WARNING

### ISSUE THREAD

**Issue by ananya-uc** [espocrm/espocrm#1529]
**Description:**

- This error will occur only when the non-admin user tries to open the lead/Contact detail view for the first time from the list view. When the detail view is loading this error will occur.  Because of the API call made to get the relationships for the layout. 
- URL :  http://localhost/api/v1/Lead/layout/relationships
- This will occur only for non-admin users. User Type = Regular.

**Steps to reproduce the bug:**

1. Create a regular user(non-admin) with access to lead
2. Login as a regular user.
3. Open details view of a lead

**Diagnostics:**
Warning message: Illegal offset type in isset or empty
File: espocrm/application/Espo/Core/Utils/Util.php
Line: 491
Function: getValueByKey

**Reason for failure:**
The class, _espocrm/application/Espo/Core/Utils/Util.php_ with function _getValueByKey()_ will accept three arguments of type mixed, to return the foreign Entity types of the current Entity.
If the second argument is of type array with mixed type of dataset like a standard class object, _isset()_ function will throw _E_WARNING_. The standard object can not be an offset of an array.

**Proposed Solution**
Add a type check for the value of the array before checking is set or not at line 491 of  _/Espo/Core/Utils/Util.php_ file.

**Comment by yurikuzn** [comment]
Hi,

I can't reproduce the issue. Could you print $keys variable when warning occurs. Fot some reason bad $key argument passed to the function. It's better to find out why. It could mean that something is broken.

**Comment by ananya-uc** [comment]
When loading the relationship layout of lead/contact, following is called

[Services/Layout.php](https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Layout.php#L64)
```php
$this->getMetadata()->get(['entityDefs', 'links', $link, 'entity']);
```

Here the value $link seems to be 
```php
(object) ['name' => 'cases']
```

So, what would be needed is using `$link->name` instead of `$link`.

Diagnostics:

In `actionRead` of `Controllers/Layout.php`
File | Line | Code
---- | ---- | ----
`application/Espo/Controllers/Layout.php` | `42` | `$this->getServiceFactory()->create('Layout')->getForFrontend($params['scope'], $params['name']);`
`application/Espo/Services/Layout.php` | `64` | `$foreignEntityType = $this->getMetadata()->get(['entityDefs', $scope, 'links', $link, 'entity']);`
`application/Espo/Core/Utils/Metadata.php` | `188` | `$result = Util::getValueByKey($this->getData(), $key, $default);`
`application/Espo/Core/Utils/Util.php` | `491` | `if (isset($item[$keyName])) {`

**Comment by yurikuzn** [comment]
Check `custom/Espo/Resources/layouts//Lead/relationships.json`.

**Comment by yurikuzn** [comment]
I managed to reproduce.

**Comment by yurikuzn** [comment]
The fix: https://github.com/espocrm/espocrm/commit/3f1f686bd117eedaf411e73e8590cff84ac31d1d

Thanks for help.
