### ISSUE TITLE
Websocket doesn't give real time updates

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1533]
## Description

I have setup websocket and socket connection is getting established. I have setup two users for test purpose. One is admin and other is regular user. When admin mentions regular user in post, I expect the post notification to be display in regular user's bell icon immediately. But right now I can see that only after refresh.

No errors found in `data/logs/espo.log`.

**Comment by yurikuzn** [comment]
I think it's misconfigured. It's working fine.

**Comment by bandtank** [comment]
@karthik-uc Did you ever figure this out? I'm having the same problem after trying websockets for the first time.
