### ISSUE TITLE
(Enhancement) Simplify customization of mass email sending process

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1534]
If I customize `\Espo\Modules\Crm\Services\MassEmail::sendQueueItem` just to add an header to the message I have to duplicate the whole method.

If I customize `\Espo\Core\Mail\Sender::send` I can not be sure the email that is being sent is actually a mass email without extensive checking.

https://github.com/espocrm/espocrm/blob/7a919dedfdec4e34fc38919b5da920de8cdc6bd7/application/Espo/Modules/Crm/Services/MassEmail.php#L478-L487

I suggest to extract the above part of `\Espo\Modules\Crm\Services\MassEmail::sendQueueItem` in a separate method. Like this:

```php


    /**
     * @param \Espo\ORM\Entity   $queueItem
     * @param \Zend\Mail\Message $message
     */
    protected function additionalHeaders(Entity $queueItem, \Zend\Mail\Message $message): void {
        $header = new \Espo\Core\Mail\Mail\Header\XQueueItemId();
        $header->setId($queueItem->id);
        $message->getHeaders()->addHeader($header);

        $message->getHeaders()->addHeaderLine('Precedence', 'bulk');

        if (!$this->getConfig()->get('massEmailDisableMandatoryOptOutLink')) {
            $optOutUrl = $this->getConfig()->getSiteUrl() . '?entryPoint=unsubscribe&id=' . $queueItem->id;
            $message->getHeaders()->addHeaderLine('List-Unsubscribe', '<' . $optOutUrl . '>');
        }
    }

```

This way customized code is simplified and more future-proof (manipulate message then call original method).

<hr>

Another idea is that there could be an `emailContext` field in the `\Espo\Core\Mail\Sender` class (defaulting to `regular`) to be set in accord to the type of mail that is being sent (`bulk`, `reminder`, etc. ) after instantiating the sender object. 

That way one could override `\Espo\Core\Mail\Sender::send`, check the email type and manipulate it if needed.

<hr>

 _Please correct me if I missed something 😄_

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c36788ba2662a80014c7dd11dc6da710ae0ab9ad
