### ISSUE TITLE
(Enhancement) Add VERP option for mass emails

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1536]
https://en.wikipedia.org/wiki/Variable_envelope_return_path

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1560

**Comment by yurikuzn** [comment]
Any help with testing would be appreciated.

**Comment by rodrigoscoelho** [comment]
Launch it, and let is disabled with an EXPERIMENTAL label.

_______________________________________




*Rodrigo Sírio Coelho*

*Engenharia / Aimsun*

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807


Em qui., 9 de jan. de 2020 às 08:23, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by beppe9000** [comment]
Great! I will try to test this. An alternative (and simpler imho) approach to the plus-addressing (or to isolate it) is to setup a dedicated verp subdomain with a single catch-all mailbox that can then be used like this: `<email id>@verp.mysite.com`. To allow the above scenario another setting is needed to specify the part after `@` of the bounce mailbox. I think it should be editable for each InboundEmail entity along with the respective imap/pop settings for accessing the verp mailbox.
