### ISSUE TITLE
removing a field does not clean up orderBy resulting in HTTP 500

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#1537]
Removing a field in entity manager which is used in metadata/entityDefs/ "orderBy" the columns will not be removed from OrderBy statement which ends up in HTTP 500 accessing the entity.
In the log only the following line is shown (after removing an foreign field accountName pointing to account.name):
````
Espo.ERROR: (42) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'account.name' in 'order clause'; GET /api/v1/Account/5d98509cc93534998; line: 266, file: /var/www/html/espocrm/application/Espo/ORM/DB/Mapper.php [] []
````
I guess there are other cases not fully remove field names in the json files after removing a field.

**Comment by hi-ko** [comment]
found in version: 5.6.2

**Comment by hi-ko** [comment]
field will also not be removed from any form

**Comment by yurikuzn** [comment]
It's known behavior. Administrator needs manually remove/change parameters. I prefer this approach.

**Comment by yurikuzn** [comment]
E.g.

Want to change field type.
1. remove field.
2. add field of another type with the same name.

Order is lost. Layouts are lost.
2.

**Comment by hi-ko** [comment]
hmm. having unmapped fields on the layout maybe acceptable but not breaking the app due to left orderBy entries. I understand your use case but we see breaking entities every view days if customers remove fields in entity manager - so this is still a bug.
If you like your use case we should add an option in the the delete warning dialog like "keep UI definitions". Same does apply for the db columns. Admin should be asked if data should be also removed to avoid to break the entity when some admin creates a field later by accident which is not compatible with the column data type.

**Comment by yurikuzn** [comment]
It's weird that you face this problem every few days. It means every few days admin creates a new field, make a default order by this field and then removes this field.

Making dialogs for this means more work for me and more code to maintain for me.

**Comment by hi-ko** [comment]
Our customers like to add entities, fields for their own. EspoCRM is the ideal tool to manage entities (relational data) a team / an organisation has no it system for yet (except excel). So different people having a good understanding for relational data, but without linux/sql skills, work on different entities and decide to remove fields again or move the fields to another entity. It is very likely that someone already defined an orderBy on a field when removing that field which then results in a broken entity showing HTTP 500 in the UI. Then we have to grep the json files to cleanup manually which sucks users and us. Customer says: system broken again - can't work! So for now we have a 2 system setup (test/prod) and we first manually (!) check any differences before syncing the changes to prod.
If we leave it as it is many not too technical admins may say it is easy to leave espo in an inconsistent state when using entity manager.

**Comment by bandtank** [comment]
You seem to be forgetting that fields can be used in custom hooks, jobs, reports, etc., which means Espo would somehow have to scrub php files upon removal of a field.

Automating field removal cleanup is an impossible task for a variety of reasons. Removing fields frequently is not how the system is designed to be used. If you want to use it that way, I think you need to accept that manual cleanup will be necessary.

**Comment by hi-ko** [comment]
@bandtank I understand your point but what I see is that people sometimes use Espo like Access or Filemaker. If you think this is the way how espo should work I would vote for removing the "remove" link for entities and fields since it is not working as expected.
On the other hand your point is dependency management in manual coding (non generated code). This could be circumvated by a 'protected' flag. Something similar is Espo already using for their own module entities (or is it protected by definition in a module?).

**Comment by hi-ko** [comment]
yet another one when leaving a link field:
````
Espo.ERROR: (42S02) SQLSTATE[42S02]: Base table or view not found: 1146 Table 'espocrm.customer_order' doesn't exist;
````

**Comment by hi-ko** [comment]
Could you please reopen the ticket?
At least a warning should be shown in the entity manager when removing a field or entity that the admin needs to remove all references in config files to avoid unexpeted exceptions.
In a later step the admin should choose to keep or cleanup the config once there is code to cleanup the config for fields and entities.

**Comment by yurikuzn** [comment]
Ok, I re-open. Although I'm going going to implement this in the nearest future. If you can do it, please contribute with PR.

**Comment by telecastg** [comment]
I recently had this issue and went through purgatory scrubbing all references to the "removed" entity. 

One suggestion would be to implement the creation of new entities inside custom named modules and not throw everything inside the "Custom" namespace, just like the Real Estate extension does and allow the removal of the module. 

This way an Administrator can remove the module and everything else related to the custom entity or entities.

**Comment by acro-labs** [comment]
Any news on this Issue, we are trying to customise espocrm to our needs and have created a link we had to remove and now espocrm is practically usless with the error 500 - Happened before and i had to nuke it and start over, but I am not interested in doing this again - how do i manually fix this issue in the db?

**Comment by yurikuzn** [comment]
If you had to nuke your instance it might be you had some different issue.

I tried to reproduce the problem.

1. Created a new field.
2. Set the default order to this new field (Administration > Entity Manager > {Entity} > Edit).
3. Removed the field.
4. On the list view I got an error with a descriptive text. It's supposed to be clear for the admin user what happened. See the screenshot.
5. Changed the default order to some different field.
6. The list view is working.

![image](https://github.com/espocrm/espocrm/assets/1006792/fddfbaa4-925c-4138-bfd5-c04c34678e6e)

**Comment by bandtank** [comment]
The only error I think should be solved automatically is the  rendering of the list view if the field is no longer valid. The user may have sorted the list, which stores the orderBy field in local storage. Users don't realize the x exists next to the list view's search bar, so they can't figure out how to fix the error. The administrator can't fix that error either because it requires access to local storage in the user's browser.

**Comment by rabiibrahimi** [comment]
> If we changed the order automatically, then we should determine to what field to change. But all fields are equal, we don't have a default one as the parameter determines the default one. Choosing arbitrary is worse than we have now.

Why not just fallback to order by field **createdAt** which is the default even for custom entities. Besides that field is core and can't be removed.
