### ISSUE TITLE
Number (auto-increment) field should not store nextNumber in metadata/entityDefs

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#1538]
In principle the json files in Resources dirs like entityDefs are excellent to be shared/syced between dev/test/prod systems (or between custom/Espo and modules). Unfortunately the "Number (auto-increment)" stores the sequence info (nextNumber) in the entityDefs which is specific to the instance.
Storing the nextNumber in the db or at least in a separate file whould avoid any conflicts.

**Comment by yurikuzn** [comment]
It stores in db. If it's stored in metadata it's a by a mistake, and it's not taken into account.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/FieldManager/Hooks/NumberType.php

If it really uses metadata (I doubt) please let me know and I will re-open the issue.

**Comment by rodrigoscoelho** [comment]
I think it stores in metadata the info about the NEW start number. If you
want to use a new number as start point....
_______________________________________




*Rodrigo Sírio Coelho*

*Engenharia / Aimsun*

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807


Em qui., 5 de dez. de 2019 às 15:57, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by rodrigoscoelho** [comment]
I think it stores in metadata the info about the NEW start number. If you
want to use a new number as start point....

Em qui., 5 de dez. de 2019 às 15:57, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by yurikuzn** [comment]
It might stores the initial value specified upon a creation, but never takes it into account.

**Comment by hi-ko** [comment]
You're right - next val is indeed stored in table next_numbe. Sorry for the false alarm and thanks a lot for the prompt feedback! So we should filter out any nextNumber in jsondiff to figure out changes made by admin users ...
