### ISSUE TITLE
New notification number in title

### ISSUE THREAD

**Issue by kemsay63** [espocrm/espocrm#1539]
show the number of notifications in the browser header.
ESPO CRM (1)

**Comment by beppe9000** [comment]
This should be a checkbox near the one for notification sounds.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3689ac0253a204cedbc6fdc483f6045c9a6ff442

**Comment by yurikuzn** [comment]
Parameter will be available at Administration > Notifications.
