### ISSUE TITLE
Calculated fields

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#154]
I've never seen such a great software as yours and I am in business for 12 years!

Great job!

Do you plan adding "calculated" fields? By this I mean having opportunity to have operators between my custom entities - for example I can design that field Cost has operator "+" to Internal Expenses. 

Am I clear enough?

**Comment by yurikuzn** [comment]
Hi David,

Yes. We planned. But have not determined when we will implement it. We have a lot of work to be done in our road map.

If you have any ideas how editor should be designed in UI please share.

**Comment by david-strejc** [comment]
Do you have Roadmap accessible anywhere online?

So I won't propose any planned features.

**Comment by david-strejc** [comment]
You can start with absolutely simple design:

Int field will have option to add operator and ability to say which other int field should be operated. (Basically you will than calculate result) 

In UI it should be simple:

Int Field1 "Which operator to apply" Int Field2

**Comment by yurikuzn** [comment]
Roadmap is not available.

**Comment by yurikuzn** [comment]
Planned it for 2016 Q4.

**Comment by ayman-alkom** [comment]
Hi @yurikuzn , 
I am working on a new field type named **Calculated Field**, and it is related to this, I can make it as PR if you want

**Comment by yurikuzn** [comment]
We already have some code written.

**Comment by yurikuzn** [comment]
In entity manager it's possible to define _formula_ for specific entity type. This script is executed every type before record is saved.

Examples:
```
amount = product.listPrice - (product.listPrice * discount / 100.0);

someFieldField = string\concatenate(firstName, " '", middleName, "' ", lastName)

ifThenElse(
  entity\isNew() && status == 'Planned' && dateStart == null,
  dateStart = datetime\addDays(datetime\now(), 10),
  ifThen(
    status == 'Held' && dateStart == null,
    dateStart = datetime\now()
  )
);


```

**Comment by alasdaircr** [comment]
What language is this written in?

This will be an amazing feature. Looking forward to it.

**Comment by yurikuzn** [comment]
It's a simple language designed specially for this feature.
