### ISSUE TITLE
No currency loaded while manual installation

### ISSUE THREAD

**Issue by prbt2016** [espocrm/espocrm#1540]
Hello,

I tried to manually install EspoCRM version 5.7.8 on PHP 7.1 , MYSQL 5.6 , Apache 2.2, Centos 6.4 Final.
However there is no currency loaded while manual installation and also the currency drop down option is blank.

![no_currency](https://user-images.githubusercontent.com/17871448/70424829-089aca00-1a96-11ea-9b01-3231e36a1c22.png)

Also, post installation inside admin panel inside Preferences - > Default Currency is just shown as 
Default() and there is no currency loaded in the drop-down. Also inside the 'preferences' table the entry 'defaultCurrency' is blank.

![no_currency_1](https://user-images.githubusercontent.com/17871448/70425160-b017fc80-1a96-11ea-9e1a-0122cf89e575.png)

Could you please check this at your end and fix this issue?

**Comment by yurikuzn** [comment]
Fixed. Thanks.
