### ISSUE TITLE
Email sent using personal email address is throwing E_NOTICE.

### ISSUE THREAD

**Issue by DarylAranha** [espocrm/espocrm#1542]
**Description:**

- When a user ties to use his/her personal email a E_NOTICE is thrown. 

**Error message**

E_NOTICE: Undefined variable: emailAddress {"code":8,"message":"Undefined variable: emailAddress","file":"/www/espocrm/application/Espo/Services/Email.php","line":201

**How to reproduce**

- Log in as a user, and go to the user's information page.

- Select Email Accounts from the drop down found at the top right of the page.

- Add a personal email for a user. 

- Once the email is added, go to the user's info page and add the created email to Email field.

- Compose an email (eg: from a lead) and use this personal email.

**Comment by yurikuzn** [comment]
Thanks. this is quite serious bug. Some functionality doesn't work because of that.

Fix:https://github.com/espocrm/espocrm/commit/0d744c5e7ff20f25f984e4e2cd9adc8a41484843

**Comment by tomaspar** [comment]
I expected that it's uses SMTP settings from user perifences? by the way for me test is working ok, but I can't send mail as well. V 5.7.7
