### ISSUE TITLE
User role permissions cannot be changed

### ISSUE THREAD

**Issue by onlinedear** [espocrm/espocrm#1543]
Version：5.7.9
Steps 1 The new role 
              Name **Github**
<img width="1055" alt="001" src="https://user-images.githubusercontent.com/10751712/71142555-acccff80-2252-11ea-99c7-a3ca84ba8997.png">
<img width="1058" alt="002" src="https://user-images.githubusercontent.com/10751712/71142654-f6b5e580-2252-11ea-8805-aedb409fc673.png">
Only set up the "patients（患者）" permissions

Steps 2 A new user
              Name **Githubuser**
<img width="714" alt="003" src="https://user-images.githubusercontent.com/10751712/71142710-2bc23800-2253-11ea-9c39-cfd803a8f9f6.png">
Select the user to the "Github" role
<img width="707" alt="004" src="https://user-images.githubusercontent.com/10751712/71142771-53b19b80-2253-11ea-868d-bd3df0d5e304.png">

However,Click to view the "access" permissions and see that they are not set
<img width="1141" alt="005" src="https://user-images.githubusercontent.com/10751712/71142794-6a57f280-2253-11ea-9319-52014837f0f0.png">

Hope to get your help, thank you

**Comment by onlinedear** [comment]
Delete the team that the user belongs to and you can use it normally, but once you join the team, you can't use your personal privileges

**Comment by yurikuzn** [comment]
It's difficult to understand for me since screenshots are not in English. All roles are merged (directly assigned and assigned via teams). Permissions that give higher access level is applied, permissions that give lower level are ignored.
