### ISSUE TITLE
Incorrect handling of angle brackets in text-only mails

### ISSUE THREAD

**Issue by mwandelt** [espocrm/espocrm#1544]
Text-only (non-HTML) mails that are fetched into a personal or group email account are treated in such a way that angle brackets at the beginning of quoted lines will appear as HTML entity (`&gt;`). When responding to such an email the quoted lines in the response will also be prefixed with entities instead of angle brackets. Tested with EspoCRM 5.7.9 in Firefox and Chrome.

![screenshot1](https://user-images.githubusercontent.com/7895787/71161763-417f2f80-224a-11ea-9f65-a71f6eff9fc2.jpg)
![screenshot2](https://user-images.githubusercontent.com/7895787/71161760-40e69900-224a-11ea-91f6-419b76c2f7ac.jpg)

**Comment by yurikuzn** [comment]
I tested and it worked fine. Need to see an email original.

**Comment by mwandelt** [comment]
It happens quite often. Here is one example.
[Test Message.zip](https://github.com/espocrm/espocrm/files/3984508/Test.Message.zip)

**Comment by yurikuzn** [comment]
Thanks for help. Here is the fix: https://github.com/espocrm/espocrm/commit/3f772f6882d398ddcc74f75d87944967696818d9

**Comment by mwandelt** [comment]
Works perfectly, thanks a lot!
