### ISSUE TITLE
Brazilian Timezone is wrong after ended the DST policy

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#1547]
Brazil doesn't use DST anymore, starting this year. So, the Timezone São Paulo, for example, is with 1 hour more. 
Please update the DST library.

Thanks.

**Comment by yurikuzn** [comment]
Moment timezone lib has not updated Brazil timezone yet https://github.com/moment/moment-timezone/issues/785

**Comment by yurikuzn** [comment]
Actually, they updated, but I tested and timezone offset was the same in May 2020 and May 2018.

**Comment by yurikuzn** [comment]
Well, I waster the half of the day on this and can't figure out why it doesn't work. Could you please apply these new files and check whether it works for you. For me, it seems it does not.

**Comment by beppe9000** [comment]
I think if the expected value is added to the test here the dev would likely find out the problem.
https://github.com/moment/moment-timezone/blob/develop/tests/zones/brazil/east.js

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/834fc25a622de76bca8ac7ba4add58a2bc4d2d12
