### ISSUE TITLE
Bulk foreign field creation and editing

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1554]
Sometimes many foreign fields need to be made at the same time. I think some interface that can take an entity type and show a checklist of fields that can be selected for creating foreign fields would make it less repetitive.

**Comment by yurikuzn** [comment]
I don't think it's needed. It happens not so often when one creates new foreign fields. But having this ability means more complex ui, more codebase to support, time for me that I could spend for more important things.

**Comment by beppe9000** [comment]
Probably better to improve CLI scripting capabilities instead at this point... after all it's a superset of this
