### ISSUE TITLE
Count is extremely slow after MySQL 8.0

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1556]
## Problem

1. I have started using MySQL 8.0 for espocrm and turns out that any table that has JSON data/Text/mediumtext has slower response time for count when compared to 5.7.
2. [Here](https://github.com/espocrm/espocrm/blob/7980887e504f445bb8d84abe738b32124354be1f/application/Espo/Services/Record.php#L1129) the query is time consuming.

## Comparison:

This sample is from a real database with proper fields and values. I have one field called additionalInformation which contains large data in JSON.

```mysql
mysql> select count(id) from lead;
+-----------+
| count(id) |
+-----------+
|    658498 |
+-----------+
1 row in set (39.45 sec)

mysql> select id from lead;
+-----------+
| id           |
+-----------+
| some number of entries |
+--------------------+
658498 rows in set (0.62 sec)
```

## Suggestion

To count entries just query for primary key without limit and get all the entries. The `$pdo->rowcount ` should give the required result as shown in the second query of comparison.

Or you can use information_schema database to get count, I think.

Open to any other solution. But please try to avoid using `count` as it is slow.

**Comment by karthik-uc** [comment]
Code to test if needed:

```php
$pdo = new \PDO($dsn, $user, $password);
$pdoStatement = $pdo->prepare('select id from lead;');

$start = microtime(true);
$pdoStatement->execute();
echo 'Count is: '.$pdoStatement->rowcount().PHP_EOL;
$totalTime = microtime(true) - $start;
echo "Time Taken: {$totalTime}".PHP_EOL;
```

**Comment by yurikuzn** [comment]
I didn't notice that it became slower since updating to 8.0. Maybe something wrong with mysql?

You can disable count in Administration > Entity Manager.

**Comment by karthik-uc** [comment]
It is not slower with my mysql. 

Have you tried inserting like million rows into lead table with a field containing JSON data and try running count?

It's applicable only when data is present json/mediumtext field.

If I run `select count(*) from email_address`, it's pretty fast. But with tables containing json data it's slow. That's what I noticed.

**Comment by karthik-uc** [comment]
Here are more examples:

`indexed_field` is never `NULL`
`id` is never `NULL`

```mysql
mysql> select count(*) from `lead` where indexed_field is not null;
+----------+
| count(*) |
+----------+
|   600000 |
+----------+
1 row in set (0.14 sec)

mysql> select count(*) from `lead`;
+----------+
| count(*) |
+----------+
|   600000 |
+----------+
1 row in set (35.48 sec)

mysql> select count(*) from `lead` where id is not null;
+----------+
| count(*) |
+----------+
|   600000 |
+----------+
1 row in set (35.91 sec)
```

**Comment by yurikuzn** [comment]
Using information_schema, indexed_field is not an option by a design.

I'm not sure PDO rowCount is a reliable solution.

The only solution I know is to disable count as I mentioned above.

**Comment by yurikuzn** [comment]
You can move your json column to another table and use foreign field,

**Comment by karthik-uc** [comment]
@yurikuzn I think that's a good idea.
