### ISSUE TITLE
global email folders 

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1563]
i see the action "move to folder" in filters is only available to users. I believe it should be expanded to support group emails too.

**Comment by yurikuzn** [comment]
It's not possible by a design.

**Comment by beppe9000** [comment]
Not real move to folder... I now share some idea about virtual folders to be used within espo.
<hr>

With different group emails would be a problem. What I meant is more like global folders as search filters. 

in Email Entity
`imapFolder` - emails need to store original folder and update it if it changes
`clientFolder` - should be null to show up in inbox

Global Folders should select emails based on client folder: if it's empty it goes to common inbox
Global and Group Filters should get a new condition to check the value of `imapFolder` and an action to change `clientFolder` to the id of global folder entity and use it to fetch the list

<hr>

A separate but parallel approach is to use a tag system:

- email arrives 
- filters apply user-defined or system-defined tags based on any condition (for group filters also being in a specific monitored folder)
- global tag folders retrieve all emails that are tagged with a list of tags

This way one could use one or two filters to tag all emails that are in the 'INBOX.important' folder in group acc.t A and the ones in `INBOX.reminders` with the `very-important` tag. Subsequently the global tag folder lists all emails with `very-important` in the `My Very Important` global tag folder
