### ISSUE TITLE
Autocomplete not working after 3rd key

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#1564]
As you can see on the image below (animated GIF), it works since you press the first key, the second, and the third. After that, it stops working. 

It was working perfectly months ago. I don't know since when it started to behave that way. 
My config is to start autocompleting after the first keypress, as you instructed long time ago. 
Now, apparently, it is with a hardcoded config making incompatibility.
![Untitled Project](https://user-images.githubusercontent.com/6912410/72284315-7307d280-361f-11ea-820b-a7f26c4e5e6a.gif)

**Comment by yurikuzn** [comment]
Do you use full-text search? It how it works and always worked. If you disable full-text, it will work as you expect.

**Comment by yurikuzn** [comment]
I decided to disable full-text search for autocomplete. https://github.com/espocrm/espocrm/issues/1566

**Comment by rodrigoscoelho** [comment]
Thanks....
