### ISSUE TITLE
Problem with rights

### ISSUE THREAD

**Issue by bennouchy** [espocrm/espocrm#1565]
Hello,

If a user doesn't have the right to see his team (Field level configuration in opportunity), even if that user has the right to modify opportunities of his team, he does not have the rights to do so. He can only modify the opportunities he created.

When I make the field visible, everything goes according to what's planned.

I only tested it for opportunities as the site is in production.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/02ab36825609d5762bc67d73825a366541cc6e62
