### ISSUE TITLE
Priorities in CSS classes

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#158]
Dear GREAT team of EspoCRM - is it possible to add class based on priority to HTML elements in future to EspoCRM? 

I would like to have visually differentiated colors of tasks and other elements which has priority.

Many thanks for your product - one of best I've ever seen ;-)

**Comment by yurikuzn** [comment]
Hi David,

Not clear. Can you explain more detail?

**Comment by david-strejc** [comment]
Let's say I got an task (issue) with High priority - I would like to see it in my dashboard in Red color. Tasks with low priority I would like to have them in blue color. 

And this can be applied system wide.

Am I claer enough? 

I have plenty of experience with Redmine which is now osbolete for me. But some features are nice to have. 

Many thanks.

**Comment by yurikuzn** [comment]
Got it. It's not planned for now.
It's not difficult to write custom view to display name field in different colors.

**Comment by david-strejc** [comment]
OK so I will try it on my own and I will see.
