### ISSUE TITLE
Popup notification performance

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1582]
It seems that the getPopupNotifications api call takes over ~20 seconds for an user who apparently has ~3000 reminders (for other reasons beyond my control).

With a default refresh rate of 10s it causes very high cpu usage. I increased that but I still think this could use some improvements.

For the ajax implementation I would like options for change or disabling the timeout (for notifications, or all api calls for slow server fault tolerance).

Also the delay between requests should be from end of request, not from start (i did inspect only the web traffic and it looked like that).
<hr>
Can websocket help with this? Does it read the popupNotifications.json file for custom notification views? How is refresh rate controlled? Is there an exaplenation somewheere? Are notification pushed with cron jobs?

**Comment by beppe9000** [comment]
Also is there a way to benchmark the sql queries? I would like to log those that take more than 5 seconds.

**Comment by yurikuzn** [comment]
I recommend look through code. I don't remember all and will need to look through code too.
