### ISSUE TITLE
Loading commands from custom path

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1585]
If the class name is not standard then metadata should be used to specify it. 

But for classes following the standard custom namespace convention the class name can be inferred from metadata.

<hr>

Example implementation of custom command to echo all parameters, flags and options below.

```PHP
<?php

    namespace Espo\Custom\Core\Console\Commands;

    class DumpOptions extends \Espo\Core\Console\Commands\Base
    {
        public function run($options, $flagList, $argumentList) {
            echo "\n>> OPTIONS: "; print_r($options);
            echo "\n>> FLAGS: "; print_r($flagList);
            echo "\n>> ARGUMENTS: "; print_r($argumentList);
            echo "\nEnd of run() method.\n\n";
        }
    }
```

Example usage:

1. Put the file in `custom/Espo/Custom/Core/Console/Commands/DumpOptions.php`.
2. Run in ssh or batch like this

```text
$ php command.php dump-options -flag --option=value argument1 argument2

>> OPTIONS: Array
(
    [option] => value
)

>> FLAGS: Array
(
    [0] => flag
)

>> ARGUMENTS: Array
(
    [0] => argument1
    [1] => argument2
)

End of run() method.

```

**Comment by WilixLead** [comment]
Any updates? Looks like pull-request was rejected but decision still not released or not described in docs.

**Comment by yurikuzn** [comment]
Is there any reason not to define a custom command in metadata?

**Comment by beppe9000** [comment]
for me it is the same reason we do not define hooks in metadata: no need to write it out since espo can infer the path with no problem, only some light performance issue but by the time i care for performance i edit the metadata no problem. but for developing is faster without metadata.

**Comment by yurikuzn** [comment]
Performance can (and should) be neglected in both ways. I do not like if something is looking into Custom but does not look into Modules. I don't see that defining in metadata can be a hurdle for developers.

**Comment by WilixLead** [comment]
No any information about information how implement custom command in metadata. I search in docs https://docs.espocrm.com/development/metadata/ and https://docs.espocrm.com/development/
I just implement custom command by looking to core code part and via debugging process. 

Next message for guys who try find tutorial about adding custom console command:

1. Create directory `custom/Espo/Custom/Core/Console/Commands`
2. Place your php file with command class (example in application/Espo/Core/Console/Commands/Rebuild.php)
3. Don't forget extend you class from Espo\Core\Console\Commands\Base
4. Create `consoleCommands.json` file under `custom/Espo/Custom/Resources/metadata/app`
5. File should have next structure:
```json
{
  "YourClassName": {
    "className": "\\Espo\\Custom\\Core\\Console\\Commands\\YourClassName"
  }
}
```
6. Rebuild app
7. Try `php command.php yourClassName'

**Comment by beppe9000** [comment]
>I don't see that defining in metadata can be a hurdle for developers.

My 2 cents. I can only speak for myself but I find it redundant in this case, given the fact that other parts of espo can already infer the class paths, and if I add a single line to the command manager I have to type less, which saves time (especially for short lived commands that are subject to constant changing in content and name).

**Comment by yurikuzn** [comment]
> can already infer the class pat

Those that can inferred by path but located in *Core* were our bad decision. We should not have done it. If something not supposed to be in *Modules/{type]* dir it should not be inferred by a file location.  Should be defined in metadata.

**Comment by beppe9000** [comment]
But for me there is no problem since i customized the loader for command manager and now see it has been refactored so I can only override the path searching function rather than the whole thing. Which is great! 👍🏻 

https://github.com/espocrm/espocrm/blob/9f2b2de261ad7e46516ac8131454ee8f9863957c/application/Espo/Core/Console/CommandManager.php#L81-L96

**Comment by yurikuzn** [comment]
I don't encourage such a customization. It is really not needed.

BTW using inheritance to customize protected method is not good. It's risky and not OOP.

**Comment by beppe9000** [comment]
As I said I only do this in development instance yeah. But what do you mean inheritance is not good? Isn't OOP all about it? How is it risky? For updates? Or because this is the core part of Espo?

**Comment by yurikuzn** [comment]
Protected methods can be changed in any update so inherited class won't work.

**Comment by beppe9000** [comment]
It's good for exceptions to be thrown on such mismatches. That way the developer can fix all the bad inheritors on a test instance and then transfer the update customizations to production server.

**Comment by yurikuzn** [comment]
Running `php preload.php` and running tests can detect some errors. We can't do anything better than this.

**Comment by beppe9000** [comment]
yes, I think that will be useful as a standard testing procedure before updating
