### ISSUE TITLE
Custom API action  404

### ISSUE THREAD

**Issue by yuejie89** [espocrm/espocrm#1592]
[2020-02-05 03:17:29] Espo.ERROR: API [GET]:/:controller, Params:Array (     [controller] => Test ) , InputData:  - Action GET 'index' does not exist in controller 'Test'. [] []
[2020-02-05 03:17:29] Espo.ERROR: Display Error: Action GET 'index' does not exist in controller 'Test'., Code: 404 URL: /api/v1/Test [] []

**Comment by yuejie89** [comment]
跪求 帮助！
Kneel for help！

**Comment by yuejie89** [comment]
<?php

namespace Espo\Controllers;

class Test extends \Espo\Core\Controllers\Base {

	public function testGet($params, $data, $request) {

		return array(
			'total' => 123,
		);
	}
}

**Comment by yuejie89** [comment]
![image](https://user-images.githubusercontent.com/36728384/73810206-ba454580-4810-11ea-8d5f-2f5d63910fc7.png)

**Comment by yuejie89** [comment]
![image](https://user-images.githubusercontent.com/36728384/73810262-e52f9980-4810-11ea-9e02-5051d494dcb8.png)

**Comment by yuejie89** [comment]
![image](https://user-images.githubusercontent.com/36728384/73810327-22942700-4811-11ea-8f2b-f8ef51505356.png)
![image](https://user-images.githubusercontent.com/36728384/73810343-33dd3380-4811-11ea-8fac-93f7438d2da0.png)

**Comment by yurikuzn** [comment]
Please create such question on our forum. Your json is invalid. Excess comma at the end.

**Comment by yurikuzn** [comment]
Try method name `actionGetIndex`

**Comment by yuejie89** [comment]
thanks

**Comment by yurikuzn** [comment]
And you have invalid json. Excess comma.
