### ISSUE TITLE
[Feature Request] Switch to commonly used storage services

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1593]
## Description

Currently, EspoCRM is using `Espo\Core\FileStorage` as storage service manager and `Espo\Core\Utils\File` as storage operator.

## Proposal

Use https://packagist.org/packages/league/flysystem

## Reason

We can integrate with several other Storage service provider on the fly using same API/Libraries.

Pass the client to FlySystem and use FlySystem API to write or read files. It's quite easy to adapt and different espo users will have different requirements.

For example,
I use S3 to store information while someone else might use dropbox or digital ocean.

**Comment by theBuzzyCoder** [comment]
Docs: https://flysystem.thephpleague.com/v1/docs/

Other packages:
league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
spatie/flysystem-dropbox (Allows you to use Dropbox storage)
srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem-ziparchive (Allows you to use ZipArchive adapter)

**Comment by bandtank** [comment]
@theBuzzyCoder Are you currently using S3 to store uploads? If so, do you have any code you can share to help me do the same? I've wanted to do this for a long time, but I am not proficient with the S3 PHP interface and I have not been able to get it to work.

**Comment by theBuzzyCoder** [comment]
I want to use s3, however as of now I am not using it. I building one extension for it and when it's done I will post my comments here. Please, feel free to contribute.

Extension: (Work in progress)
https://github.com/theBuzzyCoder/espocrm-file-storage-services

**Comment by bandtank** [comment]
I definitely will. FYI - you may want to look at [this](https://forum.espocrm.com/forum/feature-requests/23705-upload-all-files-to-an-object-store) thread if you haven't already seen it.

**Comment by theBuzzyCoder** [comment]
This definitely helps: https://github.com/saeed237/sugarpro7.1/blob/master/include/SugarUploadS3.php. Thanks @bandtank.

My plan is to write an extension that supports other providers also so that it's not limited to S3. And I would want to write it in a way where all the providers have similar API's. That's why I am using ThePHPLeague/FlySystem.
