### ISSUE TITLE
[Feature Request] Is there a way to install espocrm command line

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1594]
## Description

Usually we do http://espocrm.mysite.com/install to setup espocrm for the first time. I would like to have a command line way of installing espocrm so that we can do CI/CD.

Example,

php install.php

This should take all required params from env or one of the files like ini file when I can keep all required configurations. When bringing up the vpc instance, I can just copy the ini files into either env or related path where the espocrm will read from.

**Comment by karthik-uc** [comment]
I figured it out. It's `php install/cli.php -a action -d data`

**Comment by bandtank** [comment]
What is the data parameter? A file, path, object, or literally the word data?

**Comment by theBuzzyCoder** [comment]
Hi @bandtank,
See here:

https://github.com/espocrm/docker/blob/master/apache/docker-entrypoint.sh#L121

https://github.com/espocrm/docker/blob/master/apache/docker-entrypoint.sh#L139

**Comment by bandtank** [comment]
@theBuzzyCoder Thanks. That helps a lot.
