### ISSUE TITLE
Config.php should load information from secure locations

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1595]
## Description

Right now, config.php is setup when espocrm-site/install is called. That's a good way however it's better if we could load config.php could load information from a secure location like /etc/ which is not in the path of the web-app source code.

Also separate out user defined settings like which Storage service to use, imap and smtp configuration, etc...

Database configurations, cryptKey should not change once app is installed because users cannot login without changing password in case of deletion config.php and re-creation. Scenario: Say the espocrm hosted vpc crashes and we cannot recover, we can reinstall the application but users cannot login without password reset.

## Example

XHGUI have used config.php and load the information from env if not found in the config.php

https://github.com/perftools/xhgui
https://github.com/perftools/xhgui/tree/master/config

**Comment by yurikuzn** [comment]
At the moment the current location is secure as it's located outside of the public directory.
