### ISSUE TITLE
[security] web.config files should not be readable

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1596]
Suggested is to add any web.config to the .htaccess blocklist.

https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/webconfig-file-detected/

**Comment by telenieko** [comment]
From the page you linked you will see that the concern with this file is that it could leaks sensitive information (like DB credentials) which is not the case here.

The web.config files in espocrm do not contain any sensitive information, their contents are basicaly public even if you protect them (you cat fetch them from this very repository).

Regarding the .htaccess:
- That would only work on Apache and only if using mod_rewrite
- There are other mechanisms but if `AllowOverride` is not properly setup (ie, you do not have root access) the system will completely fail (unless specified, a denied override is a fatal error)
- You would only hide `web.config` (which is an IIS file) on Apache servers, not covering IIS itself, NGINX or other servers

**Comment by relyd** [comment]
agree, closing

**Comment by yurikuzn** [comment]
Anyway I added: https://github.com/espocrm/espocrm/commit/d7f46e039ea42203a18968d3213869b56045ae64
