### ISSUE TITLE
Identify EspoCRM instance and user in 2FA TOPT

### ISSUE THREAD

**Issue by maverage** [espocrm/espocrm#1601]
I extensively use 2FA and have a lot of applications within my authenticator app. Unfortunately, EspoCRM only creates QR codes without identifying the instance (e.g. site url) and user, therefore I can only have a single EspoCRM 2FA within one app, because else I couldn't identify, for which account which token is valid for.

Would it be possible to change line 111 in [/client/src/views/user-security/modals/totp.js](https://github.com/espocrm/espocrm/blob/master/client/src/views/user-security/modals/totp.js#L111) from `text: 'otpauth://totp/EspoCRM?secret=' + this.secret,` to something like `text: 'otpauth://totp/EspoCRM%20' + this.siteurl + ':' + this.username + '?secret=' + this.secret,` ?

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/7efd36ebe8026943db4183c25eff3825efa220f2
