### ISSUE TITLE
Integration API doesn't allow delete and re-enable integration

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#1602]
## How to reproduce error

Try this

DELETE /api/v1/Integration/Your-Integration-ID

Then

Setup integration

## Scenario

User may want to remove all records of integration from database because it contains secret which should be kept when unused. So, delete option.

After sometime user may want to enable the integration and since Id is the integration name like GoogleMaps it gives 409 Conflict.

**Comment by yurikuzn** [comment]
I think passing null values should be enough to erase data.
