### ISSUE TITLE
What happened to the 'clear cache' button in the front-end ?

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1606]
The one in the user menu to supposedly clear the localstorage cache. How do users clean the local cache in newer versions?

**Comment by yurikuzn** [comment]
If your user need to clear local storage cache that could mean that you do something wrong, Regular clear cache will force local storage to cleared.

It's also possible to clear local storage via browser's tools.

**Comment by beppe9000** [comment]
> If your users need to clear local storage cache that could mean that you do something wrong

idk, sometimes we had a problem of missing tabs when logging-in to a low-priviledge account and then to one with more permissions that was only solved by clearing browser cache manually.

Does the 'use cache' in settings refer only to server-side cache or to client also?

**Comment by yurikuzn** [comment]
> Does the 'use cache' in settings refer only to server-side cache or to client also?

Both.

**Comment by beppe9000** [comment]
Is the local storage always populated? I did find old cache entries for the js files in local storage (firefox) despite having disabled the 'use cache' check box
