### ISSUE TITLE
Fix port range to accept email servers listening on any possible port

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1610]
Apparently I have a server on illegal port range 🤦‍♂  The correct maximum should be 65535

![image](https://user-images.githubusercontent.com/6625123/74662199-b95dcd80-5199-11ea-9177-86c0b3d09b00.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/5c539b99d8bff93af40fd150e9cf08b7913db758
