### ISSUE TITLE
default value of 'from' for Email is causes smtp test email failure

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1612]
If the default value for `From` field of `Email` entity is set to some email address the `Send Test Email` procedure for smtp can fail on some hosts because the default value for `From` is different from the allowed value (i.e. a policy where the outgoing email `From` header must be equal to the login address) and interpreted as a spoofing attempt.

The solution should be for the test email entity to have the `From` value specified instead of fallback to the default value which can be 'illegal'.

**Comment by yurikuzn** [comment]
*From* field is not as customizable to prevent any side-effects.
