### ISSUE TITLE
Need "show more" button under streams of Opportunity 

### ISSUE THREAD

**Issue by DarylAranha** [espocrm/espocrm#1613]
When an email is sent from the Case tab, the stream records this and the user can read the entire content of the email just by clicking on Show More. This is not true for Opportunity, a link to the email is provided. 

Espocrm version: 5.7.11

**Comment by yurikuzn** [comment]
No. It should not.

You will be able to change config parameter: 'streamEmailWithContentEntityTypeList'

https://github.com/espocrm/espocrm/commit/d9125a5204c220116c5783791fbb4072892b0134
