### ISSUE TITLE
PDF template {{today}} placeholder prints time

### ISSUE THREAD

**Issue by tomaspar** [espocrm/espocrm#1615]
Quote template {{today}} parameter show date in date-time, like {{now}} parameter. Expected - only date format.
ESPO CRM Version 5.8.2

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/870cdb19e345a59acda5124406d6214c275937af

You can use `{{dateFormat today_RAW}}` as a workaround.
