### ISSUE TITLE
Webhook "Scalar error"

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#1616]
Espo.WARNING: E_WARNING: Cannot use a scalar value as an array {"code":2,"message":"Cannot use a scalar value as an array","file":"/var/www/html/espocrm/application/Espo/Core/Webhook/Manager.php","line":107,"context":{"event":"Financeiro.update"}} []

**Comment by yurikuzn** [comment]
I think you have some problems with cache file.

**Comment by rodrigoscoelho** [comment]
I got it working, but, the only info it is "posting" are "modifiedById" and
"id"

Any idea why?

It is a customized Object that I created. It has a lot of fields.

Thanks

Em qui., 20 de fev. de 2020 às 05:30, Yuri Kuznetsov <
notifications@github.com> escreveu:

**Comment by rodrigoscoelho** [comment]
I found why.
I'm using Object.update   as webhook, and it is sending only updated info.

That's the raw Json
[{"modifiedById":"system","id":"16"},{"dataSUS":"2011-01-30","modifiedById":
"1","modifiedByName":"Rodrigo S\u00edrio Coelho","id":"16"}]

Why we have different modifiedById 2 times? Why we don't have dataSUS
together the first key?


I would like to know how to post the ALL FIELDS, even when just updating a
field.
If I use Object.create, it will only post all fields as soon as I create
it. I would like to post it

Em sex., 21 de fev. de 2020 às 20:58, rodrigoscoelho <
notifications@github.com> escreveu:
