### ISSUE TITLE
Add support for other fullcalendar views

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1617]
fullcalendar supports list views: https://fullcalendar.io/docs/list-view

in interface settings it may be useful to add a multiple-enum to select what views are available to users

**Comment by yurikuzn** [comment]
If ever need to have list view, definitely won't use fullcalendar list view. We have own frontend for this.

**Comment by beppe9000** [comment]
it may be nicer graphically for dashlets
