### ISSUE TITLE
fullcalendar event feed

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1618]
fullcalendar can use an event feed directly: https://fullcalendar.io/docs/events-json-feed

useful feature could be to add support in calendar settings for using them

**Comment by yurikuzn** [comment]
We don't need it in CRM.

**Comment by beppe9000** [comment]
I mean the actual crm events could be loaded that way instead of doing ajax -> object conversion -> load from array

**Comment by yurikuzn** [comment]
Really no need for this. It works fine, no need for optimization there at all. It's better to spend time for more imprortant things.

**Comment by beppe9000** [comment]
but is there a way to pass custom event colors from php backend  for example ?
