### ISSUE TITLE
concurrent access 

### ISSUE THREAD

**Issue by Tlopasha** [espocrm/espocrm#1623]
Hi,

does espocrm support concurrent-access ?

for example: locking a record for users while updating from other user.

**Comment by yurikuzn** [comment]
Hi,

Doesn't support.

When you update record from UI, it send only fields you modified. So there are usually no problems with it.

**Comment by yurikuzn** [comment]
[Optimistic concurrency control](https://docs.espocrm.com/user-guide/optimistic-concurrency-control/) is supported as of v7.0.
