### ISSUE TITLE
Mails from outlook are not getting parsed properly.

### ISSUE THREAD

**Issue by DarylAranha** [espocrm/espocrm#1628]
file: /www/espocrm/application/Espo/Core/Mail/Parsers/ZendMail.php
line: 323
message: mb_convert_encoding(): Illegal character encoding specified
charset: WINDOWS-1256
charsetParamValue: windows-1256

**Comment by yurikuzn** [comment]
ZendMail parser is not supported in EspoCRM now, it's a legacy code.. Did you change a parser in config?

**Comment by DarylAranha** [comment]
I was using ZendMail parser because, MailMimeParser failed to parse the email body.

message: Error: iconv(): Wrong charset, conversion from `CP1256' to `UTF-8//TRANSLIT//IGNORE' is not allowed

line: 350
file: /www/espocrm/vendor/zbateson/mb-wrapper/src/MbWrapper.php

from: False
fromCharset: WINDOWS-1256
to: UTF-8
toCharset: UTF-8

**Comment by yurikuzn** [comment]
Could you provide me an email original so I could investigate?
