### ISSUE TITLE
Convert duplicate check will throw E_WARNING

### ISSUE THREAD

**Issue by Ananyakokala** [espocrm/espocrm#1631]
**Description:**

- When the lead is converted from the the convert button under the lead detail view will throw E_WARNING.
- URL: http://localhost/#Lead/convert/<lead_Id>
- When the there is no duplicate entries then warning will be thrown.  

**Steps to reproduce the bug:**
1. Manually create a lead in espocrm
2. Convert the Lead to a contact using the convert button under the lead detail view. Make sure that there is no duplicate contact for the lead.

**Diagnostics:**
Warning Message:   Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/www/espocrm/application/Espo/Modules/Crm/Services/Lead.php ...
File: espocrm/application/Espo/Modules/Crm/Services/Lead.php
Lines: 209, 232, 259

**Reason for failure:**
When the convert function is called from the button click under lead detail view, the duplicate check is set to true. When there is no duplicate entries found then the function _findDuplicates()_ will return null. So the _foreach_ loop will throw the warning saying _Invalid argument supplied for foreach()_.

**Detailed Explaination:**
When the convert button is clicked following is called,
[Service/Lead.php] (https://github.com/espocrm/espocrm/blob/master/application/Espo/Modules/Crm/Services/Lead.php#L186) 

The function _findDuplicates()_ will return null.
[application/Espo/Services/Record.php] (https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Record.php#L1923)

Diagnostics:
In `convert` of `Services\Lead.php`

File | Line | Code
---- | ---- | ----
`application/Espo/Modules/Crm/Services/Lead.php` | `186` | ` public function convert(string $id, object $recordsData, ?object $additionalData = null) : \Espo\Modules\Crm\Entities\Lead`
`application/Espo/Modules/Crm/Services/Lead.php` | `197` | ` $duplicateCheck = !($additionalData->skipDuplicateCheck ?? false);`
`application/Espo/Modules/Crm/Services/Lead.php` | `208 231 258` | `$rDuplicateList = $this->getServiceFactory()->create('Contact')->findDuplicates($contact, $recordsData->Contact);`
`application/Espo/Services/Record.php` | `1923` | `public function findDuplicates(Entity $entity, $data = null) : ?\Espo\ORM\EntityCollection`
`application/Espo/Modules/Crm/Services/Lead.php` | `209, 232, 259` | `foreach ($rDuplicateList as $e) {`

**Comment by yurikuzn** [comment]
Thanks for detail reporting. Here's the fix: https://github.com/espocrm/espocrm/commit/a894f9a70b1945c0b04215f9273ccf8aa8521822
