### ISSUE TITLE
LOCK table and MariaDB Cluster

### ISSUE THREAD

**Issue by Jacq** [espocrm/espocrm#1641]
LOCK tables has several known limitation (https://mariadb.com/kb/en/lock-tables/), that for Galera cluster could cause crashes.

This caused random locks while using espocrm, particularly running a php cron.php caused a hangs the execution when acquiring the lock, then another cron cycle created hanged again using another connection. This way connections/memory were exhausted in a couple of hours for the whole database.

Will it be possible to implement a LOCK free cron job?
Jacq
Cheers,

**Comment by yurikuzn** [comment]
Hi Jacq,

I don't think I have a zeal to implement it. You can customize *CronManager* class so that it won't lock tables.

**Comment by yurikuzn** [comment]
It must be simple to customize in upgrade-safe way.

**Comment by yurikuzn** [comment]
Added `jobNoTableLocking` config parameter. Not recommended if run-jobs-in-parallel is disabled.

https://github.com/espocrm/espocrm/commit/fe32d8d47bf9e69c420191ea9170babd31764565

**Comment by yurikuzn** [comment]
I'll consider rewriting the logic to use transactions + two SELECT FOR UPDATE queries. But not yet sure whether it will work as I expect.
