### ISSUE TITLE
Email: Creating documents from attachments

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1650]
On Email detail view from dropdown in the top-right menu: Create Document.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f5829310b68aa289c80a22f03bda9e2dc1c2f114

**Comment by rodrigoscoelho** [comment]
Great Yuri. I hope you launch it as soon as possible.! :)

**Comment by yurikuzn** [comment]
>  I hope you launch it as soon as possible.! :)

Release can be postponed a bit due quarantine issues.
