### ISSUE TITLE
Layouts: Bottom Panels layout instead of Relationships

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1654]
The ability to manage all bottom panels including stream, relationships and other panels in a single layout.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f6500d6c08471286d5cee440b72a6c87aca85895

**Comment by rodrigoscoelho** [comment]
WOW!!! Very good. I was waiting for this...

**Comment by rixoj** [comment]
Awesome!

**Comment by lucakuehne** [comment]
Is it possible, that this function may have removed the "Calls" and "Meetings" section on the bottom of Accounts and Contacts?
Or maybe by some other commit/release?

**Comment by yurikuzn** [comment]
I don't think so. It's not listed because of the parameter `layoutRelationshipsDisabled`. See https://github.com/espocrm/espocrm/blob/6.0.8/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Account.json#L235. You can disable it in custom metadata.
