### ISSUE TITLE
Layout Service will throw: Espo.NOTICE: E_NOTICE: Undefined variable: result

### ISSUE THREAD

**Issue by Ananyakokala** [espocrm/espocrm#1660]
**Description:**
- When the layout is loaded for any entity the layout service function will throw the following error.
Espo.NOTICE: E_NOTICE: Undefined variable: result {"code":8,"message":"Undefined variable: result"

**Steps to reproduce:**
- Load any entity detail layout.
- When the layout is loaded for the first time this error is thrown. 

**Diagnostics:**
- E-Notice Message: Espo.NOTICE: E_NOTICE: Undefined variable: result {"code":8,"message":"Undefined variable: result","file":"/www/espocrm/application/Espo/Services/Layout.php","line":67,"context":{"scope":"Lead","name":"relationships","setId":null}}
File: espocrm/application/Espo/Services/Layout.php
Line: 67

**Reason for failure:**
- When the Layout Service function `getOriginalBottomPanelsDetai` is called setId will be null. The function will call the `getOriginal` function will also do not have the value for the setId.
- If the setId field is not set then the variable _result_ value will not be set. Because of this `getOriginal` function will throw the above mentioned E_NOTICE.

**Detailed Explanation:**
When the `Layout` of an entity is loaded following things are called,
(https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/ControllerManager.php#L143)

The `Layout` Service functions will be called, 
(https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Layout.php#251)
(https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Layout.php#63)

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/14510f91301d6b5af22c691855491dad1eda5dad.
