### ISSUE TITLE
what about use it in economic?

### ISSUE THREAD

**Issue by jhzao82** [espocrm/espocrm#1661]
I don't have a company to do the job, But I found this is really good product, and Its free. I don't know that If I coud use it for many other company in my contry. any idea for me?

**Comment by telenieko** [comment]
Hi,

This issue tracker should be issued for bug reports and other matter related to the platform development, your request is more appropiate for the User Forums available at [https://forum.espocrm.com/forum/general](https://forum.espocrm.com/forum/general)
