### ISSUE TITLE
phpunit results not ignored (.gitignore)

### ISSUE THREAD

**Issue by telenieko** [espocrm/espocrm#1666]
Hi,
`grunt test` (which calls phpunit) leaves a `.phpunit.result.cache` file that is not ignored in `.gitignore``

Should it be ignored?

**Comment by yurikuzn** [comment]
Hi,

I never had this file created. Added to gitignore: https://github.com/espocrm/espocrm/commit/9b878148cfef7b5a9641e1311591764f283b61a2. Thanks for reporting.
