### ISSUE TITLE
Option to set Default Action for list view link. 

### ISSUE THREAD

**Issue by rixoj** [espocrm/espocrm#1667]
It would be a good feature if we can set default action for the list view link, Quick View or Full View. Currently, it opens the Full View of the recorded. 
![image](https://user-images.githubusercontent.com/9829335/78798294-73bdc400-79d6-11ea-8201-ee0e4fc30cde.png)

**Comment by yurikuzn** [comment]
I had though about this a lot before, still not sure we need to have such an ability. I don't like when same UI elements behaves differently in the same app. BTW it's possible to Ctrl + middle click to open any record link in a modal.
