### ISSUE TITLE
Collection.fetch method do not fetch do not fetch all the entries

### ISSUE THREAD

**Issue by daryl-uc** [espocrm/espocrm#1678]
## Problem: 
Dashlet shows chop the last few entries and replace with "Show more" which do not work.

## How to reproduce:
- Take any Dashlet and display all the entries by clicking on "show more" (i.e the Show More button should not display). _**Note:** this should be done before Dashlet auto-refreshes._
- Wait for the Dashlet to Auto Refresh.
- When the Dashlet refreshes some of the entries are removed and replaced with "Show more" button. On clicking the button nothing happens.

On investigation, I found the collection.js fetch method is setting wrong maxSize value.
https://github.com/espocrm/espocrm/blob/5.8.4/client/src/collection.js#L151

This is the code on line 151
options.data.maxSize = options.more ? this.maxSize : ((this.length + this.length > this.maxSize) ? this.length : this.maxSize);

This line sets the **maxSize** to **this.length**. It should actually be **(this.length + this.lengthCorrection)**

**Comment by yurikuzn** [comment]
Could not reproduce, but I understand there are specific cases when it can happen. For some reason after clicking 'Show More' it returns results from the previous record range.

**Comment by yurikuzn** [comment]
Here's the fix: https://github.com/espocrm/espocrm/commit/f28fcde90ca14dfeef9bcd5d052e54b6fdba8adf.

Please let me know whether everything is find after applying the fix. Thanks.

**Comment by daryl-uc** [comment]
I have applied distinct to the join.

Yes, this fix works.
