### ISSUE TITLE
Self Registration when a visitor is not a user yet

### ISSUE THREAD

**Issue by telecastg** [espocrm/espocrm#1680]
I'm working on an implementation that would allow visitors to request to be registered from the login page, and noticed that at present it is possible to change the default 'view/login' at the base front end controller by setting a "loginView" parameter but I can't find the metadata file where this parameter can be specified.

The front end controller client/src/controllers/base.js references this parameter in the login function as:
var viewName = this.getConfig().get('loginView') || 'views/login' 

and the back end controller Settings references it as:
$loginView = $this->getMetadata()->get(['clientDefs', 'App', 'loginView']); 
but there is no 'App.json' file under the application/Espo/Resources/metadata/clientDefs folder.

Where can the "loginView" parameter be set or is it not defined yet but the ability to set a custom login page is a future feature ? 

Thanks

**Comment by yurikuzn** [comment]
If the file doesn't exist you can create it. In custom.

**Comment by yurikuzn** [comment]
Just give it a try and see whether it works.

**Comment by telecastg** [comment]
Thanks, I will post the results here

**Comment by telecastg** [comment]
Thanks so much
    On Thursday, April 16, 2020, 12:49:26 PM PDT, Yuri Kuznetsov <notifications@github.com> wrote:  
 
 


If the file doesn't exist you can create it. In custom.

**Comment by telecastg** [comment]
Creating a custom App.json file worked perfectly, I am now able to call a custom template for the login screen and include a self-registration option for visitors.
![EspoCRM Custom Landing Page](https://user-images.githubusercontent.com/44280636/79949318-3de2fb80-842a-11ea-86bc-4cb64fb289ec.JPG)

The only drawback now is that I have to hard code those values (like background image location, custom registration boolean, etc) in the custom login view.

I would like to be able to store the custom data values in metadata, and have access to them from the custom login view, just like it's done for the logo with 
"var companyLogoId = this.getConfig().get('companyLogoId');" and for other settings.

I tried fetching the values in the custom login view from a custom "settings.json" file even using async and promises but since the the data is not loaded until the custom login view script executes, if I sign out and refresh the page the custom settings are lost.
![EspoCRM Default Landing Page](https://user-images.githubusercontent.com/44280636/79949491-7e427980-842a-11ea-96e7-642ef5ac6cd0.JPG)

Do you have any suggestions on how to pre-load the custom login page settings ?

Thanks

**Comment by yurikuzn** [comment]
Metadata is not available before user logged in.

**Comment by telecastg** [comment]
OK thanks

**Comment by GoZippy** [comment]
Any progress on self registration implementations? I'd like to have it integrated into community core code

**Comment by yurikuzn** [comment]
It was not in our plans.

You might also consider the OIDC authentication, relying on another provider.

**Comment by bandtank** [comment]
@telecastg Do you mind sharing your solution?

**Comment by GoZippy** [comment]
I would love to see this implemented  such that a user can register with work email address - and the domain name that is linked to a customer/company profile be used to define the role and template for the new user - access to default user set of resources and roles for that company or team - and then allow admin of that domain/team/role to define higher level permissions etc later. We have a lot of customers and I would love to be able to give them all access to our services directly.Same with new team members... just login and get default roles based on your email domain (of course we would need to make sure email is validated first before granting team and user roles etc.)

**Comment by telecastg** [comment]
@bandtank I was not able to implement self registration with the current system.
