### ISSUE TITLE
Settings: Email address autocomplete scopes

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1683]
The ability to set scope list that will be used for email address autocomplete. Settings > Outbound Emails > Email address look-up scopes.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/d1cfa84f066891102b96c789866588fc462c7c3e

**Comment by rodrigoscoelho** [comment]
Great. Is it possible to do the same for Opportunities, Leads, etc?

**Comment by yurikuzn** [comment]
Leads - yes
Opportunities - no
custom entity of Person or Company type - yes
