### ISSUE TITLE
Make saved filters available in record list dashlet

### ISSUE THREAD

**Issue by zazy** [espocrm/espocrm#1684]
Is there a way to use saved searches in the record list dashlet?
For example if I go to **Account**, inser search criteria and save this search, I can go to **Account** again and I can use the saved search from the dropdown list. 
When in the _Home_ view if I add a _List view_ dashlet, in the _Primary filter_ listbox I can see the _Recently created_ filter but not the saved ones.
Am I missing something? Is there a way to makes search filter availeble in the _Record list_ dashlet?

**Comment by yurikuzn** [comment]
There's no such an ability.

It's possible to use reports filters, but it's in advanced pack.
