### ISSUE TITLE
one-to-one relationship - not actual on update - cannot use in formula

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1692]
I've got a one-to-one (left) relation from 'nascholing' to 'opleiding'.

![one-to-one-relation](https://user-images.githubusercontent.com/745693/80825475-c3ac3700-8be0-11ea-9fb2-67db5ca92dff.PNG)

When an update occurs, I try to update the (new) record 'nascholing' with data from the selected (already existing) 'opleiding'. 

![selecting-the-relation](https://user-images.githubusercontent.com/745693/80825487-c73fbe00-8be0-11ea-8b71-48a131fbf172.PNG)

However, it turns out that the related id (opleiding.id) is the previous selected one, i.e. the existing one in the record, not the selected one. 

So, 

`
jaar = string\concatenate(description, " ", opleiding.id);
`

Results in the current `description`, and the previous `opleiding.id`.

I would expect the currently selected `opleiding` to be the one to work with in the record, i.e. the same behaviour as with the `description`.

**Comment by hdijkema** [comment]
N.B., when I run an formula update as administrator, all fields are set correctly, but that is no workable solution.

**Comment by yurikuzn** [comment]
At the moment of formula execution relation is not established yet. I recommend to find another way. For example, use `record\attribute` to fetch an attribute of the another record by its ID that you get with `opleidingId`.

**Comment by hdijkema** [comment]
> It's weird that your way works for admin. Might be some bug? Or you might have some custon logic that make formula be executed twice? I will look into.

No, what I meant was, when I run the formulas on the entities as administrator, i.e. from the list of 'nascholing'.

**Comment by hdijkema** [comment]
> ```
> $someVar = record\attribute('Opleiding', opleidingId, 'attributeYouNeed');
> ```

Does this mean that I've got this variable 'opleidingId' in the formula, or did you mean 'opleiding.id', which points to the previous relation (if one exists)?

**Comment by yurikuzn** [comment]
Yes. `opleidingId` is passed from UI (since you selected the foreign record) and then available in formula. I believe.

**Comment by hdijkema** [comment]
Oke, I've seen this working. Thank you for the information. So 'opleidingId' contains the currently selected relation; I didn't know that. Could I have known this reading the documentation? 

My code now read:


```
//////////////////////////////////////////////////////////////////////////////
// Working before save. opleidingId contains the currently selected Opleiding.
//////////////////////////////////////////////////////////////////////////////

aantalDagen = record\attribute('Opleiding', opleidingId, 'aantalDagen');
aantalDagenMedisch = record\attribute('Opleiding', opleidingId, 'aantalDagenMedisch');

$opl_date = record\attribute('Opleiding', opleidingId, 'dateStart');
$jr = datetime\year($opl_date);
jaar = $jr;

//////////////////////////////////////////////////////////////////////////////////
// Not working before save. opleiding points to the previously selected opleiding
//////////////////////////////////////////////////////////////////////////////////

//jaar = string\substring(entity\attribute('opleiding.dateStart'), 0, 4);
//aantalDagen = entity\attribute('opleiding.aantalDagen');
//aantalDagenMedisch = entity\attribute('opleiding.aantalDagenMedisch');
```

**Comment by hdijkema** [comment]
Great that this works! I was already writing an afterSave() hook.
