### ISSUE TITLE
Formula execution just before or just after removal

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1693]
Formulas are executed just before saving an entity. This is a great feature.
However, suppose one wants to recalculate some records when an entity is removed? 
Would this be possible or is it a feature request?

**Comment by yurikuzn** [comment]
No. Such a feature will not be implemented. Since formula is applied to the current record, it's not reasonable to make changes on the record that is being removed.

**Comment by hdijkema** [comment]
Thanks for the comment, however, I've added a new issue that ([#1694]) that also gives some insight in what I'm trying to create.
