### ISSUE TITLE
API: Incorrent Content-Type

### ISSUE THREAD

**Issue by arkadywtf** [espocrm/espocrm#1700]
https://github.com/espocrm/espocrm/blob/8c47f941721ad87287f8c2082609f9643fadc08d/application/Espo/Core/Application.php#L307

The API returns `text/html;charset=UTF-8` even though the headers are explicitly being set to `Content-Type:application/json`.

I have tested this on a fresh installation. Any ideas?

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/bcc3cfd143b7d2f0abd5a78a585c2b5fb9f30f03
