### ISSUE TITLE
Allowing the use of modules to encapsulate custom changes from the Admin interface

### ISSUE THREAD

**Issue by telecastg** [espocrm/espocrm#1710]
I have been using a module scheme like it is used in the Real Estate extension to store customizations instead of letting everything go to the client/custom and the application/Espo/Custom namespaces, and it works great for debugging and organization, plus allows me to completely "erase" any custom created fields, links or entities.

Is this something that is planned or that could be included in the road map ?

**Comment by yurikuzn** [comment]
Not planned at this moment.

**Comment by telecastg** [comment]
OK thanks

**Comment by yurikuzn** [comment]
You can use the extension template for this: https://github.com/espocrm/ext-template#blocking-out-extension-in-espo
