### ISSUE TITLE
a way to request refresh of foreign fields after hook

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1727]
this is a minor gui glitch when a relation is updated in the backend but it is not reflected until a page refresh. 

a solution could be to add an header like  `X-Espo-ReloadForeign: true` to the `PUT` response of the api to instruct the webapp to reload the changed fields. the hook code would use a wrapper like `Utils::forceForeignRefreshing()`.

or maybe detect it in the clientside code

**Comment by yurikuzn** [comment]
A solution is not so easy. It requires usage of websocket and it's difficult task in case of many-to-many relations.

**Comment by beppe9000** [comment]
> It requires usage of websocket

i'm not sure... why would websocket be required? I don't see the downside of using headers:  user modifies something -> custom hook is run -> header is set on relation field change -> webapp detects relation change flag from api response header-> foreign fields are reloaded by js

One point may be the need to differentiate between webapp requests in some cases maybe

**Comment by yurikuzn** [comment]
I considered situation when someone else modified relationships.

**Comment by yurikuzn** [comment]
With headers it's tricky, requires a lot of think to be re-done. Request object is not available in hooks etc. 

It'd recommend to force relationships being re-loaded in frontend w/o incorporating backend.

**Comment by beppe9000** [comment]
I believe this should be splitted in two separate issues:
 - reload of foreing and relation fields when relations are changed after editing (client can detect this from the save result object)
- update of foreing and relation fields when relations are changed by another user (no easy way without polling or websocket use)

**Comment by porquero** [comment]
You can use this:

`public function afterSave(Entity $entity, array $options) {
        $this->entityManager->refreshEntity($entity);
    }`

**Comment by yurikuzn** [comment]
Fixed issue with not being updated when link is changed: https://github.com/espocrm/espocrm/issues/2857
