### ISSUE TITLE
Url field does not support other schemes than http and https

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#1732]
We are facing the issue that an url field only supports http and https schemes.
When saving for example `ftp://ftp.test.com/` the resulting href is `http://ftp://ftp.test.com/`
```
<div class="field" data-name="ciConnectURL">	
<a href="http://ftp://ftp.test.com/" target="_blank">ftp://ftp.test.com/</a>
</div> 
```

Is it possible to support any possible scheme and only prefix the uri with http:// if no scheme is specified?

**Comment by pomazanbohdan** [comment]
Use http
https://www.chromestatus.com/feature/6246151319715840

**Comment by neknarf** [comment]
> Use http
> 
> https://www.chromestatus.com/feature/6246151319715840

FTP is just an example. Want to use a custom uri in order to start an installed application

**Comment by yurikuzn** [comment]
I suggest creating a custom field type, with view inherited from the address field. https://docs.espocrm.com/development/custom-field-type/

**Comment by neknarf** [comment]
> I suggest creating a custom field type, with a view inherited from the address field. https://docs.espocrm.com/development/custom-field-type/

To be honest, I think the fact that http:// is added automatically when no uri scheme is specified should be changed/removed.

[https://github.com/espocrm/espocrm/blob/master/client/src/views/fields/url.js#L79](url)

**Comment by yurikuzn** [comment]
Should have been already fixed/solved.
