### ISSUE TITLE
To add the possibility to filter emails, Opportunities, etc. by more than 1 condition with .AND. and .OR.

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#174]
It would be great to add the possibility to filter entities by more than one condition.

**Comment by yurikuzn** [comment]
It's implemented in reports now. We not sure whether we need to have AND/OR filters in list view since users rarely need it (the most cases are covered with multiple selection of enum/link fields tha work as OR). We'd like to keep UI simple as possible.
