### ISSUE TITLE
Two Multi-Enum Field with Conditional options

### ISSUE THREAD

**Issue by nishan56838** [espocrm/espocrm#1744]
Hi,

I have faced an issue with Two multi enum fields with conditional options. Please refer attached screenshots so you will have better understand what i was going to do. Simply I want that is,

From continent field if I chose two continent from trade lane field it will only has to be show trade lanes from each continent.

What I need to be done
Ex:
Continent = Asia, Oceania
Trade Lane = India, Pakistan, Australia, Papua New Guinea

But i'm getting only data from single continent according to Conditional options order

Conditional Order Asia,Africa,Oceania

Data i'm getting is with the current

Continent = Asia, Oceania
Trade Lane = India, Pakistan

Continent = Asia, Africa
Trade Lane = India, Pakistan

Continent = Africa, Oceania
Trade Lane = Nigeria, Ethiopia
![4yAP3D2Nvy](https://user-images.githubusercontent.com/32173067/85691191-e85cf080-b6f1-11ea-880a-86f32bfc3e01.png)
![rAMZERI7ZR](https://user-images.githubusercontent.com/32173067/85691199-e98e1d80-b6f1-11ea-9170-60b577c7206f.png)
![v484660oL9_1](https://user-images.githubusercontent.com/32173067/85691203-ea26b400-b6f1-11ea-80b5-7ac70482c8e8.png)
![v484660oL9_2](https://user-images.githubusercontent.com/32173067/85691204-eabf4a80-b6f1-11ea-8ca8-22b4e3705780.png)
![Y9aI8nOb7q](https://user-images.githubusercontent.com/32173067/85691207-eb57e100-b6f1-11ea-9e7b-5f2901742c60.png)

Conditional option well work with "Enum"

**Comment by yurikuzn** [comment]
Duplicate https://forum.espocrm.com/forum/general/59293-two-multi-enum-field-with-conditional-options
