### ISSUE TITLE
MySQL not recognized

### ISSUE THREAD

**Issue by rytis-paskauskas** [espocrm/espocrm#1745]
EspoCRM 5.9.3
The first or second installation page, I get the rant
`Your MySQL version is not supported by EspoCRM, please update to MySQL 5.7.0 at least`
on this guy:

    Server version: 5.7.28 MySQL Community Server (GPL)
    Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

So it seems like the version of the DB should be OK... Any ideas of how to resolve this issue?

**Comment by yurikuzn** [comment]
Please create a topic on our forum. I'm extremely busy and can't help.
