### ISSUE TITLE
Performance of left join

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1747]
Good afternoon.

I'v got an entity Visitatie with a many to 1 relation with Contacts. When I get the list of these entities, espocrm performs this query:

```sql
SELECT visitatie.id AS `id`, visitatie.assigned_user_id AS `assignedUserId`, visitatie.created_by_id AS `createdById`, visitatie.name AS `name`, 
       visitatie.lid_id AS `lidId`, NULLIF(REPLACE(TRIM(CONCAT(IFNULL(lid.initials_name, ''), ' ', IFNULL(lid.first_name, ''), ' ', 
       IFNULL(lid.middle_name, ''), ' ', IFNULL(lid.last_name, ''))), '  ', ' '), '') AS `lidName`, visitatie.regiocode AS `regiocode`, 
       visitatie.visitatiedatum AS `visitatiedatum`, visitatie.resultaat AS `resultaat`, visitatie.created_at AS `createdAt` 
FROM `visitatie` LEFT JOIN `contact` AS `lid` ON visitatie.lid_id = lid.id 
WHERE visitatie.deleted = '0'
ORDER BY visitatie.created_at DESC, visitatie.id DESC LIMIT 0, 200
```

I've got 17000 contact records (of which about 16000 with status deleted) and 3500 visitatie records (although, visitatie records will grow beyond contacts). And this query takes about 3,2 (200 rijen (3.234 s)) seconds if it has not been cached. Explain on the query in adminer gives this:

id? | select_type? | table? | partitions? | type? | possible_keys? | key? | key_len? | ref? | rows? | Extra?
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | visitatie | NULL | ALL | NULL | NULL | NULL | NULL | 3427 | Using where; Using temporary; Using filesort
1 | SIMPLE | lid | NULL | ALL | NULL | NULL | NULL | NULL | 17478 | Using where; Using join buffer (flat, BNL join)

When I add one simple condition in the WHERE part: `and visitatie.lid_id = lid.id` 

```sql
SELECT visitatie.id AS `id`, visitatie.assigned_user_id AS `assignedUserId`, visitatie.created_by_id AS `createdById`, visitatie.name AS `name`, 
       visitatie.lid_id AS `lidId`, NULLIF(REPLACE(TRIM(CONCAT(IFNULL(lid.initials_name, ''), ' ', IFNULL(lid.first_name, ''), ' ', 
       IFNULL(lid.middle_name, ''), ' ', IFNULL(lid.last_name, ''))), '  ', ' '), '') AS `lidName`, visitatie.regiocode AS `regiocode`, 
       visitatie.visitatiedatum AS `visitatiedatum`, visitatie.resultaat AS `resultaat`, visitatie.created_at AS `createdAt` 
FROM `visitatie` LEFT JOIN `contact` AS `lid` ON visitatie.lid_id = lid.id 
WHERE visitatie.deleted = '0' and visitatie.lid_id = lid.id
ORDER BY visitatie.created_at DESC, visitatie.id DESC LIMIT 0, 200
```

the query is consistently fast (200 rijen (0.116 s)) and explain states:

id? | select_type? | table? | partitions? | type? | possible_keys? | key? | key_len? | ref? | rows? | Extra?
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | lid | NULL | ALL | NULL | NULL | NULL | NULL | 17478 | Using temporary; Using filesort
1 | SIMPLE | visitatie | NULL | ref | IDX_LID_ID | IDX_LID_ID | 99 | func | 1 | Using index condition; Using where

When I remove the 'LEFT JOIN', it's also fast (0.129s):

```sql
SELECT visitatie.id AS `id`, visitatie.assigned_user_id AS `assignedUserId`, visitatie.created_by_id AS `createdById`, visitatie.name AS `name`, 
       visitatie.lid_id AS `lidId`, NULLIF(REPLACE(TRIM(CONCAT(IFNULL(lid.initials_name, ''), ' ', IFNULL(lid.first_name, ''), ' ', 
       IFNULL(lid.middle_name, ''), ' ', IFNULL(lid.last_name, ''))), '  ', ' '), '') AS `lidName`, visitatie.regiocode AS `regiocode`, 
       visitatie.visitatiedatum AS `visitatiedatum`, visitatie.resultaat AS `resultaat`, visitatie.created_at AS `createdAt` 
FROM `visitatie`, `contact` as `lid` 
WHERE visitatie.deleted = '0' and visitatie.lid_id = lid.id
ORDER BY visitatie.created_at DESC, visitatie.id DESC LIMIT 0, 200
```

Explain gives the same results. 

Is it possible to optimize the EspoCRM SQL generator so that MariaDB uses it's indexes better? 

Or do I need to do something else? Or am I doing something wrong?

**Comment by yurikuzn** [comment]
I suggest debugging. It should not apply left join unless 'select' is not passed in parameters or it's empty.

P.S. Please be explicit when reporting issues. It's not clear what you do. Steps to reproduce are needed.

**Comment by hdijkema** [comment]
I'm sorry for not being clear. These are the steps to reproduce:

1. I added an entity 'Visitatie'.
2. I added a relation from 'Contact' to 'Visitatie'. One to Many, i.e. one contact has many visitatie records. And each visitatie record only has one contact.
3. I created a list layout with these fields: 'visitatie.date', 'visitatie.result', 'visitatie. contact', 'visitatie.regiocode'
4. I open the 'visitaties', without any selection, so it just lists all visitatie records. 

I hope this is clear.

**Comment by yurikuzn** [comment]
Thanks. I though you meant a relationship panel.

It should not happen that left join is applied. Unless you are using very old EspoCRM version. I'm not sure why it's happening.

**Comment by yurikuzn** [comment]
Check whether 'select' GET parameter is sent to the backend when the list is requested by the frontend.

**Comment by hdijkema** [comment]
Hmm. I'm running EspoCRM almost from the git repository.

**Comment by hdijkema** [comment]
I think this is the get? 

https://crm.nvkh.nl/api/v1/Visitatie?select=name%2ClidId%2ClidName%2Cregiocode%2Cvisitatiedatum%2Cresultaat&maxSize=200&offset=0&orderBy=createdAt&order=desc

**Comment by yurikuzn** [comment]
Select parameter is fine. Since no contact fields are listed, contact table should not be joined.

I suggest debugging from here: https://github.com/espocrm/espocrm/blob/5.9.3/application/Espo/Services/Record.php#L1111.

**Comment by yurikuzn** [comment]
Also here: https://github.com/espocrm/espocrm/blob/5.9.3/application/Espo/ORM/DB/Query/Base.php#L287

Add this to debug:
```
if ($entityType === 'Visitatie') {
    print_r($params);
    die;
}
```

**Comment by hdijkema** [comment]
I see this:

Line 1112: [Sun Jun 28 13:27:52.850913 2020] [php7:notice] [pid 16517] [client [ip]:52989] Array\n(\n    [0] => id\n    [1] => assignedUserId\n    [2] => createdById\n    [3] => name\n    [4] => lidId\n    [5] => lidName\n    [6] => regiocode\n    [7] => visitatiedatum\n    [8] => resultaat\n    [9] => createdAt\n)\n, referer: [website]

Line 1120: [Sun Jun 28 13:27:52.851418 2020] [php7:notice] [pid 16517] [client [ip]:52989] Array\n(\n    [joins] => Array\n        (\n        )\n\n    [leftJoins] => Array\n        (\n        )\n\n    [whereClause] => Array\n        (\n        )\n\n    [customJoin] => \n    [additionalSelectColumns] => Array\n        (\n        )\n\n    [joinConditions] => Array\n        (\n        )\n\n    [orderBy] => Array\n        (\n            [0] => Array\n                (\n                    [0] => createdAt\n                    [1] => 1\n                )\n\n            [1] => Array\n                (\n                    [0] => id\n                    [1] => 1\n                )\n\n        )\n\n    [offset] => 0\n    [limit] => 200\n    [maxTextColumnsLength] => 5000\n    [select] => Array\n        (\n            [0] => id\n            [1] => assignedUserId\n            [2] => createdById\n            [3] => name\n            [4] => lidId\n            [5] => lidName\n            [6] => regiocode\n            [7] => visitatiedatum\n            [8] => resultaat\n            [9] => createdAt\n        )\n\n)\n, referer: [website]

**Comment by hdijkema** [comment]
Output of 

> Also here: https://github.com/espocrm/espocrm/blob/5.9.3/application/Espo/ORM/DB/Query/Base.php#L287
> 
> Add this to debug:
> 
> ```
> if ($entityType === 'Visitatie') {
>     print_r($params);
>     die;
> }
> ```

Output:

[Sun Jun 28 15:27:42.690952 2020] [php7:notice] [pid 17768] [client [ip]:65193] Array\n(\n    [joins] => Array\n        (\n        )\n\n    [leftJoins] => Array\n        (\n        )\n\n    [whereClause] => Array\n        (\n        )\n\n    [customJoin] => \n    [additionalSelectColumns] => Array\n        (\n        )\n\n    [joinConditions] => Array\n        (\n        )\n\n    [orderBy] => Array\n        (\n            [0] => Array\n                (\n                    [0] => createdAt\n                    [1] => 1\n                )\n\n            [1] => Array\n                (\n                    [0] => id\n                    [1] => 1\n                )\n\n        )\n\n    [offset] => 0\n    [limit] => 200\n    [maxTextColumnsLength] => 5000\n    [select] => Array\n        (\n            [0] => id\n            [1] => assignedUserId\n            [2] => createdById\n            [3] => name\n            [4] => lidId\n            [5] => lidName\n            [6] => regiocode\n            [7] => visitatiedatum\n            [8] => resultaat\n            [9] => createdAt\n        )\n\n    [havingClause] => Array\n        (\n        )\n\n)\n, referer: [website]
