### ISSUE TITLE
Record\Count does not always work as expected

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1749]
I had some problems with writing formula code like e.g.:

```php
$num_of_contacts = record\count('Contact', 'regio!=', 'a', 'regio!=', 'b', 'regio!=', 'c');
```

It was solved by modifying RecordGroup\CountType.php as follows:

https://github.com/hdijkema/espocrm/commit/3b2089e1ab10a3339cd28f98bad76a12e72c757b

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/eca5bdea717472d0925517290204c0a912dea78b.
