### ISSUE TITLE
Change request for Espo/Core/Utils/Database/Orm/Base.php

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1751]
> I got it to work without modifying any of the original Espo scripts.

I implemented your solution, but See issue telecastg/person-plus-for-espocrm#3 and issue telecastg/person-plus-for-espocrm#4.

Either you have no use for Contacts as foreignEntities in other Entities, or I'm missing something here. 

I'm creating a new issue with a change request for [Base.php#L225](https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Database/Orm/Base.php#L225)

_Originally posted by @hdijkema in https://github.com/espocrm/espocrm/issues/1719#issuecomment-652837051_

**Comment by hdijkema** [comment]
I'm proposing a solution for Base.php to get the right foreign fields names analogue to:

[Converter.php#L356](https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Database/Orm/Converter.php#L356)

This would change the getForeignField function to:

[Base.php#L223](https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Database/Orm/Base.php#L223)

```php
protected function getForeignField(string $name, string $entityType)
{
    $foreignField = $this->getMetadata()->get(['entityDefs', $entityType, 'fields', $name]);

    if (isset($foreignField['type']) && $foreignField['type'] == 'personName') {
        (...)
    }

    if (isset($foreignField['type'])) {
        $fieldType = ucfirst($foreignField['type']);
        
        $className = '\Espo\Custom\Core\Utils\Database\Orm\Fields\\' . $fieldType;
        if (!class_exists($className)) {
            $className = '\Espo\Core\Utils\Database\Orm\Fields\\' . $fieldType;
        }

        if (class_exists($className) && method_exists($className, 'getForeignField')) {
            $helperClass = new $className($this->getMetaData(), 
                                          $this->getOrmEntityDefs(), 
                                          $this->getEntityDefs(), 
                                          $this->config);
			return $helperClass->getForeignField($name, $entityType);
        }
    }

    return $name;
}
```

The getForeignField function in e.g.  \Espo\Core\Utils\Database\Orm\Fields\PersonName.php would then be something like:

```php
private function getFields($format) 
{
    switch ($format) {
        case 'lastFirst':
            $subList = ['last' . ucfirst($fieldName), ' ', 'first' . ucfirst($fieldName)];
            break;

        case 'lastFirstMiddle':
            $subList = [
                'last' . ucfirst($fieldName), ' ', 'first' . ucfirst($fieldName), ' ', 'middle' . ucfirst($fieldName)
            ];
            break;

        case 'firstMiddleLast':
            $subList = [
                'first' . ucfirst($fieldName), ' ', 'middle' . ucfirst($fieldName), ' ', 'last' . ucfirst($fieldName)
            ];
            break;

        default:
            $subList = ['first' . ucfirst($fieldName), ' ', 'last' . ucfirst($fieldName)];
    }
}

public function getForeignField(string $fieldName, string $entityType)
{
    $format = $this->config->get('personNameFormat');
    return $this->getFields($format);
}

```        

This would solve problems with foreign names like telecastg/person-plus-for-espocrm#4.

**Comment by yurikuzn** [comment]
The code that forms a person name is removed from there.

Now it's handled here: 
`https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Database/Orm/Fields/PersonName.php` (see `selectForeign`).
