### ISSUE TITLE
Wrong total in API response

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#1753]
I upgraded EspoCRM from 5.5.6 to 5.9.3 yesterday and most things appear to be working correctly, but a few of my custom tools, which call the API, are not working at all. After digging into the details, I found at least one odd behavior with API responses. I made the following call in Postman:

```
{host}/api/v1/project?
  sortBy=name&
  maxSize=5&
  where[0][type]=startsWith&
  where[0][attribute]=name&
  where[0][value]=18-0089-D
```

The response has four valid projects, but the total is `-2`:

```
{
  "total": -2,
  "list": [
    {
      "id": "5b72365860f4c953f",
      "name": "18-0089-D1",
      "deleted": false,
      ...
    },
    { ... },
    { ... },
    { ... }
}
```

I tried a the same query with a different entity and the result was the same regardless of how many results are returned; it's always `-2`.

**Comment by yurikuzn** [comment]
`-2` is returned if total is disabled at Administration > Entity Manager > edit entity > Disable record count. It should not be checked by default.

**Comment by bandtank** [comment]
I see. Is that the only effect or does it disable total counts in other places as well?

**Comment by yurikuzn** [comment]
Only in the list view and relationships panels of the same entity type.
