### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#1754]
I am trying websockets for the first time and I can't get them to work correctly. I'm not sure what I'm doing wrong.

I followed the guide on the EspoCRM website to install websockets. Apache and EspoCRM have been updated and configured to use websockets as far as I can tell. However, I see the following error in the chrome console:

```
WebSocket: Could not unsubscribe from recordUpdate.User.5f039c5dea85d5c37.
WebSocket connection to 'wss://localhost/wss?authToken=35418228f7d189c8e98f995ab5e6a3f&userId=5f039c5dea85d5c37' failed: Error during WebSocket handshake: Unexpected response code: 503
```

I don't see anything in the log file even though I set the level to debug. Refreshing the page works as expected, but notifications are not sent until the page is changed. Also, detail views are not updated without a refresh. There are no polled requests in the network browser in Chrome, so I know the websocket configuration is at least being used even though it doesn't appear to be working.

The 503 response code points to the server being the issue, so I checked the service. Here is the service's definition:
```
  1 [Unit]
  2 Description=EspoCRM ABA WebSocket Service
  3 Requires=mysql.service
  4 After=mysql.service
  5 
  6 [Service]
  7 Type=simple
  8 Restart=always
  9 RestartSec=5
 10 StartLimitIntervalSec=0
 11 User=ubuntu
 12 ExecStart=/usr/bin/php /var/www/aba/websocket.php
 13 StandardError=/var/www/aba/data/logs/websocket.log
 14 
 15 [Install]
 16 WantedBy=default.target
```
Here is the service's status, which is obviously part of the issue:
```
$ sudo service espocrm-aba-websocket status
● espocrm-aba-websocket.service - EspoCRM ABA WebSocket Service
   Loaded: loaded (/etc/systemd/system/espocrm-aba-websocket.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

Jul 06 16:45:33 pse-crm systemd[1]: /etc/systemd/system/espocrm-aba-websocket.service:10: Unknown lvalue 'StartLimitIntervalSec' in section 'Service'
Jul 06 16:45:33 pse-crm systemd[1]: /etc/systemd/system/espocrm-aba-websocket.service:13: Failed to parse output specifier, ignoring: /var/www/aba/data/logs/websocket.log
```
I'm not sure what that means or how to fix it. There is no `websocket.log` file, which confirms the problem in the second error statement.

**Comment by bandtank** [comment]
Ok, so part of the issue was the StartLimitIntervalSec parameter. It has to be in `[Unit]` instead of `[Service]`. Once I moved it, the service started:
```
$ sudo service espocrm-aba-websocket status | cat
● espocrm-aba-websocket.service - EspoCRM ABA WebSocket Service
   Loaded: loaded (/etc/systemd/system/espocrm-aba-websocket.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-07-06 17:46:26 CDT; 7min ago
 Main PID: 19987 (php)
    Tasks: 3 (limit: 4667)
   CGroup: /system.slice/espocrm-aba-websocket.service
           └─19987 /usr/bin/php /var/www/aba/websocket.php

Jul 06 17:46:26 pse-crm systemd[1]: Started EspoCRM ABA WebSocket Service.
```
I'm still seeing the 503 error in Chrome, though.

Something else I should point out is the Site URL setting. It was originally set to `https://localhost:443`, but I changed it to `https://localhost` because I saw an error in Chrome saying a connection couldn't be made to `https://localhost:443:443`.

**Comment by bandtank** [comment]
Some more info:

I started looking in `websocket.php` and I'm seeing a lot of configuration parameters that are not in my `data/config.php` file:
```
$isDebugMode = (bool) $config->get('webSocketDebugMode');
$useSecureServer = $config->get('webSocketUseSecureServer');
$port = $config->get('webSocketPort');
'local_cert' => $config->get('webSocketSslCertificateFile'),
'allow_self_signed' => $config->get('webSocketSslAllowSelfSigned', false),
if ($config->get('webSocketSslCertificatePassphrase')) {
if ($config->get('webSocketSslCertificateLocalPrivateKey')) {
$sslParams['local_pk'] = $config->get('webSocketSslCertificateLocalPrivateKey');
```
The only config I have related to websocket is this: `'useWebSocket' => true`.

Somehow it has values for all of these settings:
```
in websocket.php: var_dump($config);

$ php websocket.php  | grep -i webs
      string(18) "webSocketDebugMode"
      string(27) "webSocketSslCertificateFile"
      string(38) "webSocketSslCertificateLocalPrivateKey"
      string(33) "webSocketSslCertificatePassphrase"
      string(27) "webSocketSslAllowSelfSigned"
      string(24) "webSocketUseSecureServer"
      string(13) "webSocketPort"
      string(12) "useWebSocket"
      string(12) "webSocketUrl"
      string(12) "useWebSocket"
      string(12) "webSocketUrl"
```

**Comment by bandtank** [comment]
I opened port 8080 in my firewall after realizing it was closed. The 503 error is now gone, but the other errors persist in the Chrome console:

```
WebSocket: Could not unsubscribe from streamUpdate.Account.5f021f6a453a1ef9e.
WebSocket: Could not unsubscribe from recordUpdate.Account.5f021f6a453a1ef9e.
WebSocket: Could not subscribe to recordUpdate.Account.5f021f6a453a1ef9e.
WebSocket: Could not subscribe to streamUpdate.Account.5f021f6a453a1ef9e.
```

**Comment by bandtank** [comment]
The firewall was the problem. I opened `8443` in addition to `8080` and that did it. Please add this to the documentation on the website as it would have saved me a lot of time.

**Comment by bandtank** [comment]
I thought I should add a few other things in case it helps someone regarding multiple instances of websockets for EspoCRM on the same server. In summary, you have to use a different port for the websocket request (default = 8080) and a different port for the ZeroMQ instance (default = 5555). I changed the ports to 8081 and 5556, respectively, for the second EspoCRM instance.

**The Details**

_Site 1_

`/etc/systemd/system/espocrm-websocket-site1.service`:
```
[Unit]
Description=EspoCRM WebSocket Service Site 1
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=5
User=www-data
ExecStart=/usr/bin/php /var/www/site1/websocket.php
StandardError=file:/var/www/site1/data/logs/websocket.log

[Install]
WantedBy=default.target
```

Add the `proxy_module` statements to the Apache site configuration file (`/etc/apache2/sites-enabled/site1.conf`):
```
<IfModule proxy_module>
  ProxyRequests Off
  <Location /wss>
    ProxyPass ws://site1:8080
    ProxyPassReverse ws://site1:8080
  </Location>
</IfModule>
```

Enable and start the service:
```
sudo systemctl enable espocrm-websocket-site1.service
sudo systemctl start espocrm-websocket-site1.service
```

Turn on websocket support for the first EspoCRM site and it should work.

_Site 2_

`/etc/systemd/system/espocrm-websocket-site2.service`:
```
[Unit]
Description=EspoCRM WebSocket Service Site 2
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=5
User=www-data
ExecStart=/usr/bin/php /var/www/site2/websocket.php
StandardError=file:/var/www/site2/data/logs/websocket.log

[Install]
WantedBy=default.target
```

Add the `proxy_module` statements to the Apache site configuration file (`/etc/apache2/sites-enabled/site2.conf`), but make sure to change the port:
```
<IfModule proxy_module>
  ProxyRequests Off
  <Location /wss>
    ProxyPass ws://site2:8081
    ProxyPassReverse ws://site2:8081
  </Location>
</IfModule>
```

The second site needs additional configuration and code changes to not conflict with the first site's websocket bindings. In `websocket.php`, make the following changes to parameterize the ZeroMQ host and port:
```
-$pull->bind('tcp://127.0.0.1:5555');
+$zmqHost = $config->get('zmqHost');
+$pull->bind($zmqHost);
```

In `data/config.php`, add the following parameters and definitions:
```
'webSocketPort' => 8081,
'webSocketSubmissionDsn' => 'tcp://localhost:5556',
'zmqHost' => 'tcp://127.0.0.1:5556',
```

Enable and start the service:
```
sudo systemctl enable espocrm-websocket-site2.service
sudo systemctl start espocrm-websocket-site2.service
```

Turn on websocket support for the second EspoCRM site and it should work.

**Comment by yurikuzn** [comment]
Instead of modifying `websocket.php` you can copy the file with another name. To prevent its overriding after upgrade.

**Comment by bandtank** [comment]
Okay, good idea. Would it be possible to parameterize the host and port for the ZeroMQ instance? That is the only thing preventing a fully upgrade-safe solution and I think it could be useful for other reasons as well.
