### ISSUE TITLE
Admin panel: Quick search

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1756]
By typing a text it shows matching items.

![quick-search](https://user-images.githubusercontent.com/1006792/87159307-cfdfff00-c2c9-11ea-9c8b-72a504216540.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/a546b77c1081624d6b594f19bcf1df8e4afd8621

**Comment by yurikuzn** [comment]
quick-search

**Comment by o-data** [comment]
Look good, but it can only search /#Admin/. It cannot search deeper level or search not available at other area.

For example:  Entity Manager > Account > Fields
where search would be quite useful especially for entity with your abnormal numbers of field.

**Comment by yurikuzn** [comment]
>  Entity Manager > Account > Fields

Search in admin panel should not search in fields.

**Comment by yurikuzn** [comment]
> highlight

Every line would have highlighted words. There's no point having it.

**Comment by o-data** [comment]
Make sense. But I thought of Highlight because of the scenario below.

If you search "Email" it give good result (Email & Data category).
But searching "Data" and you realize the only "Data" is the Category/Title.

**Comment by o-data** [comment]
> > Entity Manager > Account > Fields
> 
> Search in admin panel should not search in fields.

Would there be much of an advantage of this enhancement if it can't search deeper level? As oppose to the "Ctrl+F" method where search currently yield better result.

For example, searching for "Setting" will give 2 result with Quick search, whereas Ctrl+F give 8 results.

**Comment by yurikuzn** [comment]
I much harder to implement to search deeper levels. I don't like this idea. If one need to search a field name, they should go to Entity Manager field and search there.

It gives less results because it doesn't search description. The less results -- more relevant and shorter list.

**Comment by yurikuzn** [comment]
It would be also good to have keywords to search in, to give relevant results.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/1bd73d787220157baf49a3f7ec6339672093e365

**Comment by o-data** [comment]
All good. That settle it.

I won't disturb you anymore until I new "closed" enhancement issue and giving that a test.
