### ISSUE TITLE
Client stops sending data to over websocket.

### ISSUE THREAD

**Issue by daryl-uc** [espocrm/espocrm#1758]
If I stop using any tasks that depend on WebSocket the socket stops working even though the status is 101. If I refresh the page the sockets work for some time and then stops.
EspoCRM version: 5.8.2

**Comment by daryl-uc** [comment]
On further investigation, I found that the browser closes with status 1006. How can I solve this?

**Comment by DimitryY** [comment]
https://forum.espocrm.com/forum/bug-reports/57642-websocket-with-nginx
