### ISSUE TITLE
Time bug in Calendar: AM vs PM, possibly timezones

### ISSUE THREAD

**Issue by javenschuetz** [espocrm/espocrm#1759]
I noticed that in the calendar, the system treats all pm times as am times. Ie, if you create a meeting for 2pm, it is changed to say 2am. Also, changing the timezone doesn't seem to change the time displayed in the calendar, which makes me wonder if the timezone is being used when displaying events.

If it helps, this was found in the self hosted version via cloudron.

**Comment by yurikuzn** [comment]
I've never encountered such an issue.

**Comment by o-data** [comment]
No issue here either, I don't think timezone would cause this type of error.

Did you write in your time or use the drop down menu?

Any chance that your formula might be converting the time?
