### ISSUE TITLE
Uploading documents - relation between contact / attachment not made

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1763]
One of our users complained about disappearing documents. She had uploaded documents, and they seemed not to have been uploaded at all when she returned to the entity later. At first I thought she had forgotten to click 'update'. However, documents kept disappearing, although they seemed uploaded.

I investigated the issue. It turns out that it is possible to click 'update' too early while uploading a document. As a result, no relation is created between the uploaded document and the entity it is uploaded for. 

E.g. for our Contact entity:

![image](https://user-images.githubusercontent.com/745693/88278989-9a80db80-cce3-11ea-8b05-8c759fd4917f.png)

Clicking on 'update', directly after the "uploading..." message disappears.

![image](https://user-images.githubusercontent.com/745693/88279070-c13f1200-cce3-11ea-9404-eb1c2c9ef8eb.png)

It looks like the document has been uploaded. It actually is uploaded, which we will see later.

Next, refresh the contact screen, and we see:

![image](https://user-images.githubusercontent.com/745693/88279339-2eeb3e00-cce4-11ea-937f-e7c7286762b3.png)

What do we see in the database? This:

![image](https://user-images.githubusercontent.com/745693/88279525-812c5f00-cce4-11ea-8e86-4bfed24e651a.png)

The related type is correct, but no relatedId has been set. 

If one waits a little longer before clicking 'update', the relation **is** created:

![image](https://user-images.githubusercontent.com/745693/88279663-bdf85600-cce4-11ea-8b82-e0db0a75e25a.png)

This has 2 consequences:

1. The end used seems to loose the uploaded document (it actually gets uploaded, but the relation is not created).
2. There exist attachments in the system that have no relation and are not deleted, i.e. they will not be cleaned but are also not reachable via a related entity. 

I don't know what the problem is exactly, but it can be reproduced quite easy. Just upload a document, click as fast as possible on 'update' and somehow one interrupts the process and no relationId is written. 

As said earlier: When I wait a little while, until all seems stable, it works fine.

**Comment by yurikuzn** [comment]
I get a validation error message that uploading is in progress not allowing to save. So I can't reproduce.

**Comment by yurikuzn** [comment]
This code validates: https://github.com/espocrm/espocrm/blob/5.9.3/client/src/views/fields/file.js#L132.

I recommend debuggin.

**Comment by hdijkema** [comment]
If you are too early with clicking, you'll get a validation error indeed. If you click just between the disappearance of the upload message and the actual creation of the relation, you won't get one and still have no related attachment. Maybe it happens somewhere here?

https://github.com/espocrm/espocrm/blob/5.9.3/client/src/views/fields/file.js#L374

 I don't know...

**Comment by yurikuzn** [comment]
Could you move this line https://github.com/espocrm/espocrm/blob/5.9.3/client/src/views/fields/file.js#L374 to the end of the function. Maybe it will work out.

**Comment by hdijkema** [comment]
It didn't , sorry. Somehow in the current file.js it is possible to click update before 'setAttachment()' is called. The end result is that no relation is set. 

I tested this. With some comments in setAttachment(). I was able to click update and actions were performed to save the entity. Afterwards, I saw the function call to setAttachment(). However, this was not saved to the backend. 

```
 VM19126:328 setAttachment 
 VM19126:334 setAttachment end
```
I modified the code a littlebit:

Line 60:
```javascript
   updateLink: null,
```

Line 68 (after inserting the line above) and further:
```javascript
            'change input.file': function (e) {
                var $file = $(e.currentTarget);
                var files = e.currentTarget.files;
                if (files.length) {
                    var el_parent = this.$el.parent();
                    var el = el_parent.find('.inline-save-link');
                    this.updateLink = el;
                    el.css('display', 'none');
                    this.uploadFile(files[0]);
                    $file.replaceWith($file.clone(true));
                }
            },
```

Line 323 and further:
```javascript
        setAttachment: function (attachment) {
            var arr = _.clone(this.model.get(this.idsName));
            var o = {};
            o[this.idName] = attachment.id;
            o[this.nameName] = attachment.get('name');
            this.model.set(o);
            if (this.updateLink !== null) {
                this.updateLink.css('display', 'inline');
                this.updateLink = null;
            }
        },
```

Now I can't save the uploaded file until the attachment id is set in the model.

**Comment by yurikuzn** [comment]
setAttachment is a sync function. It's weird why does this happen.

**Comment by yurikuzn** [comment]
Maybe it takes some time between https://github.com/espocrm/espocrm/blob/5.9.3/client/src/views/fields/file.js#L67 and https://github.com/espocrm/espocrm/blob/5.9.3/client/src/views/fields/file.js#L70 for the browser when a file is big? Could you check please?

**Comment by yurikuzn** [comment]
I checked. It run instantly. I don't understand why the issue occurs.

**Comment by hdijkema** [comment]
No, it doesn't. I did this with a file of 18MB.

2020-07-23T13:22:37.894Z VM22642:76 
2020-07-23T13:22:37.894Z VM22642:78 
2020-07-23T13:22:37.897Z

**Comment by hdijkema** [comment]
It's somewhere during the uploading. Also, one could cancel the upload with the cross sign (
![image](https://user-images.githubusercontent.com/745693/88291597-c195d800-ccf8-11ea-9202-79f0bde10966.png)) during upload. Afterwards, one cannot upload the same file, unless one clicks 'cancel' (I don't know what happens with 'update').

**Comment by hdijkema** [comment]
I refined my solution somewhat:

```javascript
(...)
        searchTypeList: ['isNotEmpty', 'isEmpty'],

        updateLink: null,
        updateLinkColor: null,
        cancelLink: null,
        cancelLinkColor: null,

        events: {
```

```javascript
        uploadFile: function (file) {
            this.blockUpdateLink();

            var isCanceled = false;
```

In uploadFile():

```javascript
(...)
                        attachment.save({}, {timeout: 0}).then(function () {
                            this.isUploading = false;
                            if (!isCanceled) {
                                $attachmentBox.trigger('ready');
                                this.setAttachment(attachment);
                            } else {
                                this.unblockUpdateLink();
                            }
                        }.bind(this)).fail(function () {
                            $attachmentBox.remove();
                            this.$el.find('.uploading-message').remove();
                            this.$el.find('.attachment-button').removeClass('hidden');
                            this.isUploading = false;
                            this.unblockUpdateLink();
                        }.bind(this));
```

In 'setAttachment()':

```javascript
        setAttachment: function (attachment) {
            var arr = _.clone(this.model.get(this.idsName));
            var o = {};
            o[this.idName] = attachment.id;
            o[this.nameName] = attachment.get('name');
            this.model.set(o);
            this.unblockUpdateLink();
        },
```

And two new functions:

```javascript
        blockUpdateLink: function() {
            var el_parent = this.$el.parent();
            var el_update = el_parent.find('.inline-save-link');
            var el_cancel = el_parent.find('.inline-cancel-link');
            this.updateLink = el_update;
            this.updateLinkColor = el_update.css('color');
            this.cancelLink = el_cancel;
            this.cancelLinkColor = el_cancel.css('color');
            el_update.css('pointer-events', 'none');   // Does not seem to work with IE. 
            el_update.css('color', '#c0c0c0');
            el_cancel.css('pointer-events', 'none');
            el_cancel.css('color', '#c0c0c0');
        },

        unblockUpdateLink: function() {
            if (this.updateLink !== null) {
                this.updateLink.css('pointer-events', 'auto');
                this.updateLink.css('color', this.updateLinkColor);
                this.cancelLink.css('pointer-events', 'auto');
                this.cancelLink.css('color', this.cancelLinkColor);
                this.updateLink = null;
                this.cancelLink = null;
            }
        },
```

This makes it impossible to to cancel or update the field while the upload of the file is processing. The upload could be canceled with the cross sign.

Afterwards, the model is correctly saved.

**Comment by hdijkema** [comment]
I think, somehow the 'update' trigger interferes with the uploading process and maybe the validation is not always called?

**Comment by hdijkema** [comment]
Oke. I think there's another problem with the uploading of files:

![image](https://user-images.githubusercontent.com/745693/88292649-33225600-ccfa-11ea-9e72-421673c1f3a4.png)

When, using inline editing, I upload a new file and I click 'cancel', instead of 'update', I also have an uploaded attachment without any relation. I would expect a rollback of the attachment...

**Comment by hdijkema** [comment]
I've decided to make this the workaround for the moment. So I added this code:

```javascript
       unblockUpdateLink: function() {
            if (this.updateLink !== null) {
                var el_update = this.updateLink;
                this.updateLink.css('pointer-events', 'auto');
                this.updateLink.css('color', this.updateLinkColor);
                this.cancelLink.css('pointer-events', 'auto');
                this.cancelLink.css('color', this.cancelLinkColor);
                this.updateLink = null;
                this.cancelLink = null;
                el_update.trigger('click');
            }
        },
```

Instead of letting the user interact, I trigger an update right away.

**Comment by hdijkema** [comment]
To prevent canceling during upload, I also added this:

```javascript
            var removeLink = '<a href="javascript:" class="remove-attachment pull-right"><span class="fas fa-times"></span></a>';
            if (this.updateLink !== null) {
               removeLink = '';
            }
```

**Comment by hdijkema** [comment]
This may also be an issue when uploading multiple attachments.
