### ISSUE TITLE
template helpers not available in email templates

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1764]
When using the helper "numberFormat" `{{numberFormat field_RAW thousandsSeparator=' '}}`
in an email template, it will not get rendered. 

Example : field x , type is Auto-increment, value = 12345

When rendered in email template will show as : 12,345 (system wide setting for thousands separator)

Espo version : 5.9.3

**Comment by yurikuzn** [comment]
Test. Works fine.
