### ISSUE TITLE
Entities for many-to-many relationship tables

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1767]
Entities are available for all many-to-many relationship tables. They are automatically created after clearing cache.

Usage example:

```php
$collection = $entityManager->getRepository('EntityEmailAddress')
    ->where('emailAddressId=', 'someEmailAddressId')
    ->find();
```

**Comment by eymen-elkum** [comment]
Hi @yurikuzn

Will be great if also can list the middle entity on the entity manager, so we can add additional columns

This is useful for my extension link-multiple-inline-list

**Comment by yurikuzn** [comment]
The feature list for 6.0 is frozen.

I don't thing that many-to-many tables should be available as entities on admin UI. The ability to define columns for these tables should be implemented but not in the way that relationships are represented as entities.

**Comment by rabiibrahimi** [comment]
I think it will be great addition if we could access middle tables so we could extend them add more fields etc.
