### ISSUE TITLE
Drop MyISAM support

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1775]
MyISAM storage engine won't be supported. If you have tables that use MyISAM you need to convert them to InnoDB.

This will allow us to utilize transactions.

**Comment by beppe9000** [comment]
great! will the transactions cover the full request including custom code or we need to add transaction manually for hooks?

**Comment by yurikuzn** [comment]
Transactions won't be used in main CRUD operation for now. Only for some specific logic.
