### ISSUE TITLE
getting Not valid data. Field: 'fieldName', type: required error

### ISSUE THREAD

**Issue by Nomansheikh0** [espocrm/espocrm#1777]
I'm getting this error while I'm creating new data via the API.
I'm providing the data but still getting the error.
here are the field details.
`"fieldName": {
            "type": "enum",
            "required": true,
            "options": [
                "",
                "Dummy Data",
            ],
            "isCustom": true,
            "isSorted": false,
            "audited": false,
            "tooltip": false,
            "readOnly": false
        }`
here are the payload data in PHP:
`"fieldName" => "Dummy Data"`
and here are the error message:
`Not valid data. Field: 'fieldName', type: required.`
what I'm missing here?

**Comment by yurikuzn** [comment]
Are you able to create a record via Espo UI? It could be that payload is not sent properly.

**Comment by Nomansheikh0** [comment]
yeah. i can create via UI. i can update a record but can't create new.

**Comment by Nomansheikh0** [comment]
I have other fields to this payload and that's working fine. the only problem with this specific field.

**Comment by yurikuzn** [comment]
Try to replicate the same API call that is made by UI. UI uses the same API. It's definitely something with a script, not Espo API side.
