### ISSUE TITLE
New email sender service

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1778]
Usage example:

```php
$emailSender    
    ->withParams([
        'fromName' => 'Tester',
    ])
    ->withSmtpParams($smtpParams)
    ->withAttachments([$attachment])
    ->send($email);
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/17e420f01b4a0fb9648883588a9917f414f002fc

**Comment by Alejarodriguezc1984** [comment]
Hola me puedes escribir a alejarodriguezc@gmail.com tengo una consulta urgente desde Colombia gracias!
