### ISSUE TITLE
Empty subject emails not imported

### ISSUE THREAD

**Issue by Whrealty** [espocrm/espocrm#178]
If any email is received without a subject line it will not be displayed
You could fix this by adding if null in subject then add "no subject"

**Comment by yurikuzn** [comment]
Actually it's already implemented. Can you provide raw data source of your email to test?

https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Mail/Importer.php#L76

**Comment by Whrealty** [comment]
i see the code and want to believe it works :)

But :) when i receive emails with no subject nothing shows up in the entity but of course the email is in the inbox on the email server

**Comment by yurikuzn** [comment]
If you provide raw source of problem email I will be able to investigate.

**Comment by Whrealty** [comment]
When you say raw data what is it you need. Logs?

The following is the sequence of events

Let's say I have an email test@Tess.com that belongs to a user in the CRM as a personal email. If I send a email to that user from an external email system with no subject line then no record of that email will be created inside the CRM system but the email will have been actually received from the email server and resides in the inbox of the server but the CRM does not create a record when it grabs that email because it does not have a subject line



Woodburn Homes Realty
Ryan Cox | Operations Manager

EMail:Ryan@woodburnhomesrealty.com
TEL: +1 503 710 5183
Web:www.woodburnhomesrealty.com
Address: 1301 Evergreen Rd, Ste. A2
Woodburn, Oregon 97071

**Comment by yurikuzn** [comment]
In Gmail it's available in menu as "Show original".

**Comment by Whrealty** [comment]
i don't use google

you can try to sending yourself a email with no subject from a external email source see if it happens to you.

**Comment by yurikuzn** [comment]
I tried and it worked. Maybe your client sends white space in subject. We could handle this situation.

**Comment by yurikuzn** [comment]
This commit must fix this https://github.com/espocrm/espocrm/commit/8fa95fcce3c2d3ea743ed3a9c57e27fc2528e973

**Comment by yurikuzn** [comment]
Would be helpful to know if there an error in EspoCRM log when such situation occurs.

**Comment by yurikuzn** [comment]
Maybe it will be fixed when we switch to the new version of zend-mail library. But it will in the next major release. 

You can try to apply this https://github.com/zendframework/zen.../pull/78/files to vendor/zendframework/zend-mail/src/Header/HeaderWrap.php

Maybe it will help.

**Comment by Whrealty** [comment]
Ok i have have done testing with the new update.

when sending with a iOS phone with no subject the email will still not post in espo even with the new update 4.2.4

**Comment by yurikuzn** [comment]
Can you open some of such emails in any email client and copy here original content of any of such emails. This feature may be called "Show Original".

**Comment by yurikuzn** [comment]
Will be fixed with the new version of Zend Framework we are applying for 4.3.0 release. Can't do it in hotfix release because first we need to drop php 5.4 support.

**Comment by Whrealty** [comment]
Excellent thank you sir 

Woodburn Homes Realty
Ryan Cox  | Operations Manager

EMail:Ryan@woodburnhomesrealty.com <mailto:ryan@woodburnhomesrealty.com>
TEL: +1 503 710 5183 <tel://15037105183>
Web:www.woodburnhomesrealty.com <http://www.woodburnhomesrealty.com/>
Address:  <https://maps.google.com/maps?um=1&ie=UTF-8&fb=1&gl=us&ftid=0x54955c416885c305:0x6c1dd4afa456bf2a&q=2200+Country+Club+Ct,+Woodburn,+OR+97071&sa=X&ei=IA_cVOGnIcKqNtCRg8gK&ved=0CB8Q8gEwAA&output=classic&dg=brw>1301 Evergreen Rd, <https://maps.google.com/maps?um=1&ie=UTF-8&fb=1&gl=us&ftid=0x54955c416885c305:0x6c1dd4afa456bf2a&q=2200+Country+Club+Ct,+Woodburn,+OR+97071&sa=X&ei=IA_cVOGnIcKqNtCRg8gK&ved=0CB8Q8gEwAA&output=classic&dg=brw> Ste. A2 <https://maps.google.com/maps?um=1&ie=UTF-8&fb=1&gl=us&ftid=0x54955c416885c305:0x6c1dd4afa456bf2a&q=2200+Country+Club+Ct,+Woodburn,+OR+97071&sa=X&ei=IA_cVOGnIcKqNtCRg8gK&ved=0CB8Q8gEwAA&output=classic&dg=brw>
Woodburn, Oregon 97071 <https://maps.google.com/maps?um=1&ie=UTF-8&fb=1&gl=us&ftid=0x54955c416885c305:0x6c1dd4afa456bf2a&q=2200+Country+Club+Ct,+Woodburn,+OR+97071&sa=X&ei=IA_cVOGnIcKqNtCRg8gK&ved=0CB8Q8gEwAA&output=classic&dg=brw>




IMPORTANT NOTICE: This e-mail message is intended to be received only by persons entitled to receive the confidential information it may contain. E-mail messages to clients of Woodburn Homes Realty may contain information that is confidential and legally privileged. Please do not read, copy, forward, or store this message unless you are an intended recipient of it. If you have received this message in error, please forward it to the sender and delete it completely from your computer system. Oregon Real Estate Agency Disclosure <https://woodburnhomesrealty.com/docs/Oregon_Real_Estate_Agency_Disclosure_Pamphlet__992013_ts40268.pdf>
