### ISSUE TITLE
Add OIDC client login (and/or relay) to espocrm

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1784]
That would be great for people who primarily manage employee accounts with espocrm

**Comment by telenieko** [comment]
Implementing an idP is a lot of work, specially if you plan on doing it securely. EspoCRM is not even an HRM.
Not that an idP is not only "employee accounts", you need to manage client keys (apps), scopes, roles, mappings, ...

If you are in the need of a centralised authentication / authorization management you ought to check, maybe, Keycloak or other solutions like it. Keycloak is quite feature complete.

A far more reasonable issue would be to ask for OIDC client authentication, so your CRM could authenticate with a proper idP like GSuite, Keycloak, etc.

**Comment by beppe9000** [comment]
do you know any self-hosted app for this ?

**Comment by telenieko** [comment]
Keycloak project. Open Source, self hosted and quite powerful

**Comment by beppe9000** [comment]
oh perfect i didn't realize, thanks.

**Comment by bhavyaWadhwa** [comment]
Can we use Keyclock in EspoCRM?

**Comment by rodrigoscoelho** [comment]
Interested in it as well

Enviado utilizando um Galaxy S10...

Em sex., 24 de set. de 2021 14:32, bhavyaWadhwa ***@***.***>
escreveu:

**Comment by Dan6erbond** [comment]
Bump. OIDC Authentication via Keycloak, Google, etc. would be really good to have. LDAP is legacy IMHO and Espo is one of the few tools in a set that we're considering, which doesn't support OIDC. Is there possibly a way to make a plug-in out of it?

**Comment by yurikuzn** [comment]
This is already in out TODO list. Any input would be appreciated. Examples, ideas of implementation.

**Comment by yurikuzn** [comment]
OIDC authentication is planned.

Espo as Open ID Provider is not planned, as it's really would require a lot of effort to implement the specification.
