### ISSUE TITLE
Import: 'Update' mode does not update 'belongsTo' relations

### ISSUE THREAD

**Issue by kaminarifox** [espocrm/espocrm#1787]
https://github.com/espocrm/espocrm/blob/6f60a73c62b41c67780629b33a019aad88e11b9f/application/Espo/Services/Import.php#L737

On create mode the $entity->has() method returns false, but while update there always true even if value is empty

**Comment by yurikuzn** [comment]
Thanks for reporting. 

I move the issue to 6.0.0 milestone, since there were some refactoring of the Import tool.

Here's the fix: https://github.com/espocrm/espocrm/commit/1f200d53f84fb09016b5ad26a824681b20072d8a.
