### ISSUE TITLE
HELP - Suddenly my ESPOCRM stopped to work with an Array expected error message on Autoload

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#1789]
I didn't any change on the OS or the Espo. Yesterday was working normally, and, today, it don't load and gives this message on LOG file.
Please, help me.  @yurikuzn @tmachyshyn 

Espo.ERROR: Uncaught Exception TypeError: "Argument 1 passed to Espo\Core\Utils\Autoload\Loader::register() must be of the type array, int given, called in /var/www/html/espocrm/application/Espo/Core/Utils/Autoload.php on line 174" at /var/www/html/espocrm/application/Espo/Core/Utils/Autoload/Loader.php line 62 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Espo\\Core\\Utils\\Autoload\\Loader::register() must be of the type array, int given, called in /var/www/html/espocrm/application/Espo/Core/Utils/Autoload.php on line 174 at /var/www/html/espocrm/application/Espo/Core/Utils/Autoload/Loader.php:62)"} []

**Comment by rodrigoscoelho** [comment]
@eymen-elkum Help if possible...

**Comment by eymen-elkum** [comment]
You may added a formula! 

this can happen if u are trying to set array value to multi enum field.

**Comment by rodrigoscoelho** [comment]
> You may added a formula!
> 
> this can happen if u are trying to set array value to multi enum field.
> 
> If so just remove the formula or fix it.

I didn't do nothing.. Really.... How to trace it? Any help?

**Comment by yurikuzn** [comment]
Could be corrupted cache files. Try to remove `data/cache` manually.

**Comment by rodrigoscoelho** [comment]
Thanks @yurikuzn , it worked. 

Any clue why this happened? 

Thanks anyway.

**Comment by yurikuzn** [comment]
I don't know. Could be a race condition issue. I have never encountered such a problem before.
