### ISSUE TITLE
Delete scope level bug

### ISSUE THREAD

**Issue by vov1** [espocrm/espocrm#179]
Users with no delete rights able to delete records on entity list page [https://snag.gy/k4lhNP.jpg](https://snag.gy/k4lhNP.jpg).
It is not only an interface bug, because records deleted from the list.
I found this on custom created entity (type: Person).

**Comment by yurikuzn** [comment]
They can delete records they just created and didn't assigne to another person. It's how it was designed. Is it your case?

**Comment by vov1** [comment]
No. Records created by another user (thru API) and assigned to api user.
Another user, with no delete permissions can dellete any record (created by him or not), using actions menu on entity list page.

**Comment by yurikuzn** [comment]
Can you check what access is applied to user. Administration > Users > choose user > click Accsess. What access level is for Delete and Edit actions?

**Comment by yurikuzn** [comment]
I could reproduce with 'own' level. With 'no' level it doesn't allow.

**Comment by yurikuzn** [comment]
Will be fixed in the next minor release. Thank you.

**Comment by vov1** [comment]
> I could reproduce with 'own' level. With 'no' level it doesn't allow.
You're quite right.
