### ISSUE TITLE
Could not load 'crypt' service

### ISSUE THREAD

**Issue by abrahamfast** [espocrm/espocrm#1790]
I'm trying to install Master Branch. I filled in the parts of the database and checked the required system then installed the button but an unexpected error occurred

```
Espo.ERROR: Uncaught Exception Espo\Core\Exceptions\Error: "Could not load 'crypt' service." at /home/vagrant/code/espocrm/application/Espo/Core/Container.php
```

**Comment by yurikuzn** [comment]
Master is a development branch and can have issues.

**Comment by yurikuzn** [comment]
I tried to install a build from master and it worked fine.

**Comment by abrahamfast** [comment]
i don't know why that not works correctly.
But it works well in new sample.
thank you
