### ISSUE TITLE
Missing entity for Folder in Email.json

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#1792]
There is missing line:

  "entity": "EmailFolder"

` "folder": {
            "type": "link",
            "notStorable": true,
            "readOnly": true,
            "entity": "EmailFolder"
        },
`
in
application/Espo/Resources/metadata/entityDefs/Email.json

So when we are creating Workflow after create of email and moving it to folder (for sent emails) - this is not working.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/70660989574b44f1f97a67b0441402883cb19463
