### ISSUE TITLE
Hook before save not affect the returned entity

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#1798]
I have used the hooks for the first time today, and just noticed that using beforeSave is not affecting the returned results of entity.

It is working perfectly but I need to reload the page to see the results I made in the entity by the hook.

Is this by design or an issue?

**Comment by yurikuzn** [comment]
It must return values set in beforeSave hook. There must be some reason why it doesn't in your case.

**Comment by eymen-elkum** [comment]
Is it because I use common hook in an extension ? here is my code:

<img width="826" alt="Screen Shot 2020-10-02 at 10 46 02 AM" src="https://user-images.githubusercontent.com/2862528/94899732-789e9480-049c-11eb-8d6a-c5abe415715f.png">

**Comment by eymen-elkum** [comment]
By the way, can I make hook for specific field types?

**Comment by yurikuzn** [comment]
I don't think it's because the hook is Common. I suggest to debug to find a place where the attribute is set back.

Hooks are only per entity type.

**Comment by yurikuzn** [comment]
Try to print value in `Service\Record` update method.

**Comment by eymen-elkum** [comment]
I printed [here](https://github.com/espocrm/espocrm/blob/hotfix/5.9.4/application/Espo/ORM/Repositories/RDB.php#L146) and got NULL
<img width="662" alt="Screen Shot 2020-10-02 at 10 55 28 AM" src="https://user-images.githubusercontent.com/2862528/94900545-d97a9c80-049d-11eb-8e18-cb7722fffc58.png">

**Comment by eymen-elkum** [comment]
You can check this back when you have the time and keep this issue opened, I made many tests and found like if the hook works in parallel and not in sequence, maybe I am wrong

**Comment by bandtank** [comment]
Do you have websockets enabled? In my experience, the page does not update after a value is modified unless websockets are enabled. Maybe this was fixed in a past release and I didn't become aware of it due to websockets, but it's possibly something to consider.
