### ISSUE TITLE
It is missing Drop File to attach on Documents Window

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#180]
It is missing Drop File to attach on Documents Window, Version 4.2

**Comment by yurikuzn** [comment]
I can drag and drop file. Please more details.

**Comment by rodrigoscoelho** [comment]
Go to documents
Create a new document.

Try to Drag and drop a file inside the attachment icon. it doesn't work here. Using Chrome.

**Comment by yurikuzn** [comment]
I did it and it worked. Maybe cached something?

**Comment by yurikuzn** [comment]
Please let us know if you still have this problem.
