### ISSUE TITLE
Email: Creating meetings from emails with ics attachment

### ISSUE THREAD

**Issue by githubkoma** [espocrm/espocrm#1806]
Dear Team,

when will it be possible to import .ics Calendar Invitations from Email to a specific Calendar?

thanks in advance for answering and best wishes to you!

**Comment by yurikuzn** [comment]
Hi,

Not planned at this moment.

**Comment by githubkoma** [comment]
Dear @yurikuzn ,
thanks for your reply. is there any feature request possibility? :-)
Or does this have more impact if we are an advance pack customer?

best regards

**Comment by yurikuzn** [comment]
This is added to my TODO list. But a have hundreds of other items in that list.

If you have ideas how you see this feature working please share.

**Comment by o-data** [comment]
May be relevant: https://github.com/MartinThoma/ics-parser

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/e514a34e6090f4825784cb12b3e791cf241394e6

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3e9556e1ef9564adb8acd903d37b3fad13c5b2d5

**Comment by yurikuzn** [comment]
![ics](https://user-images.githubusercontent.com/1006792/126463742-de4f8bf3-3b86-443f-8f35-d123b311adc4.png)

**Comment by IHAARRR** [comment]
> ![ics](https://user-images.githubusercontent.com/1006792/126463742-de4f8bf3-3b86-443f-8f35-d123b311adc4.png)

Hello. How did you make it? We have the same issue. Our version is 8.1.4

**Comment by yurikuzn** [comment]
Whenever an email with a proper ICS attachment is viewed, the panel should appear. I recommend using our forum for more help.

**Comment by IHAARRR** [comment]
> Whenever an email with a proper ICS attachment is viewed, the panel should appear. I recommend using our forum for more help.
email with a proper ICS attachment is viewed, the panel should appear. **- This is good.** 

But, is it posiible to create meeting from email in same way like creating task or contact?
