### ISSUE TITLE
Feature request: Two Factor Authentication for Portal Users (TOTP)

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1810]
EspoCRM supports 2FA for normal users. 

However, somehow it doesn't seem to support 2FA for portal users. 

I see this on the forum: https://forum.espocrm.com/forum/feature-requests/58228-enable-2fa-for-portal-user

But it looks like it's currently not supported out of the box.

**Comment by yurikuzn** [comment]
Implemented in v7.4.
