### ISSUE TITLE
Kanban: Ability to sort items within a group

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1825]
Ordering items using drag and drop. Order will be applied only for a current user, meaning it will not affect on how kanban items are ordered for other users.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/8cdbcdcb8cb073577114c6e4f839b0e01f1592f5

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/fad183e20afc231b2c47afa2e2a6390d2114825e

**Comment by tomaspar** [comment]
It would be nice to have ordering for all team, it would help to set team manager priorities for all.
