### ISSUE TITLE
Error log in espocrm v6

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#1829]
Hi,

Before espocrm v6 the log was more than enough, after I upgraded to v6 I found myself visiting the the general server php error log from time to time.

Some errors are logged and many others are not.

I wonder if there is something I have to do with the new version

**Comment by yurikuzn** [comment]
Hello,

This should fix the problem: https://github.com/espocrm/espocrm/commit/651b0be5eddb065022ee9c428b73e8324d18d53b.

**Comment by eymen-elkum** [comment]
I confirm the issue has been fixed by this commit, it is great!
