### ISSUE TITLE
New window hyperlinks

### ISSUE THREAD

**Issue by Whrealty** [espocrm/espocrm#183]
Currently throughout the entire system if you ever make a hyperlink it opens in the current window this includes for downloads is it possible to make the default open in a new window

**Comment by yurikuzn** [comment]
Do you talk about fields of URL  type?

**Comment by Whrealty** [comment]
No not URL Field type

In multi file & file field it is set to open under same window

Also any hyperlink in the system that is posted. Like when you post a hyperlink in the stream it will open the link in same window.

**Comment by yurikuzn** [comment]
For attachments: https://github.com/espocrm/espocrm/issues/185
