### ISSUE TITLE
Entity Manager: Separate page for entity

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1833]
Can be accessed by: Administration > Entity Manager > click on specific entity type.

Fields, relationships, layouts, formula, entity parameters can be accessed from this page. Before, an access point for all these functions was the list view (Administration > Entity Manager) that was not that handy.

![em](https://user-images.githubusercontent.com/1006792/98239453-a7fb6200-1f70-11eb-9c9b-9b27018e30c5.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/2d385c163fcba4544ac461932aa8544e0778f8ba

**Comment by eymen-elkum** [comment]
Yuri, I have an idea for better UX,

Why not to add those links directly to entity manager index page ?

I liked the idea of grouping all entity related admin pages in one panel, but we also need those links on every page.

For example:

In the account layout page, we can add those links to the header, then we dont need back to the account admin page to navigate to the field manager!

What do u think

As always I appreciate contributing this if you liked the idea, but I see u like to do things by yourself!

**Comment by yurikuzn** [comment]
My concern was a higher change of accidental editing wrong entity type.

**Comment by eymen-elkum** [comment]
I liked the idea of grouping the 4 admin pages in one panel, but the place where it located will force the user for one more click to access the field manager, and I think this is not compatible with the old behaviour.

If you liked my idea you will not need the layout manager link on the admin index any more!

I am preparing a screenshot of what I means

**Comment by eymen-elkum** [comment]
<img width="1015" alt="Screen Shot 2020-11-06 at 1 48 27 PM" src="https://user-images.githubusercontent.com/2862528/98357767-c166e180-2036-11eb-8e53-d569acbff396.png">

**Comment by eymen-elkum** [comment]
> My concern was a high chance of accidental editing wrong entity type.

As everything is driven by the url I think we can manage to not letting any problem happens!
