### ISSUE TITLE
Entity-level control of htmlizer feature to prevent tag stripping when using raw html string in mail templates

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1837]
From my past experiences (not recent, tho) htmlizer feature messes up email templates when the template is a full html string. 

An improvement to this could be to add a `isRawHtml` checkbox field to `EmailTemplate`, to control this behaviour per-entity instead of only forcing it globally with the config value of `emailTemplateHtmlizerDisabled`.

Maybe also use the simple text area when this is checked. 

My goal here is to copy/paste a previously made html string in a template to use in mass emails with the guarantee of it staying unchanged except for template string substitution of `{{xxx}}` tokens.

https://github.com/espocrm/espocrm/blob/710decc6105a8cc1ed505c092795088475fbdd65/application/Espo/Services/EmailTemplate.php#L149

I'll probably work on this myself, but I'd like some feedback about handling this for interactive template usage (e.g. a user selects the template for composing an email vs mass email).

**Comment by yurikuzn** [comment]
Could you tell what exactly is messed up? I'm not sure whether I understood the problem. Maybe we could address the problem somehow differently than just disabling the Htmlizer.
