### ISSUE TITLE
Missing features after update to 6.0.3

### ISSUE THREAD

**Issue by EmpireOneDevs** [espocrm/espocrm#1841]
Hi there,
List View -> Actions Dropdown -> Export option is missing after updating to the last version, ( 6.0.3 ),
Any idea how to bring it back ?
thanks

**Comment by EmpireOneDevs** [comment]
![image](https://user-images.githubusercontent.com/40423351/99082492-e4f8d180-25cc-11eb-9ef1-f2284fb64de2.png)
Found this checkbox here, however my user is Admin , no export option was available on the records list view.
Thanks

**Comment by EmpireOneDevs** [comment]
LOL, unchecked the above, the export option is missing for admin as well. so apparently this is an issue.

**Comment by yurikuzn** [comment]
Here's the fix: https://github.com/espocrm/espocrm/commit/700f4b5b10a7be73f2ae365616f323c0e5398737
