### ISSUE TITLE
Field "Link" checkbox bud in list view

### ISSUE THREAD

**Issue by tomaspar** [espocrm/espocrm#1845]
Hello, I figured out that in Opportunities and in some other modules, "layout manager" ->"list" iems the "Link" checkbox is not working as it supposed to do. And it's looks like it's a big **Bug in a whole system** "Layout Manager" -> "List" view. 

As example: we use Opportunity module for our deals registration and sales opportunity management. There are in a list account name and product name, and some other fields in flis view:
![Screenshot 2020-11-17 at 11 56 44](https://user-images.githubusercontent.com/45912754/99376154-37880580-28cd-11eb-8efb-a50845f3aad8.png)

In product field edit mode "Link" is unchecked, so I expect in a listview to see just a name column, not a product name as link to it.

![Screenshot 2020-11-17 at 11 56 29](https://user-images.githubusercontent.com/45912754/99376364-8170eb80-28cd-11eb-89ca-e2a501cd1230.png)

But in List of my Opportunities all products are shown as a names with a links.

![Screenshot 2020-11-17 at 11 58 15](https://user-images.githubusercontent.com/45912754/99376458-a49b9b00-28cd-11eb-9cf5-48b883ce391c.png)

The same is with other fields and it's annoying when you have a list of different attributes in a list with a links and  incidentally press on a wrong one.  For this scenario in Opportunities list there are no sense to have an entry to "product" card, as it is using just for screening of all opportunities. The same with account or other fields.

Ideal solution: Possibility to manage the list view when the column have "link" entries or when it's only a names without links.

**Comment by yurikuzn** [comment]
The "link" parameter is not supposed to work the way you expect.

**Comment by tomaspar** [comment]
Can you transfer it to "feature request" then.

**Comment by yurikuzn** [comment]
As a workaround you can create a custom view for your fields with custom list template.
