### ISSUE TITLE
XLSX Export error when there are rows with empty currency

### ISSUE THREAD

**Issue by EmpireOneDevs** [espocrm/espocrm#1846]
Hi there,

Upgraded to the latest version 6.0.5, the list export doesn't work for any entity, the 
Administration -> Settings -> Disable Export (only admin is allowed)  checked/unchecked, doesn't help.

**Comment by yurikuzn** [comment]
Hi,

Please check https://docs.espocrm.com/administration/troubleshooting/#check-logs

**Comment by EmpireOneDevs** [comment]
`[2020-11-18 07:23:13] Espo.ERROR: Slim Application Error Type: TypeError Code: 0 Message: Argument 1 passed to Espo\Tools\Export\Formats\Xlsx::getCurrencyFormatCode() must be of the type string, null given, called in /srv/users/serverpilot/apps/espo/public/application/Espo/Tools/Export/Formats/Xlsx.php on line 359 File: /srv/users/serverpilot/apps/espo/public/application/Espo/Tools/Export/Formats/Xlsx.php Line: 670 Trace: #0 /srv/users/serverpilot/apps/espo/public/application/Espo/Tools/Export/Formats/Xlsx.php(359): Espo\Tools\Export\Formats\Xlsx->getCurrencyFormatCode(NULL) #1 /srv/users/serverpilot/apps/espo/public/application/Espo/Tools/Export/Export.php(323): Espo\Tools\Export\Formats\Xlsx->process('Payment', Array, NULL, Resource id #12) #2 /srv/users/serverpilot/apps/espo/public/application/Espo/Services/Record.php(2254): Espo\Tools\Export\Export->run() #3 /srv/users/serverpilot/apps/espo/public/application/Espo/Core/Controllers/Record.php(288): Espo\Services\Record->export(Array) #4 /srv/users/serverpilot/apps/espo/public/application/Espo/Core/ControllerManager.php(109): Espo\Core\Controllers\Record->actionExport(Array, Object(stdClass), Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #5 /srv/users/serverpilot/apps/espo/public/application/Espo/Core/Api/RouteProcessor.php(84): Espo\Core\ControllerManager->process('Payment', 'export', Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #6 /srv/users/serverpilot/apps/espo/public/application/Espo/Core/ApplicationRunners/Api.php(184): Espo\Core\Api\RouteProcessor->process('/{controller}/a...', Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #7 /srv/users/serverpilot/apps/espo/public/application/Espo/Core/ApplicationRunners/Api.php(112): Espo\Core\ApplicationRunners\Api->processRequest(Array, Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper), Array) #8 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Espo\Core\ApplicationRunners\Api->Espo\Core\ApplicationRunners\{closure}(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #9 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #10 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Psr7\Request)) #11 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #12 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #13 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Psr7\Request)) #14 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(60): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request)) #15 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner)) #16 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Psr7\Request)) #17 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #18 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Psr7\Request)) #19 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #20 /srv/users/serverpilot/apps/espo/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Psr7\Request)) #21 /srv/users/serverpilot/apps/espo/public/application/Espo/Core/ApplicationRunners/Api.php(94): Slim\App->run() #22 /srv/users/serverpilot/apps/espo/public/application/Espo/Core/Application.php(107): Espo\Core\ApplicationRunners\Api->run(NULL) #23 /srv/users/serverpilot/apps/espo/public/api/v1/index.php(37): Espo\Core\Application->run('Espo\\Core\\Appli...') #24 {main} Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
`

**Comment by EmpireOneDevs** [comment]
Solved, one of the export records did not have the amount & currency.
Anyway there should probably be some error handling to avoid errors for this?

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/25bc3a40f7d165633bf8f0306dac5b4ed953a534
