### ISSUE TITLE
Customize report for "Group by"

### ISSUE THREAD

**Issue by Eliobencini** [espocrm/espocrm#1847]
Hi,
I need a customized solution for a "group by" in a Report. We have different Items [A, B, C, D, E];  ABC are under the same category (ex. Black) and DE are under the category (ex. red).
In the report, I would like to visualize the total count and sum for each category Black and Red, instead of the single item.

How and Where can I write the right code to archive this output?

thanks in advance.

**Comment by yurikuzn** [comment]
Hi,

This repository does no have reports extension.

**Comment by Eliobencini** [comment]
Hi Yurikuzn, can you give me more details?
