### ISSUE TITLE
Navbar: Tab groups

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1848]
The ability to group tabs in sub-menus in the navigation bar.

A group tab can have:

* label
* icon
* color

![group-tab](https://user-images.githubusercontent.com/1006792/100222433-bc54ce00-2f22-11eb-9868-d19baece1214.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/427237627805c69decf3e2b111e739a0df81befc

**Comment by nishan56838** [comment]
I was trying develop this, but at last. Thank you yuri for this option. Hope to see the sub menu visible in expandable menu.

**Comment by yurikuzn** [comment]
Group-tabs will also work if they are placed under *show more* `...` separator.

**Comment by Doopin** [comment]
How to add the group tab?

**Comment by DODOM2** [comment]
I have this issue Yuri on group tabs. Its not displaying to the right like your screenshot above.  Current version: 6.1.0 
![image](https://user-images.githubusercontent.com/11394080/107394820-e0579280-6ac1-11eb-95c1-64d09330af1c.png)

**Comment by eymen-elkum** [comment]
@DODOM2 are you using the nav-pro extension from eblasoft ?

**Comment by DODOM2** [comment]
I'm not. I couldn't ever get it working without losing my scroll abilitySent via the Samsung Galaxy S10e, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Eymen Elkum <notifications@github.com> Date: 2/10/21  7:25 AM  (GMT-06:00) To: espocrm/espocrm <espocrm@noreply.github.com> Cc: DODOM2 <DODOM2@eBSCOMPANYKY.COM>, Mention <mention@noreply.github.com> Subject: Re: [espocrm/espocrm] Navbar: Tab groups (#1848) 
@DODOM2 are you using the nav-pro extension from eblasoft ?
