### ISSUE TITLE
Base64 images don't work with gmail

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1854]
GMail and other mailers don't work with base64 encoded images in emails.

However, attached images with a 'CID' id, do work.

https://stackoverflow.com/questions/46783599/base64-encoded-image-is-not-showing-in-gmail/46789485

So, maybe the MassEmail extension can be used to include the base64 encoded images as attachments and and reference them using a CID?

**Comment by yurikuzn** [comment]
Could  you give more details? Where in EspoCRM we have base64 encoded images?

**Comment by hdijkema** [comment]
So this is what we have:

![image](https://user-images.githubusercontent.com/745693/100671586-0a256800-3361-11eb-888e-438acce2d762.png)

This email template is filled with a knowledgebase article and sent to our members.

In the HTML, the images are encoded with base64. 

I don't mind attaching the images and referencing them using an Id (CID) , but the mailer has to fill in a CID that one requests somewhere and provide it in the Mime part. 

Or one could automate it, strip all base64 images data from the HTML and put them in attachements while providing a CID reference in the mail.

**Comment by hdijkema** [comment]
This is the result of a mailing in gmail:

![image](https://user-images.githubusercontent.com/745693/100715213-23590380-33b7-11eb-967d-3dba7ba48bef.png)

**Comment by yurikuzn** [comment]
But Espo doesn't have the ability to attach images to in base64 as far I know. I don't think that we should parse base64 images on sending.

**Comment by hdijkema** [comment]
It's the HTML that doesn't work. The email has no attachments. Or am I not understanding this?

**Comment by yurikuzn** [comment]
I meant that Espo doesn't provide the ability to insert images as base64 into HTML. Even if you copy past an images, it inserts it as an inline attachment. Implementing the parsing of base64 images is an overhead I think.

**Comment by hdijkema** [comment]
I'm confused. The version of EspoCRM used is 5.9.3. When I copy an image in the email template-text, it is inserted as a base64 data image. Which probably is the behaviour of 'summernote'.

**Comment by yurikuzn** [comment]
We have customized insert image logic. I tested in chrome and FF and it inserted as an attachment, not base64.

**Comment by hdijkema** [comment]
Oke, I understand now.  Maybe it works differently when I paste the image? But I inserted the images now using the 'insert image' button. That looks like it works, however, it gives `<img style="width: 670px;" src="?entryPoint=attachment&amp;id=5fc61ac980fe51359">`, which results in a not  'image not found', because it resolves to nothing in the email.

When I change this to `<img style="width: 670px;" src="https://crm.domain.mine?entryPoint=attachment&amp;id=5fc61ac980fe51359">`, it results in a 403, permission denied.

So, what I eventually did, was make a public place in our crm system and put the image there and change the <img tag to

```html
<img style="width: 670px;" src="https://crm.domain.mine/public_place/header.png">
```

That resulted in a working solution.

**Comment by yurikuzn** [comment]
I used ctrl+v when tested.

**Comment by hdijkema** [comment]
Yes your right. I probably have added the HTML for the base64 images myself. 
The above problem stays however.

**Comment by yurikuzn** [comment]
I don't think we need this feature implemented.

**Comment by hdijkema** [comment]
Oke. Thanks for your consideration.
