### ISSUE TITLE
Advanced pack workflow : unclarity about executeFormula -> {$$variable}

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1857]
As stated in [this forum post]( https://forum.espocrm.com/forum/extensions/64726-flowcharts-send-http-request-beforevalue?p=64753#post64753 ) workflows would be able to assign a var with executeFormula and use its value subsequently in another action.

Documentation states this functionality is only available in BPM.  

Having this functionality in single workflows (without BPM) would be highly appreciated.

**Comment by hturkoz** [comment]
+1

**Comment by yurikuzn** [comment]
Hi,

This repository does not include Workflows feature.
