### ISSUE TITLE
Feature suggestion : allow monolog amqp handler

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#1858]
When hosting Espo in a cloud environment, like Azure or AWS, AMQP may be used for logging (EventHub or Amazon MQ)

Monolog has a corresponding handler for that. ( https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/AmqpHandler.php )

It would involve a.o.

- enabling php-amqp extension, 
- including the monolog handler 
- allowing connection strings in the configuration /data/config.php
- allowing AMQP in the logger section of the configuration

Any thoughts are welcome,

**Comment by yurikuzn** [comment]
Covered in this issue: https://github.com/espocrm/espocrm/issues/1861
