### ISSUE TITLE
Feature request - disable 'Show list'

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1860]
Maybe I'm missing something in the clientDefs, but AFAIK it is not possible to prevent the 'Show List' button from appearing.
Am I right? 

```json
    "relationshipPanels": {
        "nascholingen1": {
            "select": false,
            "create": true,
            "remove": true,
            "unlinkDisabled": true,
            "layoutDetailDisabled": false,
            "showListDisabled": true,
            "sortBy": "name",
            "asc": true
         }
    }
````

I'm trying something like 'showListDisabled', or 'listDisabled', etc. 

If the option is not there, this is a feature request :-)

**Comment by yurikuzn** [comment]
Here: https://github.com/espocrm/espocrm/blob/6.0.8/client/src/views/record/panels/relationship.js#L91
