### ISSUE TITLE
Wrong field validation exclusions check

### ISSUE THREAD

**Issue by krasov** [espocrm/espocrm#1866]
https://github.com/espocrm/espocrm/blob/521a166c9232529340cb260dea09027bb98a08a3/application/Espo/Services/Record.php#L734

Here we should check if the $field is in the exclusions field list, but now check the type

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/9fbc62837f8eb9f0cc3b654cc2043c3f4a6e3d45
