### ISSUE TITLE
API: Use JSON for GET search parameters

### ISSUE THREAD

**Issue by TheDutchMC** [espocrm/espocrm#1870]
Hi,

I was wondering if it would be possible to add JSON 'encoding' support for GET requests to the API. An example of the current format of doing parameters:
`select=emailAddress&where[0][type]=linkedWith&where[0][attribute]=account&where[0][value]=SomeAccountId`

This doesn't work too comfortable when trying to interact with the API from another language than PHP, JS or Python.

So, the feature request is as follows:
Add support for json encoded parameters for GET requests in the API. This would also add consistency to it, since every other type of request already uses it.

Thanks!

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/7d95969f03aca7126a97cf8167b30bcfcc8dd599

**Comment by TheDutchMC** [comment]
Neat!

If I'm undertanding this correctly, the query parameters in full would now look like `?searchParams=<JSON here>`, correct?

**Comment by yurikuzn** [comment]
Correct.

**Comment by TheDutchMC** [comment]
Awesome. Thanks!
