### ISSUE TITLE
HTTP 500 when PUT'ing into Account field, where the value is a long url

### ISSUE THREAD

**Issue by TheDutchMC** [espocrm/espocrm#1871]
EspoCRM version: 6.0.8
Host: Ubuntu 20.04 in an LXC
Authentication type: HMAC

Request payload: (some parts have been replaced with example values)
```
{
  "mailSync": "https://example.com/all-mail.php?addresses=example1@example.com,example2@example.com,example3@example.com,example4@example.com.,example5@example.com,example6@example.com,example7@example.com,example8@example.com,example9@example.com"
}
```

When making a PUT request to https://espocrm.example.com/api/v1/Account/someAccountId with the payload above, the server returned a HTTP-500 code.

The mailSync field is of type URL. Espo does not fail for all the other requests I make to it, though those have a shorter body.
The mailSync field does not have a length limit.

API client: Custom Java implementation

Hope this can be solved,
Thanks!

**Comment by yurikuzn** [comment]
It could be that your web server produces the error. All Espo errors are available in log.

**Comment by TheDutchMC** [comment]
That is a good point yeah,

Just checked my NGINX logs, of both the proxy and the webserver hosting EspoCRM. None show errors there.

Also checked Espo's log. It is as follows:
```
String data, right truncated: 1406 Data too long for column 'mail_sync' at row 1; PUT /Account/141762063; line: 72, file: /var/www/espocrm/application/Espo/ORM/SqlExecutor.php [] []
```

Seems to be an issue with the MySQL fields not being large enough to accommodate longer URLs? The total length of the parameters is about 250 characters, which is less than the ~2000 characters which is generally seen as the limit ([source](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers))

A solution I think would be to make the field in MySQL larger?

**Comment by yurikuzn** [comment]
Try making max-length larger in metadata or via Administration > Entity Manager.

**Comment by TheDutchMC** [comment]
That indeed does fix it.

So the default size isn't large anough
