### ISSUE TITLE
Error when filtering only 'Active' contacts on the account detail view

### ISSUE THREAD

**Issue by lucakuehne** [espocrm/espocrm#1878]
When I'm filtering the contacts on an account to only view the active contacts for a company I get an error 500.
I also doublechecked using the EspoCRM public demo and there the issue occurs as well.

**Comment by yurikuzn** [comment]
Thanks.

Fix: https://github.com/espocrm/espocrm/commit/e073c82992be4dde447cd61e8dda58050ed4654e
