### ISSUE TITLE
Feature Request: Allow to create loops without using script

### ISSUE THREAD

**Issue by lucakuehne** [espocrm/espocrm#1879]
I got a feature request for the Advanced Pack.
Could you please add the ability to create loops (like _while_ or _foreach_) in BPMs using the visual designer, without the need to use a script?
That would make it much easier for users to create processes involving loops and the flowchart is much clearer to view.

**Comment by yurikuzn** [comment]
Hi,

Advanced pack is out of scope of this repository.

**Comment by lucakuehne** [comment]
Sorry, didn't know that.
Were can I post feature requests for the extensions like Advanced Pack? 😄

**Comment by yurikuzn** [comment]
Forum Feature Request section is fine.
