### ISSUE TITLE
Workflow Wont Trigger

### ISSUE THREAD

**Issue by Doopin** [espocrm/espocrm#1880]
I have a module with a "many to many" relationship field.
I would like to run a service via the workflow module when new record is linked/related to this entity.
I have used the "After record updated" trigger type.
When I update any field, the workflow runs well but when I link/relate a new record of this many to many relationship, it does not trigger the workflow.
I suppose its an issue ? Please let me know how to resolve

Thanks
[image](https://forum.espocrm.com/filedata/fetch?photoid=65924)

**Comment by yurikuzn** [comment]
Could you please create a topic on our the https://forum.espocrm.com/ or in the customer portal. Advanced pack is out of scope of this repository.
