### ISSUE TITLE
Enhancement: CSS based on portal context

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1884]
I'm using the css selector:  

```css
.main-portal 
```

to hide some elements I don't want to show in the portal environment for portal users.

However, the modal dialogs are not contained within this class.

So I'd propose to add a class to the body element, or an extra DIV element to the main.html page that makes it possible to use css selectors in de portal environment. E.g.:

```html
<body  class="{{appClientClassName}}">
```

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/d7b9b65990cd3a99ef3e28f879d1abbeef2d025f
