### ISSUE TITLE
Container: Preload on application start

### ISSUE THREAD

**Issue by Ananyakokala** [espocrm/espocrm#1886]
**Description:**
Follow Up with Issue: https://github.com/espocrm/espocrm/issues/1495
The new release 6.0.9 has this feature support. But, the new release changes are not supporting this feature as expected.
I am trying to integrate the sentry with the ESPOCRM. We need to preload this class. And also did the same as mentioned [here](https://github.com/espocrm/espocrm/issues/1495#issuecomment-561580915)

**Diagnostics:**
-  Uncaught Exception TypeError: "Return value of Espo\Core\Container::getLoader() must implement interface Espo\Core\Loaders\Loader or be null, instance of Espo\Modules\Common\Core\Utils\SentryLoader returned"
-  Uncaught Exception Espo\Core\Exceptions\Error: "Could not load 'sentry' service." at /www/espocrm/application/Espo/Core/Container.php line 73 {"exception":"[object] (Espo\\Core\\Exceptions\\Error(code: 500): Could not load 'sentry' service. at /www/espocrm/application/Espo/Core/Container.php:73)"} []

**Problem Description:**
- When we are preloading the Class `SentryLoader` we are getting error `Return value of Espo\Core\Container::getLoader() must implement interface Espo\Core\Loaders\Loader or be null`

File | Line | Code
---- | ---- | ----
`application/Espo/Core/Container.php` | `216` | `private function getLoader(string $name) : ?Loader`

If we implement the `Espo\Core\Loaders\Loader` class under `SentryLoader` class then we will get `Uncaught Exception Espo\Core\Exceptions\Error: "Could not load 'sentry' service."`

File | Line | Code
---- | ---- | ----
`application/Espo/Core/Application.php` | `164`| `$this->container->get($name);`
`application/Espo/Core/Container.php` | `90` | `public function get(string $name) : object `

**Comment by yurikuzn** [comment]
I tested and it worked fine. Please investigate your code. It's not enough information for me to understand. I believe something is wrong with your classes.

**Comment by Ananyakokala** [comment]
I am not clear with do the class `Espo\Modules\Common\Core\Utils\SentryLoader.php.` needs to implement the Loader Class. 

If i debug the code at [Container](https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Container.php#L94/)
`$this->data->name` will have only following objects. And sentry will be `sentry: null`

`{"injectableFactory":{},"config":{},"log":{},"fileManager":{},"dataCache":{},"metadata":{},"container":{}}`

**Comment by yurikuzn** [comment]
```
class SentryLoader implements \Espo\Core\Loaders\Loader
{
}
```

**Comment by Ananyakokala** [comment]
This is my sentry Loader class.  
```
<?php

namespace Espo\Modules\Common\Core\Utils;

require_once '/www/vendor/autoload.php';

use Espo\Core\Utils\Config;
use Monolog\Formatter\JsonFormatter;
use Monolog\Handler\StreamHandler;
use Sentry\Event;
use Sentry\Monolog\Handler;
use Sentry\Severity;
use Sentry\State\HubAdapter;
use Sentry\State\Scope;

class SentryLoader implements \Espo\Core\Loaders\Loader
{
    private $config = null;

    public function __construct(Config $config)
    {
        $this->config = $config;
    }

    public function load()
    {
        $this->loadSentry();
        $this->loadFluentBitLogs();
    }

    public function getSentryDsn(): ?string
    {
        return $this->config->get('sentryDsn', null);
    }

    public function getMonologSentryLevel(string $loggerName, $default = 'INFO'): int
    {
        $logLevel = $this->config->get($loggerName, $default);
        $logLevelLowered = strtolower($logLevel);

        if (!in_array($logLevelLowered, Severity::ALLOWED_SEVERITIES)) {
            $logLevelLowered = Severity::INFO;
        }

        \Sentry\configureScope(function (Scope $scope) use ($logLevelLowered): void {
            $scope->setLevel(Severity::$logLevelLowered());
        });

        return $GLOBALS['log']::toMonologLevel($logLevel);
    }

    /**
     * Supports sentry/sdk >=2.0.
     *
     * TODO: Prevent sending INFO error type
     */
    public function loadSentry()
    {
        // get the sentry dsn from the config file
        $sentryDsn = $this->getSentryDsn();
        if (is_null($sentryDsn)) {
            return;
        }

        // set up sentry
        // dsn - which sentry project should show this error
        // before_send -  action that needs to be done before sending error to sentry
        //      Only those errors should be sent to sentry if the status is not DEBUG
        \Sentry\init([
            'dsn' => $sentryDsn,
            'before_send' => function (Event $event): ?Event {
                $errorInfo = $event->toArray();
                if (!empty($errorInfo['level']) && !in_array(strtoupper($errorInfo['level']), ['DEBUG', 'INFO'])) {
                    return $event;
                }

                return null;
            },
        ]);

        // By default, send any error whose severity is INFO or above
        // this can be changed by setting the "streamHandlerLevel" option in the config file.
        $logLevel = 'Logger::'.\strtoupper($this->config->get('logger.streamHandlerLevel', 'INFO'));
        $GLOBALS['log']->pushHandler(new Handler(HubAdapter::getInstance(), $logLevel));

        $GLOBALS['log']->pushProcessor(function ($record) {
            return $record;
        });
    }

    public function loadFluentBitLogs()
    {
        $logFile = $this->config->get('logger.streamHandlerLogFile', null);
        if ($logFile) {
            $logLevelCode = $this->getMonologSentryLevel('logger.streamHandlerLevel');

            $streamHandler = new StreamHandler($logFile, $logLevelCode);
            $streamHandler->setFormatter(new JsonFormatter());

            $GLOBALS['log']->pushHandler($streamHandler);
            $GLOBALS['log']->pushProcessor(function ($record) {
                return $record;
            });
        }
    }
```
`application/Espo/Modules/Common/Resources/metadata/app/containerServices.json`
**My Container Service:**
```
{
    "sentry": {
        "loaderClassName": "\\Espo\\Modules\\Common\\Core\\Utils\\SentryLoader",
        "dependencyList": ["config"],
        "preload": true
    }
}
```
I am getting: `Uncaught Exception Espo\Core\Exceptions\Error: "Could not load 'sentry' service." at /www/espocrm/application/Espo/Core/Container.php` at [here](https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Container.php#L90)

**Comment by yurikuzn** [comment]
Load method should return your service instance.
