### ISSUE TITLE
Bug? : Formulas: operator '==' does not always work as expected

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1888]
To compare two variables in a formula, in PHP, the '===' operator is used, which wants the same type.

I've got the following situation:

```javascript
$r_str = '08';  // from database
$r = 0  + $r_str;  // converts to numerical and result = 8

$a = 'no';
ifThen($r == 8,
  $a = 'yes';
);
```

Expected result would be: `$a == 'yes'`, but it will be `$a == 'no'`, because 8 is of type **integer** and `$a` is of type **double**.
However, numerically and semantically they are equal. 

So If you want to prevent comparison of strings with numbers, one would not use `===`, but in stead determine if the type is numerical or string, use `==` to compare and return `false` if string and number are compared.

**Comment by yurikuzn** [comment]
No. It's a big PHP fault for having non strict comparison. No one want to use it in serious projects. You need to compare same types.

**Comment by yurikuzn** [comment]
I will add it to documentation.

**Comment by hdijkema** [comment]
Okey. However, this means in formula code one would need to compare as follows: 

```javascript
$r_str = '08';  // from database
$r = 0  + $r_str;  // converts to numerical and result = 8

$a = 'no';
ifThen($r == 8.0,
  $a = 'yes';
);
```

What I did, is add conversion operators to https://github.com/hdijkema/espocrm-hookedformulas:

```javascript
toInt($a) -> converts to integer.
toDouble($a) -> converts to double.
toString($a) -> converts to string.
```

**Comment by yurikuzn** [comment]
Comparing float with int is prone to errors because floats often have a small decimal fraction. You could also use `number\format`. Or check whether float falls into interval with two comparison `>=` `<=`.

**Comment by hdijkema** [comment]
> Comparing float to int is prone to errors because floats often have a small decimal fraction. You could also use `number\format`. Or check whether float falls in range `$a - 0.0001 <= $b && $b <= $a + 0.0001`.

You're right of course. I wasn't aware that `'0 + "08"'` would convert to double. 
It wasn't a good programming practice.
