### ISSUE TITLE
ORM: Ability to disable SSL verification

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1889]
I suggest to include PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT as param in 
https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Database/Helper.php#L162
in order to disable verification of the server SSL certificate eg when using self signed certs.

The install procedure should preferably support all options as well, maybe in a hidden "advanced" section during DB setup.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/6b4d955d7cf5b0c3a1c37735ed86096ea1f85683

Added `sslVerifyDisabled` parameter.
