### ISSUE TITLE
PDF generating engine is quite bad

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#1890]
Hi Yuri, 

Appreciate your work on this project... We bought Advanced Pack and are still trying to generate nice PDF files but due to TCPDF missing crucial support for a lot of HTML stylization tags as well as CSS being completely useless we are having a lot of troubles even for some quite simple Invoice templates.

My suggestion is to try implementing DomPDF (https://github.com/dompdf/dompdf) because of the support for non-inline CSS as well as nice and fast PDF rendering. DomPDF also supports quite big PDF rendering (500+ pages).

Please, as you have now put HTML-to-PDF logic behind an interface it would be SUPER nice to have a way of changing the PDF engine from the main config.php or even generally replace the libraries so everyone can just use ready-made HTML templates with custom CSS without IS actually being visualized in the PDF.

**Comment by yurikuzn** [comment]
I'm aware that TCPDF is not sufficient for more complex pages. Though I have doubts that DOMPDF will be much better there.

The ability to define an engine in the config is already there. I'm bit busy now. If anyone develop an extension for DomPDF support we will appreciate.

I would ignore DOMPDF but would look to Headless Chrome usage. I think it won't be possible to include it into EspoCRM out-of-the-box because of the license and file size.

**Comment by kboykov** [comment]
Do you have any plans on integrating another Html-to-PDF engine in the near 6 months?

Also what are the main tl;dr instructions for implementing another solution so we can print/generate beautiful PDFs?

I think the only downside of the platform currently is the PDF generation process due to the HUGE limitations and inconsistency of the PDFs generated.

**Comment by yurikuzn** [comment]
No plans. Too much of work.

All you need is to implement two interfaces:

https://github.com/espocrm/espocrm/blob/master/application/Espo/Tools/Pdf/EntityPrinter.php
https://github.com/espocrm/espocrm/blob/master/application/Espo/Tools/Pdf/CollectionPrinter.php

The way they are implemented for TCPDF  here https://github.com/espocrm/espocrm/tree/master/application/Espo/Tools/Pdf/Tcpdf.

Metadata definition is at app > pdfEngines.

I looked into DOMPDF. Unfortunately, it has a lot of limitations, some features that we already have with TCPDF can not be implemented or require some workarounds or additional lib usage.

**Comment by kboykov** [comment]
Thank you, Yuri... Looking forward any updates regarding this matter.
