### ISSUE TITLE
Scroll is not working after initial login

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#1898]
We have a very strange bug where the user cannot scroll down AND don't even have the scrollbar visible after the initial login in the platform.

Version where the bug was reproduced - 6.0 up to 6.1
Webserver - Litespeed (last 3-4 latest versions)
PHP 7.3 and PHP 7.4

The bug is easily fixed after the user refresh the page.

The only error in the console is "Failed to load resource: the server responded with a status of 401" for the URL https://demo.espocrm.com/api/v1/App/user

After refreshing the page this error is not available anymore. There are NOT any PHP errors in the error log.

**Comment by yurikuzn** [comment]
I could not reproduce. What browser do you have?

**Comment by kboykov** [comment]
All browsers affected. Currently using latest Edge and Firefox.

**Comment by kboykov** [comment]
Any idea how to fix that or I need to change the whole webserver technology to Nginx/Apache?

**Comment by yurikuzn** [comment]
I have no idea since I could not produce. Web server has nothing to do with this I guess.
