### ISSUE TITLE
DISCUSS: side & bottom areas

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#1903]
Hi all,

I want to discuss with you if is resonable to have the bottom panels to get full width, 

In most cases we only have one or two side bar panels, but many bottom panels, 

I tried isWide, but it swipe the sidebar panels to after the bottom panels which is not good!

<img width="705" alt="Screen Shot 2021-02-01 at 11 40 22 AM" src="https://user-images.githubusercontent.com/2862528/106434925-40778480-6483-11eb-9e28-e9a9faa435d5.png">
<img width="707" alt="Screen Shot 2021-02-01 at 11 43 55 AM" src="https://user-images.githubusercontent.com/2862528/106434930-42d9de80-6483-11eb-96ba-c194ab15709a.png">

**Comment by eymen-elkum** [comment]
One more related idea is to be able to set the bottom panel width just like fields in record view, that will be very nice!

**Comment by yurikuzn** [comment]
The problem that side panels often are too heigh.

**Comment by eymen-elkum** [comment]
I think you are talking about the event entities where we have activities panels and so, I wonder if this can be as option, something different from the isWide.

**Comment by eymen-elkum** [comment]
One more different idea:
Why not to have a place where we can manage the whole panels in one place?
I mean the side, record & bottom panels, and we can give them different width just like the dashboard designer works.
That will be briliant!

**Comment by kboykov** [comment]
Eymen, that's a good idea! :)

**Comment by o-data** [comment]
I like this idea for some entity, but it doesn't work for Entity that is Base Plus (Calendar, Task, Email) which rely on side panel.

**Comment by yurikuzn** [comment]
I used to think about this problem before a lot. I'd like to have some consistency though, when entities share the same layout.
