### ISSUE TITLE
Maintenance mode makes people believe their credentials are wrong

### ISSUE THREAD

**Issue by diyoyo** [espocrm/espocrm#1905]
Hi, 
I noticed that during maintenance mode, the message that is displayed to users after login attempts is that their credentials are wrong.
I think that's misleading and will cause people to want to change instead of just informing them that a maintenance is currently taking place.
I am using 6.1.2
Cheers,

**Comment by yurikuzn** [comment]
Hi,

Seems the bug appeared in 6.0.

Fix: https://github.com/espocrm/espocrm/commit/d7b9492f15ffbca9007b7bb0899b7f2895ac8a40

**Comment by o-data** [comment]
I had a quick look at the code, it will show a "Service Unavailable"? 

From my perspective it not very clear that it is only temporary (Under Maintenance)
