### ISSUE TITLE
Attachments not copied an mass update

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#1910]
Hi,

The problem occurs only when we duplicate the parent entity, so the same image will be used in both the new duplicated one & the old one.

The attachment permission will calculated from the parent entity, and now **the same attatchment is related to 2 parent entities**.

This made some users can see it and some cannot because the 2 parent entities are in different teams (for example).

Not sure if there is an easy solution, but I may suggest to have the same logic as the phone and emails are working, some table like `entity_attachment`.

Best Regards

**Comment by yurikuzn** [comment]
Hi,

Could you provide more detail steps to reproduce.

**Comment by yurikuzn** [comment]
This code should copy an attachment when duplicating. https://github.com/espocrm/espocrm/blob/6.1.2/application/Espo/Services/Record.php#L2457

**Comment by eymen-elkum** [comment]
I think this problem is not caused by the duplicate, I'm sorry.

Caused by the mass update, just add the image field to the mass update fields and the same image will be linked to all entities.

**Comment by yurikuzn** [comment]
I see. Then we need to copy an attachment entity for each record.

**Comment by eymen-elkum** [comment]
Exactly, if you have a pressure on tasks I can make a PR regarding the fix.

**Comment by yurikuzn** [comment]
I will take a look. There will be conflicts with *master*, so may be I will fix in *master* rather in *hotfix*.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/79adfe70a426c84e4ef61627b8146922a5508f8a
