### ISSUE TITLE
Default reportSendingList (Report List) Email template not working

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#1911]
Hello, our in-built template for report list email sending is not working after updating to the latest 2-3 versions. It used to work around 6.0.8 - 6.0.7 version.

The table is not filling up with the contents of the report. EVERY single report is failing to be filled automatically in the email we want to send. (no mater how many columns)

Preview: https://prnt.sc/ynp7c9

The HTML contents of the email are as follows: https://pastebin.com/4U0Gxu0G

No errors in the LOG files. No errors in the console also.

**Comment by yurikuzn** [comment]
Please create a case in our customer portal. Reports are not in this repository.
