### ISSUE TITLE
Failed login count may be triggered when using gateway

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#1913]
In /application/Espo/Core/Utils/Auth.php in checkFailedAttemptsLimit()
the $_SERVER['REMOTE_ADDR'] is used to check failed attempts. 

This will not work when the server is behind a proxy or application gateway.

Suggested is to use $_SERVER['HTTP_X_FORWARDED_FOR'] instead 
of ['REMOTE_ADDR'] when available.

--

Related : To trace back attempts additional headers that are added 
by the gateway may be helpful, eg $_SERVER['HTTP_X_APPGW_TRACE_ID']
Maybe an array of headers to be included in the authlog may be added to the config.

**Comment by yurikuzn** [comment]
Fixed: https://github.com/espocrm/espocrm/commit/5f944554cfb4afe4870af2394da109063076ce11

**Comment by yurikuzn** [comment]
Changed: https://github.com/espocrm/espocrm/commit/1d52afb45a032c60e5ff933d17e33177a12bdeb0
