### ISSUE TITLE
passsing a change set to afterSave hooks

### ISSUE THREAD

**Issue by beppe9000** [espocrm/espocrm#1916]
It may be useful to have a way to check the actual entity changes in a afterSave hook to avoid doing time-consuming processes more than needed

**Comment by yurikuzn** [comment]
You can get them in your hook:

```php
$changedAtributeList = array_filter(
    $entity->getAttributeList(),
    function (string $attribute) use ($entity) {
        return $entity->isAttributeChanged($attribute);
    }
);

**Comment by beppe9000** [comment]
Oh thanks, so it is not cleaned up after saving?

**Comment by yurikuzn** [comment]
Hook processed here https://github.com/espocrm/espocrm/blob/master/application/Espo/ORM/Repository/RDBRepository.php#L143

Attributes reset lower https://github.com/espocrm/espocrm/blob/master/application/Espo/ORM/Repository/RDBRepository.php#L146

**Comment by beppe9000** [comment]
perfectlty thought 👍🏻
