### ISSUE TITLE
Attachment size not properly calculated

### ISSUE THREAD

**Issue by Malaiac** [espocrm/espocrm#1922]
An Entity was created into espocrm.client.com.
Entity is of "StaticFile" type, id 111111
This "StaticFile" has a PDF file attached, with an ID of 2222.
I can GET StaticFile/11111 Entity via the API, get the staticfileattchsIds from the response, then download the file with GET Attachment/file/2222

This is working and okay.

Another type of Entity is created
Entity is of "DynamicQuote" type, id 333333
From this "DynamicQuote", I can 'export as PDF' from the espocrm.client.com portal and get several types of PDF according to the templates created by the client.
Since these are generated PDF, they don't appear as dynamicattachsIds when I GET DynamicQuote/333333

They are generated at Entity creation with a WorkFlow :
`$quoteFileID= ext\pdf\generate(
'DynamicQuote',
entity\attribute('id'),
'<template id>',
string\concatenate(name,'_some name_',cpnumber,)) ;

entity\setAttribute( 'quoteFileID', $quoteFileID);`
= it creates the PDF ( $quoteFileID = 4444 ) from the DynamicQuote 3333
= I can later GET DynamicQuote/3333 and it includes the quoteFileID = 4444

If I try to GET Attachment/file/44444 I get a messy response, including some PDF header strings, but not a proper PDF file. However I try to serve it, it doesn't save as a proper file.

sample response :
`%PDF-1.7 %���� 7 0 obj << /Type /Page /Parent 1 0 R /LastModified (D:20210212111206+00'00') /Resources 2 0 R /MediaBox [0.000000 0.000000 595.276000 841.890000] /CropBox [0.000000 0.000000 595.276000 841.890000] /BleedBox [0.000000 0.000000 595.276000 841.890000] /TrimBox [0.000000 0.000000 595.276000 841.890000] /ArtBox [0.000000 0.000000 595.276000 841.890000] /Contents 8 0 R /Rotate 0 /Group << /Type /Group /S /Transparency /CS /DeviceRGB >> /PZ 1 >> endobj 8 0 obj <> stream x��\�r�8��o�7ޒT��9��8���v;{��dIv�%˶~���<��5������ � �AJ�ɖY%�l�����؇?��{���_�o��`

This is clearly visible from the client website, with a working "file serving" script :
clientwebsite.com/?action=downloadFile&id=2222 > serves the attached PDF 2222 and display as PDF . size is ok ( 363 kB )
clientwebsite.com/?action=downloadFile&id=4444 > "Error" "Error loading the PDF file" . size is wrong - too small ( 170 kB, is 275 kB when "Exported as PDF" from the espocrm portal)

I suspect the 4444 ID is of a different kind of Entity (not obvious), which itself may hold the PDF file as an attachement ?
If not, it seems that generated PDF are not downloadable ? That would seem quite counter productive

**Comment by yurikuzn** [comment]
You are getting an attachment entity fields, not file contents. See how to download via API: https://docs.espocrm.com/development/api/attachment/#downloading

**Comment by Malaiac** [comment]
Notice : I corrected my syntax in the original post, the API client is using GET Attachment/file/file_id and not GET Attachment/file_id 

If I GET Attachment/file/4444  I'm not getting an Entity but a "sort of a file" response. see sample of raw response: 
`ESPOAPIResponse Object
(
    [status_code] => 200
    [success] => 1
    [headers] => Array
        (
        )

    [data] => %PDF-1.7
%����
7 0 obj
<< /Type /Page /Parent 1 0 R /LastModified (D:20210212111206+00'00') /Resources 2 0 R /MediaBox [0.000000 0.000000 595.276000 841.890000] /CropBox [0.000000 0.000000 595.276000 841.890000] /BleedBox [0.000000 0.000000 595.276000 841.890000] /TrimBox [0.000000 0.000000 595.276000 841.890000] /ArtBox [0.000000 0.000000 595.276000 841.890000] /Contents 8 0 R /Rotate 0 /Group << /Type /Group /S /Transparency /CS /DeviceRGB >> /PZ 1 >>
endobj
8 0 obj
<> stream
x��\�r�8��o�7ޒT��9��8���v;{��dIv�%˶~���<��5�������
�AJ�ɖY%�l�����؇?��{���_�o��Wޯ�}����{�JzBr����3o�d˯7P�^O��9-�=�u�K.�>����@�{���U,C�{4/&��ֻ��r�	%yh��K%�Qg2၊T{q�P�n�y�=���K���J� ^E�0�emVMT�iSN׶;X�-+�j�
��p�y^�I�^�ϣ IQj��!%O}a#��O"�E�㐣;�9ׂ�Cr;hNW6u�Ӈ���'��u&n<��
E�A��G/�56�A$x�"J�0Hx�~{�"�R��k{��θ�6p�'GR�CF�L�
���]X
J��3o��T�o��[
֭�*�q���)8�l������1��KӬ:�:z�C�I��_4�>���qY�Xi�X3՚�ܥ�V��V�š��\x,
h$��~64DJ�#�$kN���4��|@oz��V�,y"������w��ʚ]0O[5h��zZ���S�4�1�̈T�(�iJāw��~{�<�=��;�{��o���� �H&-��f;�=��	�g{@y	����8�5ǻ�c��a����a��Z4	�B�O�tA+
�WA�R�S���`

If I tried to GET "Entity"/file/4444 , what would be the "Entity" to load ? The 4444 file is generated from the DynamicQuote 3333 . and the DynamicQuote has several templates to generate PDF from ( quote, specific conditions, etc.)

I've read the extensive documentation on downloading attachement via API several times .
It says :
> GET Attachment/file/{id}
> Where {id} is an ID of the attachment record.

So, GET Attachement/file/4444

**Comment by yurikuzn** [comment]
I have no time to look into this at the moment.

I suggest debug here https://github.com/espocrm/espocrm/blob/6.1.3/application/Espo/Core/Formula/Functions/ExtGroup/PdfGroup/GenerateType.php#L104. The code seems is the same.

**Comment by yurikuzn** [comment]
Could you try to change `mb_strlen` to `strlen` here https://github.com/espocrm/espocrm/blob/6.1.3/application/Espo/Repositories/Attachment.php#L78 Maybe it will fix the problem. Please let me know if it helped.

**Comment by Malaiac** [comment]
It's a cloud hosted installation. I'm not sure there is way to edit files

**Comment by Malaiac** [comment]
I contacted the developer in charge of setting up the ESPOCRM instance.

You were right, it was a problem of string length calculated, stored at the document creation

Those two modification solved the bug :

`public function beforeSave(Entity $entity, array $options = [])
    {
        parent::beforeSave($entity, $options);

        $storage = $entity->get('storage');
        if (!$storage) {
            $entity->set('storage', $this->config->get('defaultFileStorage', null));
        }

        if ($entity->isNew()) {
            if (!$entity->has('size') && $entity->has('contents')) {
                //$entity->set('size', mb_strlen($entity->get('contents')));
                $entity->set('size', strlen($entity->get('contents')));
            }
        }
    }
`

`
application/Espo/Repositories/Controllers/Attachment.php

public function getActionFile($params, $data, $request, $response)
    {
        $id = $params['id'] ?? null;

        if (!$id) throw new BadRequest();

        $fileData = $this->getRecordService()->getFileData($id);

        $response->setHeader('Content-Type', $fileData->type);
        $response->setHeader('Content-Disposition', 'Content-Disposition: attachment; filename="'.$fileData->name.'"');
        if ($fileData->size) {
            //$response->setHeader('Content-Length', $fileData->size);
            $response->setHeader('Content-Length', strlen($fileData->contents));
        }

        return $fileData->contents;
    }`

Is there hope for those modifications to be included in the next update, so as to avoid code overwrite ?

**Comment by yurikuzn** [comment]
I'm not sure about the second. Is it necessary?

The first is already applied: https://github.com/espocrm/espocrm/commit/71c72136f6aace4f71d809f01ac21d99cddec72a

**Comment by yurikuzn** [comment]
Additional fix: https://github.com/espocrm/espocrm/commit/00109768034d92311593a93efcde94b9c2a98385
