### ISSUE TITLE
model.has() return true if value = null

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#1926]
https://github.com/espocrm/espocrm/blob/494382f5cbed9f92f3c126055a8cfa7f46aad3c9/client/src/model.js#L79

I suggest to be: 
`return (typeof value !== 'undefined' && value !== null);` or `return !!value;`

**Comment by yurikuzn** [comment]
1. No. It's not good idea. null is a valid value.
2. Even if it was reasonable it would be a breaking change that would cause a lot of issues with existing code.

**Comment by eymen-elkum** [comment]
Yes, you are right, better to not make this change

**Comment by yurikuzn** [comment]
Method `has` checks whether a value is set (e.g. loaded from backend). 

* `has('firstName')` === false` -- an attribute is not yet loaded
* `has('firstName') === true && get('firstName') === null` , -- an attribute loaded and set as NULL.

**Comment by eymen-elkum** [comment]
Many thanks for the clarification ... helpful
