### ISSUE TITLE
default fontFace and fontSize for Pdf

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#1927]
Previously Pdf.php could be declared in custom namespace Espo\Custom\Services and default value for fontFace and fontSize could be set there. After latest updates it is broken.
Now fontFace and fontSize default values are hardcoded in Espo\Tools\Pdf\Tcpdf:
```
class EntityProcessor
{   
protected $fontFace = 'freesans';
protected $fontSize = 12;
```
For example I have many templates that relied on default fontSize other than 12;
Please move back ability to set default fontSize (and fontFace) through custom namespace. Or more user friendly method is to make global options for pdf fontSize and fontFace default values.

**Comment by yurikuzn** [comment]
> through custom namespace`

Unfortunately, this practice that you can extend just putting the file in *custom* will be phased out. This approach is OK for tiny applications but Espo has grown big since.

**Comment by rutkas** [comment]
But how to make customizations ? Patch core code ? each update will broke the patches...

**Comment by yurikuzn** [comment]
In a lot of cases dependency binding help. Unfortunately, need to make small refactoring of TCPDF implementation so that it would be possible to define custom EntityProcessor implementation. Will do it later.

For you, the option is to change these 2 class names to your custom ones: https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/metadata/app/pdfEngines.json#L3

**Comment by rutkas** [comment]
By the way... Customization with "custom" folder that allow to change and tune almost everything is one of the main espo-crm benefits. It allows to scale espo to any task/buisness. Without this powerful function espo will become just a generic crm software. Please think twice about removing it....

**Comment by yurikuzn** [comment]
And we can't have config param for font face, because in the future we will have additional Engines with different font faces.

**Comment by yurikuzn** [comment]
Actually, it's possible to scale even better now, w/o custom folder.

**Comment by yurikuzn** [comment]
We can't have all code in `Services`. It violates single responsibility principle. We need more structured hierarchy of classes.

**Comment by rutkas** [comment]
> For you, the option is to change these 2 class names to your custom ones: https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/metadata/app/pdfEngines.json#L3

Thank you for the solution, so I should change TcpdfEntityPrinter class to my custom redefined class and there 
change call of 
`$this->entityProcessor = new EntityProcessor($config, $htmlizerFactory);`
to  my custom redefined EntityProcessor with my favorite fontSize
correct ?

**Comment by yurikuzn** [comment]
Correct.

**Comment by rutkas** [comment]
> Actually, it's possible to scale even better now, w/o custom folder.

Do you mean method that you proposed me for Pdf class ? every class name / path can be redefined in metadata json's ?

**Comment by yurikuzn** [comment]
Yes. Plus dependency binding. Please don't tell me that single class in `Custom\Services` is better. It's not.

**Comment by yurikuzn** [comment]
> every class name

Not every. If we have some interface, we can have multiple implementations of that. We can specify in metadata a specific implementation. Or use binding if we want to substitute some dependency with our custom implementation.

**Comment by rutkas** [comment]
> Yes. Plus dependency binding. Please don't tell me that single class in `Custom\Services` is better. It's not.

New method is really better, I did not notic that implementation. Similar to view(js) clientDefs customizations that can be done through json.

Can I use className everywhere, for example in any entityDefs json for any object ? I don't see they are set to default values there.

And what is dependency binding, how it is used ?

**Comment by yurikuzn** [comment]
For every classes -- no. Only for specific. Services, Controllers, Entities, Acl are still resolved by path for now. In future we will add the ability to define in metadata. The problem that as we grow we have much more classes, and we can't have a specific path reserved for every class type. It's unfeasible. So we switch more to metadata-driven approach.

Dependency binding: https://docs.espocrm.com/development/di/#binding

**Comment by yurikuzn** [comment]
After this refactoring https://github.com/espocrm/espocrm/commit/d1b27dfd9d4e19a96d48d9cb0292d4829ab587fe it will be possible to specify a custom implementation of EntityProcessor class with binding:

```php
<?php
namespace Espo\Modules\MyModule;

use Espo\Core\Binding\Binder;

use Espo\Tools\Pdf\Tcpdf\{
     TcpdfEntityPrinter,
     EntityProcessor,
};

use Espo\MyModule\Tools\Pdf\Tcpdf\CustomEntityProcessor;

class Binding
{
    public function process(Binder $binder)
    {
        $binder
            ->for(TcpdfEntityPrinter::class)
            ->bindImplementation(EntityProcessor::class, CustomEntityProcessor::class);
     }
}
```

Means: when `TcpdfEntityPrinter` asks for `EntityProcessor`, give `CustomEntityProcessor`.
