### ISSUE TITLE
Client IP address not always detected

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#1928]
Espocrm depends on `REMOTE_ADDR ` to fetch the client user, but in some cases this key will hold the forwarded IP, so it will be the same for all users.

In my case this key was holding the real IP adress `HTTP_X_REAL_IP ` or `HTTP_X_FORWARDED_FOR `.

I wonder if worth that we use the fuction [from this answer](https://stackoverflow.com/a/2031935/2580499):

    foreach (array('HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'REMOTE_ADDR') as $key){
        if (array_key_exists($key, $_SERVER) === true){
            foreach (explode(',', $_SERVER[$key]) as $ip){
                $ip = trim($ip); // just to be safe

                if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false){
                    return $ip;
                }
            }
        }
    }

**Comment by gramakri** [comment]
Would be great to have this fixed. The approach I have seen in many apps is to have a trust_proxy variable which is the reverse proxy IP(s). When REMOTE_ADDR matches trust_proxy, the X-Forward-For header is trusted and used as the client IP.

A workaround is to use something like https://github.com/gnif/mod_rpaf

**Comment by yurikuzn** [comment]
Fixed: https://github.com/espocrm/espocrm/commit/5f944554cfb4afe4870af2394da109063076ce11

**Comment by arkadywtf** [comment]
Is it possible to define `IP_PARAM_LIST` in config.php or to add an option that makes Espo always use `REMOTE_ADDR` to obtain an IP address? `X-Forwarded-For` can be spoofed, so I would rather depend on my server configuration when behind a reverse proxy to get the real IP address of the client.

**Comment by yurikuzn** [comment]
Changed to use a config param: https://github.com/espocrm/espocrm/commit/1d52afb45a032c60e5ff933d17e33177a12bdeb0. I didn't like the previous solution anyway.
