### ISSUE TITLE
FR: running formula after entity removed

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#1931]
Hi,

What do you think about making it possible to run formula when an entity removed, this will help when we making calculating.

**Comment by yurikuzn** [comment]
Workflow can handle this (with a signal trigger). Existing script is after-save only. It would be wrong to make it to run after-delete. It would be a breaking change.

**Comment by eymen-elkum** [comment]
I may not explained my idea well, I meant to have 2 formula inputs, one for the before save as the current and one for the before delete

Or to add option to the current formula like "`Also run this formula before delete`"
