### ISSUE TITLE
File storage interface changes

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1932]
New interface:

```php
<?php

namespace Espo\Core\FileStorage;

use Psr\Http\Message\StreamInterface;

/**
 * File storing and fetching.
 */
interface Storage
{
    /**
     * Get file contents as a stream.
     */
    public function getStream(Attachment $attachment) : StreamInterface;

    /**
     * Store file contents.
     */
    public function putStream(Attachment $attachment, StreamInterface $stream) : void;

    /**
     * Whether a file exists.
     */
    public function exists(Attachment $attachment) : bool;

    /**
     * Delete a file.
     */
    public function unlink(Attachment $attachment) : void;

    /**
     * Get a file size.
     */
    public function getSize(Attachment $attachment) : int;
}
```

**Comment by taktak-dev** [comment]
Hi,
We have implemented a custom storage to replace EspoUploadDir class. 

Will the changes in this issue mean the we will need to update the code for custom Storage or the functions putContents, getContents, etc will still be compatible?

Thanks in advance

**Comment by yurikuzn** [comment]
Hi,

Yes. You will need to update. It will be quite simple to do.

Release date will be not very soon.

**Comment by yurikuzn** [comment]
What custom storage do you use BTW?

**Comment by taktak-dev** [comment]
> Hi,
> 
> Yes. You will need to update. It will be quite simple to do.
> 
> Release date will be not very soon.

Thank you for the reply. 



> What custom storage do you use BTW?

We interfaced with AWS PHP SDK for S3 Storage.

**Comment by yurikuzn** [comment]
Maybe I will add Amazon S3 implementation in the next release.

**Comment by yurikuzn** [comment]
Btw how you implemented downloading through EntryPoint. At this moment Download entry point relies on a file path. Do create a temp file locally?

**Comment by taktak-dev** [comment]
> Btw how you implemented downloading through EntryPoint. At this moment Download entry point relies on a file path. Do you create a temp file locally?

Yes we create a temporary copy locally.

**Comment by yurikuzn** [comment]
Now with a stream it won't be needed.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/ceb3b562e6032f6f8f4169ed971e87ed7b1e2c1b

**Comment by yurikuzn** [comment]
Added S3 storage plus some changes https://github.com/espocrm/espocrm/commit/b729ec1a855a402d0fcc4f2e72f6bacd9e749578
