### ISSUE TITLE
filtered Kanban shows empty columns 

### ISSUE THREAD

**Issue by diyoyo** [espocrm/espocrm#1933]
Hi, 
I don't know whether it is by design or not, but when filtering the Kanban to exclude some columns, the records are well filtered, but the columns are still shown.
Imho, empty columns are ok when there is no filter applied, but should disappear if a column filter is applied.

Thanks.
I am using 6.1.4

**Comment by yurikuzn** [comment]
Hi,

It was not intended to hide columns dynamically.
