### ISSUE TITLE
On detail selecting related entity via arrow from table is very slow

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#1939]
In attached screen there is button for selecting "Account" for other enitty.
![download - 2021-03-06T131531 144](https://user-images.githubusercontent.com/6084451/110206460-12b89d80-7e7e-11eb-8f98-f04a2afb2b08.png)

By default Espo sends this type of request:

/api/v1/Account?maxSize=30&offset=0&orderBy=createdAt&order=desc

Which in case of for example 5 relationships between Account, Attachements, Assigned users etc. is creating SQL query which is examining 123 000 000 rows in our case. Those data are unnecessary for simple two columns listing (which is defined in Entity settings for small listing) and in this case there is only Name and Country (but in query there is also attachements and other data selected which is not needed at all)

In contrary classic default view table is sending this type of request:

/api/v1/Account?select=name%2CbillingAddressCountry%2Cpartner%2Ccategory%2CemailAddressIsOptedOut%2CemailAddress%2CemailAddressData%2CphoneNumberIsOptedOut%2CphoneNumber%2CphoneNumberData&maxSize=50&offset=0&orderBy=createdAt&order=desc

And this is fast and has reasonable data selected.

**Comment by yurikuzn** [comment]
> By default Espo sends this type of request:
> /api/v1/Account?maxSize=30&offset=0&orderBy=createdAt&order=desc

It's not true.

**Comment by yurikuzn** [comment]
Tested on two different instances.

**Comment by david-strejc** [comment]
You are right - on clean instance there is different API request which is right. Sorry for missleading.
