### ISSUE TITLE
PDO SSL settings not consistently used (in v 6.0.8)

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#1941]
`\Espo\Core\Utils\Database\Helper` fetches the SSL settings from the config.

But before logging in ( eg to fetch `/api/v1/Settings` ) these parameters are not used creating  the PDO connection.

Instead it creates the connection directly using `/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection`

Workaround is hardcode the `$options` in `/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php`

Any PDOConnection should have the right $options passed.

**Comment by yurikuzn** [comment]
Would be great if you provide steps to reproduce.

**Comment by analystcmyk** [comment]
Ok, digging a bit further : DBAL/Driver/PDOConnection like this works.
```
public function __construct($dsn, $user = null, $password = null, array $options = null)
    {
        $options = array(
                PDO::MYSQL_ATTR_SSL_CA => '',
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
        );

```

Removing the `$options`, or `PDO::MYSQL_ATTR_SSL_CA => '',` and 
fetching `/api/v1/settings` while logged out will lead to :

`
[2021-03-10 14:31:41] Espo.ERROR: (9002) SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry.; GET /Settings; line: 55, file: /var/www/crm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php [] []
`
Similar behavior occurs when setting VERIFY to `true`

Furthermore a http 500 server error is triggered.

Platform : 
MySQL 8.0.15 on Azure, with TLS enforced v1.2.

$dsn and $user params get passed correctly :

**Comment by analystcmyk** [comment]
> 
> 
> Would be great if you provided steps to reproduce.
> 
> `Espo\Core\Utils\Database\Helper` is used only on rebuild (if I'm not mistaken). JFYI. It's not supposed to be used on ` /Settings` request.

What is the reason SSL settings would not be applied to any PDOConnection?

**Comment by yurikuzn** [comment]
> What is the reason SSL settings would not be applied to any PDOConnection?

I have nothing to say. If you described the problem more clear. How to reproduce, with your results of debugging.

**Comment by analystcmyk** [comment]
`/api/v1/Settings`  does indeed NOT invoke the helper. Instead it relies on `DBAL/Driver/PDOConnection `

Result from debugging shows that in DBAL/Driver/PDOConnection 
`public function __construct($dsn, $user = null, $password = null, array $options = null)`  the $dsn, $user and $password are passed correctly, but the $options are empty. 

Hence the SSL connection fails.

Hope this clarifies.

**Comment by yurikuzn** [comment]
Where exactly in the code `options` are empty.

**Comment by yurikuzn** [comment]
It would be helpful you you looked where `__construct` was invoked.

**Comment by analystcmyk** [comment]
ok will try to find out and get back, thank you for the hint.

**Comment by analystcmyk** [comment]
### Steps to reproduce


Fresh install , MySQL server with TLS 1.2 enabled.  Fetch : /api/v1/Settings
config.php 

### Backtrace



`#0  Doctrine\DBAL\Driver\PDOConnection->__construct(mysql:host=mygist;port=;dbname=espo;charset=utf8mb4;, myusername, mypassword, Array ()) called at [/var/www/crm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:37]` 

```
#1  Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array ([host] => myhost,[port] => ,[charset] => utf8mb4,[dbname] => espo,[user] => myuser,[password] => jmypassword,[sslCA] => baltimorecombined.pem,[sslCAPath] => /var/www/az,[driverClass] => \Espo\Core\Utils\Database\DBAL\Driver\PDOMySql\Driver), myuser, mypassword, Array ()) called at [/var/www/crm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:356] 

#2  Doctrine\DBAL\Connection->connect() called at [/var/www/crm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:680] 

#3  Doctrine\DBAL\Connection->executeQuery(SHOW TABLE STATUS WHERE Engine = 'MyISAM' AND Name = 'action_history_record', Array ()) called at [/var/www/crm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:419] 

#4  Doctrine\DBAL\Connection->fetchColumn(SHOW TABLE STATUS WHERE Engine = 'MyISAM' AND Name = 'action_history_record') called at [/var/www/crm/application/Espo/Core/Utils/Database/Helper.php:240] 

#5  Espo\Core\Utils\Database\Helper->getTableEngine(action_history_record) called at [/var/www/crm/application/Espo/Core/Utils/Database/Helper.php:258] 
```





Dumping the `Doctrine\DBAL\Driver\PDOMySql\Driver->connect() ` with 
```
$traceoptions = print_r($params,true);
$GLOBALS['log']->warning("\n\rconnect() params:  $traceoptions");
```

results in an empty array $driverOptions

### Issue: 

`Doctrine\DBAL\Driver\PDOMySql\Driver->connect()` expects `['driverOptions']` to have the CA definition.

### Workaround : 

add the CA in ['database'] section of `config.php` as well : 

```
 'driverOptions' => [
         PDO::MYSQL_ATTR_SSL_CA => '/var/www/az/baltimorecombined.pem',
         PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false
        ],
    'sslCA' => '/var/www/az/baltimorecombined.pem'

```

### Result 

```[2021-03-16 13:17:06] Espo.WARNING:   connect() params:  
Array (     
[host] => myhost
[port] =>      
[charset] => utf8mb4     
[dbname] => espo     
[user] => myuser
[password] => mypass     
[driverOptions] => Array         (             
     [1009] => /var/www/az/baltimorecombined.pem             
     [1014] =>          )      
[sslCA] => /var/www/az/baltimorecombined.pem     
[driverClass] => \Espo\Core\Utils\Database\DBAL\Driver\PDOMySql\Driver 
)  [] []

Thanks to Jose.

**Comment by yurikuzn** [comment]
What EspoCRM version do you use?

**Comment by analystcmyk** [comment]
6.0.8

**Comment by yurikuzn** [comment]
I see. We upgraded DBAL since. So this issue might be not actual. Please always indicate version when reporting the bug, It would have saved me a lot it time if I knew you use v6.0.
