### ISSUE TITLE
Case number format in Email Template

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#1950]
I am struggling to get our Case number in an email using Email Template (both in subject and body).
Actual case number is 10000012, i've tried the following options:

{{numberFormat Case.number decimals=0 thousandsSeparator=''}} does not work
{{numberFormat Case.number_RAW decimals=0 thousandsSeparator=''}} does not work
{{Case.number_RAW}} does not work
{Case.number_RAW} does not work
{{Case.number}} results in {10.000.012}

[https://forum.espocrm.com/forum/general/58491-case-number](https://forum.espocrm.com/forum/general/58491-case-number)

What is the correct way to just output it as 10000012 in an Email Template?

**Comment by yurikuzn** [comment]
When you editing email templates there's a placeholders you can insert into the body. Use them to insert a proper placeholder. All the placeholders you tried are incorrect.

**Comment by yurikuzn** [comment]
For formatting you can use `{{numberForma number_RAW decimals=0 thousandsSeparator=''}}`

**Comment by neknarf** [comment]
> When you editing email templates there's a placeholders you can insert into the body. Use them to insert a proper placeholder. All the placeholders you tried are incorrect. Should be `{Case.number}`.

I am using Email templates and I've used the placeholder {Case.number} which results in 10.000.012 instead of 10000012

**Comment by yurikuzn** [comment]
`{{numberFormat number_RAW decimals=0 thousandsSeparator=''}}` should help. But it's an experimental feature.

**Comment by yurikuzn** [comment]
I tested and it worked fine.

**Comment by neknarf** [comment]
Indeed I can see it is working when composing an email via the Case and selecting the Email Template.
I use Workflow or Flowchart to send email using Email Template. That doesn't work.

**Comment by neknarf** [comment]
> Set parentId and parentType to case ID and 'Case'.

But Subject and Priority are working fine so I don't think it is related to setting parent. Even Case number is sent, but not in the correct format.

**Comment by yurikuzn** [comment]
I added this fix making autoincrement being rendered w/o formatting in email templates. Only for v6.2.0. You can try to apply this fix manually.

https://github.com/espocrm/espocrm/commit/3c9c3cb70978d9bb93aacc3130b3f231611b4ca6
