### ISSUE TITLE
Additional columns in entities in v6.1+

### ISSUE THREAD

**Issue by WilixLead** [espocrm/espocrm#1960]
After updating to 6+ I see some changes in ORM. Looks like just removed "getLinkMultipleCollection" without providing alternatives and this change not documented.

Most of my fields with additionalColumns in EntityDef now working with bugs. Related to UI, field still show inputs for columns, but always empty. If I put something to input and save - it send's to API normally like before, but after refresh API return something like:

```js
{
  id: ....
  name: ....
  usersColumns: {
    5f7311e....270def: {
       projectRole: null <---- always null in all my entities
    }
  }
}
```

This is a bug or new changes? What I can do to restore my functionality regarding to new API

PS: I use updating via console (php command.php upgrade..)

**Comment by yurikuzn** [comment]
You need to define `columnAttributeMap` https://github.com/espocrm/espocrm/blob/6.1.5/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Contact.json#L582

Then when to fetch a relationship collection all columns will be selected.
```
$collection = $entityManager
     ->getRepository('EntityType')
     ->getRepository($entity, 'relationName')
     ->find();

foreach ($collection as $itemEntity) {
      $columnValue = $entityItem->get('columnAttribute');
}
```

**Comment by WilixLead** [comment]
@yurikuzn Thank you! I already find this way ins sources but still not working. Looks like now I should add virtual field to entity for map column to this field. But if I have a project with linked users and every user should have his additional field, where I should define this virtual field for map?

**Comment by yurikuzn** [comment]
I think it always required having virtual fields.

**Comment by WilixLead** [comment]
But where this field should be? Entity in my example before (`Cred` Entity) have relation to users through `credentialUsers` table with additional column `externalId`. 
So, where I should implement virtual field `externalId` ? 
I don't have addtitional entity for credentialUsers and if I implement it in `Cred` entity - it looks wrong. Implement field in User entity?

**Comment by yurikuzn** [comment]
You need to have 'notStorable' field in the related entity type. In your case it's User. In that not storable field a column values will be set. It always has been workng this way I believe.

```
foreach ($collection as $itemEntity) {
      $columnValue = $entityItem->get('yourNotStorableField');
}
```

**Comment by yurikuzn** [comment]
Yes. In User entity. We have already few for the same purpose: https://github.com/espocrm/espocrm/blob/6.1.5/application/Espo/Resources/metadata/entityDefs/User.json#L199

**Comment by WilixLead** [comment]
Hm. I check my User.json and it already have `externalId` field with `"notStorable": true` - still don't work. Saving is okay, but loading return nulls for every record. I check database - all values in their places

**Comment by yurikuzn** [comment]
Cleared cache?

**Comment by WilixLead** [comment]
Ok, I figured out it. Just need move `columnAttributeMap` to Users.json links relation not in Creds.json. It now looks bit complicated for implement additional fields :)

**Comment by WilixLead** [comment]
@yurikuzn Thank you very much! 
Additional question: have any way to request list of entities not only with related Ids and Names but with Columns?

**Comment by yurikuzn** [comment]
Before it was needed to specify a map when writing code. Not it's automatically is taken from the metadata. It was needed to specify the same map in link-multiple field before. So it actually became less work than before.

**Comment by yurikuzn** [comment]
Yes. Check how contact's roles are fetched in opportunity.

**Comment by WilixLead** [comment]
Looks like it have a bug or problems with updating. But in opportunity I see additionalColumn only when open Opportunity entity (it loads contacts roles) then return back to list and only new I see contact role from opened entity.
Now I try to compare entity configs with git versions. So, looks like `where` statement doing magic for lists, right? May be has any docs about `where` syntax in entityDefs?

**Comment by yurikuzn** [comment]
It's not loaded on list view because it would impact performance significantly. Link-multiple fields are loaded here https://github.com/espocrm/espocrm/blob/6.1.5/application/Espo/Services/Record.php#L635. For lists they are not loaded here: https://github.com/espocrm/espocrm/blob/6.1.5/application/Espo/Services/Record.php#L645.

I recommend debugging starting from Record class. Method find.

I don't think there's any bug. If there's please report with details.
