### ISSUE TITLE
Cases: Set the status to "New" when replying to an email

### ISSUE THREAD

**Issue by 123710** [espocrm/espocrm#1961]
how to Set the status to "New" when replying to an email?
i dont have workflow

**Comment by yurikuzn** [comment]
Please create a topic on our forum.

**Comment by 123710** [comment]
hallo yuri,
thanks for your response.
i've replied on your commit and mentioned you on espo forum
https://forum.espocrm.com/forum/general/45273-cases-set-the-status-to-new-when-replying-to-an-email
