### ISSUE TITLE
Display as label competing with Link

### ISSUE THREAD

**Issue by diyoyo** [espocrm/espocrm#1962]
Hi, 
it seems like when showing a field as Link in Kanban (maybe even in other modes), it overrules the fact that the parameter should be displayed as label. 
Would it be possible to create a clickable label instead? with the colored background and everything?
Thanks

**Comment by mitchplze** [comment]
I believe this is related to an issue I'm having... 

In: **Admin > Entity Manager > Case > Layouts > Kanban**

Even after unselecting the "link" checkbox for selected fields, the data is still "linked" in Kanban view.

<img width="310" alt="Screen Shot 2022-02-09 at 16 55 46" src="https://user-images.githubusercontent.com/25162574/153316384-347716be-d6ae-43f3-8fc0-348783207f1c.png">


<img width="174" alt="Screen Shot 2022-02-09 at 16 55 53" src="https://user-images.githubusercontent.com/25162574/153316400-cec3c0e9-f032-4336-a547-d069516f83e6.png">


![Screen Shot 2022-02-09 at 16 57 54](https://user-images.githubusercontent.com/25162574/153316417-bf0b8a54-9709-4759-9fe3-de7c374d8e35.png)

**Comment by yurikuzn** [comment]
No, it's not related. It's expected behaviour.

**Comment by mitchplze** [comment]
Ok. Just curious what that option means then?

**Comment by yurikuzn** [comment]
https://docs.espocrm.com/administration/layout-manager/#link

**Comment by mitchplze** [comment]
So by that definition though, would unchecking the Link box, not be expected to make it static text? Just confused how that works — sorry

**Comment by yurikuzn** [comment]
[Done for enum field.](https://github.com/espocrm/espocrm/commit/442284fee2b71472197950e02e418a3322985f3a)
