### ISSUE TITLE
Mass update and Many-to-Many relationships

### ISSUE THREAD

**Issue by diyoyo** [espocrm/espocrm#1964]
Hi, 
I realized that the only option when doing a mass update in the case of "many-to-many" relationship is to overwrite the previous relationships of the different records selected.
What would be nice, would be to have the option to "Mass Add", "Mass Remove" in addition to the "Mass Update" option. That way, records can have a different set of relations before updating, and these relations will not be lost after the update. Only the new one will be added.
Thanks.
Cheers,

**Comment by yurikuzn** [comment]
It's already possible to have mass-relate. Though it's disabled for all relationship panels by default. It's enabled only for target lists.

https://github.com/espocrm/espocrm/blob/6.1.6/application/Espo/Modules/Crm/Resources/metadata/clientDefs/TargetList.json#L32

**Comment by yurikuzn** [comment]
Has been already resolved
