### ISSUE TITLE
Sorting in list view is not applied to Kanban

### ISSUE THREAD

**Issue by diyoyo** [espocrm/espocrm#1971]
Hi, 
it seems like the choice of the sorting column (including direction) is not used in the Kanban view.
I guess the "Default Order (field)" has priority, but I am not even that sure about it.
It would be nice to be able to use the list view to define the sorting order and to apply it in the Kanban view.
Thanks.
Cheers,

**Comment by yurikuzn** [comment]
Hi,

Sorting is applied by default (as far as I know) but user can re-order items.

**Comment by yurikuzn** [comment]
You can disable custom order via metadata: https://github.com/espocrm/espocrm/blob/6.1.6/application/Espo/Services/Record.php#L1360

**Comment by diyoyo** [comment]
Ok, thanks, I'll try at least that, but as said, it would be nice if the user could change this order just by clicking on the sorting column in list mode.

**Comment by yurikuzn** [comment]
I don't think it's good to change order from a different mode.

**Comment by diyoyo** [comment]
Ok, in fact, the little scope trick you mentioned above does the trick: if I set kanbanOrderDisabled to true, then the default order is applied. And even better, I can change the order using the list view, and if I refresh the Kanban view, it follows the list view order, which is exactly what I needed. The only drawback is that the kanban view is reset back to the default order whenever the page is reloaded, but I can live with it.
Thanks.
