### ISSUE TITLE
Provider-agnostic OAuth2 documentation

### ISSUE THREAD

**Issue by torgeirl** [espocrm/espocrm#1972]
There are a few references to OAuth/OAuth2 in the source code, including `oauth-callback.php`. OAuth2 is however not covered in the documentation under `Administration > Authentication` (it just covers LDAP/AD). Instead it's covered as part of integration with Google, under `Extensions > Google Integration`.

There are however a lot of other OAuth2 providers out there. It would be great if provider-agnostic OAuth2 documentation also could be provided alongside the current LDAP/AD section.

**Comment by yurikuzn** [comment]
EspoCRM does not have OAuth2 authentication.

The existing code is utils for oauth client. And it's not fully implemented.

**Comment by torgeirl** [comment]
> EspoCRM does not have OAuth2 authentication.
> 
> The existing code is utils for oauth client. And it's not fully implemented.

That's too bad. Are there plans to (more fully) implement the OAuth(2) client in the future?

**Comment by yurikuzn** [comment]
I don't think it's TOO bad. There a lot of examples how to implement Oauth client on the internet, you can utilize libraries. I don't think we need to add it to EspoCRM. It would be a maintenance burden for me.

**Comment by torgeirl** [comment]
> I don't think it's TOO bad. There a lot of examples how to implement Oauth client on the internet, you can utilize libraries. I don't think we need to add it to EspoCRM. It would be a maintenance burden for me.

Too bad, as in I would have preferred it to be different. I'll see if we're able to implement it ourselves. Thanks for the feedback.

**Comment by yurikuzn** [comment]
Too bad is when I have to read people complaining here. Man, I work hard on Espo every day and I hate to read such posts. It's not simple to have provider agnostic OAuth impementation. They tend to differ. EspoCRM it not a tool that have implementation of everything.
