### ISSUE TITLE
Upgrade to 6.1.5 (and possibly earlier versions) break compatibility with formatPersonName Helper loading

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1979]
For an extension of Entity Person, I extended EspoCRM with IPerson a custom implementation of  [EntityManagerHelper.php]([url](https://github.com/hdijkema/espocrm-iperson/tree/master/custom/Espo/Custom/Core/Loaders)). This works with EspoCRM 5.9.*.

However, we don't want to get to far behind with our EspoCRM application version, so I'm trying to upgrade EspoCRM to the latest version (6.1.5). 

However, now the EntityManagerHelper.php isn't loaded anymore. I see that the EntityManager.php injects a 'Helper::class' class now, but I don't know what I should to to make sure that this 'Helper:class' will be the right custom class for IPerson. 

What should be done to get it working again?

**Comment by yurikuzn** [comment]
I'm not sure. I don't keep all details in my head. It is possible to use binding to bind a custom implementation since v6.1.

We will have the ability to inject additional dependencies into custom entities in v6.2.

**Comment by hdijkema** [comment]
> I'm not sure. I don't keep all details in my head. It is possible to use binding to bind a custom implementation since v6.1. You can bind a custom helper to substitute the default one.

Thank you for your answer, however, I'm still lost here. What do I have to do to bind a custom implementation and where do I have to code it, so that it gets done?

**Comment by yurikuzn** [comment]
https://docs.espocrm.com/development/di/#binding
It won't work in v6.1. Because helper is created explicitly. So there's no solution.

But it will work in v6.2 since we inject the helper with DI.

```
$binder->bindImplementation(
    'Espo\\Core\\ORM\\Helper',
    'Espo\\Custom\\YourCustomHelper'
);
```

**Comment by hdijkema** [comment]
Okay, I think I understand it now. Thank you. So I'll probably best wait for version 6.2 to come and then upgrade my 5.9.3 version...Or can I override Espo/Core/ORM/EntityManagerFactory.php with a custom one? Espo/Custom/Core/ORM/EntityManagerFactory.php?

**Comment by yurikuzn** [comment]
Yes, you can. Since it's resolved with DI here: https://github.com/espocrm/espocrm/blob/6.1.6/application/Espo/Core/Loaders/EntityManager.php#L41

**Comment by hdijkema** [comment]
DI - Dependency Injection

**Comment by hdijkema** [comment]
This is a very ugly solution, but it solves the problem with a minimum of code. 

```php
namespace Espo\Custom\Core\Loaders;

use \Espo\Core\{
    ORM\EntityManagerFactory,
    ORM\EntityManager as EntityManagerService,
};


use \Espo\Modules\IPerson\Helpers\IPersonHelper;

class EntityManager extends \Espo\Core\Loaders\EntityManager
{
    public function load() : EntityManagerService
    {
        $obj = parent::load();

        $cfgprop = new \ReflectionProperty('\\Espo\\Core\\ORM\\EntityManagerFactory', 'config');
        $cfgprop->setAccessible(true);
        $config = $cfgprop->getValue($this->entityManagerFactory);

        $property = new \ReflectionProperty('\\Espo\\Core\\ORM\\EntityManager', 'helper');
        $property->setAccessible(true);

        $helper = new IPersonHelper($config);
        $property->setValue($obj, $helper);

        return $obj;
    }
}
```
