### ISSUE TITLE
Some email attachments not being imported

### ISSUE THREAD

**Issue by Whrealty** [espocrm/espocrm#198]
i Have been having many reports of attachments not be in the emails received.

i have tested this and am seeing a pattern of about 3 out of 8 emails sent with attachments do not include the attachment.

i have checked the mail server with a standard email client and the emails do in-fact have a attachment in them but not in ESPO

this is becoming a major issue

**Comment by yurikuzn** [comment]
If you could provide such emails (raw content or send them to some email box we could take them from) it would be great.

**Comment by Whrealty** [comment]
i just sent you a email with headers

**Comment by Whrealty** [comment]
do you have a different email you want me to send a pdf to from one of are scanners
this is one of my testing scanners because espo fails to get attachment from it almost every time but it is on the server
