### ISSUE TITLE
Feature request : add "checkpermissions" as CLI command

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#1980]
When (after migration) file/dir ownership and permissions are not correct, strange rebuild and clear cache issues may arise. 

Eg : `WARNING: E_WARNING: chgrp(): Operation not permitted {"code":2,"message":"chgrp(): Operation not permitted","file":"/var/www/crm/application/Espo/Core/Utils/File/Permission.php","line":426} []`, but these warnings do not tell you what is wrong. 

Since all procedures to check permissions are already in `/var/www/crm/application/Espo/Core/Utils/File/Permission.php` it would be useful to be able to diagnose that.

Suggested is to have a `php command.php checkpermissions` CLI to generate the list of missing/wrong permissions , or extend the `protected function chownReal($path, $user)` debug message with info on what failed , eg : "failed : chown $path to $user"

**Comment by admin0o0** [comment]
请问如何解决的，我遇到了相同的问题！

**Comment by yurikuzn** [comment]
Added command checking whether needed folders are writable, the same as at Administration > System Requirements.
