### ISSUE TITLE
ecoding json body content failing if request content type is application/json; charset=utf-8 ( as opposed to just application/json)

### ISSUE THREAD

**Issue by axyl** [espocrm/espocrm#1982]
Axios and other libraries set the content-type header, for JSON data, by default, to include the encoding at the end.  But the ControllerManager.php (below) looks for an exact string match, so it doesn't process the incoming body as json...

Could that code be changed to check that the content type starts with application/json instead?

https://github.com/espocrm/espocrm/blob/9ce723930844189c1dab5e458be86ef884de2e09/application/Espo/Core/ControllerManager.php#L103

from:
```
if ($data && $request->getContentType() === 'application/json') {
            $data = json_decode($data);
        }
```
to: (or something like that)
`if ($data && str_starts_with($request->getContentType(), 'application/json'){`

**Comment by yurikuzn** [comment]
Thanks for reporting. The fix: https://github.com/espocrm/espocrm/commit/e9f7046a05c7d92c276c642793cd8f9c78928530
