### ISSUE TITLE
"Reply" from Email view doesn't work

### ISSUE THREAD

**Issue by virusyscorp** [espocrm/espocrm#2004]
I am set up to use Outlook as an external mail handler.

Clicking an email address that contains a mailto: link from any list works just fine. The Outlook email window pops up and I can send an email to that person.

When I access an email from within EspoCRM and click the "Reply" button, nothing happens.

The error log shows: 

[2021-05-24 01:12:02] ERROR: EmailAccount 6075ac34757d66c94 (Select Folder) [0] cannot change folder, maybe it does not exist [] []

Is this a bug or something I can fix?

**Comment by yurikuzn** [comment]
Please let me know if anyone run across the same issue.
