### ISSUE TITLE
Account field filled with Account ID instead of Account Name for Portal Users

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#2005]
When creating a new record on a Portal, the Account field is pre-populated with the Account ID instead of the Account Name.
This occurs when the Portal User has a Contact assigned to it. The ID shown is the ID of the Account attached to this Contact.

![image](https://user-images.githubusercontent.com/65923581/119482042-b2861900-bd53-11eb-968a-e16fe66bb619.png)

**Comment by yurikuzn** [comment]
Account name  is forbidden field for portal users by default. They can't see their account name.

**Comment by neknarf** [comment]
Account is allowed in the Portal Role. After saving the record, as shown in the screenshot, the actual Account Name is shown.

**Comment by yurikuzn** [comment]
It's restricted internally. https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/metadata/app/aclPortal.json#L102

I recommend not showing account name on the layout for portal user and fill account name with formula.

**Comment by yurikuzn** [comment]
Portal user should not be able to set any account name.
