### ISSUE TITLE
loadAdditionalFields does not work for email templates

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2009]
Issue with email template merge fields. Fields that are populated using loadAdditionalFields do not have a value when merged in to an email template.

**Comment by yurikuzn** [comment]
Please explain more clear and detail. Steps to reproduce would be helpful.

**Comment by boydle** [comment]
I have built an example of the problem and attached it:

I have created a new entity "EmailTestMyth" I have added the following code to the service:
    public function loadAdditionalFields(Entity $entity)
    {
        parent::loadAdditionalFields($entity);
        $entity->set('firstName', 'FNAME');
        $entity->set('lastName', 'LNAME');
    }  

I added the  fields firstName and lastName to the detail layout and the values set in the service are shown on the detail view.

I created an email template based on the new entity with the following body:

*************
Name: {EmailTestMyth.name},
FName: {EmailTestMyth.firstName}
LName: {EmailTestMyth.lastName}
*************

I have added "EmailTestMyth" as an email record parent.

If i use the email template and pick a "EmailTestMyth" record the name field is populated but the firstName and lastName fields are not set.
[custom.zip](https://github.com/espocrm/espocrm/files/6601921/custom.zip)
