### ISSUE TITLE
Documents: Uploading new document by drag-n-dropping a file

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2011]
On the list view.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/d7641455d496d153784bdc9fd63bb6154397ba1a

**Comment by aukrocz** [comment]
can you add the same feature to entity detail view - corresponding view of listed documents for that particular entity? 
![image](https://user-images.githubusercontent.com/73339530/186357785-a2b3f8bc-6457-4aa7-a6ca-40f9963e5d16.png)
