### ISSUE TITLE
Disable 2FA UI breaks when incorrect password given

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2016]
Hi,

I have found an issue with disabling 2FA for a user:

1) Enable 2FA for your account
2) Open your 2FA settings
3) untick Enable 2-Factor Authentication and click apply
4) enter the wrong password when prompted
5) Message shown. Incorrect PW.
6) Enter the correct password
7) Nothing happens > Expect setting to be applied.

**Comment by yurikuzn** [comment]
Hi,

Any help with the fix will be appreciated. Have a lot of work at the moment.

**Comment by arkadywtf** [comment]
Unless no one made a PR by this time, I can do a little digging later this week and see if I can find anything useful that helps.

**Comment by yurikuzn** [comment]
This fix will close the password modal if the password is not correct. More user friendly solution would require some refactoring. https://github.com/espocrm/espocrm/commit/8fef756172ca3abb78c45bc75b3c3c74dae1e6a5
