### ISSUE TITLE
Email Address Error or junk charecters

### ISSUE THREAD

**Issue by velirs** [espocrm/espocrm#2017]
Dear Team, 

I configured a Group Email Account with SMTP to Send Mails; where I use SMTP Auth and email address as "sales@foxelpie.com"
There is no issue with Outlook Client

I do receive email; but with some service providers like Gmail / live.com / outlook.com; from Email Address is as below.

**`sales@foxelpie.com <sales@foxelpie.com> on behalf of =?UTF-8?Q?sales@ <foxelpie.com?= sales@foxelpie.com>`**

is this some configuration issue or bug ? please advice

**Comment by yurikuzn** [comment]
Hi,

I've never encountered this and don't know what it can be.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/2923
