### ISSUE TITLE
Scope Level in Roles

### ISSUE THREAD

**Issue by farhadlavaei** [espocrm/espocrm#2018]
I have a question regarding using "rules". Sometimes this page can not be loaded completely (The "Scope Level" not show,
![roles](https://user-images.githubusercontent.com/7545989/122004141-45512b00-cdc9-11eb-9bc9-d40e2b306fe2.png)
 see attached pic,  please) so i should do this method one or two times to see if the page will be loaded normally or not :
1. clear cache.
2. rebuild
Why does this issue happen?
Is it a bug?
How can i prevent facing this problem?

Best regards
Farhad Lavaei

**Comment by yurikuzn** [comment]
Hi,

I don't know. Check your browser console for errors.

**Comment by eymen-elkum** [comment]
This happen when you logout from normal user and re-login to admin user without reloading the page.

Just rebuild and reload as a workaround.

**Comment by farhadlavaei** [comment]
Dear eymen-elkum
Thank you for your quick response. I think you are right.

**Comment by yurikuzn** [comment]
I could not reproduce.

**Comment by eymen-elkum** [comment]
> I could not reproduce (on master).

- go to demo.espocrm.com (must be not logged in)
- login as support user
- now logout
- re-login as administrator
- go to roles and will see the page not completed

**Comment by yurikuzn** [comment]
Metadata and language cache were not cleared when login by another user. Fixed: https://github.com/espocrm/espocrm/commit/44d97b64b927fff08b8b9af4d02e43f196d47dfd
