### ISSUE TITLE
404 Not Found on fresh install of 6.1.7

### ISSUE THREAD

**Issue by riiwjohnson** [espocrm/espocrm#2021]
I set up a fresh install 6.1.7 on new Ubuntu 20.04.2 LTS (64 bit) virtual machine using their default LAMP stack. 

- All required PHP modules installed.
- File permissions are set correctly
- File and directory ownership is set to www-data

I ran through the install without any issues and after that I receive a stylized "404 Not Found" in the main body (container-content div) that fades out after a bit.  The footer displays fine.  Once I double checked everything I upgraded to PHP 8.0.7 via `ppa:ondrej/php` but that fixed no issue. 

Am I missing something obvious or is 6.17 weird on Ubuntu?

**Comment by tmachyshyn** [comment]
EspoCRM are working fine on Ubuntu and PHP 8. 
If you made installation from this repository you have to enable `'isDeveloperMode' => true,`. More details, https://docs.espocrm.com/development/how-to-start/#option-a-using-git-repository.

**Comment by riiwjohnson** [comment]
I will check into that!

Thank you!
