### ISSUE TITLE
Text type field with audit true is not displaying clear content on the Stream

### ISSUE THREAD

**Issue by Ananyakokala** [espocrm/espocrm#2022]
- Text type fields in espocrm does not allow audit option. But we can add something like,
- `"description": {
        "audited": true
    }`  
under the entityDefination. 
- If we do it like this, a note will be created on update of the description field but the stream will not display the clear content.
 
Please find the curresponding discussion on the [espocrm forum](https://forum.espocrm.com/forum/general/28706-why-there-is-no-audit-option-on-type-textbox).

**Comment by yurikuzn** [comment]
I'll look into this later when get I chance.

**Comment by Mzingy** [comment]
Hello I hope if you can Add it

**Comment by yurikuzn** [comment]
Done.
