### ISSUE TITLE
Troubles with dev-version installation

### ISSUE THREAD

**Issue by MaryRabinovich** [espocrm/espocrm#2023]
Hi,

I'm trying to install espo from git and build it.

Composer and npm run properly.

Grunt runs almost properly but "with warnings".

Finally on the myEspoCrm/install page I have an "unexpected error" with db connection, with a log-line

ERROR: Uncaught Exception TypeError:
"Argument 1 passed to Espo\Core\Utils\SystemRequirements::__construct()
must be an instance of Espo\Core\Utils\Config,
instance of Espo\Core\Container given,
called in C:\xampp\htdocs\espocrm\install\core\Installer.php on line 262"
at C:\xampp\htdocs\espocrm\application\Espo\Core\Util s\SystemRequirements.php line 51
(e.t.c.)

In my browser I tryed the install pages both in my base espo directory and in the build directory instide it.
And always (some 10 times with both folders) I had this same error in logs.

I would really like to build it from end to end on my Windows XAMPP, without any bitnamy or any cloud.
Please, help!!

P.S.
i've changed the line 262 in core/installer: 

$systemRequirementManager = new SystemRequirements($this->app->getContainer()->get('config'));
//  $systemRequirementManager = new SystemRequirements($this->app->getContainer());

and now the error is

ERROR: Uncaught Exception ArgumentCountError: 
"Too few arguments to function Espo\Core\Utils\SystemRequirements::__construct(), 
1 passed in C:\xampp\htdocs\espocrm\install\core\Installer.php on line 262 and exactly 4 expected" at 
C:\xampp\htdocs\espocrm\application\Espo\Core\Utils\SystemRequirements.php line 51

**Comment by yurikuzn** [comment]
Do you try the `master` branch. It's not ready for yet, I did a lot of refactoring. Try `horfix` branch.
