### ISSUE TITLE
Field level security is not applied to stream notes (Update & Status) as well as notifications

### ISSUE THREAD

**Issue by aukrocz** [espocrm/espocrm#2026]
When I disable read rights for the field, it is not shown for the user with that role (OK), but when that field is audited, the user gets notification + row in stream with changed value (Security issue).

![image](https://user-images.githubusercontent.com/73339530/123509443-e1a2e980-d675-11eb-8b6d-5bed731c365b.png)

**Comment by yurikuzn** [comment]
I will take a look when get a chance. It's a known problem we lived with the very beginning. Not very easy to fix.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/25281d0c6fc85d62ca68810c99380e8fa3a7b8a8

Addressed in v6.2.0.
