### ISSUE TITLE
Address field errors when required and dynamic required are used

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2027]
Hi,

I have found an issue on addresses where using required on one field and dynamic required on another causes an error.

Steps to reproduce:
1) Entity Manger for Account
2) Set billingAddressPostalCode required
3) Set Dynamic required on billingAddressState > Industry = Advertising
4) Edit an account where  Industry <> Advertising and remove all data from the billing address fields
5) Get Post Code Required error
6) update Industry to Advertising and enter a post code
7) get errors as shown, record saved and state is not required

![image](https://user-images.githubusercontent.com/7907518/123601425-03010280-d83b-11eb-9f1c-094c0f6932a8.png)

**Comment by boydle** [comment]
![image](https://user-images.githubusercontent.com/7907518/123602227-def1f100-d83b-11eb-984e-66557fb569ce.png)

**Comment by yurikuzn** [comment]
These errors does not make any effect, the only problem that they are shown in the log, right? I encountered this before and did not consider this as a bug since the application is working as expected. These are bootstrap bug that I could not fix and didn't considered worth fixing. I believe these errors won't occur on `master` as I updated the bootstrap js recently. At least I could not reproduce.

**Comment by yurikuzn** [comment]
I missed the fact that the state should be required. I'm not sure whether it's related to the bootstrap error.

**Comment by yurikuzn** [comment]
I opened another bug report to shrink the scope to a single problem https://github.com/espocrm/espocrm/issues/2030. Setting Post field required does not effect on the behavior.

**Comment by yurikuzn** [comment]
It's a design problem that is not easy to solve. Dynamic logic was intended to work only with actual fields on the layout, but not with sub-fields of a compound fields (like address, person name fields).

**Comment by boydle** [comment]
Thanks Yuri.
