### ISSUE TITLE
Entity Manager Relationship View is missing field labels

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2036]
**Describe the bug**
Entity Manager Relationship View is missing field labels

**To Reproduce**
1. Go to entity manager
2. Click on Account
3. Click relationships

**Expected behavior**
Columns should have labels

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/125434719-9ca2a634-d369-46ab-8398-74dbff97af0a.png)

**EspoCRM version**
6.1.7

**Comment by yurikuzn** [comment]
It was not intended to display labels. It's too much columns.
