### ISSUE TITLE
Log file permission of new instance is 0644 instead of 0664

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2037]
I created a new EspoCRM instance on an AWS VM today. The OS is Ubuntu 18.04.5 LTS and the version of EspoCRM is 6.1.7. An older instance, which is running on the same OS and EspoCRM version 5.9.4, creates log files with permission 0664 (group writeable). However, the new instance creates files with permission 0644 (not group writeable). The permissions of the parent folders in both cases are 2775 (sticky bit set).

What would cause this and how can it be changed?

**Comment by yurikuzn** [comment]
The place where permissions are set for the log: https://github.com/espocrm/espocrm/blob/6.1.7/application/Espo/Core/Log/Handler/EspoFileHandler.php#L55

**Comment by bandtank** [comment]
thanks. i don't know what the issue is in my case, but this isn't an espo problem.
