### ISSUE TITLE
Instant loading foreign fields on select w/o saving link

### ISSUE THREAD

**Issue by sab0tajue** [espocrm/espocrm#2040]
It would be useful to fix one significant problem in my opinion. When selecting an entry in the external field from the section, load the data associated with this entry immediately, and not after I clicked the "Save" button"

**Comment by yurikuzn** [comment]
I don't understand. Please provide steps to reproduce: https://github.com/espocrm/espocrm/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by yurikuzn** [comment]
Are you talking about Foreign fields being not loaded until the link is saved?

**Comment by sab0tajue** [comment]
> Are you talking about Foreign fields being not loaded until the link is saved?

Yes

**Comment by yurikuzn** [comment]
This is not easy to fix I think.

**Comment by sab0tajue** [comment]
If this could be done in the future, it would be wonderful.

**Comment by radek3911** [comment]
I actually needed to do this for dynamic logic, you can make custom field view on the link
```ts
define(['views/fields/link'], FieldView => {
	return class extends FieldView {
		mandatorySelectAttributeList: Array<string> = ['name', 'group'];

		async select(model) {
			super.select(model);

			this.model.set(
				'productGroup', // product group is foreign field
				model.get('group') // this model is from the function parameter and contains id + name, using mandatory select attributes on first line I was able to make it select group field additionally
			);
		}
	};
});
```

note that there is a bug with foreign fields and in order to use this correctly with dynamic logic additional hook must be created as per additional context here #2857

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/0f146959e50b2487ea4ecbf6ed654d1d1b2e7e73
