### ISSUE TITLE
Editable tag line in 'description' HTML metatag

### ISSUE THREAD

**Issue by sekjal** [espocrm/espocrm#2041]
**Is your feature request related to a problem? Please describe.**
The default description meta tag for Espo is hard-coded in html/main.html to "EspoCRM is Open Source CRM application. Increase profitability through customer loyalty!".  Applications like Slack that bring in additional information about a link pasted in show this tagline every time, and it may not be relevant to a particular instance of EspoCRM.  It would be nice to be able to customize it like you do the Application Name.

**Describe the solution you'd like**
Making a 'tag line' configuration option, next to Application Name, in the system Settings.

**Describe alternatives you've considered**
Manually editing this in html/main.html is not upgrade-proof, nor is using a custom language file

**Additional context**
I'd be happy to implement and submit a pull request as my first foray into community contribution, if this is a desirable addition to the codebase.

**Comment by yurikuzn** [comment]
I will add a config parameter.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/52159093dd3a817a711e1fb2a5171e4b351e1290

Only for manual change in the config. Didn't add to admin UI through.
