### ISSUE TITLE
Formula email sending attachment

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2050]
**Describe the bug**
The email is sending but the attachment is not included

**To Reproduce**
1. use this formula:
```
    $emailId = record\create('Email',
        'to', $to,
        'status', 'Draft',
        'attachmentsIds', list(fileId),
        'parentId', id,
        'parentType', 'Contact'
    );
    
    //applying email template Id
    ext\email\applyTemplate($emailId, '60f96b0fb996194ff');
    ext\email\send($emailId);    

```
2. the contact has field from type "file" named file
**EspoCRM version**
6.1.7

**Additional context**
**If we change the field name from `file` to `attachments` the problem will be fixed,**

**Comment by arkadywtf** [comment]
As far as I'm aware Espo doesn't allow you to insert the attachment from the list of existing ones, for built-in entities anyway. You can for example insert a document, but it will duplicate the file and set parent to an email. The same goes for field `attachments`. When last time I checked it reassigns the file to an email so you lose the original relation since it changes the `parent` field in Attachment. So if you attach a file to a Task record and then insert the same `attachmentId` in an Email then you no longer see the attachment in Task.

So I guess if you wanted to send an attachment you'd need to duplicate it first.

**Comment by yurikuzn** [comment]
Well, this is not a bug as setting attachmentsIds is not supported and won't be fixed. Might be 'a missing ability to attach files'.

**Comment by arkadywtf** [comment]
@eymen-elkum maybe try something like this

```
$attachmentId = record\create('Attachment',
    'role', 'Attachment',
    'type', record\attribute('Attachment', fileId, 'type'),
    'size', record\attribute('Attachment', fileId, 'size'),
    'global', record\attribute('Attachment', fileId, 'global'),
    'name', record\attribute('Attachment', fileId, 'name'),
    'sourceId', fileId,
    'storage', record\attribute('Attachment', fileId, 'storage')
);

$emailId = record\create('Email',
    'to', $to,
    'status', 'Draft',
    'attachmentsIds', list($attachmentId),
    'parentId', id,
    'parentType', 'Contact'
);

//applying email template Id
ext\email\applyTemplate($emailId, '610266d717e2c7e7c');
ext\email\send($emailId);    
```

**Comment by yurikuzn** [comment]
For most cases like this, having an attachment in Email Template will do the work.

**Comment by eymen-elkum** [comment]
> For most cases like this, having an attachment in Email Template will do the work.

Sometimes including attatchment from the entity is useful, anyway just renaming the field fixed the issue completely.

Thank you @arkadywtf I tried your suggestion and worked!
Maybe it is good to make article for this case and suggestion.

Anyway, this may be also fixed by letting Email entity allow relations from attachments skipping the field column value.

**Comment by yurikuzn** [comment]
> this may be also fixed by letting Email entity allow relations from attachments skipping the field column value.
It can't be fixed this way. This is not a bug, this is a design choice. This will cause troubles in other places. One attachment record -- one email record. When checking access to the attachment for a user, we check access to its SINGLE parent.
