### ISSUE TITLE
replacing a link to text

### ISSUE THREAD

**Issue by sab0tajue** [espocrm/espocrm#2055]
In the properties of the "URL" field, I would like to be able to close the link with text. Now when I enter the value "http://espocrm.com" in the url field, then in layouts it is displayed as "http://espocrm.com" and in the layout I would like to display the list "Link" or "Icon"

**Comment by bandtank** [comment]
I’m having trouble understanding what you are saying. Are you asking for a way to display text instead of a link? If so, that is a feature I want to have as well. Some URLs are very long and ugly, so it would be nice to have a way to show text in the field instead.|

**Comment by eymen-elkum** [comment]
He just want to set label or icon instead of displaying the url itself
