### ISSUE TITLE
Error 500 in LDAP Authorization

### ISSUE THREAD

**Issue by farhadlavaei** [espocrm/espocrm#2063]
When set the LDAP information , got this error.

500: 0x31 (Invalid credentials; 80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563): ou=TNC Users,dc=TNC,dc=com

**Screenshots**
 
![image](https://user-images.githubusercontent.com/7545989/131330784-24b02a8a-4598-44ad-90e6-3c8a249b1195.png)

**EspoCRM version**
6.1.7

**Additional context**
The credentials is worked in another software.

**Comment by yurikuzn** [comment]
We tested recently and it worked. Please try to debug. If you find the reason that it's a problem in Espo please let us know.

**Comment by farhadlavaei** [comment]
I got this error again in LOG:
ERROR: (49) 0x31 (Invalid credentials; 80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563): ou=TNC Users,dc=TNC,dc=com; POST /Settings/action/testLdapConnection; line: 990, file: /opt/lampp/htdocs/vendor/laminas/laminas-ldap/src/Ldap.php [] []

**Comment by farhadlavaei** [comment]
Dear yurikuzn
I can't solve my problem and i could not find where was it. The other softwares in my local network is worked with this setting.
I'll be thankful if you guide me.

**Comment by yurikuzn** [comment]
I'm not competent here. Have never configured LDAP.

**Comment by tmachyshyn** [comment]
Dear farhadlavaei,

Please let me know what LDAP server do you use?

**Comment by farhadlavaei** [comment]
Windows Active Directory Service 2019

**Comment by tmachyshyn** [comment]
We will check this.

**Comment by frankulatowski-scm** [comment]
We have the same problem and get the same error message as farhadlavaei.

EspoCRM version 6.1.9
Windows Server 2019 Datacenter Edition (x64).

Using ldapsearch, our administrator was able to successfully connect to the LDAP server and read groups and members. Therefore, our guess is that something is not right with EspoCRM.

**Comment by frankulatowski-scm** [comment]
The LDAP connection now works for us, but it had to be set up somewhat differently than described under "Troubleshooting".

In the first step we changed "Account Canonical Form" from "Dn" to "Principal" and at the same time "Full User DN" to "espocrm@domain.zz", as recommended. The other settings remained unchanged. We were then able to successfully set up a test connection to the LDAP server.

However, no user could log in (wrong username/password, error 0x0). We then tried different combinations: After we changed "Username Attribute" to "Username" and at the same time "Account Canonical Form" from "Principal" to "sAMAccountName", a successful login succeeded. 

Surprisingly, the test connection continues to work even though "Account Canonical Form" is no longer set to "Principal". We therefore assume that the change of the "Full User DN" was sufficient to enable the connection to the LDAP server.

By the way, the user gets an error at the first login (Server side error 500: User must be fetched before ACL check), but is created in EspoCRM. After the second login, the login works as expected and the user can successfully log in to EspoCRM.

In any case, thanks for the support!

**Comment by tmachyshyn** [comment]
It is great that this solution works for you.

Do you mean that the correct settings for you are:
- `Username Attribute` is `sAMAccountName`.
- `Account Canonical Form` is `Username`.
Correct?

I'm sure when the `Username Attribute` is `sAMAccountName`, the `Account Canonical Form` can be `Principal` or `Username`.

We will investigate the second error at the first login.

**Comment by frankulatowski-scm** [comment]
That's right, I had it mixed up above. We have the following working settings:

``Username Attributes`` is  ``sAMAccountName``
``Account Canonical Form`` is ``Username``

**Comment by tmachyshyn** [comment]
Thanks for your confirmation.
We are investigating this problem.

**Comment by TSJasonH** [comment]
> > By the way, the user gets an error at the first login (Server side error 500: User must be fetched before ACL check), but is created in EspoCRM. After the second login, the login works as expected and the user can successfully log in to EspoCRM.
> 
> I can confirm this issue as well on a fresh install of 6.1.9. The user is created from ldap but not logged in. Instead that error is shown. If they simply login again it works fine.

Apologies, I realize I didn't include the error from the log in case it's useful. 

`[2021-09-29 16:15:32] ERROR: (500) User must be fetched before ACL check.; GET /App/user; line: 119, file: /var/www/html/application/Espo/Core/Acl/Table.php [] []
`

**Comment by tmachyshyn** [comment]
The problem for the first time login is fixed in EspoCRM v7.0.0.
Thanks everyone for helping.
