### ISSUE TITLE
Date Time Field does not pick value on first attempt (when panel is being shown)

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2065]
**Describe the bug**
The date time field does not pick a value on the first time.

**To Reproduce**
1. Add a date time field to account (standard options, only set the name and label)
2. Add a new panel to the account detail form
3. Add dynamic logic to the panel to only show if Account Type = Customer
4. Create a new account set Account Type = Customer
5. set the date in the date time field
6. No value picked
7. set again
8. Value picked

**Expected behavior**
Field value should pick on first attempt

**EspoCRM version**
6.1.7

**Additional context**
Seems to occur only with dynamic logic hiding the field when the record is first shown.

**Comment by yurikuzn** [comment]
Thanks for reposting. The fix is quite complex and needs to be tested.

https://github.com/espocrm/espocrm/commit/0041c11aae0591cd4dc278dd03402c35965ea1ef
