### ISSUE TITLE
Dynamic logic based on current user

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2066]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Enhancing dynamic logic with current user, many clients are interested in setting roles based on the login user (his roles for example) to hide panels or fields and so ...

I wonder how hard is to implement this feature, I am open to contribute regarding implementing it.

**Comment by yurikuzn** [comment]
It contradicts the current design of dynamic logic.

BTW for hiding panels you can utilize Layout Sets with different rules for panels.

**Comment by yurikuzn** [comment]
As a workaround is to have notStorable field with a current user ID (set with the new field loader framework https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/FieldProcessing/Loader.php).

**Comment by eymen-elkum** [comment]
> A workaround is to have notStorable field with a current user ID (set with the new field loader framework https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/FieldProcessing/Loader.php).

This is amazing! not noticed it before, I think it will do the hard part, will see if the rest can be done as an extension.

**Comment by yurikuzn** [comment]
Here's where classes are loaded: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/FieldProcessing/ReadLoadProcessor.php#L90

If you'd like to implement for all entities, the problem is that you need to have that notStorable field created for all entities somehow.

**Comment by boydle** [comment]
I agree that some extra functions would be great. For example to be able to set read only conditional logic based on portal non portal user.
