### ISSUE TITLE
Email 2 factor authentication

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2069]
Admin should allow Email 2FA method at Administration > Authentication. Then users will be able to setup Email 2FA at User detail view > Security.

It's highly recommended for users to use a non-primary email address for 2FA. A user should have at least two email addresses (set by admin).

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/bf72c8a4ccca99351ad4d6cc6cfb33dc1c9e9423

**Comment by pradnya-khandagale** [comment]
@yurikuzn please help me

**Comment by yurikuzn** [comment]
Please use our forum. We don't provide support on GitHub, I'm extremely busy.
