### ISSUE TITLE
Possibility to login by email and username

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#2074]
Is it possible to implement a way to login by either email or username or BOTH?
How hard would that be to be implemented?
Can this be easily done by changing any code in the current codebase or eventually making it as an extension? (upgrade proof)

**Comment by yurikuzn** [comment]
It can be done easily. I recommend to do it for v7.0 as interfaces changed.

Factory: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Authentication/AuthenticationFactory.php
Interface: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Authentication/Login.php

Just create a custom authentication method and implement the Login interface.
