### ISSUE TITLE
Select manager layers

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2079]
**Is your feature request related to a problem? Please describe.**
Yes, in many cases we need to apply some general logic to filter data, **
Roles & teams** are very good tools, but sometimes we need more tools & logic, like **organizations or projects**.
Or just defining new  general (bool) filter similar to "**Only my**".

I know we can define custom **Select Manager** but we cannot force all entities like events based one to inherit from the custom select manager.

**Describe the solution you'd like**
I think we can use the php magic function **__call** in combination with app json defs, to run additional layers passing the **&$result** to them.

**Describe alternatives you've considered**
I succeed to define custom `selectManagerFactory` & `SelectManager`, but I had to re define all custom select managers like Meeting, Leads and so to add the same function to them all.

**Additional context**
I think this will be great addition to version 7, you are the best to do it but in case you liked the idea and not have the time I am ready to do it.

**Comment by yurikuzn** [comment]
Select Manager is deprecated and is not used in v7.0.  A new SelectBuilder is the most important feature of v7.0.

See https://github.com/espocrm/espocrm/issues/1865

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Select/Primary/FilterFactory.php#L82

**Comment by eymen-elkum** [comment]
One another interesting feature to be watching for!
There are a lot of features can be implemented using this tool
