### ISSUE TITLE
Add types to classes properties

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2081]
**Is your feature request related to a problem? Please describe.**
Not issue, but developers will love to see autocomplete working when they write something like `$this->entityManager->`

PHP > 7.4 will support this feature which help in testing code in addition to writting more quickly, this was asked before as PHP Doc, and I agree with your answer that types are better, what do you think?

**Comment by eymen-elkum** [comment]
```diff
 {
     protected $entityFactory;
 
-    protected $entityManager;
+    protected EntityManager $entityManager;
 
     protected $seed;
 
```

**Comment by yurikuzn** [comment]
PHP 7.3 is supported version.

IDEs can handle property types if they are passed through a constructor. I never had a problem that IDE does not autocomplete.

**Comment by eymen-elkum** [comment]
What is your IDE?

**Comment by yurikuzn** [comment]
NetBeans. Far from perfect though.

**Comment by yurikuzn** [comment]
Which one you use?

**Comment by eymen-elkum** [comment]
PHPStorm :)

I found it great, except for the above issue

**Comment by yurikuzn** [comment]
Can you give an example of the class in Espo with such an issue? It would be weird if PHPStorm didn't handle this.

**Comment by arkadywtf** [comment]
I would love to see strict types be used more in Espo the same way the team over at Sylius is doing it, but not for the auto completion reasons. Will PHP 7.3 still be supported even after security patches end this year?

**Comment by eymen-elkum** [comment]
Just go to any custom php service class and extend `afterCreateEntity` for example, writting $this->entityManager-> will never trigger any autocomplete, the editor will not recognize its type.

**Comment by yurikuzn** [comment]
Because Record Service dependencies are injected via traits. It's already typed with phpdoc in v7.0.

**Comment by yurikuzn** [comment]
> I would love to see strict types be used more in Espo the same way the team over at Sylius is doing it, but not for the auto completion reasons. Will PHP 7.3 still be supported even after security patches end this year?

Espo is mostly strict typed already.

**Comment by yurikuzn** [comment]
JFYU. It's not recommended to extend Record Services since v7.0.

**Comment by yurikuzn** [comment]
> Will PHP 7.3 still 

Will end support in 6 months I hope.

**Comment by arkadywtf** [comment]
> Espo is mostly strict typed already.

Have you thought about adding `declare(strict_types=1);` for each file?

**Comment by yurikuzn** [comment]
Maybe one day. I don't find it important to have. Would be better to add a static analysis  tool first.

**Comment by arkadywtf** [comment]
> Would be better to add a static analysis tool first.

That would be great, do you have any in mind? I'm using [rector](https://github.com/rectorphp/rector) which ships with PHP Stan and [ecs](https://github.com/symplify/easy-coding-standard) which uses CodeSniffer and CS-Fixer.

BTW the cherry on top would be having these tools set up a separate repo like `espocrm-coding-standard` and have the ability to include it as a composer package for ext-template so we can reuse the same rulesets while creating extensions.

**Comment by yurikuzn** [comment]
PhpStan or Psalm.
