### ISSUE TITLE
User export does not export lastAccess field

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2087]
**Describe the bug**
When exporting a list of users you can select lastAccess as a field to export however it is always empty

**To Reproduce**
Navigate to users
Select some users
export them and select lastAccess as one of the fields

**Expected behavior**
lastAccess should contain the last accessed date time however it is empty

**EspoCRM version**
6.1.4

**Comment by yurikuzn** [comment]
It is not storable field and can't be implemented having the current logic.
