### ISSUE TITLE
Upgrade to 7.0.0 fails

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#2088]
Hi team,

I've just upgraded my EspoCRM environment via cli from 6.1.9 --> 6.1.10 --> 7.0.0. The second step towards 7.0.0 failed.
CLI Output:
`Error: Error occurred while EspoCRM rebuild. Please see the log for more detail.`

While upgrading I noticed the following 2 errors in the log file (log level set to DEBUG):

`[2021-10-01 17:36:01] ERROR: Uncaught Exception Espo\Core\Exceptions\Error: "InjectableFactory: Class Espo\ORM\EventDispatcher does not exist" at /wwwroot/application/Espo/Core/InjectableFactory.php line 168 {"exception":"[object] (Espo\\Core\\Exceptions\\Error(code: 500): InjectableFactory: Class Espo\\ORM\\EventDispatcher does not exist at /wwwroot/application/Espo/Core/InjectableFactory.php:168)"} []`

`[2021-10-01 17:36:56] ERROR: Database rebuild failure, details: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'job.class_name' in 'field list'. [] []`

Can I supply any additional info which could help solving this issue?

**Comment by yurikuzn** [comment]
Hi,

Please use our forum for upgrade help. It's weekends here. I want to rest.

Upgrading from UI is not supported at the moment (not sure if will be).

**Comment by yurikuzn** [comment]
I don't know why it's not upgrading. We tested multiple times. Maybe some env specificity. Like cached files. Not sure. When environment is not under our control it's a nightmare to support all such cases.

**Comment by yurikuzn** [comment]
As a last resort you can always just copy files from the fresh Espo distr, (and remove old ones). And after that change 'version' in data/config.php.

**Comment by yurikuzn** [comment]
In this article it's described how to upgrade manually: https://docs.espocrm.com/administration/upgrading-manually/

All steps from this article are actually steps made by the upgrade script. Assuming you have Linux, all steps will run in a separate process.

**Comment by neknarf** [comment]
Hi Yuri,
Thanks for the tips. Never had any upgrade issues for past 2 years. I will try to see if manually upgrading goes without issues.

**Comment by yurikuzn** [comment]
Also try running again.  And see what errors logged for that run (if not success).

**Comment by neknarf** [comment]
> Also try running again. And see what errors logged for that run (if not success).
> 
> Note that this release has very lot of changes. So if you have some customizations (made by coding) they can be not compatible.

Second attempt was successful! No errors at all.
Thanks again for your feedback and hard work!
