### ISSUE TITLE
Task entity missing list.js view return 404

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2090]
In a new install of version 7.0 the task entity is not loading for a 404 regarding to

"/client/modules/crm/src/views/task/list.js"

**Comment by yurikuzn** [comment]
Could you check whether the file exists?

**Comment by Kharg** [comment]
The file was missing, I added it manually by download the 7.0 release.
Maybe Filezilla failed to upload the file and I didn't notice.
