### ISSUE TITLE
Log not work as expected on v7

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2091]
**Describe the bug**
I have custom php controller class, after upgrade to 7 made crm stop working because not compatible with the new parent method, logs was empty but I found the error message in php error log.

**To Reproduce**
1. extend any php controller, and override any action method and remove the return type from the method like this

`public function postActionCreateLink(Request $request): bool`
Just remove :bool

**Comment by yurikuzn** [comment]
Compile errors are logged in webserver log. It's not possible to log in Espo.
