### ISSUE TITLE
dataquality : record level validation

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2093]
Field validation as implemented in https://github.com/espocrm/espocrm/issues/1330 is very handy to check for not valid formats or values. 

From a dataquality perspective implementing record level validation would be welcome. 

For example : 
- we sell different kind of products : screws, tools and batteries
- we can deliver worldwide, except we do not accept orders for batteries in Sweden. 
- we don't sell tools to Singapore

In this case you would like to be able to define one or more restrictions on the entitylevel:

```
pseudocode: 

$rejectcondition = ( account.country == "SWEDEN" AND article.articlegroup == "Batteries");
$rejectmessage = ("Orderline is invalid : We cannot register orderlines in this articlegroup for this country") 
rejectrecords.add( $rejectcondition, $rejectmessage ); //add this record level restriction

$rejectcondition = ( account.country == "SINGAPORE" AND article.articlegroup == "Tools");
$rejectmessage = ("Orderline is invalid : You cannot order Tools for this country") 
rejectrecords.add( $rejectcondition, $rejectmessage ); //add this record level restriction

```

Other examples : "We do not accept premium members for EU countries" 

For now we create "exception reports" that run frequently and get mailed. 
But you would like to prevent that non valid data gets registered in the first place.

**Comment by yurikuzn** [comment]
This https://github.com/espocrm/espocrm/issues/2720 solves the problem.

**Comment by RabeeBrahimi** [comment]
in this example https://github.com/espocrm/documentation/blob/master/docs/administration/api-before-save-script.md#access-control is that mean that the changes won't be saved. this is similar to validation framework but it is very powerful. 

Thanks for such implementation.

**Comment by yurikuzn** [comment]
Won't be saved as the script is executed before save. The user will see the error message with the specified text (markdown supported). It's also possible to write a frontend error [handler](https://docs.espocrm.com/development/frontend/save-error-handlers/) that will catch the error.
