### ISSUE TITLE
TOTP allow redisplay of QR to allow for multiple authenticators

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2095]
At this moment the implementation of TOTP allows a single authenticator. 

Currently to set up a different TOTP authenticator I need to fetch the secret TOTP key from the DB, 
and enter it in the TOTP device/program. 

As a logged in user it would be practical to redisplay the key/QR code to allow for a second 2FA device.

**Comment by yurikuzn** [comment]
Is it a common practice? My concern that it can be stolen (by neighbour or XSS) in case they already know a password.
