### ISSUE TITLE
Missing multiple selection of emails

### ISSUE THREAD

**Issue by copendia** [espocrm/espocrm#2107]
After Upgrade to 7.0.4 we realized the checkbox for selecting multiple E-Mails is missing.
The Problem is still persistent in 7.0.5

1. Open E-Mail Tab
2. Try to select multiple E-Mails (checkbox is missing)

We hope this behavior is not intended because this would make working with mails pretty uncomfortable.

**Comment by yurikuzn** [comment]
As I temporary workaround you can grand access *delete = own* for Email scope in Roles. It will fix the problem. I will take a look.
