### ISSUE TITLE
Layout Manager: Ability to remove side panels

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#211]
Like Activities, History, Tasks, etc.

**Comment by rodrigoscoelho** [comment]
What about the possibility to add side panels?

Email enviado usando um celular....

Em 29 de ago de 2016 09:42, "Yuri Kuznetsov" <notifications@github.com>
escreveu:

**Comment by yurikuzn** [comment]
Not planned.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/eff0152f44cbe85021753772b0d891442c0afcf8
