### ISSUE TITLE
Array values that are longer than field length cause UI issue

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2114]
**Describe the bug**
View: views/fields/array has a display issue when long values are provided. The X's of this long record and the next record in the list are incorrectly placed. Sample image using entity names provided. 

**To Reproduce**
1. Update Account label to be long
2. view UI settings and see result

**Expected behavior**
X should always be at end of line and visble

**Screenshots**
<img width="359" alt="long array val ui" src="https://user-images.githubusercontent.com/7907518/137665969-ffdcf5f0-c412-4e17-8c4f-f2b1e589b751.png">

**EspoCRM version**
6.1.4

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/d2a1737a9ef349893a7db96f2645a261e961135a
