### ISSUE TITLE
ver 7 customWhere / raw SQL 

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2116]
Hello, I was using Espo for a long time and made many customizations for my needs. Most of them are made through customWhere (custom SQL code) that can not be created / redesigned easily through ORM interface. Espo 7 totally broke such customizations. For example I have complex queries for primary filters that are done through customWhere, also some functions made through stored procedures that are called with SQL. Is there any backdoor to append custom sql code in api, or maybe you could move back customWhere support please ?

**Comment by yurikuzn** [comment]
I'm going to provide guidelines bit later.

**Comment by rutkas** [comment]
> I'm going to provide guidelines bit later.

Do you mean that `where` supports plain sql parts ?

**Comment by rutkas** [comment]
Hello, I have tried this new feature with custom functions and has no succcess. 
I ahave created a map in `custom/Espo/Custom/Resources/metadata/app/orm.json` pointing to my class:

```
{
    "functionConverterClassNameMap_Mysql": {
        "ABS": "Espo\\Core\\ORM\\QueryComposer\\Part\\FunctionConverters\\Abs",
        "REL_REC_EXISTS": "Espo\\Custom\\ORM\\QueryComposer\\Part\\FunctionConverters\\RelatedRecordExists"
    }
}
```

Created class in `custom/Espo/Custom/Core/ORM/QueryComposer/Part/FunctionConverters/RelatedRecordExists.php`:
```
namespace Espo\Custom\Core\ORM\QueryComposer\Part\FunctionConverters;

use Espo\ORM\QueryComposer\Part\FunctionConverter;

class RelatedRecordExists implements FunctionConverter
{
    public function convert(string ...$argumentList): string
    {
        return " AND (select count(*) from opportunity where (opportunity.account_id = account.id) and (opportunity.stage='Closed Won') and (opportunity.deleted = 0) ) > 0";
    }
}
```

but it is an error:

`InjectableFactory: Class 'Espo\Custom\Core\ORM\QueryComposer\Part\FunctionConverters\RelatedRecordExists' does not exist.`

Maybe I have put RelatedRecordExists.php in a wrong place and used wrong namespace.. but Have no idea where it should be in custom. Example Abd function from dist is from main Espo namespace, not modules/custom

Please advise

**Comment by yurikuzn** [comment]
Maybe you missed `<?php` in the beginning of the file.

**Comment by rutkas** [comment]
Yes, you are right, deleted it when copy-pasted from example, just noticed it 1 minute ago. thanks. 
But now got mysql error:

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (select count(*) from opportunity where (opportunity.account_id = account.id' at line 1; GET /Account; line: 70`

**Comment by yurikuzn** [comment]
Sorry, but this is not related to Espo

**Comment by rutkas** [comment]
this code worked perfectly in SelectManagers:

```
class Account extends \Espo\Modules\Crm\SelectManagers\Account
{

    protected function filterHasSuccessOpps(&$result)
    {
        $result['customWhere'] .= " AND (select count(*) from opportunity where (opportunity.account_id = account.id) and (opportunity.stage='Closed Wo
n') and (opportunity.deleted = 0) ) > 0";
    }

```

**Comment by rutkas** [comment]
I just realized that  > 0 should be moved out to custom function call: 
```
$queryBuilder->where([
     'REL_REC_EXISTS:(argument1, argument2)>' => '0',
]);
```


```
public function convert(string ...$argumentList): string
    {
        return " (select count(*) from opportunity where (opportunity.account_id = account.id) and (opportunity.stage='Closed Won') and (opportunity.deleted = 0) )";
    }
```

And it worked. thanks

**Comment by rutkas** [comment]
Hello, I noticed a strange behaviour while working with custom functions.

Im calling my function passing sql code as argument:

`$queryBuilder->where(['CUSTOM_WHERE:("' ."(select count(*) from opportunity where (opportunity.account_id = account.id) and (opportunity.stage='Closed Won') and (opportunity.deleted = 0))" . '")>' => '0']);
`

function code is:

```
<?php

namespace Espo\Custom\Core\ORM\QueryComposer\Part\FunctionConverters;

use Espo\ORM\QueryComposer\Part\FunctionConverter;

class CustomWhere implements FunctionConverter
{
    public function convert(string ...$argumentList): string
    {
        //$arg = trim(str_replace("\\'", "'", $argumentList[0]), "'");
        $arg = $argumentList[0];
        $GLOBALS['log']->error('arg=' . $arg);
        return $arg;
    }
}
```

as a result there are single quotes around string and backslashes near existing single quotes. These extra sumbols were were not present in string that is passed as an argument.

`[2021-11-07 20:25:13] ERROR: arg='(select count(*) from opportunity where (opportunity.account_id = account.id) and (opportunity.stage=\'Closed Won\') and (opportunity.deleted = 0))' [] []`

I can uncomment the line that removes these extra symbols, but maybe it is a bug somewhere ?
