### ISSUE TITLE
LDAP: User Teams is not set for auto-created user

### ISSUE THREAD

**Issue by gramakri** [espocrm/espocrm#2120]
**Describe the bug**
The teams of an auto-created LDAP user are not set.

**To Reproduce**
1. Setup EspoCRM to use LDAP
2. In the LDAP UI, assign User Team. In the screenshot below, I have set it to `CloudronTeam`.
![image](https://user-images.githubusercontent.com/82041/138374911-29606b6d-b48f-4fd5-bb7f-6ad7cd8be3bf.png)

3. User logs in via LDAP
4. The Teams is not set for the auto-created user.

![image](https://user-images.githubusercontent.com/82041/138375000-0157795c-f3e5-436e-b634-1ed8d39b4586.png)

**Expected behavior**
The Teams of auto-created user must be set to the User Teams setting in LDAP.

**EspoCRM version**
Tested with EspoCRM 7.0.3 . I tested this EspoCRM 6.1.10 and it works there. So, seems like a regression in EspoCRM 7.

**Comment by yurikuzn** [comment]
Duplicate: https://github.com/espocrm/espocrm/issues/2111
