### ISSUE TITLE
Websocket causes multiple /notReadCount requests at the same time

### ISSUE THREAD

**Issue by shefi** [espocrm/espocrm#2127]
**Is your feature request related to a problem? Please describe.**
When using websocket, if there are a few updates at the same time it will cause a burst of requests to /notReadCount at the same time. This will result in an unnecessary load and many of those requests will result in *Timeout* message in frontend.

**Describe the solution you'd like**
Add a delay/defer of requests to /notReadCount when using websocket, so requests are not sent immediately, but after a short time. If there is a new request coming in, it should cancel previously queued ones and queue only the very last one request.

**Describe alternatives you've considered**
Alternatively, if it is easier to implement first or together with the above fix, an option to choose in Settings which channels will update via websocket (detail view, notifications, etc...)

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/e5e29101fdcf69689d34a1bf391a3da1bc166cdb
