### ISSUE TITLE
Unable to view job queue details - 403

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2136]
**Describe the bug**
Get a 403 when trying to view scheduled job

**To Reproduce**
1) Navigate to admin jobs
2) on a job use the menu to view it
3) Click on the scheduled job link
3) 403 error

**Screenshots**
<img width="1219" alt="job bug 1" src="https://user-images.githubusercontent.com/7907518/140025614-9627fdc4-a87b-42ba-b456-f5d1a6c1af6c.png">
<img width="565" alt="job bug 2" src="https://user-images.githubusercontent.com/7907518/140025621-d3cf8b77-351d-4baa-82aa-ae9c17e77ec2.png">

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
It's by design. This is a system job.

**Comment by boydle** [comment]
Can the links be removed when there is no record to link to?

**Comment by yurikuzn** [comment]
It's too tedious to make such fixes. Requires quite a lot of effort but benefit is small. Maybe someday when Espo will became a corporation we will take care of such small things.
