### ISSUE TITLE
Action History/AuthLog records can be edited via API

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2140]
**Describe the bug**
Both Action History and Auth Log records can be edited via API

**To Reproduce**
Submit a put edit to an action history record

**Expected behavior**
This should be forbidden

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/140635165-3c1a203f-35fc-4834-9a54-fb586cc674be.png)
![image](https://user-images.githubusercontent.com/7907518/140638344-db9613de-055e-4b94-bf13-3bb3efd560ce.png)

**EspoCRM version**
7.0.7

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/25a607952ca498722901f21c95cf7ecc8b361543
