### ISSUE TITLE
textFilter from SelectManager in v7

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2141]
I have used to customize textFilter function in SelectManager for specific objects. How we can do it now in ver7 ?

**Comment by yurikuzn** [comment]
I recommend looking through code in `Espo\Core\Select` namespace. It's pretty straightforward. I looked into and found: https://github.com/espocrm/espocrm/blob/7.0.8/application/Espo/Core/Select/Applier/Appliers/TextFilter.php#L225. Then looked into the factory class and found: https://github.com/espocrm/espocrm/blob/7.0.8/application/Espo/Core/Select/Text/FilterFactory.php#L54
