### ISSUE TITLE
getAttachmentFromImageUrl not work in 7.0.8

### ISSUE THREAD

**Issue by WilixLead** [espocrm/espocrm#2142]
**Describe the bug**
After upgrade from 6x to 7.0.8 I get errors in my custom module. I use getAttachmentFromImageUrl from application/Espo/Services/Attachment.php and looking to 
application/Espo/Services/Attachment.php line 304 - it shows call:

`$attachment = $this->getEntity();`

So, then if we check this method (it is from application/Espo/Core/Record/Service.php) we can see (line 290):

`public function getEntity(string $id): ?Entity`

After checking this file, I see next logic: if $id not provided, we return null value. But getAttachmentFromImageUrl require valid $attachment entity for save image.

**To Reproduce**
this is custom code

**Expected behavior**
Image should be saved from url correctly

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
It's already fixed: https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Attachment.php#L308
