### ISSUE TITLE
Integration tests error Missing config file on tests/integration

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2143]
1. me create a config file tests/integration/config.php
2. run: vendor/bin/phpunit tests/integration

error message:
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

Config for integration tests [tests/integration/config.php] is not found

**Comment by yurikuzn** [comment]
Try debugging here: https://github.com/espocrm/espocrm/blob/master/tests/integration/Core/Tester.php#L141
