### ISSUE TITLE
Entity Icon Does not update reliably when changed in entity manager

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2144]
**Describe the bug**
When editing an entities icon it does not always correctly refresh the menu icon. if you change the icon a few times in a row you will see the icon in the menu get out of sync with what is actually selected (shows the previous icon). When the whole screen is refreshed the correct icon will be shown.

**Expected behavior**
Icon should show what was last selected and saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/141285650-11f4673d-44b3-4474-becf-af3d1c20337b.png)

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
Could not reproduce. Might be already resolved.
