### ISSUE TITLE
custom personName field

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2146]
one more bug in v7.
adding custom personName field to the entity (tried in Lead and Account):

```
        "contactName": {
            "type": "personName"
        },
```

Adding this new field to textFilterFields:

```
       "textFilterFields": [
            "name",
            "contactName"
        ],
```

Error when searching:

`ERROR: (0) Attribute 'contactName' does not exist.; GET /Lead; line: 224, file: /var/www/htdocs/application/Espo/ORM/Defs/EntityDefs.php [] []`

Default "name" with same field type "personName" is working.

**Comment by yurikuzn** [comment]
This is not an issue of v7. Custom person name was never supported. This should fix the problem: https://github.com/espocrm/espocrm/commit/798f56650d6c34780a7341d38b3e33dccf9ae4af
