### ISSUE TITLE
Adding extra field to phoneNumber type.

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2147]
Previousely before V7 we added extra field to phoneNumber field near "type" modifying client part and server part.
`public function getPhoneNumberData` and  `protected function storeEntityPhoneNumberData` in custom/Repositories/PhoneNumber were redefined to read and write values.

Now in Espo7 only getPhoneNumberData is working. How to store an extra sub-field for phoneNumber type in new version? For example searching code where "type" is written for phoneNumber gives many different places of code. What is a right way to do it now ?
thanks

**Comment by yurikuzn** [comment]
Moved to the separate class https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/FieldProcessing/PhoneNumber/Saver.php

**Comment by rutkas** [comment]
I have noticed that most functions and vars in that calss are private. As for me it is a bad idea, because I had to rewrite and copy paste all the class for just adding an extra field.  If varibled and methods will not be not private, we could rewrite just one or two functions in extended class.

**Comment by yurikuzn** [comment]
You are not right. Having everything private is the way to go for a solid codebase. Extending is kind of obsolete and not considered a good practice by modern standards. Use composition to inject the class you would like to extend.

**Comment by yurikuzn** [comment]
> I had to rewrite and copy paste all the class for just adding an extra field.

Yes. But it guarantees that it will work after we make changes inside the class. By making something protected we take a burden to maintain internals of the class. Only public should be a contract, not internals.
