### ISSUE TITLE
Blank accound ID in list and details

### ISSUE THREAD

**Issue by chirabino** [espocrm/espocrm#2148]
**Describe the bug**
Trying to add account ID to list and details views, following these [instructions](https://forum.espocrm.com/forum/general/36604-display-id-on-account-page?p=36610#post36610).

I can see the new ID field but the values are empty.

**To Reproduce**
1. following these these [instructions](https://forum.espocrm.com/forum/general/36604-display-id-on-account-page?p=36610#post36610)
2. Go to Account list and details
3. Account ID values are blank

**Expected behavior**
Account ID values displayed

**Screenshots**
- Account list:
![image](https://user-images.githubusercontent.com/86238512/141681444-59a3454b-104e-48a3-b698-e9d749df4424.png)

- Account details:
![image](https://user-images.githubusercontent.com/86238512/141681457-aea600ee-2132-43f9-94d0-c6874940a81e.png)

**EspoCRM version**
Same behavior on
- 5.7.11
- 7.0.8 docker-compose from [docker hub](https://hub.docker.com/r/espocrm/espocrm)

**Additional context**

- /var/www/html/custom/Espo/Custom/Resources/layouts/Account/list.json
```json
[
    {
        "name": "name",
        "link": "false"
    },
    {
        "name": "ID",
        "link": "false"
    },
    {
        "name": "website",
        "width": 25,
        "notSortable": true
    },
    {
        "name": "type",
        "width": 16
    },
    {
        "name": "billingAddressCountry",
        "width": 18
    },
    {
        "name": "billingAddressCity"
    }
]
```

- /var/www/html/custom/Espo/Custom/Resources/layouts/Account/detail.json
```json
[
    {
        "label":"Overview",
        "rows": [
            [{"name":"ID"}],
            [{"name":"name"}, {"name":"website"}],
            [{"name":"emailAddress"},{"name":"phoneNumber"}],
            [{"name":"billingAddress"},{"name":"shippingAddress"}]
        ]
    },
    {
        "label":"Details",
        "rows": [
            [{"name":"type"},{"name":"industry"}],
            [{"name":"description","fullWidth": true}]
        ]
    }
]
```

**Comment by yurikuzn** [comment]
Did you try "id"? "ID" is off the naming convention.

**Comment by chirabino** [comment]
@yurikuzn you are right, replacing `ID` with `id` works. Thanks
