### ISSUE TITLE
Error 500 when I want to save changes

### ISSUE THREAD

**Issue by MANEnterprise-Joseph** [espocrm/espocrm#2151]
Whenever I change something from the UI I am getting Error 500 that isn't logging. When I checked out my Cpanel's Terminal the following error code was found:

llegal length modifier specified 'f' in s[np]printf call in /home/nd5563d4/public_html/MyEspo/application/Espo/Core/Utils/File/Manager.php on line 344

PHP version: 7.4.25
Apache: 2.4.51
MySQL: 10.3.32-MariaDB-log

**Note:** After I get the error nothing is showing in the log file and sometimes when I refresh Espo after I save and get the error, the change that gave the Error actually occurs

**Comment by yurikuzn** [comment]
There are a lot of results in google for this error message (not related to Espo) I didn't find any answer. Usually upgrading PHP helps. Might be an issue with hosting provider. I don't know.
