### ISSUE TITLE
Field Level ACL does not control access to attachments

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2152]
**Describe the bug**
An attachment that is linked to an entity via a field that has been set read = no in ACL for the user can still be accessed.

**To Reproduce**
1. Add an attachment multiple field to Account
2. Create a portal role and user where Account is Read = Yes but the new field is Read = No
3. Portal user can access attachments through the entry point that are linked to the account even though the field read level access = No
https://Domain/?entryPoint=image&id=5559adb3c4a927337&portalId=555918fb496ecc158

**Expected behavior**
Attachment should not be accessible if the field is not readable to the user.

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
Thanks. The fix: https://github.com/espocrm/espocrm/commit/6207c8f547a2157b30d4639cdb79c9802d4b6837
