### ISSUE TITLE
Template manager only saves en_US templates

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2153]
**Describe the bug**
When logged in as a user that is using a language other than en_US updating a template saves to en_US instead of the current users language.

**To Reproduce**
1. Update user to have Bulgarian as language in preferences
2. Update any template and save
3. Template updates saved to custom/Espo/Custom/Resources/templates/TEMPLATENAME/en_US

**Expected behavior**
Should save to custom/Espo/Custom/Resources/templates/TEMPLATENAME/bg_BG

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
What is default language in Administration > Settings? Template manager does not use a user language by design.

**Comment by boydle** [comment]
It is the default language. en_US

This is a bit confusing to a user. Is is possible to add the language pick to templates like in label manager this would make it much more functional.

**Comment by yurikuzn** [comment]
I'm not sure. By design all templates supposed to be in the default language only. User language should never be used when the system email is used.

**Comment by yurikuzn** [comment]
So picking the language will add more confusion. As other than system language won't ever be used.

**Comment by boydle** [comment]
I was thinking password reset, 2fa code emails and others where you know the user who is being sent the email

**Comment by yurikuzn** [comment]
Are those translated are sent in user's language?

**Comment by boydle** [comment]
Yes I was thinking they should be sent in the users language when it is know.

**Comment by yurikuzn** [comment]
They are in the default language now.
