### ISSUE TITLE
Duplicated Assigned User field for all entities

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2155]
**Describe the bug**
I am not sure if this is a bug or not but i noticed that on all entities there is a duplicated Assigned User.

**To Reproduce**
Go to any entity:
1. check side panel fields (you will be able to see two field for Assigned User
...

**Expected behavior**
I expect to find only one Assigned User field.

**Screenshots**
<img width="1280" alt="Screenshot 2021-11-23 at 03 05 14" src="https://user-images.githubusercontent.com/19490674/142961671-d69f4f7f-d8e3-44c6-8521-cfc41dffc428.png">
<img width="1280" alt="Screenshot 2021-11-23 at 03 06 12" src="https://user-images.githubusercontent.com/19490674/142961675-9ec9e680-3aa0-4a49-a1e8-0522372e9989.png">

**EspoCRM version**
Version 7.0.8

**Comment by yurikuzn** [comment]
It's not a bug. It's a placeholder for both assigned user and assigned users fields (if the later exists).

**Comment by boydle** [comment]
It can be hard to identify different fields when they have the same label. Would it be possible to get a mouse over showing the field name?
