### ISSUE TITLE
Multiple bool filters can cause duplicate records being fetched

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2156]
**Describe the bug**
Create a new bool filter on Meeting. It does not matter what it is. If you have the new filter and the standard Only My filter selected together the API returns the same meeting for each user who is assigned to it. 

**To Reproduce**
1. Create a new bool filter on Meeting. 
2. Create a meeting with more than one user as attendee
3. Select the new bool filter in the UI and the Only My filter together
4. For each employee on the returned records the API returns a copy of the record. This makes the UI show the wrong count. 

**Expected behavior**
The API should not return the same record more than once

**EspoCRM version**
7.0.8

**Additional context**
The issue seems to be around the join being done in the Only My Filter for Meeting.

Sample result from API:

```json
{
	"total": 6,
	"list": [
		{
			"id": "619dd77375f96ae8b",
			"name": "C",
			"status": "Planned",
			"dateStart": "2021-11-24 06:00:00",
			"dateStartDate": null,
			"parentId": null,
			"parentType": null,
			"parentName": null,
			"createdById": "2",
			"assignedUserId": "2",
			"assignedUserName": "Admin"
		},
		{
			"id": "619dd77375f96ae8b",
			"name": "C",
			"status": "Planned",
			"dateStart": "2021-11-24 06:00:00",
			"dateStartDate": null,
			"parentId": null,
			"parentType": null,
			"parentName": null,
			"createdById": "2",
			"assignedUserId": "2",
			"assignedUserName": "Admin"
		},
		{
			"id": "619dd55191673e567",
			"name": "A",
			"status": "Planned",
			"dateStart": "2021-11-24 06:00:00",
			"dateStartDate": null,
			"parentId": null,
			"parentType": null,
			"parentName": null,
			"createdById": "2",
			"assignedUserId": "2",
			"assignedUserName": "Admin"
		},
		{
			"id": "619dd55191673e567",
			"name": "A",
			"status": "Planned",
			"dateStart": "2021-11-24 06:00:00",
			"dateStartDate": null,
			"parentId": null,
			"parentType": null,
			"parentName": null,
			"createdById": "2",
			"assignedUserId": "2",
			"assignedUserName": "Admin"
		},
		{
			"id": "619dd55191673e567",
			"name": "A",
			"status": "Planned",
			"dateStart": "2021-11-24 06:00:00",
			"dateStartDate": null,
			"parentId": null,
			"parentType": null,
			"parentName": null,
			"createdById": "2",
			"assignedUserId": "2",
			"assignedUserName": "Admin"
		},
		{
			"id": "619dd55191673e567",
			"name": "A",
			"status": "Planned",
			"dateStart": "2021-11-24 06:00:00",
			"dateStartDate": null,
			"parentId": null,
			"parentType": null,
			"parentName": null,
			"createdById": "2",
			"assignedUserId": "2",
			"assignedUserName": "Admin"
		}
	]
}
```

**Comment by boydle** [comment]
Sample filter on Status 


`<?php


namespace Espo\Modules\Custom\Classes\Select\Meeting\BoolFilters;

use Espo\Core\Select\Bool\Filter;
use Espo\ORM\Query\SelectBuilder;
use Espo\ORM\Query\Part\Where\OrGroupBuilder;
use Espo\ORM\Query\Part\Condition as Cond;

class Planned implements Filter
{
    public function apply(SelectBuilder $queryBuilder, OrGroupBuilder $orGroupBuilder): void
    {
        $orGroupBuilder->add(
            Cond::equal(
                Cond::column('status'),
                'Planned'
            ),
        );
    }
}
`

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/f8fd222e255fe0c93fa8ee6b12bbcb92372ade7b

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/f8fd222e255fe0c93fa8ee6b12bbcb92372ade7b

**Comment by hozza** [comment]
This also (still) happens when querying the API for leads using the "where" filters with "or". 

e.g. 
```json
[
  {
    "type": "equals",
    "attribute": "deleted",
    "value": false
  },
  {
    "type": "or",
    "value": [
      {
        "type": "equals",
        "attribute": "emailAddress",
        "value": "info@example.com"
      },
      {
        "type": "equals",
        "attribute": "accountName",
        "value": "foobar"
      },
      {
        "type": "equals",
        "attribute": "name",
        "value": "foo mctest"
      },
      {
        "type": "equals",
        "attribute": "phoneNumber",
        "value": "123"
      }
    ]
  }
]
```

This will return duplicate results with the same ID (2) in the API response when email is matched.

Is this a related issue, and so should be applied to all API endpoints or should it be a new issue?

**Comment by yurikuzn** [comment]
Might be a new issue. Any help with investigation would be appreciated.
