### ISSUE TITLE
Multiple assignedUsers feature produce error 500

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2158]
<img width="1280" alt="assignedUser still show as required although it is no longer required" src="https://user-images.githubusercontent.com/19490674/143292468-f1188e59-c74a-4625-a6d2-8133e434de5c.png">
<img width="1280" alt="creating new account with multiple assigned  users" src="https://user-images.githubusercontent.com/19490674/143292477-fb2e66ef-31e4-4fb4-9e8b-c6e5c72d9c66.png">
<img width="1280" alt="making original AssignedUser not required" src="https://user-images.githubusercontent.com/19490674/143292481-7ab8814a-0473-4d80-a020-9987d0d6d293.png">
<img width="1280" alt="Setting for new multiple assugned users" src="https://user-images.githubusercontent.com/19490674/143292482-cfeafa5c-5d60-49b9-bedb-b3e5c3c57ecb.png">
**Describe the bug**
With the new placeholder (assignedUser) in which holds assigned user or assignedUsers if the later exist. I have tried the experiment to assign multiple users to the account entity created the necessary relationship as per documentation here 👉 https://docs.espocrm.com/administration/multiple-assigned-users/#multiple-assigned-users when tried to create a new account and assign multiple users the system produce error 500. But as soon as i remove the relationship everything works fine again.

**To Reproduce**
1. create a (M:M) relationship between account and user as per documentation here 👉 https://docs.espocrm.com/administration/multiple-assigned-users/#multiple-assigned-users
2. add the new field (Users) and remove assignedUser / make assignedUser not required. 
3. try to create a new account with multiple assigned users by selecting multiple users through the new (users field)
...

**Expected behavior**
i would expect the system to allow to save the record without any issues and accept the new multiple assigned users field to allow to attach multiple user to an account.

**Screenshots**

**EspoCRM version**
version 7.0.8

**Comment by yurikuzn** [comment]
Please provide errors from the log.

**Comment by rabiibrahimi** [comment]
Checked the log and found out that the issue was with some code in forumla. All is working like a charm now.

Sorry for any inconvenience 🙏

Many thanks
