### ISSUE TITLE
Parent fields Entity list to be customizable

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#216]
I dont know if this is a global requirement, but I needed it in my application, and achieved it  by manual editing the Task.json and works fine.

But I thought that making it editable from the entity manager is easy to be done

```json
"parent": {
    "type": "linkParent",
    "entityList": ["Account", "Contact", "Lead", "Opportunity", "Case", "Project"]
},
```

![image](https://cloud.githubusercontent.com/assets/2862528/18119394/114835ac-6f63-11e6-885b-dcf583b9bd16.png)

**Comment by yurikuzn** [comment]
It's available in Entity Manager on editing Parent field.

**Comment by ayman-alkom** [comment]
Yes I just found it

**Comment by ayman-alkom** [comment]
but one min, it is not editable in the Case entity
