### ISSUE TITLE
Calendar position problem

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2160]
Sometimes calendar is not positioned correctly and being cut on Horizontal skin.

![2021-11-27 (1)](https://user-images.githubusercontent.com/14265370/143718581-6d890d41-1471-41a6-bf68-d95e07d9b045.png)

**Comment by rodrigoscoelho** [comment]
Yes, I'm having this same problem. Thanks for reporting.



Em sáb., 27 de nov. de 2021 às 15:48, rutkas ***@***.***>
escreveu:

**Comment by yurikuzn** [comment]
Forced it to be placed always down, that should fix the issue.
