### ISSUE TITLE
Can't add opt-out link

### ISSUE THREAD

**Issue by ruzzzz6312** [espocrm/espocrm#2162]
Hi! Please excuse me if that's my config error, I can't add opt-out link.

Version 7.0.8
Steps to reproduce:
1. Create a template (in the folder/category)
2. Add opt-out link/ur/button, nothing works

Screenshots attached:
<img width="1114" alt="Screen Shot 2021-11-29 at 4 11 41 PM" src="https://user-images.githubusercontent.com/23564850/143962616-f986cc3c-13da-4859-bc9e-b1f036c32ee9.png">
<img width="836" alt="Screen Shot 2021-11-29 at 4 14 38 PM" src="https://user-images.githubusercontent.com/23564850/143962680-fec9a0bd-168f-486d-a90b-ba06b66812da.png">

**Comment by ruzzzz6312** [comment]
And may I ask you kindly a second question?
How do I create an email manually in mysql DB, is there any table that is read by the ESPO core and sends emails?

**Comment by yurikuzn** [comment]
Opt-out links only works in mass email. Is it a mass email or regular?

**Comment by ruzzzz6312** [comment]
Regular one, I thought they work in regular emails, sorry for bothering.

btw, is there a way to create an email manually in DB or invoke some function/script to send email and relate it to all entities?
