### ISSUE TITLE
recordDefs metadata gives varying results

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2164]
**Describe the bug**
recordDefs metadata mass action disabling gives odd results

**To Reproduce**
setting an action to allowed: false does not work for custom entity has to be set to disabled: true

**Expected behavior**
Having an allowed and a disabled param is confusing but since they are both provided:
allowed: false should work the same as disabled:true 

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
Not bug. In Espo we avoid true by default.

**Comment by boydle** [comment]
Thanks for the clarification
