### ISSUE TITLE
SVG Image does not show preview for Image field

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2165]
**Describe the bug**
Image field does not preview image if the image is an SVG

**To Reproduce**
1. Add an image field to Account
2. Add the field to the Account Detail view
3. Edit an account and add an SVG image
4. Expect image to be visible to preview same as JPEG.

**Expected behavior**
Expect image to be visible to preview same as JPEG.

**EspoCRM version**
7.0.8

**Additional context**
The image is loaded back but the UI seems to be sizing it at 0px

**Comment by yurikuzn** [comment]
Could not reproduce. Maybe provide an image.

**Comment by yurikuzn** [comment]
Could be also an env issue, that PHP GD can't convert the image.

**Comment by boydle** [comment]
I made the edit on the main demo env please see this record. If you edit you can see the SVG but just viewing it is not visible: https://demo.us.espocrm.com/#Account/view/61a716043a75b4776
[aa.zip](https://github.com/espocrm/espocrm/files/7631602/aa.zip)

**Comment by yurikuzn** [comment]
I tried my SVG there and it worked. Any help with investigation and fix will be appreciated. Can you upload the image here?

**Comment by boydle** [comment]
It is attached in previous message as aa.zip I could not directly upload an SVG

**Comment by yurikuzn** [comment]
Seems the browser does not render it because it's too big.

**Comment by boydle** [comment]
If you edit the record the image preview is displayed. Seems odd the browser would not render in 1 mode vs another mode.

**Comment by yurikuzn** [comment]
Your image can't be rendered inside `inline-block` elements.

Minimal code to reproduce:

```html
<div style="display: inline-block;">
	<img src="aa.svg">
</div>
```

I don't know the reason why it can't be rendered.

**Comment by boydle** [comment]
I was trying to replicate an issue that was referred to me and I just grabbed the first SVG I could find. It seems to occur with a range of SVG's. 

Are you able to provide your sample SVG that works and I will take a look.

**Comment by yurikuzn** [comment]
[Disney_wordmark.svg.zip](https://github.com/espocrm/espocrm/files/7632931/Disney_wordmark.svg.zip)

**Comment by yurikuzn** [comment]
It requires redesigned html layout for attachment container.  The problem seems is with large SVG that can't be rendered inside inline-block elements where there is max-width.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/a060f0732b30dc51517be03edb415a79a3a07c2e

**Comment by boydle** [comment]
Thanks Yuri
