### ISSUE TITLE
(ORM) adding where clause with OR statement

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2166]
Previously I could add OR statement to the query, very useful for example while modifying textFilter:

```
protected function textFilter($textFilter, &$result, $noFullText = false)
    {
        parent::textFilter($textFilter, $result);
        if ( !empty($textFilter) ) {
           $result['customWhere'] .= " OR (SELECT.......)"
        }
    }
```

Now since v7 we should use QueryBuilder:

```
    public function apply(QueryBuilder $queryBuilder, Data $data): void
    {
        $filter = $data->getFilter();
        if (!empty($filter)) {
            $queryBuilder
            ->where(....)' => '0'
            ]);
        }
        $this->defaultFilter->apply($queryBuilder, $data);
    }
```

->where is adding clause with AND statement, how to add it with OR ?

using 'OR' => [....] creates OR group by adding whole clause with AND, that gives another result.

**Comment by yurikuzn** [comment]
Not possible, and supposed not to be possible, unfortunately.

**Comment by rutkas** [comment]
Can you advise me please how can I make textFilter to search by another object fields ?

For example I have object Device that is related to Opportunity, and Opp is related to Account. And I want to search in Devices by Account name.

In SelectManager I used:

`$result['customWhere'] .= " OR (SELECT COUNT(*) FROM account, opportunity WHERE account.id = opportunity.account_id AND device.opportunity_id = opportunity.id AND account.deleted = 0 AND opportunity.deleted = 0 AND account.name LIKE '%" . $textFilter . "%') > 0";`

**Comment by yurikuzn** [comment]
Specify a custom text filter class https://docs.espocrm.com/development/metadata/select-defs/#textfilterclassname and then build any query you like.

**Comment by rutkas** [comment]
That was exactly that I did, but I'm stuck with adding where with OR statement

->where is adding AND expression and gives incorrecr result for me.
```
    public function apply(QueryBuilder $queryBuilder, Data $data): void
    {
        $filter = $data->getFilter();
        if (!empty($filter)) {
            $queryBuilder
            ->where(....)' => '0'
            ]);
        }
        $this->defaultFilter->apply($queryBuilder, $data);
    }
```
Or you proposing to build entire query from scratch ?

**Comment by yurikuzn** [comment]
From the scratch. Sorry, but i'm too busy to help.
