### ISSUE TITLE
Slim errors after upgrade 6.1.10 > 7.0.8

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2167]
Server error 500 : Slim error

```
ERROR: Slim Application Error Type: TypeError Code: 0 Message: Return value of Espo\ORM\Defs\FieldDefs::getType() must be of the type string, null returned File: /var/www/crm/application/Espo/ORM/Defs/FieldDefs.php Line: 69 Trace: 
#0 /var/www/crm/application/Espo/Core/FieldProcessing/LinkParent/Loader.php(73): Espo\ORM\Defs\FieldDefs->getType() 
#1 /var/www/crm/application/Espo/Core/FieldProcessing/LinkParent/Loader.php(54): Espo\Core\FieldProcessing\LinkParent\Loader->getFieldList('Mycustomentity') 
#2 /var/www/crm/application/Espo/Core/FieldProcessing/ListLoadProcessor.php(65): Espo\Core\FieldProcessing\LinkParent\Loader->process(Object(Espo\Custom\Entities\Mycustomentity), Object(Espo\Core\FieldProcessing\Loader\Params)) 
#3 /var/www/crm/application/Espo/Core/Record/Service.php(353): Espo\Core\FieldProcessing\ListLoadProcessor->process(Object(Espo\Custom\Entities\Mycustomentity), Object(Espo\Core\FieldProcessing\Loader\Params)) 
```

**To Reproduce**
1. Create custom entity
2. upgrade from 6.1.10 > 7.0.8
3. call https://mydomain/api/v1/Mycustomentity?select=id

ERROR: Slim Application Error Type: TypeError Code: 0 Message: Return value of Espo\ORM\Defs\FieldDefs::getType() must be of the type string, null returned File: /var/www/crm/application/Espo/ORM/Defs/FieldDefs.php Line: 69

_Debug info :_ 
`NOTICE: E_NOTICE: Undefined index: type {"code":8,"message":"Undefined index: type","file":"/var/www/crm/application/Espo/ORM/Defs/FieldDefs.php","line":69} []
`

**Expected behavior**
JSON esponse body with ID 

**EspoCRM version**
7.0.8, 

**Additional context**
Other custom entities do not show this behaviour.

Investigating.

**Comment by yurikuzn** [comment]
Please debug your error. It could be you have a field w/o type in metadata.

**Comment by analystcmyk** [comment]
Correct. Not sure how this could have happened, the file was only touched via GUI.
