### ISSUE TITLE
Extending Filter Factory

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2169]
**Is your feature request related to a problem? Please describe.**
I want to add a new global bool filter "Created by me"

**Describe the solution you'd like**
A way to define extended Filter factory, or just let the current Filter factory scan Modules & Custom for matched filters implementations [here](https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Select/Bool/FilterFactory.php#L107)

**Comment by eymen-elkum** [comment]
Managed to solve this using the **binding to factory** here:
https://docs.espocrm.com/development/di/#binding-to-factory

Here is the example:

```
<?php

namespace Espo\Modules\GFilters;

use Espo\Core\Binding\Binder;
use Espo\Core\Select\Bool\FilterFactory as EspoFilterFactory;
use Espo\Modules\GFilters\Core\Select\Bool\FilterFactory;

class Binding
{
    public function process(Binder $binder): void
    {
        $binder->bindFactory(EspoFilterFactory::class, FilterFactory::class);
    }
}
```

**Comment by yurikuzn** [comment]
I think I will add the ability to define a custom global filter via metadata.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f482c41e6c46872728ca287cf7ac6172712e05d1
