### ISSUE TITLE
Error: Unknown database type enum requested

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#217]
In fact this error happened in an old project, I don't know what exactly made it happened.

this error happens now when I want to rebuild the database from the admin panel, after a small [search ](https://wildlyinaccurate.com/doctrine-2-resolving-unknown-database-type-enum-requested/)I found that it is related to Doctrine lib.
I fixed it by manually add the enum type to the schema, but I dont know if my update to [this function ](https://github.com/espocrm/espocrm/blob/2ca40a6b4e11053250ae8ec65f5ed5fab9af91dc/application/Espo/Core/Utils/Database/Schema/Schema.php#L158)is the best way or not.

```php
    protected function initFieldTypes()
    {
        $databasePlatform = $this->getConnection()->getDatabasePlatform();
        foreach ($this->fieldTypePaths as $path) {
            .............
            .............
        }

        if (!$databasePlatform->hasDoctrineTypeMappingFor('enum')) {
            $databasePlatform->registerDoctrineTypeMapping('enum', 'string');
        }
    }
```

**Comment by ayman-alkom** [comment]
I hust wanted to share the case with you (because it may general case), but up to me it is fixed.

**Comment by tmachyshyn** [comment]
Actually, Espo rewrites the 'enum' type to 'varchar'. Perhaps, you have created some custom type. Can you write the code of metadata which causes the issue.

**Comment by ayman-alkom** [comment]
No, I didn't make a new custom type (I think). I just using an own [plugin ](https://github.com/ayman-alkom/EspoDataGrid)that produce a new field type.
