### ISSUE TITLE
Bug In steps Install => Database configuration. 

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2174]
In steps Install => Database configuration.
version git master
 
Host Name : localhost:3307

Got an error in file : application\Espo\Core\Utils\Database\Helper.php

private function createDatabaseParams(array $params): DatabaseParams
    {
        $databaseParams = DatabaseParams::create()
            ->withHost($params['host'] ?? null)
            **_->withPort(isset($params['host']) ? (int) $params['host'] : null)  <====== change "host" to "port"_**

I doing it right. ?
please check.

**Comment by tmachyshyn** [comment]
Fixed, https://github.com/espocrm/espocrm/commit/28c4b8ea054040d76d9fbf57727063cf7decf479.
Thanks for reporting.
