### ISSUE TITLE
Provide parser & importer to constructor

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2177]
**Describe the bug**
It is more to be improve rather than bug

**Expected behavior**
I expect the parser & imported to be provided by constructor  and can be override by binder

**EspoCRM version**
7.0.8

**Additional context**
[Lines here](https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/EmailAccount.php#L299)

    protected function createParser(): Parser
    {
        return $this->injectableFactory->create(ParserFactory::class)->create();
    }

    protected function createImporter(): Importer
    {
        return $this->injectableFactory->create(Importer::class);
    }

**Comment by yurikuzn** [comment]
It requires moving all the logic to another class (e.g. somewhere in Tools). As the class extends Record class and constructor is problematic to override.

**Comment by yurikuzn** [comment]
The email fetching functionality  will be refactored in v7.1.
