### ISSUE TITLE
Bug In steps Install => Database configuration.

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2179]
**Describe the bug**
Bug In steps Install => Database configuration.
Can't create database if not exists

**To Reproduce**
1. In file config-internal.php
 'database' => [
    'driver' => 'pdo_mysql',
    'host' => 'localhost',
    'port' => '3307',
    'charset' => 'utf8mb4',
    'dbname' => 'espocrmdev' <= not empty
  ]

2. Database no have db name 'espocrmdev' 
3. click Test Connection return 'Unknown database' 

**Expected behavior**
happened when i delete database and reinstall 

**EspoCRM version**
git master

**Additional context**
Got an error in file : install\core\Installer.php

`

    public function checkDatabaseConnection(array $params, bool $createDatabase = false)
    {
        try {
            $pdo = $this->getDatabaseHelper()->createPdoConnection($params);
        }
        catch (Exception $e) {
            if ($createDatabase && $e->getCode() == '1049') {
                $modParams = $params;

                unset($modParams['dbname']);

                $pdo = $this->getDatabaseHelper()->createPdoConnection($modParams);
                **_------------stop working---------------_** 
                $pdo->query("CREATE DATABASE IF NOT EXISTS `". $params['dbname'] ."`");

                return $this->checkDatabaseConnection($params, false);
            }

            throw $e;
        }

        return true;
    }

`

please check in file : application\Espo\Core\Utils\Database\Helper.php

`

I doing it right. ?
please check.

    public function createPdoConnection(array $params = [])
    {
        $defaultParams = [
            'driver' => 'pdo_mysql',
        ];

       **_=========Add isset($params['dbname']) ===============_**
        if (isset($params['dbname']) && isset($this->config) && $this->config instanceof Config) {
            $defaultParams = array_merge(
                $defaultParams,
                $this->config->get('database')
            );
        }

        $params = array_merge(
            $defaultParams,
            $params
        );

        $pdoProvider = new DefaultPDOProvider(
            $this->createDatabaseParams($params)
        );

        return $pdoProvider->get();
    }

`

**Comment by tmachyshyn** [comment]
Thanks for reporting. The fix, https://github.com/espocrm/espocrm/commit/8a15278af20e3d370a715b13d7c6165c2e4a5b46.
