### ISSUE TITLE
Forward email will not duplicate the inline attachments 

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2181]
**Describe the bug**
Forward email will not duplicate the inline attachments, so the new email users will not be able to see the new forwarded email attatchments.

**To Reproduce**
Just forward an email with inline attachment and include new users not exist on the original email.

**Expected behavior**
I expect the new email inline attachments to be accessible by the users who have access to the new email.

**EspoCRM version**
Espo 7.0.8

**Additional context**
There is a function of copy the attatchments field, would be a suggestion to add another function to copy the inline attachments and replace IDs on the forwarded body.

**Another suggestion was to improve attachments so we have a new table named "attachment_entity", this will be great improvement and will make us able to link any attachment easily to multiple entities at the same time.**

NOTE: We are ready to contribute if you give us what is the best way you prefer.

**Comment by yurikuzn** [comment]
Incorporating `attachment_entity` is not an option for a hotfix release.

Do you have an idea where to put the code to copy inline attachments?

We need the fix for both Reply and Forward I guess.

**Comment by yurikuzn** [comment]
An idea. On save, https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/FieldProcessing/Wysiwyg/Saver.php, check all inline attachment entities, if the related record id does not equal the id of the current record, then duplicate the attachments. But it will have a performance impact.

**Comment by eymen-elkum** [comment]
There is already a request that copy the main attachments here: 

https://github.com/espocrm/espocrm/blob/d0de9e5bb9cf8e9b4423070c6c06cb847b8b59f0/client/src/views/email/detail.js#L466

I suggest to have an additional request that copy the inline attachments or just improve the existing one to cover the inline attachments, then will return 2d array instead of flat IDs (key,value) the key will be the key attachemnt Id and value is the copied attachment.

**Comment by yurikuzn** [comment]
It would be much more complicated, requiring some logic in front-end. Changing existing API is not good. `getCopiedAttachments` exists not only for Email entity.

**Comment by yurikuzn** [comment]
I investigated the problem a big. I think I will address this to 7.1 version.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/d57098dd506585396fc1a96ebfa47618ac15fa6f
