### ISSUE TITLE
imageTag renderer not working with Aws S3 set as storage provider

### ISSUE THREAD

**Issue by jflores1** [espocrm/espocrm#2188]
**Describe the bug**
I described the issue (with screenshots) here: https://forum.espocrm.com/forum/developer-help/48021-how-do-i-refer-to-one-image-id-in-imageids-in-template#post77747 

When the default storage provider is set as AwsS3, images attached to an Entity when "Print to PDF" don't render.

**To Reproduce**
1. Set default storage to Aws
2. Create PDF template that renders an image attached to an entity
3. Image doesn't render
4. Reset storage to default file system
5. Attach a new image to entity & click "Print to PDF"
6. Image renders
...

**Expected behavior**
I'd expect an image to render inside a PDF regardless of storage provider.

**Screenshots**
See attachments here: https://forum.espocrm.com/forum/developer-help/48021-how-do-i-refer-to-one-image-id-in-imageids-in-template#post77747 

**EspoCRM version**
7.0.8

**Additional context**
PHP 7.4.3 (cli) (built: Oct 25 2021 18:20:54) ( NTS )
Server version: Apache/2.4.41 (Ubuntu)

**Comment by yurikuzn** [comment]
Could not reproduce. Worked fine.

**Comment by michelrothgaenger** [comment]
Hi @yurikuzn,

I guess I have the same issue. No image is rendered, tried with png and jpg. The documents are rendered but all images are missing although I can see them in the template. Storage location is also S3. EspoCRM 7.2.4. Do you have any other idea?

**Comment by yurikuzn** [comment]
Hi,

I'm too busy, if you manage to find out, please let us know.
