### ISSUE TITLE
field multiEnum allowCustomOptions not working with dynamic logic

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2189]
**Describe the bug**
Field multiEnum allowCustomOptions not working with dynamic logic.

version git master

**To Reproduce**
1. create field multiEnum;
2. setting allowCustomOptions = true;
3. setting dynamic logic Conditional options.

On Create view:

Create Custom Options value to filed multiEnum and select. After that custom value missing.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/d5f42a46b3c2b702bf3b78f5d31c9a051739f334
