### ISSUE TITLE
Wysiwyg field: Supporting image pasting

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2190]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c7fe7ac01408cac4453a70c305b65db8bd389806

**Comment by o-data** [comment]
Not sure if this is a good or bad thing. 

As far as I know the current image paste is pretty good.

**Comment by eymen-elkum** [comment]
> Not sure if this is a good or bad thing. 
> 
> As far as I know the current image paste is pretty good.

I confirm that paste was working properly, now the paste made uploading to run twice.

**Comment by yurikuzn** [comment]
onImageUpload callback was not firing when pasing image. Maybe related to the chrome version
