### ISSUE TITLE
Make the account name field non-unique

### ISSUE THREAD

**Issue by ykyuen** [espocrm/espocrm#2191]
Hello,

i am new to espocrm and i have a question on the Account entity. I found that i cannot create account with the same name of other existing account. Is there anyway i could make this field non-unique?

Thanks.

**Comment by yurikuzn** [comment]
Hi,

Please use our forum for such question. Regards.

https://forum.espocrm.com/

**Comment by yurikuzn** [comment]
Actually, accounts can be created w/ a same name out-of-the-box.
