### ISSUE TITLE
SMS status values not being updated after sending

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2192]
**Describe the bug**
Using the new SMS interface and the Twilio provider sending SMS does not update SMS record status

**To Reproduce**
1. Create a formula with the following logic:

$smsId = record\create(
    'Sms',
    'to', '+UPDATE TO VALID NUMBER',
    'body', 'This is a test.'
);
ext\sms\send($smsId);

2. Trigger the formula
3. Check SMS status value it is Archived but should be Sent.

Doing the same test with an invalid phone number should update the status to Failed it does not.

**Expected behavior**
Success or Failure in sending should update the record status.

**EspoCRM version**
7.0.9

**Additional context**
Espo\Core\Sms\SmsSender.php has a call to update record to sent: $sms->setAsSent(); but no save occurs.
For failures nothing seems to occur.

**Comment by yurikuzn** [comment]
The `save` call should be added to the formula function implementation. SmsSender should not save an entity.

**Comment by boydle** [comment]
For an error when exceptions are being thrown the formula will not be able to do the save. how can this be handled?

**Comment by yurikuzn** [comment]
This needs to be added here: https://github.com/espocrm/espocrm/blob/7.0.8/application/Espo/Core/Formula/Functions/ExtGroup/SmsGroup/SendType.php#L79

If you can provide a PR it would be great as I'm busy with other stuff at this moment.

**Comment by yurikuzn** [comment]
I will fix it but won't be able to test for a while as I don't have access to needed environment. Could you help with testing?

**Comment by boydle** [comment]
Yes happy to test it.

**Comment by yurikuzn** [comment]
Here's the fix: https://github.com/espocrm/espocrm/commit/a730f47ceb7642c4faeea7d42a5f077ac5b8f5ee

**Comment by boydle** [comment]
I have tested this and the record is updated to Failed and saved as expected

**Comment by yurikuzn** [comment]
Thanks.
