### ISSUE TITLE
The mailto link is not replaced by the javascript function to call internal email client (since v7)

### ISSUE THREAD

**Issue by libremaster** [espocrm/espocrm#2194]
Before upgrade to v7, when I clicked on an email inside text field, an internal email client was launched.
But now, it launch external email client.

Inside my profile, there is a stream frame with posts. I joined a screenshot.
If i click on the email, internal email client is not launched.

![bug-espo](https://user-images.githubusercontent.com/55919603/148350967-47643552-2d6b-4491-bbe8-1245195bf0ae.png)

Inside my parameters, the option to launch external client is not checked and there is not parameter to force external email client.
With espocrm v6, it worked. But with v7, no.

**Comment by yurikuzn** [comment]
I can't reproduce. It works for me.

I don't understand this "the option to launch external client is not checked and there is not parameter to force external email client".

**Comment by libremaster** [comment]
Inside JS, there is : 

`
if (
                this.getConfig().get('emailForceUseExternalClient') ||
                this.getPreferences().get('emailUseExternalClient') ||
                !this.getAcl().checkScope('Email', 'create')
            )
`

So I checked emailUseExternalClient : 
![Capture d’écran du 2022-01-11 11-19-18](https://user-images.githubusercontent.com/55919603/148925674-2cb077a9-2c02-4a64-a213-253547276fdb.png)

In others parts of EspoCRM, if e-mail is alone in a e-mail field (and not text field), it works.
I will try to check where exactly is the problem but espo.min.js is compressed and I need to switch in developper mode and then something is not working :-)

**Comment by yurikuzn** [comment]
Reproduced. The bug appeared in 7.0.5 version. Here's the fix: https://github.com/espocrm/espocrm/commit/5dcfbf00d2e3eaa4f9e1255c42c209442ee12a8e

**Comment by libremaster** [comment]
Thank you !!! My god !

Have a good day :-)
