### ISSUE TITLE
notStorable on field type link does not work

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2195]
**Describe the bug**
notStorable on field type link gives an SQL error when retrieving the record

DEBUG: API (42S22) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'my_entity.not_stored_team_id' in 'on clause'; GET /MyEntity/61da694b883060410; Route pattern: /{controller}/{id}; Route params: Array (     [controller] => MyEntity     [action] => read     [id] => 61da694b883060410 )  [] []

**To Reproduce**
1. create a link field and set it to notStorable 
2. add the non stored link field to the UI for this entity
3. View entity

**Expected behavior**
No Error should be displayed. SQL should not be trying to retrieve the fields related to the notStorable link field
notStorable property should work for link fields.

**EspoCRM version**
7.0.8

**Additional context**
Adding the Id and Name fields for the non storable link field also as not storable made no difference

{
    "fields": {
        "notStoredTeam": {
            "type": "link",
            "notStorable": true
        },
        "notStoredTeamId": {
            "type": "varchar",
            "notStorable": true
        },
        "notStoredTeamName": {
            "type": "varchar",
            "notStorable": true
        }
    },
	"links": {
        "notStoredTeam": {
            "type": "belongsTo",
            "entity": "Team",
            "readOnly": true
        }
	}
}

**Comment by yurikuzn** [comment]
It works w/o the link at least. You should not create the link if you have a not-storable field.

**Comment by kczereczon** [comment]
@yurikuzn what you mean by "w/o the link" i need to create dynamic relation with foregin field feature, but related object is changed depends on who is exploring entity and same issue occures, it's seems to ORM don't recognize "notStorable" param and tries to fetch it from database instead of future filling data via loadAdditionalField method in Service

**Comment by yurikuzn** [comment]
It's not ORM logic. And it's not a bug. When you create the link named `myLink`, it will create the attribute `myLinkId`. It will override your created `myLink` field. Please consider finding workaround for such situations.

**Comment by yurikuzn** [comment]
Possible workaround: name your link field differently.
