### ISSUE TITLE
selectPrimaryFilterName in relationship panel not working

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2196]
ver 7.0.8
We have relation panel in ProductModel object with default filter:
```
    "relationshipPanels": {
      "devices": {
        "view": "custom:views/productmodel/record/panels/devices",
        "select": true,
        "create": false,
        "selectPrimaryFilterName": "freeDevs"
      }
    },
```
Filter freeDevs is described in Espo/Custom/Classes/Select/Device and in Espo/Custom/Resources/metadata/selectDefs/Device.json and it is working in record list of Device object directly.

In relationship panel of ProductModel object filter "freeDevs" is selected but NOT applied.

**Comment by yurikuzn** [comment]
Should it be applied? I recommend debugging as it's not a documented feature.

**Comment by rutkas** [comment]
> Should it be applied? I recommend debugging as it's not a documented feature. I believe it's not supposed to be applied.

Yes, it should be applied, because it was applied before this crazy 7.x version

**Comment by yurikuzn** [comment]
First, you should describe the issue more clear. No need to use worlds like 'crazy 7.x' version here. I don't enjoy it.

The statement `In relationship panel of ProductModel object filter "freeDevs" is selected but NOT applied.` for me is ambiguous. That's why why have the issue template here as more than 50% of bug-reports are false.

**Comment by yurikuzn** [comment]
I made some tests, and the feature worked as expected.

**Comment by rutkas** [comment]
> First, you should describe the issue more clear. No need to use worlds like 'crazy 7.x' version here. I don't enjoy it.

Sorry for that, you do a great job. But ver7 killed all customizations that were made before and now I wasted 2 month
 to explore new version and rewrite everything I made before.

Backward compatibility for customizations is a big problem of this update. I continue to find more new issues in this update. Actually some of my friends who used Espo do not want to install v7 and not going to do that at all because of these changes. It means that they will need to change Espo to some other projects after some time without updates. But I decided to enjoy this update.

**Comment by yurikuzn** [comment]
Actually, v7 had less issues than some previous major releases. It was not possible to keep 100% bc, with manual customization. And won't be possible to have it in future if customizations are made in non-documented ways. For us, it was not a big problem to migrate everything to v7. I can't imagine it could took 2 months.

**Comment by rutkas** [comment]
> I made some tests, and the feature worked as expected. The filter is selected and applied when you select a record/s.

I will try to show you the problem on screenshots and describe in details on example.

Here is a ProductModel record:
![image](https://user-images.githubusercontent.com/14265370/148735509-07ba93d8-9723-4766-8d71-d58d8d8f4e7f.png)
There's relationship panel with Products. As  you can see filter is selected. But the filter is not applied, cause these records should be filtered out.

Here is how this filter is applied if I click on view list:
![image](https://user-images.githubusercontent.com/14265370/148735908-7a114135-e68a-46d3-aad6-98cf05f754b1.png)
Filter is applied here correctly

I made test on 6 branch with same data and there are no records in this relation panel of Product1 (filter is applied there)

**Comment by rutkas** [comment]
> Actually, v7 had less issues than some previous major releases. It was not possible to keep 100% bc with manual customizations. 

I worked with Espo from v5 and accumulated many customizations from that time, both in backend and client parts. Some of them even through triggers in mysql when customization was not possible without native code patching (a little crazy, but most stable type of changes). I can't imagine how to live without my customizations now.

Passed through all project updates for all this time. I always trying to keep latest software versions on my server. Yes, sometimes I had to fix and adopt code in major releases but this time almost everything crashed.. except stored procedures ;)

**Comment by yurikuzn** [comment]
I ask again and again. Please, be as much explicit as possible when you create an issue.

**Comment by rutkas** [comment]
> selectPrimaryFilterName parameter does not have anything to do with the filters on your screenshot. I recommend to debug.

Sorry, Yuri, you are right. Found the problem in my code after putting more info to error log.
Also found useful param "filterList" in "relationshipPanels".
