### ISSUE TITLE
Export in idle

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2197]
When selected all results (on the list view) and the total number of records is greater than a specific threshold value, then the export will be processed by cron/daemon.

It will allow to export very large numbers of records.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3cb8deab2c172259685c151899f2b47942bfbdc4

**Comment by gustavo-dssi** [comment]
Hello @yurikuzn 
Any news about this improvement? Because, when I try to export a large .xlsx file, it appears "Espo\Tools\Export\Jobs\Process -> Success", but the download doesn't start.

Thank you,
Best Regards

**Comment by yurikuzn** [comment]
It it does not work please report a bug with steps to reproduce. Last time I tried it worked.

**Comment by gustavo-dssi** [comment]
> If it does not work please create a separate issue with all steps to reproduce. Last time I tried it worked.

Hey, @yurikuzn 
I've upped the `memory_limit` value in the php.ini to 2048, and it's all working now.

**Comment by gustavo-dssi** [comment]
I did not. Should I do it?
I will search how to do it so.
Thank you

**Comment by gustavo-dssi** [comment]
Hello, @jeamado 

As suggested by @yurikuzn try to update the parameter in CLI config. 
Actually I didn't seach how to do it yet, but if you found it first, let me know please.

**Comment by yurikuzn** [comment]
If a job is failed because of memory limit, it won't be marked as Failed until some specific time period is passed (like a day or so).  So it's likely a memory limit issue.  PHPSpreadsheet consumes quite a lot of memory, this problem is not related to the logic of this feature.

**Comment by jeamado** [comment]
Hi @yurikuzn 

How much memory then should be allocated? 

My Resources Usage Report shows no limit reached during the export processes. Memory usage stayed very low indeed. So it seems its not a memory limit in my case. Nevertheless other failures happenned during the exports porcesses as shown in the screens below.

![Memory Usage](https://user-images.githubusercontent.com/39569731/168877787-d71f2d42-a074-402c-a8d0-8dcb33711595.JPG)
![Cron Jobs](https://user-images.githubusercontent.com/39569731/168877880-1370c3b0-472f-4625-b9e5-28b90a1b963c.JPG)

**Comment by yurikuzn** [comment]
I don't know. Here's the related issue https://github.com/espocrm/espocrm/issues/2209. This issue is not related to the problem you have.

**Comment by yurikuzn** [comment]
The config parameter name is `exportIdleCountThreshold`, `data/config.php`. Set it to a larger value.

**Comment by yurikuzn** [comment]
As you don't have access to CLI, there's not much can be done to find out why the job is not working. When code is running in CLI (jobs) it uses different PHP configuration. It's really possible that the issue is with memory exceeded. You can also try to log your cron output to a file. It should show errors.

I recommend using hosting providers with CLI access.

**Comment by jeamado** [comment]
> The config parameter name is `exportIdleCountThreshold`, `data/config.php`. Set it to a larger value.

Many thanks @yurikuzn . Is this parameter upgrade safe? Could it be set by the admin panel in future releases?

**Comment by jeamado** [comment]
> As you don't have access to CLI, there's not much can be done to find out why the job is not working. When code is running in CLI (jobs) it uses different PHP configuration, webserver is not used. It's really possible that the issue is with memory exceeded. You can also try to log your cron output to a file. It should show errors.
> 
> I recommend using hosting providers with CLI access.

In my country, where you cannot spend in US dollars because a very high exchange rate, hosting with CLI access is a very-very expensive thing.

Neverheless, I can say that my server has 3GB memory. 

In my country today is hollyday, so I am the only person testing in my CRM. So I tested again with the same 1900 records, running the job for 2 hours, and apparentrly there were not memory issue. 

Should I understand from you, that the metrics shown by cPanel could be different that the actual memory usage?

Thanks a lot for your help and patience!!

Below some images from my cPanel resource usage for todays test:
![Snag_128c37e2](https://user-images.githubusercontent.com/39569731/169073346-f3624d15-4f15-4130-9890-4400b255d36f.png)
![Snag_128c9c39](https://user-images.githubusercontent.com/39569731/169073433-a4f0bd2e-da08-4485-940d-7d6ea357d297.png)
![Snag_128d3414](https://user-images.githubusercontent.com/39569731/169073623-d710dac7-ca3b-4cde-a0ee-4f8d805def97.png)
![Snag_128da1e2](https://user-images.githu
![Snag_128de321](https://user-images.githubusercontent.com/39569731/169073767-8d3fdcd5-1252-4b76-9855-8a82e93f604f.png)
busercontent.com/39569731/169073695-465ba4fa-79bf-4595-92ce-998e1fa86367.png)
![Snag_128e7148](https://user-images.githubusercontent.com/39569731/169073924-acc5b7f0-71c7-46eb-a9e8-aa938a588bb3.png)
![Snag_128f0961](https://user-images.githubusercontent.com/39569731/169074073-80fb1d1b-6da0-4aea-98c4-8bbf4609d96b.png)

**Comment by jeamado** [comment]
> The config parameter name is `exportIdleCountThreshold`, `data/config.php`. Set it to a larger value.

I did not find this paramerer in `data/config.php`, I found it in `application/Espo/Resources/defaults/systemConfig.php` and the changes worked.

**Comment by yurikuzn** [comment]
The parameter should be added to `data/config.php`. https://github.com/espocrm/documentation/blob/master/docs/administration/config-params.md

**Comment by yurikuzn** [comment]
Why not to ask support of your hosting provider . I'm Espo developer and don't know about how your hosting works.

**Comment by jeamado** [comment]
> The parameter should be added to `data/config.php`. https://github.com/espocrm/documentation/blob/master/docs/administration/config-params.md

Before you wrote: The config parameter name is exportIdleCountThreshold, data/config.php. Set it to a larger value.

Well. I understood I had to change something, instead I had to add something.

**Comment by jeamado** [comment]
> Why not to ask support of your hosting provider. I'm Espo developer and don't know about details how your hosting works.

I did ask support from my hosting provider. They did not find any issue. 

Anyway, thanks a lot. Changing the config params was enough info for my issue, and for sure for someone else.

Lastly, you are a great developer. Thanks again.

**Comment by yurikuzn** [comment]
1000 rows XLSX would have affect on the memory usage and it would have be visible on graphs. I assume that your PHP that run by cron has different memory limit parameter. Usually it's set to "unlimited" but your hosting might has it set to something.

**Comment by jeamado** [comment]
> 1000 rows XLSX would have affected on the memory usage and it would have been visible on graphs. I assume that your PHP that run by cron has different memory limit parameter. Usually it's set to "unlimited" but your hosting might has it set to something.

Allright, Iwill talk to my provider about your considerations related to cron memory limit. 

In the meantime I made the changes you reccomended,  and exported 3135 rows to xlsx. Espo lasted 5 seconds in download the file directly. Memory usage graphs did not show any inconvenience nor any fault. This solution works fine for my case.
