### ISSUE TITLE
 PHP8.1 Support

### ISSUE THREAD

**Issue by DoM1niC** [espocrm/espocrm#2198]
**Describe the bug**
Can't Login since PHP 8.1

**To Reproduce**
1. Install PHP8.1 fallback to PHP8.0 works

**Expected behavior**
EspoCRM don't login

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
Espo 8.1 is not fully compatible with PHP8.1 yet.

**Comment by yurikuzn** [comment]
Any help with fix appreciated.

**Comment by DoM1niC** [comment]
yeah LDAP is not the problem legacy login doesn't work too.... I think a class of EspoCRM seems be fixed like some is deprecated, I'm not so fit in advances PHP coding :(

**Comment by yurikuzn** [comment]
I believe it's already fixed in hotfix branch.
