### ISSUE TITLE
Email sending error

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2204]
It is an error while sending email. To reproduce go to Email - > new message, write recipient email address and subject. then click send.

If I click to send one more tim after receiving this error - messages is going out successfully.

Could not repeat this bug on demo espo crm, cause there is another error there while sending email.

Tried on v7.0.9 and v7.0.9

Log from backend:

`
[2022-01-21 13:07:31] ERROR: Email sending:Laminas\Mail\Transport\Smtp transport expects at least one recipient if the message has at least one header or body; 500 [] []
`

Log from browser console:

```
Server side error 500: sendingFail
(anonymous) @ app.js:909
dispatch @ jquery.js:5430
m.handle @ jquery.js:5234
trigger @ jquery.js:8719
O @ jquery.js:9806
(anonymous) @ jquery.js:10057
load (async)
send @ jquery.js:10076
ajax @ jquery.js:9690
e.ajax @ backbone.js:1460
e.sync @ backbone.js:1443
sync @ backbone.js:437
sync @ model.js:59
save @ backbone.js:648
eval @ VM5827:698
save @ VM5827:697
send @ VM7423:283
send @ VM7422:219
actionSend @ VM7398:165
(anonymous) @ ui.js:255
dispatch @ jquery.js:5430
m.handle @ jquery.js:5234
VM7423:359 Ошибка отправки электронной почты: Laminas\Mail\Transport\Smtp transport expects at least one recipient if the message has at least one header or body
errorHandlerSendingFail @ VM7423:359
errorHandlerSendingFail @ VM7422:264
handleSaveError @ VM5827:802
eval @ VM5827:725
c @ jquery.js:3500
fireWith @ jquery.js:3630
h @ jquery.js:3854
setTimeout (async)
(anonymous) @ jquery.js:3872
c @ jquery.js:3500
fireWith @ jquery.js:3630
fire @ jquery.js:3638
c @ jquery.js:3500
fireWith @ jquery.js:3630
O @ jquery.js:9798
(anonymous) @ jquery.js:10057
load (async)
send @ jquery.js:10076
ajax @ jquery.js:9690
e.ajax @ backbone.js:1460
e.sync @ backbone.js:1443
sync @ backbone.js:437
sync @ model.js:59
save @ backbone.js:648
eval @ VM5827:698
save @ VM5827:697
send @ VM7423:283
send @ VM7422:219
actionSend @ VM7398:165
(anonymous) @ ui.js:255
dispatch @ jquery.js:5430
m.handle @ jquery.js:5234
VM5827:736 Uncaught (in promise) error
```

**Comment by yurikuzn** [comment]
Not reproduced.

**Comment by rutkas** [comment]
I do not have email customizations now.

On the other hand mail on demo.eu.espocrm.com also not working with another error:

`Email sending error. Invalid credentials.`

How can I reproduce my bug on espocrm demo ?

**Comment by yurikuzn** [comment]
Why not to try to debug.

**Comment by rutkas** [comment]
Thank you for advise. After more debugging I found that:
replacing in /Espo/Custom/Resources/metadata/app/fieldProcessing.json

```
    "saverClassNameList": [
        "Espo\\Custom\\Core\\FieldProcessing\\PhoneNumber\\Saver"
    ]

```
with:

```
    "saverClassNameList": [
        "Espo\\Core\\FieldProcessing\\EmailAddress\\Saver",
        "Espo\\Core\\FieldProcessing\\Relation\\Saver",
        "Espo\\Core\\FieldProcessing\\MultiEnum\\Saver",
        "Espo\\Core\\FieldProcessing\\File\\Saver",
        "Espo\\Core\\FieldProcessing\\Wysiwyg\\Saver",
        "Espo\\Custom\\Core\\FieldProcessing\\PhoneNumber\\Saver"
    ]
```
fixes an error. Looks like  "Espo\\Core\\FieldProcessing\\EmailAddress\\Saver" is lost by the custom json. I thought that arrays are merged from core, modules and custom json's. If not, how to do that correctly without repeating all the list ?

**Comment by traien** [comment]
> how to do that correctly without repeating all the list ?

https://docs.espocrm.com/development/metadata/#extending

**Comment by rutkas** [comment]
> https://docs.espocrm.com/development/metadata/#extending

Thanks, just what needed. And objects in { } are always appended automatically from all the tree?

**Comment by traien** [comment]
> Thanks, just what needed. And objects in { } are always appended automatically from all the tree?

Yes
