### ISSUE TITLE
Roles with Reports Create Yes can access data from all Entities where rights are NO

### ISSUE THREAD

**Issue by dreginald** [espocrm/espocrm#2206]
**Describe the bug**
If a role (e.g Sales) has the following rights
Account - create Yes, View/Edit "Own"
Report - Yes, View/Edit Own.

Can create grid report(with ACL unticked) and the report will show all the Accounts to which the role has no view rights.

Ideally the report should restrict (irrespective of whether ACL is ticked or not) to which the user has the rights

**Comment by yurikuzn** [comment]
Reports tool is not a part of this repository.
