### ISSUE TITLE
custom duplicate check with other scopes

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2208]
Sometimes it is needed to check for duplicates through different scopes. Before v7 I redefined the findDuplicates function, made pdo requests there and added extra scope field, that was read in custom view to generate correct links in the dup results. It worked perfectly.
Now since v7 we need to use "duplicateWhereBuilderClassName" and define `public function build(Entity $entity): ?WhereItem`. Since it returns whereItem (not a collection as before), how to generaete duplicate list from several scopes ?

I noticed `/Espo/Core/Duplicate/Finder` class with `public function find(Entity $entity): ?Collection`, but how to redefine it ?

**Comment by yurikuzn** [comment]
You can override checkIsDuplicate method as it's public.

**Comment by rutkas** [comment]
> You can override findDuplicates method as it's public.

Exactly what I used in previous version, but noticed new way for v7. Are you planning to leave public findDuplicates method?

**Comment by yurikuzn** [comment]
At list in 7.x versions it will be public.
