### ISSUE TITLE
Shipping costs not carried over

### ISSUE THREAD

**Issue by kacktorte** [espocrm/espocrm#2210]
**Describe the bug**
When adding shipping cost to a quote and creating either a sales order or an invoice based on that quote, the shipping cost are not carried over. Furthermore, the same behavior applies to an invoice created based on a sales order with shipping cost.

**To Reproduce**
Either creatie a new sales order / invoice and selecting the corresponding quote / sales order in the drop down list (detail view) or by clicking the small plus icon in the list of associated docs an the bottom end of the page.

**Expected behavior**
The shipping costs should carry over when creating a SO / invoice based on another entity.

**EspoCRM version**
Observed in both 7.0.8 and 7.0.9

**Comment by yurikuzn** [comment]
Invoice feature is out of scope of this repo.
