### ISSUE TITLE
Client defs: editDisabled prevents create from working

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2212]
**Describe the bug**
If setting editDisabled: true in client def for an entity then whole record becomes read only including a new record. This has the effect that you can not create a record.

**To Reproduce**
1. add editDisabled: true to the client def of a entity
2. go to the entity and create a record
3. all fields are read only

**Expected behavior**
A record should be able to be created when editDisabled: true is set. This should only affect the editing of a record.

**EspoCRM version**
7.0.8

**Additional context**
view/record/detail 
            if (!this.readOnly) {
                this.readOnly = this.getMetadata().get(['clientDefs', this.scope, 'editDisabled']) || this.readOnly;
            }

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/496d132c23b647ff23b468f49eb682ae34ea1f4d
