### ISSUE TITLE
Define list (small) layout for linkMultiple view

### ISSUE THREAD

**Issue by synnack** [espocrm/espocrm#2214]
Hi, 

We have a case with multiple event entities linked to it. One of the event types is deadline. We want to show the deadlines on the case and kanban view as linkMultiple field with two columns (or concatenated value of 2 fields).

Currently, only the name of a one-to-many view or a parent-children view is shown in a linkMultiple field, obscuring the most important part, the dateStart field.

Is there a way to define a view for the linkMultiple field so that it just uses the "list (small)" layout, like the relationship panel does?

Kind of like the views/record/panels/relationship can do for sidePanels. 

Thanks in advance

**Comment by yurikuzn** [comment]
Hi,

There's no way. I believe there's a 3rd party extension doing that. Maybe try asking on our forum.

**Comment by eymen-elkum** [comment]
here is the extension:
https://www.eblasoft.com.tr/product-page/espocrm-link-multiple-inline-form
