### ISSUE TITLE
Force user password change on next login option

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2218]
**Describe the solution you'd like**
I think an option on users to force the user to change their password on next login would be very good for security. 
This could be the default for a new user and also an option for the admin user to set on a user account.

**Comment by yurikuzn** [comment]
Making is default is definitely not an option. It brings more hate than security.

**Comment by boydle** [comment]
Maybe a config option for the admin to set if they wish to have this as the default instead of sending out a password. This way unless someone sets the config manually there is no change/impact.
