### ISSUE TITLE
Simple error in package.json

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#222]
When I install the dependencies to compile (`npm install`), this warning is displayed:

`npm WARN espocrm@4.2.5 license should be a valid SPDX license expression`

That is easy solution: simply change: `"license": "GPLv3"` by `license":"GPL-3.0"` in the package.json.

More info in https://spdx.org/licenses/

Regards!

**Comment by yurikuzn** [comment]
Thanks
https://github.com/espocrm/espocrm/commit/f95fa96ae11318647dbda681d82f92a8fd2759dd
