### ISSUE TITLE
Mass Action Delete Error Message Does not Translate Entity Name

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2220]
**Describe the bug**
Mass Action Delete Error Message Does not Translate Entity Name

**To Reproduce**
1. create a record def for KnowledgeBaseArticle

`{
	"massActions": {
		"delete": {
			"disabled": true
		}
	}
}`

2. Mass delete some KnowledgeBaseArticle's

**Expected behavior**
The KnowledgeBaseArticle text should be translated in the default setup it should be "Knowledge Base Article" this issue exists with all entities

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/152120704-572f70b4-c93c-41a4-a7bf-0d4df893c981.png)

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
We don't translate exception messages.

**Comment by boydle** [comment]
These messages maybe exceptions but are used to tell users functionality is disabled. The UI does not update to remove the buttons so a helpful error message would be expected by users.

**Comment by yurikuzn** [comment]
In normal situation these should never be shown to anyone except a developer. It's too much work, I have a huge backlog, so I ignore such small issues at this moment.
