### ISSUE TITLE
Mass Action Update Error Message is not helpful

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2221]
**Describe the bug**
When mass update is disabled the error message is not helpful

**To Reproduce**
1. create a record def for KnowledgeBaseArticle

`{
	"massActions": {
		"update": {
			"disabled": true
		}
	}
}`
2. Mass Update some KnowledgeBaseArticle's

**Expected behavior**
Error message should say something like "Mass Action Update is disabled" instead of Error Occured

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/152121428-a8d3498d-23fb-4fc9-a6de-c1dae89e4ff8.png)

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
What is in log? We suppose that a developer looks into the log for more info.

**Comment by boydle** [comment]
The log has the following: [2022-02-02 08:44:15] ERROR: (403) Mass action 'update' is disabled for 'KnowledgeBaseArticle'.; POST /MassAction;
