### ISSUE TITLE
I can not translate "My Espo"

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#223]
I mean the tab on the dashboard. It is not found in the .po file. When I search in the source code, I find matches in these files:

`application/Espo/Resources/metadata/app/defaultDashboardLayouts.json`
`application/Espo/Core/defaults/config.php`
`client/src/views/settings/fields/dashboard-layout.js`
`client/src/views/dashboard.js`

I do not know if these files can be translated

You may do something?

Tanks!

**Comment by yurikuzn** [comment]
I will look. But can do it only for new users. It will be translated only when user is created. 
https://github.com/espocrm/espocrm/issues/224

**Comment by PanuWeb** [comment]
It would be good. It is that what he wanted. It is understood, as it is a custom field for the user, if you changed the language would have to manually edit later or just delete and create the tab again. Thank you.
