### ISSUE TITLE
Case: "Actual" filter not working

### ISSUE THREAD

**Issue by mitchplze** [espocrm/espocrm#2231]
**Describe the bug**
In: **Administration > Entity Manager > Case > Fields > Status**
After setting the "Not Actual Options" to custom case statuses, those cases are **not** visible under the "Closed" case filter

**To Reproduce**
1. Create a new case status
2. Add the case status to the "Actual" filter
3. Try to find the case in the Case list view - it won't show up

**Expected behavior**
The filter should push affected status items to the "Closed" view filter

**Screenshots**
<img width="355" alt="Screen Shot 2022-02-09 at 17 02 30" src="https://user-images.githubusercontent.com/25162574/153316777-7164c62a-d448-4bb4-8fcd-c5340aadf68a.png">
<img width="1029" alt="Screen Shot 2022-02-09 at 17 03 07" src="https://user-images.githubusercontent.com/25162574/153317104-ba44ec5c-e624-41c3-8c89-5070f0003534.png">
![Screen Shot 2022-02-09 at 17 03 49](https://user-images.githubusercontent.com/25162574/153317116-27211409-bdef-4132-bb4d-02ffe95191a1.png)
![Screen Shot 2022-02-09 at 17 04 59](https://user-images.githubusercontent.com/25162574/153317125-da69feb1-d4e3-4fba-b5d8-922a062ac2f9.png)

**EspoCRM version**
7.0.9

**Comment by yurikuzn** [comment]
It's not supposed to be shown. Only status == 'Closed' are shown.

**Comment by mitchplze** [comment]
This post seems to contradict that.

Could you explain the functionality of this field then? Thanks so much!

https://forum.espocrm.com/forum/general/72689-cases-status-field

**Comment by yurikuzn** [comment]
The parameter effects only 'Actual' filter. Closed filter is supposed to show only cases with status 'Closed'.

**Comment by mitchplze** [comment]
Okay thanks! Is there a way to customize/create your own filters for Cases? I wasn’t able to see a way, but maybe I’m missing it

**Comment by yurikuzn** [comment]
By coding (quite simple though). Or with advanced pack with 'Report Filters' feature.
