### ISSUE TITLE
During installation, 'First Day of Week' shows numbers instead of names

### ISSUE THREAD

**Issue by 530f6caa** [espocrm/espocrm#2236]
**Describe the bug**
During installation, at the System settings step, the dropdown for First Day of Week shows the options 0-6 instead of weekday names.

**To Reproduce**
1. Extract EspoCRM zip file onto web server.
2. Follow installation instructions as prompted until you reach the System settings screen.

**Expected behavior**
The First Day of Week dropdown shows Sunday, Monday, etc.

**Screenshots**
![espocrm1](https://user-images.githubusercontent.com/83148805/154881921-f51e6291-6349-4d97-b20b-8e6cde48086a.png)
![espocrm2](https://user-images.githubusercontent.com/83148805/154881923-708ebdbb-f195-438b-ab27-5deb7feb894b.png)

**EspoCRM version**
EspoCRM version 7.0.9

**Additional context**
Weekday names are displayed correctly in Preferences > Admin once installation is complete.

**Comment by yurikuzn** [comment]
Already fixed.
