### ISSUE TITLE
Kanban header not sliding with cards container when more records shown (show more)

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2238]
**Describe the bug**
When showing more records (cards) on the kanban view (clicking show more) if you slide over to see more kanban values the cards slides but not the header of the kanban and therefore the cards will be placed under a different kanban value. 

**To Reproduce**
1. add more options to Opportunity stage (so kanban can be long)
2. create many opportunities records under closed stage
3. go to opportunities choose kanban and click on (view more) to see more records vertically, then try to slide in kanban to view more value on right.
4. cards will be placed in different value of kanban (just UI issue not)
...

**Expected behavior**
I expect when i slide the kanban cards container to see more kanban values i expect that both cards container and kanban header to move simultaneously so that cards always are show under the correct value of the kanban.
 
**Screenshots**
<img width="1278" alt="Screenshot 2022-02-22 at 21 56 57" src="https://user-images.githubusercontent.com/19490674/155219466-b1a38070-5d68-4a88-84c1-276d9be8ef7e.png">
<img width="1278" alt="Screenshot 2022-02-22 at 21 55 14" src="https://user-images.githubusercontent.com/19490674/155219461-3f9a8099-61b1-4701-a81f-f42f64ff95b9.png">
**EspoCRM version**
version 7.0.9

**Comment by yurikuzn** [comment]
I have never observed such behavior and could not reproduce now. Do you mean 'horizontal scrolling' by 'slide'?

**Comment by rabiibrahimi** [comment]
Yes i mean horizontal scroll when i said (slide). this only happens when you click the 3 dots below as (show more) once more cards are displayed if you scroll down and then scroll horizontally then the cards will move and kanban header will not. i Have checked again and it seems that when the kanban header is positioned on top of the screen and fixed this problem happen. Try to scroll down until the kanban header is position on top of the screen and then scroll horizontally and this will trigger the issue.

**Comment by rabiibrahimi** [comment]
I think this could happens when Kanban header container is sticked (kanban-head-container **sticked**), cause this only happens when the kanban header is sticked on top of the screen.

**Comment by yurikuzn** [comment]
Here's the fix: https://github.com/espocrm/espocrm/commit/5b6889d5545cbca6ea33f3a2ed998a9f7931bb18. Any help with testing appreciated.
