### ISSUE TITLE
Select all results is not available to regular user in Documents

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2241]
**Describe the bug**
If a regular user tries to select all records in Documents the select all records option is not available.

**To Reproduce**
1. Create a role with these details:
All header level settings (export, user etc) = not-set
Documents scope set to enabled: create = Yes, Read = All, Edit = All, Delete = All
3. Create a regular user with this role and login
4. navigate to documents 
5. Select all results is not available

**Expected behavior**
Select all option should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/156478408-8f9185f2-c710-4fe9-9218-856a31d8b695.png)

**EspoCRM version**
7.0.8

**Comment by yurikuzn** [comment]
Any help with fix will be appreciated.

**Comment by yurikuzn** [comment]
You missed giving the mass-update permission.

**Comment by boydle** [comment]
Hi Yuri,

Is Mass Update permission required to be able to mass delete records?

**Comment by yurikuzn** [comment]
Yes.

**Comment by boydle** [comment]
ok, Thanks.
