### ISSUE TITLE
A regular user with Document and Document Folder permissions can not add children to a document folder

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2243]
**Describe the bug**
A regular user with Document and Document Folder permissions can not add children to a document folder.

**To Reproduce**
1. Create a role with 
2. Documents create = yes, edit = all, update = all, delete = no
3. Document Folders create = yes, edit = all, update = all, delete = no
4. Create a document and do not set the folder
5. Create a document folder 
6. Go to manage folders and enter the folder
7. Use the children bottom panel to select the created document.
8. A 403 error is returned
...

**Expected behavior**
Document should be linked to this folder

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/156868030-a2e636bd-3e5d-46f0-a3df-dff42e8b400f.png)

**EspoCRM version**
7.0.8

**Additional context**
If selecting the folder from the document form this works.

Log data:
[2022-03-05 04:32:36] DEBUG: API (403) POST /DocumentFolder/6222e7ca3d69e5c1e/children; Input data: {"ids":["6222e7ca3d69e5c1e"]}; Route pattern: /{controller}/{id}/{link}; Route params: Array (     [controller] => DocumentFolder     [action] => createLink     [id] => 6222e7ca3d69e5c1e     [link] => children )  [] []
[2022-03-05 04:32:36] ERROR: (403) POST /DocumentFolder/6222e7ca3d69e5c1e/children; line: 282, file: /home/kyledev5/public_html/application/Espo/Services/RecordTree.php [] []

**Comment by yurikuzn** [comment]
Could not reproduce on the master.

**Comment by boydle** [comment]
Hi Yuri,
I will get a clean install setup this week and give some feedback.

**Comment by boydle** [comment]
Hi Yuri,

I have installed a clean 708 and also a 709 and have the same issue I will add some more images. Maybe fixed in 7.1.0?

Create this Role and a regular user with this role.
![image](https://user-images.githubusercontent.com/7907518/157151329-abc7b102-4ec5-42e7-9f5d-4ffd7d37a0a0.png)

Create a document with the new user. Without a folder.
![image](https://user-images.githubusercontent.com/7907518/157151395-c72bdd7a-b9ed-4450-9466-4aaa873c8759.png)

Create a folder and then navigate in to it and select the new document as a child
![image](https://user-images.githubusercontent.com/7907518/157151442-4d9baf05-b22f-47eb-afea-a4fb243d9838.png)


This is when the error is displayed.

**Comment by yurikuzn** [comment]
This ability is supposed to be disabled for all users. Fixed for v7.1: https://github.com/espocrm/espocrm/commit/b5bef88a8dde8089126813e22d70ca3fe5a68833
