### ISSUE TITLE
Regular user can not create a Mass Email that is not linked to a Campaign

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2245]
**Describe the bug**
Regular user creates a mass email directly that is not linked to a Campaign and a 403 is returned.

**To Reproduce**
1. login with a regular user
2. navigate to Campaigns > Mass Emails
3. Create a Mass Email
4. Fill in all required fields and save

**Expected behavior**
Mass email should save but a 403 is returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/157167923-9de1872c-6c41-4f82-8222-efc207f6205f.png)

**EspoCRM version**
7.0.9

**Additional context**
1. If a campaign is selected this will save
2. Admin user can create without a campaign

Problem appears to be in this ACL check
Espo\Modules\Crm\Services\MassEmail.php

    protected function beforeCreateEntity(Entity $entity, $data)
    {
        parent::beforeCreateEntity($entity, $data);

        if (!$this->getAcl()->check($entity, 'edit')) {
            throw new Forbidden();
        }
    }

**Comment by yurikuzn** [comment]
It's intentional.

**Comment by boydle** [comment]
Hi Yuri,

So I can understand better it is intentional that an admin can create but a regular user can not?
Or should no user be able to create without a campaign?

Can/Should the campaign be made required on the UI to remove the confusion?
