### ISSUE TITLE
Regular user can not create a Tracking URL that is not linked to a Campaign

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2246]
**Describe the bug**
Regular user creates a tracking url directly that is not linked to a Campaign and a 403 is returned.

**To Reproduce**
1. login with a regular user
2. navigate to Campaigns > Tracking URL
3. Create a Tracking URL
4. Fill in all required fields and save

**Expected behavior**
Campaign should be a required field or the Tracking URL should save.

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/157168560-3604ca0f-aac6-4101-8063-a8cfeed152fb.png)

**EspoCRM version**
7.0.9

**Additional context**
1. If a campaign is selected this will save
2. Admin user can create without a campaign

**Comment by yurikuzn** [comment]
Intentional.

**Comment by boydle** [comment]
Hi Yuri,

So I can understand better it is intentional that an admin can create but a regular user can not?
Or should no user be able to create without a campaign?

Can/Should the campaign be made required on the UI to remove the confusion?
