### ISSUE TITLE
Remove version number

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2247]
In order to limit attack surface I would suggest to remove 

- version
- aclAllowDeleteCreated

from  `/api/v1/Settings `
or move to a location available after login. 

Background : 

- Version can be used to scan for unpatched installed versions, leading to potential security risks.
- acl policies are internal application behaviour, and not applicable/needed in this context.

**Comment by yurikuzn** [comment]
Agree. I thought about that.

**Comment by yurikuzn** [comment]
Hid the version parameter: https://github.com/espocrm/espocrm/commit/6efff8e9d0aac31bea2392f53f2df19e83cd1d6e.

Hidding aclAllowDeleteCreated requires some refactoring so I left it as it was.
