### ISSUE TITLE
Admin don't have access to email folders of another user

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2248]
**Describe the bug**
When setting up personal email account for another user, when trying to use the field (Put in folder) it won't fetch folder created by the user you are trying to set up their email account. the result is empty knowing that the user has created a folder. 

**To Reproduce**
1. create another user (john doe) (either admin or assign all permissions) and log in with the new user's credentials and go to Emails (on top right menu next to compose - choose folders and then create a new folder e.g john doe inbox)
2. log in as admin and try to set up the personal email account for the new user (john doe) 
3. on the personal email account set up try to select the folder (Put in folder) the result will be empty knowing that john doe has created a new folder called john doe inbox
4. ...
...

**Expected behavior**
when choosing to fill in put in folder normal bahvior the system should find all folders created by the user we are trying to set up their personal email account, in this case above when set up the email account for john doe i should be able to select the folder (john doe inbox) as (put in folder).

**Screenshots**

**EspoCRM version**
this is happening on both version 7.0.8 and 7.0.9
<img width="1278" alt="Screenshot 2022-03-10 at 16 32 32" src="https://user-images.githubusercontent.com/19490674/157698210-6a69b1c2-9c5a-4edd-8982-f23ca1ba18e0.png">
<img width="1278" alt="Screenshot 2022-03-10 at 16 31 15" src="https://user-images.githubusercontent.com/19490674/157698229-0bd3d2bd-a189-4160-a938-971c68d2b380.png">

**Additional context**

**Comment by yurikuzn** [comment]
It's a known issue. Won't be fixed in the nearest future.

**Comment by rabiibrahimi** [comment]
No worries, thanks for your reply.

**Comment by rabiibrahimi** [comment]
This used to work in previous versions so thought maybe this was just a bug in 7 version and above.

**Comment by yurikuzn** [comment]
I don't remember this working. Any help with fix will be appreciated.

**Comment by rabiibrahimi** [comment]
Hi Yuri, 

I have checked and it seems that this was working in all versions before version 7, i have just tested this feature on version 6.1.10 and it is working correctly. It seems the problem is coming from the new select file for emailFolder, i have gone into Application/Espo/Classes/Select/EmailFolder/AccessControlFilters/Mandatory.php and i have commented all code in the apply method and it worked, seems code in the apply method is causing issue. can you please verify that code. Once the code is commented the feature works as expected see attached screenshot from version 7.0.8
<img width="1278" alt="Screenshot 2022-03-11 at 14 39 01" src="https://user-images.githubusercontent.com/19490674/157878840-793d1ee3-4d3e-40cb-af54-bd469c50c8d0.png">

This is the code causing issue under apply method of Application/Espo/Classes/Select/EmailFolder/AccessControlFilters/Mandatory.php:

$queryBuilder->where([
            'assignedUserId' => $this->user->getId(),
        ]); 

I hope this helps.

**Comment by yurikuzn** [comment]
Thanks for help. Fix: https://github.com/espocrm/espocrm/commit/389dda2866284b9849c8c97cf066df9e0c40df8e
