### ISSUE TITLE
Setting sort order isn't working

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2249]
I set the sort order of the `User` entity to a custom field, `employeeId`, which I have since removed. Upon removal, I set the sort order to be the `lastName` field. However, the change does not appear to be reflected in the client.

Loading the `User` list shows an error:

![image](https://user-images.githubusercontent.com/1170415/157909813-2b17860c-2ac9-4821-9c1f-6f832a997ec3.png)

which appears in the log as well:

```
[2022-03-11 16:40:15] DEBUG: API (500) Order by non-existing field 'employeeId'.; GET /User; Route pattern: /{controller}; Route params: Array (     [controller] => User     [action] => index )  [] []
[2022-03-11 16:40:15] ERROR: (500) Order by non-existing field 'employeeId'.; GET /User; line: 176, file: /var/www/crm/application/Espo/Core/Select/Applier/Appliers/Order.php [] []
```

On line 82 of `application/Espo/Core/Select/Applier/Appliers/Order.php`, I added a debug statement:
```
 80     public function apply(QueryBuilder $queryBuilder, OrderParams $params): void
 81     {
 82         $GLOBALS['log']->debug("params:",(array)$params);
 83         if ($params->forceDefault()) {
```
which produces the following output:
```
[2022-03-11 16:40:15] DEBUG: params: {"\u0000Espo\\Core\\Select\\Order\\Params\u0000forbidComplexExpressions":true,"\u0000Espo\\Core\\Select\\Order\\Params\u0000forceDefault":false,"\u0000Espo\\Core\\Select\\Order\\Params\u0000orderBy":"employeeId","\u0000Espo\\Core\\Select\\Order\\Params\u0000order":"ASC"} []
```
I can't figure out how to get the value to change. I set the sort order in the `User` entity as follows:
![image](https://user-images.githubusercontent.com/1170415/157910509-4bbe60a9-7655-44bf-843d-cd9b76dcc610.png)

which appears to be reflected in the `User` entity's definition:
```
(19:11) ubuntu@odped:/var/www/crm/custom $ grep -A 8 order ./custom/Espo/Custom/Resources/metadata/entityDefs/User.json
        "orderBy": "lastName",
        "order": "asc",
        "textFilterFields": [
            "name",
            "userName",
            "title"
        ],
        "fullTextSearch": false,
        "countDisabled": true
    },
```

**Comment by bandtank** [comment]
I restarted the server, cleared the cache, and rebuilt the database. Also, I dumped the database into a text file to search for `employeeId`, which did not return any results. I have absolutely no idea where the string is stored. I can't find a single reference to it in any file on the server or any field in the database. Somehow, the `employeeId` string has been stored by Espo, but the storage of the string is a secondary issue.

**Comment by bandtank** [comment]
I found the `employeeId` string in the client. Here is the request from the client when I refresh the `User` list:

```
https://crm.odysseypediatric.com/api/v1/User?userType=internal&select=salutationName%2CfirstName%2ClastName%2CmiddleName%2Cname%2CuserName%2Ctitle%2CemailAddressIsOptedOut%2CemailAddress%2CemailAddressData%2CisActive%2ChasTimesheet%2CsalutationName%2CfirstName%2ClastName%2CmiddleName%2Cname%2CuserName%2Ctitle%2CemailAddressIsOptedOut%2CemailAddress%2CemailAddressData%2CisActive%2ChasTimesheet&maxSize=20&offset=0&orderBy=employeeId&order=asc
```

**Comment by yurikuzn** [comment]
I believe that clicking the [X] button (next to the search button) resets the locally stored sorting.

I could not come up an elegant solution how to do it automatically. If the [X] button is doing the job, I'd leave it as it is.

**Comment by bandtank** [comment]
The problem is you can't click the button during the error condition because the page doesn't finish loading. The only way I could see the list of users was to clear the value from application storage. Otherwise, the page failed to load after the error appeared.

**Comment by yurikuzn** [comment]
I see. I always though that the search view is rendered before the collection is fetched. I will take a look.

**Comment by yurikuzn** [comment]
Tried to reproduce. The search view was always rendered so I could click the [X] to reset the sorting.
![Screenshot at 2022-03-14 11-09-17](https://user-images.githubusercontent.com/1006792/158140960-d9f9609c-1bfa-4ea6-9426-3f6fb1774f64.png)
