### ISSUE TITLE
Error when upgrading version 5.9.4 to 6.0.10 with CLI.

### ISSUE THREAD

**Issue by thanhnd1997** [espocrm/espocrm#2253]
Hello,
I got an error while upgrading version 5.9.4 to 6.0.10 with CLI.
This is my error.

When I upgrade and access the web again, the white screen happens
![Screenshot 2022-03-24 180104](https://user-images.githubusercontent.com/91942636/159908797-38f0de32-652f-4eb2-93ee-5c7b1706ddd8.png)
![Screenshot 2022-03-24 180121](https://user-images.githubusercontent.com/91942636/159908801-cddb67b2-5df6-4701-b7fb-673a00a4a9d9.png)
![Screenshot 2022-03-24 180230](https://user-images.githubusercontent.com/91942636/159908805-0bbed746-b172-4051-a04f-2c31173be0ac.png)

**Comment by thanhnd1997** [comment]
Thanks @yurikuzn

**Comment by thanhnd1997** [comment]
https://forum.espocrm.com/forum/installation-and-upgrade-help/79468-error-when-upgrading-version-5-9-4-to-6-0-10-with-cli.

please help me @yurikuzn

**Comment by yurikuzn** [comment]
Please, no need to mention me.
