### ISSUE TITLE
CRM bypass duplicate check on account creation

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2255]
**Describe the bug**
The system doesn't apply duplicate check when creating new account (or duplicating an existing account)

**To Reproduce**
1. create an account (provide a name and email)
2. create second OR (try to duplicate previous created account)
...

**Expected behavior**
Expected behavior is to show duplicated account message, it should not create an account with existing name/email. 

**Screenshots**

**EspoCRM version**
both version 7.0.8 and version 7.0.9

**Additional context**
Not sure if this applies to other entities like Lead etc. 
<img width="1239" alt="Screenshot 2022-03-24 at 19 23 29" src="https://user-images.githubusercontent.com/19490674/159985049-42c0c62b-4bbf-4e89-b6a6-6617622599c1.png">

**Comment by yurikuzn** [comment]
As usual, could not reproduce.

**Comment by rabiibrahimi** [comment]
Sorry i have not explained the case, i have a field called (companyNumber) on account entity and i have created a class to check if there is a duplicate for the new accounts with existing companyNumber, if i provide an existing companyNumber the duplicate message will appear otherwise if i create a company with only existing name and a different companyNumber it will bypass the built in name duplicate check. do i have to extend existing name duplicate ?

**Comment by yurikuzn** [comment]
The provided information is not enough to be considered a bug report.

**Comment by rabiibrahimi** [comment]
Describe the bug
When new custom duplicate check is provided the system ignore built in (name & email check duplicate) for an account.

To Reproduce
Steps to reproduce the behavior:

- create a new field on account called (companyNumber) varchar
- create a custom duplicate check for the new created field (see attached screenshot)
- try to create a company with existing name and a new companyNumber (it will bypass name duplicate check)
- try to create another company with existing companyNumber (the custom duplicate check for companyNumber will show the duplicate message)
...
Expected behavior
Always have built in duplicate check run even if we have custom duplicate check. If the custom duplicate check is deactivated the built in duplicate check works again.

Hope this provides more info.

Screenshots
If applicable, add screenshots to help explain your problem.

EspoCRM version
<img width="1274" alt="Screenshot 2022-03-24 at 20 12 24" src="https://user-images.githubusercontent.com/19490674/159993170-a08f83a8-b2de-46b2-9c5a-fa59b197017b.png">
<img width="1274" alt="Screenshot 2022-03-24 at 20 12 59" src="https://user-images.githubusercontent.com/19490674/159993180-a436188a-cd2a-48a2-9ccf-eb683c97ff49.png">
version 7.0.9

**Comment by yurikuzn** [comment]
You specifies the new class, the old class is not applied anymore. Your new class should handle ALL logic now.

**Comment by rabiibrahimi** [comment]
sorry for any trouble caused, i am still learning and was just trying to help. any hints how to merge the metadata ? 
Thanks 🙏

**Comment by yurikuzn** [comment]
https://docs.espocrm.com/development/metadata/#how-its-stored

Metadata from different folders (modules, custom folder) is merged into one. If the same parameter available in core and module, the latest one will be applied, the first one will be overridden.

**Comment by rabiibrahimi** [comment]
Thanks if i understand i should just append so that the files merge into one. tried code below under recordDefs/Account.json

{
    "duplicateWhereBuilderClassName": 
    [
        "__APPEND__",
        "Espo\\Custom\\Classes\\DuplicateWhereBuilders\\Account"
    ],
    "updateDuplicateCheck": true   
}
didn't work :( not sure how to accomplish this as i am a newbie in dev. 
Sorry again

**Comment by rabiibrahimi** [comment]
Ok great thanks @yurikuzn  much appreciate your time and help. 🙏
stay safe
