### ISSUE TITLE
Can not select followers for custom entity

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2257]
**Describe the bug**
Custom entities will not allow user to select followers - gives error.

**To Reproduce**
1. Create a custom entity base plus with stream = true
2. Create a new record for this entity and save
3. Go to view followers
4. Now click select button
5. select some extra users
6. Error returned "Error occurred" 

**Expected behavior**
Followers should be added to followers list

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/160222870-4d8e21ec-4c5a-4434-8f9e-8a60b0b987f1.png)

**EspoCRM version**
7.0.9

**Additional context**
Log:
[2022-03-26 03:14:42] ERROR: (403) Could not add a user to followers. The user needs to have 'stream' access.; POST /FollowerTest/623e81a8e262244f1/followers; line: 1144, file: /home/dev/public_html/application/Espo/Core/Record/Service.php [] []

**Comment by yurikuzn** [comment]
Steps to reproduce is not detail enough. What user did you select. Is it admin or regular user. Does this user have access to the stream? The log message showed that they does not have access to the stream (in the master version it's printed on UI). It's not possible to make the user to follow the record if they does not have access to the stream (it's logical). There's no possibility to filter such users in the list.

Please try to provide more details so I didn't have to guess and try multiple scenarios.

**Comment by boydle** [comment]
Can a useful error message be provided? there is no way for the user to know why there was an error.

**Comment by yurikuzn** [comment]
As I mention in the previous post, it's already done.
