### ISSUE TITLE
Changing from LDAP to Espo authentication causes errors

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2258]
Changing the authentication method from LDAP to Espo causes a 500 error to appear. Here is the error

```
[2022-03-28 03:44:31] ERROR: Slim Application Error Type: TypeError Code: 0 Message: Argument 2 passed to
Espo\Core\Authentication\Helper\UserFinder::find() must be of the type string, null given, called in
/var/www/crm/application/Espo/Core/Authentication/Logins/Espo.php on line 68 File:
/var/www/crm/application/Espo/Core/Authentication/Helper/UserFinder.php Line: 45 Trace: ...
```

1. Configure LDAP authentication and log in
2. Change the method to Espo and stay logged in
3. Look at the error log to see the error shown above

**Expected behavior**
I would expect to be logged out after changing the method. However, this should come with a warning because the password for the admin user may not work anymore. An alert to make sure an admin user has a working password would be a great thing to add.

**EspoCRM version**
7.0.9

**Comment by yurikuzn** [comment]
I could not reproduce on the master branch. No error in the log. Could be fixed when refactored, not sure.

Login-out is not easy to implement, it would require significant changes in design of authentication.

**Comment by bandtank** [comment]
I am able to reproduce this on 7.0.9, but it doesn't seem like a big deal. An admin can kill every access token if it's an issue for all users.
