### ISSUE TITLE
Possibility to force check emails by users

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#226]
Now, it does the email check based on Scheduled times.

Is it possible to add a button to force it when desired? Like, If I press the CHECK MAIL button, it will do the update without having to wait the Scheduled check.

**Comment by yurikuzn** [comment]
It's already was planned.

**Comment by yurikuzn** [comment]
Workaround is using daemon or make crontab to run cron.php multiple times per minute.
