### ISSUE TITLE
Allow adding/removing elements from multi-enum fields using mass update

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2261]
**Is your feature request related to a problem? Please describe.**

- We use a multi-enum field to tag Accounts.  
- We want to be able to add a new tag to multiple Accounts.  
- These Accounts may already have tags.

**Describe the solution you'd like**

I would like to be able to ADD or REMOVE values from the selected records, using mass-update

**Describe alternatives you've considered**

Manual

**Suggested interface**: 

![image](https://user-images.githubusercontent.com/61187964/160610872-23122246-6c32-4f95-bc74-2ea74bc36b5d.png)

**Comment by gustavo-dssi** [comment]
Hi,
Are you already working with this solution? If yes, how did you configured it.
Regards

**Comment by gustavo-dssi** [comment]
Hello again
I'm really interested in this solution. 
I would really apreciate if you coud give a response about this.
Thank you :)

**Comment by yurikuzn** [comment]
No body is working on the solution in Espo at the moment. No time.

**Comment by gustavo-dssi** [comment]
Thank you for your response @yurikuzn
Is there any other solution for this issue?
Thank you

**Comment by yurikuzn** [comment]
There definitely should be a way. One that I see:

1. Create an additional multi-enum field with same option values.
2. Make the field "notStorable" (in metadata > entityDefs > {YourEntity} > fields > {yourField}.
3. Write formula that adds values from the auxiliary field to the main field.

For more help, please use our forum. I don't have time to provide support.

**Comment by gustavo-dssi** [comment]
Thank you for your help, @yurikuzn

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/2310
