### ISSUE TITLE
anyOf - noneOf - allOf  in SelectBuilder - Condition - Expression (for multi-enum fields)

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2268]
**Is your feature request related to a problem? Please describe.**
I have a multi-enum field called (companyType) on account entity and i created a primary filter (Client Introducers) for my account entity which means i want to select only accounts that have companyType value equals both ['Client', 'Introducer']. However for some reason the selectBuilder doesn't return the result (return no data), knowing that i have records that match such scenario in the database. i even tried both Condition and Expression (in / notIn) and they both only work for enum field but not for multi-enum field. I even tried to use condition and expression class but same thing, they only work if given field is enum.

**Describe the solution you'd like**
i would love if the selectBuilder would accept this, even Condition and Expression classes if possible: 
- SelectBuilder: (companyType is multi-enum)
`$queryBuilder->where([
            'companyType' => ['Client', 'Introducer']
        ]);`
- Using Expression: (companyType is multi-enum)
`$queryBuilder->where(
            Expr::in(
                Expr::column('companyType'),
                ['Client', 'Introducer']
            )
        );`
- Using Condition: (companyType is multi-enum)
`$queryBuilder->where(
            Cond::in(
                Cond::column('companyType'),
                ['Client', 'Introducer']
            )
        );`

**Describe alternatives you've considered**
I think this should work same way it works for enum field. If possible to add such api anyOf - noneOf - allOf to allow selecting values of multi-enum fields.

**Additional context**
I have tried selectBuilder, using condition, using expression and none worked for multi-enum field.

**Comment by yurikuzn** [comment]
It's not possible. It would add unnecessary complexity into ORM. Use joining `ArrayValues` table, with the sub-query usage if needed. It's simple, the hardest part is to design a proper SQL query, then replicate it with the ORM tool.

See: https://github.com/espocrm/espocrm/blob/7.0.9/application/Espo/Core/Select/Where/ItemGeneralConverter.php#L354

**Comment by yurikuzn** [comment]
One can also use `Espo\Core\Select\SelectBuilder`, it's a layer between the front-end search requests and ORM. It can build a needed query, it does know about different fields type of EspoCRM. ORM does not know about any field type.

**Comment by yurikuzn** [comment]
Using the select-builder framework.

Inject `Espo\Core\Select\SelectBuilderFactory` into your class.

```php
$query = $this->selectBuilderFactory
    ->create()
    ->from('EntityType')
    ->withWhere(
        \Espo\Core\Select\Where\Item::createBuilder()
            ->setAttribute('companyType')
            ->setType('arrayAllOf')
            ->setValue(['Client', 'Introducer'])
            ->build()
    )
    ->build();

$collection = $this->entityManager
    ->getRDBRepository('EntityType')
    ->clone($query)
    ->find();
```

**Comment by rabiibrahimi** [comment]
@yurikuzn thanks for your reply, i have tried the select builder as you explained but still the result is not correct, the all data is returned and seems query is not taken into consideration, below my primary filter class: 
`<?php

namespace Espo\Custom\Classes\Select\Account\PrimaryFilters;

use Espo\Core\ORM\EntityManager;
use Espo\Core\Select\Primary\Filter;
use Espo\Core\Select\SelectBuilderFactory;
use Espo\ORM\Query\SelectBuilder;

class Clients implements Filter
{
    private $selectBuilderFactory;
    private $entityManager;

    public function __construct(SelectBuilderFactory $selectBuilderFactory, EntityManager $entityManager){
            $this->selectBuilderFactory = $selectBuilderFactory;
            $this->entityManager = $entityManager;
    }
    public function apply(SelectBuilder $queryBuilder): void
    {
        $query = $this->selectBuilderFactory
            ->create()
            ->from('Account')
            ->withWhere(
                (new \Espo\Core\Select\Where\ItemBuilder)
                    ->setAttribute('companyType')
                    ->setType('arrayAllOf')
                    ->setValue(['Client', 'Introducer'])
                    ->build()
            )
            ->build();

         $this->entityManager
            ->getRDBRepository('Account')
            ->clone($query)
            ->find();
    }
}`

I just want to be able to filter data based on multi-enum field values. any help please, i have tried all but couldn't achieve the desired result. 
Many thanks

**Comment by yurikuzn** [comment]
This code won't work inside a PrimaryFilter.

You have `leftJoin`, `join`, `distinct` methods. You can use sub-query within `where`. Hope you use IDE, so autocomplete will help you. Compose the query using QueryBuilder object. The way how you would compose SQL.

Please use our forum for help. We use GitHub only for development purposes. I need to rest. Please, no need to mention me on GitHub in comments. Thanks.

**Comment by yurikuzn** [comment]
All of:

```php

$subQuery1 = QueryBuilder::create()
     ->from('ArrayValue')
     ->select('entityId')
     ->where([
          'value' => 'Value 1',
          'attribute' => 'fieldName',
          'entityType' => 'EntityType',
          'deleted' => false,
    ])
    ->build();

$subQuery2 = QueryBuilder::create()
     ->from('ArrayValue')
     ->select('entityId')
     ->where([
          'value' => 'Value 2',
          'attribute' => 'fieldName',
          'entityType' => 'EntityType',
          'deleted' => false,
    ])
    ->build();

$queryBuilder
    ->where(
        Cond::and(
             Cond::in(Cond::column('id'), $subQuery1), 
             Cond::in(Cond::column('id'), $subQuery2),
        )
    )
```

**Comment by rabiibrahimi** [comment]
Sure i will use the forum, thanks for your support. 
Many thanks

**Comment by yurikuzn** [comment]
Another way:

Inject `Espo\Core\Select\Where\ConverterFactory` and `Espo\Entities\User` into your filter class.

Then inside the `apply` method:

```php
$converter = $this->converterFactory->create('YourEntityType', $this->user);

$whereClause = $converter->convert(
    $queryBuilder,
    (new \Espo\Core\Select\Where\ItemBuilder)
        ->setAttribute('companyType')
        ->setType('arrayAllOf')
        ->setValue(['Client', 'Introducer'])
        ->build()
);

$queryBuilder->where($whereClause);
 
```

**Comment by rabiibrahimi** [comment]
Thank you so much, both ways works. I really appreciate your support and help ❤️
Stay safe

**Comment by bandtank** [comment]
I needed to do something very similar. I wanted to find a record that has one option in a multi-enum field. It could have more, but it needs to have at least the one option in the query.

Here is a nearly complete example:

```php
<?php

namespace Espo\Custom\Hooks\NewNote;

use Espo\Core\Select\SelectBuilderFactory as SelectFactory;
use Espo\Core\Exceptions\Error;
use Espo\ORM\EntityManager;
use Espo\ORM\Entity;

class NewNoteHook
{
  private $entityManager;

  public function __construct(EntityManager $entityManager, SelectFactory $selectFactory) {
    $this->entityManager = $entityManager;
    $this->selectFactory = $selectFactory;
  }

  public function beforeSave(Entity $entity, array $options = array()) {
    $session = $this->getSession($entity);

    if($entity->isNew()) {
      $template = $this->getTemplate($entity, $session);
      if(!isset($template)) {
        throw new Error("No matching templates were found");
      }
    }
    ...
  }

  private function getTemplate($entity, $session) {
    $query = $this->selectFactory->create()->from('NewNoteTemplate')
    ->withWhere(
        (new \Espo\Core\Select\Where\ItemBuilder)
            ->setAttribute('locations')
            ->setType('arrayAnyOf')
            ->setValue(["{$session->get("location")}"])
            ->build()
        )->build();

    $where = array(
      "clientId" => $session->get("accountId"),
      "assignedUserId" => $entity->get("createdById"),
    );
    $collection = $this->entityManager->getRDBRepository('NewNoteTemplate')->clone($query)->where($where)->find();

    return $template;
  }
}
```

Notice the call to `where()` after the call to `clone()` method. It must be done in that order. I couldn't figure out a way to add another parameter to the `queryBuilder` object, but it didn't matter because what is shown above worked.
