### ISSUE TITLE
Dynamic Logic: dynamic forms configurable through admin's UI

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#227]
* According specific conditions, ability to determine whether field is visible, required or read-only.
* Ability to define what option list will be available for enum field according specific conditions.

**Comment by rodrigoscoelho** [comment]
Great feature. Congratulations

**Comment by rodrigoscoelho** [comment]
When do you plan to launch the 4.3?

**Comment by yurikuzn** [comment]
In a few weeks.
