### ISSUE TITLE
Multi-enum display as label and List (values labels cross each other) on List view

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2270]
**Is your feature request related to a problem? Please describe.**
When a multi-enum field is displayed on List view as (Label and List) there is no margin between the values of the multi-enum field and the label colours cross each other. 

**Describe the solution you'd like**
Add margin to the value list of the multi-enum field when displayed as (Label and List). 
<img width="1280" alt="Screenshot 2022-04-02 at 16 30 25" src="https://user-images.githubusercontent.com/19490674/161392530-54c02c5d-9fb7-4bfe-b8b8-372e3306d080.png">

Version 7.0.9

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/0937c83746f4635a3c602d30df05ce9a2dd707b4
