### ISSUE TITLE
Risk of credentials leak

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2273]
**Is your feature request related to a problem? Please describe.**

WHEN having printTrace enabled 
AND using external log processors like logz.io 
THEN stack traces revealing credentials, may end up at third party providers. 

**Example:**

`[2022-04-06 08:38:41] ERROR: (2006) SQLSTATE[HY000] [2006] MySQL server has gone away; 
GET /Activities/action/popupNotifications; line: 122, 
file: /var/www/crm/application/Espo/ORM/PDO/DefaultPDOProvider.php :: 
#0 /var/www/crm/application/Espo/ORM/PDO/DefaultPDOProvider.php(122): PDO->__construct('mysql:host=prod...', 'XXXXXXUSERNAMEXXXX@...', 'XXXXXXXPASSWORDXXXXXXX', Array) 
#1 /var/w.....` 

**Describe the solution you'd like**

Before pushing the printTrace to the log, usernames/passwords/apikeys should be obfuscated.

**Describe alternatives you've considered**

none

**Additional context**

**Comment by yurikuzn** [comment]
This might be not an issue in PHP 8.2 https://wiki.php.net/rfc/redact_parameters_in_back_traces.

**Comment by kboykov** [comment]
Maybe it is a good idea to see how Nextcloud/Owncloud does it. I know they obfuscate potential secrets in their stack errors which are logged in both local log files and Administration.
https://github.com/nextcloud/server/search?q=obfuscate

**Comment by yurikuzn** [comment]
I will add a note to the documentation that the parameter is not recommended on production.
