### ISSUE TITLE
Enum values are copied to new entities even if the value is not valid

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2274]
**Describe the bug**
When creating a Call, Meeting, or custom entity of type Event, the values in the `Status` field may not be the same. If a value is selected for the status in one entity that does not exist in another entity, the creation process continues as expected, which is a problem. Anything downstream that uses the `Status` field will be confused by the unexpected value.

**To Reproduce**
1. Create a custom entity of type `Event`
2. Add a value to the `Status` field called `New` and set it to be the default
3. Set the custom entity to be the default, which means it will appear first in the entity list of a new calendar event.
4. Create a new event on the calendar. Notice the status is set to `New`.
5. Switch the type of the event to `Meeting`, for example, and the `Status` field will still be set to `New`.
6. Save the meeting.
...
In this case, `New` is not a valid status for `Meeting`, so it should complain.

**Expected behavior**
I expect the list of values in the `Status` field to contain only the valid values based on the entity type. If the selected value does not exist, it should be removed from the list and another value should be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/1170415/162018796-5b97be4e-1975-444c-8b67-e366471eb992.png)
![image](https://user-images.githubusercontent.com/1170415/162018847-ef0ea8eb-2ade-4a36-969f-fea201d7e577.png)

In my installation, `New` is not in the list of values for the `Status` field for the `Meeting` entity. It is only a valid value in the `Session` entity.

**EspoCRM version**
7.0.10

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/efaf1fab79d0d1d9f5a7a0e8786586522e308057
