### ISSUE TITLE
Editing report formulas on mobile

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2285]
**Describe the bug**
When I try to edit a formula for a report on my phone, I am unable to see the formula because the text entry area is malformed.

There is a formula in the report shown below, but I can’t see or select it. Landscape mode didn’t help.

**To Reproduce**
1. Create a report on the computer with a custom formula or expression
2. Edit the report on a phone
3. Scroll to the formula area

**Expected behavior**
I expect the formula to be visible and correctly formatted.

**Screenshots**
![999B8718-E8C6-4C73-A4E5-A457A53915D5](https://user-images.githubusercontent.com/1170415/164219579-9732c11c-41cf-4f2f-a502-de8cb9514165.jpeg)

**EspoCRM version**
7.0.10

**Comment by yurikuzn** [comment]
Paid extensions are out of scope of this repository. Will take a look when get a chance.
