### ISSUE TITLE
After upgrade to v7.1.0 Check Personal Email Accounts cronjob fails (same error on two separate installations)

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2286]
**Describe the bug**
After upgrading version 7.1.0 everything works fine expect cronjob for checking personal accounts. i checked and it produces an error as below: 
[2022-04-21 03:53:24] ERROR: JobManager: Failed job running, job '6059d42e535acffda'. Job CheckEmailAccounts 6227f1d5badf621a2: [0] Bad value in fetch-data.; at /home/intsales/public_html/application/Espo/Classes/Jobs/CheckEmailAccounts.php:61. [] []

**To Reproduce**
1. upgrade to version 7.1.0
2. check cronjobs 
3. all jobs works fine expect (Check Personal Email Accounts) it failed every minute.
...

**Expected behavior**
Not sure what that error means, i have checked this on two seperate installations (both been upgraded to version 7.1.0) and both share the same error (cronjob => Check Personal Email Accounts fails) same error as mentioned above. 
**Screenshots**

**EspoCRM version**
version 7.1.0
**Additional context**

**Comment by yurikuzn** [comment]
Check your `email_account` record in database. What is stored in `fetch_data` field.

**Comment by yurikuzn** [comment]
Try changing this line https://github.com/espocrm/espocrm/blob/7.1.0/application/Espo/Core/Mail/Account/FetchData.php#L66
 
from

```
if ($value === null) {
```

to  

```
if ($value === null || $value === 0) {
```

**Comment by yurikuzn** [comment]
Could you let me know what the problem was? It's important to know.

**Comment by rabiibrahimi** [comment]
Hi @yurikuzn 

I have changed the code as you advised and it solved the problem. now the cron job for Checking personal email accounts works successfully. 

I have closed this before because i was afraid to bother you and thought that since problem with cronjob it might be from server side.

Now everything works fine.  
Many thanks
