### ISSUE TITLE
Small Detail view doesn't show the edge of both right and left panels within

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2290]
**Describe the bug**
The small detail doesn't show the panels edges, both panels on right and panels on left lost their edges on the screen view. so the panels border doesn't appear on both right and left sides. 

**To Reproduce**
1. create a call
2. view the call on small detail view
3. notice the panels with the call (overview) + assignedUser panel don't show the edges.
...

**Expected behavior**
expected to see full panels border.

**Screenshots**

**EspoCRM version**
version 7.1.1
<img width="1280" alt="Screenshot 2022-04-23 at 23 03 52" src="https://user-images.githubusercontent.com/19490674/164948961-9a354e5a-62d9-4a29-bea7-e7dfa582d837.png">

**Additional context**

**Comment by yurikuzn** [comment]
Not a bug. Looks better in hazyblue and dark themes.
