### ISSUE TITLE
Inline edit available in portal when edit permission is set to 'No'

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2292]
**Describe the bug**
In a portal, it is possible for the user to click the inline edit button. The portal role does not allow edit permission.

**Expected behavior**
I expect all editing to be disabled when the edit permission is set to no.

**Screenshots**
![image](https://user-images.githubusercontent.com/1170415/165009125-7c4129b8-32dd-447c-93c9-044da132d221.png)

![image](https://user-images.githubusercontent.com/1170415/165009156-f69365cc-6ce6-467f-9ebd-926d48fe1320.png)

**EspoCRM version**
7.10.0

**Comment by yurikuzn** [comment]
Could not reproduce. No steps to reproduce provided.
