### ISSUE TITLE
Global search not ordering results correctly (with full-text)

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2293]
**Describe the bug**
When I search for a contact name written the full name on the Global Search, my target contact coming at the end of the list instead of being the first one.

**To Reproduce**
Just post the full contact name on global search input, may need to try several full names, sometimes will work as expected.

**Expected behavior**
Most relevant contact must be on the top always.

**Screenshots**
https://user-images.githubusercontent.com/2862528/165056564-c2ea9d4e-fae1-4766-89d7-9f6da4ad77be.mov

**EspoCRM version**
7.0.9

**Additional context**
In the video above I added the relevance value to the return array, it is working perfectly , the problem is that it is ordering as string, so it consider that 9 is before 10 because it compare the first character.
I tried to make a workaround but seems better if you look after it.
So it ordering as following:
9, 8, 7, .......3, 2, 1, 10, .....

**Comment by yurikuzn** [comment]
So this requires full-text be enabled to reproduce.

**Comment by yurikuzn** [comment]
This could be a mysql issue with unions. Order by relevance works fine w/o UNION. Please help with fixing. I don't have enough records in DB to reproduce real-word cases.

**Comment by yurikuzn** [comment]
Does the most relevant record always appear on the page (w/o need to click "show more")?

**Comment by eymen-elkum** [comment]
The problem is not related to union (I believe), the target contact always comes at the end, I need to make several show more clicks to get it

**Comment by eymen-elkum** [comment]
> Does the most relevant record always appear on the page (w/o need to click "show more")?

No, seems to be the general order, not the sub queries orders.

**Comment by eymen-elkum** [comment]
here is it: https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/GlobalSearch.php#L219

**Comment by yurikuzn** [comment]
What exactly wrong with it?

**Comment by yurikuzn** [comment]
I tests it w/o Espo, in MYSQL and it's reproducable. Subqueries are ordered PROPERLY. The bad order appears only with UNION.

**Comment by yurikuzn** [comment]
You can generate an SQL in GlobalSearch.php:

```
echo $this->entityManager->getQueryComposer()->compose($unionQuery);
die;
```
and try it out

**Comment by yurikuzn** [comment]
Seems I found.

Replace https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/GlobalSearch.php#L222

with

```
$queryBuilder->select(Expr::value(1.1), 'relevance');
```

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/caf20a5e61c02d9444140af61dbb05e82b42c3ce

**Comment by eymen-elkum** [comment]
I can confirm it fixed!!
Thank you!!
