### ISSUE TITLE
Forcing client refresh after updates to entities, layouts, etc.

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2294]
**Describe the bug**
After making changes to layouts, formulas, scripts, and many other aspects of the CRM, client browsers may throw errors and display inconsistent information. Forcing a refresh of the client browser usually fixes the issue, but users don't always know to do that.

**To Reproduce**
1. Make changes to an entity that will break something in the interface. For example, remove one-to-many relationship called 'client' and replace it with a field called 'person' that has the same relationship and label.
2. Create a new entity without refreshing the page.
3. Upon submission, the page will error because the code expects a 'person', but it received a 'client'. This is especially relevant if there are hooks in place to look for the 'client' relationship.
4. It is possible to navigate around the site without refreshing because it is a single-page app. Only upon refresh are these types of issues solved.
...

**Expected behavior**
When a new version of EspoCRM is released, the admin portal shows an update notification. That would be very useful for users. A comparison against the cache version or timestamp could be used to indicate that the user is viewing a stale version of the page.

**EspoCRM version**
7.10.0

**Comment by yurikuzn** [comment]
This could be done with websocket. Unfortunately, majority of Epso users does not bother no setup the websocket.

**Comment by yurikuzn** [comment]
Maybe in the future will be implemented.
