### ISSUE TITLE
Entity Manager: Status options not available in 'Ignored groups in Kanban view'

### ISSUE THREAD

**Issue by hunterwebsiteservices** [espocrm/espocrm#2295]
**Describe the bug**
Unable to set any value for "Ignored groups in Kanban view" other than "Closed Lost" for "Opportunities".

Would like to be able to customise EspoCRM a little by changing possible statuses, and also using Kanban view on other Entities.

**To Reproduce**
Cannot add any other statuses from Opportunities. Only "Closed Lost".

Likewise, you can turn on Kanban view for Leads for example. And not be able to add anything at all.

Additionally, changing the value of "Status Field" when editing Opportunities breaks "Ignored groups in Kanban view" and "Closed Lost" disappears. You need refresh the page to fix it.

**Expected behavior**
Should be able to add any of the enum options for the selected "Status Field". For all Entities than allow for Kanban board view.

**Screenshots**
![image](https://user-images.githubusercontent.com/3872103/165421897-88d73e01-3202-423a-a457-25fbd9bbe428.png)

**EspoCRM version**
7.1.2

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/4e7779ee48d35ddc1fa1fae333d75231848e2ac0.
