### ISSUE TITLE
Allow for simplified toolbar in wysiwig editor 

### ISSUE THREAD

**Issue by relyd** [espocrm/espocrm#2297]
**Is your feature request related to a problem? Please describe.**

When exporting data (eg PDF/Template) you want to keep Wysiwig fields as clean as possible, for example only allowing bold,italic and UL.  I want to limit the available options in the editor toolbar, so that users don't get fancy with colors etc.

**Describe the solution you'd like**

I want to be able to select a simplified toolbar when defining the field. 

- Add a "simpleToolbar" boolean option in the field definition [/application/Espo/Resources/metadata/fields/wysiwyg.json](https://github.com/espocrm/espocrm/blob/de39bcf1978b9f48c7dca835a8272052e82a3ad3/application/Espo/Resources/metadata/fields/wysiwyg.json#L29) :
```
     {
         "name": "simpleToolbar",
         "type": "bool",
         "default" : false
      },
```
 
- Set the simple toolbar in the setupToolbar() function in [client/src/views/fields/wysiwig.js](https://github.com/espocrm/espocrm/blob/de39bcf1978b9f48c7dca835a8272052e82a3ad3/client/src/views/fields/wysiwyg.js#L142) 
```
            if(this.params.simpleToolbar){
                    this.toolbar = this.getConfig().get('simpleToolbar');
            }
```
- Add a simple toolbar array in [/data/config.php](https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/defaults/config.php)
```
  'simpleToolbar' => [
    0 => [
      0 => 'style',
      1 => [
        0 => 'bold',
        1 => 'italic',
        2 => 'ul'
      ]
    ]
  ]
```

**Describe alternatives you've considered**
Messing with jquery to dynamically rewrite the summernote toolbar based on the selected field.

**Additional context**
Note that this is not fool proof : cleaning with a serverside strip_tag would be better. 
Furthermore you must set  the param attachmentField to false to disable pasting of clipboard image data as attachment.

**Comment by yurikuzn** [comment]
Define a custom field view for specific field and define the `toolbar` property in the view https://github.com/espocrm/espocrm/blob/7.1.2/client/src/views/fields/wysiwyg.js#L145. No need to modify DOM.

**Comment by analystcmyk** [comment]
Thank you, that works indeed using custom field view.
