### ISSUE TITLE
Upgrade CLI command should automatically enable maintenance mode and disable cron

### ISSUE THREAD

**Issue by hunterwebsiteservices** [espocrm/espocrm#2299]
**Is your feature request related to a problem? Please describe.**
As per upgrading instructions (https://docs.espocrm.com/administration/upgrading/) it is recommended to disable the cron and enable maintenance mode prior to running `php command.php upgrade`

This is a minor inconvenience. Since it involves using both a web browser and command line tool together, rather than simply command line. Which would make admin life a little easier.

Also, I am assuming it is recommended since something might go wrong during the upgrade without these changes. Hence their recommendation. Why risk someone not following the documentation (through forgetfulness or neglect) and having something go wrong with their install?

**Describe the solution you'd like**
Preferably, the `upgrade` command would do this automatically. ie: disable cron and enable maintenance mode, then upgrade, then reenable the cron and disable maintenance mode.

If these are not desired on all upgrades, potentially add flags for their optional execution instead.

Alternatively, add CLI commands (https://docs.espocrm.com/administration/commands/) for enabling/disabling cron and maintenance mode. So administrators can write their own scripts.

This way an administrator can run a script, without the need to open a browser.

If the upgrade already does this, documentation should be updated. Since it implies that this does not happen automatically.

**Describe alternatives you've considered**
Following current upgrade instructions.

**Comment by yurikuzn** [comment]
It already does both.

It's recommended to disable cron manually, to prevent a situations when job is started before upgrading and not finished when upgrade it started.

**Comment by hunterwebsiteservices** [comment]
Awesome, thank you for the response.
