### ISSUE TITLE
UI : TOTP submit button whitespace

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2306]
Small UI improvement :  when entering the OTP, browsers may overlap the Submit button (see screenshot below).  

**Describe the solution you'd like**

Suggest to increase whitespace between Input and submit.

**Describe alternatives you've considered**

Possibly set the autocomplete for the input to "new-password". (tested, worked on FF 100.0 64bit ) 
According to the documentation on https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#browser_compatibility the attribute should be "one-time-code" but this did not prevent the browser from offering "view saved passwords" 

`<input type="text" data-name="field-code" class="form-control" autocapitalize="none" autocorrect="off" tabindex="1" autocomplete="new-password">`

**Additional context**

Example : 

![image](https://user-images.githubusercontent.com/61187964/166872960-a6a5263c-88df-43db-87dc-6ee838864692.png)

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/f31ee10cf72419d328d7ce82803c0be25b20e18f Thanks for reporting.
