### ISSUE TITLE
7.0.10-to-7.1.3后 textFilterUseContainsForVarchar失效

### ISSUE THREAD

**Issue by admin0o0** [espocrm/espocrm#2309]
版本：7.1.3
问题：升级后link字段无法使用“%”检索资料，只能使用“start with”
settings中的textFilterUseContainsForVarchar 无效。

**Comment by analystcmyk** [comment]
@admin0o0 请在发帖前翻译你的报告，不是所有人都能读懂中文。谢谢你。请使用开发者提供的错误描述格式。

Translated : 
Version: 7.1.3
Problem: After the upgrade the link field cannot use "%" to retrieve information, it can only use "start with"
The textFilterUseContainsForVarchar in settings is not working.

**Comment by yurikuzn** [comment]
Might be the same problem. Here's my comment on it: https://forum.espocrm.com/forum/bug-reports/80289-after-upgrading-started-needing-to-use-to-fast-search-autocomplete-again?p=80316#post80316

**Comment by yurikuzn** [comment]
As a workaround you can use a query like `*query`. But please, bug reports need to be with steps to reproduce. I don't know whether full text is enabled or no. Let alone I don't understand Chinese.

**Comment by rodrigoscoelho** [comment]
@yurikuzn , this solves my problem too?

Thanks.

**Comment by yurikuzn** [comment]
Not sure, you can try the fix.

**Comment by rodrigoscoelho** [comment]
Just updated to 7.1.4 and it is still not working...

**Comment by rodrigoscoelho** [comment]
Didn't work. Still doesn't catch a text on the middle of a word.

Here on the company, almost all objects have the "name of object_companyname" standard, so, EspoCRM search got unusable for us since the upgrade. We constantly search for a company name to list all the objects.

**Comment by admin0o0** [comment]
> 不起作用。仍然不会在单词的中间捕获文本。
> 
> 在公司这里，几乎所有对象都有“object_companyname名称”标准，因此，自升级以来，EspoCRM搜索对我们来说变得不可用。我们不断搜索公司名称以列出所有对象。

Yes, this change is very troublesome for users. I hope you can help me after solving it. thank you.

**Comment by yurikuzn** [comment]
> Didn't work

Full-text search should be disabled. This can't work with full-text anymore (and won't be changed).

**Comment by admin0o0** [comment]
> > 不起作用
> 
> 应禁用全文搜索。这不能再适用于全文（也不会更改）。

thank you
After disabling full-text, normal operation is resumed

**Comment by admin0o0** [comment]
> 



> > 不起作用
> 
> 应禁用全文搜索。这不能再适用于全文（也不会更改）。

I found a strange thing. The entity "case" also started full-text search, but it was not affected and still worked normally.

**Comment by rodrigoscoelho** [comment]
How did you disable it?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
17/05/22
10:17:49

Em seg., 16 de mai. de 2022 às 23:37, admin0o0 ***@***.***>
escreveu:

**Comment by rodrigoscoelho** [comment]
How to disable it Yuri? It has to be disabled on the entity configuration?

Em qui., 12 de mai. de 2022 às 03:32, Yuri Kuznetsov <
***@***.***> escreveu:

**Comment by yurikuzn** [comment]
> How to disable it

Full-text search checkbox at Administration > Entity Manager > {Your Entity} > Edit.
