### ISSUE TITLE
Calendar event times changing unexpectedly during save

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2314]
**Describe the bug**
When I save a record that is type 'Event', the end time changes unexpectedly. It looks like the time is being recalculated based on the start time and the duration. The problem is intermittent - saving the same record over and over will produce both results: correct and incorrect. For example, setting an event from 0900 to 1200 and then changing the times to 0859 and 1200 will often result in the record storing 0859 and 1159, which is wrong by 1 minute. The duration was set to 3 hours, and it looks like Espo was trying to maintain a 3-hour event instead of allowing me to set it to 3 hours and 1 minute.

**To Reproduce**
I added debug statements to `application/Espo/ORM/Repository/RDBRepository.php` as follows:
```
 151     public function save(Entity $entity, array $options = []): void
 152     {
 153         $this->processCheckEntity($entity);
 154         $type = $entity->getEntityType();
 155
 156         if ($entity instanceof BaseEntity) {
 157             $entity->setAsBeingSaved();
 158         }
 159
 160         if($type == "Session")
 161           $GLOBALS['log']->debug("session save 1", [$entity->get('dateStart'), $entity->get('dateEnd')]);
 162         if (empty($options['skipBeforeSave']) && empty($options['skipAll'])) {
 163
 164
 165           $this->beforeSave($entity, $options);
 166
 167         }
 168
 169         if($type == "Session")
 170           $GLOBALS['log']->debug("session save 2", [$entity->get('dateStart'), $entity->get('dateEnd')]);
 171         $isSaved = false;
```

I also added debug statements to my beforeSave hook as follows:
```
 44   public function beforeSave(Entity $session, array $options = array()) {
 45     $GLOBALS['log']->debug('session beforeSave 1', [$session->get("dateStart"), $session->get("dateEnd")]);
```

This is what happened in the log when I tried to save a record with a start and end time of 1459 and 1930, respectively:
```
[2022-05-11 16:14:02] DEBUG: session save 1 ["2022-05-10 14:59:00","2022-05-10 19:30:00"] []
[2022-05-11 16:14:02] DEBUG: session beforeSave 1 ["2022-05-10 14:59:00","2022-05-10 19:29:00"] []
[2022-05-11 16:14:02] DEBUG: session save 2 ["2022-05-10 14:59:00","2022-05-10 19:29:00"] []
```
As you can see, the time changed by 1 minute before the code in my hook had a chance to execute. I thought my hook was causing the problem, but I have now seen that the record is entering the hook with the wrong value.

**Expected behavior**
I expect the end time to be what I manually set instead of being tied to the duration. The duration should be calculated based _only_ on the times, not the other way around.

**EspoCRM version**
7.1.3

**Additional context**
I first noticed this issue in the GUI. My users would set times and then they would be wrong, which was shown in the stream as well. Also, the change can be more than 1 minute; sometimes it can be 10 or even 20 minutes, depending on the steps in the duration field. There appears to be a type of 'rounding' going on. After fighting with it in the GUI, I started setting the values programmatically through a Job, but that didn't fix the problem either. After adding debug statements, it seems that the field is being changed somewhere in the parent beforeSave hook for the entity, but I'm not really sure.

**Comment by yurikuzn** [comment]
Maybe here https://github.com/espocrm/espocrm/blob/7.1.4/application/Espo/Core/Repositories/Event.php#L112 ?
This code preserve same duration when data-start is changed but date-end is the same as it was.

**Comment by bandtank** [comment]
That must be what it is. Thank you for the quick response and code snippet. Is there a way to set preserveDuration to false? That seems like exactly what the problem is in my case.

**Comment by yurikuzn** [comment]
Your custom entity should have Repository class. Add the property to the class:

```
    protected $preserveDuration= false;
```

**Comment by bandtank** [comment]
Excellent. Thank you for the pointer. I tested it already and it seems to work. Is this a behavior you think should be exposed to the GUI? Preserve duration would be nice to disable across every event entity in my system, for example. Either way, having a workaround is extremely helpful.

**Comment by yurikuzn** [comment]
Not sure. We don't have mechanism for having special parameters for specific entity types at the moment.

I think it should be moved to an upper level, out of ORM. This feature is sometimes needed. I will investigate when I get a chance.

**Comment by bandtank** [comment]
Thanks. For my use cases, I never want the duration to be preserved, but I can see how it is useful in many other use cases.

**Comment by bandtank** [comment]
FYI - This is the first place I thought to search for a parameter like preserveDuration:

![image](https://user-images.githubusercontent.com/1170415/167919222-f3fdb41e-149d-44a1-9381-6630f4195a75.png)

**Comment by yurikuzn** [comment]
It v7.2 this logic will be totally rewritten.

2 scenarios from UI:

* Date-start is edited using inline-edit -- duration will be preserved (unless disabled);
* Date-start is edited using full-edit form -- date-end will stay the same as it is on the form;


To disable duration preserving you will need to set the parameter `preserveDurationDisabled` to true at metadata > entityDefs > YourEntityType > fields > dateEnd:

```
"preserveDurationDisabled": true
```

**Comment by bandtank** [comment]
Thanks. Does that mean the flag in the repository will be removed or will that still work?

**Comment by yurikuzn** [comment]
Will be removed.

**Comment by bandtank** [comment]
This didn't seem to work:

```
        "dateEnd": {
            "type": "datetimeOptional",
            "notNull": false,
            "view": "crm:views/meeting/fields/date-end",
            "required": true,
            "after": null,
            "audited": true,
            "minuteStep": 1,
            "useNumericFormat": true,
            "default": null,
            "preserveDurationDisabled": true
        },
```

I noticed there is a flag in the repository for every `Event` entity:
```
custom/Espo/Custom/Repositories/TimeOff.php:  protected $preserveDuration = False;
```

Should that be set to `True` instead of using the previously mentioned flag?

**Comment by yurikuzn** [comment]
You can debug https://github.com/espocrm/espocrm/blob/master/application/Espo/Classes/RecordHooks/Event/BeforeUpdatePreserveDuration.php. Whether the class method is called, if called, debug what is happening in the method.

**Comment by yurikuzn** [comment]
> preserveDuration

Search by `preserveDuration` on GitHub does not give any result. It means this property does not have any effect anymore.

**Comment by yurikuzn** [comment]
Here it should skip https://github.com/espocrm/espocrm/blob/master/application/Espo/Classes/RecordHooks/Event/BeforeUpdatePreserveDuration.php#L70.

Maybe you have some old code. Try searching by `preserveDuration` in your codebase.

**Comment by bandtank** [comment]
That's what I noticed as well. I'm debugging the flag now. I'll let you know.

**Comment by bandtank** [comment]
I set the flag to True and False to verify that [this](https://github.com/espocrm/espocrm/blob/master/application/Espo/Classes/RecordHooks/Event/BeforeUpdatePreserveDuration.php#L65) line is working with a debug statement:

`$GLOBALS["log"]->debug("duration",[$preserveDurationDisabled]);`
```
[2022-09-24 18:43:33] DEBUG: duration [false] []
...
[2022-09-24 18:46:55] DEBUG: duration [true] []
```

After setting the flag in the entityDef to True, here is what I observed:
* Modifying the time of dateStart did not preserve dateEnd in the GUI (dateEnd changes with each change to dateStart in real time) or after the save.  [This](https://github.com/espocrm/espocrm/blob/452ea6f1ef3f4c94af10807bc654564eb56960c1/application/Espo/Classes/RecordHooks/Event/BeforeUpdatePreserveDuration.php#L61) statement evaluated to True. I expected dateEnd to remain the same while I was changing dateStart in the GUI and after the save.
* Modifying the date of dateStart resulted in the same behavior as the first point.
* Modifying the time of dateEnd preserved dateStart. [This](https://github.com/espocrm/espocrm/blob/452ea6f1ef3f4c94af10807bc654564eb56960c1/application/Espo/Classes/RecordHooks/Event/BeforeUpdatePreserveDuration.php#L57) statement evaluated to True. The duration updated to match the new time in dateEnd as I was changing it. I expected dateStart to remain the same, which is what happened, but the preserveDurationDisabled flag was never used in the code.

I have not been able to get past the if statements by modifying dateStart or dateEnd in the GUI. After commenting out the if statements, I was able to verify line 65. Nothing in my code is using the legacy $preserveDuration attribute of the entity.

**Comment by yurikuzn** [comment]
>  I expected the client to use the flag as well based on how it I thought it would work.

Was not supposed. I reviewed, it works as expected. When only the date-start passed in payload, it preserves the duration. In any other situations it bypasses the logic.

I want too rest, I work too much.

**Comment by bandtank** [comment]
Ok. I appreciate that it was added, but it doesn't seem to do anything. I'll solve the problem another way.

**Comment by yurikuzn** [comment]
Place the `Duration` field on the layout, it will preserve durations, as for meetings and calls.

**Comment by yurikuzn** [comment]
The initial issue was about opposite issue, that it preserves duration when it was not needed. Not it does not preserves, if it's bypassed, there is no any logic preserving the duration in the back-end.

If you have the `duration` on the layout, it will preserve the duration. The initial issue was not about that.
