### ISSUE TITLE
Duplication checking by overriding Team & Roles.

### ISSUE THREAD

**Issue by yadhurajm** [espocrm/espocrm#2317]
**Describe the bug**
Duplicate Check on Leads not working for the Users in different teams & Roles defined for Read is Own..

**EspoCRM version**
Version 6.1.10

**Additional context**
Please guide me how to override the Roles to check the Duplicate leads among from all the users.

**Comment by yurikuzn** [comment]
No steps to reproduce. Not clear description.

**Comment by eymen-elkum** [comment]
I think he means that if the duplication entity record is not accessed by the user then will not detected
