### ISSUE TITLE
Command renaming custom entity type

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2318]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/178d06650a229ba8ce20b58afb42e15f649f15c6

**Comment by murugappanrm** [comment]
@yurikuzn this is great but very dangerous. I foresee that we could make a mess. It should only be used under extreme care. Suggest that the availability should be controlled at the Role level. Then we can assign special people with authority. 

Just a suggestion

**Comment by yurikuzn** [comment]
Yes. Requires making back-ups before, and testing after. Can be used to resolve issues like: One has created via the admin UI a custom entity called PurchaseOrder, but then the same entity was introduced in a newer version of extension they use in their CRM. It will be possible to rename the existing entity and install the new version of extension.

**Comment by murugappanrm** [comment]
Thank you for the clear update. I understand now. We will try to ensure that this does not happen. Regards.

**Comment by shalb2018** [comment]
How would the command look like for use in a WAMP Stack running on Windows?

**Comment by rabiibrahimi** [comment]
Is there any similar command to rename fields (both on file side metadata and database side) ? I have seen something similar in the past but i can't find the post on the forum.

**Comment by murugappanrm** [comment]
@shalb2018 and @rabiibrahimi 

I am not sure how you guys are using this but, frankly, I would stay clear from this. My reasoning is continuity and support issues. I would not want to change anything that is essential to ensure stability for subsequent releases. This is my opinion. All my life in IT and programming I am sort of afraid of using "aliases". The only exception is Codeigniter 4 where the renaming (or aliasing) of routes is fantastic feature. Its more of a short-code.

**Comment by rabiibrahimi** [comment]
Hi @murugappanrm 

My use case is simple we have custom entities with names that needs to be renamed for better reading as previous dev was not naming fields properly. So i am not willing to change anything core but only custom.

**Comment by bandtank** [comment]
@rabiibrahimi  You may be thinking of my [tutorial](https://forum.espocrm.com/forum/developer-help/developer-tutorials/98736-convert-entity-from-base-to-base-plus) that explains how to convert an entity from one type to another.

@murugappanrm Your point makes no sense. What you're suggesting is for Espo to tell customers to deal with it/suck it up/get screwed if there is a namespace conflict. That is awful advice which, thankfully, Yuri has ignored. In essence, the software has a riskier-than-usual way to implement a fix for an issue that would otherwise render it completely useless. Your comment should have been nothing more than "There may be risks associated with ____, such as ____ and ____." As it stands, all you've done is dump on an idea without providing an alternative or even a specific concern. Having a career in IT is not persuasive and it didn't need to be mentioned.

**Comment by rabiibrahimi** [comment]
@bandtank 

Thanks i appreciate sharing the link, i am not looking to rename any entities but rather want to rename some fields. looks like i need to build my own command line to do that. 
will share on th forum once i do that.

**Comment by bandtank** [comment]
I have renamed fields many times without issue. My process is usually as follows:

1. Put the application in maintenance mode
2. Disable cron and wait 5 minutes to make sure all running jobs have a chance to complete
3. Rename the column in the database
4. Update the entityDef file with the new name
5. grep the project for references to the old field. Update as necessary
6. Search workflows, processes, BPM flowcharts, frontend scripts, and API clients for references to the old field. Update as necessary

**Comment by rabiibrahimi** [comment]
Yeah, i will just see if can put this into a command line hence i have few fields to rename in different custom entities, putting all of this into a command line will help reduce repective work. 
Thanks for sharing :)

**Comment by lexman1958** [comment]
@bandtank 

I am sorry i may have mis-communicated in my post , I am not or asking or intending to ask anyone to stay clear. For my own use, i would stay clear is what i said. The risk is mine not the software. **For me** it would be a a lot more trouble to maintain any customization that i could do without. Espocrm is already fantastic and the use which @rabiibrahimi is good and that is what i would do in the same situation. 

Anyway, thank you for politely advising on my mistake. I close my comments here.

**Comment by Kharg** [comment]
Doesn't seem to work with the latest version, getting "Entity type MyEntity is not custom, hence can't be renamed." even if it's really a custom entity.

**Comment by yurikuzn** [comment]
Anyone can help with a fix? Have no time and unlikely will have any during next months.

**Comment by Kharg** [comment]
I think it's worth fixing in the future, I will try to investigate if I find the time.

**Comment by lazespo** [comment]
Hi @Kharg,

I kindly ask you to note that this command works for me on the latest EspoCRM version, and the custom entity is successfully renamed without errors.

Please tell me which EspoCRM version you used to create this custom entity? Does its name match the names of any default entity (or entity from extensions)? I'll try to reproduce the error you are getting.

**Comment by Kharg** [comment]
Hi @lazespo,

I tried it in Espo 8.1.5
I tried renaming a custom entity (not used in any extension or base espo) from Plural to Singular.

Entity was named "Prestiti" and I tried renaming it to "Prestito".
