### ISSUE TITLE
Time exception in contract

### ISSUE THREAD

**Issue by admin0o0** [espocrm/espocrm#2319]
Version 7.1.5
After upgrading, the 'duration' field in the 'meeting' will change to '0', which will cause the 'dateend' to be incorrect. You need to refresh the page or reopen it to display normally.
![image](https://user-images.githubusercontent.com/24296105/168948073-2f1b87fd-edde-4a5f-b9aa-ae5fe16a527f.png)

**Comment by yurikuzn** [comment]
I can't reproduce.
