### ISSUE TITLE
Populate empty Number fields

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#232]
EspoCRM has the nice "number" field supporting readable numbers with prefix. 
If the field is added at a later time or if data is imported directly into the db the number field should be updateable as one action. 

As a work around one can create a sql script similar to the following but it should be implemented in php since the required parameters are stored in the entityDefs:

```
select @entity_type := 'BusinessTerm';
select @field_name := 'businessTermNo';
select @prefix := 'BT-';
select @padding := 5;

select @i := (select value from next_number 
   where entity_type = @entity_type and field_name = @field_name)-1;

update business_term bt
set bt.business_term_no = concat_ws('',@prefix,lpad((select @i := @i + 1),@padding,'0'))
where (business_term_no is null or business_term_no = "")
;

update next_number nn
set nn.value = @i
where nn.entity_type = @entity_type 
  and nn.field_name = @field_name
;
```

**Comment by yurikuzn** [comment]
A console command added: https://github.com/espocrm/espocrm/commit/c610f8d6a753f69420b58c1bef456ebeef431a3a.

```
bin/command populate-numbers {EntityType} {field}
```
