### ISSUE TITLE
Multiple AssignedUsers field is still editable by roles with Assignment Permission set to NO

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2321]
**Describe the bug**
I have added multiple assignedUsers relationship to the account entity, based on this https://docs.espocrm.com/administration/multiple-assigned-users/#multiple-assigned-users and everything works fine, however for the assignedusers (i have assigned accounts to a certain role which doesn't have the option to assign record at all), however the new field users seems to allow them to select more assignedusers from their session and after that it produce an error 403 (Assignment failure: assigned user or team not allowed). 
**To Reproduce**
1. create a Many To Many between Users and Accounts
2. Assign an account to a user (who has a role with Assignment Permission set to no)
3. log into the user session and try to assign more users 
...

**Expected behavior**
The only missing thing here is to make sure that new multiple assignedUsers (Users) field is not editable by the any user who has a role with (Assignment Permission set to no)

**Screenshots**

**EspoCRM version**
Version 7.1.5

**Additional context**
I just except the system to make the new field (users) not editable by any user who don't have the assignment permission (i think this is just a UI accessibility).

**Comment by yurikuzn** [comment]
It can't be implemented for technical reasons.

**Comment by rabiibrahimi** [comment]
@yurikuzn  thanks for the tip, it actually worked. this make the feature fully working and now the users with no Assignment Permission can't assign users at all. 
Many thanks
