### ISSUE TITLE
User w/o delete access can't mass-convert currency

### ISSUE THREAD

**Issue by buuduyto** [espocrm/espocrm#2327]
Regular users cannot mass update Currency in Currency Converter. It said: "Error 403: Access denied: No delete access for '...'.".
Why do we have to check the permission for delete while the action we want to do is just update the currency. Since the regular user doesn't have delete permission, should we bypass this condition?

**To Reproduce**
1. Create multiple records (could be anything)
2. Log in with regular user
3. Select more than 1 record
4. Click on Action -> Convert Currency
5. Select any Currency option and then click on Update

**Expected behavior**
Regular users should be able to mass update the currency although they don't have delete permission

**Screenshots**
![image](https://user-images.githubusercontent.com/105339533/170662207-775076eb-767c-4281-8e25-c51ec4f560f7.png)

**EspoCRM version**
Still remain on Espo 7.1.7

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/767e775f31ee5d055fc92b603d10aff1a53569b0
