### ISSUE TITLE
Shared calendar views in week mode have different UI elements

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2330]
**Is your feature request related to a problem? Please describe.**
In the calendar, the week view for the logged in user has separators at 15-minute increments. The events also display the beginning and end times. Both features are useful for a variety of reasons. However, in shared calendars, the separators are missing and only beginning times are displayed. 

**Describe the solution you'd like**
I would like both calendar views to look exactly the same. It makes sense for the views to be consistent; I am not sure why the shared view has fewer features.

**Additional context**
Here is how the personal calendar looks in week view:
![image](https://user-images.githubusercontent.com/1170415/171066643-f4bb0fbc-8f99-4e75-8698-e7a541882ead.png)

Here is how a shared calendar looks in week view:
![image](https://user-images.githubusercontent.com/1170415/171066628-b1c3d4b7-9a34-4db3-b397-59834e0bad84.png)

**Comment by yurikuzn** [comment]
There would be multiple events overlapping on the same timeslots. That's why it was not implemented.

**Comment by bandtank** [comment]
That's the issue, though. There are often times when multiple events are scheduled during the same time slot even for a single user. Here is how Outlook handles it for a single person:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1170415/171152210-13ce1921-ef7e-48b8-9a52-4c4d8f5df831.png">

and for multiple people:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1170415/171152455-666fdd6a-1eef-460d-b3b2-21a50d7e0e2d.png">

Espo overlaps the events in single-user mode, which is difficult to visually understand:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/1170415/171152747-0e04c336-a9de-4499-b9b4-a0b0886e0d0b.png">

When multiple users are added, we have a hard time seeing what is happening because too many events stack on top of each other and the gaps can be confusing when many attendees are added to a meeting (the blue meeting, for example):

![image](https://user-images.githubusercontent.com/1170415/171154487-d960c9e7-0458-4397-b79e-d6d22c73e8f5.png)

Making the views the same would fix the issue. Widening the column by adding a horizontal scroll bar would allow events to overlap in time without overlapping visually. Is there a way to override this behavior with a custom view?

**Comment by yurikuzn** [comment]
We use  FullCalendar lib, I can't make any changes there. It would add a maintenance burden.

**Comment by bandtank** [comment]
Ok, that's understandable. Which license level (standard, premium, or oem) do you use and which version of the library (v4, v5, etc.)? I will bring this discussion to the FullCalendar development team.

**Comment by bandtank** [comment]
This is an example of something that would work perfectly, by the way. It's called Vertical Resource View: https://fullcalendar.io/docs/datesAboveResources-demo

I'm not sure if Espo can access that feature, though.

**Comment by yurikuzn** [comment]
Standard of course. No other options for our GPLv3 product.

Currently it's v3. There are some breaking changes in v5, I didn't get a chance to upgrade yet.

**Comment by yurikuzn** [comment]
We use another library for timeline.

The problem is not money. We are open source and can't use any commercial license.

**Comment by bandtank** [comment]
I understand. I was offering in case it was possible, but I assumed it wasn't.

**Comment by bandtank** [comment]
@yurikuzn Can we use the full version now that the license allows for open source use?

https://fullcalendar.io/license

```
Use in GPLv3 open-source projects
Open-source projects that are fully GPLv3-compliant may use FullCalendar Premium freely under the GPLv3 license.

[Read the GPLv3 license agreement »](http://www.gnu.org/licenses/gpl-3.0.en.html)

If you meet the criteria for this license, you may begin using FullCalendar Premium with this [license key](https://fullcalendar.io/docs/schedulerLicenseKey):

var calendar = new Calendar(calendarEl, {
  schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source'
});
```

**Comment by yurikuzn** [comment]
We can't as we have a policy of not using GPL libraries as well as those that have restrictions similar to these.
