### ISSUE TITLE
Optimistic concurrency control not working with inline edit 

### ISSUE THREAD

**Issue by Mixerito** [espocrm/espocrm#2331]
**Describe the bug**
Optimistic concurrency control is a great enhancement, 
but for a full deployment it needs to be working also 
with the inline edit conflicts. 

**To Reproduce**
0. Enable Optimistic concurrency control (e.g. for Tasks)
1. User A: Open inline edit of Description + change something
2. User B: Open inline edit of Description + change something & save
3. User A: Save

**Expected behavior**
Conflict dialog should pop-up in Step 3

**EspoCRM version**
7.1.3

**Comment by yurikuzn** [comment]
Can't be implemented for now as require a lot of changes. Recommend to disable inline edit for the specific field till it's not implemented.

**Comment by rabiibrahimi** [comment]
The optimistic concurrency control triggers only when the view in full edit mode.

**Comment by yurikuzn** [comment]
Do you run with PR changes? It works for me.

**Comment by yurikuzn** [comment]
I don't think it was because of admin. Might be old cached js files were used.

**Comment by yurikuzn** [comment]
Added the fix that concurrency control was not working with inline edit and websocket enabled.

**Comment by yurikuzn** [comment]
Thanks for help.
