### ISSUE TITLE
Calendar event status will not consider custom status field

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2332]
**Describe the bug**
Activities service will always ask for status field as constant, and will not check for custom field on scopes.json files

In case you have no enough time we can help to contribute ...

**Comment by eymen-elkum** [comment]
Ok, I see how much changes will needed for not necessary results ... 
Up to you to close this ticket or keep it open for more thinking ...

**Comment by yurikuzn** [comment]
+ real estate would be affected.

**Comment by eymen-elkum** [comment]
I think that we always can make the changes in backward safe way.

API must never change, status key will remain to be 'status' keyed, will only fetch the correct value.

**Comment by yurikuzn** [comment]
Will consider the ability to disable status field for event entities.
