### ISSUE TITLE
Checking ACL read action on user model error

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2336]
**Describe the bug**
Any action that causes AclManager to check read access on a user model causes error.

**To Reproduce**
Example steps to reproduce the behavior:
1. Create a global/user detail action with `"acl": "read"` requirements. 
2. Try to open any user in detail mode.

**Screenshots**

![Error](https://user-images.githubusercontent.com/44263817/172230605-1615492d-3bd9-460e-a71d-efab3754f7c5.png)

**EspoCRM version**
Latest development version 7.1.7. 

**Possible Fix**
 The bug is caused by a call to the parent method `checkModelRead` which doesn't exist.

https://github.com/espocrm/espocrm/blob/master/client/src/acl/user.js#L40

A possible fix is to call `this.checkModel(model, data, 'read', precise)` instead, which was probabbly intended.

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/2bdde353b1d7c565692b902e1df3c4d2d558a409
