### ISSUE TITLE
Clicking Save button in label manager, without any changes made, causes error 500

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2339]
**Describe the bug**
Clicking Save button in label manager, without any changes made, causes error 500.

**To Reproduce**
1. Go to Administration > Label Manager
2. Click on Save button (do not make any changes)

**Expected behavior**
"Not Modified" notification pops-up.

**Screenshots**
![image](https://user-images.githubusercontent.com/44263817/172703085-c5516021-3706-4b5e-ae2f-e226f17b9919.png)

**EspoCRM version**
Latest development version 7.1.7

**Cause**
The return type of `getScopeData` and `saveLabels` is set to `stdClass`, however `json_decode` returns array, when first argument contains json array (`[]`) which occurs when the user tries to save unchanged labels.

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/e267c8804350444bd1f8de020ca73f15824624fe

Arrays being both hash-maps and normal arrays is one of biggest faults in PHP.
