### ISSUE TITLE
Email sending planner 

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2346]
**Is your feature request related to a problem? Please describe.**
Sometimes we work at late in evening or during weekends and we send emails and it is proper to send emails immediately. in the advanced pack on workflow sendEmail action it allows you to either send email immediately or later on and you provide when to send the email. i was hoping if this feature could be added so when we compose email we can choose to send immediately (should be default option) or later and we can specific when to send the email. 

**Describe the solution you'd like**
I would like to have an option when composing the email to choose either to send immediately or later on. this has been mentioned on [https://github.com/espocrm/espocrm/issues/718](#718)

**Describe alternatives you've considered**
Now i just have to put all emails on hold and keep them in draft until right time to send them during working days/hours. 

**Additional context**
<img width="1470" alt="Screenshot 2022-06-16 at 18 46 22" src="https://user-images.githubusercontent.com/19490674/174139273-ede73bd5-29bf-4b4b-91a1-ac91d8f4881e.png">

**Comment by rabiibrahimi** [comment]
@yurikuzn what do you think of this ?

**Comment by yurikuzn** [comment]
I have too much work. Didn't think.

**Comment by rabiibrahimi** [comment]
ok thanks would just consider this for future feature. 

Many thanks again for your all work and support. we really appreciate your work

**Comment by eymen-elkum** [comment]
This can be done without coding if you have the advanced pack.

Add a new date field to email entity named for ex: "Send At"
Add a scheduled workflow that change the status from Draft to sent for emails that status = Draft & "Send At" before now

**Comment by rabiibrahimi** [comment]
Hi eymen, 

i know it could be done. i am suggesting to have this when composing emails normal. Hence this is a good feature that allow people to schedule when their emails are sent sometimes you work on weekend and you want your email to be sent first thing on Monday morning this kind of feature is very useful for such situation.  a lot CRM are implementing this including salesforce, Zoho etc

**Comment by eymen-elkum** [comment]
Yes, you are right...

If @yurikuzn is okay we can contribute for this function ...

**Comment by yurikuzn** [comment]
Maybe. I'd suggest to have an extension. Such new features require a lot of thinking before being implemented. I'm so loaded with work for now that I can't even check this thread. Sorry. Every new feature added stays forever, and the burden on maintaining and supporting on me and our small team.

**Comment by yurikuzn** [comment]
I recommend having a dropdown menu item, that will show a modal prompting to define a time interval and Scheduled button. After clicking the button the model closes, the compose window closes, a message notification 'Scheduled' is shown.

The email should have a status 'Draft' (to not to incorporate a new status). A new date-time `sendAt` field defines when to send. A new scheduled job `sendScheduledEmails` processes sendings.

**Comment by arkadywtf** [comment]
What do you think on having a single official extension "community-edition"? We could put there new features and have looser rules on accepting pull requests. It could also serve as a place to discuss new features and this repo's issue tracker would be primarily for submitting bugs. Once stable some of the features could later be merged to the core for all.

I'm just spitballing here of course, but is it something that you would get behind?

**Comment by yurikuzn** [comment]
Not sure. Need to discuss with my colleagues first.

**Comment by yurikuzn** [comment]
This will add an extra burden to us to maintain upgrades for this version. In reality many people who purchased anything from use expects that we will provide a free support for all issues like upgrades, sever configuration. It's a nignmare.

**Comment by arkadywtf** [comment]
> This will add an extra burden for us to maintain upgrades for this version. In reality many people who purchased anything from us expect that we will be providing free support for all issues like upgrades, sever configuration. It's a nigntmare.

I meant more of a hands-off approach, but having any such repo under this org could create a different expectations, so I get that. 

Another idea is to create a separate org, an official marketplace or just a simple "awesome" list "awesome-espocrm" where all community extensions and other stuff will be listed, so that newcomers will see that there's a thriving community, so when a feature cannot be added to core there are other places than forum to seek help.

My intentions is for you for having a bit less work with maintenance and for users a chance to get a feature they're looking for.

I like @eymen-elkum idea, so please let me know when it's ready, I'd like to contribute if possible. Thanks.

**Comment by yurikuzn** [comment]
We planned to create a marketplace, but couldn't find resources to do that yet.  Does anybody know a good marketplace software that supports a multi-vendor type?

**Comment by arkadywtf** [comment]
I'd consider [Sylius](https://github.com/Sylius/Sylius) with [Marketplace Plugin](https://odiseo.io/plugins-and-bundles/premium/sylius-mvm-plugin). Maybe it something that could work for you.

**Comment by yurikuzn** [comment]
> I liked the store of suitcrm

They developed their store in-house I believe.

**Comment by hturkoz** [comment]
Hi very nice idea, https://www.sugaroutfitters.com/ was developped by a developper who contribuate to sugarcrm (forget what extension).. and it's a win :)

**Comment by yurikuzn** [comment]
Yep, I remember as I contributed to Sugar a bit back in the day as well.

**Comment by yurikuzn** [comment]
The solution with Workflows (proposed by Eymen) should work fine.

1. For Email entity type, create a custom field *To Send At*.  Add this field to the Side Panel Fields layout.
2. Create a List Report that will return email where *To Send At* is in past and the status is Draft.
3. Create a Workflow of Scheduled type, select the created report.
4. Add an Execute Formula Script action with code `ext\email\send(id);`.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/3200
