### ISSUE TITLE
When sending email from case - email is sent to secondary contact and CC primary contact

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2347]
**Describe the bug**
When sending email from a case where two contacts attached to the case e.g contact A has email a@gmail.com (set as primary contact on the case) and contact B has email b@gmail.com, when sending email from the case i expect the primary contact to be To and CC secondary contact. 

**To Reproduce**
1. create a case and link to it two contacts with emails set on their record
2. try to send email and see who the email will be send to and who will be CC on the email

**Expected behavior**
I expected that the email should be sent to the primary contact of the case and then CC secondary contact. currently it is reversed primary contact is CC in the email and secondary contact is the one the email is sent to. 

**Screenshots**

**EspoCRM version**
version 7.1.7
<img width="1470" alt="Screenshot 2022-06-17 at 16 50 52" src="https://user-images.githubusercontent.com/19490674/174334407-f07768c7-ffaf-4afe-a52e-314e23a2b9bd.png">
<img width="1470" alt="Screenshot 2022-06-17 at 16 51 26" src="https://user-images.githubusercontent.com/19490674/174334415-ad69e408-57dc-4623-b86b-cd53a6fa009a.png">

**Comment by yurikuzn** [comment]
Thanks for reporting. Was bit tricky to fix. https://github.com/espocrm/espocrm/commit/973e8cc77a6f1d8d57c7e55710a9ed35829b2358

**Comment by rabiibrahimi** [comment]
Thanks for fixing much appreciated. i will test it and let you know how it goes.

**Comment by rabiibrahimi** [comment]
Hi @yurikuzn,

I have tested this on the latest version 7.1.8 and it seems it working only on case entity. opportunity is not working as expected, when composing an email from opportunity with multiple contacts all the contacts goes to To field. see attached screenshot for your reference. I have nothing custom on opportunity.

<img width="1470" alt="Screenshot 2022-07-01 at 17 00 39" src="https://user-images.githubusercontent.com/19490674/176929981-8fa4786b-ea3f-4fab-8d89-2df8a88cb76f.png">

**Comment by yurikuzn** [comment]
It's by design. Not a bug.

**Comment by rabiibrahimi** [comment]
> 973e8cc

the fix is for both case and opportunity. is that mean that only when email is sent from case entity then the system will put the primary contact into To and bcc any other secondary contacts. and on opportunity even though we have a primary contact the system will just add all contacts' email to To field ignoring CC ? i thought the fixed you provided would make same logic applied to opportunity which mean when sending email from opportunity the primary contact will be the main contact to send email to and any secondary contacts will be CC into the email.

**Comment by yurikuzn** [comment]
It's how it ever worked. Sorry, I have tons of much more important things to do.

**Comment by rabiibrahimi** [comment]
ok many thanks
