### ISSUE TITLE
Error displaying Actions button functions when reloading page

### ISSUE THREAD

**Issue by TinhNGuyenPTN** [espocrm/espocrm#2348]
**Describe the bug**
Error displaying Actions button functions when reloading page with regular account 

**To Reproduce**
1. Log in as account type Regular 
2. Click on SampleOne  
3. Click on Select All Results ( here we have 2 button actions)
4. Reload page.
5. Click on Select All Results (now we have 4 button actions)

**Expected behavior**
Only “Export, Unfollow” button actions is displayed

**Screenshots**
Before reload
![1](https://user-images.githubusercontent.com/89956690/174521811-6c6ed9ab-03bc-4e27-a170-9ed84a92e2df.png)
After reload
![2](https://user-images.githubusercontent.com/89956690/174521845-da1f5250-7e18-4ca2-87d2-d10888b71da8.png)

**EspoCRM version**
7.1.7

**Comment by yurikuzn** [comment]
Hi,

All data is erased on the demo every 1-2 hours.

**Comment by TinhNGuyenPTN** [comment]
> Hi,
> 
> All data is erased on the demo every 1-2 hours. Could not reproduce.

No i mean the issue here is error displaying Actions button with regular account. It should not show the remove and mass update

**Comment by yurikuzn** [comment]
What I mean that you provided step to reproduce on the demo, but data is already erased. I tried to guess your actions on my local instance, but could not reproduce the issue.

**Comment by yurikuzn** [comment]
I inspected the code, didn't find anything suspicious that could produce this bug.

**Comment by TinhNGuyenPTN** [comment]
can you use this extension and try to reproduce this big ?
[sample-button.zip](https://github.com/espocrm/espocrm/files/8945076/sample-button.zip)

**Comment by yurikuzn** [comment]
This likely to be resolved recently
