### ISSUE TITLE
Bad tree behavior, when formula is present on CategoryTree entity.

### ISSUE THREAD

**Issue by Mixerito** [espocrm/espocrm#2350]
**Describe the bug**
During creation of custom CategoryTree entity, 
I found a strange behavior on tree panel filter and category selection of Record entity.

I have found out, that this issue is common for all CategoryTree entities.

When formula is not empty on CategoryTree entity, the Record cannot select it as a parent from tree view.
Also tree-view panel for filtering on Record page is not working.

**To Reproduce**
1. Add some formula to EmailTemplateCategory entity.
2. Create **2-level** structure of Email Template Categories  (e.g. A > B)
3. Press CTRL+F5
4. Create new Email Template and try to choose B as its Category **-> not selected. (due to JS error)**
5. Open EmailTemplates list view.
6. Expand the tree view panel.
7. Click on B **-> Despite that B is empty, table displays all the Email Templates (not filtering by B)**

**EspoCRM version**
EspoCRM 7.1.3
Advanced Pack 2.10.0

**Comment by rabiibrahimi** [comment]
i have checked and found that it is a bug when selecting a second level (child) category. seems the error is on select function on link.js. The error suggests that the model object that is passed into the select function does not have a get method.

Just create an email template and try to set the category as a child category it will trigger the error. 

this is produced even on latest version 7.4.3
