### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gnovaro** [espocrm/espocrm#2362]
**Describe the bug**
Try to install latest version from git.

**To Reproduce**
1. clone the repo
2. setup nginx vhost
3. run the install process

**Expected behavior**
Im geting an error with grunt compliing the assets, also backbone libs is missing and says is not defined.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/270990/177210439-55b133a2-ff05-4532-9241-73ec266e7826.png)

Login in blank
![imagen](https://user-images.githubusercontent.com/270990/177210509-db73dc93-bd37-4620-941b-994c7c2c50d8.png)

**EspoCRM version**
Latest

**Additional context**

**Comment by yurikuzn** [comment]
`replaceAll` method was introduced in node 15.

**Comment by yurikuzn** [comment]
Try updating node to v15 or higher.
