### ISSUE TITLE
searchInAddressBook not ordering results globally

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2364]
**Describe the bug**
On email composer "to" field when we write the name of contact and there are accounts with similar names will list them before the contact even if the contact is more relevant.

**To Reproduce**
On config:
  'emailAddressLookupEntityTypeList' => [
    0 => 'Account',
    1 => 'Contact',
    2 => 'Lead',
    3 => 'User'
  ],

**Expected behavior**
Sorting all results globally after sub results fetched

**EspoCRM version**
7.1.8

**Additional context**
Note: Results are sorted correctly for every scope,
we may can use the same concept as in Global Search, as it is working properly 
https://github.com/espocrm/espocrm/blob/7e5a7546f2b7c388d563c5cacc006fc1c6187fee/application/Espo/Services/EmailAddress.php#L241

**Comment by yurikuzn** [comment]
I could not reproduce. Worked as expected for me. Need more specific steps to reproduce.
