### ISSUE TITLE
Copy buttons for some or all fields

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2369]
It would be very useful to have a "Copy" button for some or all fields. I often have to edit a record to be able to select the text in a field, which takes a lot of extra time. Something like this:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1170415/178031283-ef3b76f0-2c3b-43e3-8fac-f3ba537e8d0c.png">

It would be awesome if the ability to turn the copy button on and off lived in the field definition of the entity like the 'read only', 'required', etc. parameters.

**Comment by kczereczon** [comment]
you can create custom field https://docs.espocrm.com/development/custom-field-type/ and add icon in it

**Comment by yurikuzn** [comment]
Done for varchar, url, number fields. https://github.com/espocrm/espocrm/issues/2698
