### ISSUE TITLE
Portal User: Admin user CAN NOT Reset Dashboard to Default

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2377]
**Describe the bug**
Admin user CAN NOT "Reset Dashboard to Default", show "Error 403: Access denied" error message.

**To Reproduce**
1. Admin user login EspoCRM.
2. Go to Administration.
3. Go to Portal Users.
4. Create a new Portal User.
5. Click "..." button at top right corner.
6. Click Preferences.
7. Click "..." button next to Cancel button.
8. Click Reset Dashboard to Default.
9. Click Yes.

**Actual behavior**
User CAN NOT "Reset Dashboard to Default" and show "Error 403: Access denied" error message.

**Expected behavior**
Admin user Can "Reset Dashboard to Default" and show "Done" successful message.

**Screenshots**
![Screenshot (140)](https://user-images.githubusercontent.com/97509528/178900035-76d42c1d-b713-42e7-895a-612cae800ccd.png)
![Screenshot (141)](https://user-images.githubusercontent.com/97509528/178900058-71ac26a5-32ed-4154-8af7-d352968c1f15.png)

**EspoCRM version**
Latest version 7.1.7 (Check on Live Demo page: https://demo.us.espocrm.com/)

**Comment by yurikuzn** [comment]
> Admin user Can "Reset Dashboard to Default" and show "Done" successful message.
This was not designed. Portal users  don't have custom dashboard layouts so the error message is legit. The button should be removed.

**Comment by TanDuong-PTN** [comment]
Thank you a lot, Could you please inform me when this action has been removed from UI?

**Comment by TanDuong-PTN** [comment]
> > Admin user Can "Reset Dashboard to Default" and show "Done" successful message.
> 
> This is not designed. Portal users don't have custom dashboard layouts so the error message is legit. The action should be removed from UI.

Thank you a lot, Could you please inform me when this action has been removed from UI?

**Comment by yurikuzn** [comment]
Why does it matter so?
