### ISSUE TITLE
Can not create Email Template

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2381]
**Describe the bug**
Can not create Email Template 

**EspoCRM version**
git master

**Additional context**
click save
Error : Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
file : client\src\views\fields\base.js

https://github.com/espocrm/espocrm/blob/58c5eb8118eaddb3c83c385b81cecf09db16b017/client/src/views/fields/base.js#L1432

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/9faca0fefe953b647fd761ee752f048328d84df2
