### ISSUE TITLE
Make "See more" link for long textareas more visible

### ISSUE THREAD

**Issue by hunterwebsiteservices** [espocrm/espocrm#2382]
**Is your feature request related to a problem? Please describe.**
The "See more" link for extra-long text fields (eg: case description) is easily missed/goes unnoticed.

I've had multiple staff complain that there are no details attached to a case, when there is. I've had to explicitly instruct them of the existence of the content after clicking "See more". Once people know it's there they are okay, but it's a problem with a simple fix.

**Describe the solution you'd like**
Making the "See more" link a `btn btn-default` class should help it stand out more. Or put an icon next to it. Or possibly bold text, or larger text?

![image](https://user-images.githubusercontent.com/3872103/179434993-36c32ec5-ce8a-454b-b0ef-d7a1eb994a9c.png)

![image](https://user-images.githubusercontent.com/3872103/179435296-d126da65-36e5-47cd-af09-cbc5dadcd6b7.png)

**Comment by yurikuzn** [comment]
I tried multiple options but didn't like how it didn't suit the overall style. Ended up with an arrow icon.  It's more discernible now.

![see-more](https://user-images.githubusercontent.com/1006792/183281560-7332c396-0ac3-4922-a37d-7335713ed6dd.png)

**Comment by hunterwebsiteservices** [comment]
Awesome! That's all it really needed to be more noticable :) Thank you.
