### ISSUE TITLE
Bottom panel tabs

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2384]
The ability to have tabs for bottom panels.

![tabs](https://user-images.githubusercontent.com/1006792/179513721-da03fd29-62fd-413e-af03-51bf7a6cf4b7.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c1e5af36c4de3fe90a58e58f4c5903914f80dc2a

**Comment by rabiibrahimi** [comment]
Great addition, many thanks for adding this, it really enhanced the user experience in the CRM. One note for the bottom tabs sometimes it break the order and doesn't display the tabs, when dragging the tab-break it inherits the last tab-break label and breaks down so it doesn't show any tabs. just need to put them in order carefully other than that i have checked and tested conditionally showing or hiding a tab and its panel and it works great. One note in terms of the design do you think it will be better to add some margin-bottom:5px to btn-group class to add some space between the group button tabs and its content. please see attached screenshot for your reference. 
<img width="1470" alt="Screenshot 2022-07-18 at 23 19 03" src="https://user-images.githubusercontent.com/19490674/179627709-355938c2-85bd-43eb-80dd-79ff2cd3c80f.png">

**Comment by yurikuzn** [comment]
>  it break the order and doesn't display the tabs, when dragging the tab-break it inherits the last tab-break label and breaks down so it doesn't show any tab

When two tab-breaks one after another?

**Comment by rabiibrahimi** [comment]
I have made more test and it seems to work fine, i think as mentioned when building the tab-break just need to respect the order. everything sounds to work fine now. Is this applied to the side panels (right panels) activities task history etc ?

**Comment by yurikuzn** [comment]
Only for bottom panels.

**Comment by rabiibrahimi** [comment]
any chance this will added in future for side panels as well sometimes we move some relationships to the side panels and it become missy due to many panels sticked on each other, it would be great if bottom panel tab-break would be applicable to the side panels as well of course in future when you have time for it. The tabs features is a great addition looks great and very useful 
many thanks again for your hard work and effort, much appreciated.
