### ISSUE TITLE
Theme improvements

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2386]
Values will be defined in CSS variables:

* Border radius
* Border width
* Shadows
* And others

Vertical & Horizontal themes will be joined (into one theme) with a separate Navbar parameter introduced.

Sakura theme after improvements:

![theme](https://user-images.githubusercontent.com/1006792/180217842-6210cdc0-38ae-475b-aef5-d537031a67e6.png)

**Comment by rabiibrahimi** [comment]
love it looks great. can't wait to upgrade to v 7.2
many thanks for your effort it is the best CRM ever used so elegant.
