### ISSUE TITLE
2FA Security setting: Admin can update another's 2FA setting with any password

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2388]
**Describe the bug**
2FA Security setting: Admin can update another's 2FA setting with any password.

**To Reproduce**
1. Admin user login EspoCRM.
2. Go to Administration.
3. Go to Authentication.
4. Check "Enable 2-Factor Authentication"
5. Click "Save".
5. Go to Administration.
6. Go to Users.
7. Edit a user.
6. Click "Security".
7. Click "Enable 2-Factor Authentication".
8. Click "Apply".
9. Enter any characters (wrong password) in "Your current password" field.
10. Click "Apply".

**Actual behavior**
Passed the password check and show the Scan QA-code modal.

**Suggestion**
That 2FA should either not be configurable for another user or if it is the password check should be removed.

**EspoCRM version**
Latest version 7.1.9.

**Comment by yurikuzn** [comment]
Fixed so that admin's password is checked. https://github.com/espocrm/espocrm/commit/e9de1164004b5390557bde5761b57692cad75e89

Thanks for reporting.
