### ISSUE TITLE
Add ability for setting own language object for custom translation in Htmlizer

### ISSUE THREAD

**Issue by kczereczon** [espocrm/espocrm#2391]
https://github.com/espocrm/espocrm/blob/9e6e8f580c0fa8c7bdd81172ed71b775989fc5bf/application/Espo/Core/Htmlizer/Htmlizer.php#L89

I'm currently working on rendering custom email message, and I can't translate enum option because, language by default is set to en_US

**Comment by kczereczon** [comment]
create setter or something like that

**Comment by yurikuzn** [comment]
Did you try:

```
$injectableFactory->createWith(Htmlizer::class, [
    'language' => $languageInstance
]);
```
