### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2393]
* *Ctrl+Enter*: save, post
* *Escape*: cancel
* *Ctrl+S*: save and continue editing
* *Ctrl+Space*: switch to edit

**Comment by o-data** [comment]
Will these keyboards shortcut be display somewhere inside EspoCRM? Or we will need to copy/paste it in our knowledge database or something like that.

**Comment by yurikuzn** [comment]
Some will be displayed on button hover, some not. I've already added to the documentation repository.
