### ISSUE TITLE
Pressing TAB KEY on a multi-enum field adds the next option avallabile to the list

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2394]
**Describe the bug**
Pressing TAB KEY on a multi-enum field adds the next option avallabile to the list,

**To Reproduce**
1. create a new multi-enum field and add options
2. . try the field in the detail view and press tab

**Expected behavior**
TAB key should switch to the next field in the view instead of adding options to the array of the field.

**EspoCRM version**
7.1.9

**Comment by yurikuzn** [comment]
This is issue in the selectize libriary.

**Comment by yurikuzn** [comment]
The issue is already fixed in master branch. I mistook it with another issue that pressing enter or ctrl + enter while focusing on the input selects the first option.
