### ISSUE TITLE
When composing an email on small screen (last elements on tool bar are half visible)

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2395]
**Describe the bug**
When using small device (mobile or tablet) to compose an email some of the tool bar elements on the body get hidden and unaccessible.
**To Reproduce**
1. open crm on small device mobile or tablet
2. compose email
3. check body tool bat
...

**Expected behavior**
expected behavior is to be able to see the whole toll bar element, solution below: 
@media all and (max-width: 750px) {
.panel.note-editor .panel-heading {
    padding: 5px 5px 5px 5px;
    **height: calc(40px + 70px);**
}
}
**Screenshots**

**EspoCRM version**
master branch
<img width="1470" alt="Screenshot 2022-07-31 at 12 40 48" src="https://user-images.githubusercontent.com/19490674/182024898-9c462c0c-3615-4d3f-9f7d-a5e0b4a2333f.png">
<img width="1470" alt="Screenshot 2022-07-31 at 12 41 35" src="https://user-images.githubusercontent.com/19490674/182024902-50270059-07db-4f2a-83b2-0007a54376d1.png">

**Comment by yurikuzn** [comment]
Master is in development process. There are lot of issues.
