### ISSUE TITLE
Dashboard layout: Duplicate tab name can be saved

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2397]
**Describe the bug**
Dashboard Layout: Admin user can update duplicate Tab list name

**To Reproduce**
1. Admin user login EspoCRM.
2. Go to Preferences.
3. Scroll to User Interface > Dashboard Layout.
4. Click "Edit Dashboard" button.
5. In Tab List, create 2 new tabs name "A" and "B".
6. Click "Save".
7. Click "Edit Dashboard" button again.
8. Rename "B" tab to "A".
9. Click "Save".
10. Click "Save".

**Actual behavior**
Admin user can update Dashboard Layout successfully with duplicate "A" tab name.

**Expected behavior**
Admin user CAN NOT update Dashboard Layout, show error message "Dashboard Tab List is duplicated".

**Screenshots**
![Screenshot 2022-08-05 092536](https://user-images.githubusercontent.com/97509528/182988428-d171f0d8-e397-4ba0-8e7d-511fa947dedb.png)

![Screenshot 2022-08-05 092009](https://user-images.githubusercontent.com/97509528/182988214-636e3e45-da85-40c7-b438-369106029f99.png)

![Screenshot 2022-08-05 092120](https://user-images.githubusercontent.com/97509528/182988238-870c5d9a-af6e-4e98-8857-9afabb08c14f.png)

**EspoCRM version**
EspoCRM version 7.1.9.

**Comment by yurikuzn** [comment]
Thanks for reporting the bug. Fix: https://github.com/espocrm/espocrm/commit/01cc896972fbec84ca432f8d244a40c3a284c098.
