### ISSUE TITLE
Separate view for stream note records

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2398]
Each stream note record can be displayed on a separate view with a unique URL so that one may share it with somebody. The date field will be a link to the view.

![note-link](https://user-images.githubusercontent.com/1006792/183035310-d87d4d60-ec76-414b-a057-a45749a4ff2f.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/ec0649f65aa6febfcb05223358db707c53e5fb50

**Comment by Kharg** [comment]
Can the date also include the note time? That would be useful.

**Comment by yurikuzn** [comment]
When you hover the pointer, time is shown.
