### ISSUE TITLE
Activities panel: Create icon-buttons

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2399]
Create an email, meeting or call.

![create-buttons](https://user-images.githubusercontent.com/1006792/183436629-0f6569c6-2fbf-4d9a-a472-1d3bf2614158.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/ab24606bdf7763a977a49e1620b594a68813cfd7

**Comment by Kharg** [comment]
Is the limit for activitiesCreateButtonMaxCount just 4? Adding 5 doesn't do anything
