### ISSUE TITLE
Security headers for client page

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2402]
* `Content-Security-Policy` – disallowing external script usage, unsafe inline scripts;
* `X-Frame-Options: SAMEORIGIN`;
* `X-Content-Type-Options: nosniff`;
* `Strict-Transport-Security:  max-age=10368000`.

#### Content security policy

* Can be disabled with the config parameter `clientCspDisabled`.
* External scripts can be allowed with the config parameter `clientCspScriptSourceList`.

**Comment by torgeirl** [comment]
To anyone searching for why their Strict Transport Security (HSTS) suddenly yields «Server provided more than one HSTS header»: this change is why.

The `clientSecurityHeadersDisabled` setting can be found in `data/config-internal.php`; just change it from `false` to `true` and reload your proxy, ie `service nginx reload`.

----

@yurikuzn: the comment above is mostly just to add search hits for `HSTS` in this repo so others can find the solution more easily, but let me add that the default max-age does seem very short. Ie. [Qualys' SSL Labs](https://www.ssllabs.com/ssltest/) will warn it is too short, and [Mozillia's SSL config tool ](https://ssl-config.mozilla.org/) recommends 63072000.

**Comment by yurikuzn** [comment]
I'd recommend to disable headers added by a webserver and rely on headers added by Espo as they are specific for the application.

**Comment by yurikuzn** [comment]
I added a header-specific disabling parameter: https://github.com/espocrm/espocrm/commit/04eaf4db02d0fb86d6674d41c656eae5189e54e3.

**Comment by torgeirl** [comment]
> I added a header-specific disabling parameter: [04eaf4d](https://github.com/espocrm/espocrm/commit/04eaf4db02d0fb86d6674d41c656eae5189e54e3).

Excellent, thank you! :+1:

**Comment by torgeirl** [comment]
Tested the new parameter now that 7.3.x released, and updated my post. Thanks again!
