### ISSUE TITLE
Backend errors are not shown in the UI.

### ISSUE THREAD

**Issue by AgentT30** [espocrm/espocrm#2403]
**Describe the bug**
Backend errors are not shown in the UI.

**To Reproduce**
1. Add a backend error on an inline edit field, in a hook beforeSave() for example:
2. `if(isAttributeChanged('fieldName') && $entity->get('fieldName') != 'defined_value') throw new BadRequest('Bad value entered', 400);`

**Expected behavior**
 When the user tries to change the `fieldName` in the UI using inline edit, he/she should get the "Bad value entered" in the UI.

**What is happening?**
 When the user tries to change the `fieldName` in the UI using inline edit, he/she sees "Bad value entered" for a split second but then get the "Error Occured" message.

**EspoCRM version**
v7.1.9

**Additional context**
If there is an error from the backend, that error must be shown in the UI. Looks like [this part of the code](https://github.com/espocrm/espocrm/blob/88063f5ec79771a1fcd0c2328908e37eb92a84d8/client/src/views/fields/base.js#L668) overrides the backend error to be shown in the UI.
Solution suggested [here](https://forum.espocrm.com/forum/developer-help/79948-errors-not-being-shown-on-the-ui-after-upgrade-to-7-0-10-from-6-1-0?p=79959#post79959) does not work as the above method overrides this as well.

**Comment by yurikuzn** [comment]
This code already is not used in the master. Should work fine. Moreover you can have error messages translated, example here: https://github.com/espocrm/espocrm/blob/518fe07ea1f23a997cb524267918a197d32c4f35/application/Espo/Core/FieldValidation/Exceptions/ValidationError.php#L55.
