### ISSUE TITLE
Wysiwyg field type: Validation messages display in wrong place.

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2404]
**Describe the bug**
Wysiwyg field type: Validation messages display in wrong place.

**To Reproduce**
1. Admin user login EspoCRM.
2. Go to Administration > Entity Manager.
3. Create a new Entity name 'Test'.
4. Go to Fields.
5. Add a new Field name 'Wysiwyg' with the field type is Wysiwyg and check the Required checkbox.
6. Go to Layouts.
7. Add the 'Wysiwyg' field to Detail.
8. Go to the 'Tests' list screen.
9. Click 'Create Test'.
10. Click "Save".

**Expected behavior**
Validation messages display below input field.

**Actual behavior**
Validation messages display at the top left corner of the browser.

**Screenshots**
![Screenshot (159)](https://user-images.githubusercontent.com/97509528/184300113-e361938d-8db1-4759-b859-d7032f542c5c.png)

**EspoCRM version**
EspoCRM version 7.1.9.

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/d0f65e5fd958a4b2781b36c0016e8746c1b3b826.
