### ISSUE TITLE
Meeting - Send Invitations: The ICS files do not pass RFC 5545 specification - iCalendar.

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2405]
**Describe the bug**
Meeting - Send Invitations: The ICS files do not pass RFC 5545 specification - iCalendar.

**To Reproduce**
1. Admin user login EspoCRM.
2. Go to Meetings.
3. Create a new Meeting.
4. Click 'Send Invitations'.
5. Login your email account that receive the invitation email.
6. Open the invitation email, download the Meeting.ics attached file.
7. Go to https://icalendar.org/validator.html.
8. Upload the Meeting.ics file, then click 'Validate'.

**Expected behavior**
Show success message: "Success! No errors found."

**Actual behavior**
Show error message:
Problem! Found 1 error
Errors
Lines not delimited by CRLF sequence [near line # 1](javascript:void(0);)
Reference: [RFC 5545 3.1. Content Lines](http://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html)

**Screenshots**
![Screenshot 2022-08-12 170959](https://user-images.githubusercontent.com/97509528/184333610-9a9bd8e9-6fca-4a40-a037-4eb4d283824d.png)

**EspoCRM version**
EspoCRM version 7.1.10.

**Additional context**
The line break should be \r\n (CRLF) instead of \n (LF).

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/831e589b3dd519c313beb1bd7c504d6a48386ceb
