### ISSUE TITLE
Add a new common hook type (afterView)

### ISSUE THREAD

**Issue by dmitriim** [espocrm/espocrm#2406]
Hooks doc https://docs.espocrm.com/development/hooks/

**Is your feature request related to a problem? Please describe.**

We are currently building a reporting tool that could give us answers to questions like:
• which opportunities have been viewed by team X in the last 5 days?
• which opportunities have been viewed by the most team members?
• which accounts have been viewed but not updated?
• which opportunities HAVE NOT been viewed after being created in the last 7 weeks.

**Describe the solution you'd like**

Would be good to have a new type for the hooks like afterView. So we can hook a logic after a user viewed an entity.

**Describe alternatives you've considered**

None without hacking the core.

**Additional context**

None

**Comment by yurikuzn** [comment]
There's `beforeRead` hook: https://docs.espocrm.com/development/metadata/record-defs/#beforereadhookclassnamelist

**Comment by dmitriim** [comment]
Thanks @yurikuzn! That's awesome. I got it working. 

FYI there is a little typo in https://docs.espocrm.com/development/metadata/#extending 

`custom/Espo/Custom/Resources/Metadata/entityDefs/Account.json`

should be (lowercase metadata)

`custom/Espo/Custom/Resources/metadata/entityDefs/Account.json`

**Comment by Kharg** [comment]
@yurikuzn do you have any example hooks using the ReadHook interface? I can't get it to work.
@dmitriim could you show me how you implemented it please?
