### ISSUE TITLE
Cannot use bottom panels in create record view

### ISSUE THREAD

**Issue by qbejs** [espocrm/espocrm#2407]
Hi,

Is it possible to show bottom panels in create/quickcreate view ? In clientDefs I've definied bottom panels for edit and editSmall but no success.

**Comment by yurikuzn** [comment]
Hi,

It works for create view (see Meeting entity as example). Not sure about quick-create. There's no support to do it via UI.

**Comment by yurikuzn** [comment]
It's disabled here: https://github.com/espocrm/espocrm/blob/7.1.11/client/src/views/record/edit-small.js#L33. Set it to `'views/record/edit-bottom'` in a extended view class.
