### ISSUE TITLE
Cannot require JS library that doesn't explicitly export to window

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2408]
**Describe the bug**
The `_execute` method in the [loader](https://github.com/espocrm/espocrm/blob/master/client/src/loader.js#L206) has changed from just a simple `eval` to creating a new function object, which is then called. This is equivalent to executing the library code inside an anonymous function. As a consequence, some libraries are broken.

**Example:**

```js
// Old approach
eval('var MyLibrary = \'foo\'');
console.log(window.MyLibrary); // foo

// New approach
(new Function('var MyLibrary2 = \'foo\'')).call(window);
console.log(window.MyLibrary2); // undefined
```

This will, for example, break the Vue library.

**EspoCRM version**
Upstream development version.

**Comment by yurikuzn** [comment]
Ha, funny thing right in this moment I'm looking into this issue.

**Comment by yurikuzn** [comment]
I don't know how to handle this yet. I have only an idea to fix those libraries.

**Comment by yurikuzn** [comment]
Thanks for the idea.

I think would be better to append always if exports to the `window` to maintain backward compatibility. https://github.com/espocrm/espocrm/commit/3d9c5c01d2f6f6ef097d6c15d6114a97b57b5055.
