### ISSUE TITLE
"View as User" feature for admins

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2411]
The title is pretty much self-explanatory. Might be especially useful when testing ACL settings.

I have managed to implement the feature in my custom extension, so if this request gets accepted I can contribute with PR.

**Comment by yurikuzn** [comment]
A 'login as user' feature was planned for the future. Is it what you mean?

**Comment by mozkomor05** [comment]
Yes, it is.

**Comment by yurikuzn** [comment]
If you can provide a code, please. This is quite critical feature that needs very severe inspection before implementing. I did some design in the past but set it aside for a while.

**Comment by mozkomor05** [comment]
I'll submit PR when I get home.

**Comment by yurikuzn** [comment]
Related: https://github.com/espocrm/espocrm/issues/1493

**Comment by yurikuzn** [comment]
BTW specially for this feature the login result has a user and logged-user separately: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Authentication/Result.php.

**Comment by mozkomor05** [comment]
> BTW specially for this feature the login result has a user and logged-user separately: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Authentication/Result.php. But this may change, as design is not yet determined.

I didn't use it in my original design for two reasons:

1.  There are additional conditions that depends on `$user` that could result in error. Since the `login-as-user-id` information is stored in cookies, this could cause unpleasant situations, for example when administrator switches to another user and cannot switch back without manually deleting cookies.
2. I developped the feature in extension, so I couldn't really rewrite any of this stuff.

However I am willing to change the design.

**Comment by yurikuzn** [comment]
BTW we don't store username in cookie anymore. If you are able just to share code, so I could look, not necessary PR. I had an idea how it implement it, but was not 100% sure and needed in-field testing, as we still need 2FA, LDAP and custom auth working.

**Comment by mozkomor05** [comment]
Sure. The solution is very "hacky" and I don't really like it. I hope it can at least serve as an inspiration: https://github.com/espocrm/espocrm/compare/master...mozkomor05:espocrm:login-as-user

**Comment by mozkomor05** [comment]
E.g. changing the `user` from in container by requiring `User` in constructor and then resetting its attributes.

**Comment by mozkomor05** [comment]
The "hacky" solution has few advantages - there's no way it could break LDAP, 2FA... as the user switch is happening after successful login, and it is easy to implement in the extension.

**Comment by Kharg** [comment]
@mozkomor05 Do you also have it packaged as an extension ready to share? :)

**Comment by mozkomor05** [comment]
https://github.com/mozkomor05/espocrm-login-as-user-extension/releases/latest

**Comment by Kharg** [comment]
@mozkomor05 thank you, from a quick look it looks to be working fine.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/2444

**Comment by rodrigoscoelho** [comment]
GREAT!!!!





Em qua., 21 de set. de 2022 às 10:26, Yuri Kuznetsov <
***@***.***> escreveu:
