### ISSUE TITLE
Htmlizer.php checkboxTag

### ISSUE THREAD

**Issue by czcpf** [espocrm/espocrm#2413]
Hello,

The following code for checkboxTag seems to have a bug.

```php
if (in_array($option, $list)) {
    $html =
        '<input type="checkbox" checked="checked" name="1" ' .
        'readonly="true" value="1" style="'.$css.'">';
} else {
    $html = '<input type="checkbox" name="1" readonly="true" value="1" style="color: '.$css.'">';
}
```
when rendered in the browser, both options end up being checked even though my checkbox field record only has 1 of them checked. It looks like the issue is them having the same name="1" above because the code below has the correct behavior (for a field with only 2 options.

```php
if (in_array($option, $list)) {
    $html =
        '<input type="checkbox" checked="checked" name="1" ' .
        'readonly="true" value="1" style="'.$css.'">';
} else {
    $html = '<input type="checkbox" name="2" readonly="true" value="1" style="color: '.$css.'">';
}
```
It also seems like the checkboxes are not readonly because I'm able to click them?

**Comment by yurikuzn** [comment]
It works well for me (if I don't specify color that is not working in firefox). Steps to reproduce are needed.

**Comment by czcpf** [comment]
Good day Yuri, I've looked into this further and submitted a [bug report](https://github.com/espocrm/espocrm/issues/2417) which details the confusion and/or bug here.  I appreciate your dedication and work on this project. One point of clarification for me, when the end-user prints to pdf, is this intended to be downloaded immediately as a file? Currently, it displays in the pdf viewer of client browser and the behavior (as described in the bug report) isn't the same between the browser viewer and when the end-user saves/exports the output directly from the browser menu.
