### ISSUE TITLE
Working Calendar

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2415]
Features:

* Week schedule (weekdays can have different schedule);
* Working day ranges (e.g. working weekends, days with a non-standard schedule);
* Non-working day ranges (leaves, holidays, etc.).

A Calendar record can be:

* Selected as a system default;
* Selected for a team (will be applied to user through the *default team*);
* Selected for a specific user.

Ranges can be applied to a whole calendar (e.g. holidays for a whole team) or to a specific user (e.g. leave).

Formula functions:

* `ext\workingTime\addWorkingDays(DATE, DAYS)` – adds working days, the result will be a date-time pointing at the beginning of the day  (`00:00`) in a corresponding time zone;
* `ext\workingTime\findClosestWorkingTime(DATE)` – finds the beginning of the next  closest working time slot;
* `ext\workingTime\getSummedWorkingHours(FROM, TO)` – get a total number of working hours between two dates;
* `ext\workingTime\getWorkingDays(FROM, TO)` – get a number of working days between two dates;
* `ext\workingTime\hasWorkingTime(FROM, TO)` – whether a date range contains any working time;
* `ext\workingTime\isWorkingDay(FROM, TO)` – whether a date falls into a working day.

Functions can be applied for the default calendar, user calendar or team calendar. The entity type ( `'User'` or `'Team'`) and the entity ID can be passed as last two arguments.

Non-working days having a different background color:

![calendar-1](https://user-images.githubusercontent.com/1006792/191037982-ee21833a-1b8e-4657-a6e1-63eadcea5f92.png)

Non-working timeslots:

![calendar-2](https://user-images.githubusercontent.com/1006792/191037986-b75eb987-8687-4bb8-b46b-b782c5b7ce7a.png)

Timeline has non-working ranges with a different background color:

![Timeline](https://user-images.githubusercontent.com/1006792/191037988-22e7c8ac-6c27-448c-a63e-af13914aa50a.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/4d7e56e7b794b6370db58e922429df32e4ffa6d9

**Comment by emillod** [comment]
@yurikuzn it will also work with assignment rules? For example, if there is a new case from email, system will not assign it to users which are on sick leave for example?

**Comment by yurikuzn** [comment]
Not implemented. It would be tricky as we can't know if it's a leave,  1-day off, a weekend or a out of working hours for specific user. 

One can utilize formula (+bpm/workflow) to re-assign a user if they are not available.

**Comment by yurikuzn** [comment]
Maybe in future, as a configurable parameter.

**Comment by rabiibrahimi** [comment]
non working days are they supposed to be blocked? meaning users shouldn't be able to create any activities on non working days currently non working days still allow users to create activities such as call - task - meeting. is this how it supposed to to function ? still trying to understand how the working calendar works.

**Comment by yurikuzn** [comment]
No. Never stated that.

**Comment by yurikuzn** [comment]
As we have problems with upgrades, I'm too busy these days.
