### ISSUE TITLE
Htmlizer.php not working as expected for checkBoxTag

### ISSUE THREAD

**Issue by czcpf** [espocrm/espocrm#2417]
**Describe the bug**
CheckboxTag codeblock in Htmlizer.php does not behave as expected when printing to pdf using pdf Template.

**To Reproduce**
1. Create a new entity called 'TestEntity' of baseType as shown below.
2. Create a new checkbox field in testEntity called 'actionType' with two options 'New Registration' and 'Renewal of Registration'       as shown below. Leave all other field options as default.
3. Add the new actionType checkbox field to the detail layout for testEntity
4. Create a new TestEntity record called 'Test', with only the first option 'New Registration' selected as shown below and save. 
5. Create a new pdfTemplate called 'Test Template', using Entity Type 'TestEntity', adding the 'actionType' field with checkboxTags to the body code block as shown below. (Be sure do paste the raw code below in the 'code' editor of the code block).
```html
<p>New Registration: {{checkboxTag actionType option='New Registration'}}</p>
<p>Renewal of Registration: {{checkboxTag actionType option='Renewal of Registration'}}</p>
```
6. View the detailed record 'Test' created in step 4, and choose 'Print to PDF' from the dropdown menu '...' next to the edit button as shown below.
7. Select the 'Test Template' you created in step 5 from the modal window as shown below.
8. Observe the pdf output as shown in the browser window. Notice that both options 'New Registration' and 'Renewal of Registration' are checked.
9. Selecting either option checkbox changes both simultaneously (checked or unchecked) and neither is readOnly.
10. Modify /application/Espo/Core/Htmlizer/Htmlizer.php, such that each of the two generated input fields gets a unique name starting at line 715: 

FROM:
```php
if (in_array($option, $list)) {
    $html =
        '<input type="checkbox" checked="checked" name="1" ' .
        'readonly="true" value="1" style="'.$css.'">';
} else {
    $html = '<input type="checkbox" name="1" readonly="true" value="1" style="color: '.$css.'">';
}
```
TO:
```php
if (in_array($option, $list)) {
    $html =
        '<input type="checkbox" checked="checked" readonly="readonly" value="1" ' .
        'name="checklistItem-'.
        str_replace(' ', '-', $option).'"' .
        'id="checklist-item-'.
        str_replace(' ', '-', $option) .
        '" style="'.$css.'">';
} else {
    $html =
        '<input type="checkbox" readonly="readonly" value="1" ' .
        'name="checklistItem-'.
        str_replace(' ', '-', $option).'"' .
        'id="checklist-item-'.
        str_replace(' ', '-', $option) .
        '" style="'.$css.'">';
}
```
11.  Clear cache, and repeat step 6-8 to observe the pdf output shown in the browser window. Notice that only the top option 'New Registration'  is checked, which is the expected behavior. Notice also that, although the expected behavior is that the fields are readOnly, selecting each option individually does not effect the other as it does without this modification and would be the expected behavior for a non-readOnly field.
12. Compare behavior of printing to pdf for with and without code modification to Htmlizer.php. For example, with current code, if you do  nothing to the non-read only check boxes and save/export as PDF from the browser menu, the result is shown in Test1.pdf. While this does show the option 'New Registration' checked, it doesn't render the second checkbox. Only the label is rendered.  If you then uncheck the first option 'New Registration' in the browser window, it unchecks both and upon save/export as pdf from browser window the result is shown in Test1_1.pdf. In this case, the pdf renders two non-checked, editable checkboxes. If you next check the first option again and repeat the save/export as pdf from the browser window the result in shown in Test1_2.pdf. Notice both files show two unchecked, editable checkboxes. Compare this behavior now with the code modification. The resultant pdf files are attached as Test2.pdf, Test2_1.pdf, Test2_2.pdf. Here, doing nothing to the rendered output and saving Test2.pdf shows the 'New Registration' checked as well as a readonly 2nd checkbox. If you then uncheck the first option 'New Registration' in the browser window, save/export as pdf from the browser window, the results is shown in Test2_1.pdf, which shows two non-checked, editable checkboxes similar to Test1_1.pdf. However, if you now check the first option again and repeat the save/export as pdf from the browser window the result is show in Test2_2.pdf. Which, correctly shows the first option checked (although it is no longer readonly), and the 2nd option not checked which would be the expected behavior for non-editable fields. 

**Expected behavior**
I expect only the first option 'New Registration' to be checked since that is the state of the 'actionType' field for the TestEntity record 'Test' created in the CRM. I would also expect that any of generated checkbox input fields are readonly since HtmlIzer.php adds readonly="true" to each  regardless of it being found in array $list. I would further expect, that even if neither of the generated input fields were readonly by this code, the checked/not-checked state of one, should not affect the other as it does. I would also expect that even in the case where the user doesn't modify the browser window fields and simply saves/exports as a pdf, the 2nd option checkbox should be shown as a readonly, non-checked box but it does not. It doesn't show the box at all and only a label. I suppose the real issue here is why are the fields editable in the browser window in the first place and why isn't the second checkbox rendered (only the label) even when you do nothing in the browser window except save?
 

**Screenshots**
Step 1:
<img width="1022" alt="Step1" src="https://user-images.githubusercontent.com/88215293/186985164-9e52715a-8409-486d-a957-918c24fc50fe.png">
Step 2:
<img width="747" alt="Step2" src="https://user-images.githubusercontent.com/88215293/186985166-9ce01f4e-9d5c-4fe9-97f9-aa1b79c1d0d6.png">
Step 3:
<img width="1425" alt="Step3" src="https://user-images.githubusercontent.com/88215293/186985167-7c0bd790-08d8-4139-87eb-32e74e44229b.png">
Step 4:
<img width="950" alt="Step4" src="https://user-images.githubusercontent.com/88215293/186985171-8019dff0-8f50-4c8a-a74c-db6e99a31e2a.png">
Step 5:
<img width="943" alt="Step5" src="https://user-images.githubusercontent.com/88215293/186985172-b23cc209-cf35-4628-80aa-9c685f661ba6.png">
Step 6:
<img width="943" alt="Step6" src="https://user-images.githubusercontent.com/88215293/186985174-092696c3-1159-4681-bb07-7a43eab26b9f.png">
Step 7:
<img width="201" alt="Step7" src="https://user-images.githubusercontent.com/88215293/186985175-9a89ad23-aafe-4d49-b18c-ab2cdd8be5b1.png">
Step 8:
<img width="1466" alt="Step8" src="https://user-images.githubusercontent.com/88215293/186985176-5f7ace28-4b4d-40c1-bf33-c7cbbd67aca1.png">
Step 9:
<img width="1466" alt="Step9" src="https://user-images.githubusercontent.com/88215293/186985179-c02fc292-2e4f-473b-a862-77566ef98f3b.png">
Step 11:
<img width="1465" alt="Step11" src="https://user-images.githubusercontent.com/88215293/186985182-63fe794a-7b14-4f4f-9cdf-963378b9f2af.png">

PDF Comparison Test Results:
[Test1.pdf](https://github.com/espocrm/espocrm/files/9436375/Test1.pdf)
[Test1_1.pdf](https://github.com/espocrm/espocrm/files/9436373/Test1_1.pdf)
[Test1_2.pdf](https://github.com/espocrm/espocrm/files/9436374/Test1_2.pdf)
[Test2.pdf](https://github.com/espocrm/espocrm/files/9436382/Test2.pdf)
[Test2_1.pdf](https://github.com/espocrm/espocrm/files/9436380/Test2_1.pdf)
[Test2_2.pdf](https://github.com/espocrm/espocrm/files/9436381/Test2_2.pdf)

**EspoCRM version**
7.1.11

**Additional context**
In general, I am either misunderstanding how to input the code block in pdfTemplate so that this functions correctly or this is an actual bug for checkboxTag. It would seem to me that one possible solution would be to generate unique names based on the $option passed, as in my example above. Here, the options are assumed to be unique  in the pdfTemplate code block. While the current code seems to have the correct behavior after saving the generated output to an actual pdf file (see screenshot 12) it is not duplicated in the browser window. It also doesn't show an actual checkbox for the 2nd option in the pdf which is expected. The code modification I made doesn't resolve the 'readonly' nature in the browser window but it does result in a more expected pdf file when saving the browser content as a pdf because it shows a 2nd checkbox and not white space. The different behaviors are compared in the attached pdf files. I also notice that, because the browser view doesn't have the fields as readonly, as soon as you modify one of the checkboxes, and then save it as pdf, the pdf shows the input as being editable. with or without the code modification.

**Comment by yurikuzn** [comment]
What browser and PDF viewer do you use? 

In Chrome: both rendered, read only, one one is checked (correct).
In Firefox: only one checked is rendered, both read-only (only issue is not-checked is not being rendered).

**Comment by yurikuzn** [comment]
As we moved to Dompdf, the might be not that actual anymore.
