### ISSUE TITLE
Extension Window display metadata refresh after new extension installation

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2419]
**Describe the bug**
After installing a new extension the "The application has been updated." windows show up.

**To Reproduce**
1. Install a new extension containing some sort of metadata
2. You will get an alert window asking to refresh

**Expected behavior**
No window should be visible for the user that installs the extension as after installing an extension the window will refresh it self by closing the installation popup.

**Screenshots**
![image](https://user-images.githubusercontent.com/32223252/189220771-a35a8edf-dad6-44f8-a213-6c1cbc27230f.png)

**EspoCRM version**
7.2.0 (Built from master on 08/09/2022)

**Additional context**
Looks like the problem gets triggered when the extension contains metadata.

**Comment by yurikuzn** [comment]
Found the problem. When there are no others extensions installed. Fix :https://github.com/espocrm/espocrm/commit/110dd7b8b39114ca95c2fd5bd4a6c922a37ce1c6

**Comment by Kharg** [comment]
The popup also get triggered when uninstalling an extension (it appears for just a second before the page refresh) and after installing back an uninstalled extension (if not removed from the extension list)
@yurikuzn
