### ISSUE TITLE
Values in link (URL) fields are encoded improperly

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2420]
**Describe the bug**
When I enter a URL into a field of type URL, the resulting hyperlink does not always work. For example, the following URL was entered into a detail form for an entity's field, which is type `URL`:

`.../Shared%20Documents/Some%20Folder/Authorizations/AA%20Assessment%20Approval.pdf`

Here are the properties of the resulting hyperlink element after saving the form:

`href=".../Shared%2520Documents/Some%2520Folder/Authorizations/AA%2520Assessment%2520Approval.pdf"`
`target="_blank">../Shared%20Documents/Some%20Folder/Authorizations/AA%20Assessment%20Approval.pdf`

Notice the extra `25` in the URL, which is the encoded value of `%`. Clicking the URL does not work because the path is incorrect.

Here is a shorter example. I entered `stuff.com/%20/asdf` into the field and this is what was stored in the database: `stuff.com/%2520/asdf`. Interestingly, it renders correctly even though the value of `href` is incorrect:

![image](https://user-images.githubusercontent.com/1170415/189464953-6dcc05bb-4c32-4130-b50e-6a72b4fa71af.png)
![image](https://user-images.githubusercontent.com/1170415/189464970-7d92f341-e244-4115-a5d2-76ed1fca9c04.png)

I am not sure if this happened before or after the upgrade to 7.2.0. It was working as recently as two days ago, though, on 7.1.x, so I am guessing it is related.

**Comment by yurikuzn** [comment]
This should fix the issue: https://github.com/espocrm/espocrm/commit/ccb6c19c72fa8defd6de34d9d90ad08e059b30b3

**Comment by bandtank** [comment]
The proposed fix worked for me when I saved a new value into the field. Existing URLs appear to be broken, but there may not be anything that can be done to solve that. I will work on it.

**Comment by yurikuzn** [comment]
The issue appeared only in 7.2.
