### ISSUE TITLE
Feature: Run Espo on non-root path

### ISSUE THREAD

**Issue by TobiasDeBruijn** [espocrm/espocrm#2421]
**Is your feature request related to a problem? Please describe.**
Currently, from what I can see, espocrm cannot run on a non-root path (HTTP). E.g. example.com/espocrm will not work, due to links in the site not resolving (e.g. stylesheets)

**Describe the solution you'd like**
Add an option that configures the path

**Describe alternatives you've considered**
None

**Additional context**
Configured siteUrl: `example.com/espocrm/` (tried both with and without the `/` suffix)

**Comment by yurikuzn** [comment]
It does work and always did.

**Comment by eymen-elkum** [comment]
I think he has copy of espo on the root maybe

**Comment by TobiasDeBruijn** [comment]
My issue was in the end not related to espo at all. Rather my proxy had a bug which caused it to supply the Cookie header multiple times, breaking the authentication in Espo.

With that but fixed, everything works fine. Last remaining item is being able to use /espo rather than /espo/, but that is also a proxy issue.
