### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by TobiasDeBruijn** [espocrm/espocrm#2422]
**Describe the bug**
After migrating EspoCRM to a new home, logging in produces an auth error. This happens after entering the TOTP code. Disabling TOTP gave the error after entering the username/password. A password reset did not fix the issue.

**To Reproduce**
1. Log in
2. Observe

**Expected behavior**
The user logs in, provided the credentials are correct

**Screenshots**
![image](https://user-images.githubusercontent.com/28569170/189534893-3d9b9e8a-c2f6-45c1-92e2-fc62c5040f1e.png)
![image](https://user-images.githubusercontent.com/28569170/189534940-02d0e6bc-80b9-4495-b2b2-0fc674ceebf2.png)
The first request I think indicates that the login at least was successful, but the second request failing seems to suggest the session ID (or whatever is used) is not stored properly.
**EspoCRM version**
7.0.8

**Additional context**
With debug logging enabled:
```
[2022-09-11 15:05:48] INFO: AUTH: Trying to login as user 'admin' by token but token is not found. [] []
```

**Comment by yurikuzn** [comment]
It's not a bug.

Make sure you use HTTPS (unless is localhost).

**Comment by yurikuzn** [comment]
I recommend creating a topic on our forum, more chance you will get help from the comminity.

**Comment by TobiasDeBruijn** [comment]
HTTPS is used, from the client to the server at least:
```
Client <-- HTTPS --> Proxy 1 <-- HTTP --> Proxy 2 <-- HTTP --> EspoCRM
```

Why is it not a bug? The server accepts the credentials (as invalid credentials gives a different message), yet does not let the user access the API. I've checked the authorization token against the `auth_token` table, it is noted as active there, so I'm unsure as to why access is being denied.

I'll post on the forum too!
Thanks

**Comment by yurikuzn** [comment]
We have 1000s instances working fine.

If you can debug, I recommend from Espo\Core\Api\Auth. Could be some credential data lost.

**Comment by yurikuzn** [comment]
Here's where the error thrown: https://github.com/espocrm/espocrm/blob/7.0.8/application/Espo/Core/Authentication/Authentication.php#L190

You can debug code above to try to find out why auth token is not found.

**Comment by TobiasDeBruijn** [comment]
Hm that is possible. The proxies are custom, and should pass through all headers untouched with the exception of `X-Real-IP`, `X-Forwarded-For` and `X-Forwarded-Proto`. I'll look into it.

**Comment by TobiasDeBruijn** [comment]
`Espo-Authorization` is included in the request from `Proxy 2` to Espo.

**Comment by TobiasDeBruijn** [comment]
So it seems to be related to the Cookie header. The browser sends the Cookie header as:
```
Cookie: k1=v1; k2=v2
```
The proxy translates this to
```
Cookie: k1=v1
Cookie: k2=v2
```
Which is both valid, though Espo or PHP, I don't know which, doesn't handle multiple Cookie headers.

**Comment by yurikuzn** [comment]
Which exactly cookie is lost?

**Comment by TobiasDeBruijn** [comment]
`auth-token` is preserved, but `auth-token-secret` and `auth-username` are lost.

**Comment by TobiasDeBruijn** [comment]
'Flattening' all Cookie headers into one again solves the issue.

Digging deeper, `psr7` is correct. Multiple Cookie headers are not allowed (whereas it is allowed with other headers)

Thanks for your help in debugging this issue!

**Comment by digitalextremist** [comment]
@TobiasDeBruijn do you mind expanding on what you mean by `flattening` the cookie headers? I also notice `k2=v2` being cut from the cookie hash in my implementation ( with `docker` and `nginx` )

**Comment by TobiasDeBruijn** [comment]
Sure!

I turn the three headers I wrote above into:
```
Cookie: k1=v1; k2=v2; k3=v3
```
I've fished the snippet responsible for doing so out of the proxy:
```rust
    // Some applications don't like multiple headers, 
     // so we'll combine it. 
     let mut header_map: HashMap<&HeaderName, Vec<&HeaderValue>> = HashMap::with_capacity(req.headers().len_keys()); 
  
     for (k, v) in req.headers() { 
         header_map.entry(k) 
             .and_modify(|values| values.push(v)) 
             .or_insert(vec![v]); 
     } 
  
     let processed_headers = header_map.into_iter() 
         .map(|(k, v)| { 
             let v_string = v.into_iter() 
                 .map(|x| x.to_str()) 
                 .filter_map(|x| x.ok()) 
                 .map(|x| x.to_string()) 
                 .collect::<Vec<_>>(); 
             (k, v_string.join("; ")) 
         }) 
         .collect::<HashMap<_, _>>();
```
The end result is a map of <String, String>, the key being the header name and the value being the 'flattened' value.

**Comment by digitalextremist** [comment]
@TobiasDeBruijn I amplified this over in #2726; hopefully without introducing a duplicate issue.
