### ISSUE TITLE
Attachment-multiple: Not clickable in edit mode

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#2424]
After upgrading from 7.1.11 to 7.2.1:
When composing an email with 1 or more attachments, the attachments are not rendered as link anymore and therefore are not clickable.

![Attachment](https://user-images.githubusercontent.com/65923581/189600522-4b0f4270-40c9-4d8f-a934-addd7f5f5eff.png)

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/b2d3d56a85f82d8ba2b5b4e68b89b77dfc75559f
