### ISSUE TITLE
Typo foreignAccessDisabled

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2425]
https://github.com/espocrm/espocrm/blob/4f57677e031c115e2539d8747fca17648480e88b/client/src/views/admin/entity-manager/edit.js#L742

Shouldn't this line be "foreignAccessDisabled" instead?

**Comment by yurikuzn** [comment]
Thanks. https://github.com/espocrm/espocrm/commit/872a4c2f2c53e5052f524ce2becf0be7e3b76f9e
