### ISSUE TITLE
.msg files are not compatible anymore - solved

### ISSUE THREAD

**Issue by gustavo-dssi** [espocrm/espocrm#2427]
**Describe the bug**
When I try to upload an .msg file (Outlook email format) in "_Documents>File_", it shows the error **"Error 403: Access denied. Not allowed file type"**. 
And when I try to insert the .msg file extension in "_Administration>Entity Manager>Documents>Fields>File_", it shows the error **"Error 500 Permission denied: unable to create a folder on the server data/cache/application"**.

What I did to solve this:
I went to "_application/Espo/Resources/metadata/fields/file.json_" and **added the .msg extension** to it.  I did the same in "_application/Espo/Resources/metadata/fields/attachmentMultiple.json_"; and in "application/Espo/Modules/Crm/Resources/metadata/entityDefs/Document.json"

Then I was abble to add the .msg file extension in "_Administration>Entity Manager>Documents>Fields>File_", and everything works fine.

**EspoCRM version**
7.2.1

**PS**
I believe that the error was caused by some privilege mistakes, but I don't know what privelege to apply, and which folder to apply it (config.php maybe). 
Help?

Thx

**Comment by yurikuzn** [comment]
You need to allow this file type at Administration > Entity Manager > Document > Fields > File.
