### ISSUE TITLE
Tasks on calendar do not start and end at the right times

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2429]
I created a task called Claims with a start time of 0200 and an end time of 0300. The calendar does not reflect the times:

![image](https://user-images.githubusercontent.com/1170415/189861711-6d2961d1-005c-46f3-b32d-ae6a7cdb7025.png)

![image](https://user-images.githubusercontent.com/1170415/189862108-1e8b8358-6a87-4b64-8ec7-8bc87ae9f4d1.png)

The database shows the expected times for `dateStart` and `dateEnd` (UTC-6):

![image](https://user-images.githubusercontent.com/1170415/189861954-515f848f-814a-46a5-991b-8b9036d1e641.png)

This is in 7.2.2.

**Comment by yurikuzn** [comment]
Tasks are shown by date-end, it's how it always worked.

**Comment by yurikuzn** [comment]
https://forum.espocrm.com/forum/general/82658-calendar-planed-tasks-do-not-mark-from-start-to-begining-of-the-task

**Comment by bandtank** [comment]
From the link above:

To make tasks appear like events, create a file: `custom/Espo/Custom/Resources/metadata/clientDefs/Calendar.json`

Code:
```
{
    "allDayScopeList": []
}
```
