### ISSUE TITLE
Better process for Personal Email Accounts

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2433]
**Describe the bug**
Emails from user record can not send email and emails from Personal Email Accounts don't show in From select field.

**To Reproduce**
1. Go to Administration > Outbound Emails.
2. Uncheck 'Is Shared' field.
3. Click 'Save'.
![Screenshot 2022-09-14 134841](https://user-images.githubusercontent.com/97509528/190081301-a8fde19b-d368-4453-98ff-58603a3c3dc0.png)

4. Go to profile page.
5. Click 'Edit'.
6. Add a email address in 'Email' field: 'primary_email@example.com'.
7. Click 'Save'.
![Screenshot 2022-09-14 112408](https://user-images.githubusercontent.com/97509528/190081438-07477d33-767a-400b-9a45-5e3349c4d184.png)

8. Go to Email.
9. Click 'Compose'.
10. Send a email with 'From' field is 'primary_email@example.com'.
=> Result: Show error message:
```
Error 500
Email sending: No SMTP params found for primary_email@example.com.
```
![Screenshot 2022-09-14 113752](https://user-images.githubusercontent.com/97509528/190081638-dc638627-3a8d-48fb-ba50-fab3071fda7e.png)

11. Go to AdministrationPersonal > Email Accounts.
12. Click 'Create Email Account'.
13. Create a new personal email account with Email Address is 'personal_email@example.com' and Use SMTP.
14. Click 'Save'.
![Screenshot 2022-09-14 134406](https://user-images.githubusercontent.com/97509528/190081754-fb40c358-2b44-4309-b9ff-c19422b676bd.png)

15. Go to Email.
16. Click 'Compose'.
=> Result: Personal email account 'personal_email@example.com' doesn't show in From select field. From select field just shows emails from Email field in user record which can not use to send an email.
![Screenshot 2022-09-14 112723](https://user-images.githubusercontent.com/97509528/190081793-9e082f68-e869-4bef-b956-a73a12475b2b.png)

**Expected result/Ideally**
- From select field should only shows emails which actually can use to send email.
- Emails from user record should only be shown if "Is Shared" field is checked (true) in Outbound Emails.
- Personal email accounts for the user should show in From select field even if not on user record. Or user record should have personal email account emails automatically added to the record on creation.

**EspoCRM version**
EspoCRM latest version 7.2.2.

**Comment by yurikuzn** [comment]
Unfortunately, I'm very busy and likely will be the next few weeks, can't look into it. For the first look, user emails not supposed to be group emails. This can't be considered as a bug,

**Comment by yurikuzn** [comment]
> 16. Click 'Compose'.
> => Result: Personal email account '[personal_email@example.com](mailto:personal_email@example.com)' doesn't show in > From select field. 

The item 16 is a behavior by design. A personal email account's email address should match one of user's email addresses. Otherwise, it breaks some logic. This actually is covered in the Name field tooltip.

**Comment by yurikuzn** [comment]
It's more complex as it may seem. We have also (legacy) SMTP settings in preferences available for users in some circumstances. Some SMTP servers may allow using one account for sending from multiple addresses. It's possible that a user has SMTP in their preferences that allows them sending from all their addresses despite not having shared SMTP and personal email accounts.

Maybe we also would need a new config parameter that defines whether using a shared SMTP is allowed for sending from users addresses.

**Comment by yurikuzn** [comment]
Will discard SMTP in preferences. This will make things less complex. https://github.com/espocrm/espocrm/issues/2468

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/945921b38d354e611cd9b827b6ec09dbbf4975b9
