### ISSUE TITLE
Link Parent field value not saved when field is read-only

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#2440]
**Describe the bug**
The value off a Link Parent field is not saved when this field is configured as read-only. When the field is configured as required the following error is thrown:
![image](https://user-images.githubusercontent.com/65923581/190728242-91cde647-3959-4860-97d3-84fe9d6e7f60.png)

**To Reproduce**
1. Create a new entity named Test
2. Create a Children-to-Parent relationship on this entity and set the Parent Entity Types to Account for example
3. Save the relationship, edit it again and enable Foreign Links for the Account entity
4. In Administration > Entity Manager > Test > Fields edit the Parent field and enable Read-only
5. In Administration > Entity Manager > Account > Layouts > Bottom Panels add the Test entity and save it
6. From an Account record, click + to add a Test record
7. Parent field is automatically filled with the Account but when saving the record, the parent field stays empty
8. When the Parent field is also configured as Required in step 4, the error from the screenshot above is thrown
...

**Expected behavior**
Parent value should be saved, even though the field is set to read-only 

**EspoCRM version**
7.2.3

**Comment by yurikuzn** [comment]
Expected behavior. Read-only clears an input value, then validation fails. You need to uncheck the read-only.
