### ISSUE TITLE
Hidden option for Panel does not work if Panel is in the last tab

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#2442]
**Describe the bug**
Hidden option for a Panel does not work when the following conditions are met:
- Multiple tabs configured
- Panel is on the last tab

**EspoCRM version**
7.2.4

**Comment by yurikuzn** [comment]
Hidden not fully compatible with tabs. Not recommended to use both simultaneously. https://github.com/espocrm/espocrm/issues/2379#issuecomment-1186281368
