### ISSUE TITLE
Logging in as another user for admin

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2444]
The ability to log in as another (regular) user for admin.

Can be disabled in the config: `'authAnotherUserDisabled' => true`.

Limitations:
* WebSocked is disabled when logged in as another user.
* Requires re-entering admin password to log in as another user.
* Recommended to open the login link in an incognito/private window to avoid losing a current login session.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/8e62ed2fb8e44d09ac8932a1afbd9230fa6c0c45

**Comment by rabiibrahimi** [comment]
does this support the ability to log in as another (admin) user for admin ? 

sometimes there might more admins in the CRM and an admin might want to check other admin session to fix their issues.

**Comment by yurikuzn** [comment]
No, as is stated.

**Comment by yurikuzn** [comment]
To lessen the chance of a security failure only regular users are supported.

**Comment by rabiibrahimi** [comment]
i understand
thanks

**Comment by rabiibrahimi** [comment]
Hey 
Recommended to open the login link in an incognito/private window to avoid losing a current login session. (this not working) Even if i log in as another user and open the link in incognito/private window still the system log me out of my admin session everytime. i don't think that this behaviour is intentional right ?

**Comment by bkonia** [comment]
Is this supposed to work with OIDC login? I'm logged into my admin account in an incognito window. However, when I navigate to the login link for a user, I get an auth error. I see the following in the log:

[2024-06-07 14:52:22] INFO: AUTH: Trying to login as user 'cff1a93b-be7e-490c-99d5-d8d642c68e27' by token but token is not found.

**Comment by yurikuzn** [comment]
I believe it's supposed to but can't check right now. Maybe somebody who knows may help.
