### ISSUE TITLE
Emails not working after upgrade to 7.2.x

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2445]
I am no longer able to send emails from any part of the application after upgrading to 7.2.x. I am not sure when it started, but I know it was working with 7.1.x. I am currently using 7.2.4.

Emails are being sent through the system's outgoing email address. Nothing seems to be wrong with that part of the system. However, my user is unable to send emails. For example, the "Send Test Email" button results in a 403 error:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/1170415/191934169-7725a1bc-2216-44e2-abea-5745064a93a1.png">

```
[2022-09-23 09:42:36] ERROR: (403) POST /Email/action/sendTestEmail; line: 79, file: /var/www/crm-odysseypediatric-com/application/Espo/Controllers/Email.php [] []
```

Adding a debug statement at that line:
```
    public function postActionSendTestEmail(Request $request): bool
    {
        $GLOBALS["log"]->debug("",[$this->acl->checkScope(EmailEntity::ENTITY_TYPE)]);
        if (!$this->acl->checkScope(EmailEntity::ENTITY_TYPE)) {
            throw new Forbidden();
        }
```

results in:
```
[2022-09-23 09:42:36] DEBUG:  [false] []
```

I've also noticed the following issues:
* The button to send reports via email is missing
* The button to send meeting invitations is missing

This bug may be related to a [similar issue](https://forum.espocrm.com/forum/general/83058-can-t-send-emails-after-upgrade-to-7-2-3) from the forums.

**Comment by yurikuzn** [comment]
The topic on the forum is definitely another issue.

**Comment by bandtank** [comment]
It seems related to me. I am having the same issues and it started with the upgrade to 7.2.x. Nothing else was changed.

**Comment by yurikuzn** [comment]
I don't see any changes related to Email access checking between 7.1 and 7.2. Check Roles of your user, whether it has Email access.

**Comment by bandtank** [comment]
I am logged in as the administrator:

<img width="115" alt="image" src="https://user-images.githubusercontent.com/1170415/191939059-f1c48353-18f9-4377-82be-9e3f4fe1f7b0.png">

Everything is enabled:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/1170415/191939132-92f92497-019a-4537-a01b-d8dbeaebe45e.png">

Where are the ACL values stored in the database?

**Comment by yurikuzn** [comment]
ACL is merged from roles and cached in `data/cache/application/acl`. 

Does the admin user have the same issue?

**Comment by bandtank** [comment]
Yes, logging in to the user with `id = 1` results in the same behavior.

**Comment by bandtank** [comment]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/1170415/191940592-1a960acd-0aad-4222-b83a-1e05ace1ce6c.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1170415/191940842-576c89d8-d424-41a5-9b6b-11da5ee217a5.png">


<img width="339" alt="image" src="https://user-images.githubusercontent.com/1170415/191940689-e5e53840-2d1d-4f14-a1e6-737f88f078f4.png">

<img width="332" alt="image" src="https://user-images.githubusercontent.com/1170415/191940768-3cb685e7-df30-4d3a-b74e-c59db0ac9f57.png">

**Comment by yurikuzn** [comment]
Maybe you have your Email entity type disabled (Entity Manager > Edit).

**Comment by bandtank** [comment]
Thanks. That fixed it. FYI - I disabled the Email entity more than one year ago and I have always been able to send invitations, reports, etc.
