### ISSUE TITLE
Record Create Not Working After Upgrade to Latest Version V7.2.4

### ISSUE THREAD

**Issue by Doopin** [espocrm/espocrm#2447]
Hi Team

I use Espo API to sync data from my live system.
Since I upgraded to the latest version V7.2.4, its completely down. Records Cannot be created via the API anymore no matter the module. Not 100% sure but most fields involved into this issue are **required fields** which are set as **Read Only**.
I will have these errors where what changes is either the field name or the validation type.
`[2022-09-26 20:49:00] ERROR: (400) Field validation failure; entityType: Account, field: username, type: required.; POST /Account; line: 54, file: /var/www/d_app_crm/application/Espo/Core/Exceptions/BadRequest.php [] []`
In the error above, username field is not empty in the POST data.
While debugging I noticed that commenting this ligne, some of that error will disapear for all _varchar_ type field.
[https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Record/Service.php#L479](url)

Now the error will start appearing for Enum whereas data posted via the API is not empty. See error for Enum type field
`[2022-09-26 17:00:03] ERROR: (400) Field validation failure; entityType: Account, field: subscribedFrom, type: valid.; POST /Account; line: 54, file: /var/www/d_app_crm/application/Espo/Core/Exceptions/BadRequest.php [] []`

Please have a look into that.

**Comment by arkadywtf** [comment]
It's not a bug, see this issues: https://github.com/espocrm/espocrm/issues/2375 https://github.com/espocrm/espocrm/issues/2361

**Comment by Doopin** [comment]
Thank you for the reply @arkadywtf 
Am soo sad. This was a very nice feature where you could allow an API User to set set a read only field.
This would ensure that no regular user could modify but it would allow API User

**Comment by arkadywtf** [comment]
You can still do that by disabling "Edit" ability at Field Level for certain roles in ACL.

**Comment by Doopin** [comment]
Ooh yeah you're right. I missed that feature. Will do the setup.
Thanks

**Comment by yurikuzn** [comment]
> very nice feature where you could allow an API User to set set a read only field

That was a design flaw actually, we was living with it for some compatibility reasons.

Or you can use dynamic logic making a field read-only with a condition always resolving to true.

**Comment by Doopin** [comment]
Yes dynamic logic may be another good solution. 
But I cannot rely on it @yurikuzn as you already said on issue 2440 at the link below 

> there's a chance that in future we will validate server-side by dynamic-logic too

[https://github.com/espocrm/espocrm/issues/2440#issuecomment-1250015443](url)

So if I go that way, there is a chance that I will have restart everything later in the future. I will try ACL later and I hope that it will offer similar behaviour. 
Thank you all for your assistance
