### ISSUE TITLE
Ability to translate "Global Search" label

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2450]
At the moment it's not possible to translate the "Global Search" label, it would be useful to be able to do so.
as of now you can only translate it if you add the label manually in the "Global.json", but it's not available in POEditor nor in the label manager/language files.
![image](https://user-images.githubusercontent.com/32223252/192431497-57892ff4-3901-4f77-8b32-6a4d25961e6b.png)

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/fba191f22c6064b130f37815ec3fc00740a27607

**Comment by Kharg** [comment]
Thanks Yuri! When will it be available in POEditor?

**Comment by yurikuzn** [comment]
Later, I'm too busy.
