### ISSUE TITLE
Address field doesn't create when is declared in actualFields.

### ISSUE THREAD

**Issue by kczereczon** [espocrm/espocrm#2451]
**Describe the bug**
When declare address type field in actualFields of complex field, the fields are not created in database.

**To Reproduce**
1. Create custom field
2. Add address to actualFields
...

**Expected behavior**
Address actual fields should be created in entity.

**Screenshots**
![image](https://user-images.githubusercontent.com/22079016/192563273-2188438e-670a-4807-88ad-7776d7dc37d0.png)
![image](https://user-images.githubusercontent.com/22079016/192563294-df8c950a-b7cc-4c70-a55a-d7d9cc93a559.png)

**EspoCRM version**
7.2.0

**Comment by yurikuzn** [comment]
Please, don't create bug reports for such issues. It's not a bug. It's not supposed to be created.
