### ISSUE TITLE
Lead record page minor design issue

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2452]
**Describe the bug**
On the Lead record both sidepanel and task panel miss rounded edges. 
**To Reproduce**
1. acces a lead record page
2. check sidepanel & task
...

**Expected behavior**
Unless this is a design implementation, i think they should rounded just like any other record on the CRM.
**Screenshots**

**EspoCRM version**
v 7.2.4
<img width="1466" alt="Screenshot 2022-09-27 at 18 42 35" src="https://user-images.githubusercontent.com/19490674/192609115-52bf31a0-20dd-4659-bb69-036ca03829d3.png">

**Comment by yurikuzn** [comment]
I can't reproduce.

**Comment by yurikuzn** [comment]
Try disabling sticked parameter for some panel (maybe Converted To). It may give side-effects when combined with hidden panels. It's not easy to fix and I'd rather live with it for now as it can be avoided if applying sticked parameter to panels that always have the previous panel visible.

**Comment by rabiibrahimi** [comment]
you are right default panel was Sticked and was causing this behaviour. all is good now thanks
