### ISSUE TITLE
OIDC authentication

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2455]
The ability to authenticate with identity providers that support OpenID Connect.

Additional features:

* User creation. Optional.
* Team mapping. Espo teams against groups/teams/roles of the identity provider.
* User profile and user teams sync. Optional, on every login.
* Ability to choose a claim that will be used for a username.
* Fallback login. Only for admins or for regular users too.
* For admins OIDC can be disabled, so that only fallback method  allowed.
* Logout redirect. To clear an identity provider session when a user is logging out from Espo. 
* Backchannel logout. The ability to forcibly log out a user from Espo. `api/v1/backchannelLogout` endpoint.

Details:

* No portal support.
* Espo 2FA may not work with some identity providers (where an authorization code can't be used twice).
* The *userName* field length may need to be increased up to 255 in some cases (by default Espo has the limit 50).
* Supported signing algorithms: RS256, RS384. RS512, HS256, HS384, HS512. Developers can add implementations of other algorithms in an upgrade-safe manner.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/616d65023b4c9da27e0e6039f1ff4caa3c2a63fb

**Comment by analystcmyk** [comment]
That is a huge block of work, looking forward to testing this. 

One small remark : signing out of Espo does not necessarily you want to completely logout of all other applications, eg Office 365 etc. You might just want to logout from Espo, (and relogin only using MFA)

Maybe consider this behaviour could be configurable.

**Comment by yurikuzn** [comment]
> Maybe consider this behaviour could be configurable.

This is optional (if admin will configure). This is on a part of the OIDC standard but some providers do have this feature.

**Comment by emillod** [comment]
Do you plan to add portal support?

**Comment by yurikuzn** [comment]
You can enable with minimal customization. There was a post on the forum recently. During these days when we released, I don't have the ability to look into non-urgent issues.

**Comment by emillod** [comment]
@yurikuzn thank you for fast response. just asking :)

**Comment by bandtank** [comment]
How does OIDC affect API connections? My application requires the user to sign in:

```python
  def getBasicAuthToken(self):
    username = input("Enter your CRM username (first.last): ")
    password = getpass.getpass("Enter your CRM password (characters are hidden): ")

    url = self._cfg['crmApiBaseUrl'].rstrip("/") + "/App/user"
    headers = {
      "Content-Type": "application/json",
      "Espo-Authorization": base64.b64encode(f"{username}:{password}".encode()).decode()
    }

    r = requests.get(url, headers = headers)
    ...
```

I am not sure what the system will do if authentication is set to `OIDC` instead of `Espo`.

**Comment by yurikuzn** [comment]
API users use a different auth mechanism. OIDC does not affect them.
