### ISSUE TITLE
Improve flow of mass action (deletion) on selected record

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2456]
**Is your feature request related to a problem? Please describe.**
When deleting massive data list from the CRM the flow of how it is done efficiently. 

**Describe the solution you'd like**
When we select record to delete once the action delete is performed i would like to see next record listed properly instead of clicking on **show more** this way i can just select next chunk to delete from the list. Currently when we delete selected record we have to click on **show more** then we need to click to uncheck the main checkbox selector and then click on the checkbox selector to select next records to delete. please see attached recording to see how flow of deleting records works now (too many actions)

**Describe alternatives you've considered**
What i suggest is: 
- select records to delete
- once selected records are deleted the list view should re-render to show next records on list
- also when selected records are deleted system should uncheck the checkbox on the header to get it ready for next records selection  

https://user-images.githubusercontent.com/19490674/193303129-b4b872fc-d98a-4cc5-ba2e-9babb1b52ee7.mov

**Additional context**

**Comment by yurikuzn** [comment]
Done for a select-all case: https://github.com/espocrm/espocrm/commit/7738b9c3e0be0843a7bc92feba925aecccd65f2b. Not changed for a case when select-all is not used.

**Comment by yurikuzn** [comment]
BTW I'd recommend using select-all-result to delete all search result at once.

**Comment by rabiibrahimi** [comment]
Hey i agree bur sometimes the select all result wouldn’t work if the result if thousands of record. My use case was deleting ended processes from advanced pack and there was thousands more than 50k of ended processes so selecting all results to delete them was returning error 500 due to large number of records to delete. 
thanks for the improvment 🙏

**Comment by yurikuzn** [comment]
It has been improved since the recent version so that deleting is processed by cron if there are too much of records.

**Comment by rabiibrahimi** [comment]
Great 👌
Thanks
