### ISSUE TITLE
composeMailToLink separator

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2457]
https://github.com/espocrm/espocrm/blob/99670c7b3de4d253110b840f3834d170f5148307/client/src/email-helper.js#L515

Could we get an enum/varchar option to choose the external client separator? 
Depending on your computer/outlook regional settings Outlook uses ";" as a separator and doesn't accept ",".

Thanks

**Comment by yurikuzn** [comment]
I'd rather stick to a comma which is designated by a standard.  It's possible to configure in Outlook to accept comma.
