### ISSUE TITLE
Avatar color index out of range

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2463]
I see this E_NOTICE line in the log on a regular basis:
```
[2022-10-03 21:51:47] NOTICE: E_NOTICE: Undefined offset: 9 {"code":8,"message":"Undefined offset: 9","file":"/var/www/crm-odysseypediatric-com/application/Espo/EntryPoints/Avatar.php","line":88} []
```
Note: line 88 is not the right line. I added several debug statements. It's complaining about this line:
```
return $colorList[$index];
```
The issue is with this line:
```
$colorList = $this->metadata->get(['app', 'avatars', 'colorList']) ?? $this->colorList;
```
The metadata does not have `colorList`, which means the class uses the default array that has 9 elements. An index of 9 doesn't work with an array that has 9 elements, so the notice is emitted. Nothing is broken as far as I can tell, but I figured I'd mention this in case anyone has seen the issue.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/6d1ab5870fb36faa2d6114f32cfcfb33a6b2f434. This happened with the probability 1/128 per user.
