### ISSUE TITLE
Bad request Backend validation failure

### ISSUE THREAD

**Issue by AlexeyBalin** [espocrm/espocrm#2464]
**Describe the bug**
update contact with custom field take error

**To Reproduce**
1. edit contact
2. change custom fields (array)
3. update

**Expected behavior**
doesn't update custom fields

**Screenshots**
![image](https://user-images.githubusercontent.com/652118/193977960-587b484e-ca31-43f5-8b9a-a4b41ebd53b0.png)

**EspoCRM version**
2.7.4 (latest)

**Comment by yurikuzn** [comment]
See release notes 'Possible compatibility issues' https://github.com/espocrm/espocrm/releases/tag/7.2.0.

Provided steps to reproduce are not steps to reproduce.
