### ISSUE TITLE
Wide images cut off in emails

### ISSUE THREAD

**Issue by lucakuehne** [espocrm/espocrm#2465]
**Describe the bug**
If there are big images in an email, EspoCRM is not able to show those pictures.

**To Reproduce**
Open an email in EspoCRM with a big image.

**Expected behavior**
Possible solutions would be the following:
- The image should be shrunk down (I guess width max 100% of it's parent container) to the size of the email window/modal. Then with a click on the image the image could be opened in a modal, to view it in detail.
- Implement a scrollbar to allow to scroll the email left and right.

**Screenshots**
![emails with uncomplete image](https://user-images.githubusercontent.com/15850551/194004360-0a97e467-aead-4e41-acc4-7f1653d9d1f4.png)
The image is at least twice of the visible width, because it is cut off at the right side.

**EspoCRM version**
7.2.4 (But the problem also existed on 6.x.x as I can remember.)

**Comment by lucakuehne** [comment]
I just saw, that there is a scrollbar all the way down the email. But the emails are so long, that you can't really use it. Because you can't see where you are srolling when you are all the way down in the email, because the content to be scrolled is all the way up in the email.
I think to shrinking and zooming in modal solution would be much cleaner. Or at least you could add a second scrollbar on top of the email. Or make the scrollbar stick to the bottom of the (viewable) screen.
This makes it not a technical bug, but an UI/UX-bug.

**Comment by yurikuzn** [comment]
I recommend to 'open in new tab' from the context menu to be able to view all image. I can't solve this problem at the moment as we have much more important things to do.

**Comment by yurikuzn** [comment]
> Or make the scrollbar stick to the bottom of the (viewable) screen.

This option not available for us.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/0ed243c9b1b1b6866be42b08e9fbdd39ceb454a2
