### ISSUE TITLE
Email: Group folders

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2467]
Before, Espo had only personal email folders. If a user moved an email to a folder, it did not any effect for other users.

New group email folders are shared for teams. Admin can create group email folders and specify which teams have access to a particular folder.

If an email is moved from a group folder to a personal folder or inbox, it will unlink the email from that group folder.

The ability to automatically put inbound emails imported through a group email account to a specific group folder.

Users that have access to a group folder can put there any email (only read level access to the email is required). If an email is located in a group folder the user does not have access to, they won't be able to move that email to another folder.

The field-level-security (in Roles) can be used to disable the ability to change (edit) the group folder.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/cb009228418835692a6635c79e43d946f041c325

**Comment by rabiibrahimi** [comment]
Neat 👌
