### ISSUE TITLE
PDF Template adds unwanted HTML Tags

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#2470]
**Describe the bug**
The PDF template engine adds an unwanted closing td tag when embed it inside an if statement.

**To Reproduce**
The following PDF template....
```
<table>
          <tbody>
          <tr>
          <!-- {{#ifEqual name "testaccount"}} -->
          <td colspan="2">
          <!-- {{else}} -->
          <td colspan="3">
          <!-- {{/if}} -->
          test123
          </td>
     </tr>
     </tbody>
</table>
```
....results in
```
<table>
          <tbody>
          <tr>
          <!-- {{#ifEqual name "testaccount"}} -->
          <td colspan="2">
          <!-- {{else}} -->
          </td><td colspan="3">
          <!-- {{/if}} -->
          test123
          </td>
     </tr>
     </tbody>
</table>
```

**Expected behavior**
The added </td> tag breaks the table in the PDF template. The closing td tag should not be added.

**EspoCRM version**
7.2.4

**Comment by yurikuzn** [comment]
Not a bug. It's not a PDF template engine, but contenteditable behavior. Use special table tags for this https://docs.espocrm.com/user-guide/printing-to-pdf/#tables
