### ISSUE TITLE
CSV Import Error 

### ISSUE THREAD

**Issue by Aakash-Roy** [espocrm/espocrm#2474]
**Describe the bug**
I was trying to upload a CSV file but I was getting a 406 error, after inspecting I got 404 at `/api/v1/Import/action/uploadFile`. 
I went through error logs of my server it displays:

`[2022-10-21 07:57:57] ERROR: (404) Action GET 'uploadFile' does not exist in controller 'Import'.; GET /Import/action/uploadFile; line: 92, file: /{PATH_TO_FILE}/application/Espo/Core/Api/ActionProcessor.php [] []`

I have specified PHP INI as stated in EspoCRM Documentation.

**Comment by yurikuzn** [comment]
Please create a topic on the forum (not in the bug report section).
