### ISSUE TITLE
Can't Upgrade from CLI

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2475]
Upgrading using CLI in EspoCRM 7.2.4 doesn't work,  getting the "There are no available upgrades." message.

Using command "php command.php upgrade"

I even tried it on a brand new instance of 7.2.4

![image](https://user-images.githubusercontent.com/32223252/197241170-213a660c-d767-47ce-8221-f6441fce96b2.png)

**Comment by yurikuzn** [comment]
Should work now. Github changed their API endpoint. Please let us know there is any problem.
