### ISSUE TITLE
LDAP issue in 7.2.5 package

### ISSUE THREAD

**Issue by gramakri** [espocrm/espocrm#2476]
**Describe the bug**
With LDAP enabled, 7.2.5 throws an error. `InjectableFactory: Class Espo\Core\Authentication\LDAP\ClientFactory does not exist`

**To Reproduce**
1. Install 7.2.5
2. Enable LDAP in configuration
3. Try to login

...

**Expected behavior**
Should not throw error on logic

**Screenshots**
![image](https://user-images.githubusercontent.com/82041/197393862-18555148-2968-4b33-8ba7-1c60658e13ec.png)

**EspoCRM version**
7.2.5

**Additional context**
Found this when updating the Cloudron package but should be the case on any distro.

**Comment by gramakri** [comment]
I am not sure how the download tarballs are generated (i.e in https://www.espocrm.com/download/), but:

* In git, it is `application/Espo/Core/Authentication/LDAP`. But in release tarball it is `application/Espo/Core/Authentication/Ldap`.


The release tarball has the following code in `application/Espo/Core/Authentication/Logins/LDAP.php`:

```
    Authentication\LDAP\Utils as LDAPUtils,
    Authentication\LDAP\Client as Client,
    Authentication\LDAP\ClientFactory as ClientFactory,
```

The above is the source of the issue. It should be `Ldap` i guess.

**Comment by yurikuzn** [comment]
Is it fresh installed or upgraded?

**Comment by yurikuzn** [comment]
I will release 7.2.6 soon with the proper case directory name. Thanks for reporting.

**Comment by yurikuzn** [comment]
For information: Upgrading the affected instance (`php command.php upgrade`) will resolve the issue too.

**Comment by gramakri** [comment]
@yurikuzn Thanks for the quick response! Will there be a `EspoCRM-upgrade-7.2.4-to-7.2.6.zip` available for download ?

**Comment by yurikuzn** [comment]
Never. There are two upgrades between these versions.
