### ISSUE TITLE
jsLibs exportsTo window not defined

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2477]
Using Espo 7.2.5, creating an extension using a custom jsLibs with parameter  "exportsTo": "window" gives a 

`jQuery.Deferred exception: MyLib is not defined ReferenceError: MyLib is not defined`

Example jsLibs:

`{
    "mylib": {
        "path": "client/modules/my-extension/lib/customlib/bundle.min.js",
        "exportsTo": "window",
        "exportsAs": "MyLib"
    }
}`

This is the line that gets added to the bundle.min.js
`window.MyLib = window.MyLib || MyLib`
it was working fine in previous version, was there some changes?

Removing the "exportsTo": "window" makes the extension work.

**Comment by yurikuzn** [comment]
There was no change in 7.2.5. There was change in 7.2.0.

**Comment by Kharg** [comment]
Yes, probably the same would happen using 7.2.0, I just tested in 7.2.5, that's why I mentioned it.

**Comment by yurikuzn** [comment]
We have all our libs working. Maybe your lib does not export to window.

**Comment by yurikuzn** [comment]
Ok. It's my weekend and i'm working as always . Please, I'd appreciate if issues are posted on working day.
