### ISSUE TITLE
PhoneNumber default type is not selectable

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2481]
**Describe the bug**
When trying to set a default type for a phoneNumber field it is not presented as a select box but as a string.

**To Reproduce**
1. Go to entity Manager => account => fields
2. access phoneNumber field
3. default type is not select list it is presented as string
...

**Expected behavior**
I think the default type for the phoneNumber should allow to select which phoneNumber type, it should be selectable.
<img width="694" alt="Screenshot 2022-10-26 at 14 11 34" src="https://user-images.githubusercontent.com/19490674/198035495-bcb69780-f843-4c1d-a45b-0a4f449d369d.png">

**Screenshots**

**EspoCRM version**
v 7.2.4

**Comment by yurikuzn** [comment]
It was always a varchar field.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/09d8bc5a364c8f3e91ca9c79c2bad9315e473bb1
