### ISSUE TITLE
Stream: Refresh notes when updated (with web socket)

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2482]
WebSocket doesn't update the stream if the note was edited, only if it's new.

Any chance of adding support in a future release?

**Comment by yurikuzn** [comment]
Here's a PR: https://github.com/espocrm/espocrm/pull/2483

Could you try it? I don't have a needed environment at hand at the moment.

**Comment by Kharg** [comment]
Still not refreshing on update, tested the PR on 7.2.6

**Comment by yurikuzn** [comment]
Did you try updating by another user?

**Comment by Kharg** [comment]
Correct, tried with 2 users logged from 2 different browsers.
Tried to update the Note of both users, update not visible unless I refresh the page

**Comment by yurikuzn** [comment]
Could you debug. It looks like it should work.

**Comment by yurikuzn** [comment]
It should work only on the stream panel on the detail view.

**Comment by yurikuzn** [comment]
I'll look into it when get a chance. But it can take days. I believe the code is correct.

**Comment by Kharg** [comment]
Of course I tested in on the Stream panel of the  detail view of a Lead Record.
I'll be waiting, Thank you Yuri.

Any chance about also supporting the deletion of a stream note?
