### ISSUE TITLE
Email Inline images do not display when using Thunderbird

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2484]
**Describe the bug**
When sending emails with inline images they do not display in Thunderbird.

**To Reproduce**
1. Create an email with an inline image and send it
2. View email using thunderbird email client

**Expected behavior**
Image should show inline

**Screenshots**
<img width="1076" alt="email image 1" src="https://user-images.githubusercontent.com/7907518/198820239-9616e224-78a3-4a1d-aa30-331bbfda7247.png">

**EspoCRM version**
Current version

**Additional context**
ln 540 of application/Espo/Core/Mail/Sender.php changes the $messageType from multipart/related to multipart/mixed

If this line is commented out emails render as expected in thunderbird. Also tested results after commenting this line in Gmail, Desktop Outlook and Outlook 365 and all worked as expected.

**Comment by yurikuzn** [comment]
In needs a more comprehensive fix. Changing multipart/related to multipart/mixed will cause issues.

This structure might be needed:
```
multipart/mixed
├─── multipart/related
│   ├─── multipart/alternative
│   │   ├─── text/plain
│   │   └─── text/html
│   └─── image/png - inline image
└─── application/pdf - attachment
```

**Comment by yurikuzn** [comment]
Note that it's not easy to apply (cherry-pick) to the fix branch. So needed to be tested from the master.

**Comment by TanDuong-PTN** [comment]
Hi @yurikuzn ,

I set up the latest EspoCRM version 7.2.6 and update the application\Espo\Core\Mail\Sender.php file according to your PR: https://github.com/espocrm/espocrm/pull/2486 and some related files.

Result: The images don't show.

But when I add some debug text to body in the if else at line 458, the images show:

if (count($attachmentPartList) || count($inlineAttachmentPartList)) {
            if ($htmlPart) {
                $body->addPart(
                    (new MimePart('Debug:True'))
                        ->setType('multipart/related')
                );
...........

Don't know reason why. Could you have a look at that?

**Comment by yurikuzn** [comment]
Did the problem exist before or it came about recently?

**Comment by yurikuzn** [comment]
I managed to set up the Thunderbird to check Gmail. I look into an email source and its mime parts seems not corresponding to the message composed by Espo. Could it be that Gmail amended the message when received and stored it on IMAP?

**Comment by boydle** [comment]
Hi Yuri, 
The problem has existed for a while at least back to version 6.0

Not sure about what Gmail maybe doing to the message. Do you have any other email without Google? I can setup an email against one of my domains and send you the login details if this would help?

**Comment by yurikuzn** [comment]
It seems that Laminas (Zend) library strips multipart/related part from the body when generating a message. I will look into.

**Comment by yurikuzn** [comment]
Found out. We should have different structures for emails:

* inline attachments only
* inline attachments and regular attachments
* regular attachments only
* no attachments

**Comment by yurikuzn** [comment]
Pushed changes. Seems to be working now.

**Comment by boydle** [comment]
Tested and looks good thanks.

**Comment by yurikuzn** [comment]
The fix is not good. HTML is not rendered in Gmail when there's attachment. Any helpful wanted.

**Comment by yurikuzn** [comment]
Hope this would be a final fix: https://github.com/espocrm/espocrm/commit/cadf54fb4e186dd265eb7b734e8a55f6aa70086a.
