### ISSUE TITLE
Error after upgrading to 7.2.6

### ISSUE THREAD

**Issue by ccolussi** [espocrm/espocrm#2487]
**Describe the bug**
After upgrading to 7.2.6 from 7.1.11, we cannot save opportunities. Espocrm shows the error "Erro 400: Bad request
Backend validation failure.

Field: liderProjeto
Validation: valid"

Field: liderProjeto is a custom field without any validation formula.

**To Reproduce**
1. Click "Add opportunity"
2. Fill the fields
3. Click Save

**Expected behavior**
Opportunity saved without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/28111342/199014647-95118203-e57a-4cbd-b9d4-4bc9c72bda11.png)

**EspoCRM version**
7.2.6

**Additional context**
Error log:

[2022-10-31 13:00:44] ERROR: (400) Field validation failure; entityType: Opportunity, field: liderProjeto, type: valid.; POST /Opportunity; line: 54, file: /var/www/keyworks_com_br/espocrm/application/Espo/Core/Exceptions/BadRequest.php [] []

**Comment by yurikuzn** [comment]
Need providing more details about your custom field. Steps to reproduce are not actual steps to reproduce.

**Comment by yurikuzn** [comment]
Please try debugging. https://github.com/espocrm/espocrm/tree/master/application/Espo/Classes/FieldValidators. One of validator fails. I know nothing about your field. I'm one against 1000nds. It's very hard for me to engage in every issue.

**Comment by yurikuzn** [comment]
Depending on your field type, look into the corresponding validation class > checkValid method.

**Comment by ccolussi** [comment]
Found the issue:

The field is a list with e-mails as values. Since 7.2.6, Espo doesn'r accept e-mails as values in lists. If it's possible, could return the behavior to previous version?

**Comment by yurikuzn** [comment]
Still no details about your field.

**Comment by yurikuzn** [comment]
I spent some time trying reproducing, doing multiple scenarios. Required steps to reproduce serve time saving. I spend a lot of time in vain.
