### ISSUE TITLE
Workflow Issue

### ISSUE THREAD

**Issue by Whrealty** [espocrm/espocrm#249]
I ran into a bug in a workflow. currently I have a workflow that sends a email to the assigned user of that lead with info of the lead.
And it works just fine

But the bug is if I do not assign that lead to a user it sends the email template to the leads email that is in the record . kinda a big issue since i got a call from a client say she received internal info from my system 
This only happens if I do not have a assigned user in the record

**Comment by yurikuzn** [comment]
This repository not for Advanced Pack features. We will check.
