### ISSUE TITLE
Bottom tabs' content is not visible if First tab is visible/invisible based on certain condition

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2493]
**Describe the bug**
I have set up bottom tabs for account entity and i have company type field which determine what type of account options are (Client - Accountant - Introducer) i have set up the first tab called (Claims) to host certain related record and this tab should be visible on the account detail view only if company type === client otherwise if company type === accountant || company type === introducer then the Claims Tab should be hidden, everything works well but i noticed when i access accounts with company type === accountant || introducer then the bottom tabs' content is not visible unless if i click on one of them. this is happening because the first Tab on the bottom tabs is conditioned to be visible or not based on company type value.

**To Reproduce**
1. create bottom tabs on account and make first Tab visible/invisible based on some condition e.g account type value
2. create two accounts and have one of them have a condition that makes the First Tab on bottom tabs visible and second doesn't not match the condition so the first Tab on bottom tabs won't be visible.
3. Try to switch between the two accounts and notice how the second account which doesn't have the condition to make the first Tab visible will not display the content of the rest of the tabs unless if you click on one of them
...

**Expected behavior**
I expect when i condition the first Tab on bottom tabs to be visible based on certain condition, to not make other tabs' content not visible if the account doesn't match the condition to make first Tab visible. 

**Screenshots**

**EspoCRM version**
Version 7.2.6
<img width="968" alt="Screenshot 2022-11-04 at 14 41 50" src="https://user-images.githubusercontent.com/19490674/200006851-adac076e-8207-4f70-8495-b9e4276a2380.png">
<img width="968" alt="Screenshot 2022-11-04 at 14 44 38" src="https://user-images.githubusercontent.com/19490674/200006859-3e50d2f1-b0f9-4aa9-aea9-aa0ec84b2948.png">

**Additional context**

**Comment by yurikuzn** [comment]
There was no logic coded to cover this situation. IIRC I new about such possible case. UI is too complex, too many scenarios, race conditions, models being fully loaded after render. I do myself a burden to develop new stuff like this to support all possible scenarios. I'm not sure whether to fix this. I did not consider it as a bug when implemeted.

**Comment by rabiibrahimi** [comment]
i understand the burden with such features and all scenarios that could be taken into consideration. I would appreciate if you could have a look when you have time and of course if you could as i think the feature works fine i guess there is only issue if the First Tab is conditioned to be visible or not based on certain conditions hence why if conditions not meet seems that visibility would be persistent. how about rerendering the view if any conditions applies to the tabs?

Thank you so much for your work and effort.

**Comment by yurikuzn** [comment]
Possible fix: https://github.com/espocrm/espocrm/commit/334d88775fa471f22a9e1c96d26a3b0cc91d453c.

**Comment by rabiibrahimi** [comment]
Thank you so much just tested it and it works. 

Many thanks

**Comment by yurikuzn** [comment]
I'm not sure whether it does not cause new issues with different conditions.

**Comment by rabiibrahimi** [comment]
i will try different conditions on the tabs and let you know. so far i have tried other conditions on another two tabs and everything seems to work fine. i will do more tests to see if there is any issues.

**Comment by yurikuzn** [comment]
Fix of the fix: https://github.com/espocrm/espocrm/commit/fdf72b36763b37787655cb8e5450026f1286b51a
