### ISSUE TITLE
"Emojis" in Event/Meeting title prevent list entry in Account/Opportunity Activity pane

### ISSUE THREAD

**Issue by krraaamer** [espocrm/espocrm#2494]
We recently added emojis to a few event titles, but immediately noticed that any events with emojis in the title does not show up properly in the Acc/Opp pannels

**Comment by yurikuzn** [comment]
We have bug reports template. Please use it. Explicit steps to reproduce a required.

**Comment by yurikuzn** [comment]
Emoji that I added to a meeting's name did not cause any problem to the Activities panel on the Account detail view.
