### ISSUE TITLE
Full text search force user to add % at the end

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2496]
If I enabled the full search on account and search for "stef" stefan will not fetched till I completed the search word to exact Stefan.

If I added the trailing % issue will be fixed

I think the end % must be added by default

Not sure if this is part of the design.

NOTE: in link field text search will work as expected

**Comment by yurikuzn** [comment]
It was definitely by design, but I don't remember details and context.

**Comment by yurikuzn** [comment]
Forced appended wildcard negates some benefits of full=text search. When we search in google, we don't have '*' appended.

One can easily customize to have the wildcard appended https://github.com/espocrm/espocrm/blob/7.2.7/application/Espo/Core/Select/Text/FullTextSearch/DataComposerFactory.php#L63.

**Comment by marcusquinn** [comment]
@eymen-elkum @yurikuzn I think I have found the confusion that causes this issue to be posted.

In Entity Manager, the "Full-Text Search" tick-box wording suggests to us that it enables searching the test of all fields on the entity.

What it actually appears to do is, when ticked, only return results for full work matches.

I suggest renaming that boolean as "Full-Word Search", with the tool tip extended to: "Tick to only return full-word matching results in searched. Running rebuild is required for each change of state for this option."

**Comment by yurikuzn** [comment]
Full-text search is not a term we contrived. When full-text search is enabled, full-text search is applied. No need to rename anything.

**Comment by marcusquinn** [comment]
The current wording managed to mislead us all, as having that option ticked then causes the issue where searches need to exact match strings for the selected "Text Filter Fields" — which then returns no results for partial word searches, and users simply see as a bad search experience, that they continually report to us as "search doesn't work".

We've solved our problem, by disabling "Full-Text Search" everywhere now, as the need for exact word matching makes it appear to be a bug or primitive experience to users, and adding Description and other fields to "Text Filter Fields" yields better results, in allowing partial string matching.

My suggestion is that the feature wording isn't matching our development or user expectations, and perhaps it could be improved functionally or clearer, or both.

Open to suggestions, or collaboration if you would like us to offer pull requests based on your preferences and our user-experience needs.
