### ISSUE TITLE
Not working on IIS 10

### ISSUE THREAD

**Issue by HenningArtur** [espocrm/espocrm#2500]
First of all I want to tell you that we have been using espocrm for over a year and we are very happy with it.

Unfortunately I have to move to the IIS.

Unfortunately you don't provide a web.config. That's why I can't move to IIS.

Could you please provide a web.config?

**Comment by arkadywtf** [comment]
Have you tried this? https://github.com/espocrm/espocrm/blob/master/public/web.config

**Comment by yurikuzn** [comment]
We will have documentation soon.

Personally, I've never tried IIS so I can't help. It's better to ask on the forum.
