### ISSUE TITLE
Styled checkboxes

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2507]
![image](https://user-images.githubusercontent.com/1006792/202206336-1b7f3485-5dc0-402a-a608-404722dca9f1.png)
![image](https://user-images.githubusercontent.com/1006792/202206504-35160183-3123-437e-b07d-7e4edfd4f00d.png)

**Comment by yurikuzn** [comment]
Plus radio-buttons are improved too.

**Comment by Kharg** [comment]
Aren't checkboxes a little bit too big?
At least in Admin menu/user preferences
![image](https://user-images.githubusercontent.com/32223252/211497824-20215a1f-5bf9-4a3a-b495-046704bab6c8.png)
![image](https://user-images.githubusercontent.com/32223252/211498080-f89d94af-ccc3-458a-a9fe-24303757003b.png)

**Comment by yurikuzn** [comment]
Needs some time to get used.

**Comment by Kharg** [comment]
Yes, I guess I just need some time to get used to it.

**Comment by yurikuzn** [comment]
There are a little offset issue happens (seems a Webkit bug). If one can find a fix, please let me know.
