### ISSUE TITLE
Selectbox improvements

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2508]
* Suiting Espo themes.
* Options are searchable (using typing).
* For enum fields it's also possible to search any word.

**Comment by yurikuzn** [comment]
It's taking an effort to adapt Selectize lib to make it user-friendly in single-select mode.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/4e0de42b0d004fa8d7a7cf949770887ef4c2e093

**Comment by o-data** [comment]
Is it possible to also add this feature for PDF Template and Email Template creation?

**Comment by micker** [comment]
yes good idea !

**Comment by yurikuzn** [comment]
> Is it possible to also add this feature for PDF Template and Email Template creation?

What do you mean?

**Comment by rabiibrahimi** [comment]
the cursor is missing when focusing on the selectbox it would only appear after selecting an option. would be nice to have the cursor active on element focus.

**Comment by yurikuzn** [comment]
It's intentionally. To have it similar to the standard selectbox as much as possible.

**Comment by rabiibrahimi** [comment]
i understand 
thanks
