### ISSUE TITLE
Bottom panel still shows but throw '403: Access denied'

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2509]
**Describe the bug**
When I:
- Set relationship entity in "bottomPanels" - clientDefs instead of bottomPanelsDetail.json file.
- Set relationship entity permission:
	+ Create: yes
	+ Read: no
The bottom panel still shows but throw '403: Access denied'

**To Reproduce**
1. Delete the "leads" session in application\Espo\Modules\Crm\Resources\layouts\Campaign\bottomPanelsDetail.json file.
![Screenshot_20221117_023357](https://user-images.githubusercontent.com/97509528/202387435-f23bb86c-56e5-4b8e-84c6-54ec5a84a9da.png)

2. Add "bottomPanels" session in application\Espo\Modules\Crm\Resources\metadata\clientDefs\Campaign.json file.
```
"bottomPanels": {
	"detail": [
		{
			"name": "leads",
			"order": 3,
			"view": "views/record/panels/relationship",
			"rowActionsView": "views/record/row-actions/default"
		}
	]
}
```
![Screenshot_20221117_023432](https://user-images.githubusercontent.com/97509528/202387490-1c77bbb8-8686-4532-8a36-4e4b93db4ab2.png)

3. Create a role with the following permission:
- Campaigns:
	+ Create: yes
	+ Read: all
	+ Edit: all
	+ Delete: no
- Leads:
	+ Create: yes
	+ Read: no
	+ Edit: ano
	+ Delete: no
	+ Stream: no
![Screenshot_20221117_021339](https://user-images.githubusercontent.com/97509528/202387566-b64dbd8c-5aca-43a1-bd85-c7d841a10ff8.png)

4. Login by a regular user has the new role.
5. Go to Campaigns screen.

**Actual behavior**
The Leads bottom panel still shows but throw '403: Access denied'.
![Screenshot_20221117_021241](https://user-images.githubusercontent.com/97509528/202387673-ba9c37fe-0ed3-4692-937d-5c83b2ac9559.png)

**Expected behavior**
The Leads bottom panel should not show if user doesn't have 'read' permission.

**EspoCRM version**
EspoCRM version 7.2.6

**Comment by yurikuzn** [comment]
This is not a bug I think (very busy to investigate). You added metadata, rather than did manipulation via UI. Please try to solve such issues by your own, I'm too busy now.

**Comment by yurikuzn** [comment]
Here's what you need: 

https://github.com/espocrm/espocrm/blob/7.2.7/client/src/views/record/panels-container.js#L283
https://github.com/espocrm/espocrm/blob/7.2.7/client/src/utils.js#L186

You need to define `"aclScope": "Lead"` parameter.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/7.2.7/application/Espo/Resources/metadata/clientDefs/PortalUser.json#L43
