### ISSUE TITLE
when i am tried to import csv file in import module, i am getting 406 error how can i rectify this error. Any body have the solution?

### ISSUE THREAD

**Issue by keerthana-malar** [espocrm/espocrm#2510]
![406 error import data](https://user-images.githubusercontent.com/73170775/202518996-88e757f6-8fe5-4951-a0af-c80b96a64d35.jpg)

**Comment by arkadywtf** [comment]
It's likely not a bug. You should create a topic on the [forum](https://forum.espocrm.com/) (not in the bug report). If you believe it's a bug then please use the provided [bug report template](https://github.com/espocrm/espocrm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). More on bug reporting you can read [here](https://forum.espocrm.com/forum/bug-reports/23321-important-read-before-posting-how-to-report-a-bug).
