### ISSUE TITLE
Formula enhancements

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2513]
**Is your feature request related to a problem? Please describe.**
Currently formula works only before save, we often need to run formula **after save**, I have found workarounds but all are not like if we simply have after save formula, will be clearer for clients.
Another point is the formatting of formula, I wonder if having them **stored in files** would be better than json as encoded strings, something like **Call/afterSave.frml** would be great, large projects will be managed their code using git, and it is very useful to track the formula changes in clear way.

**Describe the solution you'd like**
I strongly hope this implemented into the core directly, I can help by contributing, if you dont like the idea then will think of making an extension, but will be more difficult.

**Comment by yurikuzn** [comment]
It would require a lot of thinking before implementing. Currently we are busy with other things, I can't answer whether we implement it at the moment.

**Comment by eymen-elkum** [comment]
Then we may keep this open for another discussion on the future

**Comment by yurikuzn** [comment]
JFI, after-save formula is available in Workflow tools.

**Comment by rabiibrahimi** [comment]
> What I planned, is to add additional formula script for API create/update calls (before). To be able to throw validation exceptions. My concern is that people will misunderstand the purpose of this too.

that would be great enhancement. totally get your point about after save hence workflow does the job, it is fair to keep such functionality in commercial extension (advanced pack). one enhancement i would like to see if the ability to access multiple attributes of a record. e.g when trying to get more than one attribute (currently using record/attribute works well but will be repeatetive to get more attributes -> will be great if this could be enhanced to get more attributes e.g record/attributes). 
Thanks

**Comment by eymen-elkum** [comment]
Thank you @yurikuzn for the information,

We have made an extension that trigger the save action for related entities and that was the main purpose of this feature request, so me too don’t think we need it any more.

Just a quick reminder about the formula saving if can be considered (low priority).
