### ISSUE TITLE
Field Level Permission doesn't apply to list

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2515]
**Describe the bug**
We have set up a (sales agent) role with all its permission, we need the sales agent to not view certain fields on few entities so we have set up those fields to read (no) edit (no) on the Field Level and it works fine but only on details view however those fields exists on the list view as well and therefore the sales agent is capable to see those fields on list view. 

**To Reproduce**
1. set up list view for account entity with fields like (name - type - phone - website)
2. create a role to see all accounts (view only) 
3. add Field Level permission on the and select field type (read: no) (edit: no)
4. access the crm with the new role and you will see that on the detail view of the account the type field is hidden but on the list view the user can still see the type field
...

**Expected behavior**
I expect when a Field Level permission is applied to a field then that permission should be applied to the list view alongside the detail view, meaning when a user's role is restricted to read/edit certain fields then the restriction should work on both detail view and list view of the entity. 

**Screenshots**

**EspoCRM version**
version 7.2.7
<img width="960" alt="Screenshot 2022-11-19 at 19 03 41" src="https://user-images.githubusercontent.com/19490674/202867467-b3489814-685c-422c-a669-710b29f93b7f.png">
<img width="1298" alt="Screenshot 2022-11-19 at 19 04 03" src="https://user-images.githubusercontent.com/19490674/202867471-34e64958-9611-4b52-8fad-9368c3dfb29b.png">

**Additional context**

**Comment by yurikuzn** [comment]
I doubt this is a bug. It would have been already reported. And I could not reproduce.

**Comment by yurikuzn** [comment]
Try reproduce on another instance (w/o customizations). Receiving such bug reports on weekends makes my life miserable.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/7.2.7/application/Espo/Core/Record/Service.php#L858
=>
https://github.com/espocrm/espocrm/blob/7.2.7/application/Espo/Core/Record/Service.php#L1626
