### ISSUE TITLE
Allow for setting additional database parameters during installation

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/espocrm#2516]
**Is your feature request related to a problem? Please describe.**

Running a fresh install does not provide entering specific DB params

**Describe the solution you'd like**

Allow these setting during install, possibly hidden in an "advanced" section.

```
$params['platform']
$params['sslCA']
$params['sslCert']
$params['sslKey']
$params['sslCAPath']
$params['sslCipher']
$params['sslVerifyDisabled']

```

**Describe alternatives you've considered**

Hardcoding in /resources/defaults/config.php

**Additional context**

**Comment by yurikuzn** [comment]
I believe if you write these parameters into `data/config-internal.php` > *database*, they will be applied upon installation.

**Comment by relyd** [comment]
Ok, yes that is a valid workaround.
