### ISSUE TITLE
Emails: Corresponding from-address pre-selected when replying on email

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2522]
If an email is sent to a user's non-primary personal email address, replying on it will pre-select that address as an from-address. Only for personal email accounts.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/a86ca38bd7803500c87d389a8fb78be47f22c06d

**Comment by yurikuzn** [comment]
It would be not desired behavior for many including us. We never send from group emails.

**Comment by rabiibrahimi** [comment]
I meant not sent but reply to an email received on group email accounts. if a user has access to few group email accounts and they have received an email on group email account when they reply it should reply from address of the email group they received the email on. sorry for any confusion.

**Comment by yurikuzn** [comment]
No confusion, I understood you right. If it had be implemented as a mandatory behavior it would be undesired for many including me as I always reply from personal email (it's a policy of many companies) but receive a lot of emails on the group account that I have access to.

**Comment by rabiibrahimi** [comment]
I understand one question please. when you say you reply from your personal email is that means that when the recipient replies back to you will their reply come to your personal email or the original group email account that received the first email ?

**Comment by rabiibrahimi** [comment]
Ok thank you so much for explaining this. appreciate it
