### ISSUE TITLE
loadAdditionalFields not called for child entities in PDF Templates

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2523]
**Describe the bug**
When using a PDF template that uses each to show child entity. The child entity loadAdditionalFields method is not called. 

**To Reproduce**
1. Create a nonStorable field on an entity
2. Populate this field in the Service using method "loadAdditionalFields"
3. Create a PDF template and use this field in a pdf template that is based off the parent of the entity you created the field on
4. Field is blank in PDF output

**Expected behavior**
loadAdditionalFields should execute for child entities used in PDF templates

**Screenshots based off attached zip file example**
![image](https://user-images.githubusercontent.com/7907518/204409021-cab18a28-9f36-4aa5-b766-efeba8b454cd.png)

**Additional context**
I have attached a zip containing a sample. 
[PDF load fields.zip](https://github.com/espocrm/espocrm/files/10108651/PDF.load.fields.zip)

Just create a PDF template based on Contact, template body:

---
Contact: {{name}}

{{#each details}}

{{name}} = {{notStored}}

{{/each}}
---

**Comment by yurikuzn** [comment]
I don't consider this as a bug. We should not use Record/Service internaly, the main purpose of that class is a layer for CRUD API.

Try using custom data loader https://github.com/espocrm/documentation/blob/master/docs/development/metadata/pdf-defs.md to load any data you need for PDF.

**Comment by yurikuzn** [comment]
I will take a look more when get a chance.
