### ISSUE TITLE
Tiny image in PDF

### ISSUE THREAD

**Issue by TanDuong-PTN** [espocrm/espocrm#2524]
Tiny image in PDF

**Describe the bug**
Images in wysiwyg field type don't show properly when I update the image size, it's so tiny.

**To Reproduce**
1. Create a new field names Wysiwyg has type is wysiwyg in Account entity.
2. Add Wysiwyg field to Detail layout.
3. Create a PDF Template for Account entity to print the Wysiwyg field.
![Screenshot_20221129_022425](https://user-images.githubusercontent.com/97509528/204468140-af5d1176-bd93-469f-9a11-622e42fbe8a5.png)

4. Create a new Account record. In this record, I add a image in Wysiwyg field and update the image size to 50% (Resize half).
![Screenshot (190)](https://user-images.githubusercontent.com/97509528/204468225-ee730695-32e3-490c-b554-84d6573a93f9.png)

5. Click Print to PDF button.

**Actual behavior**
The image is tiny in PDF.
![Screenshot_20221129_022443](https://user-images.githubusercontent.com/97509528/204468279-17ba097f-6346-42ef-8fe2-4d3717e6cdf8.png)

**Expected behavior**
The image size should be 50% page width.

**EspoCRM version**
EspoCRM latest version 7.2.7

**Comment by yurikuzn** [comment]
I don't consider this a bug. If you can help with a fix, please.

**Comment by yurikuzn** [comment]
Wysiwyg printed in PDF was not an intentional functionality.

**Comment by TanDuong-PTN** [comment]
@yurikuzn 
TCPDF does not support styling with percentage. Percentage number will be converted to wrong size:
https://github.com/tecnickcom/TCPDF/issues/275
But before print a field in PDF, we can add a function to convert the Wysiwyg field content to not use percentage in.
