### ISSUE TITLE
How to remove the restriction of 'frame'

### ISSUE THREAD

**Issue by admin0o0** [espocrm/espocrm#2525]
Version 7.2.7  
How to remove the restriction of 'frame'

**Comment by admin0o0** [comment]
<iframe src="http://xxx.xxx" style="width:100%;height:100%;border:none;"></iframe>

**Comment by eymen-elkum** [comment]
Enable security skips from your config.php file, see this link:

https://docs.espocrm.com/administration/config-params/#security

**Comment by yurikuzn** [comment]
Added a separate parameter `clientXFrameOptionsHeaderDisabled` for v7.3.
