### ISSUE TITLE
ui, bottom panel headers not show all letters

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2529]
I was going to make a pull request but thought you may like to do it differently 
https://demo.us.espocrm.com/?l=en_US#Contact/view/5f607b7ac109b5cca
<img width="248" alt="Screenshot 2022-12-09 at 4 43 46 PM" src="https://user-images.githubusercontent.com/2862528/206715850-8c931dce-8f88-45c4-a681-7433f38722f3.png">

**Comment by yurikuzn** [comment]
Seems to be already fixed on master.
