### ISSUE TITLE
Email: Corresponding from-address pre-selected when replying on email - Group Email

### ISSUE THREAD

**Issue by Cri00** [espocrm/espocrm#2530]
If an email is sent to a group email address, replying on it will pre-select that address as an from-address. 

This is necessary for users who are part of different teams with different group email address.

**Comment by yurikuzn** [comment]
It would be an undesired behavior for many us it's a regular practice when users always replying from their own identity receiving emails to a group email account. Maybe as a preferences parameter in the future but not for now.

**Comment by Cri00** [comment]
Thanks. The idea was that if user X is part of 2 teams and a client sends him an email, when reply user X will send the email by default from first team email, not the second even if the email was sent to the second team address.
