### ISSUE TITLE
Hide and Show Navigation Panel Translations

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2531]
Hi Yuri,

Both the strings "Hide Navigation Panel" and "Show Navigation Panel" are not present in the languages files nor POEditor.
Could you please fix that so that these strings can be translated using POEditor?

https://github.com/espocrm/espocrm/blob/4634597b7fe2bdfd6fb281f1f968985fa06ea0fd/client/res/templates/record/list-nested-categories.tpl#L43

**Comment by yurikuzn** [comment]
Added. To POEditor will be added later.
