### ISSUE TITLE
DefaultPDOProvider is hardcoded

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2537]
**Is your feature request related to a problem? Please describe.**
I'd like to use EspoCRM with Postgres. I assumed that it would only take extending the BaseQueryComposer class, but you hit a brick wall much sooner. In Espo\ORM\PDO\PDOProvider, there is this code:

`        if ($charset) {
            $dsn .= ';' . 'charset=' . $charset;
        }
`

With the code as is, the PDO constructor throws an exception. The problem is that to properly pass the charset option to postgres, the code would have to be like this:

`
        if ($charset) {
             $dsn .= ';' . 'options=' . "'--client_encoding=$charset'";
         }
`

The PDOProvider class is used in 2 places, Espo/Core/Utils/Database/Helper and Espo/Core/ORM/EntityManagerFactory. In EntityManagerFactory, it's created through InjectableFactory, but in the PDOProvider, it's simply hardcoded.

**Describe the solution you'd like**
Probably create a PDOProvider factory to create the PDOProvider, which would allow replacing the DefaultPDOProvider.

**Describe alternatives you've considered**
I don't believe any upgrade-safe solutions currently exist.

**Additional context**
Espo/Core/Utils/Database/Helper (line 235):
`
        $pdoProvider = new DefaultPDOProvider(
            $this->createDatabaseParams($params)
        );
`

Espo/Core/ORM/EntityManagerFactory (line 116):
`
        $pdoProvider = $this->injectableFactory->createWithBinding(
            DefaultPDOProvider::class,
            BindingContainerBuilder::create()
                ->bindInstance(DatabaseParams::class, $databaseParams)
                ->build()
        );
`

**Comment by yurikuzn** [comment]
This can't be solved quickly as it's quite core logic and would require some revising. As a temporary workaround consider defining a custom loader instead of `Espo\Core\Loaders\EntityManager`. See the article Dependency Injection in the docs on how to define custom loaders (for container services).

**Comment by SuchAFuriousDeath** [comment]
Thank you very much for the quick answer, I'll try it out.

**Comment by yurikuzn** [comment]
Turned out to be a huge commit: https://github.com/espocrm/espocrm/commit/49bb6771f6b8abf82aa12b69e2b27481d076c202. Had to untangle a legacy mess in ORM metadata converter to be able to use DI there.

Introduced a PDOFactory https://github.com/espocrm/espocrm/blob/49bb6771f6b8abf82aa12b69e2b27481d076c202/application/Espo/Resources/metadata/app/orm.json#L8.

Will be available in v7.4.

**Comment by SuchAFuriousDeath** [comment]
Wow, amazing. Can't wait for 7.4.
