### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by kczereczon** [espocrm/espocrm#2538]
**Is your feature request related to a problem? Please describe.**
Performance of development on Apple Silicon is very low because of amd64 emulation

**Describe the solution you'd like**
Create support for arm64 architecture on docker, get rid of PhantomJS that causes problems on Apple Silicon (missing binary)

**Comment by kczereczon** [comment]
Yes sure, but before that we need to get rid of PhantomJS which occurs in npm dependencies. PhantomJS does not support arm64, we need find alternative with arm64 support

**Comment by kczereczon** [comment]
eg. puppeteer instead of phantom

**Comment by yurikuzn** [comment]
Could you point out where we use phantom. I can't recall it neither can find it in npm ls.

**Comment by yurikuzn** [comment]
Did you try to disable its installation in package.json?

**Comment by yurikuzn** [comment]
This package is not installed on my dev instance at least.

**Comment by kczereczon** [comment]
We work with 7.0.10 currently, glad to hear that in latest version phantom has been removed, im closing nad create feature request on docker repo, thanks
