### ISSUE TITLE
Task: Date Completed not being imported

### ISSUE THREAD

**Issue by rochiey** [espocrm/espocrm#2541]
**Describe the bug**
During import, the csv has provided a "Date Completed" field. The espocrm overrides that date and uses time now as a date completed instead of the one provided in the csv.

**To Reproduce**
1. Go to Administration > Import
2. Import a task csv, map the fields
3. Import. And then check the task section to see that the dateCompleted is wrong.

**Expected behavior**
The csv provided the status of those task to be completed, the csv also provided when it was completed. System should not override the dateCompleted. System should use the dateCompleted provided in the csv

**Screenshots**
See more in #2540 

**EspoCRM version**
Version 7.2.7

**Additional context**
See more in #2540

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/4dec6b8d49a2ebca2f21f4e180f158b1d517a38c

**Comment by rochiey** [comment]
@yurikuzn how do I pull the fix. I actually downloaded EspoCRM on a zip file from the website. Should I delete the EspoCRM from my directory and clone this repo instead?

**Comment by yurikuzn** [comment]
I'd recommend waiting to the release and upgrade like it's recommended in the docs.

You can also apply similar fix manually. Change this line https://github.com/espocrm/espocrm/blob/7.1.7/application/Espo/Modules/Crm/Repositories/Task.php#L44 to:
```php
if ($entity->isAttributeChanged('status') && empty($options['import'])) {
```
