### ISSUE TITLE
API request handling with PSR-15 middlewares

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2543]
The ability to add middlewares for all requests, specific routes, controllers and controller actions. Supporting the PSR-15 standard means that it's possible to use 3rd party middlewares, like [these](https://github.com/middlewares/psr15-middlewares). If a middleware you want to use has dependencies in a constructor, use DI binding to resolve them.

See in the [docs](https://github.com/espocrm/documentation/blob/master/docs/development/metadata/app-api.md).

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/28d8fcd31e1fb402f975119926cc57de9a89a458

**Comment by eymen-elkum** [comment]
This is very interesting feature, I just wonder if there is already middlewares defined on EspoCRM? or if there is an example we can follow?

I noticed the doc of psr15-middlewares just not sure if they are applicable as it is in espo, I have to make test but liked to see if there is already something more we can use before make the try.

**Comment by yurikuzn** [comment]
There's no any in Espo. Since it's an official standard some might want to utilize middlewares to handle request or response for their needs. Adding specific headers for all routes, or for specific controller.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/a0d39be19cccaf65d97ee0432c6da01c33157b70
