### ISSUE TITLE
BaseQueryComposer not using correct first day of week

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2555]
The first day of the week for my organization is Sunday. However, the SQL queries generated by the BaseQueryComposer have a hard-coded mode of 3 in the YEARWEEK function. As seen [here](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_week), mode 3 means the week starts on Monday, which is incorrect.

Settings:
<img width="162" alt="image" src="https://user-images.githubusercontent.com/1170415/211180036-2226cd58-d986-4ce0-86fa-6294cb629289.png">

Relevant SQL generated by the BaseQueryComposer:
```
CONCAT(SUBSTRING(YEARWEEK(CONVERT_TZ(NOW(), '+00:00', '-07:00'), 3),1,4),'/',TRIM(LEADING '0' FROM SUBSTRING(YEARWEEK(CONVERT_TZ(NOW(), '+00:00', '-07:00'), 3),5,2))),
CONCAT(SUBSTRING(YEARWEEK(CONVERT_TZ(session.date_start, '+00:00', '-07:00'),3),1,4),'/',TRIM(LEADING '0' FROM SUBSTRING(YEARWEEK(CONVERT_TZ(session.date_start, '+00:00', '-07:00'),3),5,2)))
```

As you can see, the mode is set to 3 when it should be set to 2. It looks like this will fail if the first day of the week is anything other than Sunday or Monday as the mode only supports those two days. See #1953 for reference.

The origin of the query is an Expression:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/1170415/211180135-7a5c45ef-7a07-4f77-951d-aaca85110b01.png">

When I run the query with the mode set to 2 instead of 3, it selects the correct data. I have verified this multiple times.

**Comment by yurikuzn** [comment]
Expression functions (and everything behind the QueryComposer interface) are config agnostic.

* `WEEK` & `WEEK_1` – uses mode = 3 (there's a mistake in the docs_;
* `WEEK_0` – uses mode = 6.

There's no functions for other week starts.

**Comment by bandtank** [comment]
Ok, I see. Thanks.
