### ISSUE TITLE
BackDrop: false not working

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2556]
**Describe the bug**
Please correct me if I am wrong but as I've seen from other libraries backdrop should work as follow:
backdrop: 'static', //blur background, clicking outside of it **will NOT close** the modal
backdrop: true, //normal background, clicking outside of it **will close** the modal
backdrop: false, //normal background, clicking outside of it **will NOT close** the modal
Even the documentation states:
` // if true, clicking on the backdrop will close the dialog`
`backdrop: true, // 'static', true, false`
If I am correct then backdrop false isn't working as it is behaving the same as backdrop: true
If I am wrong I am sorry if I misunderstood how backdrop works.

**To Reproduce**
1. Create a new Modal Form following this instructions https://docs.espocrm.com/development/modal/#modal-form
2. Use backdrop: false, 
3. Click outside of the modal
The modal will close even if the backdrop value is false.

**Expected behavior**
Backdrop should not close just like if the value was 'static'.

**EspoCRM version**
EspoCRM 7.2.7

**Additional context**
PHP 8.0

**Comment by yurikuzn** [comment]
Modals was not designed to be able to be unfocused to access elements under the modal. Try using Espo.Ui.dialog instead.

**Comment by Kharg** [comment]
Thanks for the explanation.
