### ISSUE TITLE
PHP 8.1.14 - PHP Fatal error:  Uncaught ValueError: class_alias(): Argument #1 ($class) must be a user-defined class name

### ISSUE THREAD

**Issue by nephaste** [espocrm/espocrm#2557]
Hi, i am trying to push EspoCRM 7.3.0 on Qnap NAS

while with PHP 8.0.27, i have no issue

stating with PHP 8.1.14, remain in error

logs from Apache 2.4.54 reveal :

n Jan 09 13:19:32.048608 2023] [authz_core:debug] [pid 5169:tid 140036901328640] mod_authz_core.c(818): [client 192.168.0.2:45429] AH01626: authorization result of Require all granted: granted, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.048649 2023] [authz_core:debug] [pid 5169:tid 140036901328640] mod_authz_core.c(818): [client 192.168.0.2:45429] AH01626: authorization result of <RequireAny>: granted, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.048706 2023] [charset_lite:debug] [pid 5169:tid 140036901328640] mod_charset_lite.c(219): [client 192.168.0.2:45429] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.048853 2023] [authz_core:debug] [pid 5169:tid 140036901328640] mod_authz_core.c(818): [client 192.168.0.2:45429] AH01626: authorization result of Require all granted: granted, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.048887 2023] [authz_core:debug] [pid 5169:tid 140036901328640] mod_authz_core.c(818): [client 192.168.0.2:45429] AH01626: authorization result of <RequireAny>: granted, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.048918 2023] [charset_lite:debug] [pid 5169:tid 140036901328640] mod_charset_lite.c(219): [client 192.168.0.2:45429] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.048984 2023] [authz_core:debug] [pid 5169:tid 140036901328640] mod_authz_core.c(818): [client 192.168.0.2:45429] AH01626: authorization result of Require all granted: granted, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.048993 2023] [authz_core:debug] [pid 5169:tid 140036901328640] mod_authz_core.c(818): [client 192.168.0.2:45429] AH01626: authorization result of <RequireAny>: granted, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.049036 2023] [charset_lite:debug] [pid 5169:tid 140036901328640] mod_charset_lite.c(219): [client 192.168.0.2:45429] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.85:8080/
[Mon Jan 09 13:19:32.067334 2023] [php:error] [pid 5169:tid 140036901328640] [client 192.168.0.2:45429] PHP Fatal error:  Uncaught ValueError: class_alias(): Argument #1 ($class) must be a user-defined class name, internal class name given in /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php:14\nStack trace:\n#0 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php(14): class_alias()\n#1 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/composer/autoload_real.php(55): require('/share/CACHEDEV...')\n#2 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/composer/autoload_real.php(38): composerRequire913e5516c3915b44ffadc5b89261eb75()\n#3 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/autoload.php(25): ComposerAutoloaderInit913e5516c3915b44ffadc5b89261eb75::getLoader()\n#4 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/bootstrap.php(33): require_once('/share/CACHEDEV...')\n#5 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/public/index.php(30): include('/share/CACHEDEV...')\n#6 {main}\n  thrown in /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php on line 14, referer: http://192.168.0.85:8080/

any clue on how to fix it ?

**Comment by nephaste** [comment]
getting same problem with PHP 8.1.0

[Mon Jan 09 14:37:24.902400 2023] [charset_lite:debug] [pid 14932:tid 139912581592832] mod_charset_lite.c(219): [client 192.168.0.2:41765] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.85:8080/
[Mon Jan 09 14:37:24.934142 2023] [php:error] [pid 14932:tid 139912581592832] [client 192.168.0.2:41765] PHP Fatal error:  Uncaught ValueError: class_alias(): Argument #1 ($class) must be a user-defined class name, internal class name given in /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/vendor/laminas/laminas-servicemanager/src/autoload.php:14\nStack trace:\n#0 /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/vendor/laminas/laminas-servicemanager/src/autoload.php(14): class_alias()\n#1 /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/vendor/composer/autoload_real.php(55): require('...')\n#2 /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/vendor/composer/autoload_real.php(38): composerRequire913e5516c3915b44ffadc5b89261eb75()\n#3 /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/vendor/autoload.php(25): ComposerAutoloaderInit913e5516c3915b44ffadc5b89261eb75::getLoader()\n#4 /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/bootstrap.php(33): require_once('...')\n#5 /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/public/index.php(30): include('...')\n#6 {main}\n  thrown in /share/CACHEDEV1_DATA/.qpkg/EspoCRM82/www/vendor/laminas/laminas-servicemanager/src/autoload.php on line 14, referer: http://192.168.0.85:8080/
[Mon Jan 09 14:37:24.934715 2023] [optional_hook_import:error] [pid 14932:tid 139912581592832] AH01866: Optional hook test said: GET / HTTP/1.1
[Mon Jan 09 14:37:24.934726 2023] [optional_fn_export:error] [pid 14932:tid 139912581592832] AH01871: Optional function test said: GET / HTTP/1.1
[Mon Jan 09 14:37:25.199887 2023] [example_hooks:notice] [pid 14863:tid 139913573058432] x_monitor()
[Mon Jan 09 14:37:32.305533 2023] [example_hooks:notice] [pid 14932:tid 139912564807424] x_create_connection()
[Mon Jan 09 14:37:32.305630 2023] [example_hooks:notice] [pid 14932:tid 139912564807424] x_create_request()
[Mon Jan 09 14:37:35.210095 2023] [example_hooks:notice] [pid 14863:tid 139913573058432] x_monitor()
[Mon Jan 09 14:37:45.220050 2023] [example_hooks:notice] [pid 14863:tid 139913573058432] x_monitor()

**Comment by yurikuzn** [comment]
I don't know how issue with class_alias could happen to you, as classes should be in vendor. Nevertheless, I added the fix fix for this case in v7.3.1.

**Comment by nephaste** [comment]
just tried with 7.3.1..; issue is same form (all work with php 8.0.x)

[Tue Jan 10 10:48:22.049306 2023] [charset_lite:debug] [pid 20192:tid 139997277583104] mod_charset_lite.c(219): [client 192.168.0.2:36057] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.85:8080/
[Tue Jan 10 10:48:22.052600 2023] [php:error] [pid 20192:tid 139997277583104] [client 192.168.0.2:36057] PHP Fatal error:  Uncaught ValueError: class_alias(): Argument #1 ($class) must be a user-defined class name, internal class name given in /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php:14\nStack trace:\n#0 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php(14): class_alias()\n#1 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/composer/autoload_real.php(55): require('/share/CACHEDEV...')\n#2 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/composer/autoload_real.php(38): composerRequire913e5516c3915b44ffadc5b89261eb75()\n#3 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/autoload.php(25): ComposerAutoloaderInit913e5516c3915b44ffadc5b89261eb75::getLoader()\n#4 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/bootstrap.php(33): require_once('/share/CACHEDEV...')\n#5 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/public/index.php(30): include('/share/CACHEDEV...')\n#6 {main}\n  thrown in /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php on line 14, referer: http://192.168.0.85:8080/

**Comment by nephaste** [comment]
just tried with 7.3.1..; issue is same form (all work with php 8.0.x)

[Tue Jan 10 10:48:22.049306 2023] [charset_lite:debug] [pid 20192:tid 139997277583104] mod_charset_lite.c(219): [client 192.168.0.2:36057] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.85:8080/
[Tue Jan 10 10:48:22.052600 2023] [php:error] [pid 20192:tid 139997277583104] [client 192.168.0.2:36057] PHP Fatal error:  Uncaught ValueError: class_alias(): Argument #1 ($class) must be a user-defined class name, internal class name given in /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php:14\nStack trace:\n#0 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php(14): class_alias()\n#1 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/composer/autoload_real.php(55): require('/share/CACHEDEV...')\n#2 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/composer/autoload_real.php(38): composerRequire913e5516c3915b44ffadc5b89261eb75()\n#3 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/autoload.php(25): ComposerAutoloaderInit913e5516c3915b44ffadc5b89261eb75::getLoader()\n#4 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/bootstrap.php(33): require_once('/share/CACHEDEV...')\n#5 /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/public/index.php(30): include('/share/CACHEDEV...')\n#6 {main}\n  thrown in /share/CACHEDEV1_DATA/.qpkg/EspoCRM81/www/vendor/laminas/laminas-servicemanager/src/autoload.php on line 14, referer: http://192.168.0.85:8080/
