### ISSUE TITLE
GlobalSearch customization

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2560]
There was ability to customize GlobalSearch backend by putting code in 'Custom/Services/GlobalSearch.php' before 7.3 update. Now 'Espo/Services/GlobalSearch.php' is gone and same code found in 'Tools/GlobalSearch/Service.php'. How it can be customized correctly now ?

**Comment by yurikuzn** [comment]
Bind `Espo\Tools\GlobalSearch\Service` to the extended class `Espo\Custom\Tools\GlobalSearch\Service` in the binder.

But I'd recommend to try to achieve needed customizations with the *Select* framework if possible.

**Comment by yurikuzn** [comment]
See https://docs.espocrm.com/development/di/#binding

**Comment by yurikuzn** [comment]
You can also define a custom controller or even route and use completely own service class. To avoid using any extending. Extending (with a few exception) is not future proof.
