### ISSUE TITLE
Mass Action header text translation

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2561]
Hi Yuri,

Could you please add the Mass Action Header and its actions to the language files?

![image](https://user-images.githubusercontent.com/32223252/211963495-6b8d1650-bb6c-43fe-a08c-17aa296cbaca.png)

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/093d71e5ae9936db6cf81f60273a9bc3318e2faa

**Comment by Kharg** [comment]
HI Yuri,
This line as well needs to be translated "Mass Action" 
https://github.com/espocrm/espocrm/blob/6f676c8a2f0b55f430e8497a6a758b263978ab43/client/src/views/modals/mass-action.js#L51
