### ISSUE TITLE
Version 7.3.1 multiple errors

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#2562]
[2023-01-13 11:37:48] ERROR: (42S22) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user.working_time_calendar_id' in 'field list'; GET /Activities/action/popupNotifications; line: 70, file: /home/crm/public_html/application/Espo/ORM/SqlExecutor.php [] []

[2023-01-13 11:37:43] WARNING: E_WARNING: foreach() argument must be of type array|object, null given {"code":2,"message":"foreach() argument must be of type array|object, null given","file":"/home/crm/public_html/application/Espo/Core/Utils/Database/Orm/Converter.php","line":427} []

After upgrading to 7.3.1 from 7.2.6 these two errors are constantly popping up in the logs.
The second log is generating an error log for every each request. (basically filling up the storage with errors.)

PHP 8.0 and PHP 8.1 were tested with OpenLiteSpeed.

Additionally, after upgrading to 7.3.1 in the browser console this error is always showing up:

![image](https://user-images.githubusercontent.com/66499378/212312553-db5b66b9-a9d8-465f-ad07-219010df8614.png)

**You can even see it in portal.espocrm.com and demo.espocrm.com.**

**Comment by kboykov** [comment]
Additionally, the dashboard are broken (idk if that's due to the 'could not open 'espo' cache' error).
![image](https://user-images.githubusercontent.com/66499378/212316340-5c36a0ac-f35e-4128-a288-f24aaede95f7.png)

**Comment by yurikuzn** [comment]
Try a different browser to check if there's the JS error.

Regarding errors in log, please try debugging, rebuilding. It could be specific to your instance.

**Comment by Kharg** [comment]
> Additionally, the dashboard is broken (idk if that's due to the 'could not open 'espo' cache' error).
> 
> ![image](https://user-images.githubusercontent.com/66499378/212316340-5c36a0ac-f35e-4128-a288-f24aaede95f7.png)
> 
> 

For this you have to update Modern Theme to the latest version.

**Comment by arkadywtf** [comment]
> Column not found: 1054 Unknown column 'user.working_time_calendar_id' in 'field list';

Had the same error while using a docker instance. When I ran the upgrade command again everything went correctly. I'll see if I can reproduce the issue.

**Comment by yurikuzn** [comment]
The error is mentioned here: https://forum.espocrm.com/forum/announcements/86871-espocrm-v7-3-0-released#post86926. Can happen if an environment does not support running CLI commands from PHP or the upgraded is run with -s parameter. The next upgrade package should solve this isssue.

**Comment by kboykov** [comment]
The problem with the console error was browser related (cache).

The problem with the PHP errors was fixed after rebuilding.

The problem with the UI was due to outdated 3rd party "Modern Theme".
