### ISSUE TITLE
PDF: Dompdf engine

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2564]
[Dompdf](https://github.com/dompdf/dompdf) has much better CSS support than the Tcpdf engine Espo currently uses.

Engine can be switched at Administration > Settings > PDF Engine.

Limitations:

* No mass print into a single PDF. Multiple PDFs are zipped instead.
* No ability to print a total number of records (in footer & header).
* Barcode text, padding, bg color do not work. Can be easily achieved by adding needed code in a template.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/6339690e58ae4bc8aae8f94d1d2dd2f0dcde5312

**Comment by allahcurse** [comment]
Does that mean that we will also get Inline PHP support? (Its a part of Dompdf)

**Comment by yurikuzn** [comment]
Never, unless you customize it. It would be a security disaster.
