### ISSUE TITLE
OIDC Get Token params should include client_secret

### ISSUE THREAD

**Issue by ecg-io** [espocrm/espocrm#2565]
**Issue**

When requesting a new token with grant_type = authorization_code, you send the code along with the client_id and client_secret.  The secret seems to be missing from this set of params:  

https://github.com/espocrm/espocrm/blob/c7b7848e69fdfc27bcd5ac55fd403af2e91aae77/application/Espo/Core/Authentication/Oidc/Login.php#L185

**Workaround/Fix**

I was able to get this working by pulling the secret from the config `$this->config->get('oidcClientSecret');`

**Error message:**

Trying to do a login with a new user and seeing this:
`[2023-01-14 05:41:10] WARNING: OIDC: Token request error.; Status: 401; Response: {"error":"invalid_client","error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: <>\r\nCorrelation ID: <>\r\nTimestamp: 2023-01-14 05:41:10Z","error_codes":[7000218],"timestamp":"2023-01-14 05:41:10Z","trace_id":"<>","correlation_id":"<>","error_uri":"https://login.microsoftonline.com/error?code=7000218"} [] []`

**Comment by yurikuzn** [comment]
It should work if you enabled public clients on Azure side. I will take a look.
