### ISSUE TITLE
Improve function string\replace

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2568]
**Is your feature request related to a problem? Please describe.**
The current function action only string where is the php str_replace accepts both string and array. currently the function is limited to replace only one string per time so we end up replacing multiple paragraphs for just one text. Means if i have a text i need to search each phrase and replace it is content separately. 

**Describe the solution you'd like**
Solution is to enable full function capacity built by PHP by allowing it to accept string or array. 

**Describe alternatives you've considered**
Only alternative way is to build another custom function that return str_replace without checking is params are string.

**Additional context**

**Comment by yurikuzn** [comment]
PHP's supporting strings or arrays for one function parameter is an example of bad design. They would introduced new function like replaceMany had they developed std lib today.

**Comment by yurikuzn** [comment]
I'll consider adding a new function for this. You can create your own to solve your current problem for this time.

**Comment by rabiibrahimi** [comment]
Thanks @yurikuzn that what i have done created a custom one but i would appreciate if you consider adding another function which supports array. 

Many thanks
