### ISSUE TITLE
[HELP] Unable to add a new field in a custom entity

### ISSUE THREAD

**Issue by Virtute90** [espocrm/espocrm#2569]
**Describe the bug**
With a custom entity I can't insert new fields.

**To Reproduce**
1. Go to entity manager
2. Select the entity
3. Add new field

**Expected behavior**
Add new field

**EspoCRM version**
7.2.6

**Additional context**
Error to screen:
```
Error 500
Can't read field defs Voucher.test.
```
Log:
`[2023-01-18 11:54:01] ERROR: (500) Can't read field defs Voucher.test.; POST /Admin/fieldManager/Voucher; line: 110, file: /var/www/html/application/Espo/Tools/FieldManager/FieldManager.php :: #0 /var/www/html/application/Espo/Controllers/FieldManager.php(122): Espo\Tools\FieldManager\FieldManager->read('Voucher', 'test') #1 /var/www/html/application/Espo/Core/Api/ActionProcessor.php(100): Espo\Controllers\FieldManager->postActionCreate(Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #2 /var/www/html/application/Espo/Core/Api/RequestProcessor.php(141): Espo\Core\Api\ActionProcessor->process('FieldManager', 'create', Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #3 /var/www/html/application/Espo/Core/Api/RequestProcessor.php(112): Espo\Core\Api\RequestProcessor->proceed(Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #4 /var/www/html/application/Espo/Core/Api/RequestProcessor.php(83): Espo\Core\Api\RequestProcessor->processInternal(Object(Espo\Core\Api\Route), Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #5 /var/www/html/application/Espo/Core/Api/Starter.php(103): Espo\Core\Api\RequestProcessor->process(Object(Espo\Core\Api\Route), Object(Espo\Core\Api\RequestWrapper), Object(Espo\Core\Api\ResponseWrapper)) #6 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Espo\Core\Api\Starter->Espo\Core\Api\{closure}(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #7 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #8 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Psr7\Request)) #9 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #10 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #11 /var/www/html/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Psr7\Request)) #12 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request)) #13 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner)) #14 /var/www/html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) #15 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #16 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request)) #17 /var/www/html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #18 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Psr7\Request)) #19 /var/www/html/application/Espo/Core/Api/Starter.php(79): Slim\App->run() #20 /var/www/html/application/Espo/Core/ApplicationRunners/Api.php(49): Espo\Core\Api\Starter->start() #21 /var/www/html/application/Espo/Core/Application/RunnerRunner.php(85): Espo\Core\ApplicationRunners\Api->run() #22 /var/www/html/application/Espo/Core/Application.php(81): Espo\Core\Application\RunnerRunner->run('Espo\\Core\\Appli...', NULL) #23 /var/www/html/public/api/v1/index.php(37): Espo\Core\Application->run('Espo\\Core\\Appli...') #24 {main} [] []
`

**Comment by yurikuzn** [comment]
For help, please create a topic on the forum (not in the bug reports section). This feature is working on properly configured environment.
