### ISSUE TITLE
Set correct email status when fetch sent emails

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2570]
**Is your feature request related to a problem? Please describe.**
Currently when crm fetch the email it sets the status as (archived) even though emails sent are set as archived. It would be nice if there is a way to set the correct email status based on fetched emails source e.g email is fetched from inbox status should be (archived) or if email is fetched from sent folder then status should be set as (sent). 

**Describe the solution you'd like**
Ability for the crm to set each status according to which folder the email was fetched from.

**Describe alternatives you've considered**
We use workflow to change the status of fetched emails, if they are fetched from sent folder we set their status to (sent).

**Additional context**

**Comment by yurikuzn** [comment]
It's how it was designed and can't be changed now.

**Comment by yurikuzn** [comment]
* Sent -- sent from CRM.
* Archived -- imported.


The way you propose does not suit the logic the application uses. One email can be sent for one user, but it's not sent for another.

**Comment by rabiibrahimi** [comment]
Yes one email can be sent for one user and received by other user. first user email is set as (sent) and second user email status (archived). 
issue currently archived emails includes emails sent from other client and fetched into the crm. when crm fetched the emails is it possible to figure out which inbox the email is fetched from ?

**Comment by yurikuzn** [comment]
Espo imports one email for two users. It can't be both archived and sent.

The current logic is correct. You might need another field to distinguish emails sent to client and received from clients. But it would be an endeavor to have this logic.

**Comment by yurikuzn** [comment]
In Espo terms, there is only one email in the word. It can't have status sent, as every email is sent (unless draft).

**Comment by rabiibrahimi** [comment]
Thanks for the explanation.
