### ISSUE TITLE
Custom routes in modules must use unique controller names

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2575]
**Describe the bug**
Controller names are not isolated in modules. Defining two routes in two custom modules with the same controller names causes one controller to be ignored.

**To Reproduce**
Create two modules with controllers that have the same name. Add custom routes to each controller:
```
In custom/Espo/Modules/Mod1/Resources/routes.json:
{
      "route": "TestRoute1",
      "params": {
          "controller": "Message",
          "action": "incoming"
      ...
}
```
In custom/Espo/Modules/Mod2/Resources/routes.json:
```
{
      "route": "TestRoute2",
      "params": {
          "controller": "Message",
          "action": "incoming"
      ...
}
```
In custom/Espo/Modules/<Modules>/Controllers/, define two controllers called `Message.php`.

Call both endpoints and the same controller will respond to the request.

**Expected behavior**
I expected the controllers to be isolated to the namespace of the modules instead of being global. The routes.json file does not have a way to specify a namespace for the controller, which means all controllers must have unique names.

**Comment by SuchAFuriousDeath** [comment]
I don't want to speak for Yuri, but I think this is a feature and not a bug. If the Controllers were isolated, you couldn't 'override' a controller from a different module or a base one from Espo to change functionality.

**Comment by yurikuzn** [comment]
It is a core design concept in Espo. Changing this now would mean breaking what is working.

**Comment by bandtank** [comment]
I disagree with both of you, but it won’t be fixed so it is what it is. Extensions collide with each other as a result of this bug, which is how I ran into the issue. I guess I’ll modify the extension.

**Comment by yurikuzn** [comment]
This is not a bug. It cannot  be fixed the way you propose without breaking existing extensions.

**Comment by yurikuzn** [comment]
You disagree with that we should not break what is working? Causing troubles for many existing users. 

The proper way to solve the problem would be incorporate a qualified class names support. That is planned. With middleware it is also possible to have isolated logic.

**Comment by bandtank** [comment]
I disagree that this isn’t a problem or bug. It doesn’t break anything if there is an optional namespace parameter. I don’t know what you mean by middleware, but that sounds more complicated when there is a simpler solution.

**Comment by eymen-elkum** [comment]
Modules must be self contained, if there is a dependency you can easily check for it on the after install and let the controller extend the one on the dependency.
I think this is not issue or bug.

**Comment by yurikuzn** [comment]
The problem exists but we cannot call it a bug as it works as is was expected to work. we should separate two terms: controller name and class name. currtently routes operate with controller names. They are global by design and it cannot be changed without compatibility break. This is a legacy from times when espo was a small app. The solution that I have planned is to incorporate an actionClassName param in routes. 

Regarding middleware s it's very easy to use, it's a defacto industry standard. It is coming in the next release.

**Comment by yurikuzn** [comment]
Why action class but not controller. To be able to use an interface. Much more handy to create a new class implementing an interface in IDE. Method and parameters are automatically generated. Plus different actions often have different dependencies.
