### ISSUE TITLE
Search box for Admin Labels

### ISSUE THREAD

**Issue by marcusquinn** [espocrm/espocrm#2576]
**Is your feature request related to a problem? Please describe.**
Often we want to change the label for something from the default. 

**Describe the solution you'd like**
Add a search input to filter Admin > Labels

**Describe alternatives you've considered**
Since all panels are collapsed, browser search for them doesn't work.

**Additional context**

**Comment by yurikuzn** [comment]
I though about that too.

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/c35545c209cf5114e44fa487efddffb166ac25cc
