### ISSUE TITLE
OIDC: Portal support

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2578]
A separate Authentication Provider entity that can be linked to a Portal entity. Quite a big overhaul.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/15f337a3199cadc926d1d91a4b57a1ab17ba9465

**Comment by emillod** [comment]
@yurikuzn i think there is a problem if identification (sub) is not hashed. In this scenario user will receive "No hash." error. After i switch sub to hashed user id, everything is okay, but username is like 2846e42c30ae73c0033978b6c3cccc4fd3b974514fea38ef9766e9545e4aec01

I'm still testing it

**Comment by yurikuzn** [comment]
I understand nothing from it. Unfortunately, I'm extremely not having time. Please try to investigate the problem and let me know in case you found a solution.

**Comment by emillod** [comment]
@yurikuzn i described everything on forum: https://forum.espocrm.com/forum/bug-reports/87526-issue-with-portal-sso-in-7-4-no-hash#post87526
I'm trying to investigate also on my end in the same time. :)

**Comment by yurikuzn** [comment]
It works for me with user names that not are hashes.

**Comment by emillod** [comment]
@yurikuzn it is working on my environment only for main crm, not for portal.. I'll investigate it deeper...

**Comment by emillod** [comment]
@yurikuzn i've configured everything from scratch and it seems working for now. Sorry for taking you from other things. Have a great night.

**Comment by yurikuzn** [comment]
Could be some customization you did on that instance?

**Comment by emillod** [comment]
Can't tell. Tomorrow i'm starting tests so i'll report if i find something :) Great changes coming in 7.4, thank you!
