### ISSUE TITLE
Fetching values to model after opening the record detail sometimes causes onChange call in the dynamic handler

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2579]
**Describe the bug**
Fetching values to model after opening the record detail sometimes causes onChange call in the dynamic handler. The change event is unrecognizable from any other change event. 

**To Reproduce**
1. Create a dynamic handler, that listens to the field's change. The field must not be present in the list view, so the record's model doesn't contain the field's value initially. (i. e. after fetching the collection)
2. Open any record from list view. This triggers a fetch to the model, which completes faster than preparing the view and therefore before the dynamic handler is initialized.
3. Go back to the list view.
4. Open different record. This triggers a fetch to the model. This time though, the view is already cached. Therefore dynamic handler initializes before the fetch is completed.
5. The bug happens: `change` event propagates to the dynamic handler, which can lead to unexpected behaviour.

**Possible fix**
Add some option (`sync: true`?) to the fetch in record controller: 

https://github.com/espocrm/espocrm/blob/1ce38253382eeb483a9da77cae1c11b3f2121d81/client/src/controllers/record.js#L190

This makes it possible to identify the event and later ignore it in the dynamic handler. Setting `silent: true` may be a solution, but I haven't tested whether this will lead to unwanted side effects.

**EspoCRM version**
7.3.x

**Comment by yurikuzn** [comment]
*onChange* as well as *change* events are supposed to be called in this situation. You can check whether *xhr* object is present in options to ignore the event, or whether *ui* is present to know it was initiated by a user interaction.
