### ISSUE TITLE
Wrong "from name" in group mail accounts

### ISSUE THREAD

**Issue by k1mp** [espocrm/espocrm#2580]
**Describe the bug**
If I send a mail from a Group Email Account the "from name" is not set correctly.
The "from name" is taken out of the outbound mail account for every group Email Account. 

**To Reproduce**
1. Write a new Email and choose any Group Mail Account 
2. Send the Mail 
3. The "from name" the recipient sees, is not the same as set in the settings of the Group Mail Account

**Expected behavior**
The Recipient sees the correct Name as set in the setting of the individual Group Mail Account

**EspoCRM version**
Version 7.3.2

**Comment by yurikuzn** [comment]
It seems it always used the system from name. Here is the fix: https://github.com/espocrm/espocrm/tree/fix
