### ISSUE TITLE
Email address invalid set null when lead converting

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2583]
Error 500 is thrown when trying to add email address in lead convert view.

` ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'invalid' cannot be null; POST /Lead/action/convert; line: 70, file: /var/www/htdocs/application/Espo/ORM/SqlExecutor.php [] []`

**Comment by yurikuzn** [comment]
We have a form for bug reports. It's too little information provided.

**Comment by rutkas** [comment]
Sorry, here are the steps to reproduce it:

1. Create a new lead without email address.
2. Click Convert, check "account".
3. Type in email address into email field.
4. Click Convert.
And we receive Error 500.

Checked it also on demo espocrm, bug is present there too.

Hope this will help to reproduce it.

**Comment by yurikuzn** [comment]
Could not reproduce on local environment yet. Any help with the fix will be appreciated.

**Comment by rutkas** [comment]
I have created a lead for test:

https://demo.eu.espocrm.com/?l=ru_RU#Lead/view/63d80bd888dbe3966

Please try to convert it with such options:

![image](https://user-images.githubusercontent.com/14265370/215566278-d67c0c68-06b0-49c0-8156-c0865c467d60.png)

**Comment by rutkas** [comment]
![image](https://user-images.githubusercontent.com/14265370/215567175-18dc6c2d-f31d-4458-807b-67fb36df6007.png)

**Comment by yurikuzn** [comment]
I can reproduce on the demo. But to be able to fix I tried to reproduce on the local env. I don't have access to demo to fix right there.

**Comment by rutkas** [comment]
I did not find exact place of the problem yet, looks like somewhere "invalid" bool value is lost. Probably in backend, cause I checked fetchEmailAddressData function in js and row.invalid is filled there:

```
row.invalid = $d.find('button[data-property-type="invalid"]').hasClass('active');
console.log(row)
```
this test outputs row.invalid = false

but SQL gets it as null

**Comment by yurikuzn** [comment]
I think I found, it's in the same view. It might be reproducible on latest MySQLs that I don't have at hand. I'll try to fix.

**Comment by rutkas** [comment]
Strange that it is hitting only when converting the lead. I can successfully add email in lead or in account objects directly.

**Comment by rutkas** [comment]
false is represented as null ?
I have tried to toggle it to true, emailAddressData.invalid = true in js data object, but error still persists:

convert func in convert.js:
```
            scopeList.forEach(scope => {^M
                data.records[scope] = this.getView(scope).model.attributes;^M
            });^M
            console.log(data);

```

logs:

```
[
    {
        "emailAddress": "foobar@gmail.com",
        "primary": true,
        "optOut": false,
        "invalid": true,
        "lower": "foobar@gmail.com"
    }
]
```

and error still persists.

So looks like data is posted from client correctly.

**Comment by yurikuzn** [comment]
Here's the possible fix. Could you apply changed files and clear cache? https://github.com/espocrm/espocrm/commit/fe3ab8b8a0e4db7421678fac294de44f5bf91310

**Comment by rutkas** [comment]
You are right. Just uploaded and tested the fix on my test host and it worked.

**Comment by rutkas** [comment]
thanks :)

**Comment by yurikuzn** [comment]
Thanks for help.
