### ISSUE TITLE
Avatars for Assigned Users field

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2584]
HI Yuri,

I think it would be nice to have avatars for the assignedUsers field as it is currently with the assigned user field.
Would it be possible?
https://github.com/espocrm/espocrm/blob/da45d958b7cabe6f0ace96b7b82fa18b02c37603/client/src/views/fields/assigned-users.js#L29

**Comment by yurikuzn** [comment]
Hi, I don't have time to take a look any soon. Have more important things to do and only a few hours of electricity a day.

**Comment by Kharg** [comment]
Take your time Yuri, I hope the situation gets better.
Stay safe.

**Comment by eymen-elkum** [comment]
Hope this helps https://github.com/espocrm/espocrm/pull/2593

**Comment by Kharg** [comment]
@eymen-elkum it works, thank you so much.
I hope Yuri can merge it for the next release.

**Comment by Kharg** [comment]
This commit by Yuri implemented the avatars
https://github.com/espocrm/espocrm/blob/4cd0961f8036e74737a7ca5d0b12e4c431df4829/client/src/views/fields/assigned-users.js
Thank you Yuri.
