### ISSUE TITLE
Group tab can't be added for portals

### ISSUE THREAD

**Issue by Virtute90** [espocrm/espocrm#2586]
**Describe the bug**
When trying to insert a tab group in a portal, the application returns this error:

Error 400: Bad request
Backend validation failure.

Field: tabList
Validation: arrayOfString

### I also reproduced the error in the demo environment.

**To Reproduce**
1. Go to portal's config
2. Edit one portal
3. Add a group tab

**Screenshots**
![image](https://user-images.githubusercontent.com/32056724/215701286-039c8b88-7493-44ee-b316-232ca02529a5.png)

**EspoCRM version**
7.3.2

**Additional context**
If I activate the debug logs and insert the returned string in the tab_list field on the database, the portal works correctly.
At this point the problem is only in the insertion of the configuration.

**My Log**

`[2023-01-31 07:53:02] DEBUG: API (400) validationFailure; PUT /Portal/639999ce7d29fe205; Input data: {"tabList":[{"type":"group","text":"Group Tab","iconClass":"fas fa-ad","color":"#a11e1e","id":"6445","itemList":[]}]}; Route pattern: /{controller}/{id}; Route params: Array (     [controller] => Portal     [action] => update     [id] => 639999ce7d29fe205 )  [] []`

**Comment by yurikuzn** [comment]
I disabled group tabs for portal for now. There some difficulties to make it to work for portal (not a validation error but others).
