### ISSUE TITLE
Email fetching is hanging on a 500 internal server error if it gets an UTF8 encoded email

### ISSUE THREAD

**Issue by makayjozsef** [espocrm/espocrm#2588]
Email fetching is hanging on a 500 internal server error if it gets an UTF8 encoded email into the INBOX.

Affected: Docker version

The bug maybe affects the /var/www/espocrm/data/espocrm/application/Espo/Core/Utils/Json.php file.

When I added the JSON_UNESCAPED_UNICODE parameter to the json_decode, the email fetching worked again. (I cant open the problematic email, but the newer emails fetched correctly)

**Comment by yurikuzn** [comment]
Emails encoding is usually UTF-8. Provided information is not enough to reproduce. Maybe you could provide the problem email original.

**Comment by makayjozsef** [comment]
Thank you for the fast respond. EML is not allowed file type so I archived it into a zip.

[Oscal S80 Tipped to Launch with 13000mAh Large Battery, Arcsoft Camera, and MediaTek Helio G85 & Doke OS 3.0..zip](https://github.com/espocrm/espocrm/files/10566624/Oscal.S80.Tipped.to.Launch.with.13000mAh.Large.Battery.Arcsoft.Camera.and.MediaTek.Helio.G85.Doke.OS.3.0.zip)

**Comment by yurikuzn** [comment]
> When I added the JSON_UNESCAPED_UNICODE parameter to the json_decode.

I could reproduce. But I can't manage to suppress the error. Could you elaborate more detail how you suppressed. On email importing step or on fetching.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/cc1bfce3ddc310495c17df2f6e3d38b4760ca76d
