### ISSUE TITLE
Custom configurations with level 'internal' overwrite if left empty

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2589]
**Describe the bug**
I followed the instructions on this page to create custom configuration panels and views. Everything works very well except the field that is set to 'internal'. When saving the settings, the value for the 'internal' field is overwritten if it is blank, which causes the config-internal.php to show a value of Null. This causes a problem because the form can never be saved again if the 'internal' value is to be maintained.

**Screenshots**
The field with an app secret:
![image](https://user-images.githubusercontent.com/1170415/216490553-466fe061-1ebf-4d65-b96e-85b7232ea619.png)
The config-internal file:
![image](https://user-images.githubusercontent.com/1170415/216490651-3de55bdb-9493-4aec-8b41-fe58a7b8e63d.png)
The configuration of the field:
![image](https://user-images.githubusercontent.com/1170415/216490719-9f876893-1fbd-43ec-8ba2-3ca689fd64c7.png)

**EspoCRM version**
7.3.2

**Additional context**
As long as the form has not been saved, the right value persists in the config-internal file. Saving the form when the 'internal' field is empty causes the field to be overwritten.

**Comment by yurikuzn** [comment]
What field type do you have on the form? If it's a varchar it's an expected behavior. The backend works as it should be, the frontend field view works as it should be, fetching the null on empty value. You need to use type *password* with internal fields.
