### ISSUE TITLE
Original Lead field for Account, Contact, Lead.

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#259]
To be able to see which lead was converted to the certain account/contact/lead and search by this lead.

**Comment by filippogasbarro** [comment]
The original lead field is not displayed in account and contact

**Comment by yurikuzn** [comment]
It's hidden by default !!!!!

**Comment by filippogasbarro** [comment]
I have found. Sorry, I'm pretty new with this CRM, I'm trying to learn how to use and how to customise it as better as possible in these weeks.
