### ISSUE TITLE
Missing options of "Industry" enum in "Lead" entity & validation errors

### ISSUE THREAD

**Issue by chrdavid** [espocrm/espocrm#2595]
**Describe the bug**
We've updated from 7.1.x to 7.3.2 last week using command line tool. After that update, we are not able to create Leads anymore. This includes the "Leads" section as well as "Lead Captures". 

**To Reproduce**
A) Configuration in Entity Manager:

"Accounts" are OK:
1. Go to "Administration > Entity Manager > Account > Fields > Industry"
2. Find the "Options" section and add some values.
3. "Default" combo box is filled with values from the "Options". (screenshot 1)

"Leads" are Broken:
1. Go to "Administration > Entity Manager > Lead > Fields > Industry"
2. The form is missing the "Options" section.
3. "Default" combo box is empty and no value can be selected (screenshot 2)

B) Try to create "Lead"
1. Go to "Leads" > "Create Lead"
2. Enter Name and hit "Save"
3. See validation error for "industry" field (screenshot 3)

C) Try to create "Lead Capture"
1. Go to "Admin" > "Lead Capture"
2. Create  Entry Point with default settings (First Name, Last Name, Email) (screenshot 4)
3. Test Lead Capture, e.g. with Postman (screenshot 5)

**Expected behavior**
A) Lead.industry should be optional
B) Industry options should be editable, "Default" value should be selectable from added "Options".

**Screenshots**
1. Existing "Options" in "Account > Industry" enum
![Screenshot 2023-02-06 at 10-47-15 Field Manager](https://user-images.githubusercontent.com/15276813/216941712-7106072c-6196-4a30-ae57-5f88bc52d78b.png)

2. Missing "Options" in "Lead > Industry" enum
![Screenshot 2023-02-06 at 10-46-47 Field Manager](https://user-images.githubusercontent.com/15276813/216941526-972cca90-b9d3-44ec-85fe-0b4146514d42.png)

3. Validation Error in "Create Lead" form
![Screenshot 2023-02-06 at 10-50-10 Create Lead](https://user-images.githubusercontent.com/15276813/216941838-947dbf68-9107-4819-8023-214f4f5aa061.png)

4. Create minimal Lead Capture
![Screenshot 2023-02-06 at 10-52-21 Create Lead Capture Entry Point](https://user-images.githubusercontent.com/15276813/216942001-38c6601d-e2cf-472c-9dcf-22a6f4784af9.png)

5. Validation Error in "Lead Capture" test call
![Bildschirmfoto vom 2023-02-06 10-53-43](https://user-images.githubusercontent.com/15276813/216941925-c25afc57-a60c-4110-9c3c-112588f64e2e.png)

**EspoCRM version**
7.3.2

**Comment by yurikuzn** [comment]
Lead entity been always used industry options from account entity. it' not a bug that it' not available for lead.

Try adding an empty option for account industry.

**Comment by chrdavid** [comment]
Hello @yurikuzn,

thanks for your fast reply.

- I've added a "None" option to "Account" > "Industry" (an _empty_ value was not saved, but replaced by "None" by the Label).
-  Then I've enabled the "Industry" field via Layout Manager so I can set a value when creating a "Lead".
- Then I was able to save the record.

Adding "Industry" to the "Lead Capture" parameter list and setting it to "None" also works.

So this workaround fixed it for us, thanks a lot!

---

However, it still feels a little bit odd:
1. in both cases - "Account" and "Lead" - we've set "Industry" to be optional, so it shouldn't have triggered a validation error at all
2. this didn't happen with 7.1.x (prior our update), so something changed with the validation (?)
3. if "Industry" options are to be set on "Account" - shouldn't the "Default" setting in "Lead" show these values (it does not; the "Default" combo box is always empty (see screenshot 2)?

---

Nevertheless - for us, your suggestion to add an "empty" option works. So you might close this, if not considered as a bug. Thanks again.

**Comment by chrdavid** [comment]
Hello @yurikuzn,

just confirmed: Removing "Industry" for Detail Page or leave it "empty" (not value selected) produce validation errors. Selecting a value from the dropdown saves the record. I've double checked, Account>Industry is not "Required" (checkbox off). See screenshots below.

Best,
![Screenshot 2023-02-06 at 15-10-42 Create Lead](https://user-images.githubusercontent.com/15276813/216994208-de1ff3df-f6d4-4dd7-9dfb-b54e1b777d87.png)
![Screenshot 2023-02-06 at 15-11-28 Create Lead](https://user-images.githubusercontent.com/15276813/216994216-148fa7b3-a337-48e4-ac28-c83e9a4c1875.png)
![Screenshot 2023-02-06 at 15-12-32 Field Manager](https://user-images.githubusercontent.com/15276813/216994223-47380b93-e57a-4927-a765-517e26ad2364.png)

**Comment by yurikuzn** [comment]
I tried to reproduce. Removed the industry field from the lead detail view. Create a new lead and it saved w/o the error.

**Comment by yurikuzn** [comment]
It's weird how it changed an empty value to None. There should not be such logic. I just checked and it added an empty value.
