### ISSUE TITLE
Image field: Preview size in list view has no effect

### ISSUE THREAD

**Issue by shalb2018** [espocrm/espocrm#2596]
**Describe the bug**

**To Reproduce**
1. If in the list view layout there are images, they do not change size even if changed in the field configuration.
2. It can be reproduced in the online demo (contacts e.g.)
3. ...
...

**Expected behavior**

In the field configuration there is the possibility to resize the images shown in the list view. In former releases this worked. In version 7.3.2 obviously no more.

**Screenshots**

**EspoCRM version**
Specify the EspoCRM version (or versions) on which the bug occurs.
I perceived it in version 7.3.2 but maybe it ocurred already before.

**Additional context**

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/89d775a8a81949c661c89a7bf5593ea7dcc8172c
