### ISSUE TITLE
List items remain selected after mass update actions

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2598]
**Describe the bug**
When performing mass action updates to a partially selected list of items, the selected items may be filtered by the view after the updates have been applied. That is not an issue. However, the items remain selected, which means further updates applied via mass update will also apply to hidden records. I have experienced this issue in regular list views as well as reports (I know advanced pack issues don't belong on Github, but it is related to the base CRM).

**To Reproduce**
Filter a list to show a certain set of items, e.g. "Description => Is Empty". Select a partial set of the items and mass update the descriptions to be '123'. After applying the updates, the filter will hide the newly changed rows that no loner have empty descriptions. Verify in another browser tab that the descriptions contain '123'.

Notice in the list the checkbox at the top of the column (for select all) is still checked, which shows that some items are still selected even though they are now hidden due to the filter. Apply another mass update to change the text in the selected rows' descriptions to 'ABC'. Now remove the filter so all rows are visible. The descriptions will say 'ABC' instead of '123'.

**Expected behavior**
After a mass update applies, I expect the changed rows to no longer be selected. Unfortunately, this behavior has caused a lot of problems in my system because hidden rows have been unknowingly changed.

**Screenshots**
Empty descriptions:
![image](https://user-images.githubusercontent.com/1170415/217346013-462332fd-7a2b-4d00-9988-40b7252d48bf.png)

Update one row using mass update:
![image](https://user-images.githubusercontent.com/1170415/217346249-ab87870e-1aee-494c-8bee-dfb3fc6b0abd.png)

The filter hid the row, but the checkbox shows that something is still checked:
![image](https://user-images.githubusercontent.com/1170415/217346291-dbd9a31d-cb6e-453a-94d2-3ab72d9bbd31.png)

Apply another update to the hidden row:
![image](https://user-images.githubusercontent.com/1170415/217346410-428a28ed-4dc4-428e-bb2f-0214c0fda161.png)

Remove the filter to see that the hidden row has been modified:
![image](https://user-images.githubusercontent.com/1170415/217346486-b5a47458-b827-40db-849a-5e3d5a7832d5.png)

**EspoCRM version**
Latest

**Additional context**
This also happens with reports. However, in the reports tab, the checkbox at the top of the column does *not* stay checked even if hidden rows are still selected. The mass action menu remains visible even if none of the visible rows have been selected, which is how you can see the bug. Running the report again by clicking the button causes all rows to be deselected.

**Comment by yurikuzn** [comment]
Good catch. This bug might have been for long. Hope this fix won't cause any side effects: https://github.com/espocrm/espocrm/commit/f09fe03f60ea5b6bf94a6e888263883318f14641

**Comment by bandtank** [comment]
I use the CRM for 7 to 8 hours per day and I have only experienced it a handful of times. Hopefully it won't impact anyone very much.

**Comment by bandtank** [comment]
I confirm this is fixed in 7.3.4. Thank you.
