### ISSUE TITLE
Help in Email Stream Function

### ISSUE THREAD

**Issue by lucasxteixeira** [espocrm/espocrm#260]
Hi,
First of all excellent work on espocrm.
Now I'd like to implement a new functionality into espocrm, however it's been a long time since I develop in php, so I'd like some directions in what to do.
The functionality is a stream of emails, the user can create a sequence of emails to be sent to a client and one email is sent every week.
Thanks for the attention.

**Comment by yurikuzn** [comment]
Hi, 
Please ask question on our forum at Developers Help section.
