### ISSUE TITLE
Missing translation for information panel

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2600]
https://github.com/espocrm/espocrm/blob/6f676c8a2f0b55f430e8497a6a758b263978ab43/client/src/views/email-template/record/panels/information.js#L39

it should be using the available translation.

>this.translate('Available placeholders', 'labels', 'EmailTemplate')

**Comment by yurikuzn** [comment]
Thank you for reporting. Fix here: https://github.com/espocrm/espocrm/commit/d88e47b5089a00378db56df89d418ea9c772a38a
