### ISSUE TITLE
PostgreSQL experimental support

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2605]
Experimental support, No guarantees.

In `data/config-internal.php` in the *database* section, add `'platform' => 'Postgresql'`.

**Comment by SuchAFuriousDeath** [comment]
If I may ask, are all issues (that we knew of) solved?

**Comment by yurikuzn** [comment]
Yes, I believe. But not tested enough.

**Comment by kczereczon** [comment]
Is there any chance for sqlite support? It would be game changer during integration tests.

**Comment by yurikuzn** [comment]
> Is there any chance for sqlite support? It would be game changer during integration tests.

I'm still not sure when we make Postgres officially supported.

I think implementing SQLite will be similar to PostgreSQL. BTW anybody can try it having the existing DIFF for the Postgres. I don't think that SQLite on production is a good choice for CRMs. Regarding integration tests, the value of those tests would be less of we run them on a different database system than production.

There might be ways to increase performance of integration tests. I haven't look into it yet.

**Comment by cometpos** [comment]
@yurikuzn do you suspect postgres will become supported officially?

**Comment by yurikuzn** [comment]
Maybe in 1 or 2 minor release cycles. It works much better already, I suggest trying it on production.

**Comment by cometpos** [comment]
I'm trying to get it to work with Supabase. Have you successfully installed it on a server with a remote database from supabase?
