### ISSUE TITLE
Relation from User to Call should be in Crm module(?)

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2606]
I'm a bit confused about this. The Call entity is defined in the Crm module, but the relation from user to call is defined in Espo 'core'. Is there a reason behind this? It's far from the only Crm-related thing in the file. Of course, this doesn't really matter for the application, but it gave me a pretty hard time trying to figure out how is it possible that the relation is manyMany and the middle table is created (It was related to another issue and I kept looking in the Crm module)

https://github.com/espocrm/espocrm/blob/d9c0f7d055ef9f3d7f5a3bda164aa024eeb7afe6/application/Espo/Resources/metadata/entityDefs/User.json#L471-L478

**Comment by yurikuzn** [comment]
When debugging metadata, do it with merged one data/cache/applicaton/ormMetadata.php. There's many stuff that is related to Crm but defined in base metadata. It's not fully decoupled. Maybe someday in future we will do it.

**Comment by SuchAFuriousDeath** [comment]
Understandable: Thank you for clarifying.
