### ISSUE TITLE
Exception constructor throws an error in Timeline query.

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2609]
**Describe the bug**
If the timeline query throws a PDO exception, it isn't logged in the log, because the Exception constructor throws an error and that is logged instead.

**To Reproduce**
1. Get the timeline query to throw a PDO Exception (unknown column for me, but it might happen whenever the getCode method doesn't return an int)

**Expected behavior**
Have the message from the PDO Exception directly in the log.

**Screenshots**
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/48620541/219321328-7dc39b31-f298-4805-905a-82c3129a131f.png">

**Possible fix**
Maybe throw the Exception directly?

**EspoCRM version**
7.3.3
**Additional context**
https://github.com/espocrm/espocrm/blob/02d277d0458e3d39435bb18e358b23e86480c01c/application/Espo/Modules/Crm/Tools/Calendar/Service.php#L574-L580

**Comment by yurikuzn** [comment]
Yes. Better to re-throw it directly.

**Comment by SuchAFuriousDeath** [comment]
@yurikuzn T think it's in two more places in the same file, lines 741 and 989.

**Comment by yurikuzn** [comment]
Actually, for strict typing, re-throwing exceptions is not that good, unless we sure what exception is caught. We could re-throw RuntimeException but fix it not to produce error.

**Comment by SuchAFuriousDeath** [comment]
Up to you.

**Comment by yurikuzn** [comment]
Weird, why getCode returned string when it's documented to return int. https://www.php.net/manual/en/exception.getcode.php. It breaks LSP.

**Comment by SuchAFuriousDeath** [comment]
If you Ctrl+ left click on the getCode method in PHPStorm: 
<img width="363" alt="image" src="https://user-images.githubusercontent.com/48620541/219334442-869ca96b-3fde-4e29-8053-2974d10fc75d.png">
