### ISSUE TITLE
Meeting Detail View: WARNING: infinite loop in redraw?

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2611]
**Describe the bug**
Getting this in the JS console on Chrome browser.

"WARNING: infinite loop in redraw?"

It does not appear to be causing functionality issues

**To Reproduce**
1. Open developer console
2. Navigate from Meeting list to Meeting detail 
3. See warnings logged in console

**Expected behaviour**
No warning should be printed

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/219519392-92df26a1-eda7-4858-87aa-b2686e44aac2.png)

**EspoCRM version**
7.3.2

**Additional context**
Does not always occur and I am not sure why this would come and go.

**Comment by yurikuzn** [comment]
I don't have this message.

**Comment by boydle** [comment]
I dont have a reliable way to reproduce. It occurs in Chrome and Firefox so its not a browser issue.

It does seem to be more common in a clean/newly opened browser but this may just be chance.

**Comment by bandtank** [comment]
I have seen this error, but only recently and not consistently. The message seems to only appear while looking at the calendar, at least for me.

**Comment by bandtank** [comment]
Maybe a library is responsible for the issue. Searching for the error produced several results about visjs. For example: https://github.com/visjs/vis-timeline/issues/17

**Comment by yurikuzn** [comment]
As we updated the lib, hope this error does not occur anymore. Please let know if it does.
