### ISSUE TITLE
Stream: Notes about record unlinking

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2612]
When a related record is unlinked, a note will be logged in the stream. For audited relations.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f97bb82d9e3f4691531551d134aea28b5cd482a9

**Comment by Kharg** [comment]
Something similar to show archived emails? :)

**Comment by yurikuzn** [comment]
Make account - email relationship audited.

**Comment by Kharg** [comment]
Yes, but like this you can't show the email body in the stream like Sent/Received emails.
