### ISSUE TITLE
Barcode field doesn't show when not on first tab

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2614]
**To Reproduce**
1. Have an entity with a barcode field
2. Use tab breaks in detail layout
3. Put the barcode field in a tab which isn't the first one.

**Expected behavior**
The barcode should be visible.

**Screenshots**
<img width="365" alt="image" src="https://user-images.githubusercontent.com/48620541/219872277-870c4417-fefb-411a-a350-59416dbcbf2b.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/48620541/219872542-d616178e-448e-4bfc-89d3-e9b02c664e74.png">

**EspoCRM version**
7.3.3

**Additional context**
Switching the field or the whole detail to edit mode and then back shows the barcode. When the barcode isn't visible, the svg element has max-width set to zero. From a quick glimpse at the code, it probably has something to do with the 'controlWidth' function in the barcode field view.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/bf1ed3c2871fc335103aee2590172206d73589aa

**Comment by SuchAFuriousDeath** [comment]
Perfect. Thank you
