### ISSUE TITLE
Add LEAST and GREATEST functions to ORM

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2616]
**Is your feature request related to a problem? Please describe.**
Not really, it would just be a nice way to simplify things, I don't think that needs any explaining. These functions should act the same way in all database platforms.

**Describe the solution you'd like**
Just add them here: 
https://github.com/espocrm/espocrm/blob/39939191e53dfc864d3da81fc76e3707373c5b20/application/Espo/ORM/QueryComposer/Functions.php#L34
I don't think it should break anything.

**Describe alternatives you've considered**
You could build a converter or get around it using conditions.

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/92e62c7760166432de45a236ece29fb3cbf3aadc
