### ISSUE TITLE
Log In as User Menu option displayed when disabled in config with authAnotherUserDisabled

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2617]
**Describe the bug**
When you disable the login as another user function using the config item: authAnotherUserDisabled the menu option in user detail "Log In" is still shown.

**To Reproduce**
1. set config item: authAnotherUserDisabled => true
2. login as an admin user
3. query for a non admin user and go to detail
4. view menu options > "Log In" is displayed

**Expected behavior**
Menu option Log In should be not be shown when this feature is disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/220259553-24ce6105-68d0-4cd7-af3b-13dfdc61aec7.png)

**EspoCRM version**
7.3.2

**Additional context**
I think this view just needs the if updated to check the config: 'views/user/record/detail'
From:
            if (this.getUser().isAdmin() && this.model.isRegular()) {
                this.addDropdownItem({
                    label: 'Log in',
                    name: 'login',
                    action: 'login',
                });
            }
To: 
            if (this.getUser().isAdmin() && this.model.isRegular() && !this.getConfig().get('authAnotherUserDisabled')) {
                this.addDropdownItem({
                    label: 'Log in',
                    name: 'login',
                    action: 'login',
                });
            }

**Comment by yurikuzn** [comment]
The proposed fix won't work as the parameter is *system*, not available for read.

**Comment by yurikuzn** [comment]
This will work for the future version: https://github.com/espocrm/espocrm/commit/7bb204a43202ef0b73a51f8cda8d35115d4d31e0
