### ISSUE TITLE
Scheduler busy times difficult to see when using dark themes

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2618]
When a dark theme is selected, the busy times in the scheduler are difficult to see:

![image](https://user-images.githubusercontent.com/1170415/221066527-be8933d9-05e3-48e0-a319-67dda1d9fd99.png)

The light themes have purple blocks, which are much easier to see:

![image](https://user-images.githubusercontent.com/1170415/221066579-fae4340f-c7c7-4e47-bb26-008b61e9d39f.png)

It would be great if a different color is used with dark themes.

**Comment by yurikuzn** [comment]
Fixed: https://github.com/espocrm/espocrm/commit/82cf211822e19deb70bdecc78067dae65bf9b68b
