### ISSUE TITLE
Issue with Invalid - Optout Email address

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2619]
**Describe the bug**
When we set an email in the system as invalid, it is reflected on the detail view meaning the email is no longer clickable which is perfect, however if you go to the list the email is not style as invalid and also still allow to click on it to send email. Same behavior with Optout email, on the detail view they are styled to not be clickable but on the list view they are still clickable. this cause a issue hence the email is invalid or optout, this should be reflected on all views including list view. 

**To Reproduce**
Steps to reproduce the behavior: (Invalid email)
1. create a contact with an email address and set email as invalid
2. on detail view email is styled to not be clickable but on the list view you can still click on the email to send an email although it is set as invalid

Steps to reproduce the behavior: (Optout email)
1. update previously created contact's email address and set it as optout
2. on detail view email is styled to not be clickable but on the list view styled as line-through but still clickable to send an email although it is set as optout
...

**Expected behavior**
When an email is set as invalid and/or optout it is expected to be styled as line-through but also it should not be clickable which means the user should not be able to send email to any invalid and/or optout email addresses in the system. 
 
**Screenshots**

**EspoCRM version**
version 7.3.3
<img width="484" alt="Screenshot 2023-02-24 at 10 48 00" src="https://user-images.githubusercontent.com/19490674/221164036-ac70437c-b745-4e27-aab1-0c441269f302.png">
<img width="1070" alt="Screenshot 2023-02-24 at 10 49 23" src="https://user-images.githubusercontent.com/19490674/221164043-587677e5-be28-4762-98ef-bb1299d69ebc.png">
<img width="1070" alt="Screenshot 2023-02-24 at 11 03 29" src="https://user-images.githubusercontent.com/19490674/221164049-e3783cde-ee93-4b91-bb77-f06f27c7bfd0.png">

**Additional context**

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/be54198265da27c9ebcc536454b5b0a8ac5b3af4

**Comment by rabiibrahimi** [comment]
Thanks 🙏
