### ISSUE TITLE
extend link field to optionally select foreign field

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#262]
By now a link fields (link, linkMultiple, linkParent) show hard coded the "name" field of the referenced entity. Sometimes the name field may not be very helpful and should be replaced by a different field (e.g. the case number instead of the case name).

Example config using an optional field attribute to show e.g. field "number" instead of "name":

``` json
"fields" : {
    "caseTest" : {
        "type" : "link",
        "field" : "number"
    }
},
"links" : {
    "caseTest" : {
        "type" : "belongsTo",
        "foreign" : "tasksTest",
        "entity" : "Case"
    }
}
```

http://forum.espocrm.com/forum/developer-help/24169-alternative-foreign-field-for-link-field

**Comment by yurikuzn** [comment]
For belongsTo relations will be added in 4.6.0.

Paremeters `foreignName` to specify custom field and `noForeignName` to skip name.

**Comment by RabeeBrahimi** [comment]
noForeignName is this still available as parameter. Couldn't find anything on the schema.
