### ISSUE TITLE
Lead Capture accepts fields outside of the Payload

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2620]
**Describe the bug**
Lead Capture accepts fields outside of the Payload

**To Reproduce**
1. Create a new Lead Capture
2. ..Select first name and last name as payload fields
3.  send a post request to the lead capture url with the choosen parameters and parameters not in the payload such as Email or Status
4.  A new lead will be created with all the sent parameters if the fields exist.

**Expected behavior**
Fields not selected in the payload shouldn't be updated.

**EspoCRM version**
7.3.3

**Comment by yurikuzn** [comment]
Not confirmed the bug.

**Comment by Kharg** [comment]
I will try to narrow down the cause and update this issue if I find anything.

**Comment by yurikuzn** [comment]
Maybe you send directly to the *Lead* endpoint instead of *LeadCapture*.

**Comment by Kharg** [comment]
Nope, could reproduce posting descriptiong field even if not in the payload

![image](https://user-images.githubusercontent.com/32223252/221213347-3c80106b-99d7-4cb1-993c-f6a185518cf6.png)
![image](https://user-images.githubusercontent.com/32223252/221213456-3965b661-36a6-43f2-a0bd-39b536eac7dc.png)
![image](https://user-images.githubusercontent.com/32223252/221213559-e6477127-2ea5-4e08-9aa2-cfc9d9c166aa.png)

**Comment by Kharg** [comment]
Used Payload:

> {
    "firstName": "FIRST_NAME",
    "lastName": "LAST_NAME",
    "status": "1",
    "description": "test"
}

**Comment by yurikuzn** [comment]
From screenshots it's not obvious whether there's the issue. Status is OK, description is different (might be formula sets the field, not value from payload). If you look into the CaptureService you can see that only fields from the *fieldList* are being read and set.

**Comment by Kharg** [comment]
Maybe it was a Espo Cache problem...

**Comment by yurikuzn** [comment]
Cache is not utilized here.
