### ISSUE TITLE
Text in knowledge base articles in dark mode has inconsistent background colors

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2621]
When creating knowledge base articles, I've noticed `<span>` elements in the HTML, which causes inconsistent styling.

Here is an example of a difference in the background color between light and dark modes:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/1170415/221358798-eb777b4b-6a55-4f15-9acb-66d733667ad2.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/1170415/221358825-48e32ef6-c441-4e24-a7e6-acd3cbe1f724.png">

The sentence that starts with "Many options..." has the expected coloration, i.e. none.

The HTML that was generated automatically:
```
<h4 class="Apple-interchange-newline"><span style="font-size: 26px;">Complete</span></h4>
<h4><span style="background-color: var(--input-bg); color: var(--input-color); font-size: 14px;">When a note reaches this...</span></h4>
<hr>
<h4><span style="background-color: var(--input-bg); color: inherit; font-size: 30px;">Searching and Filtering</span></h4>
<p>Many options are available...</p>
```
The HTML I was expecting:
```
<h4>Complete</h4>
<p>When a note reaches this...</p>
<hr>
<h4>Searching and Filtering</h4>
<p>Many options are available...</p>
```

Here is an example of a difference in the text color between light and dark modes:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/1170415/221358880-7d259bee-995a-48ae-aca6-59b7f6ce38f2.png">
<img width="213" alt="image" src="https://user-images.githubusercontent.com/1170415/221358989-9665ee7d-2f09-43a3-b401-6f78f6cafe10.png">

The HTML that was generated automatically:
```
<p>The resulting list of...</p>
<hr>
<h4 style="color: rgb(219, 219, 219);"><span style="background-color: var(--input-bg); color: inherit; font-size: 30px;">Other Tools</span></h4>
<h2 style="color: rgb(219, 219, 219);">Dashlets</h2>
<p style="color: rgb(219, 219, 219);"><span style="background-color: var(--input-bg); color: var(--input-color); font-size: 14px;">A quick way to see...</span></p>
```
The HTML I was expecting:
```
<p>The resulting list of...</p>
<hr>
<h4>Other Tools</h4>
<h2>Dashlets</h2>
<p>A quick way to see...</p>
```

I'm not sure why it happens some times and not others. Maybe it isn't a bug and I'm using the tools incorrectly.

**Comment by yurikuzn** [comment]
It's how contenteditable works when a formatted text is pasted. It's a browser functionality, we don't have control over it. You can 'paste as plain text' (ctrl+shift+v).

**Comment by bandtank** [comment]
Your suggestion works. There are still some quirks, but it's not an issue.
