### ISSUE TITLE
500 error when Edit Case

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2622]
Describe the bug
Edit Case View, me clear Contact
500 error when save

EspoCRM version
git master

Additional context
PHP crash log:
[2023-02-28 06:46:20] 
ERROR: Slim Application Error Type: TypeError Code: 0 Message: Espo\ORM\Repository\RDBRelation::unrelate(): Argument #1 ($entity) must be of type Espo\ORM\Entity, string given, called in 
application\Espo\Modules\Crm\Hooks\CaseObj\Contacts.php on line 88 File: 
application\Espo\ORM\Repository\RDBRelation.php Line: 528 Trace: #0 application\Espo\Modules\Crm\Hooks\CaseObj\Contacts.php(88):

**Comment by yurikuzn** [comment]
Fixed. Thanks.
