### ISSUE TITLE
Foreign field of type int does not apply disableFormatting setting of origin field

### ISSUE THREAD

**Issue by tiwj** [espocrm/espocrm#2626]
**Describe the bug**
A foreign field to type integer does not apply the displayFormatting=false setting of the origin field.

Entity A has an INT field with disableFormatting set to true.
Detail of entity A shows the field without formatting as excpeted.

Entity B references entity A with foreign field. 
Detail of entity B displays foreign int field with thousands seperator.
The entityDef of foreign field contains the view view/fields/foreign-int, which inherits view/fields/int and handles the formatting.

**To Reproduce**
1. Create entity A with int field X
2. Set new X field to disable formatting
3. Align X field in detail layout of entity A
4. Create new entry of entity A
5. Enter large number in X field e.g. 1.000.000
6. See formattig is not applied and number is displayed as "1000000" as expected
7. Create entity B and relate it to entity A (n:1)
8. Add foreign field to entity B to entity A.X field
9. Align relation to enttiy A and foreign field in detail layout of entity B
10. Create new entity B and relate it to the entity A entry.
11. See formatting is applied and number is displayed as "1.000.000" as NOT expected

**Expected behavior**
A foreign field reference to an integer field should apply formatting settings of the origin field, since the formatting can not be set in the referencing entities' field definition.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39725141/222198324-b86e314c-c9b9-4ba1-b15a-8098bb899fc4.png)

![grafik](https://user-images.githubusercontent.com/39725141/222198427-8191dd8e-c6a2-43bd-a277-ec125afc0cd2.png)

![grafik](https://user-images.githubusercontent.com/39725141/222198714-3816a5ad-44a6-4cdf-ab67-510f743579a7.png)

![grafik](https://user-images.githubusercontent.com/39725141/222198564-7e718bf2-218a-4ac8-8050-52e21541d49f.png)

**EspoCRM version**
7.2.7

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/3229ba10431ba0efae47356e3133f0def1be28a4
