### ISSUE TITLE
Wrong default mail address when sending mail over case

### ISSUE THREAD

**Issue by RobinTheHood** [espocrm/espocrm#2627]
**Describe the bug**
If you send an email via a `case`, the email address of the user is not automatically selected as the sender. This worked in previous versions. Currently, the first / top in the dropdown is always preselected. That doesn't seem right.

**To Reproduce**
1. Go to a case detail
2. Klick on the right navi on the mail icon
3. Control the sender email address

**Expected behavior**
I expect my user email address to be used as the sender.

**Screenshots**
Step 1:
![step1](https://user-images.githubusercontent.com/6323551/222411536-8d75de62-7b3e-4207-9a93-e45e031b02ac.png)

Step 2: Its German, but you can see the sender address is design@. But my user sending address is user-foo@
![step2](https://user-images.githubusercontent.com/6323551/222411930-a062eab4-9785-4d94-a1e1-0d1fcd6067ee.png)

**EspoCRM version**
I noticed the behavior in:
- 7.3.2
- 7.3.3

**Comment by rabiibrahimi** [comment]
i have just tested this on version 7.3.3 and it seems to work fine. just check that you have an email address under your user profile. If the system doesn't find an email address for current user it will default to outbound email address.

**Comment by RobinTheHood** [comment]
Thank you for your quick response. Here is a screenshot of my use profile settings. The email address is set. (I only chose fake data for the screenshot because I don't want to publish my real address)

![settings](https://user-images.githubusercontent.com/6323551/222416638-f477041d-4839-4255-97a5-d586d0ff9b79.png)

**Comment by RobinTheHood** [comment]
So that there is no misunderstanding, it does not work as expected even if an e-mail address is specified in the user profile.

**Comment by RobinTheHood** [comment]
I tried to reproduce it in your demo, but everything works there as expected.

So ... since I'm a developer myself, you can give me a hint where in the code the automatic selection takes place, then I'll research myself what could be the reason. Thx

**Comment by Kharg** [comment]
@RobinTheHood should be #2522

**Comment by yurikuzn** [comment]
The list of email addresses for a user: https://github.com/espocrm/espocrm/blob/7.3.3/application/Espo/Tools/App/AppService.php#L299

The first address from the list is picked except when replying it may be different: https://github.com/espocrm/espocrm/blob/7.3.3/client/src/email-helper.js#L264

Check whether your email address has a corresponding email account with configured SMTP.

**Comment by RobinTheHood** [comment]
Thx
