### ISSUE TITLE
Group email account: Auto-reply from-name and from-address are not applied

### ISSUE THREAD

**Issue by RobinTheHood** [espocrm/espocrm#2628]
**Describe the bug**
If an e-mail to a group e-mail is fetched from espo via IMAP and a `case` is to be created automatically and an `automatic reply` is to be sent to the sender, the sender (name and address) of the group e-mail address is not used. Espo now unexpectedly uses the settings from `/#Admin/outboundEmails`. In earlier versions, espo uses the sender (name and address) from the group email setting.

After updating from version 7.3.2 to 7.3.3 the sender name of the auto reply mail now is the group e-mail name, as expected, but the sender (reply address) is still from `/#Admin/outboundEmails` and not from the `/#InboundEmail/view/ settings` under group e-mail accounts.

**To Reproduce**
1. Send an e-mail to a group e-mail account (for example from gmail or apple mail, or any other)
2. Wait for an auto reply from espo (in your gmail account or in apple mail)
3. Control the sender and reply name and sender mail address in this e-mail

**Expected behavior**
In previous versions, the sender and name from the groups e-mail settings were used.

**Screenshots**
Espo no longer uses these group e-mail settings when sending an email automatically as a reply. I have marked the expected settings in red. (I have made some data unrecognizable and overwritten in the screenshot for data protection reasons.)

![Group-Email-Settings](https://user-images.githubusercontent.com/6323551/222424192-ba42ac1f-6e03-4cad-96ff-75194b101fa3.png)

**EspoCRM version**
- 7.3.2 name and address is not used from group e-mail settings
- 7.3.3 name is used now, but address is still not used

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/f0b49cd467fb474a60076dcce06d840351da50b8

**Comment by RobinTheHood** [comment]
Wow, that was fast 🤯 😊 Thx!
