### ISSUE TITLE
Conditional Operations - Selecting values results in wrong value picked in UI

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2630]
**Describe the bug**
Create an enum that uses conditional logic. When using this in the UI wrong values are picked in to the field.

**To Reproduce**
1. Create a new enum field with value One, Two, Three, Four
2. set conditional changes ex. 
One > Two 
Two > One or Four
Four > Three or One
4. Add to UI
5. Edit the field changing through the values, the wrong value is selected back to the UI

**Expected behavior**
UI should update to show the selected value

**Screenshots**
<img width="453" alt="setup" src="https://user-images.githubusercontent.com/7907518/222669951-1c69f1f2-5dae-414d-b855-a864eb63ad93.png">
<img width="791" alt="change" src="https://user-images.githubusercontent.com/7907518/222670067-8f42bc44-1f75-4c39-ba07-7033f79ce785.png">
<img width="541" alt="result" src="https://user-images.githubusercontent.com/7907518/222670122-f722534e-58f0-4633-96a0-847db12e7a41.png">

**EspoCRM version**
7.3.3

**Comment by yurikuzn** [comment]
It's not a bug. Such functionality is not supported. It was discussed recently on the forum. You need to include current options in option sets.
