### ISSUE TITLE
Adding custom fields to FE entity-manager

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2634]
**Is your feature request related to a problem? Please describe.**
We want to add our own field here to the entity-manager: 
<img width="738" alt="image" src="https://user-images.githubusercontent.com/48620541/222925861-4e22f068-461a-4514-9d64-37d17fb87100.png">

**Describe the solution you'd like**
Maybe put the fields in metadata and include some kind of a path property which says where the field should be saved and from where it should be loaded in.

**Describe alternatives you've considered**
Extending the view and saving the added fields in a new request, but this creates dependencies between modules. You could also get very hacky and redefine the view or something like that

**Additional context**
This isn't urgent or important or anything, I just wanted to ask if you think this is reasonable request. If you give me a hint on how you would implement it, I could try doing it myself and creating a pull request.
https://github.com/espocrm/espocrm/blob/48c3ea5f1303871aa5b93171bfc06f849490ee37/client/src/views/admin/entity-manager/edit.js#L61-L108
https://github.com/espocrm/espocrm/blob/48c3ea5f1303871aa5b93171bfc06f849490ee37/client/src/views/admin/entity-manager/edit.js#L297-L383
https://github.com/espocrm/espocrm/blob/48c3ea5f1303871aa5b93171bfc06f849490ee37/client/src/views/admin/entity-manager/edit.js#L189-L280

**Comment by yurikuzn** [comment]
It was planned, but it's long way to implementation. Please no need pull request on this. This requires massive refactoring.

**Comment by SuchAFuriousDeath** [comment]
Ok then. Thank you for the quick answer
