### ISSUE TITLE
Custom hooks won't work as of PHP 8.0.0

### ISSUE THREAD

**Issue by GZPERRA** [espocrm/espocrm#2639]
**Describe the bug**
Adding a custom hook causes Internal Server Error. 

**Cause**
As of PHP 8.0.0, [`get_class_methods`](https://www.php.net/manual/en/function.get-class-methods.php) only accepts objects or valid class names. Thus, [`HookManager::readHookData`](https://github.com/espocrm/espocrm/blob/48c3ea5f1303871aa5b93171bfc06f849490ee37/application/Espo/Core/HookManager.php#L193) fails when calling `$classMethods = get_class_methods($className)` with error `ERROR: Slim Application Error Type: TypeError Code: 0 Message: get_class_methods(): Argument #1 ($object_or_class) must be an object or a valid class name, string given File`, since `$className` is a relative file path and not a class name.

**To Reproduce**
Steps to reproduce the behavior (from [docs](https://docs.espocrm.com/development/hooks/)):
1. create a file `custom/Espo/Custom/Hooks/{EntityName}/{HookName}.php`;
2. declare a hook action method with a name the same as a hook name (e.g. beforeSave)
3. clear Cache in Administration.
4. trigger the hook

**Expected behavior**
Execution of the custom hook script.

**EspoCRM version**
7.3.3

**Comment by yurikuzn** [comment]
Hi,

Today is Sunday, we don't work. I'd appreciate when bug reports are posted on weekdays rather than weekends. Tomorrow is Monday, a pile of work is waiting, weekends issues are likely to be ignored.

PHP 8.0 is supported for a 2.5 years, we have many hooks and they all work.

**Comment by SuchAFuriousDeath** [comment]
I got this error many times, but it was always because I forgot to create a directory named after the entity type.

**Comment by yurikuzn** [comment]
When using IDE capabilities to create classes, such errors don't happen. In PHPStorm: Alt + Home > Insert > type *Class*.

**Comment by SuchAFuriousDeath** [comment]
I use that when I have the project locally, what I was talking about only happens when creating files on a server.

**Comment by GZPERRA** [comment]
@yurikuzn, sorry I didn't know that, maybe you could add it to the contributing guidelines.
@SuchAFuriousDeath that's what I thought too, but the namespace is correct (`namespace Espo\Custom\Hooks\Purchase;`) and my hook file is inside a folder named after the entity type (`Espo/Custom/Hooks/Purchase/MyHook.php`), exactly like the docs example.

I'm not a PHP expert, but what made me create the issue is that when I tested `get_class_methods` in a simple PHP script with a file path, it didn't work.

**Comment by SuchAFuriousDeath** [comment]
And did you var_dump what the get_class_methods was being passed in the HookManager?

**Comment by GZPERRA** [comment]
Yes I did, it was being passed: `"Espo\\Custom\\Hooks\\Purchase\\MyHook"`.

**Comment by SuchAFuriousDeath** [comment]
But that is a valid class name, isn't it?

**Comment by GZPERRA** [comment]
Yes it's. Sorry, I was wrong and I thought that it was a file path (I didn't know about namespaces). So now I think the issue is due to the fact that the hook file is not included, right?

**Comment by SuchAFuriousDeath** [comment]
Depends on what you mean by 'included'. The file should by included by php, because all the Espo files are included automatically.

**Comment by GZPERRA** [comment]
Silly mistake :/. The hook file name didn't match the class name. I'm sorry for wasting your time, thank you @SuchAFuriousDeath.

**Comment by SuchAFuriousDeath** [comment]
No big deal. It happens
