### ISSUE TITLE
Sort on regular user email causes 500 error when viewing API users

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2640]
**Describe the bug**
After sorting users by email, navigating and viewing API users throws 500 error

**To Reproduce**
1. Navigate to users
2. sort users by email
3. navigate to api users
4. error shown

**Expected behavior**
API users should display without error

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/223009479-55dd3fac-f296-474f-a450-3638b7f1deb2.png)
![image](https://user-images.githubusercontent.com/7907518/223009514-d598f493-ee34-4b8a-b4db-6f684e9aac94.png)

**EspoCRM version**
7.3.3

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/7aabbc5d28e3e21c56384641018082def820d245
