### ISSUE TITLE
Double consecutive `createView` calls may cause side effects

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2644]
**Describe the bug**
Double consecutive `createView` calls may cause side effects (dangling promises) because of the way Bullbone works. Most often such an error is related to double consecutive re-render (closely related to https://github.com/espocrm/espocrm/issues/2635) or `prepare` call.

**Explanation**
Suppose (i) a view _A_ that creates nested view _B_ inside its `prepare` function. For example A = `time-ranges` and B = `item-detail` of working calendar field, which already exist in EspoCRM. Suppose (ii) that view B takes some time to load. We can simulate this by adding 
```js
this.wait(new Promise(resolve => setTimeout(resolve, 500)));
```
to its setup function. (I couldn't find a view in Espo that meets both conditions (i) and (ii), but developers can create such views. For sake of this example I appended the `wait` line to the `item-detail` manually).

Now:
1. Begin inline editation of view _A_
2. Make changes
3. **Close** inline editation

https://github.com/espocrm/espocrm/blob/6afd616e42deb6ec9f9590803fd1825fc28c01a5/client/src/views/fields/base.js#L1280-L1286

4. This causes a call to `setDetailMode` function, which calls `prepare`. This creates a promise _X_ on which depends the correct termination of inline editation.
5. Initial attributes are stored back to model, which causes change event. Causing another call to `prepare`.
6. Another call to `prepare` marks promise _X_ as cancelled. However, as view _B_ takes some time to load, promise _X_ haven't resolved yet.
7. This creates dangling promise _X_, thus inline editation never terminates correctly and editation links never disappear.

I think that this is fundamental issue with Bullbone, as developes have no feedback when createView terminates. I can think of adding a new option to `createView`, that tells `createView` to reject, when promise is marked as cancelled.

```diff
delete this._viewPromiseHash[key];

if (promise && promise._isToCancel) {
+    if (options.rejectOnCancel) {
+       reject();
+    }
    return;
}
```

**Comment by yurikuzn** [comment]
The issue with closing inline-edit should be addressed anyway.

I believe changing the method to the following might work:

```js
            let promise = this.setDetailMode()
                .then(() => {
                    if (!noReset) {
                        this.model.set(this.initialAttributes, {skipRerender: true});
                    }

                    return Promise.resolve();
                })
                .then(() => this.reRender(true))
                .then(() => this.removeInlineEditLinks());
```

**Comment by yurikuzn** [comment]
It simpler:

```js
            if (!noReset) {
                this.model.set(this.initialAttributes, {skipRerender: true});
            }

            let promise = this.setDetailMode()
                .then(() => this.reRender(true))
                .then(() => this.removeInlineEditLinks());
```

Needs some testing.

**Comment by mozkomor05** [comment]
> It simpler:
> 
> ```js
>             if (!noReset) {
>                 this.model.set(this.initialAttributes, {skipRerender: true});
>             }
> 
>             let promise = this.setDetailMode()
>                 .then(() => this.reRender(true))
>                 .then(() => this.removeInlineEditLinks());
> ```
> 
> Needs some testing.

Yep, that's what I thought about too. This ensures, that if views creation ever gets cancelled, it's the one that comes from `change` event (which should be safe to cancel).

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/0afd5e1d734e8847a4e2f50f959635a56dd928ba

There might be other similar cases in the codebase.

**Comment by mozkomor05** [comment]
Thanks.

What do you think about adding the option to `createView` so that developers can choose to have the promise rejected instead of dangling.

**Comment by yurikuzn** [comment]
Not sure on this. I'd better first fix all possible cases in the codebase where a view is re-rendered in between createView.

**Comment by mozkomor05** [comment]
Double consecutive call to `createView` might also lead to double call to `_initialize`, which can lead to double initialization of listeners, that will never be unregistered which can cause unexpected beahviour (i.e. when listeners manipulates DOM) and errors in console. 

This happens because if `createView` is called a second time in the interval after the first view calls `_initialize`, but before it calls `_onReady` the first view is not set, but it could have already registered its listeners. 

I suggest moving `off` and `stopListening` to clearView, or to some common method (that both `clearView` and `remove` call). However, I realize how dangerous this is.

**Comment by mozkomor05** [comment]
```diff
if (promise && promise._isToCancel) {
+   view.remove();
    return;
}
```

This won't terminate the listeners as soon as possible, but it seems to be enough to prevent all side effects I observed. If you separate the termination of the listener into a separate method, instead of this.remove(), it should probably be called here.

**Comment by yurikuzn** [comment]
Setting a view immediately is too big change that would require a lot of testing.

Will this solve the problem?

```js
if (previusView) {
    //previusView.cancelRender();
    previusView.remove();
}
```

**Comment by mozkomor05** [comment]
I think it won't, as it assumes previous view is set. But it might not be and `_initialize` will be called regardless. 

Anyway, I'll test it when I get home.

**Comment by yurikuzn** [comment]
Indeed it won't work.

**Comment by yurikuzn** [comment]
Might need an additional check to prevent removal/unsubscribing twice.

```js
if (promise && promise._isToCancel) {
    if (!view.isRemoved()) { // It can be already removed from clearView.
        view.remove();
    }

    return;
}
```

**Comment by mozkomor05** [comment]
Hi, have you come to any conclusions? Will the above code be added to Bullbone? No pressure, of course :)

**Comment by yurikuzn** [comment]
I set it aside for now. We have v7.4 coming plus I needed some rest.

**Comment by yurikuzn** [comment]
Applied the fix https://github.com/yurikuzn/bull/commit/468171adca0afc2d0a913765dfea8c457e30e849.
