### ISSUE TITLE
Action Set Held Or Set Not Held on a List of Meetings / Calls records produces an error

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2646]
**Describe the bug**
When trying set up collection of meetings / calls for an account/contact etc as set held or as set not held, it produce an error not found. if you try to do it from the list view of a meeting entity / call entity it produce a different error (no ids). 

**To Reproduce**
1. create few meetings/calls for an account
2. from activities panel of the account / choose (view list - meetings OR view list - calls) 
3. on the list select all / some of the meetings / calls and select action set held Or set not held (will produce an error NOT FOUND)
4. Access Meeting Entity List Or Call Entity List view and select few record apply action Set Held OR Set Not Held and will produce another error (no Ids)
...

**Expected behavior**
Ability to set a collection of meeting or calls as held or set not held from the actions button. 

**Screenshots**

**EspoCRM version**
7.3.3
<img width="1464" alt="Screenshot 2023-03-07 at 14 37 32" src="https://user-images.githubusercontent.com/19490674/223456581-9799fb53-8f2a-4c73-aab4-27351a77035c.png">
<img width="1464" alt="Screenshot 2023-03-07 at 14 41 00" src="https://user-images.githubusercontent.com/19490674/223456592-754e10c9-c368-40a9-875d-e23d411a4641.png">

**Additional context**

**Comment by yurikuzn** [comment]
Thanks. Fix; https://github.com/espocrm/espocrm/commit/2578b397e7ff71dbb4867f20e6685a1ca71480a9

**Comment by rabiibrahimi** [comment]
Thanks 🙏
