### ISSUE TITLE
When creating a task from an email, "Name" is not filled in

### ISSUE THREAD

**Issue by IgorA100** [espocrm/espocrm#2654]
**Is your feature request related to a problem? Please describe.**
When creating a task from an email, "Name" is not filled in

**Describe the solution you'd like**
When creating a task from an email, it would be logical to fill in the "Name" field in the created task based on the subject of the email

**Comment by yurikuzn** [comment]
It will suppress the current auto-complete. Email names are usually long and don't suit to be good names.

**Comment by IgorA100** [comment]
> Email names usually don't suit to be good task names.

The subject line of an email often contains a lot of information that can be used in a task name. It would be much more convenient to correct some of the information already in the subject of the task. Now I have to copy the subject of the letter, paste the text into the task name and edit it further.
