### ISSUE TITLE
define loginView in theme json

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2657]
**Is your feature request related to a problem? Please describe.**
Most of the free themes available usually includes a custom loginView, this login view is applied as soon as the theme is installed even if the theme is not set as default as it's just defined in the App.json file.
This may not be an optimal solution as if I just want more themes for my users and keep a different default theme the login view will still be changed.

**Describe the solution you'd like**
A solution would be to be able to define the login view also inside the [theme json](https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/metadata/themes/Glass.json ) as an alternative, and apply it only if the theme is selected as a default theme in the admin settings.

**Comment by yurikuzn** [comment]
It would an issue every time we make changes in the file. It happens quite often. Users will report bugs to us, overwhelming our support.

**Comment by yurikuzn** [comment]
Currently the themes framework only suppose to change styles. Not any JS. Changing it is a step we won't be able to revert.
