### ISSUE TITLE
Add CSS id of current entity to body 

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#2658]
It would be really useful to have body tag with id of current enttity.

Example: 

I am in Contacts entity and:

`<body id="contact"`

is in HTML.

This should make CSS styling much easier.

**Comment by yurikuzn** [comment]
ID is not option 100%. If it could be added, only data-attribute. But it's against the design. It would mean that a specific view modifies outer DOM. Not all views have its scope. It would require some not elegant methods, I'd rather avoid.

**Comment by david-strejc** [comment]
> ID is not an option 100%. If it could be added, only data-attribute. But it's against the design. It would mean that a specific view modifies outer DOM. Not all views have its scope. It would require some not elegant methods, I'd rather avoid.

OK - and is there any "right place" to have unique ID or even Class in HTML for details and lists so we can style individual parts? 
Probably data-attribute is sufficient. 

I don't want to you make any antipatterns or design flaws.

**Comment by yurikuzn** [comment]
It does already have the scope data attribute, but only for record views
![image](https://user-images.githubusercontent.com/1006792/225233451-414def7d-9b48-4fa4-9bd6-1421b842782a.png)
