### ISSUE TITLE
linkMultiple with sortable params doesnt work correctly

### ISSUE THREAD

**Issue by ddanninger** [espocrm/espocrm#266]
I defined an entity with field:
```javascript
"textblocks": {
          "type": "linkMultiple",
          "sortable": true
 },
```
and links:
```javascript
"textblocks": {
            "type": "hasMany",
            "entity": "Textblock",
            "foreign": "blockDocuments",
            "layoutRelationshipsDisabled": true
},
```

everything gets displayed well and i can resort the relations on the UI but after saving the sorting order gets lost.

**Comment by yurikuzn** [comment]
linkMultiple fields are not supported for List layouts and can't be sorted.

**Comment by ddanninger** [comment]
iam talking about the detail view - the sorting works in the UI -
updateing the entity in the detailview also sends the linked entities in the correct order - but in Espo\Core\ORM\Repositories\RDB -> processSpecifiedRelationsSave

the sorting order gets mixed up again.

**Comment by yurikuzn** [comment]
Link Multiple fields doesn't support sorting.

**Comment by yurikuzn** [comment]
It's not easy to implement.
