### ISSUE TITLE
Repeat/recurring meeting option.

### ISSUE THREAD

**Issue by andihaxhillari** [espocrm/espocrm#2664]
Hi. Is it possible to add the option of repeating/recuring Meetings?

Example: Meeting every Monday of the month. Closing report every fourth Friday of the month. Meeting with staff every second Thursday of the month.. and so on.

It is often necessary for the events to be repeated every month and will need to be defined in advance.

Thank you.

**Comment by yurikuzn** [comment]
Hi,

It was already requested. Here a few on the forum: 

https://forum.espocrm.com/forum/general/27732-calendar-recurring-event
https://forum.espocrm.com/forum/developer-help/83044-automate-recurring-tasks
https://forum.espocrm.com/forum/feature-requests/66816-recurring-meetings-or-calls

It's likely to be implemented but not very soon.

**Comment by andihaxhillari** [comment]
Thank you.
