### ISSUE TITLE
Allow type-specific field params in foreign fields more easily.

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2666]
**Is your feature request related to a problem? Please describe.**
If you have a foreign field and want to set a type-specific parameter(for example 'useNumericFormat' for dates), it can't be done in entityDefs, you have to create a custom view and set the param yourself (Because the below code only keeps link, field and view, the rest is ignored).

**Describe the solution you'd like**
Keep the appropriate params in the field view. Maybe even allow editing them via the FE field manager. However, keep in mind that this is not an urgent bug or anything, just a friendly suggestion. In the least, some kind of a warning could be added to inform the user that setting params in entityDefs might have no effect.

**Describe alternatives you've considered**
Creating a custom view.

**Additional context**
I believe this code to be the culprit:
https://github.com/espocrm/espocrm/blob/9e25804f8914ef1fd973b1edea8b91fe513d06ec/client/src/views/fields/base.js#L675-L685

**Comment by yurikuzn** [comment]
I planned just to copy all parameters from the source field. Like I did just a few days ago but for all params.

**Comment by SuchAFuriousDeath** [comment]
Ah, nice.
