### ISSUE TITLE
Export to CSV breaks when exporting Currency Field and Currency Currency

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2669]
**Describe the bug**
If a user exports both a currency field (Opty Amount)  and the currency field (Opty Amount Currency) the Currency field is not exported but the header value is. Field data is moved left 1 column in the output file.

**To Reproduce**
1. Export opportunities to CSV
2. Select fields as shown in the CSV ensuring that some fields are after the Amount Currency field
3. Export

**Expected behavior**
Either amount currency should not be exported in the header or it should be exported in the data.

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/226223870-c53373cf-ad63-4df0-8633-b827d7343318.png)

**EspoCRM version**
7.3.4

**Comment by yurikuzn** [comment]
Seems to be fixed on the master with refactoring.
