### ISSUE TITLE
View option in Portal User List does not work

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2670]
**Describe the bug**
In the list of portal users use the row action to View one of the records. Nothing occurs in the UI and a error is logged to the JS Console.

**To Reproduce**
1. Create a portal user
2. On the portal user list use the row action to view the record

**Expected behavior**
Modal should open and show the user

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/226224992-ff140097-7b35-4d45-b56b-8c8fde8bb822.png)

**EspoCRM version**
7.3.4

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/8cf2e270a596c41ab9dc8235aee3d9f90243b938
