### ISSUE TITLE
Allow setting kanban maxSize for a specific entityType

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [espocrm/espocrm#2671]
**Is your feature request related to a problem? Please describe.**
I would like to set maxSize for a specific entity independently of the config 'recordsPerPageSmall' value.

**Describe the solution you'd like**
Pull the value somewhere from metadata, if it doesn't exist, fallback to the config value.

**Describe alternatives you've considered**
Creating a custom view and setting the value manually.

**Additional context** https://github.com/espocrm/espocrm/blob/b85f60b855e43e744eb00558da4d8a0877bcc4c3/client/src/views/list.js#L408-L412

**Comment by rabiibrahimi** [comment]
I have already submitted a request to add this new config parameter to specify the number of records to show on a kanban. it would be very useful and will help a lot i would appreciate if you consider to add such config parameter. https://github.com/espocrm/espocrm/issues/2526#issue-1478995360
