### ISSUE TITLE
Add OIDC support to REST API

### ISSUE THREAD

**Issue by phyx3r** [espocrm/espocrm#2674]
**Is your feature request related to a problem? Please describe.**
Add OIDC support to REST API.

**Describe the solution you'd like**
A stand-alone frontend client should be able to log on using OIDC and than call EspoCRM APIs with the JWT token retrieved from the OIDC flow.

**Comment by yurikuzn** [comment]
It's not clear what do you mean. Do you mean making Espo OIDC provider. It's unlikely to happen any soon, there are other open source solutions like Keycloak.

If you mean just connecting to Espo using OIDC, it's not actual, as Espo is SPA, UI uses REST API.

**Comment by yurikuzn** [comment]
Maybe it's possible to customize Espo authentication so 3rd party issued JWT used instead of auth token. Espo is pretty customizable there.

**Comment by yurikuzn** [comment]
It's possible use a custom auth token manager https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Authentication/AuthToken/Manager.php#L40.

Then with a a custom Login implementation for a custom API login method, to check validity of that auth token. Here it uses the default Espo method to check auth token  https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Authentication/Oidc/Login.php#L174.
