### ISSUE TITLE
Restore lost styles

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2675]
Hi,

"Primary" and "Info"  styles were removed from panels styling,
Would it be possible to bring them back?
https://github.com/espocrm/espocrm/blob/master/client/src/views/admin/layouts/detail.js#L78
https://github.com/espocrm/espocrm/blob/master/client/src/views/admin/layouts/side-panels-detail.js#L50
https://github.com/espocrm/espocrm/blob/master/client/src/views/admin/layouts/relationships.js#L49

**Comment by yurikuzn** [comment]
It was done deliberately. Those colors were off. Our demo was ugly. I don't want Espo be presented in such an ugly way. Maybe in future when colors are fixed for all themes.
