### ISSUE TITLE
Portal index.php not found

### ISSUE THREAD

**Issue by SinglWolf** [espocrm/espocrm#2677]
**Describe the bug**
OS Debian 10.13
Server version: Apache/2.4.38 (Debian)
Protocol: `HTTPS`
Configured the portal by default. When I try to go to the page portal, I get
`404 Page Not Found
Portal index.php not found.`
![2023-03-28_08-39-12](https://user-images.githubusercontent.com/32172969/228121918-e7d50032-7abd-4702-807c-59a3819f6702.png)

In the file `data/logs/espo-2023-03-28 .log` this message appears:
```
[2023-03-28 03:35:34] ERROR: (404) Portal index.php not found.; GET /portal/; line: 101, file: /var/www/alexander/data/www/my_site/application/Espo/Core/Portal/Application.php [] []
```
After the change in the file `public/portal/.htaccess`
before
```
# RewriteBase /
```
after
```
RewriteBase /
```
I get an almost empty page

![2023-03-28_08-39-58](https://user-images.githubusercontent.com/32172969/228122899-5b6020ff-01b8-42bc-93b0-d27885ac19f2.png)

**EspoCRM version**
Version 7.3.4

All recommendations from the [documentation](https://docs.espocrm.com/administration/apache-server-configuration/) have been implemented.
The installation of `EspoCRM` went without errors.
Please help me set up the portal.

**Comment by yurikuzn** [comment]
Please use our forum for such issues.

**Comment by SinglWolf** [comment]
> Please use our forum for such issues.

There is a similar topic on the forum that has not been resolved since 2022 until now. What's the point of that?
