### ISSUE TITLE
Read-only fields in side panel are editable when certain conditions are met

### ISSUE THREAD

**Issue by arkadywtf** [espocrm/espocrm#2679]
**Describe the bug**
Affected fields are 'Created At', 'Modified At' and 'Followers'. Screenshots below.

**To Reproduce**
1. Create role and enable access to `Leads` with Create = yes, Read = all, **Edit = team**, Delete = team, Stream = all;
2. Create team ie. Sales;
3. Create `Regular` user and assign it to the role from step 1 and team from step 2;
4. Login as `Admin` and create new `Lead` record ONLY filling the name and assigning it to a team from step 2;
5. Login as `Regular` user, go to Leads, on the list view refresh the tab (F5 / Ctrl +F5), then click on the newly created record and click `Edit`.

**Video**

https://user-images.githubusercontent.com/17282224/228352816-4e388690-8f6a-42bf-87df-5fe517ab6158.mp4

**Screenshots**
![image](https://user-images.githubusercontent.com/17282224/228348219-a862dc65-6f97-41d5-a755-252a494e898e.png)
![image](https://user-images.githubusercontent.com/17282224/228350555-9db082a0-57b6-4a43-be9c-1e53c3166ded.png)
![image](https://user-images.githubusercontent.com/17282224/228350705-33e2c3d3-ca42-493a-b0c2-f86f6d6c198b.png)

**EspoCRM version**
master

**Comment by yurikuzn** [comment]
This issues is actual for the release version too. The fix: https://github.com/espocrm/espocrm/commit/94321b3500c934608c122b584e61b32ada0201d7. Hope it won't break anything.
