### ISSUE TITLE
Sort on regular user email causes 500 error when viewing Portal users

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2680]
**Describe the bug**
After sorting users by email, navigating and viewing Portal users throws 500 error

**To Reproduce**
1. Navigate to users
2. sort users by email
3. navigate to portal users
4. error shown

**Expected behavior**
Portal users should display without error 

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/228459192-e479bb59-8d1d-4b3c-83a2-0062616be944.png)
![image](https://user-images.githubusercontent.com/7907518/228459298-fb4afc76-92bd-4b7a-a586-eb8cfa830f0a.png)

**EspoCRM version**
7.3.4

**Additional context**
This is the same behaviour as seen for API users in https://github.com/espocrm/espocrm/issues/2640

**Comment by yurikuzn** [comment]
Not actual as the fix is the same.
