### ISSUE TITLE
Could not handle 'order' for 'Note'. error

### ISSUE THREAD

**Issue by ronenb75** [espocrm/espocrm#2682]
Current version: 7.3.4
Plain vanilla, not modifications nor added modules.

I'm getting `Error 500 Could not handle 'order' for 'Note'.` error trying to search.

Console log:
```
jquery.js:10109          GET https://xxxxxxxx/api/v1/GlobalSearch?q=quote&maxSize=10&offset=0&orderBy=&order= 500 (Internal Server Error)
Server side error 500: Could not handle 'order' for 'Note'.
```

![image](https://user-images.githubusercontent.com/21135594/228686668-a4d8d882-fbe5-4ba3-8ad9-c19f66826bfe.png)

**Comment by yurikuzn** [comment]
Notes are already removed from the Global Search. Please, when reporting bugs, include bug-reports template with steps to reproduce.
