### ISSUE TITLE
JobManager is not working in some cases

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#2683]
We found this error in logs:
```

[2023-03-31 10:39:02] ERROR: JobManager: Failed job running, job '6426b823206db9d5b'. Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) 
must be of type array, bool given, called in /public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 86; a
t /public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:831. [] []
[2023-03-31 10:39:02] ERROR: JobManager: Failed job running, job '6426b83d0a3de2ba5'. Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) 
must be of type array, bool given, called in /public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 86; at /public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:831. [] []                          
```

It causes issue where emails are not sent in Workflows.

**Comment by yurikuzn** [comment]
It's not enough information so I could fix the issue (if there is an issue).

**Comment by yurikuzn** [comment]
If you find out what causes the error and it's an issue that needs to be solved in Espo, please let me know.

**Comment by david-strejc** [comment]
> If you find out what causes the error and it's an issue that needs to be solved in Espo, please let me know.

Where shoul we look at? This is the only error log we found.

**Comment by yurikuzn** [comment]
The error information does not correspond the file `vendor/nesbot/carbon/src/Carbon/Traits/Creator.php` from the latest release (nor from the master).

I recommend debugging.

**Comment by yurikuzn** [comment]
In the issue template with have requirement to provide Espo version. It seems that you use old version that uses older Carbon not compatible with PHP 8.1.

**Comment by david-strejc** [comment]
> In the issue template with have requirement to provide Espo version. It seems that you use old version that uses older Carbon not compatible with PHP 8.1.

Thanks - appologize for not providing enough information.
