### ISSUE TITLE
Failed Upgrade 7.3.4 to 7.4.0

### ISSUE THREAD

**Issue by DoM1niC** [espocrm/espocrm#2689]
**Describe the bug**
Upgrade failed with Error: 500

**To Reproduce**
`sudo -u www-data php upgrade.php EspoCRM-upgrade-7.3.4-to-7.4.0.zip`

**Expected behavior**
## Output
```
Current version is 7.3.4
Starting upgrade process...
Error: Error occurred while EspoCRM rebuild. Please see the log for more detail.
```
```
[2023-04-06 10:00:50] ERROR: Failed to rebuild database schema. Details: There is no column with name "entity_type" on table "array_value". at /home/www/projects/3DNS/crm/vendor/doctrine/dbal/src/Schema/Exception/ColumnDoesNotExist.php:16 [] []
[2023-04-06 10:00:50] ERROR: Database rebuild failure, details: Error while rebuilding database. See log file for details.. [] []
```

**EspoCRM version**
7.3.4

**Comment by yurikuzn** [comment]
Check whether you have entity_type column in array_value table.

**Comment by DoM1niC** [comment]
> entity_type

![image](https://user-images.githubusercontent.com/1436958/230347353-13b7a43b-1315-4438-b0fe-d954bef3d2aa.png)

**Comment by yurikuzn** [comment]
Weird, we upgraded many instances.

**Comment by yurikuzn** [comment]
BTW, you use the legacy command. Use `php command.php upgrade --filte='path-to-file.zip'`

**Comment by DoM1niC** [comment]
> BTW, you use the legacy command. Use `php command.php upgrade --file='path-to-file.zip'`

ok crazy this was working now, the Web UI upgrade have the same problem, I have no idea why .... I use NGINX + PHP8.2-FPM

**Comment by yurikuzn** [comment]
Web upgrade is not recommended too. It's because it executes in a single process, PHP files are cached, issues may occur.

**Comment by homyvietnam** [comment]
I got the same error and don't know how to fix it

**Comment by yurikuzn** [comment]
Try to upgrade manually, by copying files. Then rebuild.

**Comment by sab0tajue** [comment]
Is the problem still there or did you somehow decide I can't update?
