### ISSUE TITLE
The used SELECT statements have a different number of columns

### ISSUE THREAD

**Issue by DoM1niC** [espocrm/espocrm#2691]
**Describe the bug**
The used SELECT statements have a different number of columns, problem since 7.4.0

**To Reproduce**
Open Cases / Accounts / Contact Pages and a notification appears with error code 500

**tested on 4x EspoCRM Instances with same issue**
**Webserver:** NGINX (latest Version)
**MariaDB:** 10.11.2
**PHP:** 8.2.4

**Expected behavior**
`[2023-04-06 12:12:59] ERROR: (21000) SQLSTATE[21000]: Cardinality violation: 1222 The used SELECT statements have a different number of columns; GET /Activities/Locations/63d84f1c8ba98e2d2/activities; line: 76, file: /home/www/radio/crm/application/Espo/ORM/Executor/DefaultSqlExecutor.php   [2023-04-06 12:12:59] ERROR: (21000) SQLSTATE[21000]: Cardinality violation: 1222 The used SELECT statements have a different number of columns; GET /Activities/Locations/63d84f1c8ba98e2d2/history; line: 76, file: /home/www/radio/crm/application/Espo/ORM/Executor/DefaultSqlExecutor.php  `
![image](https://user-images.githubusercontent.com/1436958/230376566-5c16269d-978d-4348-bf16-b622e9869cf5.png)

**EspoCRM version**
7.4.0

**Comment by yurikuzn** [comment]
Do you have any customization in Activities?

**Comment by DoM1niC** [comment]
> Do you have any customization in Activities?

yes

**Comment by yurikuzn** [comment]
I tested Base Plus (created before) with a custom event but it works for me. Maybe your entity was created long before and differs somehow.

**Comment by yurikuzn** [comment]
Try debugging here https://github.com/espocrm/espocrm/blob/7.4.0/application/Espo/Modules/Crm/Tools/Activities/Service.php#L352 and bellow where select is defined for other entities. It might be that some field in your custom entity is skipped for some reason.

**Comment by yurikuzn** [comment]
Or provide your custom entity's entityDefs here, maybe I'll see the problem.

**Comment by yurikuzn** [comment]
You can enable SQL logging to see the problem SQL query. It must be a UNION query. https://docs.espocrm.com/administration/log/#sql-queries

**Comment by rabiibrahimi** [comment]
i have enabled the sql mode and this is what is printed on log (it is  union) not sure how to solve though. 
`[2023-04-06 13:43:40] INFO: SQL: SELECT COUNT(c.id) AS `count` FROM ((SELECT meeting.id AS `id`, meeting.name AS `name`, meeting.date_start AS `dateStart`, meeting.date_end AS `dateEnd`, meeting.date_start_date AS `dateStartDate`, meeting.date_end_date AS `dateEndDate`, 'Meeting' AS `_scope`, meeting.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, meeting.parent_type AS `parentType`, meeting.parent_id AS `parentId`, meeting.status AS `status`, meeting.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `meeting` LEFT JOIN `user` AS `assignedUser` ON meeting.assigned_user_id = assignedUser.id WHERE meeting.parent_id = '642ec9cac40278d18' AND meeting.parent_type = 'Project' AND meeting.status IN ('Planned') AND meeting.deleted = 0) UNION (SELECT call.id AS `id`, call.name AS `name`, call.date_start AS `dateStart`, call.date_end AS `dateEnd`, NULL AS `dateStartDate`, NULL AS `dateEndDate`, 'Call' AS `_scope`, call.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, call.parent_type AS `parentType`, call.parent_id AS `parentId`, call.status AS `status`, call.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `call` LEFT JOIN `user` AS `assignedUser` ON call.assigned_user_id = assignedUser.id WHERE call.parent_id = '642ec9cac40278d18' AND call.parent_type = 'Project' AND call.status IN ('Planned') AND call.deleted = 0) UNION (SELECT project.id AS `id`, project.name AS `name`, project.date_start AS `dateStart`, project.date_end AS `dateEnd`, project.date_start_date AS `dateStartDate`, project.date_end_date AS `dateEndDate`, 'Project' AS `_scope`, project.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, project.status AS `status`, project.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `project` LEFT JOIN `user` AS `assignedUser` ON project.assigned_user_id = assignedUser.id WHERE project.status IN ('Planned') AND project.parent_id = '642ec9cac40278d18' AND project.parent_type = 'Project' AND project.deleted = 0)) AS `c`  
[2023-04-06 13:43:40] INFO: SQL: SELECT note.id AS `id`, note.deleted AS `deleted`, note.post AS `post`, note.data AS `data`, note.type AS `type`, note.target_type AS `targetType`, note.number AS `number`, note.is_global AS `isGlobal`, createdBy.gender AS `createdByGender`, note.is_internal AS `isInternal`, note.created_at AS `createdAt`, note.modified_at AS `modifiedAt`, note.parent_id AS `parentId`, note.parent_type AS `parentType`, note.related_id AS `relatedId`, note.related_type AS `relatedType`, note.created_by_id AS `createdById`, NULLIF(TRIM(CONCAT(IFNULL(createdBy.first_name, ''), ' ', IFNULL(createdBy.last_name, ''))), '') AS `createdByName`, note.modified_by_id AS `modifiedById`, NULLIF(TRIM(CONCAT(IFNULL(modifiedBy.first_name, ''), ' ', IFNULL(modifiedBy.last_name, ''))), '') AS `modifiedByName`, note.super_parent_id AS `superParentId`, note.super_parent_type AS `superParentType` FROM `note` AS `note` LEFT JOIN `user` AS `modifiedBy` ON note.modified_by_id = modifiedBy.id LEFT JOIN `user` AS `createdBy` ON note.created_by_id = createdBy.id WHERE ((note.parent_type = 'Project' AND note.parent_id = '642ec9cac40278d18') OR (note.super_parent_type = 'Project' AND note.super_parent_id = '642ec9cac40278d18')) AND note.deleted = 0 ORDER BY note.number DESC LIMIT 0, 5  
[2023-04-06 13:43:40] INFO: SQL: SELECT COUNT(c.id) AS `count` FROM ((SELECT meeting.id AS `id`, meeting.name AS `name`, meeting.date_start AS `dateStart`, meeting.date_end AS `dateEnd`, meeting.date_start_date AS `dateStartDate`, meeting.date_end_date AS `dateEndDate`, 'Meeting' AS `_scope`, meeting.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, meeting.parent_type AS `parentType`, meeting.parent_id AS `parentId`, meeting.status AS `status`, meeting.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `meeting` LEFT JOIN `user` AS `assignedUser` ON meeting.assigned_user_id = assignedUser.id WHERE meeting.parent_id = '642ec9cac40278d18' AND meeting.parent_type = 'Project' AND meeting.status IN ('Held','Not Held') AND meeting.deleted = 0) UNION (SELECT call.id AS `id`, call.name AS `name`, call.date_start AS `dateStart`, call.date_end AS `dateEnd`, NULL AS `dateStartDate`, NULL AS `dateEndDate`, 'Call' AS `_scope`, call.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, call.parent_type AS `parentType`, call.parent_id AS `parentId`, call.status AS `status`, call.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `call` LEFT JOIN `user` AS `assignedUser` ON call.assigned_user_id = assignedUser.id WHERE call.parent_id = '642ec9cac40278d18' AND call.parent_type = 'Project' AND call.status IN ('Held','Not Held') AND call.deleted = 0) UNION (SELECT email.id AS `id`, email.name AS `name`, email.date_sent AS `dateStart`, NULL AS `dateEnd`, NULL AS `dateStartDate`, NULL AS `dateEndDate`, 'Email' AS `_scope`, email.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, email.parent_type AS `parentType`, email.parent_id AS `parentId`, email.status AS `status`, email.created_at AS `createdAt`, email.has_attachment AS `hasAttachment` FROM `email` LEFT JOIN `user` AS `assignedUser` ON email.assigned_user_id = assignedUser.id WHERE email.parent_id = '642ec9cac40278d18' AND email.parent_type = 'Project' AND email.status IN ('Archived','Sent') AND email.deleted = 0) UNION (SELECT project.id AS `id`, project.name AS `name`, project.date_start AS `dateStart`, project.date_end AS `dateEnd`, project.date_start_date AS `dateStartDate`, project.date_end_date AS `dateEndDate`, 'Project' AS `_scope`, project.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, project.status AS `status`, project.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `project` LEFT JOIN `user` AS `assignedUser` ON project.assigned_user_id = assignedUser.id WHERE project.status IN ('Held','Not Held') AND project.parent_id = '642ec9cac40278d18' AND project.parent_type = 'Project' AND project.deleted = 0)) AS `c`  
[2023-04-06 13:43:40] DEBUG: API (21000) SQLSTATE[21000]: Cardinality violation: 1222 The used SELECT statements have a different number of columns; GET /Activities/Project/642ec9cac40278d18/activities; Route pattern: /Activities/{parentType}/{id}/{type}; Route params: Array (     [parentType] => Project     [id] => 642ec9cac40278d18     [type] => activities )`
the error is produced on the UI only when i add the project to the activity list and history activity list under setting.

**Comment by yurikuzn** [comment]
Does this query fail if you run it manually?

**Comment by rabiibrahimi** [comment]
yes i have the queries and both these queries below fail, same error (The used SELECT statements have a different number of columns): 
```
SELECT COUNT(c.id) AS `count` FROM ((SELECT meeting.id AS `id`, meeting.name AS `name`, meeting.date_start AS `dateStart`, meeting.date_end AS `dateEnd`, meeting.date_start_date AS `dateStartDate`, meeting.date_end_date AS `dateEndDate`, 'Meeting' AS `_scope`, meeting.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, meeting.parent_type AS `parentType`, meeting.parent_id AS `parentId`, meeting.status AS `status`, meeting.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `meeting` LEFT JOIN `user` AS `assignedUser` ON meeting.assigned_user_id = assignedUser.id WHERE meeting.parent_id = '642ec9cac40278d18' AND meeting.parent_type = 'Project' AND meeting.status IN ('Planned') AND meeting.deleted = 0) UNION (SELECT call.id AS `id`, call.name AS `name`, call.date_start AS `dateStart`, call.date_end AS `dateEnd`, NULL AS `dateStartDate`, NULL AS `dateEndDate`, 'Call' AS `_scope`, call.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, call.parent_type AS `parentType`, call.parent_id AS `parentId`, call.status AS `status`, call.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `call` LEFT JOIN `user` AS `assignedUser` ON call.assigned_user_id = assignedUser.id WHERE call.parent_id = '642ec9cac40278d18' AND call.parent_type = 'Project' AND call.status IN ('Planned') AND call.deleted = 0) UNION (SELECT project.id AS `id`, project.name AS `name`, project.date_start AS `dateStart`, project.date_end AS `dateEnd`, project.date_start_date AS `dateStartDate`, project.date_end_date AS `dateEndDate`, 'Project' AS `_scope`, project.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, project.status AS `status`, project.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `project` LEFT JOIN `user` AS `assignedUser` ON project.assigned_user_id = assignedUser.id WHERE project.status IN ('Planned') AND project.parent_id = '642ec9cac40278d18' AND project.parent_type = 'Project' AND project.deleted = 0)) AS `c`  
```
```
SELECT COUNT(c.id) AS `count` FROM ((SELECT meeting.id AS `id`, meeting.name AS `name`, meeting.date_start AS `dateStart`, meeting.date_end AS `dateEnd`, meeting.date_start_date AS `dateStartDate`, meeting.date_end_date AS `dateEndDate`, 'Meeting' AS `_scope`, meeting.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, meeting.parent_type AS `parentType`, meeting.parent_id AS `parentId`, meeting.status AS `status`, meeting.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `meeting` LEFT JOIN `user` AS `assignedUser` ON meeting.assigned_user_id = assignedUser.id WHERE meeting.parent_id = '642ec9cac40278d18' AND meeting.parent_type = 'Project' AND meeting.status IN ('Held','Not Held') AND meeting.deleted = 0) UNION (SELECT call.id AS `id`, call.name AS `name`, call.date_start AS `dateStart`, call.date_end AS `dateEnd`, NULL AS `dateStartDate`, NULL AS `dateEndDate`, 'Call' AS `_scope`, call.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, call.parent_type AS `parentType`, call.parent_id AS `parentId`, call.status AS `status`, call.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `call` LEFT JOIN `user` AS `assignedUser` ON call.assigned_user_id = assignedUser.id WHERE call.parent_id = '642ec9cac40278d18' AND call.parent_type = 'Project' AND call.status IN ('Held','Not Held') AND call.deleted = 0) UNION (SELECT email.id AS `id`, email.name AS `name`, email.date_sent AS `dateStart`, NULL AS `dateEnd`, NULL AS `dateStartDate`, NULL AS `dateEndDate`, 'Email' AS `_scope`, email.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, email.parent_type AS `parentType`, email.parent_id AS `parentId`, email.status AS `status`, email.created_at AS `createdAt`, email.has_attachment AS `hasAttachment` FROM `email` LEFT JOIN `user` AS `assignedUser` ON email.assigned_user_id = assignedUser.id WHERE email.parent_id = '642ec9cac40278d18' AND email.parent_type = 'Project' AND email.status IN ('Archived','Sent') AND email.deleted = 0) UNION (SELECT project.id AS `id`, project.name AS `name`, project.date_start AS `dateStart`, project.date_end AS `dateEnd`, project.date_start_date AS `dateStartDate`, project.date_end_date AS `dateEndDate`, 'Project' AS `_scope`, project.assigned_user_id AS `assignedUserId`, NULLIF(TRIM(CONCAT(IFNULL(assignedUser.first_name, ''), ' ', IFNULL(assignedUser.last_name, ''))), '') AS `assignedUserName`, project.status AS `status`, project.created_at AS `createdAt`, FALSE AS `hasAttachment` FROM `project` LEFT JOIN `user` AS `assignedUser` ON project.assigned_user_id = assignedUser.id WHERE project.status IN ('Held','Not Held') AND project.parent_id = '642ec9cac40278d18' AND project.parent_type = 'Project' AND project.deleted = 0)) AS `c`  
```

**Comment by yurikuzn** [comment]
Maybe you have another overriding entityDefs file in custom?

**Comment by rabiibrahimi** [comment]
i have only one project.json under entityDefs folder in custom *which is the file generated by the crm when i created the base plus event type entity*

**Comment by yurikuzn** [comment]
Can you provide it.

**Comment by rabiibrahimi** [comment]
this is the project.json on entityDefs folder on in custom: 
```
{
    "fields": {
        "name": {
            "type": "varchar",
            "required": true,
            "trim": true,
            "pattern": "$noBadCharacters"
        },
        "status": {
            "type": "enum",
            "options": [
                "Planned",
                "Held",
                "Not Held"
            ],
            "default": "Planned",
            "style": {
                "Held": "success"
            },
            "audited": true
        },
        "dateStart": {
            "type": "datetimeOptional",
            "view": "crm:views/meeting/fields/date-start",
            "required": true,
            "default": "javascript: return this.dateTime.getNow(15);",
            "audited": true
        },
        "dateEnd": {
            "type": "datetimeOptional",
            "view": "crm:views/meeting/fields/date-end",
            "required": true,
            "after": "dateStart"
        },
        "isAllDay": {
            "type": "bool",
            "layoutListDisabled": true,
            "layoutDetailDisabled": true,
            "layoutMassUpdateDisabled": true
        },
        "duration": {
            "type": "duration",
            "start": "dateStart",
            "end": "dateEnd",
            "options": [
                300,
                600,
                900,
                1800,
                2700,
                3600,
                7200,
                10800
            ],
            "default": 300,
            "notStorable": true,
            "select": {
                "select": "TIMESTAMPDIFF_SECOND:(dateStart, dateEnd)"
            },
            "order": {
                "order": [
                    [
                        "TIMESTAMPDIFF_SECOND:(dateStart, dateEnd)",
                        "{direction}"
                    ]
                ]
            }
        },
        "parent": {
            "type": "linkParent",
            "entityList": [
                "Account",
                "Lead",
                "Contact"
            ]
        },
        "description": {
            "type": "text"
        },
        "reminders": {
            "type": "jsonArray",
            "notStorable": true,
            "view": "crm:views/meeting/fields/reminders",
            "layoutListDisabled": true,
            "validatorClassNameList": [
                "Espo\\Modules\\Crm\\Classes\\FieldValidators\\Event\\Reminders\\Valid",
                "Espo\\Modules\\Crm\\Classes\\FieldValidators\\Event\\Reminders\\MaxCount"
            ]
        },
        "createdAt": {
            "type": "datetime",
            "readOnly": true
        },
        "modifiedAt": {
            "type": "datetime",
            "readOnly": true
        },
        "createdBy": {
            "type": "link",
            "readOnly": true,
            "view": "views/fields/user"
        },
        "modifiedBy": {
            "type": "link",
            "readOnly": true,
            "view": "views/fields/user"
        },
        "assignedUser": {
            "type": "link",
            "required": true,
            "view": "views/fields/assigned-user"
        },
        "teams": {
            "type": "linkMultiple",
            "view": "views/fields/teams"
        }
    },
    "links": {
        "parent": {
            "type": "belongsToParent",
            "foreign": "projectChildren"
        },
        "createdBy": {
            "type": "belongsTo",
            "entity": "User"
        },
        "modifiedBy": {
            "type": "belongsTo",
            "entity": "User"
        },
        "assignedUser": {
            "type": "belongsTo",
            "entity": "User"
        },
        "teams": {
            "type": "hasMany",
            "entity": "Team",
            "relationName": "EntityTeam",
            "layoutRelationshipsDisabled": true
        },
        "meetings": {
            "type": "hasMany",
            "entity": "Meeting",
            "foreign": "parent",
            "layoutRelationshipsDisabled": true
        },
        "calls": {
            "type": "hasMany",
            "entity": "Call",
            "foreign": "parent",
            "layoutRelationshipsDisabled": true
        },
        "tasks": {
            "type": "hasChildren",
            "entity": "Task",
            "foreign": "parent",
            "layoutRelationshipsDisabled": true
        },
        "emails": {
            "type": "hasChildren",
            "entity": "Email",
            "foreign": "parent",
            "layoutRelationshipsDisabled": true
        }
    },
    "collection": {
        "orderBy": "createdAt",
        "order": "desc"
    },
    "indexes": {
        "name": {
            "columns": [
                "name",
                "deleted"
            ]
        },
        "dateStartStatus": {
            "columns": [
                "dateStart",
                "status"
            ]
        },
        "dateStart": {
            "columns": [
                "dateStart",
                "deleted"
            ]
        },
        "status": {
            "columns": [
                "status",
                "deleted"
            ]
        },
        "assignedUser": {
            "columns": [
                "assignedUserId",
                "deleted"
            ]
        },
        "assignedUserStatus": {
            "columns": [
                "assignedUserId",
                "status"
            ]
        }
    }
}
```

**Comment by yurikuzn** [comment]
Weird. Could you provide `data/cache/application/objMetadata.php`.

**Comment by rabiibrahimi** [comment]
i have tested this on a new instance of espocrm, and definitely this is not about the custom entity i have. i have created a new entity (type event) and same error is produced. error is produced on ui when i added the entity to the activity list and history activity list under setting. what i have noticed is that the entityDefs generated for the visit event entity type is weird and doesn't comply with the template used to generate  the files. i have noticed that the visit entityDefs has: 
```
"fields": {
"parent": {
            "notStorable": true, // this should not be generated as it is not on the template
            "type": "linkParent",
            "entityList": [
                "Account",
                "Lead",
                "Contact"
            ]
        },
}
```
this is what is causing the error once i removed "notStorable": true then everything works fine. but i have double check the event template entityDefs and parent field is set properly not sure how this "notStorable": true is injected.

**Comment by yurikuzn** [comment]
I've been investigating the source of that notStorable, But no luck. I don't have it added on my instance.

**Comment by yurikuzn** [comment]
The issue is with any link-parent field saved ever. I might write upgrade script.

**Comment by rabiibrahimi** [comment]
i have tried it on a base entity (called employ) and added a (employ) as parent to the parent field and checked the entityDefs and it is clear and no error. this only happens when it is an event type entity.

**Comment by yurikuzn** [comment]
Here the fix with the upgrade-script. https://github.com/espocrm/espocrm/commit/65bef1df6567c9ccc4bd6eca8a8d2da72da7095f

**Comment by rabiibrahimi** [comment]
Thanks

**Comment by yurikuzn** [comment]
Have the error gone after upgrading?

**Comment by rabiibrahimi** [comment]
yes 
it is sorted now, i have done more tests and everything seems to work fine.
