### ISSUE TITLE
Enum/Mulyi-enum/Array/Checklist: Options re-use

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2695]
The ability to re-use options from another field.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/73650075112abcf04a66d0b6623f7f366f502b42
https://github.com/espocrm/espocrm/commit/66ecf7794e43d3b31db65dcc372ff4fb14d3aa64

**Comment by murugappanrm** [comment]
This one is great. Thank you Yuri.
