### ISSUE TITLE
Alias for /client/ did not work with suggested vhost settings

### ISSUE THREAD

**Issue by maisen20** [espocrm/espocrm#2697]
**Describe the bug**
The alias for /client/ did not work. But I was able to solve the problem by changing the host settings in addition to the suggested customizations. I don't know if this is a problem from my server, but maybe this would help someone?

**Expected behavior**
Route /client access to correct folder

**EspoCRM version**
EspoCRM v7.4.3

Proposed vhost config from EspoCRM:
```
DocumentRoot /www/workflow_dev/CRM/EspoCRM-7.4.3/public/
Alias /client/ /www/workflow_dev/CRM/EspoCRM-7.4.3/client/

<Directory /www/workflow_dev/CRM/EspoCRM-7.4.3/public/>
  AllowOverride All
</Directory>
```

Configuration which worked for me:
DocumentRoot "/www/CRM/EspoCRM-7.4.3/public/"^

```
    <Directory "/www/CRM/EspoCRM-7.4.3/public/">
        AllowOverride All
        Require all granted
    </Directory>

    Alias /client/ /www/CRM/EspoCRM-7.4.3/client/
    <Directory "/www/CRM/EspoCRM-7.4.3/client/">
        AllowOverride All
        Require all granted
    </Directory>
```

So i had to add Directory-Settings for Alias.

**Comment by maisen20** [comment]
It doesn't work that way either. There seem to be several problems with .htaccess. Also I have seen that other users also had various problems with it, but these issues here were simply closed without the problem being solved.

So I have to find another application.

**Comment by yurikuzn** [comment]
> issues here were simply closed without the problem being solved

We don't provide free support on GitHub. Only bug reporting and feature requests.
