### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2698]
A parameter for the following field types:

* Varchar
* URL
* Number

![image](https://user-images.githubusercontent.com/1006792/232754396-c1329f19-0b06-4f82-90f3-80150fd16adb.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3d743d306b948909804afbc5dd10eb6829198725

**Comment by Kharg** [comment]
Awesome!
Would it be difficult to extend it to email/phone/text fields?

**Comment by yurikuzn** [comment]
There are some difficulties.

**Comment by yurikuzn** [comment]
Not planned.

**Comment by yurikuzn** [comment]
What browsers do not support `navigator.clipboard` ?

**Comment by RabeeBrahimi** [comment]
so i have tried it on firefox version113 which the latest and i get an error. see attached screenshot. also tested it on chrome version 114.0.5735.110 same error see screenshot
Not sure if the error is only local or is this general. 

<img width="960" alt="chrome_clipboard_error" src="https://github.com/espocrm/espocrm/assets/130481723/85b4d972-56c1-40f6-8a30-d54a3e68d0c8">
<img width="960" alt="clipboard_error" src="https://github.com/espocrm/espocrm/assets/130481723/f0db194c-2733-4a4b-8680-f394a823b849">

**Comment by RabeeBrahimi** [comment]
yes you are right, switched to https and it works. i am not using localhost (using laravel valet instead)
