### ISSUE TITLE
Memo dashlet

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2699]
To display some text. Can be useful for portals to display some information. Markdown is supported.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/e3a2042990f2b50cfb904502e66130e14dafe2f7

**Comment by Kharg** [comment]
7.5 is looking so good so far 😃

**Comment by Kharg** [comment]
https://github.com/espocrm/espocrm/blob/9099f84441e1b682efa8c9930ed7d997f8074972/client/src/views/dashlets/memo.js#L39
is it normal for the name to be 'iframe'? Shouldn't it be Memo?

**Comment by yurikuzn** [comment]
No, but this values is never read/used, so won't have any effect.

**Comment by sab0tajue** [comment]
yeeeahhhhaa!!! Cool

**Comment by Kharg** [comment]
> yeeeahhhhaa!!! Cool job! But need html tags (may be <center>, <b>...)

There's a custom extension for that
