### ISSUE TITLE
Enable Cross-domain

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#270]
Hi @yurikuzn 

can we make the app Cross-domain enabled by default, or by setting? 
I solved it but I am sure that it 's not he best solution, you may take a look to [CorsSlim](https://github.com/palanik/CorsSlim)

**Comment by yurikuzn** [comment]
Hi,

Do you have code committed to see how you implemented this?

**Comment by ayman-alkom** [comment]
I will make a PR, to explain what I did, but I didn't used the CorsSlim.

**Comment by ayman-alkom** [comment]
https://github.com/ayman-alkom/espocrm/commit/872fd931d71e091232577cc24a778aa818658f80
https://github.com/ayman-alkom/espocrm/commit/4154aa1ed282d7fe990eeefb2d646d61f64b9efd

**Comment by ayman-alkom** [comment]
improve clear cache: merge backend and front end clear: https://github.com/ayman-alkom/espocrm/commit/95a0eaf3ca4f1364290f6db46b667d9b80cdeea8
across-origin: add Access-Control-Allow-Origin header: https://github.com/ayman-alkom/espocrm/commit/9ce4505750206ceb0fd40e0acde5a03983efe509
