### ISSUE TITLE
Add admin entities to Search results 

### ISSUE THREAD

**Issue by emillod** [espocrm/espocrm#2701]
**Describe the solution you'd like**
I would greatly appreciate a new feature in EspoCRM that would allow admin users to easily search for admin features like Entity Manager, Formula Sandbox, etc. in global search. 

This would simplify managing EspoCRM and make it more efficient. It would also be wonderful if a shortcut `/` could be added to focus on the global search-bar. Thank you very much in advance.

**Comment by yurikuzn** [comment]
I wouldn't mix admin features with global search. Too much issues to resolve for 2 clicks. Unlikely to be implemented.
