### ISSUE TITLE
Style tag is being removed from pdf templates when editing

### ISSUE THREAD

**Issue by afzt** [espocrm/espocrm#2703]
**Describe the bug**
When creating a pdf template for an entity, style tag is being saved to db, but gets removed on a subsequent edit.

**To Reproduce**
1. In Administration > Templates, create a new Template;
2. Assign an arbitrary *Name* and *Entity Type*;
3. Write this *Body*: 
```
<style>
h1 {
  color: #f00;
}
</style>

<h1>Example title</h1>
<p>Example paragraph</p>
```
4. Save template;
5. In the chosen entity, choose an arbitrary item and print it using the *Print to PDF* menu item, with the newly created template;
6. The PDF gets printed correctly, using red color for `<h1>` title;
7. In Administration > Templates, choose the previously created template, and *Edit*;
8. In *Body* field, `<style>` tags and their relative content are missing, but on database is still present; if the template gets now saved, the style gets definitively lost also from database.

**Expected behavior**
When editing template, I expect to see `<style>` tags as when the template was saved.

**Screenshots**
![Screenshot 2023-04-19 at 17-03-51 DEMO BUG](https://user-images.githubusercontent.com/131279046/233119534-514032c4-afae-49f0-8463-5e3290f1e002.png)
![Screenshot 2023-04-19 at 17-04-35 DEMO](https://user-images.githubusercontent.com/131279046/233119531-c4940834-8dfe-42ee-9749-48966aa6ae6b.png)
![Screenshot 2023-04-19 at 17-12-11 DEMO BUG](https://user-images.githubusercontent.com/131279046/233120482-093ab35c-a869-4ebc-868d-7b3907277b54.png)

**EspoCRM version**
7.4.3

**Additional context**

**Comment by yurikuzn** [comment]
It was posted a few times. It's not a bug. We don't have control over this functionality.
