### ISSUE TITLE
Group Email Folders not visible if no team set

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2705]
**Describe the bug**
Group Email Folders not visible if no team set

**To Reproduce**
1. Create a group email folder "Folder A" without a team
2. create a user with a role that has "Group Email Account Permission" = all
3. Login as user 
4. View email list
5. Folder A is not shown 

**Expected behavior**
When use has  "Group Email Account Permission" = all then all Group email folder should be shown.

**EspoCRM version**
Specify the EspoCRM version (or versions) on which the bug occurs.

**Comment by yurikuzn** [comment]
Group Email Account and Group Email Folder are different things. It's not documented that group email account permission should take effect on group email folder definitions. But it's stated that access is controlled by teams https://github.com/espocrm/espocrm/issues/2467.

**Comment by boydle** [comment]
Thanks Yuri
