### ISSUE TITLE
Compatibility issue Espo 7.4.3 and Advanced pack 2.15.3

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#2711]
**Describe the bug**
Workflows with defined email action are not sending emails.

**To Reproduce**
Create worklofw which has Email action and trigger it.

**Expected behavior**
EspoCRM sends email.

**EspoCRM version**
7.4.3

**Additional context**
There is no error in DEBUG log.
Email is not sent to mailserver (from logs of mail server).

**Comment by yurikuzn** [comment]
Please create issues related to extensions on the forum or customer portal. This repository is for open source EspoCRM.
