### ISSUE TITLE
URL-Multiple field type

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2713]
![url-multiple](https://user-images.githubusercontent.com/1006792/234561228-8fe55ba0-7070-418f-9b5f-9b3bed8d267f.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/d62d4265a81adf05c44a6dc286a79c44e25fcf13

**Comment by murugappanrm** [comment]
Hehehe.. this has removed the need for some third-party extensions. Thank you so much
