### ISSUE TITLE
IDE flags client/css/misc/layout-manager-grid.css

### ISSUE THREAD

**Issue by czcpf** [espocrm/espocrm#2715]
**Describe the bug**
My IDE is claiming layout-manager-grid.css has a syntax error lines 50-55

**To Reproduce**
1. Open layout-manager-grid.css in IDE 
2. ...
3. ...
...

**Expected behavior**
No errors or warnings in screenshots

**Screenshots**
<img width="777" alt="Screen Shot 2023-04-26 at 1 07 15 PM" src="https://user-images.githubusercontent.com/88215293/234664909-dbd9b225-83f7-422f-916a-8da062fd53a1.png">
<img width="555" alt="Screen Shot 2023-04-26 at 1 07 01 PM" src="https://user-images.githubusercontent.com/88215293/234664900-26204b47-f6ec-4d88-a676-8829eac5ba00.png">

**EspoCRM version**
7.4.3

**Additional context**

**Comment by yurikuzn** [comment]
Fixed. Thanks.
