### ISSUE TITLE
Can not query for 0 - 500 error

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2716]
**Describe the bug**
Search in Account List for 0 > a 500 error is shown

**To Reproduce**
1. Search in Account List for 0

**Expected behavior**
Search should be performed for 0

**Screenshots**
![image](https://user-images.githubusercontent.com/7907518/234735712-db63e7f5-db81-4b09-93aa-3cabbb3cdd87.png)

**EspoCRM version**
7.4.3

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/aa5427d9760473091c5df20a32eb3a3e516753e3
