### ISSUE TITLE
Locking dashboard layout 

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2717]
Regular users are able to lock their dashboard layout. Dragging, resizing and adding will be disabled. Admin can lock the dashboard layout for specific users by editing their preferences. Users will still be able to unlock.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/0e94a9708a70e0a20cd372681377e742260592a6

**Comment by yurikuzn** [comment]
Didn't think about *remove*. Will add.

**Comment by Kharg** [comment]
Thanks Yuri, you are the best 😊

**Comment by Kharg** [comment]
Maybe Dashboard locking should also lock the "Options" menu item for dashlets?

**Comment by yurikuzn** [comment]
Was not intended. Only layout is locked.

**Comment by yurikuzn** [comment]
I'm still extremely busy, can't review any feature requests for a few weeks at least.
