### ISSUE TITLE
API Before-Save script

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2720]
Can be used for duplicate checking and custom validation. See in [docs](https://github.com/espocrm/documentation/blob/master/docs/administration/api-before-save-script.md).

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/5d61b049b565438ea741569738335c69c54001d1

**Comment by rabiibrahimi** [comment]
``Hey i have played with this and it is very powerful. one thing that i find would enhance the use of it is adding an extra formula function record\findMany with ability to accept a limit of how many records to fetch. the use case is when trying to prevent the user from creating another record with some value e.g don't create a new lead with status = "Assigned" in this case findMany will come handy to fetch a collection of leads that have a status (Assigned) and can provide a possibility to provide optional limit of how many records to fetch : 

`record\findMany(ENTITY_TYPE, Limit, ORDER_BY, ORDER, KEY1, VALUE1, KEY2, VALUE2)` 

and use the function as below: 

```
if (entity\isNew() && !recordService\skipDuplicateCheck()) {

    $ids = record\findMany('Lead', 3, 'createdAt', 'asc', 'status=', 'Assigned');

    $ids = array\unique($ids);

    if (array\length($ids)) {
        recordService\throwDuplicateConflict($ids);
    }
}
```

FindMany is very useful many times a user would want to fetch a collection of records not necessarily related to target entity (already we have record\findRelatedMany and record\findRelatedOne).

Hope this makes sense.
