### ISSUE TITLE
Abstraction of Currency Conversion framework

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2721]
**Is your feature request related to a problem? Please describe.**
It's impossible to convert currency of Quote/Invoice in SalesPack. 

**Describe the solution you'd like**
Ability to implement different Currency Convertors for each entity type. First idea that comes to my mind is factory-based design for currency converters.

**Describe alternatives you've considered**
Writing my custom `MassConvertCurrency` and `ConvertCurrency` that implement exceptions for certain entities.

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/e0a00f4d419e9d5ac6502f5ece24ecf4a7d37954

**Comment by yurikuzn** [comment]
I changed it so that it's not supposed that *saveEntity* is  called within the interface.
