### ISSUE TITLE
 Display related objects in a merged report

### ISSUE THREAD

**Issue by sab0tajue** [espocrm/espocrm#2728]
It is required to make a grouped report from two sections "Buildings" and "Lands". They are combined into one field "Building + Land" where the user attaches the building to the land. Display a grouped report for this related field so that you can see the related properties: Building + land

**Comment by yurikuzn** [comment]
Issue does not use one of two templates. It's not clear what it's about. Not clear what is reports. This repository is for Open Source EspoCRM.

**Comment by sab0tajue** [comment]
<img width="1277" alt="Снимок экрана 2023-05-05 в 13 24 41" src="https://user-images.githubusercontent.com/87798667/236434804-93571aa0-ee49-4772-a50b-899c8a6fe3d2.png">
I just mean esposrm, or rather advanced pack, there you need to build a report in such a way as to show in the table a link between two sections and
