### ISSUE TITLE
Creatable CategoryTree Entities

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2729]
**Is your feature request related to a problem? Please describe.**
It's would be useful to have the possibility to create new CategoryTree (list with categories) entities

**Describe the solution you'd like**
Being able to create new category tree entities from the entity Manager so that it creates the 2 needed entity MyEntity and MyEntityFolder

**Describe alternatives you've considered**
Manually creating the needed entities using the list with categories view. But it's time consuming.

**Additional context**
![image](https://user-images.githubusercontent.com/32223252/236262514-bcbf89ab-d59e-4b4c-90ca-53be7907e89c.png)

**Comment by yurikuzn** [comment]
This can't implemented this way.

**Comment by yurikuzn** [comment]
JFY, for the next few months we don't plan to add new features. Need to concentrate on another work. I'll try not to follow feature requests during this period to avoid distraction.

**Comment by yurikuzn** [comment]
If this ever be implemented, then with some hooks, but not as a new entity template.

**Comment by Kharg** [comment]
@o-data I think I tried once, but it needs to be adapted to use the new classes of v7.
So it's a lot of work
