### ISSUE TITLE
LDAP authentication not working with user admin (id user = 1)

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2731]
https://github.com/espocrm/espocrm/blob/3e18f488c60a81617a81149565d5d1f0cf50cb1d/application/Espo/Core/Authentication/Ldap/LdapLogin.php#L203

1. Configure LDAP authentication
2. logged in with user admin (user id = 1 )
3. can't login

Expected behavior
I would expect to be logged in with user admin 

EspoCRM version
git master

**Comment by yurikuzn** [comment]
I'm not sure there's a bug. Could you help with fix if so?

**Comment by yurikuzn** [comment]
Does the same configuration work on the stable version instance?

**Comment by kamolpech** [comment]
Thank you for your reply, I can fix it by
Edit file application/Espo/Core/Authentication/Ldap/LdapLogin.php Line 203

`

                $adminUser = $this->adminLogin($username, $password);
                if (!isset($adminUser)) {
                    return Result::fail();
                }`

**Comment by yurikuzn** [comment]
This is not the way to fix. It would be a security hole.

Unfortunately, I'm busy and can't take a look. I don't have access to LDAP env at hand, our tester tested the functionality before v7.3 release and didn't report any issues.

**Comment by kamolpech** [comment]
Thank you for your reply, I'll try to find a new way.
