### ISSUE TITLE
Documents Attachment field overlay bug

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2733]
**Describe the bug**
Clicking the pencil icon to edit a file attachment in a document and then cancelling will keep the create document overlay if you try to drop a file (happens as well if you switch entity).
It doesn't happen always.

**To Reproduce**
1. Open a document record containing a file attached
2. .Click the pencil action and then cancel.
3. .try to drop a file in the window.

**Expected behavior**
The overlay shouldn't not be displayed or you will be unable to upload extensions or files to other fields unless you refresh the page

**Video**
Reproduced in the demo
https://www.awesomescreenshot.com/video/17215219?key=4698da834ccef29eb25e8f334f2a9cdf

**EspoCRM version**
7.4.3

**Comment by Kharg** [comment]
Doesn't happen anymore inside the record but it still happens if you exit the record and do it in list view! 

https://www.awesomescreenshot.com/video/17255730?key=68746d75487e5ae13ad61a4ba20d577f

**Comment by yurikuzn** [comment]
> if you exit the record and do it in list view

It is a feature: https://github.com/espocrm/espocrm/issues/2011

**Comment by Kharg** [comment]
Oh, but then it keeps happening in other entities list view if you switch entity.

**Comment by Kharg** [comment]
Oh, I got it, thanks!
