### ISSUE TITLE
Duplicated Code on Meeting detail view

### ISSUE THREAD

**Issue by RabeeBrahimi** [espocrm/espocrm#2736]
**Describe the bug**
I noticed that there is a duplicate code on the meeting detail view.
**To Reproduce**
1. check this https://github.com/espocrm/espocrm/blob/ed12c6f6bde9bba1039d2a5b6a72086e41d95b9e/client/modules/crm/src/views/meeting/detail.js#L164
```
if (show) {
                let dateEnd = this.model.get('dateEnd');

                if (
                    dateEnd &&
                    this.getDateTime().toMoment(dateEnd).isBefore(moment.now())
                ) {
                    show = false;
                }
 }
```
3. this piece of code is repeated twice. 
...

**Expected behavior**
if this is a duplicated code should removed. 

**Screenshots**

**EspoCRM version**
7.4.4
**Additional context**

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/6f7b5e9973b8fb7dcca0d5ff51079da166abb4f4
