### ISSUE TITLE
autofocus not set

### ISSUE THREAD

**Issue by pow-nico** [espocrm/espocrm#2738]
**Describe the bug**
If you've logged into your EspoCRM instance and have MFA activated, the focus doesn't get set automatically into the "code" input field.

**To Reproduce**
1. activate MFA
2. log into EspoCRM
3. wait until the page "Enter a code from your authenticator app." got loaded

**Expected behavior**
After the login was successful and the page "Enter a code from your authenticator app." got loaded the keyboard focus should be at the "code" input field

**Screenshots**
![screen](https://github.com/espocrm/espocrm/assets/99261218/1d0fa2da-8380-4a19-bfa5-2063164ef8b7)

**EspoCRM version**
7.4.3 (docker setup)

**Comment by pow-nico** [comment]
I hereby agree to the terms of the EspoCRM Contributor License Agreement v1.1.

2023-05-12

Nico Heinrich

**Comment by yurikuzn** [comment]
Implemented: https://github.com/espocrm/espocrm/commit/a727cee3a61953cbcc47d15d878fc6a3051bf679

**Comment by pow-nico** [comment]
Thank you very much for the fast response!
