### ISSUE TITLE
Cleanup job error

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#2742]
**Describe the bug**

**To Reproduce**
1. new install 
2. Running specific job manually in CLI  "php command.php run-job Cleanup"
3. error Error: Job 'Cleanup' failed to execute. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'currency.deleted' in 'field list'

**EspoCRM version**
git master

**Additional context**
ERROR: JobManager: Failed job running, job '6460a84ebb31dcf10'. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'currency.deleted' in 'field list'; at application\Espo\ORM\Executor\DefaultSqlExecutor.php:76.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/53ecb367055ef03d742dcfe87034d4242606f5f7
