### ISSUE TITLE
InjectableFactory:class doesnot exists

### ISSUE THREAD

**Issue by pradnya-khandagale** [espocrm/espocrm#2744]
**Describe the bug**
ERROR: (500) InjectableFactory: Class 'Espo\ORM\MetadataDataProvider' does not exist.;

**EspoCRM version**
6.1.7

**Additional context**
i am trying to add two factor email authentication to 6.1.7 version after adding fiels related to that from reference to 7.0.0 version i am getting this error.even though i have the both the fiels present in my folder.please help me out of this.
thanks in advance

ERROR: (500) InjectableFactory: Class 'Espo\ORM\MetadataDataProvider' does not exist.; GET /Settings; line: 91, file: C:\xampp\htdocs\crm\pipalcrm-production\application\Espo\Core\InjectableFactory.php [] []

this is  my injectablefactory.php file

<?php

namespace Espo\Core;

use Espo\Core\{
    Exceptions\Error,
    Interfaces\Injectable,
    Binding\BindingContainer,
    Binding\Factory,
    Binding\Binding,
};

use ReflectionClass;
use ReflectionParameter;
use ReflectionFunction;
use Throwable;

/**
 * Creates an instance by a class name. Uses constructor param names and type hinting to detect which
 * dependencies are needed. Service dependencies are instantiated only once. Non-service dependencies
 * are instantiated every time along with a dependent class.
 *
 * Aware interfaces are also used to detect service dependencies.
 */
class InjectableFactory
{
    protected $container;

    protected $bindingContainer;

    public function __construct(Container $container, ?BindingContainer $bindingContainer = null)
    {
        $this->container = $container;
        $this->bindingContainer = $bindingContainer;
    }

    /**
     * Creates an instance by a class name.
     */
    public function create(string $className) : object
    {
        return $this->createByClassName($className);
    }

    /**
     * Creates an instance by a class name. Allows passing specific constructor parameters.
     * Defined in an associative array. A key should match the parameter name.
     */
    public function createWith(string $className, array $with = []) : object
    {
        return $this->createByClassName($className, $with);
    }
    public function createWithBinding(string $className, BindingContainer $bindingContainer): object
    {
        return $this->createByClassName($className, null, $bindingContainer);
    }
    /**
     * @deprecated Use create or createWith methods instead. Left public for backward compatibility.
     * @todo Make protected.
     */
    public function createByClassName(string $className, ?array $with = null,?BindingContainer $bindingContainer = null) : object
    {
        if (!class_exists($className)) {
            throw new Error("InjectableFactory: Class '{$className}' does not exist.");
        }

        $class = new ReflectionClass($className);

        $injectionList = $this->getConstructorInjectionList($class, $with);

        $obj = $class->newInstanceArgs($injectionList);

        // @todo Remove in 6.4.
        if ($class->implementsInterface(Injectable::class)) {
            $this->applyInjectable($class, $obj);

            return $obj;
        }

        $this->applyAwareInjections($class, $obj);

        return $obj;
    }

    /**
     * @deprecated
     * @todo Remove in 6.4.
     */
    protected function applyInjectable(ReflectionClass $class, object $obj)
    {
        $setList = [];

        $dependencyList = $obj->getDependencyList();

        foreach ($dependencyList as $name) {
            $injection = $this->container->get($name);

            if ($this->classHasDependencySetter($class, $name)) {
                $methodName = 'set' . ucfirst($name);
                $obj->$methodName($injection);
                $setList[] = $name;
            }

            $obj->inject($name, $injection);
        }

        $this->applyAwareInjections($class, $obj, $setList);

        return $obj;
    }

    protected function getConstructorInjectionList(ReflectionClass $class, ?array $with = null,?BindingContainer $bindingContainer = null) : array
    {
        $injectionList = [];

        $constructor = $class->getConstructor();

        if (!$constructor) {
            return $injectionList;
        }

        $params = $constructor->getParameters();

        foreach ($params as $param) {
            $injectionList[] = $this->getMethodParamInjection($class, $param, $with);
        }

        return $injectionList;
    }

    protected function getMethodParamInjection(?ReflectionClass $class, ReflectionParameter $param, ?array $with = null,?BindingContainer $bindingContainer = null)
    {
        $name = $param->getName();

        if ($with && array_key_exists($name, $with)) {
            return $with[$name];
        }

        $dependencyClass = null;

        $type = $param->getType();

        if ($type && !$type->isBuiltin()) {
            try {
                $dependencyClass = new ReflectionClass($type->getName());
            }
            catch (Throwable $e) {
                $badClassName = $param->getType()->getName();

                // This trick allows to log syntax errors.
                class_exists($badClassName);

                throw new Error("InjectableFactory: " . $e->getMessage());
            }
        }

        if ($this->bindingContainer && $this->bindingContainer->has($class, $param)) {
            $binding = $this->bindingContainer->get($class, $param);

            return $this->resolveBinding($binding,$bindingContainer);
        }

        if (!$dependencyClass && $param->isDefaultValueAvailable()) {
            return $param->getDefaultValue();
        }

        if (
            $dependencyClass && $this->container->has($name) &&
            $this->areDependencyClassesMatching($dependencyClass, $this->container->getClass($name))
        ) {
            return $this->container->get($name);
        }

        if ($dependencyClass && $param->allowsNull()) {
            return null;
        }

        if ($dependencyClass) {
            return $this->create($dependencyClass->getName(), null, $bindingContainer);
        }

        if (!$class) {
            throw new Error("InjectableFactory: Could not resolve the dependency '{$name}' for a callback.");
        }

        $className = $class->getName();

        throw new Error("InjectableFactory: Could not create '{$className}', the dependency '{$name}' is not resolved.");
    }

    protected function getCallbackInjectionList(callable $callback, ?array $with = null) : array
    {
        $injectionList = [];

        $function = new ReflectionFunction($callback);

        foreach ($function->getParameters() as $param) {
            $injectionList[] = $this->getMethodParamInjection(null, $param, $with);
        }

        return $injectionList;
    }

    protected function resolveBinding(Binding $binding, ?BindingContainer $bindingContainer)
    {
        $type = $binding->getType();
        $value = $binding->getValue();

        if ($type === Binding::CONTAINER_SERVICE) {
            return $this->container->get($value);
        }

        if ($type === Binding::IMPLEMENTATION_CLASS_NAME) {
            return $this->create($value, null, $bindingContainer);
        }

        if ($type === Binding::VALUE) {
            return $value;
        }

        if ($type === Binding::CALLBACK) {
            $callback = $value;

            $dependencyList = $this->getCallbackInjectionList($callback);

            return $callback(...$dependencyList);
        }

        throw new Error("InjectableFactory: Bad binding.");
    }

    protected function areDependencyClassesMatching(ReflectionClass $paramHintClass, ReflectionClass $returnHintClass) : bool
    {
        if ($paramHintClass->getName() === $returnHintClass->getName()) {
            return true;
        }

        if ($returnHintClass->isSubclassOf($paramHintClass)) {
            return true;
        }

        return false;
    }

    protected function applyAwareInjections(ReflectionClass $class, object $obj, array $ignoreList = [])
    {
        foreach ($class->getInterfaces() as $interface) {
            $interfaceName = $interface->getShortName();

            if (substr($interfaceName, -5) !== 'Aware' || strlen($interfaceName) <= 5) {
                continue;
            }

            $name = lcfirst(substr($interfaceName, 0, -5));

            if (in_array($name, $ignoreList)) {
                continue;
            }

            if (!$this->classHasDependencySetter($class, $name, true)) {
                continue;
            }

            $injection = $this->container->get($name);

            $methodName = 'set' . ucfirst($name);
            $obj->$methodName($injection);
        }
    }

    protected function classHasDependencySetter(ReflectionClass $class, string $name, bool $skipInstanceCheck = false) : bool
    {
        $methodName = 'set' . ucfirst($name);

        if (!$class->hasMethod($methodName) || !$class->getMethod($methodName)->isPublic()) {
            return false;
        }

        $params = $class->getMethod($methodName)->getParameters();

        if (!$params || !count($params)) {
            return false;
        }

        if ($skipInstanceCheck) {
            return true;
        }

        $injection = $this->container->get($name);

        $paramClass = null;

        $type = $params[0]->getType();

        if ($type && !$type->isBuiltin()) {
            $paramClass = new ReflectionClass($type->getName());
        }

        if ($paramClass && $paramClass->isInstance($injection)) {
            return true;
        }

        return false;
    }
}

**Comment by yurikuzn** [comment]
This not a bug. Please use our forum for developer questions.
