### ISSUE TITLE
Knowledge base language is ignored 

### ISSUE THREAD

**Issue by cobia** [espocrm/espocrm#2752]
Setting language on knowledge base articles has no effect. The articles are shown regardless  of the language selected in the portal preferences. Eg. I set the article's language to Spanish(spain) while the portal is set to English(US) and the article is still shown. 

This is happening on version 7.4.5

**Comment by yurikuzn** [comment]
I believe this was never implemented, I don't know how it ended up in the documentation. This functionality would be redundant as there's the ability to display a KB article in a specific portal. I';; remove the statement from the docs.

**Comment by cobia** [comment]
Does this mean that the recommended approach is to create a different portal for each language?

**Comment by yurikuzn** [comment]
It's one of the options. Or group articles in different folders/categories.

**Comment by cobia** [comment]
Are you going to remove the language field from the articles entity? We prefer to filter by that field when choosing which articles to show the portal user. If you will remove it, then we will just create another field for language so as not to break our installation when the system is updated.
