### ISSUE TITLE
Layout Editor - Bottom Panels Removes Properties set in metadata

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2753]
**Describe the bug**
When creating bottomPanelsDetail.json in an extension or in custom folders you can set properties like these for the relationship panels:

        "select": false,
        "create": false,
        "createAction": "MyAction",
        "view": "custom:views/record/panels/relationship-custom",
        "rowActionsView": "custom:views/record/row-actions/relationship-view-and-edit-custom"

When using the layout editor to make changes to bottom panels like adding a new panel or re-ordering existing panels these properties are removed on save.

**Expected behavior**
These extended options should be preserved.

**EspoCRM version**
7.4.0

**Comment by yurikuzn** [comment]
This feature is not intentional and not documented, hence not considered to be a bug. Please use clientDefs > bottomPanels instead.

**Comment by boydle** [comment]
ok.

When using clientDefs the user is unable to remove/reorder these panels in the layout editor. Is there any setting that can be provided in clientDefs to allow this?

**Comment by yurikuzn** [comment]
Do you mean that you set properties in metadata > clientDefs and they are unset?

**Comment by yurikuzn** [comment]
> When using clientDefs the user is unable to remove/reorder these panels in the layout editor.

It shouldn't be so. All panels in layout editor (except relationship) are defined by clientDefs. There are also relationship panels.

**Comment by boydle** [comment]
No.

I have taken another look and the panel is shown in the bottom panels layout editor in the disabled section even though it is shown on the screen.
The user can drag it on and reorder the panels and the clientDefs properties are kept.

The panel should probably show in the enabled section of the layout editor rather than disabled.

There does not seem to be anyway for a user to remove a clientDefs defined panel from bottom panels

**Comment by yurikuzn** [comment]
> There does not seem to be anyway for a user to remove a clientDefs defined panel from bottom panels

We do have this out of the box (for meeting) and it works (at least there was no bug report).

**Comment by yurikuzn** [comment]
https://docs.espocrm.com/development/metadata/client-defs/#relationshippanels

**Comment by boydle** [comment]
Thanks, I have just checked meeting and the clientDef panel scheduler is defined in it and in the bottomPanelsDetail.json and this resolves the issue I see with the user not being able to remove the panel and it showing in the incorrect location.

Thanks for your help.

**Comment by yurikuzn** [comment]
I checked meetings panels and they are working fine.
