### ISSUE TITLE
Saving Emails: SQLSTATE[HY000]: General error: 1366 Incorrect string value

### ISSUE THREAD

**Issue by digitalextremist** [espocrm/espocrm#2758]
Saving a draft email returns `500` error, with this in the log:

```
[2023-05-31 22:36:27] ERROR: (HY000) SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x85)\x0A...' for column 'body_plain' at row 1; POST /Email; line: 76, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php
```

As well as:

```
[2023-05-31 22:38:06] ERROR: EmailAccount 646b01e305893fed7, import message; HY000 SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\xA5\x87 A...' for column 'body_plain' at row 1  
```

**Describe the bug**
It seems there is an unescaped string going into the database?

**To Reproduce**
Trying to isolate what character(s) made that particular email special.

**Expected behavior**
Drafts ought to save, and emails ought to send, regardless of the characters in the email body.

**EspoCRM version `7.4.5`**

**Comment by digitalextremist** [comment]
Noticed this also on `InboundEmail` and I think I have email samples now which reproduce the issue, on sending drafts, on sending, and on receiving. There is a character preventing saving of emails:

```
$ cat espo-2023-05-31.log | grep "ERROR: Inbound"
[2023-05-31 20:05:06] ERROR: InboundEmail 6467ae6a1be0f375d, import message; HY000 SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x82. ...' for column 'body_plain' at row 1  
[2023-05-31 23:45:07] ERROR: InboundEmail 6467ae6a1be0f375d, import message; HY000 SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x85)\x0D...' for column 'body_plain' at row 1  
```

Then upon widening the search, it appears this is a pretty deep-seated issue which explains why I have not been seeing a lot of emails:

![image](https://github.com/espocrm/espocrm/assets/21095/926fa574-dc08-4d3d-853a-8dca68ab7743)

I have samples of all those emails too, for the most part. Investigating.

**Comment by yurikuzn** [comment]
What collation do you have for body and body_plain columns? These are emoji characters. I tried to save them, got no error.

**Comment by digitalextremist** [comment]
Thanks for the tip so far @yurikuzn -- the collation of the table is `utf8mb3_unicode_ci` it seems. Here is what I have:

```
MySQL [espocrm]> SHOW TABLE STATUS where name LIKE 'email'
    -> ;
+-------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+--------------------+----------+----------------+---------+
| Name  | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time | Collation          | Checksum | Create_options | Comment |
+-------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+--------------------+----------+----------------+---------+
| email | InnoDB |      10 | Dynamic    |  460 |          49045 |    22560768 |               0 |       573440 |   4194304 |           NULL | 2023-04-16 23:31:02 | 2023-06-01 18:03:17 | NULL       | utf8mb3_unicode_ci |     NULL |                |         |
+-------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+--------------------+----------+----------------+---------+
1 row in set (0.144 sec)

MySQL [espocrm] > SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_0900_ai_ci   |
+--------------------------+----------------------+
1 row in set (0.001 sec)
```

Is there a recommended collation I missed?

**Comment by digitalextremist** [comment]
```sql
ALTER TABLE Tablename CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
```

Seems that will be needed per this:

https://github.com/espocrm/espocrm/blob/6346fae0445bb5fe6eb4487ff469de62f607bde1/application/Espo/Core/Utils/Database/Schema/ColumnPreparators/MysqlColumnPreparator.php#L167-L171

**Comment by yurikuzn** [comment]
Collation of the table does not matter. Collation of a column does.

**Comment by yurikuzn** [comment]
I don't know how it happened, seems you have mb3 collation. I can't look into deeper as I'm extremely loaded with work.  This is unlikely a bug that can be fixed. At least we need a way to reproduce it. Never encounter a collation issue in Espo in years.

**Comment by digitalextremist** [comment]
fyi: this is on a table in a database at a `DigitalOcean` MySQL cluster.

I *really* appreciate the key tip here @yurikuzn. Cheering you on as you attack your workload!

**Comment by digitalextremist** [comment]
![image](https://github.com/espocrm/espocrm/assets/21095/cc051868-1b09-4b73-b06d-e3dc4be969ea)

Does it need to be `_bin` versus `_unicode_ci`?

**Comment by yurikuzn** [comment]
`utf8mb4_unicode_ci`

**Comment by digitalextremist** [comment]
@yurikuzn storing emoji in `EspoCRM` ( not just for email ) with the correct charset cannot be fixed?

Not just for email, but any entity. Right now I have 5 test instances which all crash with emoji, even using the correct collation, on the docker container implementation.

**Comment by digitalextremist** [comment]
Somehow `data/config-internal.php` had `charset` provided as `NULL` on the database connection!

Any idea how that would happen?

Changing `charset` to `utf8mb4` in `data/config-internal.php` resolves the issue.

**Comment by yurikuzn** [comment]
> storing emoji in EspoCRM ( not just for email ) with the correct charset cannot be fixed?

EspoCRM does store emoji. Considering collation is not wrong. As I mentioned, we've never encountered this issue. It works for every our instances and I haven't seen people complaining about this problem for the last few years. I really have no time.

**Comment by digitalextremist** [comment]
I will keep an eye on it in future instances, and see why that happens.

I will be here a very long time I hope, so your time helping goes a long way. I will bring help moving issues forward here once I get through these initial glitches and fully understand the design. We have gotten through some big one so far with your tips to give clues.

Best of luck on your day/night @yurikuzn. I really appreciate your work.

**Comment by digitalextremist** [comment]
I notice that is maintained by @tmachyshyn and `docker` is an essential to us, so I have been focusing on building expertise in that context. I will keep an eye on this and be available to help in support instances in the future on that repository.
