### ISSUE TITLE
ES modules

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2762]
Gradual migrating frontend to ES modules. The current AMD module system will still be supported (maybe forever).

```js
import View from 'view';
import DetailRecordView from 'views/record/detail';

class MyView extends View {

    templateContent = `<div class="record">{{{record}}}</div>`

    setup() {
        const recordView = new DetailRecordView({/* options, autocompleted in IDE */});

        this.assignView('record', recordView, '.record');
    }
}

export default MyView;
```

Transpile all:

```
node js/transpile
```

Transpile a file:

```
node js/transpile -f {specific/file.js}
```

**Comment by yurikuzn** [comment]
I considered the second lib. But there are still a lot of work to be done aside actual JS file migrating.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c6b73373179cc6f65560b8d913f95788312de1c2

**Comment by yurikuzn** [comment]
Seems all is done. It was huge. Also added support in ext-template.

**Comment by Kharg** [comment]
Nice job!
What's gonna be the advantage over amd?

**Comment by yurikuzn** [comment]
AMD is a legacy long ago. It's keep being used only internally, nobody write AMD modules anymore for years. No proper IDE support, bad readability and many other. esm is standard

**Comment by Kharg** [comment]
Thanks for the explanation.
