### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by sofiaAv** [espocrm/espocrm#2764]
Hello, my Espo is showing erro 500 and requesting  the file https://crminnova.innovaiusti.com.br/api/v1/Settings
but this file Settings do not exits neither on the installation files, it was working as well now have this issue, can anybody help me?

Best regards.

**EspoCRM version**
7.4.3

**Additional context**
Hosted at Hostinger

**Comment by yurikuzn** [comment]
Please use our forum for help, here only development issues.

**Comment by yurikuzn** [comment]
https://docs.espocrm.com/administration/troubleshooting/

Please do not keep creating new issues on this. Would have to resort to blocking.

**Comment by digitalextremist** [comment]
@sofiaAv you will get a lot of help if you post here: https://forum.espocrm.com/forum/general
