### ISSUE TITLE
ES classes

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2766]
Migrating core frontend classes to ES syntax.

```js
import View from 'view';

class DetailView extends View {
    // ...
}

export default DetailView;
```

**Comment by mozkomor05** [comment]
Hi, I'm not sure if you already know it but current implementation is not backwards-compatible enough. Class fields cannot be accessed before initizalition, so this legacy code:

```js
define('my-view', 'views/base-view-with-events', function (Dep) {

    return Dep.extend({

        events: _.extend({
            'click .action': () => ...
        }, Dep.prototype.events);

    });
});

won't work as Dep.prototype.events is not defined.

**Comment by yurikuzn** [comment]
Indeed. Static is not an option as we have a lot of this.events[...] = usage.

**Comment by yurikuzn** [comment]
It seems we have only 1 usage of `Dep.prototype.events` in one extension and lot of `this.events` in many extensions.

**Comment by mozkomor05** [comment]
Okay, great.

**Comment by yurikuzn** [comment]
When defining events in a class property, there's also an issue that IDE does not know that callback is bound to the class, hence need to add `/** @this ClassName */`. Defining events in `setup` is more preferable way from this point of view.
