### ISSUE TITLE
OIDC sends prompt=consent parameter to authentication provider

### ISSUE THREAD

**Issue by mjvanderveen** [espocrm/espocrm#2769]
**Describe the bug**
We configured the azure AD oidc login to enable SSO.

Espocrm adds a url parameter prompt=consent to every login request. This parameter enforces the azure AD login to ask for consent to share data with espo each login attempt. Since in our system only admins can consent, the user is unable to login

**To Reproduce**
1. Configure oidc for active ad
2. Login with sso
3. Copy url of AD login screen popup
4. Observe that it has prompt=consent url parameter

**Expected behavior**
No prompt=consent url parameter. Possibly to be enforced as a setting in the OIDC authentication in azure admin area.

**Screenshots**

**EspoCRM version**
7.5.0

**Additional context**

The resolution is not to have the prompt=consent parameter.

I've manually tested this by editing application/Espo/Core/Authentication/Oidc/ConfigDataProvider.php

    public function getAuthorizationPrompt(): string
    {
        return $this->config->get('oidcAuthorizationPrompt') ?? ''; //'consent';
    }

I'm unable to locate what setting to change to prevent the consent prompt to be set by Espo. The oidcAuthorizationPrompt setting in the json is set to Admin.

**Comment by yurikuzn** [comment]
Please no need to report such issues as bugs. The parameter name is `oidcAuthorizationPrompt`, can be set in data/config.php to 'none' or 'login'. But 'consent' would be most secure.
