### ISSUE TITLE
MVC framework?

### ISSUE THREAD

**Issue by richhl** [espocrm/espocrm#277]
hi, evaluating for adopt CRM. is this product built agains any MVC 'standard' framework? symfony? zend? yii?

thx in advance.

**Comment by ayman-alkom** [comment]
Slim framework used here, as RESTFUL back-end server.
up to the frontend backbone.js is the main library
<div class="page-header">
    <h3>EspoCRM - Open Source CRM application</h3>
</div>

<div class="row">
    <div class="col-md-7">
        <section>
            <h5>Version {{version}}</h5>
            <p>
                Copyright &copy; 2014-2016 EspoCRM: Yuri Kuznetsov, Taras Machyshyn, Oleksiy Avramenko.
                <br>
                Website: <a href="http://www.espocrm.com">http://www.espocrm.com</a>.
            </p>
            <p>
                EspoCRM is free software: you can redistribute it and/or modify
                it under the terms of the GNU General Public License as published by
                the Free Software Foundation, either version 3 of the License, or
                (at your option) any later version.
            </p>
            <p>
                EspoCRM is distributed in the hope that it will be useful,
                but WITHOUT ANY WARRANTY; without even the implied warranty
                of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
            </p>
            <p>
                You should have received a copy of the GNU General Public License
                along with EspoCRM. If not, see http://www.gnu.org/licenses/.
            </p>

            <p>
                The interactive user interfaces in modified source and object code versions
                of this program must display Appropriate Legal Notices, as required under
                Section 5 of the GNU General Public License version 3.
            </p>

            <p>
                In accordance with Section 7(b) of the GNU General Public License version 3,
                these Appropriate Legal Notices must retain the display of the "EspoCRM" word.
            </p>
        </section>

        <section style="margin-top: 30px;">
        <h5>Javascript libraries used</h5>
        <ul>
            <li>Backbone.js</li>
            <li>Handlebars</li>
            <li>Grunt</li>
            <li>Underscore.js</li>
            <li>Moment.js</li>
            <li>Selectize.js by Brian Reavis</li>
            <li>Summernote</li>
            <li>Bootstrap</li>
            <li>Bootstrap Datepicker by Andrew Rowls</li>
            <li>Flotr2</li>
            <li>Fullcalendar</li>
            <li>Cropper by Fengyuan Chen</li>
            <li>JQuery</li>
            <li>JQuery UI</li>
            <li>JQuery Autocomplete by Tomas Kirda</li>
            <li>JQuery Textcomplete by Yuku Takahashi</li>
            <li>JQuery Timepicker by Jon Thornton</li>
            <li>gridstack.js by Pavel Reznikov</li>
            <li>vis.js by Almende B.V.</li>
        </ul>
        </section>
        <section style="margin-top: 30px;">
            <h5>PHP libraries used</h5>
            <ul>
                <li>Composer</li>
                <li>Doctrine (DBAL)</li>
                <li>Slim</li>
                <li>Cron Expression Parser by Michael Dowling</li>
                <li>Zendframework (Validator, Mail, Ldap)</li>
                <li>Monolog</li>
                <li>Identicon by Don Park</li>
                <li>php-semver by Lars Vierbergen</li>
                <li>TCPDF</li>
                <li>Lightncandy by Zordius</li>
            </ul>
        </section>
    </div>
</div>

**Comment by yurikuzn** [comment]
There is frontend based on backbone bun vastly extended and API backend written in php.
