### ISSUE TITLE
OIDC: Users without password can't log in

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2775]
**Describe the bug**
If user tries to log-in using OIDC, and has no password (hash) set. Espo returns error 500 after otherwise successful OIDC sign-in.
![image](https://github.com/espocrm/espocrm/assets/15276167/26908d8c-09a9-49c3-aaec-6693bdcfda84)

**To Reproduce**
1. Create Espo instance
2. Setup OIDC auth
3. Create user without password
4. Log-in as the user through OIDC
5. Error 500

**Expected behavior**
User is logged in successfuly and is able to use Espo. 

**EspoCRM version**
7.5.2

**Additional context**
This only occurs if option "Create users" in OIDC settings is turned off, and users have to be created manually.
If a user is created manually without password you get this error. If option "Create users" is on and user gets created, the log-in goes through without any issues (I am assuming its assigning some kind of random password).

**Workaround**
If admin generates random password for the user, the user is then able to log-in with OIDC and the "No hash" error goes away.

**Comment by yurikuzn** [comment]
Fix (generating password for new users): https://github.com/espocrm/espocrm/commit/5861923f3bb168d965fbc3af1f102340ae5f6b82. I apply it to the minor release as this would require QA.
