### ISSUE TITLE
Lead - nothing is changed during editing but lead is updated and the stream shows update

### ISSUE THREAD

**Issue by jakub-frajt** [espocrm/espocrm#2778]
**Describe the bug**
When I open lead for editing like this https://demo.eu.espocrm.com/?l=en_US#Lead/view/5f61b9b6dc8a12c55 on live demo and swith to edit mode but I will not do any edits and just hit save button then the stream will show update but nothing changed actually.  It looks like it only happens after the first update of the lead but not every time. When I tried again It showed right that nothing changed.

**To Reproduce**
1. Open already created lead and switch to edit mode.
2. Don't change anything and press save.
3. Lead is updated and the stream shows update but nothing changed actually.
...

**Expected behavior**
When I open edit mode for lead but I will not change anything it should not update lead.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/10637345/895d7c91-6419-4c6a-932f-eb9942822450)

**EspoCRM version**
7.5.3
7.2.7

**Additional context**
It appears on offical demo too like this case - https://demo.eu.espocrm.com/?l=en_US#Lead/view/5f61b9b6dc8a12c55

**Comment by yurikuzn** [comment]
This is a Espo bug. It's because wrong Currency value is stored in database. Should be NULL but set to EUR.

**Comment by jakub-frajt** [comment]
@yurikuzn  Thanks for your response.  But it looks like that multi enum field has bug too. 
![image](https://github.com/espocrm/espocrm/assets/10637345/bf6a9580-1216-4164-a127-c4eb62e99589)

I tried also locally. Field "bonuses" is multi enum and this is stored in note:

```
{
    "fields":
    [
        "bonuses",
    ],
    "attributes":
    {
        "was":
        {
            "bonuses": null,
        },
        "became":
        {
            "bonuses":
            [],
        }
    }
}
```
The default value is null but after that change to array

**Comment by yurikuzn** [comment]
It's a known issue with default values of array field types. I was considering it low priority.
