### ISSUE TITLE
Fetching all followers of a records fetches duplicates instead of the real followers

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2779]
**Describe the bug**
Fetching all followers of a records fetches duplicates instead of the real followers.

**To Reproduce**
1. Assign 8 followers to a record
2. click the "..." to view all the followers
3. Instead of fetching the missing follower you will get a duplicate
...

**Expected behavior**
You should be able to see all the record followers without getting duplicates

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/32223252/027aefb8-9cde-45f4-b0d4-0c0caca84a2e)
Video:
https://www.awesomescreenshot.com/video/18595224?key=d31c67298c3d12b42ffd60c660b4af9e
**EspoCRM version**
7.5.4

**Comment by yurikuzn** [comment]
I will take a look later. I'm switching the repository to 2 days quarantine to induce resting on weekends.

**Comment by Kharg** [comment]
Was able to reproduce in the demo as well
User 6 is not fetched
![image](https://github.com/espocrm/espocrm/assets/32223252/46e7b382-2f64-43e4-81b3-72aa4c628817)

**Comment by yurikuzn** [comment]
It was extra ORDER applied before. Fix: https://github.com/espocrm/espocrm/commit/2dfd14f3c5e0f77d050a1ec0c89c5f71130ac513
