### ISSUE TITLE
Emails containing 'base' html tag not displaying

### ISSUE THREAD

**Issue by filippogasbarro** [espocrm/espocrm#278]
Hello,
I've received an e-mail and the body content inside the E-mail is base64 encoded, in Outlook and in Thunderbird is possible to see without any problem, instead in Espocrm when I open the e-mail, it appear a empty page

**Comment by yurikuzn** [comment]
Can you attach email content here please?

**Comment by filippogasbarro** [comment]
Yes, here you are
[email.zip](https://github.com/espocrm/espocrm/files/556388/email.zip)

**Comment by yurikuzn** [comment]
Must work in the next 4.3.0 release

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/17b48c0e4c17e73c20a53d6e488a48020b16b7f1
