### ISSUE TITLE
Navbar tab grouping

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2780]
With dividers and optional labels. Only for side navbar.

![image](https://github.com/espocrm/espocrm/assets/1006792/d022430f-b52f-4710-8cc7-1ff0b686c302)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/4be63cb75eb75fcab06641afcda8bf5b24cec665

**Comment by Kharg** [comment]
Are dividers visible only inside a group?

Or you can have labels without dividers?

**Comment by yurikuzn** [comment]
Dividers invisible deliberately.
