### ISSUE TITLE
Wrong default encoding in PDO connection

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2781]
If an encoding is not specified in the config, a wrong encoding is applied. As of v7.4. Emojis may not save. Newly installed versions affected.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/975b7b72c3d92b933a689655d9ca0d094f8190a8

**Comment by digitalextremist** [comment]
Glad to see this one got caught @yurikuzn! Will test on future instances.
