### ISSUE TITLE
Images not rendered in PDF if defaultFileStorage is set to AwsS3

### ISSUE THREAD

**Issue by huseyin-cakmak** [espocrm/espocrm#2782]
**Describe the bug**
The images are not rendered in PDF if defaultFileStorage is set to AwsS3 while it works file when it is set to EspoUploadDir.

**To Reproduce**
1. Configuring aws s3 storage and linking to espocrm in config-internal.php
2. Create a PDF Template and upload an inline image in wysiwyg editor. The image is correctly uploaded to aws s3 bucket and is shown correctly in the GUI of Template edition.
3. Try to render a record to PDF using this template. → image does not appear. 
4. Try to do the same when the defaultFileStorage is EspoUploadDir → image renders fine.

**Expected behavior**
One would expect that the images appear in PDF irrespective of the defaultFileStorage used.

**EspoCRM version**
Version 7.5.4

**Comment by yurikuzn** [comment]
If works for me. Same steps, uploaded to Aws3. Inserted inline image using Ctrl+V.

**Comment by huseyin-cakmak** [comment]
Ok, thank you for testing on your side. 
I will investigate on my side then.

**Comment by yurikuzn** [comment]
Likely [here](https://github.com/espocrm/espocrm/blob/7.5.5/application/Espo/Core/FileStorage/Manager.php#L156) something is going wrong.

**Comment by huseyin-cakmak** [comment]
@yurikuzn Thank you for pointing a starting point.
