### ISSUE TITLE
Name field not generated when creating users

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2783]
The last several users I created do not have values in the `name` field. As you can see in the picture below, the behavior began occurring on May 8, 2023, which is when I upgraded from 7.3.4 to 7.4.3. Regular and portal users are affected.

![image](https://github.com/espocrm/espocrm/assets/1170415/4bee46a8-7df9-44de-9ece-23324c6bfab9)

**To Reproduce**
1. Create a new user with a first name, last name, or both.
2. View the database entry for the new user. The `name` field will be empty.

**EspoCRM version**
It started when I upgraded from 7.3.4 to 7.4.3 I am still experiencing the bug in version 7.5.5.

**Comment by bandtank** [comment]
Maybe this is a desired behavior. I'm not sure. I see some changes in 7.4.0 related to entities and names. I use the name field in hooks, which is how I came across this issue.

**Comment by yurikuzn** [comment]
It was there by a mistake. The Name field is of person-name type and should not be stored in database but concatenated dynamically depending on the set name-format.
