### ISSUE TITLE
Roles: Message permission

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2784]
Defines the ability for users to send stream messages to other users. Levels: all, team, no. Before, the Assignment Permission was used to define access.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/415199d8146b10e30ae7ef17de98571e8c55238d

**Comment by Sakkhor909** [comment]
How do I send stream  message to other users ?

**Comment by Shootify** [comment]
> How do I send stream message to other users ?

id like to know too.

**Comment by yurikuzn** [comment]
From the Stream dashlet or from the user detail view by posing to their stream.
