### ISSUE TITLE
Auth Provider Keycloak as OIDC result in error

### ISSUE THREAD

**Issue by ykorzikowski** [espocrm/espocrm#2786]
**Describe the bug**
I set up OIDC Auth in EspoCRM with keycloak using the following settings: 

<img width="1110" alt="Bildschirmfoto 2023-06-30 um 11 46 32" src="https://github.com/espocrm/espocrm/assets/20556547/ca76bca8-527a-4643-8973-8a450f703be5">
<img width="1123" alt="Bildschirmfoto 2023-06-30 um 11 46 24" src="https://github.com/espocrm/espocrm/assets/20556547/1c65e1eb-e3d3-4476-b9e2-8319e7e80cb5">
<img width="989" alt="Bildschirmfoto 2023-06-30 um 11 45 33" src="https://github.com/espocrm/espocrm/assets/20556547/34c4c5c7-182c-4b97-b5d7-024817a0f6ae">
<img width="1014" alt="Bildschirmfoto 2023-06-30 um 11 46 28" src="https://github.com/espocrm/espocrm/assets/20556547/7a78ef3e-3013-4a0f-a2c2-c5ab50ea709e">

**To Reproduce**
1. Setup  Keycloak Server
2. Setup EspoCRM
3. Configure EspoCRM Client in Keycloak
4. Setup OIDC Auth in Espocrm

**Expected behavior**
Login is working

**Screenshots**

```
[2023-06-30 09:47:44] ERROR: OIDC: Bad token request.; Status: 400; Response: {"error":"invalid_client","error_description":"Parameter client_assertion_type is missing"}
[2023-06-30 09:47:44] ERROR: (0) GET /App/user; line: 249, file: /var/www/html/application/Espo/Core/Authentication/Oidc/Login.php
```

**EspoCRM version**
7.4.6

**Additional context**
https://stackoverflow.com/questions/45428487/parameter-client-assertion-type-is-missing-in-keycloak

When using only `Client Id and Secret` (without the Signed Jwt stuff) its giving me a `500: no hash error`.

Why its not possible to use the simple client id and secret. I set up all my other services like this.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/2775

**Comment by yurikuzn** [comment]
If you can to help with a fix (if it's release a bug) it would be great. It unlikely that I will be able to set to Keyclock in the nearest future for reproducing.

**Comment by yurikuzn** [comment]
Added to docs that *client_secret_post* method might needs to be enabled for some providers.
