### ISSUE TITLE
Duplicate checking fields

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2790]
The ability to specify which field to check when performing duplicate checking. At Administration > Entity Manager.

Supported entity types:

* Account
* Contact
* Lead

Supported custom entity types of templates:

* Base
* Base Plus
* Company
* Person

Supported field types:

* Person Name
* Varchar
* Email
* Phone
* URL
* Barcode

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/82efcefac74da43040112432533902b350ffb142

**Comment by Kharg** [comment]
This is so cool! Thanks Yuri! 😃

Would it be possible to also add support for date field?

**Comment by Kharg** [comment]
Shouldn't "duplicateCheckFieldList" be a multi-enum to select the fields?

It is a bool as of now.

**Comment by yurikuzn** [comment]
> be a multi-enum

Indeed. It didn't take any effect though.

**Comment by rabiibrahimi** [comment]
Great addition thanks @yurikuzn 

One question this doesn't allow to apply condition e.g if name & email exists OR name & phoneNumber ? 

We can still use custom duplicateCheckBuiler for more complex duplicate checking right ? using expression to nest some complex conditions or AND + OR etc

**Comment by yurikuzn** [comment]
Right. Only 'OR'. For more complex conditions one needs to use a custom checker class.
