### ISSUE TITLE
Unlink (deleteActionRemoveLink) does not check if link field is a required field

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2795]
**Describe the bug**
In a Parent Child relationship the child has required on the link field to the parent. Unlink does not check if this is required allowing records to be unlinked. Unlink should check required-ness of the field the same as other updates.

**Expected behavior**
Unlink should not be allowed when the link field is marked as required

**EspoCRM version**
7.4

**Comment by yurikuzn** [comment]
It was not designed to do such a check.

**Comment by boydle** [comment]
OK, I will look at the workaround.

**Comment by yurikuzn** [comment]
Implemented in https://github.com/espocrm/espocrm/issues/2797.
