### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2799]
A new Light theme.

![image](https://github.com/espocrm/espocrm/assets/1006792/0c3afaa8-d5d0-4589-b1e4-0b8b5536e4d8)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/96fd21b381694a6c7e086fed9f7cb149e844de66

**Comment by buzzard10** [comment]
are you changing the logo? 😎

**Comment by yurikuzn** [comment]
This is by design to prevent form elements being too wide. You can change --record-grid-max-width CSS variable in custom CSS.

**Comment by rabiibrahimi** [comment]
yeah, i have noticed that the same applied to all other themes and even for all type of navbar (lef or top). 
Thanks yuri, wonder if there are any issues should we submit requests even though this version is not yet released? e.g in two instance of version 8 on my local host i found issue with phone field it doesn't allow to add more phone number when i checked i found that the field export function is wrong here https://github.com/espocrm/espocrm/blob/c6a2622744693c84d7a1b8561c120bbb461f6201/client/src/views/fields/phone.js#L513 it should `export default PhoneFieldView;` and even though i changed it in my instance still the phone number doesn't allow to add more phones, i am still investigating and i will share the fix if i figured it out. 

Version 8 looks really good thanks

**Comment by yurikuzn** [comment]
You can create GitHub issues for bugs in master too. We are on testing phase now. I'll fix the phone number field.
