### ISSUE TITLE
Add "Document" field in Cases

### ISSUE THREAD

**Issue by filippogasbarro** [espocrm/espocrm#280]
A lot of time is useful to have Documents linked to every case (like happens in opportunities)

**Comment by yurikuzn** [comment]
There is Knowledge Base Articles panel.

**Comment by filippogasbarro** [comment]
Ok, also if with the files field is more speedy, instead of go to Knowledge Base, create article, save, go another time to cases, open the case, go to knowledge Base and at the finish link to the knowledge Base article.
No need all these functionality/property of Knowledge Base for only basic upload a simple file.

If is it a problem to put by default, ok no problem, I will put manually the link/correlation in the administrator tab --> entity manager :)

Best regards,
Filippo Gasbarro
