### ISSUE TITLE
Invalid import data converted to default or unexpected values, imported, and no errors raised

### ISSUE THREAD

**Issue by AlexxxH** [espocrm/espocrm#2801]
**Describe the bug**
Invalid data in import gets converted to blank, default, or unexpected values. The data is imported and no errors are raised.
This applies to float and date type fields, and probably others (I've not checked). 
In `Espo/Tools/Import/Import.php`, parsing is run before validation. In `importRow`, `processRowItem` calls `parseValue` which takes in imported data and converts it to blank, default, or unexpected values. E.g., for floats, the `parseValue` function will convert:
- "test" -> 0
- "1test" -> 1
- "test1" -> 0
- "1.2.3" -> 1.2

The validation step (Ln 563) receives the new parsed value so cannot validate the original data or raise an error.

**To Reproduce**
Steps to reproduce the behavior using "float" type (but this is also a problem for other types):
1. Create an entity with a float-type field
2. Create a CSV file with an invalid value for the float field, e.g. "test"
3. Import the data, set field mapping in step 2 to map the CSV column to the float field
4. Import results shows the invalid record in the imported list with "0" value in place of "test". No errors are listed.

**Expected behavior**
Invalid input data should give a validation error and the entity should not be imported. On the import results page, the entity should be listed under "errors".
Suggestion: validation should be done before parsing, and parsing should raise an error if the field is not a valid type.

**EspoCRM version**
7.5.4

**Comment by yurikuzn** [comment]
It's known behavior. I'll fix it but it will be bit harder than it seems.

**Comment by AlexxxH** [comment]
Thanks for the quick reply! Would it be possible to raise an exception in `parseValue` and catch it in `importRow`, e.g. expanding the `try` on ln 556 to include the `processRowItem` loop? This would avoid having to change the validation or order.

**Comment by yurikuzn** [comment]
A already did the fix: https://github.com/espocrm/espocrm/commit/0c26d35287d0f8ee53bd4ed502266c523c4e70cd

**Comment by AlexxxH** [comment]
Great, thanks!

**Comment by AlexxxH** [comment]
Thanks for sorting this so quickly. Do you know when it's likely to be included in a next release?

**Comment by yurikuzn** [comment]
In v8.0, ETA: the end of August.
