### ISSUE TITLE
Schedule Translation

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2802]
Hi Yuri, can we make "Schedule" and 'Log' to use a translated label?

https://github.com/espocrm/espocrm/blob/36aa6739fce2dad11c7332cffb20e8b5401862a7/client/modules/crm/src/views/record/panels/activities.js#L199

**Comment by yurikuzn** [comment]
Hi, Not clear what you mean. Please provide more details. It's translated here: https://github.com/espocrm/espocrm/blob/7.5.5/client/modules/crm/src/views/record/panels/activities.js#L209

**Comment by Kharg** [comment]
Will provide more details when I get home.

But basically setting "activitiesCreateButtonMaxCount" to 4 the 4th icon in the Activities panel will have "Schedule EntityName" as its label while hovering on the icon, it will not use the translated label for "Schedule".

**Comment by yurikuzn** [comment]
I added a hook that creates "Schedule {entity}" and "Lod {entity}" labels when an Event entity type is created. https://github.com/espocrm/espocrm/commit/837f8b2796ceb8357b251464dc996607eac65b28
