### ISSUE TITLE
LDAP Authentication issue

### ISSUE THREAD

**Issue by vvsreerag** [espocrm/espocrm#2803]
I have configured the Ldap and the test connection was successfull, 

but i have a doubt how to setup User Team and Default User Team and what that means for ldap, 

and Default Portal for a Portal User setting up can anyone show me a sample of those users that we can create for ldap does that have to have any configuration similiar to ldap configuration

and do we really need those things ?

**Comment by yurikuzn** [comment]
Please use our forum. We don't provide support on Github (as it's stated on New Issue  page). There are more people on the forum who can potentially help.
