### ISSUE TITLE
"of" label

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2804]
Hi Yuri,

Would it be possible to get this "of" label in the language files so that it can be translated into other languages in POEditor?

https://github.com/espocrm/espocrm/blob/efdff66593b1eb509e2121f19b442ab8fea4abca/client/res/templates/record/list-pagination.tpl#L15C60-L15C62

Thanks

**Comment by yurikuzn** [comment]
It's not fully working, we don't test it, we don't support it, it's not good UX. As I have already mentioned, we put quite an an effort to deliver a quality product, having half-baked buggy features negates the  effort.

**Comment by Kharg** [comment]
I understand your point of view, it's a feature loved by many, it would be a shame to remove it.

Is this feature really this buggy? :(

**Comment by yurikuzn** [comment]
It's not an official feature, and was not in documentation. I understand that many may like old school pagination. But we have a view how Espo should look and feel from the beginning. We could add many things that many people would have loved, but that would have been a different product.

**Comment by Kharg** [comment]
I understand Yuri, do what's right for Espo.
