### ISSUE TITLE
Followup to "JobManager is not working in some cases"

### ISSUE THREAD

**Issue by githubkoma** [espocrm/espocrm#2806]
**Describe the bug**
Follow up to https://github.com/espocrm/espocrm/issues/2683

We also have this issue since updating from PHP 7.4 to PHP 8.2 + Espo to 7.5.5

We have a custom job that Syncs Espo Data with an Outside Server: `EspoSync.php`

Since upgrading php from 7.4 to 8.2 and Espo to 7.5.5 the job throws those 1) warnings:
`[2023-07-26 00:00:24] WARNING: E_WARNING: Trying to access array offset on value of type null {"code":2,"message":"Trying to access array offset on value of type null","file":"/home/espo/www/espo/custom/Espo/Custom/Jobs/EspoSync.php","line":92}`

And 2) after directly following in that Espo log file, we got the same error as mentioned in the previous Bugreport:
`[2023-07-26 00:00:32] ERROR: JobManager: Failed job running, job '64c05e7e020e1f6cf'. Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /home/espo/www/espo/custom/Espo/Custom/Jobs/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 96; at /home/espo/www/espo/custom/Espo/Custom/Jobs/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:892.`

I was able to workaround this issue with changing the line in Creator.php:892:
```
    //private static function setLastErrors(array $lastErrors)
    private static function setLastErrors($lastErrors)
```

-> After that the Job did not crash anymore!

It looks like sometimes within Espo, the function setLastErrors() is called with a bool as parameter instead of an array.
I was not able to debug where/in which runtime case exactly Espo calls this function only with a bool.

How can this be debugged further?

We dont want to maintain workaround in the Creator.php

**Comment by yurikuzn** [comment]
We have never encountered such error. It could be that your vendor is not upgraded for some reason.

**Comment by yurikuzn** [comment]
You provided error `"file":"/home/espo/www/espo/custom/Espo/Custom/Jobs/EspoSync.php","line":92` but didn't provide the your job content. I can't know that's there.
