### ISSUE TITLE
Controller Route Aliases

### ISSUE THREAD

**Issue by TFesmire** [espocrm/espocrm#2808]
**Describe the bug**
When creating a route, the route needs to match the controller name exactly in order to work. There is an option to create a route with parameters that list the controller and action which is shown below. My understanding is that you should be able to name the route whatever you would like and it should not need to match the class name. 

This works correctly:
```
{
    "route": "/MyController",
    "method": "get",
    "params": {
        "controller": "MyController",
        "action": "test"
    }
}
```

This does not:
```
{
    "route": "/Asdf",
    "method": "get",
    "params": {
        "controller": "MyController",
        "action": "test"
    }
}
```
The error that is produced is being generated is shown below:  
```
[2023-07-27 16:02:30] WARNING: (404) Controller 'Asdf' does not exist.; GET /Asdf/action/Test; line: 190, file: ~/site/application/Espo/Core/Api/ControllerActionProcessor.php  
```

```
185     private function getControllerClassName(string $name): string
186     {
187         $className = $this->classFinder->find('Controllers', $name);
188 
189         if (!$className) {
190             throw new NotFound("Controller '{$name}' does not exist.");
191         }                                                                                
192 
193         if (!class_exists($className)) {
194             throw new NotFound("Class not found for controller '{$name}'.");
195         }
196 
197         return $className;
198     }
```

**Comment by yurikuzn** [comment]
There's no bug. You didn't clear a cache and the route is intercepted by the [existing route](https://github.com/espocrm/espocrm/blob/7.5.5/application/Espo/Resources/routes.json#L447).

BTW it's better to use `actionClassName` instead of controllers.

**Comment by RabeeBrahimi** [comment]
> BTW it's better to use actionClassName rather than controllers.

what the difference between using a controller and actionClassName ?

**Comment by yurikuzn** [comment]
* Explicitness.
* No need to remember method naming and class location conventions.
* No controller name conflicts.
* Class can be put in any place.
* Different action classes don't share same dependencies.
