### ISSUE TITLE
Global Search and Notifications modals display issue on iPhone

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2811]
**Describe the bug**
Happens on mobile, if you open the menu while inside list view and then open the notification list the element of the list view (search bar and create button) will be shown on top of the notification bar

**To Reproduce**
1. Go to Contact entity
2. Open the navbar menu
3. Open the notification list
...

**Expected behavior**
Element from the list view should be covered by the notification list

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/32223252/c349a6dd-3a75-4cbb-8899-054b71fc9060)

**EspoCRM version**
Tested on the official demo 7.5.5

**Comment by yurikuzn** [comment]
I could not reproduce.

**Comment by yurikuzn** [comment]
I could not reproduce.

**Comment by yurikuzn** [comment]
Actually, it's the way it worked in early versions.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/7.5.5/frontend/less/espo/custom.less#L3307

Maybe changing 100% to 100vh will help. Could you check?

**Comment by Kharg** [comment]
Changed it directly in espo.css theme

@media screen and (max-width:767px) {
    #notifications-panel {
        position: fixed;
        width: 100%;
        top: 0;
        right: 0;
        left: 0;
        margin-right: 0;
        height: 100vh
    }

issue is still there, I used browserstack.com and was able to reproduce on iPhone simulators as well, issue is not reproducible on Safari for MacOS.

Can be reproduced also inside records, not only on list view.

**Comment by yurikuzn** [comment]
We could not find a solution yet. We could just close the navbar, but this is not good solution for the global search (which has this issue too). Any help appreciated.

**Comment by yurikuzn** [comment]
It seems that elements with `position: relative;` are making though the background.

**Comment by Kharg** [comment]
Maybe using z-index would fix the issue? Or adding !important to the notifications-panel?

**Comment by yurikuzn** [comment]
> Maybe using z-index would fix the issue

We tried. Didn't work. It seems a bug in latest iOS versions.

**Comment by yurikuzn** [comment]
> This is a small issue anyway

With global search, it's quite significant issue as results overlaps with elements from below. Anyway I did a workaround: https://github.com/espocrm/espocrm/commit/3d4ceb9efb988e3497d7bb43cf4b4c513886a4be

**Comment by Kharg** [comment]
Awesome Yuri! :) I will test the fix as soon as possible.

**Comment by yurikuzn** [comment]
We already tested.
