### ISSUE TITLE
custom checkAllResultMassActionList not working for (follow) action

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2814]
**Describe the bug**
We need to enable a follow massAction on checkAllResultMassActionList, based on documentation i have added the element to checkAllResultMassActionList on scope clientDefs, however the follow action still doesn't appear on the massAction list. when investigated i found that addMassAction method requires a second params true in order to display the item on the massAction Button. i have checked all and it seems that it should work if only a true boolean is added to the method here https://github.com/espocrm/espocrm/blob/9f9e2d75071b407225ce077398e7496c7f9cef56/client/src/views/record/list.js#L2178C40-L2178C40

**To Reproduce**
1. add "checkAllResultMassActionList": [
		"__APPEND__",
		"follow"
	]
to account clientDefs
2. rebuild and clear cache
3. go to accounts selectAll (the follow action is still not visible)
...

**Expected behavior**
Based on code the follow button should be added to the massAction button list item when added to the clientDefs checkAllResultMassActionList

**Screenshots**

**EspoCRM version**
version 7.5

**Additional context**

**Comment by yurikuzn** [comment]
This should not be considered as a bug.

**Comment by yurikuzn** [comment]
You can create any other action, with 'Follow' translation label.

**Comment by rabiibrahimi** [comment]
> You can create any other action, with 'Follow' translation label.
sorry i didn't get your point. i just want the follow action to be added when checking all result (selectAll records).

**Comment by yurikuzn** [comment]
There's no functionality to customize existing actions. The only possible option I see is to use another action.

**Comment by yurikuzn** [comment]
It's how it was implemented. Follow as any other standard action are not compatible with custom actions lists.

**Comment by yurikuzn** [comment]
> My purpose is not to customise the action itself but just to add it to the actionlist button when all records are selected.

There is no such functionality.

**Comment by rabiibrahimi** [comment]
is there anyway to add by default the follow action to the actionList button when all records are selected, currently follow action will appear on the actionlist button only when certain records selected.

**Comment by yurikuzn** [comment]
I don't remember why we didn't add the Follow for select-all. Anyway, v8.1 will be available not soon, v8.0 is frozen for new stuff. I suggest a custom action, it's a few minutes of metadata coding.

**Comment by rabiibrahimi** [comment]
sure i will go with a custom action. hope this will be added in future if you think it won't cause issues. 
Thanks

**Comment by yurikuzn** [comment]
We'll look when once we are on v8.1 milestone.

**Comment by yurikuzn** [comment]
One of possible issues: a user can significantly  load the server by making one Mass Follow request. This action is not controlled by 'Mass-Update' permission, so any user with Stream access level can do it.

**Comment by rabiibrahimi** [comment]
> One of possible issues: a user can significantly load the server by making one Mass Follow request. This action is not controlled by 'Mass-Update' permission, so any user with Stream access level can do it.

make sense
