### ISSUE TITLE
Email from another EspoCRM system will not import

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2816]
**Describe the bug**
A customer uses EspoCRM and the emails they send us are not read in to our system and ours are not being read in to theirs.

Problem appears to be from this code in application\Espo\Core\Mail\Importer.php 

            if (stripos($messageId, '@espo-system') !== false) {
                return null;
            }

This check is only checking that an espocrm was the source of the email not that it has already been read in to this system.

**To Reproduce**
1. Setup personal/group email to read emails in to the system
2. Send an email from another espocrm system to this email
3. Email not imported

**Expected behavior**
Email should import

**Comment by yurikuzn** [comment]
It's known issue and not considered as a bug. Only system emails (notifications) are not imported. This logic improves security significantly.

Maybe in the future we will use instance specific suffix.

**Comment by yurikuzn** [comment]
Only system emails should not be imported IIRC. It's a security measure. Regular emails should be imported as they should not have `-system` prefix.

**Comment by yurikuzn** [comment]
Are you sure regular emails are not imported? I don't see any logic that should prevent them from importing.

**Comment by yurikuzn** [comment]
Just tested. An email sent from one CRM is imported by another CRM. False bug report.

**Comment by boydle** [comment]
Hi Yuri,
It is system emails as you say, user related links are what have been the issue.

**Comment by yurikuzn** [comment]
> user related links 

Do you mean stream notes?

**Comment by yurikuzn** [comment]
From code I see, not imported by another CRM and not re-imported by the same CRM:

* Notifications
* Password recovery

**Comment by boydle** [comment]
Password change links. its ok not a bug. My misunderstanding.

**Comment by yurikuzn** [comment]
Having explicit and actual steps to reproduce is quite important.
