### ISSUE TITLE
Kanban view - kanban field readOnly not applied

### ISSUE THREAD

**Issue by boydle** [espocrm/espocrm#2817]
**Describe the bug**
When a field used for Kanban is has readOnly = true, UI shows MoveOver menu and allows drag and drop.

**To Reproduce**
Explicit steps to reproduce the behavior:
1. Make opportunity stage field readOnly
2. Go to opportunity and change to kanban mode
3. Drag and drop items between stages
4. Use Move Over menu to change stage
5. Refresh records
6. records have not been updated

**Expected behavior**
Drag and drop should be disabled if field is readOnly
Move Over menu option should not be shown if field is readOnly
It would probably also make sense to remove the + create in each row of the Kanban as the field would not be saved with the default value given when creating like this.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/7907518/12e6e4b5-fa62-4881-8f6a-aab8d2c285d1)

**EspoCRM version**
Latest (demo.espocrm.com)

**Additional context**
view file: views/record/kanban

has this check to see if field/record is readOnly, it is missing a check on the readOnly property of the field itself.
            if (
                this.getAcl().checkScope(this.entityType, 'edit') &&
                !~this.getAcl().getScopeForbiddenFieldList(this.entityType, 'edit').indexOf(this.statusField) &&
                !this.getMetadata().get(['clientDefs', this.scope, 'editDisabled'])
            ) {
                this.statusFieldIsEditable = true;
            } else {
                this.statusFieldIsEditable = false;
            }

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/c6a2622744693c84d7a1b8561c120bbb461f6201
