### ISSUE TITLE
Wysiwyg in email template introduces additional <br/> for invisible new lines

### ISSUE THREAD

**Issue by alexandru-bagu** [espocrm/espocrm#2821]
In our use case we ended up with a wysiwyg field that had new lines that were not converted to <br/> upon copy paste. The field looked correct however, formatting wise everything was where it should have been.

When this field was referenced in an email template, however, the invisible new lines were converted to <br/> tags and so everything looked wrong.

Our solution was to allow wysiwyg html to be unchanged when copied to the template.
Along with this issue I am pushing a pull request with our solution.

**Comment by yurikuzn** [comment]
Needed steps to reproduce. We do have them in the Bug Report issue template. I tried to reproduce but it worked fine for me.

**Comment by yurikuzn** [comment]
I'll be able to merge your PR but we require CLA for the first PR.
