### ISSUE TITLE
GPS Cordinates

### ISSUE THREAD

**Issue by AjGaht** [espocrm/espocrm#2825]
The google maps integration on the EspoCRM is an awesome feature.
However I'm trying to create a GPS button through which a user can click and their GPS cordinates are acquired automatically and saved in a field called locationCordinates in the Opportunity entity. The locationCordinates will be related to the address so that it can show the location on maps. I have tried a couple of formulae in the sandbox but I'm unable to achieve the same. 

I'm open and I deeply appreciate any support and assistance.
Thanks.

**Comment by Kharg** [comment]
I think that Map Plus from @eymen-elkum can do this.
https://www.eblasoft.com.tr/espocrm-extension-page/espocrm-map-extension

**Comment by eymen-elkum** [comment]
Thank you @Kharg for the notice, 

Yes that extension helps, but there is another extension more light named "Ebla Location", 
I will do my best to share it on the site asap, and will announce it here when published

**Comment by AjGaht** [comment]
I am trying to implement a custom solution through EspoCRM sandbox formulae. Here is my code,
var apiKey = 'Google APi ******';

var address = getField('address'); 

var apiUrl = 'https://maps.googleapis.com/maps/api/geocode/json?address=' + encodeURIComponent(address) + '&key=' + apiKey;

httpClient.get(apiUrl).then(function(response) {
    var data = JSON.parse(response.getBody());
    
    if (data.status === 'OK') {
        var location = data.results[0].geometry.location;
        var latitude = location.lat;
        var longitude = location.lng;

        set('gpsCoordinates', latitude + ',' + longitude);
    } else {
        logger.error('Geocoding API error: ' + data.status);
    }
}).catch(function(error) {
    logger.error('Error fetching data: ' + error);
});

Currently not working, for sure i need to make changes, kindly help..
