### ISSUE TITLE
Jobs running in-parallel processes not working in PHP 8.1.22, 8.2.9 (exclusively)

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2828]
After three hours of debugging, I found that the latest PHP patch versions 8.1.22 and 8.2.9, which many people use, have a changed way of getting the PID after SIGCHLD (see https://github.com/php/php-src/pull/11509). This change is reverted in the PHP development branch (https://github.com/php/php-src/pull/11863).

This causes asynchronous jobs to not be marked as complete and cron.php to run indefinitely. When used with a daemon, this causes cron to stop completely as all `daemonMaxProcessNumber` processes are stuck.

The developers of spatie/async were quick to react to this change, so you need to update the dependency to the latest version.

NOTE: This is the relevant fix, that new dependency version adds: 

https://github.com/spatie/async/blob/59985e70e94b8afb1ef1d65de73e8f80cddb4146/src/Pool.php#L323-L335

**Comment by yurikuzn** [comment]
Thanks for reporting. spatie/async is updated to 1.5.6 in v7.5.6.
