### ISSUE TITLE
assignedUser automatically set to current user when read only

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2829]
In a custom entity, the `assignedUser` field has been set to optional and read only. I expected the field to remain empty after creation because the user can't access it and it is marked as not required. However, the current user is automatically added to the record due to the read only setting. When read only is set to false, the current user is not added to the record.

The following entityDef configuration causes `assignedUser` to automatically be set to the current user.
```
"assignedUser": {
  ...       
  "required": false,
  "readOnly": true,
  ...
},
```

The following entityDef configuration causes `assignedUser` to remain unset, which is the desired behavior:
```
"assignedUser": {
  ...       
  "required": false,
  "readOnly": false,
  ...
},
```

The only way I have found to fix the behavior is to unset the `assignedUser` field in a hook:
```
  public function beforeSave(Entity $entity, array $options): void {
    if($entity->isNew()) {
      $entity->set(array(
        "assignedUserId" => NULL,
        "assignedUserName" => NULL,
      ));
    }
  }
```

It is common to create records in Espo that should not be assigned to anyone, so I will need to work around the behavior in almost every custom entity. Is there a way to fix this without hooks?

**Comment by yurikuzn** [comment]
There's is no way to do it globally. The value is set here: https://github.com/espocrm/espocrm/blob/7.5.6/application/Espo/Core/Record/Service.php#L591C35-L591C49. The value sent from the front-end does not have any effect as read-only fields are unset.

Instead of Hook  it's better to utilize API Before-Save script.

**Comment by bandtank** [comment]
Thank you. That helps a lot.
