### ISSUE TITLE
EMail attachment Indicator visible, but no attachments listed

### ISSUE THREAD

**Issue by githubkoma** [espocrm/espocrm#2830]
**Describe the bug**
We have some EMails in a IMAP Group Mail Account where we know Files are attached.
Such EMails show the attachment indicator, but when clicking on the icon its not listing any attachments.
And below the EMail no Attachments are listed either.
A few percent of our EMails are affected, rest are working fine. Dont know if this is only happening on having multiple attachments.

Please See Screenshot below

Is there anything we can provide for further troubleshooting?

**Expected behavior**
List every attachment on every email with attachment.

**Screenshots**
![Espo EMail Attachments](https://github.com/espocrm/espocrm/assets/5107805/406ae38b-66ee-4b44-bee5-af2d8242ed59)

**EspoCRM version**
Espo 7.5.5
PHP 8.2.8
Apache

**Comment by yurikuzn** [comment]
I checked a few dozens of real imported emails. Zero was affected. Here's the only place where the field is set: https://github.com/espocrm/espocrm/blob/7.5.6/application/Espo/Repositories/Email.php#L312.

Maybe attachments were removed manually by admin?

**Comment by yurikuzn** [comment]
It seems that the problem is happens because the attachment part has `Content-Disposition: inline` header.

What client/software was used to send/generate this email?

**Comment by yurikuzn** [comment]
Try to change the `role` from 'Inline Attachment' to 'Attachment' in database. Do attachments show up?

**Comment by githubkoma** [comment]
Yes, the attachments now show up!!

Is there a quick workaround and/or should we wait for an espo point release?

**Comment by yurikuzn** [comment]
Not yet. It's not a no-brainer fix.

**Comment by yurikuzn** [comment]
This fix should help: https://github.com/espocrm/espocrm/commit/a0695b492e5444ac9580e63c78b8159794bb41fe

**Comment by githubkoma** [comment]
Many Thanks!!
This is for future/new EMails only, not EMails that are already in the system, right?

**Comment by yurikuzn** [comment]
Right.

**Comment by yurikuzn** [comment]
You can run an SQL that changes all email entries where `role = 'Inline Attachment' AND parent_type = 'Email'`.
