### ISSUE TITLE
Integrating Trello like functionality in Espocrm but with opensource solutions

### ISSUE THREAD

**Issue by mrabino1** [espocrm/espocrm#2837]
With open-source solutions like https://github.com/plankanban/planka ... It would be wonderful to use Espocrm as the core install base and have solution like Planka built on-top-of instead of next-to Espocrm..  even as the integration of a card based model would take several iterations, the inbound-email-to-card .. or other such functionality would dovetail well with other espocrm functionality.

**Comment by yurikuzn** [comment]
There's the Kanban view in Espo.

**Comment by mrabino1** [comment]
Understood.. For what it is worth, the additional functionality w/in the cards in Planka would be nice to see in Espo.. labels.. dates.. check lists.. file attachments accessible in the card.. etc.. thx.

**Comment by yurikuzn** [comment]
I believe it's all available in Espo as well.

**Comment by mrabino1** [comment]
Without any tone of coming across as confrontational, respectfully, where my head is... is less about it being applied to the Opportunities.. but rather also expanding the core functionality by having a "Boards" Entity... such that users of the platform could use Espo as a place to create an infinite number of Boards (and invite other users)... each one having lists and cards... and as a result, all of the opportunites themselves could be linked to a collaborative Board (where actions / notes / files / labes / due dates / etc) can be housed... contacts could link to the board.. or a list in a board.. or a card in a list in a board... for example... as mentioned at the top, to have this functionality build on top of espo, not next to it, per se.

**Comment by RabeeBrahimi** [comment]
> Without any tone of coming across as confrontational, respectfully, where my head is... is less about it being applied to the Opportunities.. but rather also expanding the core functionality by having a "Boards" Entity... such that users of the platform could use Espo as a place to create an infinite number of Boards (and invite other users)... each one having lists and cards... and as a result, all of the opportunites themselves could be linked to a collaborative Board (where actions / notes / files / labes / due dates / etc) can be housed... contacts could link to the board.. or a list in a board.. or a card in a list in a board... for example... as mentioned at the top, to have this functionality build on top of espo, not next to it, per se.

That would be cool. Having ability to create multiple boards and multiple list for each entity in the system would improve the user experience. But i think that would require rewriting whole kanban logic i guess. But loved the functionalities on the planka app.
