### ISSUE TITLE
Dividers invisible deliberately. Otherwise, would take more vertical space to be balanced, work not nice with minimized mode, and I didn't like how it looked. In dropdown they are coherent with existing dropdown dividers.

### ISSUE THREAD

**Issue by sab0tajue** [espocrm/espocrm#2838]
I installed the divider but they are not visible in the drop-down list. Is this right or wrong?

<img width="454" alt="Снимок экрана 2023-09-11 в 17 49 03" src="https://github.com/espocrm/espocrm/assets/87798667/014c1e5a-8510-43b6-8d24-cf60551a2f42">

<img width="497" alt="Снимок экрана 2023-09-11 в 17 49 18" src="https://user-images.githubusercontent.com/87798667/267059093-d81dac21-0700-46b4-83e1-03a4d3c6dfac.png">
              Dividers invisible deliberately. Otherwise, would take more vertical space to be balanced, work not nice with minimized mode, and I didn't like how it looked. In dropdown they are coherent with existing dropdown dividers.

_Originally posted by @yurikuzn in https://github.com/espocrm/espocrm/issues/2780#issuecomment-1611083283_

**Comment by yurikuzn** [comment]
Dividers are not supported in dropdown lists.

**Comment by sab0tajue** [comment]
<img width="275" alt="Снимок экрана 2023-09-12 в 11 48 39" src="https://github.com/espocrm/espocrm/assets/87798667/f789ec8f-263e-4aff-a827-612c086db169">

And isn’t that what is meant? Screenshot is yours
