### ISSUE TITLE
The `prepare` method may cause a rendering problem in rare situations

### ISSUE THREAD

**Issue by mozkomor05** [espocrm/espocrm#2839]
Sometimes it is possible to get into situations where the `prepare` method is called, but is not followed by a re-render. This will cause particular problems if a nested view is created in `prepare` (as is the case with the time-ranges field, for example).

**Theoretical reproduction**
1. Have a client-read-only field that changes value during record editing (e.g. due to dyanmic handler)
2. Cancel editing
3. The following code undoes the changes to the model, but skips the re-render. 
https://github.com/espocrm/espocrm/blob/a20c3f14ace3d9ea266d52240ec32415c5724b9c/client/src/views/record/detail.js#L1656
4. As a result, only `prepare` is called, without subsequent re-rendering.

**Example**
1. Create a read-only test field with the following custom view: 
```js
define(["views/fields/varchar"], Dep => {
    return class extends Dep {
        readOnly = true;

        _template = '<div class="field">{{{myView}}}</div>';

        setup() {
            super.setup();

            // for the sake of simple test case
            window.triggerChange = () => {
                this.model.set('test', Math.random().toString(36).substring(2, 15));
            };
        }

        prepare() {
            return this.createView('myView', 'views/base', {
                templateContent: "Hello!",
                selector: '.field',
            });
        }
    };
});
```
4. Add it to the layout.
5. Create a new record and edit it.
![image](https://github.com/espocrm/espocrm/assets/44263817/2ad35e49-e0ea-4fb2-a6b2-d635ae7b9aab)
![image](https://github.com/espocrm/espocrm/assets/44263817/c9aa8bf5-c71d-4037-86ee-4d4e5105410b)

6. Call `window.triggerChange()` (used to simulate a real field value change during edit mode, can occur e.g. by dynamic handler)
![image](https://github.com/espocrm/espocrm/assets/44263817/da6d626a-0efa-4da7-bf74-91b28b874367)
7. Cancel the editation.
7. **Nested view `myView` will not render.** 
![image](https://github.com/espocrm/espocrm/assets/44263817/46e7aba4-6975-46d9-8645-394f4947f9b4)

**Proposed solution**
Do not call `prepare` in situations where it is unconditionally known in advance that a render cannot occur. This solution, in my opinion, is more general and may prevent more problems with `prepare` in the future.

**Comment by yurikuzn** [comment]
I was doing a custom field view with *createView* in *prepare* and run across another issue. If the field is reRendered between initialization and render, the first promise can be not resolved causing the view being not rendered. I added a fix for this.

The same issue if we call `prepare` manually in-between initialization and render. For this, I added `whenReady` method.

Usage example:

```js
setup() {
   this.someSetup();

    this.listenTo(this.model, 'change', () => {
        this.whenReady().then(() => {
            this.someSetup();

            this.whenReady()
                 .then(() => this.prepare())
                 .then(() => this.reRender())
        }); 
    });
}

prepare() {
     return this.createView('some', 'some/view');
}

someSetup() {}
```

Added `whenReady` and reRender fix: https://github.com/espocrm/espocrm/commit/6a6446d0b7b66b67960165afdf48c4761c1f27c4
