### ISSUE TITLE
If foreign link field is set to read only, new childs get no parent

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#2845]
If a foreign link field on a child is set readOnly, a new child created from the parent gets no parent set.

**How to reproduce**

* create 2 entities
* define a parent-child relation between these two entities
* on the child edit the foreign link field and set it "Read-only" --> "Field value can't be specified by user. But can be calculated by formula."
  intention: a parent association should not be modifiable (s. #2843)
* on the parent's layout add the parent as relation 
* create a new parent
* in the parent's child table view add (+) a new child
* nothing is shown in the parent's child table
* a new child has been created but without parent set

**Expected behavior**

A new child is beeing created, linked to the parent and listed in the parent's child table

**EspoCRM version**

tested on 7.4 - 8.0

As a work around on could define a form field validation:  
 Conditions making field read-only 
```
(
Parent Entity ≠ ∅
)
```

**Comment by hi-ko** [comment]
At least not expected from the admin users ;-)

as a compromise, the hint on the read-only checkbox should contain something like: If set on a link, a new linked entity will have an empty link.

**Comment by yurikuzn** [comment]
As EspoCRM is API based app, such issues are inevitable. The tooltip is only justifiable if shown only on link fields to prevent cognitive load with unnecessary information. Not sure if currently it's possible though.

**Comment by hi-ko** [comment]
my painpoint is that even an entity formula on the child will not get the parent's id but I get your point from the REST-API perspective that a user should not be able to set a value on that field.

**Comment by yurikuzn** [comment]
We will have the new param *readOnlyNotNew* that covers this issue.

**Comment by RabeeBrahimi** [comment]
would the same behavior happen if set through permission ? e.g a user with role for Case entity (Create - Read - Edit) if field level of account is set to read only when this user create a case from an account will the new case be linked or not ?

**Comment by yurikuzn** [comment]
Yes. Expected.

**Comment by RabeeBrahimi** [comment]
> We will have the new param _readOnlyNotNew_ that covers this issue.

so this will solve the issue. will this work for all field types including link right?

**Comment by yurikuzn** [comment]
BTW it was added to docs just a few hours ago: https://github.com/espocrm/documentation/commit/8089dff2d584e0301fd65d38f4d64499561ad864

**Comment by yurikuzn** [comment]
> will this work for all field types including link right?

It's not yet implemented. But expected for all types.

**Comment by hi-ko** [comment]
crazy - what a coincidence

**Comment by yurikuzn** [comment]
Maybe because if created an issue (which was in my backlog for long, but created only after added to the docs), and you've seen the issue and remembered the issue with relationships.

**Comment by hi-ko** [comment]
> When the read-only parameter is enabled for a *link* or *link-multiple* field, it won't be possible to create a related record from the relationship panel.

enhancement: If read-only parameter is enabled for a *link* or *link-multiple* field the relationship panel shoud not offer to add related records

**Comment by yurikuzn** [comment]
BTW if anybody has an idea for the parameter name rather than *readOnlyNotNew*, please suggest.

**Comment by yurikuzn** [comment]
> enhancement: If read-only parameter is enabled for a link or link-multiple field the relationship panel shoud not offer to add related records

I thought about it, but not sure whether we can have some special cases when it would not be desired.

**Comment by RabeeBrahimi** [comment]
> readOnlyNotNew

Why not have an explicit name like readOnlyAfterCreate

**Comment by Kharg** [comment]
> > readOnlyNotNew
> 
> 
> 
> Why not have an explicit name like readOnlyAfterCreate

I also think that readOnlyAfterCreate sounds good.

**Comment by hi-ko** [comment]
> I thought about it, but not sure whether we can have some special cases when it would not be desired.

readOnlyNotNew/readOnlyAfterCreate is the way to go. Personally, I find it difficult when errors are quietly ignored instead of throwing and from a REST perspective I would expect a bad request if providing data for a readOnly field. So readOnly means readOnly for REST but not for formular. Anyhow I understand the issue and there will be a solution 😉

**Comment by yurikuzn** [comment]
If we implemented error throwing for read-only fields there would be a strong backlash.

**Comment by hi-ko** [comment]
> If we implemented error throwing for read-only fields there would be a strong backlash. And it's technically impossible with all current codebase.

all good, only formally unexpected
