### ISSUE TITLE
Formulas in templates are not saved correctly

### ISSUE THREAD

**Issue by ChrisSka** [espocrm/espocrm#2851]
**Describe the bug**
I use formulas for arrays in PDF & email templates.
However, after saving, they are always saved outside of the array.

**To Reproduce**
Explicit steps to reproduce the behavior:
1. Creating the array query in the template
2. After saving, you can use the template, but if you edit it again, the query will always be over the array
3. It does not matter whether you copy the template or write it manually.

**Expected behavior**
That the template remains the way you save it

**Screenshots**
Before:
![before](https://github.com/espocrm/espocrm/assets/68166740/2f3a308e-bede-415c-8091-d592be8c84be)

After 1:
![after1](https://github.com/espocrm/espocrm/assets/68166740/1bc74219-645d-400e-a430-92c7e09a3401)

After 2:
![after2](https://github.com/espocrm/espocrm/assets/68166740/91a2f1cf-4b10-4796-91cd-a1d4ae11dfa0)

**EspoCRM version**
8.0.1

**Additional context**

**Comment by yurikuzn** [comment]
It's a limitation of contenteditable. It was covered many times on the forum and in the documentation.

**Comment by yurikuzn** [comment]
https://docs.espocrm.com/user-guide/printing-to-pdf/#each-iterator

![image](https://github.com/espocrm/espocrm/assets/1006792/cbb02263-36d3-4249-8bd6-23aaa9196b5c)
