### ISSUE TITLE
Teams not set to default values if field is read only

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2855]
Setting the Teams field to read only changes the behavior of the default assignments.
* If the Teams field is read only, no Teams are related to the entity after creation.
* If the Teams field is not read only, the teams in the default list are related to the entity after creation.

Here is an example of a Teams field that has a default team:
<img width="305" alt="image" src="https://github.com/espocrm/espocrm/assets/1170415/d77af68a-ca10-433a-89ea-99c03f9c0a07">

The Management team should be related to every record upon creation. Here is how the record looks when the entity is new and unsaved:

<img width="268" alt="image" src="https://github.com/espocrm/espocrm/assets/1170415/69e03c4c-240a-4ce2-8fb4-d68f180563c2">

This is what happens after the record has been saved:

<img width="265" alt="image" src="https://github.com/espocrm/espocrm/assets/1170415/d5000c43-f1cf-4a68-aa1b-1530143bc9a5">

This happens in a new instance of EspoCRM (Versions 7.5.6 and 8.0.2) with no hooks or scripts. The reason is seen [here](https://github.com/espocrm/espocrm/blob/9b788c3c2dc04bb4f123049b3bdef90c0f777451/application/Espo/Core/Record/Service.php#L602). In short, if the teams field is not editable, it is added to the forbiddenFieldList array, which causes the field to not be set. That is an unexpected behavior. To work around this, I force the relationship to exist in a hook, but it seems like the CRM should allow read-only fields to take default values.

I am slightly concerned by the logic of the defaultTeamId variable. It looks like the user's default team will override the entity's default value for the teams field, which is not what I would expect to happen.

My use case is to force all records of a certain type to be visible to managers. Users should not be allowed to modify the list of teams.

**Comment by yurikuzn** [comment]
> it is added to the forbiddenFieldList ... That is an unexpected behavior.

This is intentional, we won't change it.

The future readOnlyNotNew parameter will work for your use case https://github.com/espocrm/espocrm/issues/2843.

Before v8.1, you can use Dynamic Logic to set the field read-only if ID is not empty.

**Comment by yurikuzn** [comment]
This issue gets into details of almost the same problem https://github.com/espocrm/espocrm/issues/2845

**Comment by yurikuzn** [comment]
It seems that the root of this problem is deeper. When metadata is converted to ORM metadata, the default values is not carried over. I will look into and may be address this issue in v8.1.

**Comment by bandtank** [comment]
For anyone who needs to solve this, the following code works:

```
<?php

namespace Espo\Modules\Paragon\Hooks\PerformanceReport;

use Espo\ORM\Entity;

class PerformanceReportHook
{
  public function __construct(
    private \Espo\Modules\Paragon\Services\PerformanceReport $pfService,
    private \Espo\Core\Utils\Metadata $metadata,
  ) {}

  # do not allow managers to edit their own records
  public function beforeSave(Entity $entity, array $options = array()) {
    $this->pfService->processReport($entity);

    if($entity->isNew())
      $this->assignTeams($entity);
  }

  private function assignTeams(Entity $entity): void {
    $metadata = $this->metadata->get(['entityDefs', 'PerformanceReport', 'fields', 'teams', 'defaultAttributes']);
    $entity->set(array(
      "teamsIds" => $metadata["teamsIds"],
      "teamsNames" => $metadata["teamsNames"],
    ));
  }
}
```

**Comment by yurikuzn** [comment]
The simple Dynamic Logic should work. We often recommend this approach.

**Comment by bandtank** [comment]
> > it is added to the forbiddenFieldList ... That is an unexpected behavior.
> 
> This is intentional, we won't change it.
> 
> The future readOnlyNotNew parameter will work for your use case #2843.
> 
> Before v8.1, you can use Dynamic Logic to set the field read-only if ID is not empty.

For my use case, the field has to be read only from the beginning. No users should be able to access the field. The only two solutions I could think to implement were blocking the field in the ACL for all users of overriding the assignment in a hook. The latter solution is easier to maintain, at least for me.

**Comment by yurikuzn** [comment]
This fix solves the problem that default link-multiple value is populated when a new entity is created. https://github.com/espocrm/espocrm/commit/5282f01cda33ab17fa3ad62804010c935d55c679
