### ISSUE TITLE
Dynamic logic is inconsistent with filters

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2856]
**Describe the bug**
When using dynamic logic, in entity manager, field options. I have found that it is inconsistent with normal search filters and I believe the goal is for them to be consistent

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Set dynamic logic for a field. Example rule: Show field if `name` contains `Dynamic`
2. Create new record for the entity and name it `dynamic`
3. You can see, that the field won't show, as dynamic logic does not match the rule for `name` contains `Dynamic`
4. In list view of the entity, apply filter for name to contain word Dynamic / dynamic. You will see record showing either way, regardless of capitalization.

**Expected behavior**
Dynamic logic should not be case sensitive for `contains` rules.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/15276167/e400674e-b7f4-4179-807f-4cf1fb55702f)
![image](https://github.com/espocrm/espocrm/assets/15276167/ac805237-ab27-489f-a709-5e41841cb632)
![image](https://github.com/espocrm/espocrm/assets/15276167/3053ff09-b988-4c6d-ab4f-2b2a9210bb87)
![image](https://github.com/espocrm/espocrm/assets/15276167/25c9856b-e3b6-41ae-b3d4-6f3aedffa727)
![image](https://github.com/espocrm/espocrm/assets/15276167/32cc311e-5f38-4c33-820f-2e98aff918ef)

**EspoCRM version**
7.5.6

**Additional context**
-

**Comment by radek3911** [comment]
I have found workaround using regex I can use /dynamic/i

**Comment by yurikuzn** [comment]
This

**Comment by yurikuzn** [comment]
Dynamic logic supposed to work only on the detail view. Not a bug.

**Comment by yurikuzn** [comment]
It seems to me you misunderstood the dynamic logic. Is has nothing to to with filters and fetched records.

**Comment by radek3911** [comment]
The bug that I was trying to explain that dynamic logic has same rules as filter do, but it does not work the same way as filters.

If I have search filter for name contains 'dynamic' the search is case insensitive. However dynamic logic for name contains 'dynamic' is case sensitive. Anyways after submitting the issue I noticed I can use regex where I can use the case insensitive regex flag which makes this 'bug' no longer an issue and due to the fact that I can use regex I don't think this would be even worth fixing.

Thanks

**Comment by radek3911** [comment]
Of course regex does not work for rule 'contains' there is a separate type for regex (matches).
![image](https://github.com/espocrm/espocrm/assets/15276167/529c5b7f-1237-483e-a89f-060a38770e8c)
![image](https://github.com/espocrm/espocrm/assets/15276167/036deb5f-95a6-4080-916a-2c40c6b7fd80)

**Comment by yurikuzn** [comment]
It's not a bug.
