### ISSUE TITLE
Foreign field not being refreshed on link update

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2857]
**Describe the bug**
When using foreign fields, EspoCRM returns incorrect value after link gets updated with a PUT request. The foreign field has to be related to the linked entity that is being changed.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Relate 2 entities (ex. QuoteItem, Product)
2. Add a foreign field to entity QuoteItem referencing field from entity Product. 
3. Change related product on QuoteItem and observe PUT request response.
4. PUT request returns old value of a foreign field, instead of returning new value.

Example:
Entity QuoteItem has fields: name,product(relation),group(foreign field from product)
Entity Product has fields: name,group

Example product1:
- name: delivery services
- group: 100

Example product2:
- name: assembly services
- group: 200

Currently, QuoteItem has linked product `delivery services` and is displaying group 100 properly. Now we are going to change the product to `assembly services`.

PUT /QuoteItem/650b0b2edfd97531e
Request:
{"productId":"64d042345bf309de8","productName":"assembly services"}
(This request is sent by frontend and is correct)

Received response
{"productId":"64d042345bf309de8","productName":"assembly services","group":100}

Expected response:
{"productId":"64d042345bf309de8","productName":"assembly services","group":200}

**EspoCRM version**
7.5.6

**Screenshots**
1. Screenshot of PUT request where linked product gets updated. Previously linked product was from group 430, newly linked product is from group 410.
![image](https://github.com/espocrm/espocrm/assets/15276167/c7b0e0f9-f400-4058-b481-0e5ee5b299cf)
2. Response of PUT request
![image](https://github.com/espocrm/espocrm/assets/15276167/394b8bb8-1478-4719-ac17-c40082f9d588)
3. Response of GET request for the same entity after refreshing the page
![image](https://github.com/espocrm/espocrm/assets/15276167/1d517ef0-210e-4527-827c-f834c023a388)

**Additional context**
There is a workaround available that fixes this issue. You can make beforeSave hook that fetches correct group from product and sets it to quoteitem entity.

Please note that this only applies when you edit the linked field. After editing and refreshing page, correct group is displayed, however this is not ideal when you rely on correct group value (for example in case of dynamic logic).

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/63afa92fc177e7ce10706354b77a1ec635aa34ca
Test: https://github.com/espocrm/espocrm/commit/449d6a6fcd9169bd9c9b9cd4d59b59e452aae9b4
