### ISSUE TITLE
Mass Email/Campaigns - Feature request

### ISSUE THREAD

**Issue by Sakkhor909** [espocrm/espocrm#2858]
**Is your feature request related to a problem? Please describe.**
Mass emails are sent during the holidays.

**Describe the solution you'd like**
Ability to turn off mass emails for specific days like Saturday and Sunday.

**Comment by yurikuzn** [comment]
I believe you can configure weekdays using crontab notation for the scheduled job that send mass emails. You can also specify a specific date for a mass email.
