### ISSUE TITLE
LDAP authentication PHP Warnings

### ISSUE THREAD

**Issue by kboykov** [espocrm/espocrm#2859]
**Describe the bug**
I'm getting thousands of errors such as this one:
"[2023-09-26 05:03:44] WARNING: E_WARNING: Undefined array key "useStartTls" {"code":2,"message":"Undefined array key \"useStartTls\"","file":"/home/xxxxxx/public_html/application/Espo/Core/Authentication/Ldap/Utils.php","line":153} "

"[2023-09-26 05:03:41] WARNING: E_WARNING: Undefined array key "useSsl" {"code":2,"message":"Undefined array key \"useSsl\"","file":"/home/xxxxxx/public_html/application/Espo/Core/Authentication/Ldap/Utils.php","line":152} "

**To Reproduce**
Explicit steps to reproduce the behavior:
1. Enable LDAP authentication with AD
2. Try changing any of the LDAP security settings
3. LDAP authentication works flawlessly but generates an error everytime someone logs in.
...

**Expected behavior**
I expect the LDAP auth not to generate this kind of errors.

**Screenshots**
N/A

**EspoCRM version**
version 8.0.0, PHP 8.1.22, all mandatory extensions installed, all systemRequirements passed.

**Additional context**
N/A

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/25b0077adcd7ee9ecf488ab1c20407fa38288780

If you apply this fix manually, please let me know if everything fine.

**Comment by kboykov** [comment]
I applied the fix manually, cleared cache, rebuilded and the problem still persists. These particular errors first appeared 2-3 months ago.

**Comment by yurikuzn** [comment]
The same warning? It's unlikely. Maybe some different ones?

**Comment by kboykov** [comment]
Yup, 100% same errors. Bare in mind that I don't have any customizations regarding the authentication or LDAP. I have only applied this fix manually to check.

[2023-09-26 14:14:40] WARNING: E_WARNING: Undefined array key "useSsl" {"code":2,"message":"Undefined array key \"useSsl\"","file":"/home/xxxxx/public_html/application/Espo/Core/Authentication/Ldap/Utils.php","line":152} 
[2023-09-26 14:14:40] WARNING: E_WARNING: Undefined array key "useStartTls" {"code":2,"message":"Undefined array key \"useStartTls\"","file":"/home/xxxxx/public_html/application/Espo/Core/Authentication/Ldap/Utils.php","line":153}

**Comment by yurikuzn** [comment]
It's not possible. Warnings does not correspond to the updated file. You did not apply the fix.

**Comment by kboykov** [comment]
The problem is actually fixed. Since I'm using PHP Opcache/JIT and the changes have not reflected immediately on the CRM.

For the last 2 days no logs regarding the above mentioned problem occured.
