### ISSUE TITLE
Calendar: Wrong week displayed when refreshing or using date query parameter

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2860]
**Describe the bug**
Refreshing the page with the browser's refresh button when viewing the calendar in Week mode (single user and shared) causes the calendar to display the wrong week sometimes. The issue appears to be related to the `date` query parameter. The bug can also be seen if you enter a date directly into the URL as a query parameter, e.g. `&date=2023-09-10`.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
#### Pre-requisites:
Set the application's timezone to `America/Denver` and first day of the week to `Sunday`.

#### Reproducing the bug with the refresh button:
1. Go to the calendar
2. Set it to week mode
3. Scroll to September 17, which is a Sunday, using the arrow buttons at the top left of the calendar view.
4. As you scroll, be sure the `date` query parameter is updating to match the first day of the week. For example, when you scroll to the right to set the first column as September 17, the query parameter should be `&date=2023-09-17`. The page should look like this:
![image](https://github.com/espocrm/espocrm/assets/1170415/45c7ae26-fdd1-4cda-a03e-792dbfe54390)
and the URL should look like this: `http://espocrm-fork:8081/#Calendar/show/mode=agendaWeek&date=2023-09-17`
6. Scroll to the left by 1 week using the arrow. The query parameter should now be `&date=2023-09-10`. The page should look like this:
![image](https://github.com/espocrm/espocrm/assets/1170415/aba02d41-af0f-499b-8a69-7dd6c7de1d54)
and the URL should look like this: `http://espocrm-fork:8081/#Calendar/show/mode=agendaWeek&date=2023-09-10`
7. Refresh the page using the browser's refresh button. The calendar now looks like this:
![image](https://github.com/espocrm/espocrm/assets/1170415/ea6f885f-90f3-42f7-81b9-f67626b9ae51)
and the URL still looks like this: `http://espocrm-fork:8081/#Calendar/show/mode=agendaWeek&date=2023-09-10`

#### Reproducing the bug with the query parameter:
Instead of scrolling through the calendar, go directly to the first day of a week using the query parameter. In my case, this only happens when the date is a Sunday because the first day of the week is configured as Sunday. Entering a date that is a Saturday or Monday will cause the week to render correctly.

Entering this URL: `http://espocrm-fork:8081/#Calendar/show/mode=agendaWeek&date=2023-09-10`
Results in this view:
![image](https://github.com/espocrm/espocrm/assets/1170415/6ac4520c-a66e-483f-8092-97dad9c3e46c)

**Expected behavior**
I expect the calendar to load the correct week upon refresh and when a URL is entered with the `date` parameter set to the leftmost date of the week (in the first column).

**Screenshots**
See above.

**EspoCRM version**
This **does not happen** in 7.5.6.
This **does** happen in 8.0.2.

**Additional context**
I can reproduce this issue in a new instance of EspoCRM as well as instances with extension and customizations. My gut instinct is to say this is related to timezone conversions because it happens on the boundary of a week. The date in the parameter is probably in UTC while the displayed week is localized, which causes the week to render incorrectly.

**Comment by yurikuzn** [comment]
As we updated FullCalendar from v3 to v6 there was a lot of issues, it's almost completely the different lib. Any help with the fix appreciated. I will be able to look into tomorrow or later.

**Comment by bandtank** [comment]
I will look into this and let you know if I figure out the solution.

**Comment by bandtank** [comment]
This issue is due to moment converting a date in a timezone to the same timezone, which sets the date to the previous date. It happens at here: https://github.com/espocrm/espocrm/blob/9f38c016686ade37447f66a17cb20df7d3ff74b1/client/modules/crm/src/views/calendar/calendar.js#L835


With a timezone of `America/Denver`, here is a log statement that shows the problem:
```
datesSet: () => {
  let date = this.getDateTime().fromIso(this.calendar.getDate().toISOString());
  let m = moment(this.calendar.getDate());

  this.date = date;

  this.trigger('view', m.format('YYYY-MM-DD'), this.mode);
  console.log("datesSet", date, this.date, m.format('YYYY-MM-DD'), this.mode)
},
```
```
datesSet 2023-09-24 00:00 2023-09-24 00:00 2023-09-23 agendaWeek
```

**Comment by bandtank** [comment]
I believe I have found the problem. The `initialDate` parameter for FullCalendar is being set as a UTC date, which the calendar then changes in accordance with the supplied timezone. From [here](https://fullcalendar.io/docs/date-parsing), FullCalendar will apply the timezone automatically:
```
2018-06-01T12:30:00-05:00 — has a -05:00 UTC offset
2018-06-01T12:30:00Z — Z signifies 00:00 UTC offset
2018-06-01T12:30:00 — no UTC offset specified. parsing will depend on the [timeZone](https://fullcalendar.io/docs/timeZone)
2018-06-01 — no UTC offset specified. parsing will depend on the [timeZone](https://fullcalendar.io/docs/timeZone)
```

The [line of code](https://github.com/espocrm/espocrm/blob/9f38c016686ade37447f66a17cb20df7d3ff74b1/client/modules/crm/src/views/calendar/calendar.js#L1013C1-L1013C1) in question is as follows:
```
options.initialDate = moment.utc(this.date).toDate();
```
Changing it to this exhibits the correct behavior:
```
options.initialDate = this.date;
```

With that change and a parameter of `&date=2023-09-17`, the following dates are used during the fetch query:
```
America/Denver: 2023-09-17 06:00 2023-09-24 06:00
Australia/Perth: 2023-09-16 16:00 2023-09-23 16:00
```

**Comment by yurikuzn** [comment]
Thanks for the fix. I applied it separately to the fix branch https://github.com/espocrm/espocrm/commit/8bce12aca3f50fef339b7d8c9ecb24f7b13d5129.
