### ISSUE TITLE
Website unreachable with Italian IP address

### ISSUE THREAD

**Issue by svtcpx** [espocrm/espocrm#2867]
Hello there,

sorry if this is not the right place to post it but since your entire websie and forum infrastrucure seems to be unreachable unless I use a VPN?  Maybe take a look at that. I'd love to read some documentation, as I'm sure others in Italy would too :)

Best Regards,
SVT

**Comment by arkadywtf** [comment]
Not the owner, but you sure the issue is not on your end? I was able to connect without any problems using an Italian IP address. The documentation is hosted on GitHub, so you can use this repository in the meantime: https://github.com/espocrm/documentation

**Comment by Kharg** [comment]
I am able to access everything correctly with my Italian IP Address.

**Comment by svtcpx** [comment]
Good to hear it's not an issue for anyone else! I have no problems connecting to any other website though, just this one so that seemed a bit odd. Thanks for the quick responses.

**Comment by yurikuzn** [comment]
It's might be a DNS issue. Not related to this repository.
