### ISSUE TITLE
Display any Entity with Date or Date-Time fields in calendar plus Outlook & Google extensions

### ISSUE THREAD

**Issue by hunterwebsiteservices** [espocrm/espocrm#2871]
**Is your feature request related to a problem? Please describe.**
We have follow up dates for Cases which are Date fields. We have a custom filter in the Dashboard to show Cases with a follow up date of today (or earlier). But it doesn't allow for much flexibility.

With the ability to have these show in the built in Calendar, as well as Outlook and Google extensions (which sync to calendars). This creates a huge amount of flexibility for data display.

For example, it would be nice for contractors to be able to use their own calendar they like to use on their phone. And have EspoCRM Cases which are due appear in those calendars.

At the moment only Tasks, Calls and Meetings display. If you add a Date or Date-Time custom field to any other Entity they will not appear. This is what would be great to update. Make it so any Entity with Date or Date-Time appear in the calendar.

**Describe the solution you'd like**
As per title. If an Entity has either Date or Date-Time custom field, have it display in the Calendar. As well as in the Outlook and Google extensions.

**Describe alternatives you've considered**
There is no alternative, other than to manually add a Task to each Case with the date. This is very cumbersome. To the point it's not a real alternative.

Another alternative is to create a custom Entity. But we are using Cases as Cases (to our knowledge). Why create a new entity. Cases are working as we like (except this one feature).

**Comment by yurikuzn** [comment]
There's a workaround. You can convert your entity to event/calendar. You will need dateStart, dateEnd fields. You can fill only one field (e.g. dateEnd).

https://github.com/espocrm/espocrm/blob/8.0.2/application/Espo/Modules/Crm/Resources/metadata/scopes/Meeting.json#L12

Regarding extensions. It's unlikely to be implemented.

**Comment by yurikuzn** [comment]
Another workaround, is automatically to create a task on a follow-up date (using formula or workflow).

**Comment by hunterwebsiteservices** [comment]
> There's a workaround. You can convert your entity to event/calendar. You will need dateStart, dateEnd fields. You can fill only one field (e.g. dateEnd).
> 
> https://github.com/espocrm/espocrm/blob/8.0.2/application/Espo/Modules/Crm/Resources/metadata/scopes/Meeting.json#L12
> 
> Regarding extensions. It's unlikely to be implemented.

Is it really that easy? Thank you. But doing this won't have it appear in Outlook extension correct?

**Comment by yurikuzn** [comment]
> But doing this won't have it appear in Outlook extension correct?

I'm not sure. Maybe yes, maybe some additional actions will be needed.
