### ISSUE TITLE
New entities created with only a controller in PHP; no service, repository, entity, etc.

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2873]
**Describe the bug**
It looks like 8.0 added [entityTemplates](https://docs.espocrm.com/development/metadata/app-entity-templates/), which are supposed to assist with the creation of entities [based on type](https://docs.espocrm.com/development/metadata/app-entity-template-list/) (base, base plus, etc.).

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Use V8.0.0 or later
2. Create a new entity called `Topic` in the Entity Manager through the GUI
3. Inspect the files in `custom/Espo/Custom` to see that only a controller has been created

**Expected behavior**
I was expecting to see:
* `Controllers/Topic.php`
* `Entities/Topic.php`
* `Repositories/Topic.php`
* `Services/Topic.php`

However, only `Controllers/Topic.php` was created.

As an aside, the following json files were also created, which is consistent with my past experience:
* `Resources/i18n/en_US/Topic.json`
* `Resources/metadata/clientDefs/Topic.json`
* `Resources/metadata/clientDefs/Topic.json`
* `Resources/metadata/entityDefs/Topic.json`
* `Resources/metadata/recordsDefs/Topic.json`
* `Resources/metadata/scopes/Topic.json`

**EspoCRM version**
V8.0.0 or later

**Additional context**
After reviewing the [code](https://github.com/espocrm/espocrm/blob/8c54ca43f0e3598dfffb38c94780bb88d1798884/application/Espo/Tools/EntityManager/EntityManager.php#L78) in `application/Espo/Tools/EntityManager/EntityManager.php`, I do not see a call to the template to create new files. Is this intentional? Is the controller the only file that should exist for a new entity of type `base`?

**Comment by yurikuzn** [comment]
It's intentional.

**Comment by bandtank** [comment]
Ok, sounds good. Thanks. Is it fine for the developer to create the files if they are needed? For example, `Entities/Topic.php` may be needed so I can use `Topic::ENTITY_TYPE` in code. Will Espo still use the file if it is created manually?

**Comment by rabiibrahimi** [comment]
yeah you can create the files manually, i always do that so i could defined setters and getters on the Entities/MyEntity.php

You can even create you own template if you want to and it will be merged if you added everything correctly. i have used in many project a hybride entity template BasePlusEvent which is composed of both base plus and event.

**Comment by bandtank** [comment]
That did not work for me. I added this file:
```
{
  "Base": {
      "entityClassName": "Espo\\Core\\Templates\\Entities\\Base"
  },
  "BasePlus": {
      "entityClassName": "Espo\\Core\\Templates\\Entities\\BasePlus"
  },
  "Event": {
      "entityClassName": "Espo\\Core\\Templates\\Entities\\Event"
  },
  "Person": {
      "entityClassName": "Espo\\Core\\Templates\\Entities\\Person"
  },
  "Company": {
      "entityClassName": "Espo\\Core\\Templates\\Entities\\Company"
  }
}
```
and then created a new entity `Base` entity called `Test`. Only a controller was created. I cleared the cache after adding the `entityTemplates.json` file to `custom/Espo/Custom/Resources/metadata/app/`.

**Comment by yurikuzn** [comment]
Everything in Espo works fine as it was designed. You shouldn't create `entityTemplates.json`. Here's entity class provider https://github.com/espocrm/espocrm/blob/8.0.3/application/Espo/Core/ORM/ClassNameProvider.php#L87.

Just create an entity class and clear cache.

**Comment by yurikuzn** [comment]
We JSON schema it's also easy to create entities manually. I do it manually. All classes fields, layouts, language.

**Comment by yurikuzn** [comment]
This file is used. By the class provider in linked above. It has nothing to do what is created by Entity Manager Tool.

**Comment by yurikuzn** [comment]
Whenever I want quickly check where in codebase something is used I press Ctrl + Shift + F (in PhpStorm), paste the name (e.g. `repositoryClassName`) and it finds all occurrences instantly.
