### ISSUE TITLE
Lead Capture Improvements

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2874]
**Is your feature request related to a problem? Please describe.**
Online forms don't always send the data in the root of the request, so they are not compatible with EspoCRM out of the box

**Describe the solution you'd like**
I'd like two improvements to the lead capture:
- Field to choose the json path of the data (some forms put data inside another path, so the json path would be .formdata instead of being just root.
- log all requests to the lead capture url (so debugging is easier, instead of using external tools you can see the request and the path of the data you need)

**Describe alternatives you've considered**
For this issue I usually build external php scripts where I then send a new request to my Lead Capture after gathering the data I need in the correct path.

**Additional context**

**Comment by yurikuzn** [comment]
Not able to review feature requests due high work load.

**Comment by yurikuzn** [comment]
Can't tackle this for nearest months or more.

**Comment by yurikuzn** [comment]
For custom payloads, I think it's possible to do it with a custom controller action. Take a payload and modify it to a needed one before passing to the service.
