### ISSUE TITLE
Custom EmailTemplate placeholders

### ISSUE THREAD

**Issue by DrWarpMan** [espocrm/espocrm#2875]
**Is your feature request related to a problem? Please describe.**
I am unable to use **{siteUrl}** placeholder inside an **EmailTemplate**, because it does not exist.

**Describe the solution you'd like**
I would like to be able to use **{siteUrl}** within EmailTemplates to create custom links with EspoCRM instance URL.
In the best scenario I would like to be able to define my own placeholders  (created/processed via backend).

**Describe alternatives you've considered**
I found out, that `Resources/metadata/clientDefs/EmailTemplate.json` has a configurable `placeholderList` parameter, unfortunately that is completely useless, since it's not actually doing anything, but showing the available placeholders and their descriptions.
![image](https://github.com/espocrm/espocrm/assets/36279265/97f88a82-b770-4a8e-b1f5-a79fb65557d9)

If I am not mistaken, the built-in placeholders are hardcoded within the [EmailTemplate processor](https://github.com/espocrm/espocrm/blob/master/application/Espo/Tools/EmailTemplate/Processor.php#L302).

**Comment by mozkomor05** [comment]
This feature would be very useful. I had to implement custom parameters via my own processor implementation which I injected via binding. A logic to make defining custom parameters easier would be appreciated.

**Comment by yurikuzn** [comment]
Do you mean you would like having a backend interface for a placeholder. Like:

```php
class MyPlaceholder implements Placeholder
{
    public function get(Entity $entity, Data $data): string
    {
        return 'some-value';   
    }  
}
```

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/6d1d38c4af26c719436ec6ccba1227d7d29dfee4. [Docs](https://github.com/espocrm/documentation/blob/master/docs/development/metadata/app-email-template.md).
