### ISSUE TITLE
Scroll location reset when entering custom configuration panels

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2876]
**Describe the bug**
The scroll position in the Administration page is not consistently applied when moving in and out of configuration subpages. NOTE: This behavior is new as of 8.0.0. I cannot reproduce the behavior in 7.5.6.

Moving in and out of configuration pages causes the scroll position to change. I noticed the back button in the browser seems to work more often than the back button on my mouse. Going in and out of custom configuration pages (e.g., following [this guide](https://docs.espocrm.com/development/custom-config-parameters/)) almost never results in a saved scroll position.

I have been trying to reproduce the issue for almost 30 minutes. The behavior changes depending on how I click back (browser button, command+left arrow on a mac, or the back button on my mouse). When clicking on default EspoCRM configuration pages, sometimes the scroll position resets and sometimes it doesn't. When clicking on custom configuration pages, the scroll position always resets.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Create a custom configuration panel (`MyCustomPanel`) and at least one subpage (`FirstCustomPage`).

1. Size the browser window to be smaller than the length of the administration page. Some of the links to subpages must require scrolling down.
2. Scroll until the `Data->Import` subpage is visible. Note the position of the link on the page. 
3. Click on the `Import` link.
4. Click the back button. The link to the `Import` page should be in the same place (usually, but not always).
5. Click the link to a custom configuration subpage, e.g. `CustomPanel->FirstRow`. You should move into a custom configuration page.
6. Click the back button again. The scroll position is now reset and the `CustomPanel->FirstCustomPage` link is no longer visible.

**Expected behavior**
I expect the browser to return to the same position in the viewport when moving back and forth between menus. Clicking on a link and then hitting the back button should not reset the scroll position.

**Screenshots**
[Here is a link](https://pseglobal3-my.sharepoint.com/:v:/g/personal/anthony_pseglobal_com/ESXvrdhkQzBJvQCitXRoeNgBfpNVV8d_qiCxMJe8Y8qmDw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=cz2gY2) to a video. In the video, the scroll position is correct when I click the back button for the first time, but it is incorrect when I click the back button on all subsequent clicks. Clicking back from a custom configuration page results in an incorrect scroll position every time.

**EspoCRM version**
8.0.3
The behavior is not observable in 7.5.6.

**Additional Context**
I was not able to find a setting for this in local storage or cookies. It seems to be internal to Javascript, so I am not sure where to look.

**Comment by bandtank** [comment]
I am updating the bug report. I noticed after creating the bug report that the behavior changes with default configuration pages if you use the back button in the browser or the back button on a mouse.

**Comment by yurikuzn** [comment]
I didn't happen to me, at least I never noticed.

**Comment by yurikuzn** [comment]
I can reproduce when clicking back end forth. But I wouldn't have bothered about it. It's too minor issue, but the fix can be not that trivial to work reliable w/o breaking something else. I cannot look soon as having lot of other important work. If one can come up with an easy reliable fix we will appreciate.

**Comment by yurikuzn** [comment]
This fix should help for custom views: https://github.com/espocrm/espocrm/commit/73753b364e3d6d000b8b26ef723e5d731056d6c3
