### ISSUE TITLE
Reminder without options on Detail Layout

### ISSUE THREAD

**Issue by fabiomorais99** [espocrm/espocrm#2877]
**Describe the bug**
The options to reminder fields does not apper to select on Call and meeting entities. This appends on Call and Meetings entities.
When we create on small detail layout it is ok.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Open form to create entity and try to put an Reminder.

**Expected behavior**
This appends on Call and Meetings entities.
When we create on small detail layout it is ok.

**Screenshots**
Bug on Detail layout NOK
![image](https://github.com/espocrm/espocrm/assets/6087482/8d685f9b-4cb3-4529-b198-5512cbcdb503)

Small layout OK

![image](https://github.com/espocrm/espocrm/assets/6087482/549c2adf-2fd0-4832-9ef3-2494f378f54b)

**EspoCRM version**
8.0.3

**Additional context**

**Comment by yurikuzn** [comment]
Not a bug. It displays only options which represent future time. Date Start + reminder should be in future.
