### ISSUE TITLE
Maintenance mode error is not translated during page refresh

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2879]
**Describe the bug**
When the application is in maintenance mode, the user sees a translated message when performing actions. However, if the page is refreshed, the error message is not translated or formatted correctly. The message the user sees when clicking on buttons in the application looks like an intentional error message. The message the user sees after a page refresh looks like a real error with the application instead of a notice about maintenance mode.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
1. Put the application in maintenance mode
2. Log in as a regular user
3. Click buttons to see the regular maintenance mode message
4. Refresh the page to see an incorrectly formatted maintenance mode message

**Expected behavior**
I expect to see the same message with the same formatting and translation regardless of how I interact with the page.

**Screenshots**
What the user sees when clicking on a button in the application:
![image](https://github.com/espocrm/espocrm/assets/1170415/fd52bad7-a6bb-43d2-9f4a-e2c1767bcb3f)

What the user sees after a page refresh:
![image](https://github.com/espocrm/espocrm/assets/1170415/aacf82a4-cb80-43a7-a4f7-89dc16abf8ea)

**EspoCRM version**
8.0.2

**Additional context**
[Here](https://pseglobal3-my.sharepoint.com/:v:/g/personal/anthony_pseglobal_com/EddFm1yaqJZFk5Bm9mb2MnkB5USs-AS6qMn4NsIe-EGeAg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=Fzq4Li) is a video of the issue.

**Comment by yurikuzn** [comment]
Fixed with this: https://github.com/espocrm/espocrm/commit/94ffa77f908899d26c842c716eb0f062badb216f
