### ISSUE TITLE
Formula: Suppor empty path in `json\retrieve`

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2880]
Will parse the whole JSON.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/33e7f4e3efbc1bfe53d55ded333770e2f0c95852

**Comment by rabiibrahimi** [comment]
any chance of adding **json_decode** to the functions. It is useful when dealing with retrived json, e.g if the json data is nested collections and want to loop through the collection and do some sort of count of items in each collection etc.

**Comment by yurikuzn** [comment]
Actually, this change is about this. "Will parse the whole JSON.".
