### ISSUE TITLE
Capture BCC address on incoming emails

### ISSUE THREAD

**Issue by averymd** [espocrm/espocrm#2884]
**Is your feature request related to a problem? Please describe.**
If EspoCRM is BCC'd on an incoming email, the BCC address is not captured in the database. This limits the ability to write certain kinds of integrations that want to see that address.

**Describe the solution you'd like**
I would like to be able to query the Email API or the `email_email_address` table and see BCC address for incoming emails. Currently the only `address_type`s captured are To, CC, and ReplyTo. 

**Describe alternatives you've considered**
Not much alternative if the data just isn't there.

**Additional context**
The context for this is a custom integration that checks for new incoming emails with a Case/Opportunity/etc. indicated in either the To or BCC fields. For example, if "espo@example.com" is the address EspoCRM is configured to check via IMAP, then emails either forwarded to or BCC'd to espo+case1234abcd@example.com would get their Parent set to the Case with an ID of 1234abcd. This integration works great, but requires me to manually modify EspoCRM code. (And re-modify after some updates.)

The (probably clumsy) modification I make is to the file `application/Espo/Core/Mail/Importer.php` around [line 165](https://github.com/espocrm/espocrm/blob/67ecb7b73f3b0e29eed3251cd767fd22607dc286/application/Espo/Core/Mail/Importer.php#L165):

````
$email->setReplyToAddressList($replyToArr); // unchanged, just for context

if ($parser->hasHeader($message, 'X-Original-Delivered-to')) {
  $bccData = $parser->getHeader($message, 'X-Original-Delivered-to');

  if ($bccData && !in_array($bccData, $toArr) && !in_array($bccData, $ccArr)) {
    $email->addBccAddress($bccData);
  }
}

$addressNameMap = $parser->getAddressNameMap($message); // unchanged, just for context
 ````

The `addBccAddress()` method already exists in the Email entity; it just needs to be called. I don't know if the original `BCC` field would show in the headers for most people; I have a non-trivial email setup involving SpamHero and some routing by Fastmail, and `X-Original-Delivered-to` always seems to exist and be correct.

Once that BCC address is added, the value pops right up in the database and API for use by downstream integrations.

**Comment by yurikuzn** [comment]
There's an issue with this. BCC is supposed to be invisible for a recipient. In Espo, we have a single record per email Message-ID. If an email is sent to multiple people who are Espo users, there will only one email record in Espo. If we stored BCC, all users would be able to see all other recipients.

**Comment by yurikuzn** [comment]
The BCC field would be not a right choice also because an email can be forwarded to another address, having the address in the BCC would be misleading.

Another issue, that *Delivered-To*, *X-Delivered-To*, *X-Original-Delivered-To* are not standard headers. We would need to figure out what and how to use them to support majority of SMTP implementations.

Maybe we just could end up with the ability to add a custom code, so developers could handle it as they need. It's already should be possible to bind an extended Importer class and do a custom manipulations with an email. I'll consider adding an *Importer* interface to have it more easier to customize.

**Comment by averymd** [comment]
I can see why the BCC field wouldn't be a great option in a general sense. It'd be nice if however the data is captured, it doesn't require non-Espo users to see the funky email addresses in use, which is why I'm using the BCC field on the email side.

**Comment by yurikuzn** [comment]
[Added](https://github.com/espocrm/espocrm/commit/07c223e521a3656f40194d52a22ee9f262716812) *Importer* interface.

One can bind a custom one in custom binding.

```php
class MyCustomImporter implements Importer
{    
    public function __construct(
        private DefaultImporter $defaultImporter
    ) {}

    public function import(Message $message, Data $data): ?Email
    {
        $email = $this->defaultImporter->import($message, $data);
        
        if (!$emal) {
            return null;
        }

        // Do something.
 
        return $email;
    }
}
```
