### ISSUE TITLE
Not copying status field on record duplicate

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2885]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/b1d2795347bf1255d03871e2076771e8578edd38

**Comment by boydle** [comment]
This appears to affect all entities not just Meeting. I would suggest adding the duplicate ignore property to the UI in field manager so it can be controlled on a case by case basis would allow more flexibity for both status field and for any other field that may need to be prevented from duplication.
