### ISSUE TITLE
Customization of core JS files in safe upgrade way

### ISSUE THREAD

**Issue by traien** [espocrm/espocrm#2890]
**Is your feature request related to a problem? Please describe.**
I've encountered a specific issue within the EspoCRM that necessitates making changes to core JavaScript files. And we need to customize certain aspects to better suit our needs.

**Describe the solution you'd like**
I would like to propose making changes to the following JavaScript files:

- `views/fields/base.js`: We need to modify this file to implement changes that apply to all fields by default. These changes include altering the default behavior, appearance, or functionality of fields to meet our project's specific requirements.
For example: change the CSS classes for each edit/view modes.

- `views/modals/edit.js`, `views/modals/detail`: We need to modify those files to implement global changes.
For example: apply custom filter to all modals.

**Additional context**
Previously we were using extender to extend `define` function to add our customization into core files, after EspoCRM 8, it is not working because of transpile/bundle, is there a proper method to do this in safe upgrade way?

**Comment by yurikuzn** [comment]
It's unlikely we will ever have an official way to customize any core JS module/view. It would be an excessive burden for product development. Maybe it can be monkey patched somehow? What if you require a needed JS module and then apply some monkey patch a to JS class/function?

**Comment by yurikuzn** [comment]
```js
const defaultSetup = BaseFieldView.prototype.setup;

BaseFieldView.prototype.setup = function () {
    defaultSetup.call(this);

    console.log('custom setup', this.name);
};
```
Should be initialized in a custom script file (app > client > scriptList). Wrap into an AMD module. I believe this work. Though I wouldn't recommend using it.

**Comment by traien** [comment]
OK, thank you, I will give it a try

**Comment by yurikuzn** [comment]
Explaining for those who upset that we cannot have an official way to patch core JS files. Any change in such files is a potential BC break. In software development we usually have sort of contract that describe what can be extended what can not, by means of interfaces, public methods, docs. By following the rules, your customization is supposed to be future proof, at least until the major release. If one want us to take a burden of officially support monkey patching, I suggest to invest a few mil so we have a resource to support it (at least pretending we support, as it would be impossible).
