### ISSUE TITLE
Ability to hide/show columns on the list view

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2891]
The ability to hide/show specific columns on the main list view. Some fields can be set as hidden by default in the layout manager, and then can be shown by a user. The ability to reset to default.

![image](https://github.com/espocrm/espocrm/assets/1006792/2c86bb37-e6c3-42f3-9db3-243f26060016)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f64eb866d51f3df4ec8c86f9b3d36d24f0ad2c17 + a few further commit.

**Comment by Kharg** [comment]
Can this be disabled per entity? Or can we get a setting to do so in the entity's metadata? :)

**Comment by murugappanrm** [comment]
@Kharg i thought list view only applies to entities. Am i  wrong?
