### ISSUE TITLE
Email In Trash filter giving error 500

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2892]
**Describe the bug**
<img width="794" alt="Screenshot 2023-11-09 at 12 48 17 PM" src="https://github.com/espocrm/espocrm/assets/2862528/c0befb1d-b373-4d53-a8ab-919256a51406">

**EspoCRM version**
Can be checked on demo, 8.0.5

**Additional context**
Maybe need to be removed from filter fields as we already have side filter named Trash

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/tree/fix

Please, don't remove 'steps to reproduce' from the template. Just a simple steps would be enough.

**Comment by eymen-elkum** [comment]
Thanks for the fix, I thought the screenshot is enough
