### ISSUE TITLE
email-user optimisation

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2893]
**Is your feature request related to a problem? Please describe.**
We have a project heavily depends on email, we need 12 seconds for inbox to be fetched, we upgraded the server many times but I think we have a bottleneck on db. 

I can see that email_user is too large, I wonder if we need "deleted" column here, I don’t think anyone will restore this record.
Indexes all are combined with deleted column, also wheres will has to add it to where.

![image](https://github.com/espocrm/espocrm/assets/2862528/97863b8e-0e4a-42fe-b5f5-eb3201b0da62)

**Describe the solution you'd like**
Is there a way we can remove "deleted"  column?

**Comment by yurikuzn** [comment]
Does the Cleanup job removes deleted entries?

**Comment by yurikuzn** [comment]
I checked. The cleanup job removes not actual email_user entries. You can set `cleanupDeletedRecordsPeriod` to a shorter period to delete recently removed emails.

The type of the 'deleted' is Tinyint. It should not affect on performance.

* How many records do you have in the email table? 
* Does the user have a 'team' access level for Emails?
* MySQL or MariaDB?

We have an instance with 500,000 emails and the list view loads instantly.

**Comment by eymen-elkum** [comment]
> How long the query would execute w/o deleted column?

Not easy to test on the production server, but I just noticed that the problem is caused by the count query.

We have more than 754,000 emails, I think "deleted" is not the issue, we have custom counts queries on the list side causing the issue, will fix it and back to here if the fix needs core changes.

**Comment by yurikuzn** [comment]
Count is disabled by default for emails. Counts can be very slow on MySQL/MariaDB.
