### ISSUE TITLE
International phone numbers

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2896]
Can be enabled at Administration > Settings > International phone numbers. In this mode, all phone number values will be stored in the international format (e.g. +111111111111).

Features:

* picking country code (in edit mode);
* formatting (in read mode);
* validation (backend and frontend);
* import & lead capture: ability to specify a regional telephone code format, values will be converted to international;
* ability to define preferred country codes (to avoid entering a country code when operating in a specific region).

**Comment by Kharg** [comment]
Awesome feature, great work as always Yuri 😃

**Comment by yurikuzn** [comment]
It's been for many years in the backlog. As it's optional, there is no backward compatibility issue, unless one enables it. If enabled, old stored numbers may be invalid. In this case some migration script will be needed.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/66cbf57f5eb163f185233ce941cd6edb1673f800

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/75763bf2876902702457ba909f2e76a8b6b8b987
