### ISSUE TITLE
Error 500: Unknown error. at SOME smtp test connection

### ISSUE THREAD

**Issue by j2l** [espocrm/espocrm#2897]
**Describe the bug**
I can send email to local email server's addresses but not to distant email addresses.
email server is a container on host network, local IP is allowed to send messages without auth.
espocrm is a container on the bridge network.
Could also be an error from the email server, but all emails sent to and from it to external emails work.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. visit .../#Admin/outboundEmails
2. set local server, smtp as 25, no security, no auth
3. test sending email to email address managed by the email server: pass, delivered
4. test sending email to external email address, through the email server:  Error 500: Unknown error.
5. no indication where to find the complete error log

**Expected behavior**
Send emails

**EspoCRM version**
Version 8.0.2 (docker)

**Comment by yurikuzn** [comment]
Anything in espo log?

**Comment by j2l** [comment]
Thanks @yurikuzn I'm new to espocrm, where are the logs?
Trough UI logs are too succint

**Comment by yurikuzn** [comment]
In `data/logs/` folder.  https://docs.espocrm.com/administration/log/#default-log

**Comment by j2l** [comment]
[2023-11-11 13:28:06] ERROR: Email sending error: I cannot deliver mail for <...>
But I fixed it, it was on the email server.

**Comment by yurikuzn** [comment]
Ok. But create topics on the forum next time. We don't provide support on GitHub as stated on the New Issue page.

**Comment by j2l** [comment]
@yurikuzn you edited my message to remove the text and screenshot showing that I couldn't register on the forum.
It's not fair to tell me something you know I tried to do.
Hopefully, github allows to find previous versions and who edited a message.
