### ISSUE TITLE
Version >8.0.3 are not available in DockerHub

### ISSUE THREAD

**Issue by guillaume-dfsec** [espocrm/espocrm#2898]
**Describe the bug**
The latest version available in DockerHub is 8.0.2, however the latest release in GitHub is 8.0.5.

**To Reproduce**
Explicit steps to reproduce the behavior:
1. `docker pull espocrm/espocrm:8.0.5`

**Expected behavior**
The latest version should be available with `docker pull`.

**EspoCRM version**
* 8.0.3
* 8.0.4
* 8.0.5

**Comment by arkadiyasuratov** [comment]
As a workaround, you can trigger the upgrade manually in a container (e.g., using the command: `docker exec -i espocrm php bin/command upgrade -y`)

**Comment by yurikuzn** [comment]
Better to create issues related to docker here https://github.com/espocrm/espocrm-docker or on the forum, as it's not a bug in the software.
