### ISSUE TITLE
Send Invitations for meeting: 500 error

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#29]
In the console I have read this message:

POST
http://{www.server.com}/api/v1/Meeting/action/sendInvitations 500 (Internal Server Error)

Server side error: The input appears to be a DNS hostname but cannot match against hostname schema for TLD 'com', The input does not appear to be a valid URI hostname, The input does not appear to be a valid local network name

**Comment by yurikuzn** [comment]
Hello

Have you solved this issue?

**Comment by ayman-alkom** [comment]
It seems to be solved for now, thanks ..

**Comment by SaeedHashemi** [comment]
Hello

I have the same issue, how can I solve this error?

**Comment by yurikuzn** [comment]
> I have the same issue, how can I solve this error?
Hi,

Check https://github.com/espocrm/documentation/blob/master/administration/troubleshooting.md

**Comment by SaeedHashemi** [comment]
I check it, system requirement is OK, but I didn't error on logs!
