### ISSUE TITLE
Import: Ability to skip search for duplicates

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#290]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f4a88df067faff1cbcf4d559c91f8a28d4bc79a9

**Comment by lorenzopozzoli** [comment]
I tried to update files, but I don't see "Skip searching for duplicates" in import page.
thank you

**Comment by yurikuzn** [comment]
Cache?

**Comment by lorenzopozzoli** [comment]
Thank you,
I've already cleared browser cache and crm cache, but I can't see Skip searching for duplicates.
Which file is generating the import page? step-1.tpl?
