### ISSUE TITLE
 Selecting Different PDF Engines for Individual Templates

### ISSUE THREAD

**Issue by yubrajkafle** [espocrm/espocrm#2902]
**Is your feature request related to a problem? Please describe.**
The problem revolves around the limitations encountered while using the default PDF engine, DomPDF, within Espo CRM. Specifically, when attempting to transition from TCPDF to DomPDF for template design, issues arise with elements breaking during the rendering process. Furthermore, DomPDF lacks support for Nepali fonts, impacting the proper display of content in Nepali (Devanagari fonts). Integrating an alternative PDF engine, such as mPDF, to address this language support issue creates compatibility challenges within Espo CRM, affecting the rendering of other existing templates. This leads to a necessity for a feature enhancement that allows the selection of different PDF engines for individual templates, providing flexibility and resolving rendering inconsistencies experienced when switching between engines.

**Describe the solution you'd like**
The solution I'm seeking involves enabling the functionality within Espo CRM to select different PDF engines for individual templates. Presently, the platform allows for the switching of PDF engines, but this change applies universally across all templates. I propose the implementation of a feature that would allow users to choose distinct PDF engines for each template separately. This enhancement would provide greater flexibility, especially for users who have specific requirements for different languages or rendering needs. Ultimately, this feature would significantly improve the user experience by ensuring better compatibility with diverse templates and language support while using Espo CRM.

**Comment by yurikuzn** [comment]
I hope Dompdf eventually support Nepali fonts and other ones which are not supported now. If they do it soon , maybe we won't need to implement this feature.

BTW we are removing Tcpdf engine from the official distribution. It will be available as a free extension. The library, being LGPL, has GPL dependencies what does not met our policy.
