### ISSUE TITLE
Dynamic Logic: Conditions checking current user & current user teams

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2912]
The ability to check with Dynamic Logic:

* current user (equals or not equals to a specific one);
* current user teams (contains or not contains a specific team).

**Comment by murugappanrm** [comment]
This good one @yurikuzn

**Comment by Kharg** [comment]
I was thinking... Maybe this can be expanded with the user role as well? :)

**Comment by yurikuzn** [comment]
No, it can't. Roles should not be used anywhere other than access control table.

**Comment by murugappanrm** [comment]
@yurikuzn @Kharg 

I am using the conditional checking on teams but could not find use case for users. We definitely could use an additional roles option. Let me give a use case where we would need this extensively. E.g. When certain changes need to be approved by a user who has the specific role to approve. Additionally, connected to this we also need a field type called "approval" which is essentially is a password of logged-in user. Examples where this is used are approving payments, special requests, discounts on invoices, waivers etc.

I know i saw a signature extension but is only useful on tablets and mobile devices but has no use on the desktops. I guess i  should put this under suggestions.

**Comment by yurikuzn** [comment]
Roles has it's own intention and should not be used for anything else, especially the front-end only dynamic logic. It's my firm opinion.

**Comment by Kharg** [comment]
Sorry Yuri, I just noticed I wrote Role when in reality I wanted to write 'type' as in Regular/Admin as to show certain fields only to admin users.

But I guess this can just be achieved with an extra team with all the admins in.

**Comment by murugappanrm** [comment]
@yurikuzn just a suggestion. No worries. Thank you for the update.
