### ISSUE TITLE
 $_lastHttpResponseBody is empty

### ISSUE THREAD

**Issue by AMTpavel** [espocrm/espocrm#2914]
**Describe the bug**
If I send a GET request, the response is not loaded into the variable. The $_lastHttpResponseBody variable is empty.
**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. ... Create a workflow with a manual button.
2. ... Send HTTP Request: GET https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty/47905085 , Content Type: Content-Type: application/json 
3. ... Execute Formula Script: aa00datev = $_lastHttpResponseBody
**Expected behavior**
The full content of the response is loaded into the text field (aa00datev).
**Screenshots**
<img width="657" alt="Snímek obrazovky 2023-12-02 v 15 47 27" src="https://github.com/espocrm/espocrm/assets/152709171/1c701e45-4277-4cb2-8bc3-3a10ac564a96">
**EspoCRM version**
ESPOCRM: 8.0.5
Advanced Pack: 3.0.13
**Additional context**

**Comment by yurikuzn** [comment]
This repository does not cover paid extension. If you have issues with advanced pack consider our support. If it's a our bug or small issue, we can help for free. Otherwise, consider a paid support.
