### ISSUE TITLE
Clipboard button for more fields.

### ISSUE THREAD

**Issue by grahamgraham** [espocrm/espocrm#2917]
**Is your feature request related to a problem? Please describe.**
There is not the ability to add a clipboard button for specific fields.

**Describe the solution you'd like**
The ability to add the clipboard button for more/all fields. Largely wanting it for contact information (email, phone, etc).

**Describe alternatives you've considered**

**Additional context**
There is a clipboard button option for specific fields, but not all of them. 
[This post](https://github.com/espocrm/espocrm/issues/2698#issuecomment-1512913687) Indicated it might be difficult, but does not speak to if this is something that could be implemented.

**Comment by yurikuzn** [comment]
Not planned for now. Maybe in future.
