### ISSUE TITLE
OpenID Connect: Add state param in login request

### ISSUE THREAD

**Issue by tba-code** [espocrm/espocrm#2933]
**Is your feature request related to a problem? Please describe.**
I would like to use OIDC with Authelia (an IdP). It requires state be set for confidential clients, for security reasons.

**Describe the solution you'd like**
Implement logic for state param generation and client storage.

A possible validation may look like:

base64 encoded state -> decode == hash of (timestamp of request (saved in an httpOnly client cookie) and a session secret which stays on the server).

**Describe alternatives you've considered**
No alternatives are available to fix the issue.

**Additional context**
I understand that the OIDC spec does not explicitly require the state parameter; however, there is a security benefit for doing so, and it broadens compatibility with IdPs that may require it for security reasons. At the very least, including it as an option would work.

**Comment by yurikuzn** [comment]
We do send *state* parameter on Authentication Request: https://github.com/espocrm/espocrm/blob/8.0.6/client/src/handlers/login/oidc.js#L92.

**Comment by tba-code** [comment]
Oops, I had been looking in the wrong file (and misread my logs). I am sorry for the mistake.

Issue actually turned out to be about the length of the state rather than it being missing. I can handle this locally. Thank you for the quick response!

**Comment by yurikuzn** [comment]
Does Authelia not allow the current length? What length it requries?

**Comment by yurikuzn** [comment]
Additional question. Is it possible to turn the requirement off?

**Comment by tba-code** [comment]
Hi, Authelia asks for a minuimum of 8. This is my proposed change:
`let state = (Math.random() + 1).toString(36).substring(7);` Currently outputs 5 characters.
becomes
`let state = (Math.random() + 1).toString(36).substring(4);` This is the Authelia minimum of 8 characters.

It is generally not recommended to lower the requirement, though, as it lowers it for all clients.

**Comment by yurikuzn** [comment]
I see. Thanks for the info.
