### ISSUE TITLE
Default Values not saved when duplicating imports

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#2934]
**Is your feature request related to a problem? Please describe.**
When a user imports files, e.g. csv, it is possible to add **Default Values** to fields in the target entity:

![image](https://github.com/espocrm/espocrm/assets/1170415/85d9d257-fb75-46e4-b416-bd677815edb2)

This is extremely helpful and it works as expected. However, the values of the Default Values fields are not saved when the user duplicates the import using **New import with same params**:

![image](https://github.com/espocrm/espocrm/assets/1170415/13ac9f2c-f97f-4c6b-b483-e0b41d479558)

It would be very helpful if the duplicated import process saved the settings for Default Values as well as imported fields in the file.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
I currently work around this issue by using a workflow, which is clumsy and fragile.

**Additional context**
See above.

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/commit/3e71c3db314575ed34da05f9ad5c744dda18fe05
