### ISSUE TITLE
Tcpdf extension install error

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#2935]
Hello,

Recently updated to Espo 8.1 and now miss Tcpdf cause many customizations depend on it.

Tried to install as extension regarding to Documentation.
- Downloaded https://github.com/yurikuzn/ext-tcpdf/releases/download/0.1.0/tcpdf-0.1.0.zip
- Went to Adm-Settings-Extensions, choose tcpdf-0.1.0.zip and click upload

After some time got errors in browser console, extension is not installed:

```
espo-main.js:19500 Could not parse API response.

Bad server response: <br />
<b>Warning</b>:  Unknown: POST Content-Length of 23354203 bytes exceeds the limit of 20971520 bytes in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"id":"65995644ebcc93128","version":"0.1.0","name":"Tcpdf","description":"TCPDF engine."}
```

**Comment by yurikuzn** [comment]
Please look up errors such on the internet first.

https://www.google.com/search?q=POST+Content-Length+of+23354203+bytes+exceeds+the+limit&oq=POST+Content-Length+of+23354203+bytes+exceeds+the+limit
