### ISSUE TITLE
Returning to list view while having empty string filter breaks view

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2943]
**Describe the bug**
When you view the details of a record with a filter that has no value, and then go back to the list view, the frontend throws a fatal error and becomes dysfunctional for the given entity. You're unable to interact with the entity unless you perform a full refresh of the page by pressing F5.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Go to a list view of any entity (ex. Account)
2. Apply at least 2 filters
3. The first filter can be anything (boolean/assigned user/does not matter)
4. Second filter should be for a text field (however I think it can happen to other types of fields)
5. Leave the second filter blank
6. Make sure to apply filters (or press the search button) Note: This bug is not reproducible after clean refresh if you do not apply the filters (by pressing search button) a search/apply button must be pressed before continuing, for 99% cases it will be as the user just entered the filter and applied it.
7. Open detail of any available record
8. Go back to list either by navbar tab or by breadcrumb link
9. Entire list view for the given entity will break and will not fix itself until full refresh (F5), other entities are accessible

**Expected behavior**
User should be able to return to list view.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/15276167/4f8ecf7f-5871-4342-8407-d1c56dc65ba0)
![image](https://github.com/espocrm/espocrm/assets/15276167/5ec3f453-ba3d-4ac7-be31-9dd4fc5bdddf)
![image](https://github.com/espocrm/espocrm/assets/15276167/bc4c69a8-b432-4a2a-81b8-65e8ae8f7243)

**EspoCRM version**
Tested on 8.0.5 all the way to 8.1.0 (happens on both), clean install no extensions

**Additional context**
Javascript error in console:
```
Uncaught (in promise) TypeError: this.searchParams is null
    getSearchParamsData espo-main.js:2492
    getSearchValues espo-main.js:2502
    data espo-main.js:2096
    data espo-main.js:26019
    data espo-main.js:39580
    _getData bullbone.umd.js:1574
    _getHtml bullbone.umd.js:1659
    s bullbone.umd.js:1613
    _getNestedViewsHtmlMap bullbone.umd.js:1617
    _getHtml bullbone.umd.js:1658
    getHtml bullbone.umd.js:1183
    _getNestedViewsHtmlMap bullbone.umd.js:1634
    _getNestedViewsHtmlMap bullbone.umd.js:1619
    _getHtml bullbone.umd.js:1658
    getHtml bullbone.umd.js:1183
    _getNestedViewsHtmlMap bullbone.umd.js:1634
    _getNestedViewsHtmlMap bullbone.umd.js:1619
    _getHtml bullbone.umd.js:1658
    getHtml bullbone.umd.js:1183
    _getNestedViewsHtmlMap bullbone.umd.js:1634
    _getNestedViewsHtmlMap bullbone.umd.js:1619
    _getHtml bullbone.umd.js:1658
    render bullbone.umd.js:1215
    render bullbone.umd.js:1214
    _processMain espo-main.js:7411
    main espo-main.js:7342
    master espo-main.js:7264
    main espo-main.js:7328
    actionList espo-main.js:41293
    promise callback*actionList espo-main.js:41273
    doAction espo-main.js:7244
    e espo-main.js:31512
    getController espo-main.js:31576
    doAction espo-main.js:31532
    initRouter espo-main.js:31486
    Backbone 4
    dispatch espo-main.js:16380
    actionNavigateToRoot espo-main.js:8187
    checkConfirmLeaveOut espo-main.js:16182
    actionNavigateToRoot espo-main.js:8179
    handleAction espo-main.js:5143
    click .action espo-main.js:7876
    jQuery 8
    _delegate bullbone.umd.js:879
    _delegateEvents bullbone.umd.js:873
    setElement bullbone.umd.js:835
    setElementInAdvance bullbone.umd.js:1107
    m bullbone.umd.js:363
    f bullbone.umd.js:342
    l bullbone.umd.js:48
    trigger bullbone.umd.js:327
    _afterRender bullbone.umd.js:1324
    render bullbone.umd.js:1235
    _getHtml bullbone.umd.js:1677
    n bullbone.umd.js:2683
    _executeLoadCallback extender.js:276
    _executeLoadCallback extender.js:276
    _handleResponseText extender.js:1031
    _load extender.js:829
    promise callback*_load/< extender.js:829
    promise callback*_load extender.js:820
    require extender.js:455
    require extender.js:1202
    template espo-main.js:31699
    _callExternalLoader bullbone.umd.js:2438
    load bullbone.umd.js:2450
    getTemplate bullbone.umd.js:2692
    _getTemplate bullbone.umd.js:1754
    _getHtml bullbone.umd.js:1673
    s bullbone.umd.js:1613
    _getNestedViewsHtmlMap bullbone.umd.js:1638
    _getHtml bullbone.umd.js:1677
    n bullbone.umd.js:2683
    _executeLoadCallback extender.js:276
    _executeLoadCallback extender.js:276
    _handleResponseText extender.js:1031
    _load extender.js:829
    promise callback*_load/< extender.js:829
    promise callback*_load extender.js:820
    require extender.js:455
    require extender.js:1202
    template espo-main.js:31699
    _callExternalLoader bullbone.umd.js:2438
    load bullbone.umd.js:2450
    getTemplate bullbone.umd.js:2692
    _getTemplate bullbone.umd.js:1754
    _getHtml bullbone.umd.js:1673
    s bullbone.umd.js:1613
    _getNestedViewsHtmlMap bullbone.umd.js:1638
espo-main.js:2492:6
```

**Comment by yurikuzn** [comment]
Thanks for the qualitative report. Fix: https://github.com/espocrm/espocrm/commit/f7b2ad17be38088a6741c28edca0b139db029218
