### ISSUE TITLE
Stream: View user activity

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2945]
The ability to view all stream notes that were either created by a user or created as result of users' actions.

Available from the Stream panel on the User detail view. The user should have an appropriate *User* permission to be able to see activities for another user.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/4d735e9e261f73a5db5cf7144fd7edc47b2239e6

**Comment by bandtank** [comment]
This is extremely useful. I built a custom tool to do the same thing, but I'd much rather do it in Espo. Thanks for the feature updte.
