### ISSUE TITLE
Postgres official support

### ISSUE THREAD

**Issue by cpcotuser** [espocrm/espocrm#2947]
Hello there,

Just checking to see when you plan to mark Postgres support as official. Is there known work needed on that front?

Thanks!

**Comment by yurikuzn** [comment]
Hi, Planned to declare it official this year. The work is fully done, everything is supposed to work. We just don't have enough to resources to perform manual functional testing on Postgres on the same level as we do for MySQL/MariaDB, for EspoCRM and all our extensions. The more people adopt it, the soon it we will feel it's really ready.
