### ISSUE TITLE
Record locking

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2948]
**Is your feature request related to a problem? Please describe.**
EspoCRM is very versatile and can be used far beyond CRM (as demonstrated in sales pack and other extensions alike). With this usage there can be cases where records need to become locked in specific state. For example invoices in EU, once invoice in EU is handed to customer it cannot be easily edited (legally) without creating a credit note and reissuing the invoice.

**Describe the solution you'd like**
Ability to define rules (filter-like would be fine) that make entity locked for further edits once the rule is fullfilled.
For example: Warehouse Goods Issue, once processed shouldn't be touched in any way as it's an accounting document.
Also in addition to this an option where administrator can override the lock would be helpful.

**Describe alternatives you've considered**
You can lock the records from being edited with before save hook, however this solution is not very versatile and user editable.
Dynamic logic can also be applied to make field read only, by setting it for each field, but it's not convenient for future changes, or even setting up and still if adjustment is needed (from CRM admin) the admin would need to edit the dynamic logic beforehand.

**Additional context**
I saw this feature when I tried vtiger cloud demo and while espocrm definetely beats vtiger, I beleive this feature would be useful to have in core Espo.

**Comment by yurikuzn** [comment]
In the new Sales Pack there is order locking feature. For information.

**Comment by radek3911** [comment]
> In the new Sales Pack there is order locking feature. For information.
> 
> BTW it can be also implemented using API Before Save Script (w/o custom files).

Thanks for the quick response I'll look into API before save, also in regards to salespack:

Yes I have tried the salespack demo, but didn't it rely on dynamic logic?

**Comment by yurikuzn** [comment]
I will add this request to the backlog. Not sure yet whether we will add it, need more time to think.

**Comment by radek3911** [comment]
Yeah the more I think about it the harder it becomes, maybe the modal using Espo.Ui.confirm is not the best approach (as you can't put modal in API) perhaps a "lock" toggle icon would be more reasonable with endpoint to unlock/lock would be a better idea, but I am not sure if it goes well with Espo clean design.

Next thing to consider are mass actions how to handle locking and unlocking there? Sure it could be simple, but if unlocking record is now another API endpoint it needs additional work in mass action to be able handle locking and unlocking through them too.

However I think I like the idea of being able to lock records (ideally massively or individually through API). Another use case that comes to mind is data synchronization across external systems that are not as fast as espo. For example we implemented full 1:1 woo commerce sync from espo to woo (products, warehouse stock etc.) and sometimes due to woo api we have to make multiple requests for one record update and woo api can be quite slow based on the scale of the website (wordpress DB is not very well designed, everything is a "post" and has Metadata as fields, to be fair recently woo commerce launched HPOS which solves partially this design flaw). And while optimistic concurrency control is a thing I think it still would be wise to have ability to easily lock records while sync is progress, especially in case of woo commerce where the sync is not instant and takes a few seconds.

Thanks for the consideration 👍

**Comment by rabiibrahimi** [comment]
+1

**Comment by yurikuzn** [comment]
Just letting know that unlikely to be added in the nearest future. It's too much work as always. For those how need it, I recommend implementing a customization which is not that difficult.

**Comment by Kharg** [comment]
It's easy enough with API before save script.
Just create a bool field called "lock"
and use the following formula:
`if (entity\isAttributeNotChanged('lock') && lock == true) {
    recordService\throwForbidden("Il record è bloccato.");
}`


@radek3911

**Comment by radek3911** [comment]
> It's easy enough with API before save script.
> 
> Just create a bool field called "lock"
> 
> and use the following formula:
> 
> 
> 
> > if (entity\isAttributeNotChanged('lock') && lock == true) {
> 
> >     recordService\throwForbidden("Record is locked.");
> 
> > }
> 
> 
> 
> 
> 
> @radek3911 

Hello Andrew,

Thanks for the input, yes this was communicated by Yuri in one of the first replies.

I have thought about it and perhaps pairing this with admin-only manuál workflow from Advanced pack is a great solution.

My idea is to implement the formula you wrote, but make lock field read only and be only able to unlock it from manual workflow. I believe this can work quite well and fit my needs that I previously described. 

The think that's missing now is ability to add styles to manual workflow buttons (background color and perhaps an icon would be nice touch). Either way I am satisfied so @yurikuzn feel free to close the issue as this "advanced functionality" can be easily done with Advanced pack (and even without it with some coding).

**Comment by Kharg** [comment]
@radek3911 I am working on a free extension, should be ready very soon!

![image](https://github.com/espocrm/espocrm/assets/32223252/0d53e817-6916-47ed-bae7-0b8ebe507ef6)

![image](https://github.com/espocrm/espocrm/assets/32223252/582bdb60-5f9d-4c22-ac68-6f0de0807bef)
