### ISSUE TITLE
PDF: Ability to define CSS in Templates

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2949]
A defined style will be applied to a printed PDF document.

![image](https://github.com/espocrm/espocrm/assets/1006792/3c952b19-2c40-4bc7-b051-d80efba5eea9)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/99bd7ae43763c0e938315207b6b99f96d5ccb8c3

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/b6179463b1cddc39ac4c22d95a419f8bd4c17234

**Comment by rabiibrahimi** [comment]
Very good addition, definitely will help a lot. Will it be difficult to implement same concept for email template ? 
Thanks

**Comment by yurikuzn** [comment]
Style in emails won't work reliably in all email clients and providers. Not planned.
