### ISSUE TITLE
Email improvements

### ISSUE THREAD

**Issue by zesava** [espocrm/espocrm#2950]
Here are some ideas for improving email:

Improve previewing: Currently, to preview an email, you need to open it, then click back and open another email. This requires at least two mouse clicks to switch between two emails. In contrast, Roundcube and Outlook only require one click to read the next email.

A better solution would be to allow users to preview emails without opening them. This could be done by displaying a preview pane in the email client, or by allowing users to hover over an email to see a preview.

Improve unread mail detection: Currently, the only way to distinguish between read and unread emails is by the font of the subject line. Unread emails have a bold subject line, while read emails have a regular subject line. This can be difficult to see, especially if you have a lot of emails in your inbox.

A better solution would be to use a more obvious visual indicator to distinguish between read and unread emails. This could be done by using a different color for the subject line, or by adding a checkmark or other symbol next to the email.

Add the ability to add labels to messages: This would allow users to organize their emails into different categories. For example, you could create labels for work emails, personal emails, or marketing emails. This would make it easier to find the emails you're looking for.

These are just a few ideas for improving email. By making these changes, we can make email more efficient and user-friendly.

**Comment by yurikuzn** [comment]
Hi,

Thanks for input.

Regarding preview, it's in backlog, but not planned for soon. See here: https://forum.espocrm.com/forum/feature-requests/81974-email-preview-pop-up-pane

Regarding unread. We might better to make the font bolder for light themes. In dark theme I believe it's already bolder.

Regarding labels. I'm not sure. There's already folders: personal and group. There's the ability to create custom fields. The admin can create a Label field.

**Comment by yurikuzn** [comment]
>  allowing users to hover over an email to see a preview.

Popups on mouse hover is no-no in Espo. Just for information.

**Comment by zesava** [comment]
Hi,
Hi, thanks for quick response.

> 
>Regarding preview, it's in backlog, but not planned for soon. See here: https://forum.espocrm.com/forum/feature-requests/81974-email-preview-pop-up-pane

This is exactly what i was looking for. Thanks for a hint.

>Regarding unread. We might better to make the font bolder for light themes. In dark theme I believe it's already bolder.

Maybe better to highlight entire row or add some vertical line eg as is done with selected mail folder on left panel

>Regarding labels. I'm not sure. There's already folders: personal and group. There's the ability to create custom fields. The admin can create a Label field.

I already created custom field of type list . But there is no possibility to change these field in list mode. To change this label you need to open selected email and only there you can change it.
