### ISSUE TITLE
Import: Relate by foreign field

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2956]
*Relate on Import* parameter for foreign fields. If enabled, then, when importing records with foreign field values, a matching foreign records will be automatically linked. Use this functionality when the foreign field is considered as unique.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/acd5d78d30c5177b9e92b1c86dc4f2feac5c1db4

**Comment by bandtank** [comment]
Ahhhh this is amazing. Thank you. It will save me a ton of time every day.
