### ISSUE TITLE
Zombie processes for cron Daemon.php

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#2966]
The command: 

`/usr/bin/php public_html/daemon.php`

is spawning zombie processes:

`ps aux | grep 'Z'`

`rw.devc+  527929 10.0  0.0      0     0 ?        Z    11:17   0:00 [php8.2] <defunct>`

It can be tested as described above - clean EspoCRM 8.1.1 with PHP 8.2:

`PHP 8.2.15 (cli) (built: Jan 20 2024 14:13:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.15, Copyright (c), by Zend Technologies
`

**Comment by yurikuzn** [comment]
How much of them do you get?

**Comment by yurikuzn** [comment]
Only one shouldn't be a problem I think.

**Comment by david-strejc** [comment]
It is not a problem with process itself - it is problem with system resources (even very small) when there is respawned one process per instance and it is considered Zombie (probably due to exit code, because it is a child). We can look into it and send a fix - i will let team do that.

**Comment by yurikuzn** [comment]
The daemon.php runs a loop, that runs `php cron.php` processes using symfony/process. Each child process runs separate processes per each job using spatie/async. It does not run all in a single process as it's PHP with no parallelism our of the box. Maybe that zombie process is not a problem at all, as it's only one and it termintes with each lool run, meaning it's not hang for long. It could be
