### ISSUE TITLE
Documents relation for Contacts

### ISSUE THREAD

**Issue by filippogasbarro** [espocrm/espocrm#297]
At this time is not possible to attach a document in contacts and leads

**Comment by yurikuzn** [comment]
I think we will add relationship but hidden by default.

**Comment by yurikuzn** [comment]
Leads already have relationship with documents.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/e0128bf54f581ff253bf79ab7e1b41d6914b539a

**Comment by filippogasbarro** [comment]
Thank you, because sometimes is important to link for example a identity document etc. So, personal files that cannot stay in opportunity. If I have 5 opportunity with the same person, why must I reupload the same file (or files) in all the opportunity :smile:
