### ISSUE TITLE
Navbar tabs with custom URLs

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2974]
The ability to define custom URLs for tabs.

* URLs can start with `#`. This allows to follow to pages of the application, e.g. some administration settings.
* The ability to define access with the  *ACL Scope* parameter.
* The ability to allow only for admin.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/5a3b3ab2e8abd7bed8c3e4a122725521059a402a

**Comment by eymen-elkum** [comment]
Very nice to have this feature on espocrm, finally good by to NavPro :)

**Comment by eymen-elkum** [comment]
The only missing feature now is mouse hover open sub menu

**Comment by yurikuzn** [comment]
> The only missing feature now is mouse hover open sub menu.

In EspoCRM, we have a rule of not using mouse hover actions: no popups, no menu openings. They are against EspoCRM UI principles. For sub-sub-menus they are OK though.

**Comment by yurikuzn** [comment]
But this is off topic.

**Comment by Kharg** [comment]
Hi Yuri,
Would it be possible to add a bool field 'open in new tab'?
I've just tested the custom url feature and I think that opening the url in the same window as Espo (thus replacing the crm page) is not a desidered behaviour for many, unless it's going to be a crm url.

I know users can press ctrl and open in a new window, but I think a behaviour toggleable with a bool field is the best solution.

**Comment by yurikuzn** [comment]
Not sure. I'm for that links should be always opened in the same tab except very few cases. As example, one can check external links here on GitHub. Maybe one can create an extension that modifies the behavior.
