### ISSUE TITLE
Panel notes

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2977]
The ability to specify a text that will be displayed at the top of a detail view panel. Available only in the Detail layout.

![image](https://github.com/espocrm/espocrm/assets/1006792/434d46ce-9e0d-4a1e-9fdd-9d0edb8a5f8b)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/1ccd70b3fc540d65ddf6894d6b90f4bf849e73fe

**Comment by Kharg** [comment]
Awesome! Salesforce has a similar feature, it's a pleasure to see how much Espo is growing, keep up the good work Yuri!
