### ISSUE TITLE
Add the SiteUrl placeholder to core

### ISSUE THREAD

**Issue by rouhu** [espocrm/espocrm#2978]
Could the proposed SiteUrl placeholder for email templates be added to the core placeholders.
See issue: https://github.com/espocrm/espocrm/issues/2875

Thanks, Tim

**Comment by yurikuzn** [comment]
Hi,

It's just the same URL. You can just insert it as it is. Or implement a custom placeholder.

**Comment by yurikuzn** [comment]
Want to ask again not to remove the whole issue template. Issues with deleted templates to be deleted entirely.

**Comment by rouhu** [comment]
Step by step instructions on how to add a custom placeholder would be very useful.

Is the new placeholder code file added here or somewhere at custom-folder ?
/application/Espo/Tools/EmailTemplate/Placeholders

Is the new Placeholder then also added to these files ?
application/Espo/Resources/metadata/app/emailTemplate.json
application/Espo/Resources/metadata/clientDefs/EmailTemplate.json

Thank you, Tim

**Comment by yurikuzn** [comment]
See docs: https://github.com/espocrm/espocrm/issues/2875#issuecomment-1799291807

**Comment by rouhu** [comment]
Some of us are still learning, bear with us :)

Quick Instructions:

Created file /custom/Espo/Custom/Resources/metadata/app/emailTemplate.json
{
    "placeholders": {
        "today": {
            "className": "Espo\\Tools\\EmailTemplate\\Placeholders\\Today",
            "order": 0
        },
        "now": {
            "className": "Espo\\Tools\\EmailTemplate\\Placeholders\\Now",
            "order": 1
        },
        "currentYear": {
            "className": "Espo\\Tools\\EmailTemplate\\Placeholders\\CurrentYear",
            "order": 2
        },
		"SiteUrl": {
            "className": "Espo\\Tools\\EmailTemplate\\Placeholders\\SiteUrl",
            "order": 3
        }
    }
}

Create file /application/Espo/Tools/EmailTemplate/Placeholders/SiteUrl.php
<?php
namespace Espo\Tools\EmailTemplate\Placeholders;

use Espo\Tools\EmailTemplate\Data;
use Espo\Tools\EmailTemplate\Placeholder;

/**
 * @noinspection PhpUnused
 */
class SiteUrl implements Placeholder
{
    public function __construct(
    
    ) {}

    public function get(Data $data): string
    {
		return 'mydomain.com';
    }
}

In Email template place {SiteUrl}.

To-Do:
- Place SiteUrl.php somewhere under custom-folder (?)
- Pick-up the real config data (see https://forum.espocrm.com/forum/general/69491-read-current-url-in-formula)
