### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2979]
The ability to view field updates w/o Stream enabled for an entity type. Access is controlled by Audit permission in roles.

**Comment by yurikuzn** [comment]
Added an ability to restore previous values: https://github.com/espocrm/espocrm/commit/0da0b8974c5a44e9db8844d8d455ffe648526231

**Comment by Kharg** [comment]
Awesome feature, thanks for all your hard work Yuri!
