### ISSUE TITLE
Contact custom entity hook "after/beforeSave" wont be executed after relate contacts in account if contact have already associations 

### ISSUE THREAD

**Issue by simppa69** [espocrm/espocrm#298]
DEFECT

Contact custom entity hook afterSave and beforeSave wont be executed after relate or unrelate contacts in account entity if contact have already account associations. If contact has none of the associations hook is executed.
![2016-11-13_23-26-22](https://cloud.githubusercontent.com/assets/23297584/20248979/ade04038-a9f8-11e6-97e6-fd82ab5ff00c.png)

**Comment by yurikuzn** [comment]
I think it's because entity is not changed when it's get linked with related entity through hasMany. When contact doesn't have any relations with accounts then afterSave is triggered becase primary account gets changed.

**Comment by simppa69** [comment]
Okay, I understand. So the only way to catch these updates is modify core file Espo\Modules\Crm\Repositories\Account.php and add my hooks there for this actions. I'm I right?

Btw. is it possible to overwrite the core files with extensions packages?

**Comment by yurikuzn** [comment]
It's already implemented for 4.3.0 release. AfterRelate and AfterUnrelate hooks.

**Comment by yurikuzn** [comment]
Possible to override core files but not compatible with upgrades.

**Comment by simppa69** [comment]
Okay, I did hear that there is coming AfterRelate and AfterUnrelate Hooks available. Any plans when will be 4.3 available?

**Comment by yurikuzn** [comment]
Beta planned for this week. GA release depending how many bugs we will have.

**Comment by simppa69** [comment]
Hi, I'm testing AfterRelate and AfterUnrelate in new branch. But I have trouble to get Contact ID to be associated to Account. Is it given in parameters? Please.

**Comment by yurikuzn** [comment]
Sorry, I'm vert busy with upcoming release.

**Comment by simppa69** [comment]
I figured it out:

	public function afterRelate(Entity $entity, array $options = array(), array $data = array())
    {
		$foreignEntity = $data['foreignEntity'];
	}
	
	public function afterUnrelate(Entity $entity, array $options = array(), array $data = array())
    {
		$foreignEntity = $data['foreignEntity'];
	}

**Comment by yurikuzn** [comment]
Cool. Can you star our repository please :)
