### ISSUE TITLE
New function for API Before Save Formula

### ISSUE THREAD

**Issue by rouhu** [espocrm/espocrm#2983]
**Is your feature request related to a problem? Please describe.**
It is often needed to alert, advice, guide or remind user for the correct business process. So it would be useful to have a modal alert popup with OK-button that would still submit the form after clicking the OK button. Now all API formula functions block the form submission.

**Describe the solution you'd like**
Add a function recordService\throwAlert(MESSAGE) for the API Before Save Formula script. This would allow to give information to user what is expected to happen next. For example, MESSAGE="Remember to complete all line items and then set status to READY."
After pressing OK button form would be submitted normally.

**Describe alternatives you've considered**
Maybe some custom code could do this.

**Additional context**
 Functionality is similar to the dublicate check function but more simple, so should not be too big of a development effort

**Comment by yurikuzn** [comment]
I believe this could be done by a developer. This not difficult with [save error handlers](https://docs.espocrm.com/development/metadata/client-defs/#saveerrorhandlers). When user clicks OK you could set some notStorable field to true and then check in the formula.

> so should not be too big of a development effort

It can turn out to be quite an effort to do it properly. Would require passing custom headers.

Closing it as not planned for the nearest future. Maybe re-consider someday.
