### ISSUE TITLE
Install.sh  fails on  Linux Mint 21.3

### ISSUE THREAD

**Issue by mhmoran** [espocrm/espocrm#2984]
**Describe the bug**
Fresh install on Linux Mint 21.3,  sudo bash install.sh  fails with  cat: /etc/upstream-release: Is a directory

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Fresh install of Linux Mint 21.3
2. wget https://github.com/espocrm/espocrm-installer/releases/latest/download/install.sh
3. sudo bash install.sh

**Expected behavior**
The install script to recognize  that it is running on a Linux Mint 21.3 system and appropriately determine the information
it needs from the /etc/upstream-release directory

**Screenshots**

**EspoCRM version**
Specify the EspoCRM version (or versions) on which the bug occurs.
Fresh pull of Espo 8.1.4
![Espo_ss](https://github.com/espocrm/espocrm/assets/10239911/c2d9bb78-61a6-4d0b-83cd-e322c9d17cec)

**Additional context**

**Comment by yurikuzn** [comment]
Please re-create the issue there https://github.com/espocrm/espocrm-installer. As it's not the bug in the EspoCRM application,
