### ISSUE TITLE
CategoryTree entity first record missing navigation arrows

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2985]
**Describe the bug**
First record of category folder is missing the navigation arrows, if the first element is visited and then you select another element in the list view it will mark the right navigation arrow with class "disabled" but it will still work when pressed.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Visit a Category folder entity (https://demo.eu.espocrm.com/?l=en_US#KnowledgeBaseCategory)
2. Click on the first record 
3. No navigation arrows will be visible
4. Go back on the list view and click the second record
5. Next record navigation arrow will have disabled as its class but will still work

**Expected behavior**
Navigation arrows should always be visible and not disabled if there's a next element in the list

**Screenshots**

**EspoCRM version**
Tested in the official demo 8.1.4 (https://demo.eu.espocrm.com)

**Additional context**
Video of the issue: https://www.awesomescreenshot.com/video/24948083?key=568d35b254b8728a5bd2f3e3fad2ee49

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/8cd6912fee91b4c0fdfba5fb329b31ccfe0924de
