### ISSUE TITLE
Adding prefix to entity type, field & link names

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2988]
When creating fields, links and entity types, a prefix will be automatically added.

* MyEntity => CMyEntity
* myField => cMyField (only for non-custom entity types)
* myLink => cMyLink (only for non-custom entity types)
* relationshipName => cRelationshipName 

Only names, not labels. The functionality can be disabled with the config parameter `customPrefixDisabled`.

The main purpose is to prevent conflicts with future installed extensions or future added functionality.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/ext-template?tab=readme-ov-file#using-entity-manager-to-create-entities

**Comment by yurikuzn** [comment]
It won't affect anyhow.

**Comment by yurikuzn** [comment]
You can disable the prefix and add it manually for now.

>  tables are prefixed "C_" due to the handling of capitals.

This is intentional. But "c_" rather than "C_".

**Comment by murugappanrm** [comment]
@yurikuzn @analystcmyk 

I vaguely understand this feature. If my understanding is correct, enabling this feature, it will add "c" prefix  to a relationship name. Example If i have relationship "Account" to "Entity1" and also in "Entity2". Both these relationship names with renamed as "cAccount". Is my understanding correct?

If this is true, i am not sure how I going use this. It will greatly help if the suggestion by @analystcmyk is implemented. A custom prefix will add great value globally as i am manually prefixing all the fields. With custom prefix, I can have a field name "Myfield" in both entities and this will make the definitions and glossary in my documentation very consistent.

**Comment by yurikuzn** [comment]
It's not a feature for users, it's a care for a feature. 

Use case. We have an extension. Many companies use it. Many created custom fields. We decide to add new features to the extension. Added many new entities, fields and links. Chance that these new items will have name conflicts with client's custom fields. As the result, some our users have broken software after upgrade. By forcing a prefix, we would have prevented this.

**Comment by murugappanrm** [comment]
I understand the needs. In summary, this feature is there to resolve symbol issues when using certain Espo extensions. Setting the default value to false in the config, will it not cause problems to users who may be caught unaware and start wondering why their new entities have "C"prefix?

Question: Do you suggest that all future custom entities should have the "C" prefix to provide for future releases?

**Comment by yurikuzn** [comment]
Having prefixes enabled by default, releases us (and any extension developer) from liability. As a user intentionally disabled prefixes, they are responsible for future naming conflicts.

> will it not cause problems to users who may be caught unaware

I don't see having prefixes as something that may seemed as a  problem. The decision is already done, prefixes are there. One can disable it at their own risk. I need to move forward.

**Comment by yurikuzn** [comment]
Not related with extensions. It's up to developer how to name. But I'd recommend to try to pick names minimizing the chance of future conflicts.
