### ISSUE TITLE
Unable to add Migadu IMAP/SMTP accounts with error "ERROR: (0) cannot read - connection closed?"

### ISSUE THREAD

**Issue by komali2** [espocrm/espocrm#2991]
**Describe the bug**
On an espocrm deployment for which we've confirmed gmail accounts work as personal or group email accounts, for IMAP and SMTP, we can't get Migadu accounts authenticated for IMAP or SMTP.

On the Group Email Accounts > Add New page, if we fill out the account details, and then click Test Connection, after a while, the `POST` request will resolve with 500. The `POST` request details contain the known-good credentials that work with other IMAP and SMTP software:

```
emailAddress:  "caleb@example.com"
host: "imap.migadu.com"
id: "{an id}"
password: "known-good password"
port: 993
security: "TLS"
username: "caleb@example.com"
```

Under `espocrm/data/logs` , we see the following error:

`ERROR: (0) cannot read - connection closed?; POST /InboundEmail/action/testConnection; line: 143, file: /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Imap.php`

Migadu accounts work in other IMAP/SMTP software, such as Thunderbird, Gitlab, Vaultwarden, etc, so I'm opening a bug here. I poked around in the php code but didn't see anything obvious, so I'm hoping someone more familiar with the codebase can help me understand what might be going wrong specifically with Migadu. 

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Have a Migadu account
2. In an EspoCRM instance, click "Emails > top-right 3 dot menu > Personal (or Group) Email Accounts > Create Email Account
3. Click IMAP tab
4. Fill out all required fields with known-good IMAP configuration information
5. Click "Test Connection"
6. Wait
7. Observe 500 error in browser (or in network panel)

**Expected behavior**
After step 5 above, an indication that the connection was successful.

**Screenshots**

**EspoCRM version**
`Version 8.1.4`
Deployed via Elestio

**Additional context**

**Comment by yurikuzn** [comment]
Did you try SSL instead?

**Comment by yurikuzn** [comment]
It could be that your web server is blocking outgoing connections on 993 port.

**Comment by komali2** [comment]
> Did you try SSL instead?

I did try SSL though I'm not sure migadu supports that, it directs TLS in its instructions. 

Re: port, I'll investigate the port thing.
