### ISSUE TITLE
Disallowing field level edit permission on assigned user, prefills the assigned user

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#2992]
**Describe the bug**
I have a following user story:
Make internal help desk entity where users are able to make "tickets", users should not pick assigned user to a ticket and "ticket resolvers" should take over and handle the ticket.
After setting up field level permissions to disable edit on assigned user, when creating a ticket assigned user is prefilled and non-removable by the user.
(Note there are some additional ACL PHP files to complete this user story, but to reproduce the bug it's not necessary)

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Make a new entity: Helpdesk
2. Create a role: Helpdesk user, set create,read,edit access to all (you can set other levels too as long as the user can create the ticket)
3. Observe that non-admin user with this role can create a helpdesk ticket, while not requiring assigned user to be filled
4. Edit Helpdesk user role and add field level permission on assigned user. Read:yes, edit: no
5. Try creating helpdesk ticket again, notice that assigned user is now prefilled and non removable by the user.

**Expected behavior**
Assigned user should be empty as
a) user should not be able to edit the field
b) the field is not mandatory in entityDefs

I think this behavior should be only intentional if the assigned user is mandatory, but I might be wrong.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/15276167/beba49b9-dec8-45df-aacb-8610d1de2e58)
![image](https://github.com/espocrm/espocrm/assets/15276167/a1bdfbd4-5fa8-4c83-8739-d12e6b539339)

**EspoCRM version**
8.1.1, all the way to 8.1.4 (older versions were not tested)

**Additional context**
Workflows from advanced pack(or hook) can be used as workaround to remove assigned user on creation of the ticket.

**Comment by yurikuzn** [comment]
There's code in the frontend and the backend that intentionally does it. I'm not sure why we did it, but having it two separate places says that it's likely were considered as an intentional behavior. Maybe I'll reconsidering this behavior for the next version. I suppose it should work the way it works now, only if assignment permission is set to 'no' as leaving assigned user empty will cause Forbidden error.

**Comment by yurikuzn** [comment]
This behavior is intentional.

**Comment by radek3911** [comment]
Sure, we can always use workflows/hooks so it's not a big issue.
