### ISSUE TITLE
Customizing tree part in list-with-categories  

### ISSUE THREAD

**Issue by Liqynn** [espocrm/espocrm#2997]
file views/list-with-categories

using **'views/record/list-tree'**   is hardcoded in

loadCategories() {
this.getTreeCollection(collection => {
this.createView('categories', **'views/record/list-tree'**, {

So to change  'views/record/list-tree'  It's nessesary to modify  loadCategories function

May be it's  better to ​ change code like
 **record_listtree_view**:  'views/record/list-tree';
loadCategories() {
this.getTreeCollection(collection => {
this.createView('categories',record_**record_listtree_view**, {

Then It's possible to change view in custom  list-with-categories  like
 return Dep.extend({
     **record_listtree_view**:  _'custom:views/record/list-tree'_

**Comment by Kharg** [comment]
Or could be added to metadata

**Comment by yurikuzn** [comment]
It's ok to have view hardcoded. We were moving away from customizing by extending views to composition approach.

You can customize the parent view, the way list tree is created.

**Comment by eymen-elkum** [comment]
> We were moving away from customizing by extending views to composition approach.

This is very interesting, is there more information for now if possible.

**Comment by yurikuzn** [comment]
Example of composition is view-setup-handlers. It does not use inheritance, allows multiple customizations for one scope, facilitates using public methods rather than access internals of views that more likelihood to change over time. Custom views are less reliable.
