### ISSUE TITLE
Add quick search to the add field dropdown on the import view step 2

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#2998]
**Is your feature request related to a problem? Please describe.**
When importing records to the crm, you can add fields with specfic values using the add field button in step 2. If the current entity has a lot of fields even with regular entities, you end up scrolling down the page to select the field from the list. It would be nice if this could be improved similar to what is been done to the add filter field.  

**Describe the solution you'd like**
Add search capacity to the field, similar solution applied to the text field filter on the list. It would help a lot and improve user experience. 

**Describe alternatives you've considered**
Custom implemetation of the solution described above. 
<img width="960" alt="search add field" src="https://github.com/espocrm/espocrm/assets/19490674/d3bb05ab-d588-485e-96d2-286b5444e599">

**Additional context**

**Comment by yurikuzn** [comment]
I'll add to my backlog. Please prefer our forum for high-level features.

**Comment by rabiibrahimi** [comment]
sure 
thanks Yuri

**Comment by yurikuzn** [comment]
Implemented for v8.2.

**Comment by rabiibrahimi** [comment]
Great 
thanks @yurikuzn
