### ISSUE TITLE
webhook of notes are not propagating the field created_by_id...

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#2999]
**Describe the bug**
The field created_by_id of the notes are not being informed.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. create a webhook for note.create event
2. verify the posted payload, you will not see the field created_by_id.

**Expected behavior**
Information of all fields of the respective event

**EspoCRM version**
8.1.5

**Comment by yurikuzn** [comment]
I hacked to be able to create the hook. createdById was in the payload.

Note that steps to reproduce are not explicit enough.

**Comment by rodrigoscoelho** [comment]
[image: image.png]

Em qua., 28 de fev. de 2024 às 18:26, Yuri Kuznetsov <
***@***.***> escreveu:

**Comment by rodrigoscoelho** [comment]
Actually, just saw that I have the webook created, but it doesn't send any
info at all.
So, I created a workflow. In the workflow I'm not getting the createdById
info.

Please tell me how to hack the Note.create webhook event. Thanks

Em qua., 28 de fev. de 2024 às 18:26, Yuri Kuznetsov <
***@***.***> escreveu:

**Comment by yurikuzn** [comment]
Better not to use hacks but use workflows Send HTTP Request. If you create a topic on the forum with details of your problem our support can help.
