### ISSUE TITLE
Custom OptOut Link when EspoCRM is behind VPN

### ISSUE THREAD

**Issue by ykorzikowski** [espocrm/espocrm#3001]
Hi there, 

is there any option to customize opt-out links when espocrm can not be accesed via internet?

Usually, a link using the following pattern is attached: https://crm.vpn.XXX.XXX/?entryPoint=unsubscribe&emailAddress=XXX

But clients cant reach this link, as it can only be reached via a vpn connection. 

Maybe there should be a feature, where the link can be customized, so this endpoint can be explicitly opened to the www.

**Comment by yurikuzn** [comment]
We have only bug reports and feature requests templates on GitHub. Please do not remove issue templates.

We don't have the ability to customize opt-out URLs. But there's the ability to customize email messages via coding.

**Comment by yurikuzn** [comment]
I'll consider adding an alternative URL config parameter, but yet not sure.

**Comment by ykorzikowski** [comment]
**Is your feature request related to a problem? Please describe.**
Problem is, that the opt-out link can not be reached by people because espocrm is running behind a VPN. 

**Describe the solution you'd like**
Add an option t ocustomize the opt-out url, so e.g a custom nginx VHOST (optout.tld.com) will redirect opt outs to espocrm instance. 

**Describe alternatives you've considered**
Nonw

**Additional context**
Usually, a link using the following pattern is attached: https://crm.vpn.xxx.xxx/?entryPoint=unsubscribe&emailAddress=XXX


Good @yurikuzn ? :) So is the ticket closed now as not planned or do ou consider adding a config parameter? Or is there already one but I could not find it in the docs.

**Comment by yurikuzn** [comment]
There's no such an ability at the moment. I'll review this later when get a chance. Not sure whether a config parameter is a right choice.

**Comment by yurikuzn** [comment]
What exactly "to customize the opt-out url" implies? A custom domain name?

**Comment by ykorzikowski** [comment]
Yes, like the opt-out link e.g. https://optout.example.com/?emailAddress=XXX will internally call the original Espo Link e.g.  https://crm.vpn.xxx.xxx/?entryPoint=unsubscribe&emailAddress=XXX.

**Comment by yurikuzn** [comment]
It's already available: https://docs.espocrm.com/administration/config-params/#mass-email, `massEmailSiteUrl`.
