### ISSUE TITLE
Relationship Manager: Ability to specify select primary filter

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3002]
A primary filter to apply by default when selecting a record. The ability to specify this filter via the admin UI.

The configurable parameter: metadata > clientDefs > {EntityType} > relationshipPanels > {link} > selectPrimaryFilterName.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/8aa7236dd6fb85c9ed3ce9ded507292063cfca68

**Comment by bandtank** [comment]
Bro. Yes. I love this. Thank you.

**Comment by maxxatgit** [comment]
I cannot figure out how to do this. I have Espo 9.0.8 installed... can I _create_ a primary filter from the admin panel?

**Comment by maxxatgit** [comment]
OK, I see that I have to do some coding to create a primary filter.
Thank you for this amazing application!
