### ISSUE TITLE
Link is not hidden on the UI when the 'utility' property is set

### ISSUE THREAD

**Issue by arkadiyasuratov** [espocrm/espocrm#3004]
**Describe the bug**

Not sure if this is a bug or not, but I'm trying to hide the "Contacts" relationship from the "Target List" entity on the UI. I've tried to use the `utility` property, but it doesn't seem to work.

If it's a bug, then I believe this code should be added to JS. Let me know if I should create a PR.

<https://github.com/espocrm/espocrm/blob/8.1.5/client/src/views/admin/link-manager/index.js#L135>

```javascript
if (d.utility) {
    return;
}
```

**To Reproduce (MANDATORY, DO NOT REMOVE)**

1. Create `custom/Espo/Custom/Resources/metadata/entityDefs/TargetList.json`
2. Add the following content:
    ```json
    {
        "links": {
            "contacts": {
                "utility": true
            }
        }
    }
    ```

3. Go to Administration > Entity Manager > Target List > Relationships (/#Admin/linkManager/scope=TargetList).

**Expected behavior**

The "Contacts" relationship should be hidden.

**Screenshots**

**EspoCRM version**

8.1.5

**Additional context**

JSON schema: <https://github.com/espocrm/espocrm/blob/8.1.5/schema/metadata/entityDefs.json#L859-L862>

**Comment by yurikuzn** [comment]
Should not be hidden there. It should be hidden in layouts, reports, workflows, templates etc.
