### ISSUE TITLE
Problem in administration and roles

### ISSUE THREAD

**Issue by gn-sic** [espocrm/espocrm#3006]
**Describe the bug**
When I click on the role name (preview), I receive an error in the console and I cannot display anything.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Administration -> Roles
2. click on the role name

**Expected behavior**
role preview

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/162130021/0f6d1f14-48e9-40e4-a788-e8c1edecd365)

**EspoCRM version**
8.1.5

**Additional context**
The problem occurred after updating from version 8.1.4 to 8.1.5

**Comment by yurikuzn** [comment]
I could not reproduce.

**Comment by yurikuzn** [comment]
Anyone has this issue too? It's been a while since the release, it should have been reported already.

**Comment by arkadiyasuratov** [comment]
Just did an upgrade from 8.1.4 to 8.1.5 on our internal instance and also could not reproduce.

**Comment by yurikuzn** [comment]
From the small amount of information available I inferred that it could be that table.js file is from master (not yet released), table.tpl from the stable release. Do you use an official package or you build Espo by yourself?

**Comment by gn-sic** [comment]
I downloaded the file from the website https://www.espocrm.com/download/upgrades/ (EspoCRM-upgrade-8.1.4-to-8.1.5.zip) and updated it in the panel Administration ->Upgrade

**Comment by yurikuzn** [comment]
Did you enable developer mode in your instance?

**Comment by yurikuzn** [comment]
You should not use it on installed instances. Only if you work on repository or ext-template.

**Comment by gn-sic** [comment]
Could I fix it somehow?

**Comment by yurikuzn** [comment]
Disable developer mode. Use an official package.
