### ISSUE TITLE
Stream parts have no "leave the form" alert prevention to avoid losing data

### ISSUE THREAD

**Issue by filippogasbarro** [espocrm/espocrm#301]
In all the section of the CRM, in the stream field if you write something and you go in another page there isn't the pop up protection "are you sure to leave the form" of the browser

**Comment by donavynelliott** [comment]
I have no idea about the technical's' of this but another (possibly better) solution would be to keep in progress comments to the stream stored in the cache until posted. So when you come back to the page you were on you can keep editing. This would be extremely helpful say when looking at information in another part of the CRM in the middle of posting to the stream.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/514
