### ISSUE TITLE
Send test email UI bugs with port

### ISSUE THREAD

**Issue by nebulade** [espocrm/espocrm#3010]
**Describe the bug**
When an admin changes the email `smtpSecurity` dropdown. The port gets automatically reset to the usual default ports. However the issue is that the port now becomes a type string when sent further down to test the mail sending.

The test mail rest call would send this JSON:
```
{"server":"mail","port":"465","auth":true,"security":"SSL","use....
```

The REST api error handled at https://github.com/espocrm/espocrm/blob/master/application/Espo/Tools/Email/Api/PostSendTest.php#L91 gets triggered then. (This is correct)

Now clearing the port field and manually typing that value, the field correctly becomes a number. The input type is actually set to `text` rather than probably the more correct `number`

Furthermore if 4 digit ports are put in, it would render with a `.` or `,` depending on the locale: `2,525`

**Screenshots**
just for context where this is in the UI:
![image](https://github.com/espocrm/espocrm/assets/646768/637cbfd7-15d8-4c1e-b42e-f4abcc059b12)

**EspoCRM version**
8.1.5

**Additional context**
https://forum.cloudron.io/topic/10522/outbound-email-settings-being-overwritten-when-app-is-restarted/22

**Comment by yurikuzn** [comment]
![image](https://github.com/espocrm/espocrm/assets/1006792/0c323cf1-b311-41ac-9828-9de629b5a9f2)

I could not reproduce.

Bug report w/o steps to reproduce is my woe.

**Comment by yurikuzn** [comment]
Maybe your instance is broken. I assume JS error occurred before fields fully initiated. I tested multiple scenarios (had to, as absence of steps to reproduce made to try multiple ones), on two instances. Integer is sent.

**Comment by nebulade** [comment]
Ah sorry for not writing them in a list, I guess I thought the bug description outlines the steps already. Will reformat next time. 

There are no missing JS files or other Javascript errors reported in the browser console though. I tried to also adjust bandwidth to test if this might be a race or so, but also that didn't reveal anything further.

So that text input field should be of type `text` then and some other js code would do the formatting? Asking since https://github.com/espocrm/espocrm/blob/master/client/src/views/admin/outbound-emails.js#L131 appears to also set a string.

**Comment by yurikuzn** [comment]
That's why steps to reproduce are so important in bug reports for big apps. We have 3 different places where SMTP is configured. I tried two and forgot about existence of the 3rd. I'll look into.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/0832faa2f2d0a89c0faf6b12ff1dd53439f45606. Thanks for help.

BTW, it's possible to use Group Email Account as a system account. SMTP parameters in settings were considered by me as a legacy, that's why I forgot about them. In future it's likely that these settings will be forcibly migrated to a Group Email Account.

**Comment by nebulade** [comment]
Thanks for the quick fix and also the note about the Group Email Account, we will rework our app package startup script then to use that forward.
