### ISSUE TITLE
Calendar shows current time incorrectly

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#3014]
**Describe the bug**
I noticed that current time is shown incorrectly in calendar.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Open EspoCRM calendar (I used demo.espocrm.com)
2. Observe your current system time and observe current time as shown by calendar
3. Time is incorrect (by about +-40 minutes?)

**Expected behavior**
Calendar should display correct time

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/15276167/d0ebb06b-ee24-46f4-8901-790387dc3e55)

**EspoCRM version**
Latest EspoCRM (also happens on demo.espocrm.com)

**Additional context**
I am not sure when did this became an issue, but I recall seeing it correctly in version 7.5 (I think, I am not sure)
Happens across browsers: Firefox, Chrome, Safari for iOS

**Comment by yurikuzn** [comment]
Not reproduced.

Could you help with the fix?

**Comment by radek3911** [comment]
My colleagues mentioned it's also not reproducible for them, I'll try to debug more.

**Comment by radek3911** [comment]
So I don't know why but I switched to X11 from Wayland and it disappeared. Not sure if it had to do anything with wayland, but this is most likely out of EspoCRM scope.
