### ISSUE TITLE
Missing Assigned User Name in Note Create/Assign

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#3015]
**Describe the bug**
I've not been able to reproduce this bug and I don't know what causes it.
It seems that sometimes the assignedUserName will not be populated for Assign/Create note, leading to an unclickable assignedUser link as shown in the screenshot.
Seems to happen both if the record is assigned by system or by an user, even using workflow.
I am sorry for the lack of steps to reproduce, but I still didn't catch what causes this.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Create new record and assign it to an user or assign it after the record has been created
2. Sometimes the assignedUserName will not be populated
3. ...
...

**Expected behavior**
assignedUserName in the note should be populated.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/32223252/4fdaa829-9de1-4966-9468-9d205189af1a)
![image](https://github.com/espocrm/espocrm/assets/32223252/e39eca08-7549-4994-bd67-d88ec8324ebb)

**EspoCRM version**
8.1.5

**Additional context**

**Comment by yurikuzn** [comment]
Not clickable issue is already fixed.

It looks like you explicitly passed null in assignedUserName. This fix should help: https://github.com/espocrm/espocrm/commit/91d0660cba17f7fac2195996ef75f6efc5ae0844

**Comment by Kharg** [comment]
Not done explicitly.

by the way it seems to happen 100% of the times (And sporadically when assigned manually) with workflows (Advanced Pack 3.0.12), maybe this action doesn't pass the AssignedUserName?

Will update soon to the latest version of the Advanced Pack to check if that's the issue.

![image](https://github.com/espocrm/espocrm/assets/32223252/a70d203c-b15b-4eae-8720-8c78624a12a6)
