### ISSUE TITLE
Template helper in loop causes error

### ISSUE THREAD

**Issue by radek3911** [espocrm/espocrm#3016]
**Describe the bug**
When using template helper combined with multienum for loop to iterate it, espo throws a typesafety error and does not render the template.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Create an example template helper (I used 1:1 instructions here https://docs.espocrm.com/development/template-custom-helper/)
2. Create/edit entity: add multi-enum field, add field to layout
3. Create a template for given entity:
{{#each multiEnum}}
{{myHelper 'some text' color='#bd318e'}}
{{/each}}
4. Create a record in the entity, add some options in multi enum
5. Print
6. Observe espo log, notice the error

**Expected behavior**
Espo should iterate multi-enum and render template helper, note that rendering and iterating multi-enum without template helper (with just generic template content works)

**Screenshots**
N/A 

**EspoCRM version**
8.1.5

**Additional context**
Error given:
[2024-03-19 20:49:50] ERROR: Uncaught Exception TypeError: "Espo\Core\Htmlizer\Helper\Data::__construct(): Argument #4 ($context) must be of type array, string given, called in /tmp/lci_8aYDpD on line 18" at /home/x/public_html/application/Espo/Core/Htmlizer/Helper/Data.php line 74 {"exception":"[object] (TypeError(code: 0): Espo\\Core\\Htmlizer\\Helper\\Data::__construct(): Argument #4 ($context) must be of type array, string given, called in /tmp/lci_8aYDpD on line 18 at /home/x/public_html/application/Espo/Core/Htmlizer/Helper/Data.php:74)"}

There appears to be a mistake on [line 78 of Data.php](https://github.com/espocrm/espocrm/blob/ee3b0cb53d6eaf71a99019580d01c1a65319f2fa/application/Espo/Core/Htmlizer/Helper/Data.php#L78) file, I attempted to log the value of the context variable and it returns the option value of the currently iterated multi-enum. 

It can be fixed by removing typesafety on the context, although I am not sure what other issues this could potentially cause elsewhere.

**Comment by yurikuzn** [comment]
Thanks for reporting the issue. Fix: https://github.com/espocrm/espocrm/commit/2e550af1963076f9bd3d51eda0dbff57b02f42b8
