### ISSUE TITLE
Events not showing as all-day when they start and end on a same day of week

### ISSUE THREAD

**Issue by cezaryszymanski** [espocrm/espocrm#3017]
**Describe the bug**
When the event starts and ends in the same day of the week it is not shown as all-day event on calendar.

**To Reproduce**
1. Create task that starts on monday and ends on any further monday
2. Calendar shows this task in a wrong way

**Expected behavior**
Task should be shown as all-day event

**Screenshots**
<img width="739" alt="image" src="https://github.com/espocrm/espocrm/assets/104898426/a9e5db40-323e-4b09-9936-ef6bdbb3d8bb">

**EspoCRM version**
8.1.5

**Comment by yurikuzn** [comment]
Could not reproduce.

**Comment by bandtank** [comment]
I believe this is the same issue as what I described [here](https://github.com/espocrm/espocrm/issues/2861).

**Comment by yurikuzn** [comment]
By default, Tasks are not displayed spanning from start to end. Modifications in metadata required to enable this behavior that is not officially supported. If Fullcalendar has a parameter that automatically display events multi-day (more than 24h, as less would be preferable to display it as it is), I'd consider 'fixing' it.

**Comment by bandtank** [comment]
In my situation, the issue involved Calls, Meetings, and other Event type entities. It has been a while since I looked at the issue, so I'm not sure about the details at the moment. If I have time this week, I'll see if I can produce the issue with the latest version of Espo.

**Comment by yurikuzn** [comment]
In steps to reproduce, it's not clear whether Task has a time, or only a date. For everyone reading, please, I asked in many times, try to provide clear and detail steps to reproduce. So much times is spent on not clear bug reports.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/b91e40b0e773e747f0be7abb6ef8d919c68c2b20
