### ISSUE TITLE
Phone number extensions

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3022]
Supporting phone number extensions when international phone numbers are enabled. Must be enabled at Administration > Settings > Misc > Phone Number Extensions.

Can be entered with:

* `ext.`
* `x.`
* `x`
* `#`

Example: `+49 4333 633333 ext. 543`.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/89ff3dcf156f0de6cf40bca1ffc4f1e2625b3141

**Comment by emillod** [comment]
Hello!
can you tell me how it works with voip extension? It'll take extension number and enter it after call will be initiated?
Normally extensions are handled by entering phone with comma, like `+123456789,123` where 123 is an extension.

**Comment by yurikuzn** [comment]
Hi, It's maybe better to raise this question in the customer portal or on the forum.
