### ISSUE TITLE
array\indexOf() formula not working on 8.2.2 in docker (Installed by script)

### ISSUE THREAD

**Issue by trungtvmso** [espocrm/espocrm#3027]
**Describe the bug**
array\indexOf() formula not working, always return "null" value. Pls help to solves this issue asap.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/55830319/288151a5-9988-4102-b7cf-225d6b928229)
![image](https://github.com/espocrm/espocrm/assets/55830319/8e98b1cf-8843-4a6f-801f-704154a0a26e)

**EspoCRM version**
ESPOCR 8.2.2 in docker (Installed by script)

**Comment by trungtvmso** [comment]
I'm looking for the solution to fix this issue asap because this formula is currently requiring in almost my custom instant workflow.

Thank you team

**Comment by trungtvmso** [comment]
@yurikuzn pls help me

**Comment by arkadiyasuratov** [comment]
GitHub issues are not for free support. It's best to seek assistance on the forum, where you can also find developers for hire if you believe the issue is urgent. Remember, the software is provided without any warranty.

**Comment by yurikuzn** [comment]
You should use array\at. Your formula has a logical mistake. This issue evoked unnecessary stress to me, as we really had some changes in the formula parser. Would you compensate this stress so I could by some pills? :)

**Comment by yurikuzn** [comment]
Giving a star to the espocrm/espocrm repository will be appreciated. We have quite a lot of users already but so few GitHub stars.

**Comment by trungtvmso** [comment]
I'm so sorry because of posting issue here. I'm new here also just though that I could ask here. Will not do this anymore sir :( I'm retry with your suggestion.

Thank you so much.

**Comment by yurikuzn** [comment]
No problem. Giving a start would be appreciated. 
![image](https://github.com/espocrm/espocrm/assets/1006792/1905ca3e-4464-4352-8146-e730d1e48f4a)
