### ISSUE TITLE
Add the hour and minute of the task in the homepage widget (Like my activity)

### ISSUE THREAD

**Issue by filippogasbarro** [espocrm/espocrm#303]

**Comment by yurikuzn** [comment]
I don't understand. Date Due field is displayed at My Tasks dashlet.

**Comment by filippogasbarro** [comment]
Yes, the due field there is, but not the start field

**Comment by yurikuzn** [comment]
I see. We don't want to put it on there. You can modify the layout manually here application/Espo/Modules/Crm/Resources/metadata/dashlets/Tasks.json
