### ISSUE TITLE
OIDC ADMIN user unable to login after first login- /api/v1/App/user 500 (Internal Server Error)

### ISSUE THREAD

**Issue by amitmadahar** [espocrm/espocrm#3030]
**Describe the bug**
On OIDC configured CRM instance users are able to login using their organisation accounts without any issues. The reopeing of the CRM  after closing the browser window works. The issue happens only for ADMIN accounts. The OIDC works for other user types (tested).

Same machine:
1. If ADMIN user logouts and tries to log back in: Error 500  /api/v1/App/user 500 (Internal Server Error)
2. Goes to a different browser or incognito and tries to login: 500  /api/v1/App/user 500 (Internal Server Error)

Different machine:
1. ADMIN User still logged in on other machine and now tries to login at other system: Error 500  /api/v1/App/user 500 (Internal Server Error)

The issue has been described [here](https://forum.cloudron.io/topic/10906/serious-oidc-espocrm-issues) too but seems to be lost in noise of other OIDC issues that were fixed in the latest build.

**To Reproduce**
1. Configure OIDC on EspoCRM
2. Login using your organisational credentials
3. Ask another user to login too to check if OIDC works well.
4. Make yourself ADMIN > SAVE
5. Now logout
6. Login >  Error 500  /api/v1/App/user 500 (Internal Server Error)

**Expected behavior**
User should be able to login after logout.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/34081823/2579f0dd-c482-4cce-944c-1e8b1445dff4)

**EspoCRM version**
8.2.2

**Additional context**
1. Inbuild logins work ok
2. No Auth Tokens generated with user trying to login again which perhaps is the side effect of failing API call.

**Comment by yurikuzn** [comment]
> The issue has been described [here](https://forum.cloudron.io/topic/10906/serious-oidc-espocrm-issues)

Where exactly? Can't find it. As far as I remember, there was only 1 legit issue occurring on FF and some other browsers.

**Comment by yurikuzn** [comment]
I mean Espo log files.

**Comment by yurikuzn** [comment]
Internal error are often logged in the web server log.

**Comment by yurikuzn** [comment]
For information, we tested an 2 instances. Could not reproduce.

**Comment by amitmadahar** [comment]
Log is riddled with: Integrity constraint violation, Which is indeed correct as it should be unique. So it seems everytime a user logs in they are being recreated again.


ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ABC@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ABC@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xyz@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php  
ERROR: (23000) SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ABC@company.com-0' for key 'UNIQ_USER_NAME_DELETE_ID'; GET /App/user; line: 77, file: /var/www/html/application/Espo/ORM/Executor/DefaultSqlExecutor.php

**Comment by yurikuzn** [comment]
You can try to debug here: https://github.com/espocrm/espocrm/blob/8.2.2/application/Espo/Core/Authentication/Oidc/UserProvider/DefaultUserProvider.php. Maybe it does not find the user, and tries to create. Maybe you need to configure something.

**Comment by yurikuzn** [comment]
Does it happen only with admin user? You can also set log level to INFO for more details.

**Comment by amitmadahar** [comment]
That is correct I am admin. Have not tried on any other user type.

**Comment by yurikuzn** [comment]
Maybe you have not allowed admin users in authentication settings.

**Comment by amitmadahar** [comment]
Can you please elaborate? Is it on Azure App Registrants or in EspoCRM?

**Comment by yurikuzn** [comment]
In Espo. 
![image](https://github.com/espocrm/espocrm/assets/1006792/b4e9e8a1-2264-4c23-a9b4-b8b6b1fa0d23)

**Comment by amitmadahar** [comment]
God almighty! I feel so silly and stupid. I saw that not ticked like gazzlion times and never occured to me that it might be because of that.

**Comment by yurikuzn** [comment]
Can you confirm, that you first logged in then made the user admin. I did not foresee such scenario in the implementation. We should throw another user. Though with "INFO" log level it is logged I believe.

**Comment by amitmadahar** [comment]
I have two logins one is recovery login that uses ESPO authentication and I now have an organisation email login as well. I was made recently admin on that and I used my local ESPO login to change my organisational profile to Admin. 

Thats where it all started. I redeployed umpteen times as I though that my database is not getting read correct for users.
