### ISSUE TITLE
Stars

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3032]
The ability to star records.  Stars can be used by users to bookmark specific records.

* Can be enabled for a specific entity type in the Entity Manager.
* Once enabled, a primary filter *Starred* is automatically added.

![image](https://github.com/espocrm/espocrm/assets/1006792/70caef41-52ce-477b-8cd6-c4776bee84c0)

![image](https://github.com/espocrm/espocrm/assets/1006792/f8040787-7165-4b9b-9234-35e8c4b3e2c9)

Note: Administrators and users can add a custom tab that follows to the list view with the Starred filter applied.

**Comment by jeamado** [comment]
Could it be possible to have the star visible for each record in the List view of the related entity? As it works in gmail, for instance. Thanks a lot for your work.

**Comment by jeamado** [comment]
I elevated this consideration to you because it was the first question my users elevated to me, early today, after upgrading during the weekend.  I can see your point. The star is an atribute of one or more specific records, but only for each specific user. Having in mind not touching the layout, a solution can be using colors. Maybe having a different color for the row or for the selection checklist field, which is always fixed there by default in the most left of the list panel. Thanks again for listening your users.

**Comment by yurikuzn** [comment]
A solution I was considering is having a separate *Is Starred* field (automatically created when an entity type has Stars enabled). The field will be rendered as a star icon The admin can put this field on the list layout, disable a column label. This would be an elegant solution w/o hardcoding. I was considering colors too. Maybe in the future, not for the next release, as it's too already much work to be done.

**Comment by jeamado** [comment]
Thank you, Yuri.

**Comment by jeamado** [comment]
Thank you, Yuri. As far I can understand, a "starred/ no starred" record has to do with each individual user needs, like the "follow/no follow" condition. At the end of the day, both conditions have similarities in this filed. Given the case, both conditions could be needed to be shown in the List view. If we create a field which can be seen for anybody, all users will be seeing all the stars of all the other users. A bit confusing. Am I wrong or missing something?  Just for thinking for releases after next.

**Comment by yurikuzn** [comment]
No. The field will show only current users' value. I'd call it a day with stars for now  as I have many issues on my todo and have no capacity for one more.
