### ISSUE TITLE
Upgrading by replacing files and running migration

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3033]
An optional way to upgrade.

Steps: 

1. Replace all app files with files with files from a new version package.
2. Run `bin/command migrate`. It will run needed prepare and after-upgrade scripts, run rebuild. The version parameter in config will be updated.

Supposed to be used in docker installations.

**Comment by RoSk0** [comment]
This is an awesome feature! Thank you.

One thing to consider though, related to the 

> The version parameter in config will be updated.

Secure platforms are enforcing read only root file system . This means that the script will fail when it will try to update the version in the config file in at the run time.

I'm not familiar with the details of the version number usage from the config file, but can suggest to either read thatvfrom the code base or update during container image build.

**Comment by yurikuzn** [comment]
I'm not sure we can do it. We already have the config which is not read only. We already have the version parameter in the config which is not read-only from within the application. We have read-only default config which is read only and the current version will be taken from there. Using the version from the config was the most simple solution I could come up with.

**Comment by tmachyshyn** [comment]
If we are talking about docker implementation, all core EspoCRM files will be added while image build. The directories as `data` (where the config is located) and `custom` will be mapped to the host.
While starting the container, the entrypoint script will check the version, and run the `bin/command migrate`  in case it requires.

**Comment by eymen-elkum** [comment]
Just a note here, I had to run `php upgrade` first

**Comment by yurikuzn** [comment]
It's better to create a separate issue or a forum post.

**Comment by yurikuzn** [comment]
> I had to run php upgrade first

You mean rebuild?

**Comment by yurikuzn** [comment]
I added an additional rebuild before: https://github.com/espocrm/espocrm/commit/e26026c9ad0db4a09e2983161d5947f8a5b19c3b
