### ISSUE TITLE
Not unique table/alias error when Emails panel added to User detail view

### ISSUE THREAD

**Issue by RoSk0** [espocrm/espocrm#3035]
**Describe the bug**

Viewing individual user page, e.g. `/#User/view/6621d3623b980bd3e`, triggers `Error 500` red popup message on the frontend and `ERROR: (42000) SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'emailUser'; GET /User/6621d3623b980bd3e/emails; line: 77, file: /app/application/Espo/ORM/Executor/DefaultSqlExecutor.php` on the backend.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Install EspoCRM 8.2.2
2. Log in as the `admin` user
3. Navigate to the `Administration` > `Layout Manager`
4. Select `User` >  `Bottom Panels`
5. Drag `Emails` from the `Disabled` into `Enabled` and save
6. Navigate to the `Users`
7. Click on the `Admin`
8. Observe the error

**Expected behavior**
No errors

**EspoCRM version**
Observed in version 8.0.6 and 8.2.2 .

**Additional context**

- PHP 8.1 
- MySQL 5.7

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/0819b69d4a03670cccbd1d65d8582941f976506d

**Comment by RoSk0** [comment]
@yurikuzn I believe there is an issue in your commit . Please check https://github.com/espocrm/espocrm/commit/0819b69d4a03670cccbd1d65d8582941f976506d#r141250727
