### ISSUE TITLE
Add dashlet quick search not working for portal

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#3037]
**Describe the bug**
Using the search field for dashlet in the portal user interface doesn't work
`Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at espo-main.js:62415:47
    at Array.forEach (<anonymous>)
    at s.processQuickSearch (espo-main.js:62414:24)
    at keyup input[data-name="quick-search"] (espo-main.js:62358:14)
    at HTMLDivElement.dispatch (jquery.js:5136:27)
    at f.handle (jquery.js:4940:28)`

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Navigate to #Admin/portals
2. Create a new portal
3. Go to User Interface tab
4. Edit the dashboard layout to add a new dashlet
5. Use the search feature
6. search will not filter results, error will be logged in the browser console

**Expected behavior**
Search should filter results.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/32223252/32bc4757-1893-4a3e-a7b8-e6e93224ffaf)

**EspoCRM version**
8.2.3

**Additional context**
The dashlet search correctly works in the dashboard

**Comment by yurikuzn** [comment]
Fixed: https://github.com/espocrm/espocrm/commit/540c58a56461aab43d07ef7b8924b8bf2d14de8d
