### ISSUE TITLE
Roles: Mention permission

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3039]
A new permission. Allows to mention other users in the Stream.

* all – can mention all;
* team – can mention only teammates;
* no – cannot mention.

Before, the *Assignment Permission* was used. But one may need to disable the ability to assign but allow the ability to mention.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/665dd2f242eb5acf866b1618a24fc1113dce572b

**Comment by rabiibrahimi** [comment]
very useful thanks 👍
