### ISSUE TITLE
memory leak When modify entity field in the admin page

### ISSUE THREAD

**Issue by zhuyicheng666** [espocrm/espocrm#3042]
**Describe the bug**
memory leak When modify entity field in the admin page
url: /#Admin/fieldManager/scope=Account&type=text&create=true

**To Reproduce (MANDATORY, DO NOT REMOVE)**
In this page /#Admin/fieldManager/scope=Account&type=text&create=true, create a new field  or 
In this page /#Admin/fieldManager/scope=Account&field=accountNature, modify the label.
**Expected behavior**
The page is running normally and a "Saved" prompt appears.

**Screenshots**

**EspoCRM version**
8.2.0

**Additional context**
We have discovered that a statement [this.off('sync');]  is missing in the load function within client/src/language.js, but it is present in client/src/metadata.js.

**Comment by yurikuzn** [comment]
What do you mean by 'memory leak'. I tried on two instances, the "Saved" alert appeared. It does not appear for you? What exactly happens?

**Comment by zhuyicheng666** [comment]
My chrome will be frozon and nothing responds when I click on anything。

**Comment by yurikuzn** [comment]
Any JS errors in the browser console?

**Comment by zhuyicheng666** [comment]
no。Chrome has frozen due to an infinite loop.

**Comment by yurikuzn** [comment]
Strange. I'll try to figure out but the fact that I can't reproduce complicate things. Does it happen only if you change the label or happens if you change any parameter?

Could you point where exactly the loop happens?

**Comment by zhuyicheng666** [comment]
When I add  `this.off('sync');` in the function  load  which in the client/src/languages  and the problem has solved.  The whole function is 

 load(callback, disableCache, loadDefault) {
        this.off('sync');
        if (callback) {
            this.once('sync', callback);
        }

        if (!disableCache) {
            if (this.loadFromCache(loadDefault)) {
                this.trigger('sync');

                return new Promise(resolve => resolve());
            }
        }

        return new Promise(resolve => {
            this.fetch(loadDefault)
                .then(() => resolve());
        });
    }

the loop i think is about 'sync' event.

**Comment by yurikuzn** [comment]
Thanks for info. Do you have any custom code that calls the *load* method of the language object?

**Comment by zhuyicheng666** [comment]
No custom code. I set 'useCache' => true in data/config.php and in production mode.

**Comment by yurikuzn** [comment]
I checked the whole codebase and have not found the 'sync' event being used on the language object. The 'callback' is never passed (it's deprecated). No idea why this happens on your instance. I might be add the 'off' for v8.2 hotfix, but need to refactor the method for the future versions so that only promise is used.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/bfed154feb252e96943deb6a02b6aa457e0d5f50

**Comment by zhuyicheng666** [comment]
I found that in client\src\ui\select.js there is a callback
```
/**
     * Set options.
     * @todo Side effects may occur if called multiple times. Workaround is to re-initialize. To be fixed.
     *
     * @param {Element|JQuery} element An element.
     * @param {{value: string, text: string}[]} options Options.
     */
    setOptions: function (element, options) {
        const $el = $(element);

        const selectize = $el.get(0).selectize;

        selectize.clearOptions(true);
        selectize.load(callback => {
            callback(
                options.map(item => {
                    return {
                        value: item.value,
                        text: item.text || item.label,
                    };
                })
            );
        });
    },
```
But I'm not sure if it's related to this issue.

**Comment by yurikuzn** [comment]
It's not related. It's another object.

**Comment by zhuyicheng666** [comment]
In client\src\views\site\navbar.js  
``` 
this.listenTo(this.getHelper().language, 'sync', () => update());
```

**Comment by yurikuzn** [comment]
This could be a reason.

**Comment by zhuyicheng666** [comment]
maybe something wrong where excuting '() => update()' .because if not removing the listener on language, it may add a same one on it when update()

**Comment by yurikuzn** [comment]
Yes. It's possible that code fails within update() execution, and then not proceeded to `return new Promise(resolve => resolve());` in the load method. But usually it should be seen in the console log.

**Comment by eymen-elkum** [comment]
@zhuyicheng666 do you have 3rd party extensions
