### ISSUE TITLE
Application log available from admin UI

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3047]
Can be enabled in `config-internal.php`:

```
'logger' => [
    ...
    'databaseHandler' => true,
],
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/e0909af3fe209c9d5b1d6a5f5fc689deeb4af1c2
https://github.com/espocrm/espocrm/commit/b006349528d732a3910c0c75e14d7fe6e434f7a1

**Comment by Kharg** [comment]
Any screenshot of the feature? :)

**Comment by yurikuzn** [comment]
![image](https://github.com/espocrm/espocrm/assets/1006792/e6d8a623-b3dd-47d0-8d9d-1b8bf23ef0e6)

**Comment by Kharg** [comment]
This is awesome!

if the message is too long will you be able to go in detail view (like a record) to read it all/see more details?

**Comment by yurikuzn** [comment]
Yes, but there won't be long messages. Traces and SQL won't be available here.
