### ISSUE TITLE
Formula: Equal operator (=) inside string literal causes "Syntax error: Bad variable name"

### ISSUE THREAD

**Issue by act4pal** [espocrm/espocrm#3048]
**Describe the bug**
Formula script: "Syntax error: Bad variable name" is raised if a string literal contains an equal operator `=`.

**To Reproduce**
Explicit steps to reproduce the behavior:
1. Go to **Administration** → **Formula Sandbox**
2. Write `$var = '=';`
3. Click **Check Syntax** 

**Expected behavior**
_"Syntax is correct."_ should be displayed.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/167753375/5240c868-20a4-47bf-9a19-2f338852bff2)

**EspoCRM version**
8.2.3

**Additional context**
It appears that the issue started after this commit [55dd4ec](https://github.com/espocrm/espocrm/commit/55dd4ecf749810fd95e37628d73adb5f3534607a).

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/cbec1cbbe5dcd52616e99766b9cb7577f0e6352c
