### ISSUE TITLE
Pinned notes

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3051]
Pinned notes in the Stream panel. Pinned notes are displayed dubbed in the top, before the list.

Users with edit access can pin and unpin notes. The max number of pinned notes is controlled by a config parameter.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3fc4b487b3d9df0ad6f55e437dac282b27478811

**Comment by Kharg** [comment]
I dreamt this for so long.

Thank you for caring about the community feedback.

This is why Espo is the best CRM available!

From the code I can see that it will
Also allow to pin Sent and Received emails, right?

Super useful!

**Comment by yurikuzn** [comment]
> pin Sent and Received emails, right?

Right.

**Comment by Kharg** [comment]
> I notice it just pin Note, can we pin Record?

No, but you will be able to “Star” records with a different feature, which is a good solution.

**Comment by jeamado** [comment]
Could it be possible to have each user pinned the notes as her/his preference? I noticed that when one user pins a note, it is shown pinned for all the others, even having they the ability to unpin others pinned notes. Many thanks, Yuri.

**Comment by yurikuzn** [comment]
It's by design, a note is pinned for all. An *edit* access to a record is required to be able to pin/unpin. So unwanted unpins should not be problem .

**Comment by jeamado** [comment]
Thanks for your fast response. I thought in cases when there are several users having editing rights to the same record, maybe in deferent panels or tabs, and each one has its own criteria about what notes or emails are relevant to have fixed on top, or no pinned at all. Something like whatsapp contacts works. Nevertheles I understand your point and feel gratefull for these kind of enhancements. . Thanks again.
