### ISSUE TITLE
Option for API to return array and not object

### ISSUE THREAD

**Issue by rouhu** [espocrm/espocrm#3052]
**Is your feature request related to a problem? Please describe.**
To make a custom module available in Zapier, the API needs to return an array but it returns an object

**Describe the solution you'd like**
There should be API header variable: X-Return-Array: true

**Describe alternatives you've considered**
Not known

**Additional context**
I believe this was somehow solved with the Zapier integration with the Leads API calls

**Comment by yurikuzn** [comment]
Returning array is not right. GET sends object, POST/PUT returns object. Which is symmetrical. We'd better not to adopt APIs for specific cases. You can modify the response in Zapier action, wrapping the object into an array.

**Comment by rouhu** [comment]
Yes, indeed, it is possible to activate "code mode" in Zapier and then manipulate the return object. Here is how it works:
`const options = {
  url: 'http://mycrm.com/api/v1/PurchaseOrders/6633509f45bcd12d6',
  method: 'GET',
  headers: {
    'X-API-KEY': bundle.authData['Api-Key'],
    'Accept': 'application/json',
    'X-No-Total': 'true'
  },
  params: {

  }
}

return z.request(options)
  .then((response) => {

     response.throwForStatus();
 const result = z.JSON.parse(response.content);

 return [result];
    
  });`
