### ISSUE TITLE
URL with tilde character fails validation

### ISSUE THREAD

**Issue by bkidwell** [espocrm/espocrm#3053]
**Describe the bug**
If you paste a URL with a tilde into a field of type URL, the value fails validation.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Go to any record with a field of type URL.
2. Paste `https://www.unix-ag.uni-kl.de/~bloch/acng/` into it.
3. Save.
4. Receive validation error message: "[field name] is invalid".
5. Remove the `~` from the value.
6. Save.
7. No validation error.

**Expected behavior**
A URL with a tilde in it is a valid URL. This value should pass validation.

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/723919/cc163b7d-99a1-4c40-89b8-778fbe27fc93)

**EspoCRM version**
EspoCRM 8.2.3

**Additional context**
If you go to a `https://www.unix-ag.uni-kl.de/~bloch/acng/` in your browser, the Address Bar treats it as a normal URL, without URL-encoding the `~`.

**Comment by yurikuzn** [comment]
Fixed: https://github.com/espocrm/espocrm/commit/1f3a0bb5dd284b30f1a6fac7c63d2c1da6dfe2bf
