### ISSUE TITLE
pdfTemplates : Error if body of header or footer empty and checkbox checked

### ISSUE THREAD

**Issue by libremaster** [espocrm/espocrm#3055]
Hello,

At the bottom of the page to edit a PDF template, if header or footer is checked but the body is empty, then PDF can't be generated and an error appear.

I used it via API only, i have the error detail but it contains URL so I give it in private only but here the beginning :

`
[2024-05-07 19:40:37] ERROR: Slim Application Error Type: ValueError Code: 0 Message: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty File: /var/www/users/xxxxxxx/app/application/Espo/Core/Htmlizer/Htmlizer.php Line: 853 
......
`
I searched what is the problem and the variable $template is empty here : 
$loadResult = $xml->loadHTML($template);

I think you should add a test to check if body template is empty (null inside database I think) at the same level you check "print header" or "print footer".

I made a picture for someone else, there is some french but I give it :

![bug-espocrm](https://github.com/espocrm/espocrm/assets/55919603/e9a434c7-e572-4c3d-8141-3dc691d399f5)

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/0bcbfdd223a67a69ea6f6c05b5fe7bcd508cf8fc
