### ISSUE TITLE
List (Small) - CSS Layout - Width Size px Overflowing

### ISSUE THREAD

**Issue by o-data** [espocrm/espocrm#3056]
**Describe the bug**
For Layout > Small (List) > when you use px Width and it go over a certain size it overflow location.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. [Go to ](https://demo.us.espocrm.com/?l=en_US#Admin/layouts/scope=Contact&type=listForAccount&em=true)
2. Edit the 3 default field (Name, Title, Email) to have Width to be 250 px (or higher)
3. Save Layout
4. Refresh and go open any Accounts with Contact linked. For example: https://demo.us.espocrm.com/?l=en_US#Account/view/5f5b2be3355a2388b

**Expected behavior**
Width to not overflow or a "horizontal scrollbar?"

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/67723461/90386e94-4c54-42ff-a4ea-dfccdc80abab)
![image](https://github.com/espocrm/espocrm/assets/67723461/fce54445-32db-4cb6-88b0-b45dcf5622ff)
![image](https://github.com/espocrm/espocrm/assets/67723461/ac1e9475-cacb-4f51-a7d5-a6d5d89f2926)
![image](https://github.com/espocrm/espocrm/assets/67723461/478ee1ef-35f8-4348-bd30-c654e7893f55)

**EspoCRM version**
Version 8.2.4

**Additional context**
Not sure how you can fix this here. You might have to restrict PX width or add note or something.

**Comment by yurikuzn** [comment]
It would be difficult to fix w/o breaking other things. I would leave it for now.

Scrollbar – would be a big endeavor to implement.
Hiding overflowed content – will cause issues with dropdowns and other things.

**Comment by yurikuzn** [comment]
If anyone suggest a simple solution, I'll appreciate.
