### ISSUE TITLE
Address country list

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3059]
The admin can add country names with their ISO 3166-1 alpha-2 codes. Countries can also be imported from a CSV. Added countries will be available in autocompletion. Counties marked as preferred will be displayed first (on empty input).

A default predefined country list with English names can be optionally loaded.

Future application: The ability to obtain the ISO 3166-1 code from an address field. Needed for e-invoicing.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/a1d5174372d61b186fa34d2c465c67ee739b9723

**Comment by rabiibrahimi** [comment]
could this be enhanced in future to include Address city list with some sort of mapping between each country and its cities. maybe using https://countriesnow.space/

**Comment by yurikuzn** [comment]
In the future. One would need to import a CSV of States and/or Cities.
