### ISSUE TITLE
User Login Time Frame Restriction

### ISSUE THREAD

**Issue by radeoncode** [espocrm/espocrm#3061]
**Is your feature request related to a problem? Please describe.**

Yes, the feature request is related to addressing a potential security vulnerability and adapting to the changing work dynamics, particularly in the post-COVID-19 era where remote work has become prevalent. By restricting user login based on defined time frames, the feature aims to enhance data security by ensuring that users can only access the system during specified work hours, thus reducing the risk of unauthorized access outside of designated times.

**Describe the solution you'd like**

The solution I am proposing involves implementing a feature that allows administrators to define multiple time frames during which users can log in to the system. Users attempting to log in outside of these specified time frames would be denied access. This solution provides administrators with greater control over user access and enhances data security by restricting login privileges to designated work hours.
I recently noticed the update regarding the enhancement of the user login process with the introduction of IP address whitelisting (#3054), which I must commend as a fantastic improvement. Building upon this enhancement, I would like to propose the addition of a feature that allows for user login restriction based on defined time frames.

**Comment by yurikuzn** [comment]
With authentication hooks it's possible to implement an extension or just a simple customization in form of just 2 files.

https://docs.espocrm.com/development/metadata/app-authentication/

**Comment by yurikuzn** [comment]
BTW, I think it's became opposite post covid. Now we tend to work w/o a specific time schedule.

**Comment by radeoncode** [comment]
But still many company allows the user to work on schedule basis . We dont want to allow the user to login or access data after their working hours.
Is there any chances adding this features to core ? So that non technical user will also able to use from setting .

**Comment by yurikuzn** [comment]
I don't think we will implement this feature.

**Comment by Kharg** [comment]
There's an extension that does just this by using the working time calendar to restrict users login:
https://bpm4b.com/downloads/timeguard/

**Comment by yurikuzn** [comment]
I can also recommend considering finding a developer or as a community to implement a simple extension. Timeframes could be defined in a config manually (to make thinks easier to implement). A hook will check the current time, the current user and throw an exception if time is wrong and the user is not admin.
