### ISSUE TITLE
Mass Unfollow not using the translation in Global.json

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#3062]
**Describe the bug**
The mass unfollow action is not using the "unfollow" translation contained in Global.json
https://github.com/espocrm/espocrm/blob/7ebcc6c71affaf521f3bd95a414998ff0e7036d3/client/src/views/record/list.js#L1574

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Set EspoCRM to any another language than English
2. Go to an entity List view
3. Select 1 or more records
4. Click the Unfollow Mass Action
5. The button to confirm the mass action will not be translated
...

**Expected behavior**
Expecting the button to use the correct translation from Global.json

**Screenshots**
![image](https://github.com/espocrm/espocrm/assets/32223252/1d9b2331-39d9-40e8-8f34-d1732f464364)

**EspoCRM version**
8.2.4

**Additional context**
The error message that appears when only one record is selected for merging is also not translated "Select 2 or more records"
![image](https://github.com/espocrm/espocrm/assets/32223252/b0360226-7555-4967-a236-6408f5443801)

**Comment by yurikuzn** [comment]
Fixed: https://github.com/espocrm/espocrm/commit/73f88bc097e9110086826e8e600e9963abd73cef

**Comment by Kharg** [comment]
Thank you Yuri, will you update POEditor soon? There are a lot of new strings to translate.

**Comment by yurikuzn** [comment]
Closer to v8.3 release.
