### ISSUE TITLE
Failed opening required 'vendor/autoload.php'

### ISSUE THREAD

**Issue by strk** [espocrm/espocrm#3063]
Following the install instructions in https://docs.espocrm.com/administration/installation/#4-run-espocrm-installation-wizard
I end up with a failure opening the required `vendor/autoload.php` file. The `include_path` is reported to be only the "root" directory (where I installed the softare) while the `vendor` dir is in an `install` subdirectory.

**Comment by strk** [comment]
This also happens for tag 8.2.4

**Comment by arkadiyasuratov** [comment]
If the `vendor` directory is missing, it seems you grabbed the source files rather than a release version packaged in a .zip file.

**Comment by arkadiyasuratov** [comment]
https://docs.espocrm.com/development/how-to-start/#option-a-using-git-repository

**Comment by yurikuzn** [comment]
All questions are covered in readme and docs.

**Comment by strk** [comment]
ok sorry for the noise, and thank you
