### ISSUE TITLE
Multiple Assigned Users does not work due to 'c' prefix

### ISSUE THREAD

**Issue by o-data** [espocrm/espocrm#3067]
**Describe the bug**
Due to the "c" prefix that get added in v8.2 - the Multiple Assigned Users feature does not work.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Reference: https://forum.espocrm.com/forum/general/106368-multiple-assigned-users-not-working-as-of-8-2#post106495
2. Reference: https://docs.espocrm.com/administration/multiple-assigned-users/
3. Try to create the relationship and Multi Assigned Users using link **2. Reference**: https://docs.espocrm.com/administration/multiple-assigned-users/
4. It will not work because the "c" prefix get add after saving
5. To make it work EspoCRM need to update that will make it work with this "c" prefix. Or to disable "c" prefix in **config.php** file, create this and then enable to again.

**Expected behavior**
Multiple Assigned Users to work as per documentation

**Screenshots**

**EspoCRM version**
v8.2.2

**Additional context**
Work around method is posted in the forum.

**Comment by Kharg** [comment]
@yurikuzn I think that the same bug applies to the Location field for the Google Integration.

maybe an exclusion list could be defined in the global metadata to avoid applying the prefix to certain names?

it would be useful for extension developers as well.

**Comment by yurikuzn** [comment]
It was a mistake to add the assigned users functionality the way it is  in a first place. It won't be fixed soon. It was a design mistake.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/documentation/commit/5a92e1b6329b219e38faa78194b68607cdb27a4c

**Comment by hturkoz** [comment]
Please Yuri, don't remove this feature.. maybe make a pool on forum for see "yes" or "no".
I never interact on github, but for this functionality, i must and i have too use google translate :)

**Comment by yurikuzn** [comment]
We won't remove as it's widely used.
