### ISSUE TITLE
Reminders only for self

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3070]
Before, when specifying reminders for an Event or Task, these reminders were applied for all participants (an assigned user in case of Task). A user could create undesired reminders for another user.

Now, specified reminders, will be applied only for an own user (the field will be hidden if creating an event for another user). For other users, their default reminders (defined in Preferences) will be automatically applied.

In the future, this functionality may be extended, so that users could modify their reminders even without having *edit* access to an event.

**Comment by bandtank** [comment]
What about group events such as meetings with many attendees? Is there a way to set a reminder for all participants or is the configured reminder only for the createdBy user?

**Comment by yurikuzn** [comment]
Not yet. Only reminders for a current user are listed. Before, it was something in between, but not reliable.
