### ISSUE TITLE
API - Email - folderId - not mapping correctly - GET and POST 

### ISSUE THREAD

**Issue by mullerpetr76** [espocrm/espocrm#3071]
**Describe the bug**
By using Emails via API, folders are not mapped / presented / used correctly.
In GET operation is folderId still null, also for email in sent or inbox
In POST, when I set "folderId": "sent", the email is not folder sent. It is in inbox or none.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. API: GET /api/v1/Email
2. Response:
{
    "total": -2,
    "list": [
        {
            "id": "665c21964151f3cdb",
            "name": "OPT generated manualy 4",
            "deleted": false,
            "subject": "OPT generated manualy 4",
            "fromName": "HomerBee support",
            "fromAddress": "support@homerbee.cz",
            "fromString": "HomerBee support <support@homerbee.cz>",
            "replyToString": null,
            "replyToName": null,
            "replyToAddress": null,
            "addressNameMap": null,
            "personStringData": "To: zombbieM09@namiste.cz",
            "isRead": true,
            "isReplied": false,
            "isImportant": false,
            "inTrash": false,
            "folderId": null,

Explicit steps to reproduce the second behavior:
1. API: POST /api/v1/Email
2. Body: 
{
    "from": "support@XY.com",
    "to": "ABC@gmail.com",
    "status": "Sending",

    "name": "Name",
    "deleted": false,
    "subject": "Sobject",
    "fromName": "EspoCRM",
    "fromAddress": "support@XY.com",
    "fromString": "EspoCRM <support@XY.com>",
    "folderId": "sent",
3. Email is not in any folder.

**Expected behavior**
In the GET operation should be folderId not null if the email is in some folder. In the folderId should be than identified of the folder. For example: "inbox", or "sent", or other.  
In the POST: When the request include "folderId": "sent", it will be stored into the folder Sent.

**Screenshots**
Not needed

**EspoCRM version**
Version 8.2.3 (from Bitnami on AWS)

**Additional context**
If you deliver to latest version, please share hotfix (what to change in the local code)
Many Thanks Petr

**Comment by yurikuzn** [comment]
> By using Emails via API, folders are not mapped / presented / used correctly.

Is not supposed to. There's many such non-storable fields that are not available via API by design.

**Comment by mullerpetr76** [comment]
This is extremely important parameter. When you use API, email shold be directed to some directory.

**Comment by yurikuzn** [comment]
I don't know what to tell. It seems to me that you don't understand details of how the emails functionality is implemented in EspoCRM and tell me how this parameter should work. It's not possible to map the email to a folder by design. One email record can be in different folders for different users. Sorry, but I don't have time to continue.

**Comment by yurikuzn** [comment]
`POST https://your_url/api/v1/Email/inbox/folders/your_folder_id` 

```json
{
    "id": "your_email_id"
}
```

This request will move an email to a user folder for a current user.

But you CAN NOT move to "sent" folder, there's no sent folder in Espo, it's an abstract folder.
