### ISSUE TITLE
Field level inline editing functionality

### ISSUE THREAD

**Issue by conceptmedical** [espocrm/espocrm#3077]
**Describe the bug**

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Even if the scope level has beeen defined to each only permission
1. I can edit & update the teams in case object.
2. Field level editting is enabled in case
...

**Expected behavior**
As per the scope defined in Role it should not be enabled for editting specific to the user under Teams & Roles

**EspoCRM version**
Current version: 8.2.5

**Comment by yurikuzn** [comment]
It's not clear for me. Steps to reproduce would have been helpful.

**Comment by yurikuzn** [comment]
Will be reopened if we get steps to reproduce and it will expose not a designed behavior.

**Comment by conceptmedical** [comment]
> It's not clear for me. Steps to reproduce would have been helpful.

I'm manipulating the users rights by Roles. Here I have attached the roles where I'm only giving view permission in case but the user can still able to edit the records.

![permission-issue](https://github.com/espocrm/espocrm/assets/173148374/ece6ed64-3c89-47c4-bb26-3da7834ddf04)

**Comment by yurikuzn** [comment]
Check what access is applied for a user. Users > {User} > Access button. It will show actual access levels which is inferred by merging all roles.

**Comment by conceptmedical** [comment]
pls find the Access Rights, still inline editing is working
![Uploading screencapture-ACCESS Rights-2024-06-19-12_15_05-edit.png…]()

**Comment by yurikuzn** [comment]
I could not reproduce. But as the issue description is not clear and no steps to reproduce provided I can't be sure.  I can't spend time on issues there are not clear.
