### ISSUE TITLE
List view does not update on many-to-many relationships

### ISSUE THREAD

**Issue by andrewvaughan** [espocrm/espocrm#3081]
**Describe the bug**
Per the documentation here:
https://docs.espocrm.com/administration/layout-manager/#list-small

I expected the `list small` configuration to update the fields that are shown in foreign relationships. In my case, I have an Entity called `Person` with a many-to-many relationship to an Entity called `Residence`.

I don't use the default `name` field in `Residence`, so I have it marked non-required and is hidden in my layouts.

I have setup my `list small` configuration as follows:

![Screenshot 2024-06-21 at 12 29 42 PM](https://github.com/espocrm/espocrm/assets/1119590/ead8df7d-ecfd-485a-8b6e-1088028a70db)

However, when you view the relationship in the `Person` panel, you get the UUID for the entry (which I presume is the default `name` when none is entered):

![Screenshot 2024-06-21 at 12 30 35 PM](https://github.com/espocrm/espocrm/assets/1119590/ff2f5a7c-5e8f-43e3-9419-9b4af164f7b3)

As configured:

![Screenshot 2024-06-21 at 12 31 10 PM](https://github.com/espocrm/espocrm/assets/1119590/0d979eef-52c4-4d77-968f-7e3d35bd820a)

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Create a many-to-many relationship between two Entities
2. Update the `list small` on one Entity
3. Add that Entity to the `details` layout on the other Entity

**Expected behavior**
The fields as configured in the `list small` should appear in the foreign relationship.

**Screenshots**
See above.

**EspoCRM version**
`v8.2.5` (the latest available Docker image - is there a reason the Docker images are on a release delay, given the formal update recommendations are to do a `docker pull` to update?)

**Additional context**
Thanks!

**Comment by andrewvaughan** [comment]
If it matters, the `Address` field is marked as the "Link" in the configuration.

**Comment by andrewvaughan** [comment]
This bug may be due to (or in addition to) the fact that the `address` field shows "None" for some reason in other list views. For example if, if I set my `list` view to:

![Screenshot 2024-06-21 at 12 48 33 PM](https://github.com/espocrm/espocrm/assets/1119590/c5b05bef-b6e7-4320-8eb9-29076deebe9c)

This is the type of result:

![Screenshot 2024-06-21 at 12 48 58 PM](https://github.com/espocrm/espocrm/assets/1119590/b4455bb5-47f8-4452-b9ed-6f3e74746256)

This may be a secondary bug, though.

**Comment by yurikuzn** [comment]
This is not a bug. The Name field is used for link and link-multiple fields. If no name, fallback to ID.

The system won't check any layouts. This would be overengineering. Such issues should not be considered as bugs.

**Comment by andrewvaughan** [comment]
@yurikuzn your documentation explicitly states:

> List (Small)[¶](https://docs.espocrm.com/administration/layout-manager/#list-small)
> 
> The list layout for relationship panels. Also, it can be used in other places where it's reasonable to display lists in the narrow view.

What the heck does the `List (Small)` layout do, then?

**Comment by yurikuzn** [comment]
For relationship panels, which can be added in the Bottom Panel layout. And for other list views which are too narrow to display the full List layouts. 

On your screenshot I see a link field, no list view.

I suggest our forum to ask questions too get more familiar with the system.

There are workarounds for your issue. E g using formula to set a name with other field.

**Comment by andrewvaughan** [comment]
Pretty disappointed by this response. If I understand correctly, you're telling me that view only works for `one-to-*` relationships only, although that is not documented.

Per your recommendation - the codebase isn't particularly complex, I feel fairly comfortable in discourse with you. I had setup the recommended formula approach for my client as an anti-pattern while waiting for the response here. I'm not sure how people are just supposed to "know" that their layouts won't work for N-N relationships from the documentation.

I don't call this an anti-pattern lightly. I won't question your decision that this is over-engineering, but it is confusing to me that the alternative would be to point to a fully-custom, comprehensive scripting implementation as an alternative. It sounds dangerously close to a "catch all" for bad or half-implemented functionality.

For anyone who comes across this issue in the future with a similar issue, here is a similar naming formula you might use:

```
name=string\concatenate(
    datetime\year(moveInDate),
    "-",
    ifThenElse(
        datetime\year(moveOutDate) > 0,
        datetime\year(moveOutDate),
        "Present"
    ),
    " - ",
    addressStreet,
    ", ",
    addressCity,
    ", ",
    addressState,
    ", ",
    addressCountry
)
```

It is very kind for this to be called a "workaround." You have a feature (Layouts) that works in some cases but not all, and the only way to have your records read reference (emphasis, _read_) correctly on those views is to create your own code to update the record on _write_. That's a classic anti-pattern - you have a user with a read-based, and your solution is write-based.

Finally, if you care, just a reminder here that your `address` record type is still showing `None` on all lists, too. I'd recommend removing it from the Layouts screen as an option, if it isn't intended to be supported, or updating the renderer.

**Comment by andrewvaughan** [comment]
Finally, I forgot to respond to one thing you mentioned:

> On your screenshot I see a link field, no list view.

I think you may be referring to my follow-up comment, not my original post. Please read both.

**Comment by yurikuzn** [comment]
Steps to reproduce are not explicit enough to say for sure. You mentioned Detail layout. You provided the screenshot with a link multiple field on detail view. 

To see the list small layout in effect, add your link in the Bottom layout.

If need a non antipattern solution for link fields, you can do it with code customization.

I'm not here to satisfy, my previous response explained how the system works.

**Comment by andrewvaughan** [comment]
> I'm not here to satisfy, my previous response explained how the system works.

As is your right - although this did just help us in our discovery process between HubSpot and EspoCRM. Best of luck in your endeavors.

**Comment by yurikuzn** [comment]
Right choice. Good product.
