### ISSUE TITLE
Emails: Import EML

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3082]
The ability to create an Email record from an EML file. Requires access to the *Import* scope.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/5a937222326f4adf6c364b951a5ae4148b264bec

**Comment by Kharg** [comment]
Will it also allow to import attached eml directly from a received email?

It may partially solve #2722

**Comment by yurikuzn** [comment]
It will work the same way as emails are imported from IMAP but manually.

**Comment by yurikuzn** [comment]
Use case. A client sent an email to a worker's personal email address that is not monitored. The email is important, need to import it to the CRM.

**Comment by yurikuzn** [comment]
> Will it also allow to import attached eml directly from a received email?

If download an attachment and then import, it will appear in the system as a regular email record.

**Comment by murugappanrm** [comment]
@yurikuzn Fantastic,. It will be great if we could export and import emails in CRM so that we can back and recover into another instance. I hope our wished come true.
