### ISSUE TITLE
Linking records in detail view failing after upgrade to 8.3.0

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#3083]
**Describe the bug**
Linking records no longer works in some cases.

In a custom entity called `Session`, there is a `link one` field called `importedSanDataVisit`. I frequently edit `Session` records to link `importSanDataVisit` records like this:
![image](https://github.com/espocrm/espocrm/assets/1170415/ab9bae18-01a0-48a6-b68d-d8be3008e4ef)

I expect the foreign record to link to the `Session` record after saving, which should look like this:
![image](https://github.com/espocrm/espocrm/assets/1170415/f3f9ebdf-235b-4a26-8002-7cf04e866bae)

However, after I click `Update`, the `Session` has no link to the foreign record because the data is filtered by `filterInputForeignAttributes`. There are no errors in the log. Interestingly, if I link the `Session` record to the `ImportedSanDataVisit` from the detail view of the `importedSanDataVisit` record, it works as expected:
![image](https://github.com/espocrm/espocrm/assets/1170415/4ff93ec7-4d65-41a4-9e88-0392d8092972)

When updating the `Session` record, this is what is sent to the server:
```
Request URL: https://xxxx.com/api/v1/Session/6665729acc916288b
Request Method: PUT
Status Code: 200 OK

Body:
{
    importedSanDataVisitId: "667763d7446944392",
    importedSanDataVisitName: "Imported Visit"
}
```

The default route is used, which means the following function in `application/Espo/Core/Controllers/RecordBase.php` receives the request:

```php
    public function putActionUpdate(Request $request, Response $response): stdClass
    {
        ...
        $entity = $this->getRecordService()->update($id, $data, $params);
        ...
    }
```

The problem occurs in the `$this->getRecordService()->update($id, $data, $params);`, which eventually calls `$this->filterInputForeignAttributes($data);`. Here is the function with two new log statements:
```php
    private function filterInputForeignAttributes(stdClass $data): void
    {
        ...
        foreach ($entityDefs->getAttributeList() as $attributeDefs) {
            if (
                $attributeDefs->getType() !== AttributeType::FOREIGN &&
                !$attributeDefs->getParam('isLinkMultipleNameMap')
            ) {
              $GLOBALS["log"]->debug("continue" . " " . $attributeDefs->getName() . " " .$attributeDefs->getType() . " " . $attributeDefs->getParam('isLinkMultipleNameMap'),[]);
                continue;
            }
            $GLOBALS["log"]->debug("unset   " . " " . $attributeDefs->getName() . " " .$attributeDefs->getType() . " " . $attributeDefs->getParam('isLinkMultipleNameMap'),[]);

            $attribute = $attributeDefs->getName();
            unset($data->$attribute);
        }
    }
```

When I link an `ImportedSanDataVisit` to a `Session` from within the `Session`, this is what the log shows:
```
[2024-06-23 01:37:19] DEBUG: unset    importedSanDataVisitId foreign
[2024-06-23 01:37:19] DEBUG: unset    importedSanDataVisitName foreign
```

When I link a `Session` record to an `importedSanDataVisit` from within the `ImportedSanDataVisit`, this is what the log shows:
```
[2024-06-23 01:37:58] DEBUG: continue sessionId foreignId
[2024-06-23 01:37:58] DEBUG: unset    sessionName foreign
```
## ISSUE
`importedSanDataVisitId` is treated as `foreign` while `sessionId` is treated as `foreignId`. I don't know what the difference is, but the `foreign` field is filtered while the `foreignId` field is not filtered. Filtering `foreign` is causing the update to fail to relate the `importedSanDataVisit` to the `Session`.

Here are the definitions of the relationship:

`custom/Espo/Custom/Resources/metadata/entityDefs/ImportedSanDataVisit.json`
```json
    "fields": {
        "session": {
            "type": "link",
            "isCustom": true
        },
    },
    "links": {
        "session": {
            "type": "belongsTo",
            "foreign": "importedSanDataVisit",
            "entity": "Session",
            "isCustom": true
        }
    },
```

`custom/Espo/Custom/Resources/metadata/entityDefs/Session.json`:
```json
    "fields": {
        "importedSanDataVisit": {
            "type": "linkOne",
            "isCustom": true
        },
    },
    "links": {
        "importedSanDataVisit": {
            "type": "hasOne",
            "foreign": "session",
            "entity": "ImportedSanDataVisit",
            "isCustom": true
        },
    },
```

When linking an `importedSanDataVisit` record to a `Session` from within a `Session`, this is what the browser shows as a response even though the fields had values (see the initial request at the top of this post):
```
{
    ...
    "importedSanDataVisitId": null,
    "importedSanDataVisitName": null,
    ...
}
```

Linking `importSanDataVisit` records within the detail views of `Session` records was working correctly until yesterday, which was when I upgraded from 8.2.5 to 8.3.0. I don't see any changes in the upgrade that would have affected the logic, so I don't know what to do.

**EspoCRM version**
8.3.0

**Comment by bandtank** [comment]
I added a debug statement to show the `data` in the `attributeDef` for each field:

```
[2024-06-23 02:04:03] DEBUG: {"len":24,"dbType":"string","type":"foreignId","index":true,"attributeRole":"id","fieldType":"link","notNull":false}
[2024-06-23 02:04:03] DEBUG: continue sessionId foreignId
```
```
[2024-06-23 02:04:57] DEBUG: {"type":"foreign","notStorable":true,"attributeRole":"id","fieldType":"linkOne","relation":"importedSanDataVisit","foreign":"id","foreignType":"id"}
[2024-06-23 02:04:57] DEBUG: unset    importedSanDataVisitId foreign
```

To test my theory, I modified the `filterInputForeignAttributes` function as follows:

```php
if (
  ($attributeDefs->getType() !== AttributeType::FOREIGN &&
    !$attributeDefs->getParam('isLinkMultipleNameMap'))

  ### NEW LINE BELOW
  || ($attributeDefs->getType() !== AttributeType::FOREIGN_ID &&
    !$attributeDefs->getParam('isLinkMultipleNameMap'))
) {
...
```

I do not know if that change works for other situations, but it fixed the issue I am currently experiencing because the sessions now link as expected. Please let me know if you need more information.

**Comment by bandtank** [comment]
This is most likely when the change occurred: https://github.com/espocrm/espocrm/commit/bb091a0301a5fc6a1c5429e424a9bf96b6cdb22f

**Comment by yurikuzn** [comment]
Thanks for researching. Fixed, test added: https://github.com/espocrm/espocrm/issues/3085
