### ISSUE TITLE
Unit tests failing on PHP 8.2.21

### ISSUE THREAD

**Issue by jakub-frajt** [espocrm/espocrm#3099]
**Describe the bug**
An external library zbateson/mail-mime-parser is not compatible with PHP 8.2. Espo uses old version 1.3.1.
Unit tests failing on the Espo 7.3.4 even on the master branch.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Clone stable version or master branch of EspoCrm
2. Run docker run --rm -it -u 1000 -v {path-to-project}:/var/www/html -w /var/www/html docker.io/php:8.2.21 php vendor/bin/phpunit tests/unit

**Error**
```
Fatal error: During inheritance of IteratorAggregate: Uncaught Return type of ZBateson\MailMimeParser\Header\HeaderContainer::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

/var/www/html/vendor/zbateson/mail-mime-parser/src/Header/HeaderContainer.php:280
/var/www/html/vendor/zbateson/mail-mime-parser/src/Header/HeaderContainer.php:18
/var/www/html/vendor/zbateson/mail-mime-parser/src/Header/HeaderFactory.php:166
/var/www/html/vendor/zbateson/mail-mime-parser/src/Message/Part/Factory/PartBuilderFactory.php:50
/var/www/html/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php:274
/var/www/html/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php:65
/var/www/html/vendor/zbateson/mail-mime-parser/src/MailMimeParser.php:75
/var/www/html/application/Espo/Core/Mail/Parsers/MailMimeParser.php:110
/var/www/html/application/Espo/Core/Mail/Parsers/MailMimeParser.php:118
/var/www/html/application/Espo/Core/Mail/Parsers/MailMimeParser.php:123
/var/www/html/application/Espo/Core/Mail/MessageWrapper.php:102
/var/www/html/application/Espo/Core/Mail/Account/GroupAccount/BouncedRecognizer.php:48
/var/www/html/tests/unit/Espo/Core/Mail/Account/BouncedRecognizerTest.php:62
 in /var/www/html/vendor/zbateson/mail-mime-parser/src/Header/HeaderContainer.php on line 18
```

**Solution**
Update zbateson/mail-mime-parser (probably breaking change) or create a fork and fix an old version.

**EspoCRM version**
7.3.4, 8.2, current master

**Comment by yurikuzn** [comment]
The GitHub action run successfuly on PHP 8.2.21 today. Weird.

**Comment by jakub-frajt** [comment]
I tried base Docker image for Ubuntu and Debian and I install PHP 8.2. After that all tests pass without error. It's weird that same version of PHP has different behavior in Docker.

**Comment by jakub-frajt** [comment]
It looks like that caused by different configuration in php.ini. In base images for Ubuntu and Debian is set **error_reporting** to **22527**. But in PHP docker image **error_reporting** has no value -> it means E_ALL. When I run tests with -d error_reporting=E_ALL in Ubuntu image for example the error will appear.

**Comment by yurikuzn** [comment]
I see. Thanks for information.

I was considering upgrading mail-mime-parser for v8.4. Unfortunately, the new lib added the php-di dependency, what I was not happy about.

**Comment by jakub-frajt** [comment]
> the new version added the php-di dependency, what I was not happy about.

Can you elaborate more on this?

Otherwise I think it would be better to set the error_reporting for the GitHub action to E_ALL and not rely on the default value in Ubuntu at least for future versions of EspoCRM.

**Comment by yurikuzn** [comment]
In a large project, when a library depends an another popular library from other vendor, there's a significant probability that some other library will depend on the same library in the future. If they require different versions, an incompatibility will occur. With NodeJS, with modules, it's not an issue as dependencies are independent, but with PHP it's not the case.

**Comment by jakub-frajt** [comment]
I see, thanks for the explanation.

**Comment by yurikuzn** [comment]
Updated mailmimeparser lib: https://github.com/espocrm/espocrm/commit/d97b9be4c9b3712ee94232e875940da3d96df982
