### ISSUE TITLE
Dont strip http(s):// when entering an URL in website-field

### ISSUE THREAD

**Issue by k00ni** [espocrm/espocrm#3100]
**Describe the bug**
Neither `http://` nor `https://` are getting stored in website field.

**To Reproduce (MANDATORY, DO NOT REMOVE)**

When you enter a website in the account view:

![Bildschirmfoto vom 2024-07-15 10-19-53](https://github.com/user-attachments/assets/30dc6c5e-3f9c-4666-8376-f116b1c8fde4)

it automatically removes the `http://` part after "leaving" the field (= going to another field or click save):

![Bildschirmfoto vom 2024-07-15 10-18-58](https://github.com/user-attachments/assets/c1d781e0-df6e-4fac-a355-8924feb1051a)

**Expected behavior**
Please keep it, if explicitly given by the user. Some websites not yet support a SSL certificate and therefore the link leads to an error:

![Bildschirmfoto vom 2024-07-15 10-15-25](https://github.com/user-attachments/assets/066dbd1d-68b4-40a0-9ff8-eea3f6244600)

If there is a setting to change this behavior I couldn't found it.

**EspoCRM version**
8.3.5

**Comment by arkadiyasuratov** [comment]
Go to Administration > Entity Manager and uncheck the "Strip" parameter.

![image](https://github.com/user-attachments/assets/17c5a4a4-f768-402c-b283-a8e84838e2bb)

**Comment by k00ni** [comment]
Thank you.
