### ISSUE TITLE
Translation minor bugs

### ISSUE THREAD

**Issue by gobido-research** [espocrm/espocrm#3101]
**Describe the bug**
```
this.buttonList = [
                {
                    name: 'save',
                    text: this.translate('Apply'),
                    style: 'primary',
                },
                {
                    name: 'cancel',
                    text: 'Cancel',
                },
            ];
```

doesn't translate Cancel 

https://github.com/espocrm/espocrm/blob/9339082f9b2df7952a526ef455f4e3d40b191e6a/client/src/views/admin/layouts/modals/panel-attributes.js#L61

**Comment by gobido-research** [comment]
Is the Save Filter Modal field name not getting translated!

**Comment by gobido-research** [comment]
In Global.json en_US there is no entry for "Remove Filter" 
there is a reference for translate but there is nothing in global

reference
https://github.com/espocrm/espocrm/blob/9339082f9b2df7952a526ef455f4e3d40b191e6a/client/res/templates/record/search.tpl#L45

Missing after Save Filter
https://github.com/espocrm/espocrm/blob/9339082f9b2df7952a526ef455f4e3d40b191e6a/application/Espo/Resources/i18n/en_US/Global.json#L240

**Comment by gobido-research** [comment]
In Global.json en_US there is no entry for "Ready"
Used in this sections , small text showing after upload is complete

https://github.com/espocrm/espocrm/blob/9339082f9b2df7952a526ef455f4e3d40b191e6a/client/src/views/fields/file.js#L743

https://github.com/espocrm/espocrm/blob/9339082f9b2df7952a526ef455f4e3d40b191e6a/client/src/views/fields/attachment-multiple.js#L471

**Comment by yurikuzn** [comment]
Thanks for reporting. https://github.com/espocrm/espocrm/commit/d6d83a209fda45c644139f143d8bc7b61b7ce60c
