### ISSUE TITLE
Select link from model list doesn't work with enum field

### ISSUE THREAD

**Issue by kamolpech** [espocrm/espocrm#3103]
**Describe the bug**
Select link from model list doesn't work with enum field

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Go to Layout Manager -> Case -> List (Small)
2. Add field Type to list and set as link
3. Go to page Create Call 
4. At Field Parent set type to Case and select link 
5. click field Type on list
6. no action
...

**Expected behavior**
Please help make it work.

**Screenshots**
![Capture](https://github.com/user-attachments/assets/16346bfd-516b-4146-ad47-5c0804b76652)

![Create-Call](https://github.com/user-attachments/assets/e9ea5a96-2aaa-42ce-9c00-5f78e0e9e297)

**EspoCRM version**
master, stable

**Comment by kamolpech** [comment]
> Are you reporting this as a bug? For help question I think yuri will send you to the forum to ask.
> 
> As for not being able to click, I think you have to go to Layout Manager and use the option, "linkable".

I think that's a bug or Espocrm does not allow this.
I use the option "linkable" as shown in the screenshots above.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/38ad6def8cf85e655b82e925aa1ebc021d32a04c
