### ISSUE TITLE
Two-factor authentication when using OIDC

### ISSUE THREAD

**Issue by Gebetshaus** [espocrm/espocrm#3104]
If OIDC Auth is used and TFA is activated for the internal ESPO login, the login fails with error 500.
TFA should actually only be used for the internal login and should not work with OIDC, as the OIDC provider itself offers TFA. 
Please remove the TFA for OIDC login.

**EspoCRM version**
8.X,X

**Comment by yurikuzn** [comment]
It's documented: https://docs.espocrm.com/administration/oidc/. Details.

**Comment by metalmatze74** [comment]
I don't understand why OIDC is mixed with the local TFA. When I log in with the local ESPO credentials, the TFA code is requested, when I use the external OIDC, it is not. It is the same on every other system.

**Comment by yurikuzn** [comment]
2FA does not work with OIDC and there's no parameter to disable it only when authenticated with OIDC.. The admin needs to disable it in the system.

Answer to the question "why"? Because it's not implemented. "Every other system" is an manipulative argument,

**Comment by yurikuzn** [comment]
In the future, we can add a parameter forcing by-passing 2FA only when OIDC is applied.  But I'm not sure whether it's easy to implement. If any one can look into the code and suggest an idea how to implement it, it will be helpful and expedite implementation.

**Comment by yurikuzn** [comment]
I'm not sure I understand the problem. You need to disable 2fa for your user in Espo. Maybe you configured it before configuring OIDC.

**Comment by metalmatze74** [comment]
I want to disable 2fa for OIDC but not for Espo Login.
This change seems to solve this problem:
adding &&
            $username !== '**oidc'
on
application/Espo/Core/Authentication/Authentication.php
Line 239-245
        $this->applicationUser->setUser($loggedUser);
        if (
            !$result->isSecondStepRequired() &&
            !$authToken &&
            $this->configDataProvider->isTwoFactorEnabled() &&
            $username !== '**oidc'
