### ISSUE TITLE
Working Time Calendar Exception assigned to a specific User is applied to all users when using ext\workingTime\isWorkingDay

### ISSUE THREAD

**Issue by neknarf** [espocrm/espocrm#3105]
**Describe the bug**
Multiple Users have a Working Time Calendar assigned with a Mo-Fri schedule, from 09:00 till 18:00.
Created a Working Time Calendar Exception for today, assigned to a specific user.

When running `ext\workingTime\isWorkingDay(datetime\today(), 'User', id)` the result is False for all users and not only for the User which has the exception assigned.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Create a Working Time Calendar
2. Assign the Calendar to 2 Users (John & Brian)
3. Create an exception for today (Vacation) assigned to John
4. Run the following formula in the Formula Sandbox on user Brian
`output\printLine(ext\workingTime\isWorkingDay(datetime\today(), 'User', id));
`
5. The result will be false instead of true

**EspoCRM version**
8.3.1
8.3.5 public demo environnent

**Comment by yurikuzn** [comment]
I could not reproduce.

**Comment by yurikuzn** [comment]
I suspect that you created an exception with for both User and Calendar. Need only for User.

**Comment by neknarf** [comment]
Indeed, I did assume that an exception needs to be assigned to both the calendar and a user. 
Thanks for the clarification!

**Comment by yurikuzn** [comment]
We need to add a tooltip for the Calendars field.
