### ISSUE TITLE
Conditional Text Display in PDF Templates Based on Checklist and Multi-Enum Fields

### ISSUE THREAD

**Issue by yubrajkafle** [espocrm/espocrm#3106]
**Is your feature request related to a problem? Please describe.**

Yes, the feature request is related to the limitation in the current functionality of generating PDFs from templates. Specifically, there is no way to conditionally display or hide text based on the selections in checklist or multi-enum fields. This limitation affects our ability to create dynamic and context-sensitive PDF documents, as we cannot automatically include or exclude text based on user selections. This leads to manual editing of PDFs, which is time-consuming and prone to errors.

**Describe the solution you'd like**
I would like to have a feature that enables conditional text display in PDF templates based on the selections in checklist and multi-enum fields. 

I am submitting this feature request because I have not found any existing solution to achieve the desired functionality. If there is already a way to implement conditional text display in PDF templates based on checklist and multi-enum fields, please let me know.

**Comment by yurikuzn** [comment]
We could solve it with a new template `inArray` helper.

Workaround:

```
{{#each field_RAW}}{{#ifEqual this 'Value'}} ... {{/ifEqual}}{{/each}}
```

**Comment by yubrajkafle** [comment]
Tried this . problem solved .
thank you
