### ISSUE TITLE
Exclude display of records with 0 count (group by) in reports

### ISSUE THREAD

**Issue by JulianHochgesang** [espocrm/espocrm#3112]
**Information**

- EspoCRM version: `8.3.5`
- Advanced Pack version: `3.4.3`

**Bug**
We have created a report with grouping by one field. Several parameters are queried. However, the result (in table and chart form) also shows rows/columns with "empty" results (= 0).

We have already tried to set filters such as "greater than 0" or "not empty", but nothing works.

After some research, I found out that this bug appeared in 2021, but was not fixed:
https://forum.espocrm.com/forum/general/74656-exclude-display-of-records-with-0-count-group-by-in-reports

A screenshot of the report configuration is attached:

![screencapture-crm-beyondssl-2024-07-30-10_34_23](https://github.com/user-attachments/assets/35dc96c7-841d-476f-b545-237bedf14ddb)

**Comment by yurikuzn** [comment]
The report feature is not part of this repository.
![image](https://github.com/user-attachments/assets/af2b0c6f-0e99-4089-850c-265d1e0fcdff)

**Comment by yurikuzn** [comment]
If you have an issue with Reports feature, I suggest contacting our support team by creating a case in the customer portal.
