### ISSUE TITLE
Custom log loaders cannot access all configuration options

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#3113]
**Describe the bug**
When a custom log loader (`loaderClassName`) is used, there is no way to access the full set of configuration parameters for the handler in the customer loader class.

The `params` key from the root of the handler's configuration options is stored in `$params` as seen here:
https://github.com/espocrm/espocrm/blob/b34d8ebca848259b45b83778a03206627b6b7efd/application/Espo/Core/Log/HandlerListLoader.php#L65

When a custom loader is used, `$params` is passed to the constructor as seen here: https://github.com/espocrm/espocrm/blob/b34d8ebca848259b45b83778a03206627b6b7efd/application/Espo/Core/Log/HandlerListLoader.php#L74

However, when the default loader is used, the `$data` array, which contains all configuration options, is passed to the constructor as seen here: https://github.com/espocrm/espocrm/blob/b34d8ebca848259b45b83778a03206627b6b7efd/application/Espo/Core/Log/HandlerListLoader.php#L77

The `customParam` and `lineFormat` parameters are not available in the custom loader as seen in the following print statement, which contains the full set of options that were passed to the custom loader:
```php
Array
(
    [filename] => data/logs/espo-info.log
    [level] => DEBUG
)
```

This issue can be worked around by putting the configuration options in the root `params` key instead of using the `formatter` key to organize the options that are specific to the formatter. With that said, it makes more sense to allow the regular configuration format to be used by passing `$data` to the custom loader.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Create a custom handler. Add the following configuration to `config-internal.php`:
```php
      [
        'className' => 'Espo\\Custom\\Log\\CustomHandler',
        'loaderClassName' => 'Espo\\Custom\\CustomLoader',
        'params' => [
          'filename' => 'data/logs/espo-info.log',
        ],
        'level' => 'INFO',
        'formatter' => [
          'className' => 'Espo\\Custom\\Log\\CustomFormatter,
          'params' => [
            'lineFormat' => "[%datetime%] %level_name%: %code% %message% %request% %context%\n",
            'customParam' => 'abc',
          ]
        ]
      ]
```

**Expected behavior**
All parameters within the handler's configuration should be passed to the custom loader.

**Suggested Fix**
Change this:
```php
    private function loadHandler(array $data, ?string $defaultLevel = null): HandlerInterface
    {
        $params = $data['params'] ?? [];
        $params['level'] ??= $defaultLevel;

        /** @var ?class-string<HandlerLoader> $loaderClassName */
        $loaderClassName = $data['loaderClassName'] ?? null;

        if ($loaderClassName) {
            $loader = $this->injectableFactory->create($loaderClassName);

            return $loader->load($params);
        }

        return $this->defaultLoader->load($data, $defaultLevel);
    }
```
to this:
```php
    private function loadHandler(array $data, ?string $defaultLevel = null): HandlerInterface
    {
        /** @var ?class-string<HandlerLoader> $loaderClassName */
        $loaderClassName = $data['loaderClassName'] ?? null;

        if ($loaderClassName) {
            $loader = $this->injectableFactory->create($loaderClassName);

            return $loader->load($data, $defaultLevel);
        }

        return $this->defaultLoader->load($data, $defaultLevel);
    }
```

**EspoCRM version**
Latest

**Comment by yurikuzn** [comment]
If it works as it was designed, it's not a bug.

DefaultHandlerLoader does not implemented the HandlerLoader interface. The way it works does not dictate how the HandlerLoader classes should work.

Your proposal is a breaking change that would requires a major version change (from 8.3 to 9.0).

**Comment by bandtank** [comment]
It is a little bit confusing, but I understand. It would be better in the long run if the interfaces were consistent. Documentation to explain that the custom options must all be placed in the root `params` key would be helpful.

**Comment by yurikuzn** [comment]
IIRC, loaders were introduced only for cases where it's not not possible to instantiate Handler as constructor parameters require non scalar values. Handlers receive parameters from the *params*.  Hence, for Loaders,  the *params* should be enough.

**Comment by yurikuzn** [comment]
Maybe we could set the formatter for the loaded handler automatically. After the handler is instantiated with the loader, if the formatter parameters are specified in the config, instantiate a formatter and call `setFormatter` on the handler.

**Comment by bandtank** [comment]
That is an interesting solution. Whatever you decide will be fine with me. Thank you for the information and insight.

**Comment by yurikuzn** [comment]
> and call `setFormatter` on the handler.

Done: https://github.com/espocrm/espocrm/commit/a9e0dad0dd7f23ca482d76d34afb235d90d7fd55

**Comment by bandtank** [comment]
That works perfectly. Thank you.
