### ISSUE TITLE
Kanban view configuration flow

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#3117]
**Describe the bug**
This is not a bug but rather how the fields order is set when enabling kanban view. Here is a scenario, when you go to edit an entity you select  a statusField => this would show the kanban view checkbox => if checked then kanban ignore groups is shown. The issues is that you can set a status field => show the kanban view checkbox => check it and then change the statusField to none. if you visit your entity list the kanban button is listed but when you click it keeps loading but nothing is shown because no statusField was provided. 

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Go to administration -> entity manager -> account
2. select a statusField (Type) -> check the kanban view checkbox (Save) 
3. then chose a statusField (none) and Save (kanban will disppear but the value will still be set as true (checked))
4. Visit accounts (kanban button will be displayed but when you click it it keep just loading because although kanban is still active no statusField is set. 

**Expected behavior**
I think the logic needs to check so that kanban view checkbox should control visibility of the statusField. Here is a logic that would fit:
- Kanban view (checkbox) enabled -> make statusField field visible
- once statusField value is set -> display Ignored groups in Kanban view field 
- If kanban view field is unchecked then unset both values of statusField and Ignored groups in Kanban view fields and make them hidden. 

**Screenshots**

https://github.com/user-attachments/assets/6bc7ddb6-9c8d-43da-8baa-781b3bd27715

**EspoCRM version**
version 8.3
**Additional context**

**Comment by yurikuzn** [comment]
> I think the logic needs to check so that kanban view checkbox should control visibility of the statusField.

No as Status Field is needed not only for Kanban.

**Comment by yurikuzn** [comment]
Unsetting kanban: https://github.com/espocrm/espocrm/commit/ce58cc262f266f4878521ea9d23d9d7e4d2d35fe
