### ISSUE TITLE
Please replace abandoned package laminas/laminas-crypt

### ISSUE THREAD

**Issue by shinsenter** [espocrm/espocrm#3118]
### Summary
I noticed that the package laminas/laminas-crypt is marked as abandoned, and it is recommended to avoid using it.

When running `composer install` or `composer update`, the message is as the below.

```
...

   0/130 [>---------------------------]   0%
  41/130 [========>-------------------]  31%
  68/130 [==============>-------------]  52%
  89/130 [===================>--------]  68%
 104/130 [======================>-----]  80%
 129/130 [===========================>]  99%
 130/130 [============================] 100%
Package laminas/laminas-crypt is abandoned, you should avoid using it. No replacement was suggested.
```

### Details
https://github.com/laminas/laminas-crypt

---

To ensure our project remains secure and maintainable, I kindly request that we identify and replace this package with a suitable alternative.

Thank you for your attention to this matter.

Best regards,

**Comment by yurikuzn** [comment]
It's not used anywhere since laminas-mail were updated. Will remove laminas-crypt in v8.5 as 8.4 is already tested.
