### ISSUE TITLE
phoneNumber field cannot be set on new entity

### ISSUE THREAD

**Issue by tim-bezhashvyly** [espocrm/espocrm#3120]
I'm not quite sure if it is a bug but setting phone number on a new entity (I tried contact) does not work. I can understand why, as phone number is another entity and connection between contact and phone number is in fact a relation but at the same time setting an email address which is also a separate entity works just fine.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:

```php
$contact = $this->entityManager->getEntity(Contact::ENTITY_TYPE);
$contact->set('phoneNumber', '+41797777777');
$this->entityManager->saveEntity($contact);

echo $contact->get('phoneNumber'); // Returns null

$contact->set('phoneNumber', '+41797777777');
$this->entityManager->saveEntity($contact);

echo $contact->get('phoneNumber'); // Returns '+41797777777'
```

**Comment by yurikuzn** [comment]
I modified the test to reproduce the same scenario and it worked fine. The test passed.

https://github.com/espocrm/espocrm/commit/6e6478bb6ac30647828d21106c5abbbb972fbc6a

**Comment by tim-bezhashvyly** [comment]
Found an issue on my side. Sorry about that and thank you for a prompt reaction.

**Comment by yurikuzn** [comment]
It's normal:) More than 50% of bug reports are not bugs. It used to be worse before we added mandatory steps to reproduce. I had already 3 false bug reports for today. And it's Sunday morning :)
