### ISSUE TITLE
PDF Templates: Conditional rendering attribute x-if

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3122]
Example:

```
<table>
    <tr x-if="{{equal status 'Active'}}">
        <td></td>
    </tr>
</table>
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/03c275f4954bc25b74faf55ee87237b589a2f691

**Comment by rabiibrahimi** [comment]
I saw the syntax and thought it is Alpine js 😎
Thanks @yurikuzn this is really helpful :)
