### ISSUE TITLE
Possibility to override AclManager

### ISSUE THREAD

**Issue by hajek-raven** [espocrm/espocrm#3126]
**Is your feature request related to a problem? Please describe.**
Currently, in EspoCRM, it is not possible to override the AclManager. In our company, we need to customize the ACL behavior to better align with our unique business processes and security requirements. The inability to override the AclManager restricts our flexibility in implementing custom access control rules, resulting in limitations that affect user experience and operational efficiency.

**Describe the solution you'd like**
We would like the ability to override the AclManager in EspoCRM. This feature would allow developers to extend or modify the existing ACL logic by creating a custom implementation of the AclManager class.

**Describe alternatives you've considered**
One alternative we have considered is forking the EspoCRM repository and making the necessary changes directly in the codebase. However, this approach is not ideal as it requires maintaining a separate codebase and complicates future updates and maintenance.

**Additional context**
-

**Comment by yurikuzn** [comment]
"Overriding AclManager" is too vague. You can already extend AclManager by means of the DI framework. The ACL framework is already provides quite a few customization abiltities..

**Comment by yurikuzn** [comment]
Recently I wrote a completely independent additional ACL functionality for a proprietary extension. It works independently from the build-in ACL. Overriding is not always the best choice.

**Comment by hajek-raven** [comment]
To be more specific, we want to restrict reading of some fields based on a role (row level).
Example:
- User with role "Salesman" can see all Contacts, they can see all information of their own Contacts. The can also see Team Contacts but only certain fields like name, but not `email`.

**Comment by yurikuzn** [comment]
You could filter specific fields using an output filter https://docs.espocrm.com/development/metadata/record-defs/#outputfilterclassnamelist.
