### ISSUE TITLE
Question about Case auto flollow

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#3139]
**Describe the bug**
Hi Yuri, I faced a case when I developed a custom ACL checker for cases, I noticed that this line has a parameter that skipping acl check for auto following for portal users.

Is this intended by design?

https://github.com/espocrm/espocrm/blob/bdc9505094e4155b0d54ab6bcbc6a8c0ee67fa64/application/Espo/Modules/Crm/Hooks/CaseObj/Contacts.php#L109

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Add custom acl checker for cases entity, make it limit access to stream even if contact is linked

**EspoCRM version**
8.2

**Comment by yurikuzn** [comment]
I'm not sure. Maybe we'd better change it to false.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/b46c6d76a56af816daa76cb95170f8b70bd42f15

There's an issue when the same user is related to multiple portals. It will check only the first one.
