### ISSUE TITLE
Mass Follow/Unfollow actions

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#314]
As the user that uploads data with import function, all leads created are auto followed for my account. Renders stream feature useless on dashboard.

**Comment by yurikuzn** [comment]
BTW If assigned user left empty then it shouldn't be followed.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/d8b2a13c2055a4f26461a4711e44c3eca54612a1
