### ISSUE TITLE
Additional select appliers applied globally

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3141]
The same as *recordDefs > {EntityType} > selectApplierClassNameList* but applied for all entity types.

[Docs](https://github.com/espocrm/documentation/blob/master/docs/development/metadata/app-record.md#selectapplierclassnamelist).

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/c0ef13c7f42592bf3d86397244748bf18a1c7dd0

**Comment by eymen-elkum** [comment]
This is a big addition, we were waiting for it for long time, many thanks!
