### ISSUE TITLE
Indicating starred record on list view

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3142]
With a star icon before the name.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/ab581a4faed817a06121648080f80de49391ce4e

**Comment by rabiibrahimi** [comment]
Hey @yurikuzn 
Any chance to allow admin to enable/disable this feature via entity manager per each entity? 
Thanks

**Comment by yurikuzn** [comment]
We would end up with 1000s of parameters. You can disable with CSS.
