### ISSUE TITLE
Knowledge Articles / Categories - Navigation on the left not completely working (second level)

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#3145]
**Describe the bug**

We've got a knowledge base structure that's hierarchical

First level:
![image](https://github.com/user-attachments/assets/5a506856-48cf-43a3-9a67-06928c16e9b6)

Second Level: 
![image](https://github.com/user-attachments/assets/e59088b8-0c22-493a-a538-b0a96165b3c3)

Article Level:
![image](https://github.com/user-attachments/assets/1105c3bf-14d8-4a7d-809a-d5333fc5143e)

It works using the navigation on the images above. However, when using the hierarchical category browser (navigation on the left):

First level works:
![image](https://github.com/user-attachments/assets/0c85a882-7b0d-429d-ae8f-0c0d75bdf805)

Second level not (2023 has been clicked):
![image](https://github.com/user-attachments/assets/855becaa-8fd1-41e7-92f7-6acc303d5961)

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:

See above. 

**Expected behavior**
Same behavior as in EspoCRM 6. 
I noticed the current behavior from EspoCRM 7.3.4 (now testing with 8.3.6).

**Screenshots**
See above. 

**EspoCRM version**
7.3.4 - 8.3.6.

**Additional context**
-

**Comment by hdijkema** [comment]
Same for 8.4.0.

**Comment by yurikuzn** [comment]
See https://docs.espocrm.com/administration/commands/#rebuild-category-paths

This is not reproducible bug. There're many thousands installations without this problem. Please prefer our forum for such issues. We provide support on our forum but not on GitHub.
