### ISSUE TITLE
AuthTokenControl incorrectly converts decimal values for token lifetime and idle time to integers

### ISSUE THREAD

**Issue by jarca0123** [espocrm/espocrm#3146]
**Describe the bug**
authTokenLifetime and authTokenMaxIdleTime are converted to int in AuthTokenControl even if they are float in settings. If then someone were to set such a value in decimal, for example 0.25, then that would be converted to 0.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. In authentication settings, set either lifetime or max idle time to a decimal value, for example 0.05.
2. Wait for 0.05 hours and don't interact with the site, if max idle time is set. If only lifetime is set, wait for 0.05 hours.
3. Run job "AuthTokenControl".
4. If set to a decimal value like 0.05, then the user will be not logged out.

**Expected behavior**
I would expect that the user would be logged out if a decimal value lower than 1 would be set and if following the instructions above.

**EspoCRM version**
I used the tag 8.4.0.

**Additional context**
This can be fixed by having brackets like so:
`(int) ($this->config->get('authTokenMaxIdleTime', 0) * 60);`

I'm not sure if this is the right way to fix it though.

**Comment by yurikuzn** [comment]
Here's the fix: https://github.com/espocrm/espocrm/commit/8b8d3ee1588a01a7b15bbb7214bb161b620fef7a

**Comment by Kharg** [comment]
I don't want to alarm you, but I think that this broke the AuthTokenControl job.

It doesn't seem to be working anymore, I tried setting both Token lifetime and Idle lifetime to 0.1 but the user keeps being logged in even if the job is ran successfully.

**Comment by yurikuzn** [comment]
To run the job from CLI and debug. https://docs.espocrm.com/administration/commands/#running-job
