### ISSUE TITLE
App secrets

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3148]
The ability for admin to store secrets: API keys, passwords, etc. Can be read from code.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3c57b7e39ecb064d68afaf7fcab04c0eedde66ef

**Comment by yurikuzn** [comment]
Store at: Administration > App Secrets.

Read using the class: `Espo\Tools\AppSecret\SecretProvider`.

**Comment by yurikuzn** [comment]
Can be used in Workflows Send HTTP Request headers. Out of scope of this repository.

**Comment by rabiibrahimi** [comment]
> Can be used in Workflows Send HTTP Request headers. Out of scope of this repository.

It would be nice if this added extended to be used in workflow. when hitting other api services api key secret is exposed in the workflow or bpmn send http request. It will be nice to reference a key from the appsecret entity without exposing it.

**Comment by yurikuzn** [comment]
>  It will be nice to reference a key from the appsecret entity without exposing it.


https://github.com/espocrm/documentation/commit/46e04503db8fe4e7e92f246a9cf953bbf8a18ded
