### ISSUE TITLE
Leads list sorting by name not working properly

### ISSUE THREAD

**Issue by santibm** [espocrm/espocrm#3154]
**Describe the bug**
On the leads page, when sorting by name the order is not correct 

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Go to the leads listing page with some leads in it, click the column name, the leads are sorted but not by name, it looks they get sorted by id

**Expected behavior**
I'd expect the leads to be sorted by name 

**Screenshots**
<img width="275" alt="Captura de Pantalla 2024-09-17 a las 12 54 59" src="https://github.com/user-attachments/assets/8e91dc93-c25a-4751-aeed-0fa827389e3a">

**EspoCRM version**
Version 8.1.5

**Comment by yurikuzn** [comment]
Not by ID. By first name + last name + id. But the name can be empty, then Account Name or email address is displayed.
