### ISSUE TITLE
Import doesn't work if creating entity with empty ID

### ISSUE THREAD

**Issue by jarca0123** [espocrm/espocrm#3155]
**Describe the bug**
Import doesn't work if creating entity with empty ID. This may be because the hasId function in \Espo\ORM\BaseEntity doesn't check whether the ID is an empty string, which is what happens when the ID is empty in import.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Make a CSV file with an empty ID. The first line should be "id,something" and the second line should be ",something".
2. Import it with the importer and in field mapping, map id to ID.
3. The import will fail without any explanation in the frontend and will log "ERROR: Import: Entity ID is empty."

**Expected behavior**
I would expect that the entities would be imported successfully.

**EspoCRM version**
Version 8.3.0

**Additional context**
https://github.com/espocrm/espocrm/blob/92d164d3d35831351c4e24d7d3beea6e0462fc37/application/Espo/Tools/Import/Import.php#L569-L574

https://github.com/espocrm/espocrm/blob/92d164d3d35831351c4e24d7d3beea6e0462fc37/application/Espo/ORM/BaseEntity.php#L105-L127

**Comment by yurikuzn** [comment]
But it should not import. You mapped a column with an invalid value. It's how it works with all fields.

The only problem I see is that an error is not explained in the import error record.

**Comment by yurikuzn** [comment]
This fix will solve the problem partially: https://github.com/espocrm/espocrm/commit/7bcd5b5bdba64e337b95978cd0e9ad06d352852a

**Comment by bandtank** [comment]
@jarca0123 Are you expecting Espo to create an ID if one is not provided?

**Comment by yurikuzn** [comment]
The system generates IDs for new records. But Import allows to use predefined IDs. It's hard to imagine a CSV where some some records have IDs, some not. But anyway, after the fix it, it should work.
