### ISSUE TITLE
Users cannot edit own records

### ISSUE THREAD

**Issue by mwandelt** [espocrm/espocrm#3156]
**Describe the bug**
When a role allows editing only own records for a specific entity type, a user of this role cannot edit his records of this type.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Define a role which allows editing only own records of a specific entity type (say Document).
2. Assign this role to a user.
3. When logged in as this user create a new record of the respective entity type.
4. After the record is created it is not possible to edit it. The edit button is not shown.

**Expected behavior**
The edit button should be visible, and it should be possible to edit the record.

**EspoCRM version**
v8.4.1

**Additional context**
I recognized this bug in v8.4 first, but it might well be that it existed in earlier versions too.

**Comment by yurikuzn** [comment]
I could not reproduce. When a user creating a record, the assigned user field was pre-filled with the own user. After creation, a user could edit the created record.

What *Assignment Permission* is set in the Role?

**Comment by yurikuzn** [comment]
Such an issue would likely have been caught while v8.4 was tested, or reported by users after the release. We suspect it could be some customization causing the problem. E.g. the assigned user is modified by a script.

**Comment by mwandelt** [comment]
The _Assignment Permission_ in the role has the value _not-set_. 

The user is assigned correctly to new records but still cannot edit them.

It seems, the problem occurs only with custom entities. With _Document_ entity I cannot reproduce it anymore, curiously. Is there a kind of cache for role-based privileges?

**Comment by yurikuzn** [comment]
The role case is cleared every time a role is changed. You can manually clear cache: Admin > Clear Cache.

**Comment by yurikuzn** [comment]
Does the Edit button appear after refreshing the page?

**Comment by mwandelt** [comment]
I have cleared the cache and refreshed the page many times, also reassigend the user. But the Edit button still does not appear.

What kind of customization could have an impact on this behaviour?

**Comment by mwandelt** [comment]
BTW, when I switch the role permission to _Team_  everything works fine.

**Comment by yurikuzn** [comment]
After the record is created, is the Assigned User is set to the user who created the record?

**Comment by mwandelt** [comment]
I think, I found the cause if the problem. In the role there were field-based rules that prohibited reading the _Assigned User_ for some entities. After I gave read access for the _Assigned User_ everything works fine. Sorry for the trouble and thanks for your help!
