### ISSUE TITLE
Multiple assigned users enabled with parameter in entity manager

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3158]
Multiple assigned users can be enabled in the Entity Manager with a checkbox. Available for custom entity types and some out-of-the-box entity types.

The old way of enabling multiple assigned users is removed.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/b752f43ee90806aaf1a33b821eda6fd34c27121e

**Comment by Kharg** [comment]
So glad to see this being added.

thank you for your hard work Yuri :)

**Comment by raalink938** [comment]
Its a great feature.

Would be great if this is enabled for Quotes and Invoice Entities in the Sales Pack also
