### ISSUE TITLE
Address field required error

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#316]
Hello,

This is EspoCRM version 4.2.7

The handling of requried address fields could be improved. If I set only billingAddressPostalCode to be required, then the entire cell is still highglighted in red, and the popup message uses the 'parent' field name not the particular sub-field.

E.g. this image:

![screen shot 2016-11-28 at 17 08 26](https://cloud.githubusercontent.com/assets/7381617/20678157/a0437f08-b58d-11e6-823c-ef31655d3bf5.png)

**Comment by yurikuzn** [comment]
Hi, Fixed https://github.com/espocrm/espocrm/commit/5b25e8b7e6bed2b8a6009e2ac8a5bb98c1685333 Thank for report

**Comment by alasdaircr** [comment]
Great -thanks,
Is it possible to only surround the 'Postal Code' sub-field with a red border?

**Comment by yurikuzn** [comment]
Not easy.

**Comment by alasdaircr** [comment]
I know :-) I looked into it. thanks for this though it helps
