### ISSUE TITLE
action handler for adminPanel

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#3161]
**Is your feature request related to a problem? Please describe.**
I am developing an extension to update the app timestamp by sending a POST request to the server, rather than manually updating it via the terminal.
I would like to add a new "Update App Timestamp" menu option to the "System" section of the Admin Panel (see screenshot). However, the current architecture doesn't seem to provide a way to attach a custom handler to an action defined in the adminPanel.json, like we can do for clientNavbar menuItems.

![image](https://github.com/user-attachments/assets/958f76bc-99e4-475b-a43d-8cb2ec8b124a)

**Describe the solution you'd like**
Ideally, I would like a way to define a custom handler for actions in the adminPanel.json, similar to how we can specify handlers for clientNavbar menuItems.
For example, allowing something like:
 
```javascript
{
    "system": {
        "label": "System",
        "itemList": [
            "__APPEND__",
            {
                "action": "updateAppTimestamp",
                "handler": "custom:handlers/admin-menu",
                "label": "Update App Timestamp",
                "iconClass": "fas fa-clock",
                "description": "Update App Timestamp"
            }
        ]
    }
}
``` 
This way, I could define the logic for sending the POST request to update the timestamp in my custom handler file.
This would be an upgrade-safe approach, as opposed to monkey patching the admin index file, which could break with future updates .
**Describe alternatives you've considered**
As a workaround, I was able to add the "Update App Timestamp" option as a menuItem in the clientNavbar, since menuItems do support custom handler definitions:

```javascript
{
    "menuItems": {
        "updateAppTimestamp": {
            "order": 0,
            "groupIndex": 10,
            "labelTranslation": "Global.labels.updateAppTimestamp",
            "handler": "update-app-timestamp:handlers/navbar-menu",
            "actionFunction": "updateAppTimestamp",
            "accessDataList": [
                {
                    "isAdminOnly": true
                }
            ]
        }
    }
}
``` 
While this works, it's not ideal since the "Update App Timestamp" action really belongs in the Admin Panel with the other system actions, rather than in the client navbar.

**Additional context**
As an alternative to supporting custom handlers in adminPanel.json, adding native support for updating the app timestamp via the Admin UI would achieve the same end goal.

Perhaps an "Update App Timestamp" option could be added to the existing "System" actions menu, calling the server-side timestamp update logic internally, without the need for an extension to define custom handlers.

In any case, having a convenient way to update the app timestamp from the Admin Panel would be a nice addition to improve the developer experience.

Thanks for considering this feature request.

**Comment by yurikuzn** [comment]
One can redirect to a view (with a regular link) and there, automatically call an HTTP request. I can't imagine handlers will be needed often for developers.

**Comment by Kharg** [comment]
> One can redirect to a view (with a regular link) and there, automatically call an HTTP request. I can't imagine handlers will be needed often for developers.

I had the same idea as a workaround even if less "classy".

It probably makes more sense.

**Comment by yurikuzn** [comment]
For what cases you find you need app timestamp clearing?

**Comment by Kharg** [comment]
> For what cases you find you need app timestamp clearing?

When developing such as adding buttons with custom handlers.

I helped a [user on the forum](https://forum.espocrm.com/forum/general/110430-button-in-accout-view-to-create-a-new-contact-in-full-edit-view) and I had to update the timestamp so many times for every little change to the handler.

Maybe this can be avoided using developer mode? But having to enable/disable it often would be more time consuming than updating the timestamp using the terminal.

**Comment by SuchAFuriousDeath** [comment]
Wouldn't it be more convenient to use 'items' instead of 'menuItems' for that? The only issue is that AFAIK there is no way to have admin-only items, so that's something Yuri could consider. But maybe it's already possible.

**Comment by SuchAFuriousDeath** [comment]
I added several items for quick use this way, such as for cache clearing and rebuild. 
![image](https://github.com/user-attachments/assets/bc69a7b4-3930-4a55-a2c1-9172990ce9f9)

**Comment by yurikuzn** [comment]
It's also possible to clear cache from the browser console. Cached JS files are stored in the browser's cache.

**Comment by yurikuzn** [comment]
> AFAIK there is no way to have admin-only items

https://docs.espocrm.com/development/metadata/app-client-navbar/#accessdatalist

```json
"accessDataList": [
    {"isAdminOnly": true}
]
```

**Comment by SuchAFuriousDeath** [comment]
If I'm not mistaken, that's only for menuItems and not items. Or is it for both?

**Comment by yurikuzn** [comment]
Correct. For items, there's a check on *isAvailable* method against the view. If the method exists in the view/

**Comment by SuchAFuriousDeath** [comment]
Thanks.
