### ISSUE TITLE
Stream: Quote reply on posts

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3163]
By clicking 'Quote Reply' on a stream post, it will paste quote contents into the text field.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/611e00fdb7ea1957d46bc0295a4d57625bb79d19

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/f9efca0523ed7eded42b3047071e904ff1ec84e4

Added the ability to quote only a selected text. The same as in GitHub issues.

**Comment by rabiibrahimi** [comment]
Nice features, i have tested it and it works great however i think there is a missing part. e.g imagine you have a stream with 15 posts and you want to copy an old post then you will scroll down to the post you want to copy and click **quote-reply**  and there is no feedback on what happened so you will have to scroll back to the textarea and then click on the field to focus then add more context or just post. I think it will be really better UX if when a user select text or just click on **Quote Reply** then it would be nice to automatically scroll back to the textarea and have the cursor focus. i have tested this code below and does the job

```
   quoteReply(quoted) {
        const quote = '> ' + quoted.split(/\r?\n|\r|\n/g).join('\n> ');

        let post = this.seed.attributes.post || '';

        const $textAreaElement = $(this.postFieldView.getTextAreaElement());

        if (post !== '') {
            post += '\n';
        }

        post += quote + '\n';

        this.setPostText(post);

        this.controlPreviewButton();
        this.controlPostButtonAvailability();
        this.postFieldView.controlTextareaHeight();
        this.enablePostingMode();

        // For better UX scroll to textarea and focus
        setTimeout(() => {
            $textAreaElement.focus();
            $textAreaElement.scrollTop(0);
        }, 100);
    }
   ```
   
   What do you think ?

**Comment by rabiibrahimi** [comment]
> Indeed, it's reasonable to focus and scroll.
> 
> [f031635](https://github.com/espocrm/espocrm/commit/f0316355746e4704245261a4ab958cda9a499c76)
> 
> I don't understand why you call `.scrollTop(0);`. When _focus_ is called, the browser performs scroll automatically.

I have tried focus() but the scroll was not added and browser didn't scroll to the element that is what i end up calling scroll and focus.
