### ISSUE TITLE
Allow external database configuration in install script

### ISSUE THREAD

**Issue by DGorsseRedCross** [espocrm/espocrm#3170]
**Is your feature request related to a problem? Please describe.**
I am installing EspoCRM with external MySQL database using the Azure Cloud. Currently I install EspoCRM on a virtual Machine, I dump the existing database, I create and connect this to a new external MySQL database (Azure). Then I configure the new database using the dumped database structure. This last step gives me a lot of errors of having default values (example: ERROR 1101 (42000) at line 4712: BLOB, TEXT, GEOMETRY or JSON column 'time_ranges' can't have a default value).

**Describe the solution you'd like**
The above steps can be avoided if I can connect EspoCRM to an external database upon installation, instead of after installation. When installing a new instance of EspoCRM, I can already point EspoCRM to an existing external database using the following settings as used in config-internal.php: 'host', 'dbname', 'user', 'password', 'actualDatabaseType' and 'actualDatabaseVersion'. This will avoid the unnessecary steps needed to dump the database and troubleshoot.

**Describe alternatives you've considered**
I have tried installing, dumping, connecting, troubleshooting but that gives me many errors. 

**Additional context**
This issue is also placed [here](https://github.com/espocrm/espocrm-installer/issues/8).

**Comment by yurikuzn** [comment]
Is is possible when installing through UI?

Install script is separate from this repository.

**Comment by DGorsseRedCross** [comment]
I don't think it is possible when installing through admin UI. Is this what you mean @yurikuzn ?

**Comment by yurikuzn** [comment]
There's the database host parameter when installing through the UI.

![image](https://github.com/user-attachments/assets/13913979-9759-446c-86b1-249d64c75f0d)

I assume install script you mean [this](https://docs.espocrm.com/administration/installation-by-script/).

**Comment by yurikuzn** [comment]
Note that it should be possible to install by running `cli/install.php`. https://github.com/espocrm/espocrm/issues/1594#issuecomment-583306161

You can create *config-internal.php* file with needed DB credentials manually before running installation.

**Comment by DGorsseRedCross** [comment]
Thanks @yurikuzn , can you let me know where we can find that the 'database configuration' page? It is not in a newly installed instance.

**Comment by yurikuzn** [comment]
If you drop an unzipped Espo build into a web root folder and access it via the browser, it the installation wizard will be shown (if the webserver is configured fine for Espo). The 3rd step of the wizard is the database configuration.

I'm not sure about your use case. Maybe using the built-in UI installer is not OK for you. Anyway, I believe Taras will reply to you in the issue in the installer repository.
