### ISSUE TITLE
Only Ints should be compared when searching by phone number

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#318]
Extra Characters[ (, ), -, " " (parantheses, dashes, spaces, etc...) have to be inserted to search phone numbers containing these characters. Search should ignore non-integers when comparing.

**Comment by yurikuzn** [comment]
This requires us to make script running after app upgrade that will be re-formatting existing phone numbers in database and store it to the additional column. Idea is nice. But how it implement.
