### ISSUE TITLE
Default reminder not set on task with default dateEnd

### ISSUE THREAD

**Issue by Gerlif** [espocrm/espocrm#3180]
When creating a task, I have the **default reminder** set to **email** in my user preferences.

However, when the task's **dateEnd** field is automatically populated through a system-level default setting (e.g., via formula or pre-configured logic), the default email reminder is **not applied.**

Steps to reproduce:
1. Set a default reminder to email in user preferences.
2. Create a task where the dateEnd is set automatically by a system default (not manually).
3. Observe that no default reminder is applied.

Expected behavior: A default reminder should be applied when a dateEnd is set, regardless of whether it's set manually or automatically.

EspoCRM Version: 8.4.1

**Comment by Gerlif** [comment]
Seems like I had something wrong configured, it's working as expected now!

**Comment by yurikuzn** [comment]
It will work if a record is created not but a current user. I'll look into how it can be fixed. But I'd consider it as a bug. It was not designed not work this way.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/3d1a2320de5a269a63484e7d2eec7f3cadc06a7c
