### ISSUE TITLE
Extend dateEnd default value options for Tasks

### ISSUE THREAD

**Issue by Gerlif** [espocrm/espocrm#3181]
I would like the ability to configure the default **dateEnd** value for Tasks beyond the current +1 week limitation.

Specifically, I'm looking for an option to set the default **dateEnd** to +1 month, but it would be beneficial to allow users to adjust this to any desired time period (e.g., days, weeks, months, years) for more flexibility.

**Use Case:** For project management purposes, we often work with longer task durations, and having the ability to automatically set a longer default deadline, such as 1 month, would be very helpful and help us save clicks for all tasks created.

EspoCRM Version: 8.4.1

**Comment by yurikuzn** [comment]
Use Date End (all day) instead. I doubt one would need +1-year with an exact time specified.

![image](https://github.com/user-attachments/assets/0f0ddeca-c519-41f5-81c7-73d0bc4cc659)

**Comment by Gerlif** [comment]
Perfect! I completely missed this option, this works, thanks!
