### ISSUE TITLE
findDuplicates function limited to first match only due to ignored LIMIT parameter

### ISSUE THREAD

**Issue by tomasrotek** [espocrm/espocrm#3182]
**Describe the bug**
The findDuplicates function in EspoCRM is limited to finding only the first duplicate record due to the SQL query generated by the findByWhere method in the file application/Espo/Core/Duplicate/Finder.php.

The issue is not the hardcoded limit itself, as self::LIMIT is correctly set to 5, but rather that the LIMIT parameter appears to be ignored when executing the SQL query. Even with self::LIMIT set to 5, the SQL query always returns only one result due to an apparent LIMIT 0, 1 being enforced in the final query.

The affected code section is in the findByWhere method: https://github.com/espocrm/espocrm/blob/699705d44a75abc88f96af3e98c0bae2396e8213/application/Espo/Core/Duplicate/Finder.php#L117

**Problem**
Despite self::LIMIT being set to 5, the SQL query seems to always enforce LIMIT 0, 1, and as a result, only the first duplicate record is returned, ignoring the specified limit.

**To Reproduce**
1. Use the findDuplicates function in EspoCRM to search for duplicate records.
2. Inspect the SQL query generated by the findByWhere method.
3. Observe that the query still includes LIMIT 0, 1, despite attempts to modify the limit.

**Expected behavior**
The findDuplicates function should honor the self::LIMIT value (which is set to 5) and return multiple duplicate records up to the limit specified.

**EspoCRM version**
8.4.2

**Comment by yurikuzn** [comment]
It was already fixed month ago I believe. https://github.com/espocrm/espocrm/commit/debd0f700e86fc17ad667e7c9deb22a9b54c1a71

**Comment by tomasrotek** [comment]
> It was already fixed month ago I believe. [debd0f7](https://github.com/espocrm/espocrm/commit/debd0f700e86fc17ad667e7c9deb22a9b54c1a71)
> 
> Will be available in the minor release.

I tried to use this new file, but in the final sql query there is still LIMIT 0, 1 (->limit(0, self::LIMIT); is not used).
