### ISSUE TITLE
List view column resize

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3186]
The ability to resize columns in the main view list. The changed width is stored. Can be reset to default.

Requirements:

* At least one column in the layout should have an empty width. By default, it's the *name* column.

Limitations:

* Not applicable on small screens (less then 768px).

**Comment by eymen-elkum** [comment]
Maybe off topic, but also fixed headers is one of the most requested features so far

**Comment by yurikuzn** [comment]
Out of many requests we have received the fixed header was not among popular. But any way it's offopic.

**Comment by yurikuzn** [comment]
Quite complex to solve, harder that it may to seem. https://github.com/espocrm/espocrm/commit/df7f75ec5297d83d00c8f6d1f26fb4660ab7b1e4

**Comment by rabiibrahimi** [comment]
The way it is implemented is elegant UI and UX wise 👍

**Comment by yurikuzn** [comment]
There were a few edge cases which took more time to implement than the basic functionality.

**Comment by grray** [comment]
Small note: you also have to turn it on in the menu in table header (next to rows count).
