### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3190]
The collaborators feature can be enabled for an entity type in the Entity Manager.  Once enabled:

* A link-multiple field *Collaborators* will be automatically created.
* A bool filter *Shared* will be added.

Users added as collaborators to a record will have *read* and *stream* access considering they have an access level in Roles other than *no*.

Assignees are automatically added to collaborators.

Assignment Permission is required to be able to add a user to a collaborator. 

Available for:

* custom entities created via the Entity Manager
* Tasks
* Cases
* Accounts
* Contacts
* Leads
* Opportunities
* Documents
* Knowledge Base Articles
* Target Lists

Portal users cannot be added as collaborators.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/089fc98fdebeee5e911d24be270a9e18a60b0caf

**Comment by rabiibrahimi** [comment]
I come across a scenario that cause error. when enabling both **Multiple AssiginedUsers** and **Collaborators** at once then only **entityUser** table will be created which cause an issue as **entityCollaborator** table won't be created. below error from the log 

```php
[2024-11-26 11:46:32] CRITICAL: (42S02) SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.entity_collaborator'
doesn't exist :: GET /Opportunity/671f8d6d128dfb8f9 ::
C:\herd\espodev\site\application\Espo\ORM\Executor\DefaultSqlExecutor.php(77)
```

Steps to produce: 

1- go to entity manager > oppotunity 
2- edit (check both Multiple AssignedUsers and Collaborators
3- save the changes
4- visit any opportunity record (an error 500 is produced)

I have tried this on two different instances (no customization at all).
