### ISSUE TITLE
Global View Transitions

### ISSUE THREAD

**Issue by hajek-raven** [espocrm/espocrm#3193]
**Is your feature request related to a problem? Please describe.**  
EspoCRM lacks smooth transitions between views, making the user experience feel less fluid and modern.

**Describe the solution you'd like**  
Integrate the [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) to enable seamless, native transitions between pages, improving overall user experience.

**Describe alternatives you've considered**  
Considered CSS animations and JavaScript libraries, but they’re less performant and harder to maintain than the View Transitions API.

**Additional context**  
The API is widely supported in modern browsers and would enhance EspoCRM's visual appeal and usability.

**Comment by yurikuzn** [comment]
Hi,

Not planned for the nearest future. I'm not a fan of most of transitions when it comes to an app used on the daily basis.

**Comment by hajek-raven** [comment]
Hello,
I understand and appreciate your perspective on minimal animations for a daily-use app.

However, subtle and well-executed animations can make the system feel more polished and modern. This refinement can sometimes influence decision-making for business users when evaluating software options, as first impressions and user experience play a crucial role in adoption.

Thank you for considering this!

**Comment by yurikuzn** [comment]
Any main view transition will be hated by users in a few days after extensive use. I spend a lot of time on this topic and the decision is already made long before. I can't discuss any further due a having a lot of work. I don't agree about polished and modern.
