### ISSUE TITLE
Hosting EspoCrm Locally

### ISSUE THREAD

**Issue by Aelkeris** [espocrm/espocrm#321]
So, i have tried installing espoCrm two ways.

One is using bitnami. And another by cloning github repo.

While using bitnami, i get espo set up on my localhost, i have absolutly no idea how to customise EspoCrm.
So i figured i need the github version of the Crm. Now, when i cloned the repo, and i put it in my wampserver's www folder, it simply will not work. 

I think i know how i should set this up, but i can't, or am doing something wrong. I know this is not much or enough information about my issue, but i would be happy to provide more, i just need some general tips on where to go, and how to locally host the EspoCrm i have cloned, and how to actually customise it.

Thank you all in advance.

**Comment by yurikuzn** [comment]
You can download EspoCRM build from the website https://www.espocrm.com/download/

**Comment by ayman-alkom** [comment]
@Aelkeris you don't need to clone the repo unless you want to make development on the code, if so you can follow [these instructions](https://github.com/espocrm/espocrm#how-to-get-started-for-developers):
