### ISSUE TITLE
Registering container service via Dependency Binder not functioning following documentation

### ISSUE THREAD

**Issue by simon-horny** [espocrm/espocrm#3215]
**Describe the bug**
Following the documentation, I am unable to successfully register a container service. Binding simply doesn't seem to do anything.

**To Reproduce**
Explicit steps to reproduce the behavior:
1. Create JSON in `src/custom/Modules/{moduleName}/Resources/metadata/app/containerService.json`
2. See context for structure (addendum 1) 
3. Create a binder `src\custom\Espo\Modules\{moduleName}\Binding.php`
4. Bind the service, see context for contents (addendum 2)
5. Rebuild and clear cache
6. Call (unsuccessfully) said service

**Expected behavior**
Successful dependency injection being called with `$this->serviceName` and being able to see the container service with this command: `bin/command app-info --container`

**EspoCRM version**
8.4.2

**Additional context**
Addendum 1:

``` JSON
{
  "globalSearchService": {
    "className": "Espo\\Modules\\{moduleName}\\Tools\\GlobalSearch\\Service"
  }
}
```
Addendum 2:

```php
namespace Espo\Modules\{moduleName};

use Espo\Core\Binding\BindingProcessor;
use Espo\Core\Binding\Binder;

class Binding implements BindingProcessor
{
    public function process(Binder $binder): void
    {
           $binder->bindService('Espo\Modules\{moduleName}\Tools\GlobalSearch\Service', 'globalSearchService');
    }
}

```

**Comment by arkadiyasuratov** [comment]
I think it's supposed to be like this

```php
$binder->bindService('Espo\\Modules\\{moduleName}\\Tools\\GlobalSearch\\Service
```

**Comment by yurikuzn** [comment]
It was literally the last my commit a hour ago: https://github.com/espocrm/espocrm/commit/56735e93585af50ae9d6950e15ede0a8fe7c89ac

Please use the form for help.
