### ISSUE TITLE
Reduce list item loading times by making equivalent selectors

### ISSUE THREAD

**Issue by jarca0123** [espocrm/espocrm#3222]
**Is your feature request related to a problem? Please describe.**
I'm experiencing significant loading delays when dealing with thousands of list items in the record list (a client requirement). Currently, it takes about two minutes to load in my instance. This delay occurs because the substring of the parent view varies, forcing setElement to search through the entire page document. The functions here might explain why:

https://github.com/espocrm/espocrm/blob/63755bb0b912898e47e88afc1c0928920e258bd2/client/src/views/record/list.js#L2960-L2964

https://github.com/espocrm/espocrm/blob/63755bb0b912898e47e88afc1c0928920e258bd2/client/src/views/record/list.js#L2994-L3006

**Describe the solution you'd like**
I propose changing tr to .list-row or vice versa. In testing, this modification reduced the loading time from 2 minutes to approximately 20 seconds.

**Comment by jarca0123** [comment]
I changed 

```
 getItemEl(model, item) { 
     return this.getSelector() + 
         ' tr[data-id="' + model.id + '"]' + 
         ' td.cell[data-name="' + item.columnName + '"]'; 
 } 
```
to

```
 getItemEl(model, item) { 
     return this.getSelector() + 
         ' .list-row[data-id="' + model.id + '"]' + 
         ' td.cell[data-name="' + item.columnName + '"]'; 
 } 
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/226ae20f7b4610f33e0f3df9da659161b679dac3

It gave me about 10-15% percent improvement for 100 rows.

**Comment by yurikuzn** [comment]
As I understand, browsers have memory for used selectors, that's why it gives benefit in performance to use the exactly same selector parts.

**Comment by yurikuzn** [comment]
I rewrote the rendering mechanism in the framework. This was the first planned iteration of modernization. Now it does not build a raw HTML but build a DOM. This might not improve performance significantly but the benefit is that assigning DOM selectors to child views won't be needed anymore (except cases when a child view deliberately is not rendered along with parent). It also open the way for future modernizations.
