### ISSUE TITLE
Optimize template caching for modules in frontend

### ISSUE THREAD

**Issue by jarca0123** [espocrm/espocrm#3223]
**Is your feature request related to a problem? Please describe.**  
This is related to the feature request of optimizing list items, which is here: https://github.com/espocrm/espocrm/issues/3222. It appears that when dealing with thousands of list items (and possibly only for a custom template), bullbone ignores the template cache entirely. This likely happens because the cache is being accessed before the template finishes loading. I haven't looked into it much, so there might be a better solution than what I'm suggesting.

**Describe the solution you'd like**  
In bullbone, modifying getTemplate to this function makes the run time (while also having applied the fix from the issue) drop from about 20 seconds to 8 seconds:

```javascript
getTemplate(name, layoutOptions, callback) {
    layoutOptions = layoutOptions || {};

    if (!layoutOptions.layout && !name) {
        throw new Error(`Can not get template. Not enough data passed.`);
    }

    if (name && !layoutOptions.layout) {
        let template = this._getCachedTemplate(name);

        if (template) {
            callback(template);
            return;
        }
    }

    let then = (template) => {
        if (name && !layoutOptions.layout) {
            let template = this._getCachedTemplate(name);

            if (template) {
                callback(template);
                return;
            }
        }

        if (this.compilable) {
            template = this.compileTemplate(template);
        }

        this._templates[name] = template;

        callback(template);
    };

    if (layoutOptions.layout) {
        this._buildTemplate(layoutOptions.layout, layoutOptions.data, then);
        return;
    }

    this._loader.load('template', name, then);
}
```

**Comment by yurikuzn** [comment]
IIRC correctly I disable cache there deliberately. Does it provide any benefit?

**Comment by yurikuzn** [comment]
It seems it was another cache that I disabled. Here we have issue with

Could you confirm that the performance improvement is also observed when:

* developer mode is disabled
* cache is enabled
* page was refreshed after the first load after clearing cache.

**Comment by yurikuzn** [comment]
Fix: https://github.com/yurikuzn/bull/commit/8ffcc330486ebc86c2108c0716d4e5c6277c1ffc
