### ISSUE TITLE
Update Call's record detail view to fix visibility of actions (Set Held - Set Not Held)

### ISSUE THREAD

**Issue by rabiibrahimi** [espocrm/espocrm#3228]
**Describe the bug**
Call record details actions (Set Held - Set Not Held) are still visible even though the user role's field scope is only (read) for the status field. So when the user with such role visit call record they can still view (set held & set not held) actions. The call's record detail view needs to be updated. 

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. create a role with ability to create call - edit | field level: status (read: yes | edit: no)
2. access instance as the user with role above
3. create a call - check the actions (set held & set not held) 
...

**Expected behavior**
Call record detail view need to be updated. 

**Screenshots**

**EspoCRM version**
8.4

**Additional context**

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/43e7a327d09829a9b871fad912989f1e7e772d18
