### ISSUE TITLE
Possibility for Green acknowledgment checkmark on stream for other users

### ISSUE THREAD

**Issue by RCFilm** [espocrm/espocrm#323]
Possibility for Green acknowledgment checkmark on stream for other users

the user or system would leave a comment in the stream then another user could click it for acknowledgment that the comment has been received maybe even in small font next to the greened check it says who acknowledged the comment

**Comment by rodrigoscoelho** [comment]
Perfect

Email enviado usando um celular....

Em 1 de dez de 2016 7:26 PM, "Whrealty" <notifications@github.com> escreveu:

**Comment by alasdaircr** [comment]
This is great idea - but maybe also link it to the Mention feature - so that all mentioned users can Acknowledge the note.

This would work across all Streams.

**Comment by alasdaircr** [comment]
Then if you get that far, why not allow 'reactions' just like github for all users. Thumbs up / down, Smile.
