### ISSUE TITLE
Same layout is requested multiple times from the server and in parallel, causing slowdown when loading (module issue)

### ISSUE THREAD

**Issue by jarca0123** [espocrm/espocrm#3231]
**Describe the bug**
When loading a detail with multiple record lists (which is in our module), it loads the same layout multiple times. Which makes sense, but it makes requests to the server multiple times, in which the requests are stalled by the browser, causing the long loading.

**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Create multiple record lists for an entity (in our module)
2. Try to load the creation menu for the entity
3. In Network in Dev Tools, see the multiple requests

**Expected behavior**
I would expect it to make only one request.

**EspoCRM version**
8.4.2

**Additional context**
This might be partly caused by a module, but it might be worth fixing. I found a fix modifying the layout manager:
```javascript
get(scope, type, callback, cache) {
  if (typeof cache === 'undefined') {
    cache = true;
  }
  const key = this.getKey(scope, type);
  
  if (cache) {
    if (key in this.data) {
      if (typeof callback === 'function') {
        callback(this.data[key]);
      }
      return;
    }
  }

  if (this.cache && cache) {
    const cached = this.cache.get('app-layout', key);
    if (cached) {
      if (typeof callback === 'function') {
        callback(cached);
      }
      this.data[key] = cached;
      return;
    }
  }

  this.pendingRequests = this.pendingRequests || {};

  if (this.pendingRequests[key]) {
    this.pendingRequests[key].then(layout => {
      if (typeof callback === 'function') {
        callback(layout);
      }
    });
    return;
  }

  this.pendingRequests[key] = this.ajax.getRequest(this.getUrl(scope, type))
    .then(layout => {
      if (typeof callback === 'function') {
        callback(layout);
      }
      this.data[key] = layout;
      if (this.cache) {
        this.cache.set('app-layout', key, layout);
      }
      delete this.pendingRequests[key];
      return layout;
    })
    .catch(error => {
      delete this.pendingRequests[key];
      throw error;
    });
}
```

**Comment by jarca0123** [comment]
I should add that a record list in our module is a list with items (of an entity) which you can edit inline. Also, this issue probably might occur without modules when having multiple relationship panels, I'll check.

**Comment by yurikuzn** [comment]
I'll look into when get a chance. Usually there's should not be more than 1-2 of the same layouts. The other option, which I prefer, is to load a single layout explicitly and then pass the array to child list views in the `listLayout` param.

**Comment by jarca0123** [comment]
Well, I cannot reproduce this on the relationship panels, but I still think this might be more convenient for module developers. Your solution seems good to me though, I'll probably try to fix it in our module.

**Comment by yurikuzn** [comment]
I don't understand how it can be affected by the fact that it's module.

**Comment by jarca0123** [comment]
I may not fully understand what you mean, but if I get it right - you're correct that I shouldn't have implied it was a module-specific issue. The problem exists regardless of whether it's in a module or not. The proposed change would just make development more efficient by preventing duplicate requests.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/7e349c37501cfef8c21905b933947418ca583070

Thank you for help.
