### ISSUE TITLE
Read-only currency fields do not append the three-letter currency abbreviation (as in USD, CZK) to payloud on request

### ISSUE THREAD

**Issue by simon-horny** [espocrm/espocrm#3238]
**Describe the bug**
We're dynamically calculating final price on leads (`opportunityAmmount`) using some additional fields (`commision + minimalPrice`) for commission with JavaScript, via the `this.model.set()` and event listeners listening on change on the model. This occurs only for specific lead types. This field works fine provided it is not that specific lead type, however, the moment this field is dynamically set up as read-only, it turns into plain `<div>` with the currency updating properly, even having the proper symbol for currency (I work with CZK so it's Kč, that's all good, we just pipe in the number into the model), however, on save we receive 400 code with validation error, because the currency abbreviation (`opportunityAmmountCurrency`) isn't passed in the request. The moment we set it up with some other lead type manually, currency will be set in database and it will work just fine, but if the lead is fresh with no currency yet set up in DB, it's impossible to save the lead with this field as read-only, because `opportunityAmmountCurrency` isn't sent to the backend. 

**To Reproduce**
1. Setup a lead currency field that will be read-only dynamically based on any condition of your choice
2. Create a new lead with the non-read-only currency field type (say Sale)
3. Edit the lead, change to the state with currency field (say Buy) as read-only and fill in the currency field from which is the read-only field calculated from (either `commision `or `minimalPrice`, point is to get the `opportunityAmmount` to be calculated)
5. Check console, see that ie. `opportunityAmmountCurrency` is missing from the payload, even though it's appended to other, non-read-only fields. 

**Expected behavior**
Appending currency fields (as in attributes) even when the field is read-only preferably, if not, then consistency with read-only field not being sent at all in the payload.

**Screenshots**
Bad scenario: 
![image](https://github.com/user-attachments/assets/dc73eccd-7a4b-465e-8345-9f17731ae15d)

Good scenario, after failed save attempt, this one is successful:
![image](https://github.com/user-attachments/assets/889e7296-9ec2-439c-b1b8-e1050d723ed2)

Now everything works, since it's set up in DB:
![image](https://github.com/user-attachments/assets/e405d807-63b1-4791-8a8e-27c88b2b9955)

**EspoCRM version**
8.4.2

**Additional context**
Setup for listener and model change
``` JavaScript
this.listenTo(this.model, "change", () => {
      this.model.set(
        "opportunityAmount",
        String(
          Number(intermediaryPriceClient) +
          Number(intermediaryRewardMoney)
       )
      );
    }
});
```

**Comment by yurikuzn** [comment]
When a record is saved, the model values are sent. We can't filter out read-only fields at this step without massive redesign which is not desirable.

Workaround for your case is to unset the value in the before save api script. But I'm not fully sure at the moment.

**Comment by yurikuzn** [comment]
Calculating price should be done in the backend as well (if you don't do it yet).

**Comment by yurikuzn** [comment]
If I understood all correctly, it's an expected behavior, not a bug. You definitely need to set all fields manually (amount and currency) or/and unset in the backend before validation.

Thing is that when we designed the dynamic logic it was a front-end only functionality. It was in the backlog for long to move it make it both frontend/backend but it's a big breaking change and some migration complexities. Eventually we are going to do it.
