### ISSUE TITLE
Special characters in incoming ICS attachment cause Error 500

### ISSUE THREAD

**Issue by ahvensoppa** [espocrm/espocrm#3239]
**Describe the bug**
Incoming emails with ICS attachments containing special characters like åÅäÄöÖ cause an Error 500
**To Reproduce (MANDATORY, DO NOT REMOVE)**
Explicit steps to reproduce the behavior:
1. Send an email with an attached ICS containing åÅäÄöÖ to an EspoCRM instance and try to open this email.
2. EspoCRM fails with an Error 500
3. ...
...

**Expected behavior**
EspoCRM should open the email and process the ICS

**Screenshots**

**EspoCRM version**
Version 8.4.1

**Additional context**

**Comment by yurikuzn** [comment]
Could you check the log for error details?

**Comment by yurikuzn** [comment]
We could not reproduce. If we receive more input, we can look into again.
