### ISSUE TITLE
Field Manager: Ability to specify default values for Date and DateTime fields

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#324]
The default field for the DateTime field, is sort of pointless at the moment. It would be extremely helpful to make tasks automatically due the next day, if not set.

**Comment by yurikuzn** [comment]
Actually it's possible to set some values there:

**Comment by rodrigoscoelho** [comment]
It would be good a today button when setting a date independently where.
Sometimes is boring be changing months, days, until we get the today to be
clicked.

Email enviado usando um celular....

Em 2 de dez de 2016 17:28, "Yuri Kuznetsov" <notifications@github.com>
escreveu:

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/9e3096b674274646fe1fc182021b31574af62338
