### ISSUE TITLE
Users: Tasks panel

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#328]
When viewing your tasks via the Tasks list, our employees usually have the 'only my' option checked. Checking another employees task means resetting their views. A panel on the Users detail page listing their tasks would be very useful, and makes sense intuitively.

**Comment by donavynelliott** [comment]
Another side note: the side panels on users detail display meetings & calls but not tasks.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/1096f719ae5fa80257a08a7a7baf0886345918f7
