### ISSUE TITLE
Popup Reminders: Display popup to users mentioned via @username

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#329]
Currently the only notifications users receive is via email. I find this rather silly considering every other notification still comes through the notification panel, but users still need their email up in case of a mention.

**Comment by yurikuzn** [comment]
Actually there must be in-app notification in the top-right corner.

**Comment by donavynelliott** [comment]
You're correct. I'm not sure how i missed this. I believe popup reminders are a great way of displaying priority notifications.

**Comment by yurikuzn** [comment]
We don't want to have popup notifications for this.
