### ISSUE TITLE
Notifications for Mentions in stream 'to myself', shows up as {target} 

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#330]
Notification displays the following:

> User mentioned you in post to **{target}**
> 'message content'
> 10:30am

Version 4.3.0-beta.2

**Comment by yurikuzn** [comment]
I believe it should be already fixed in master but I will check.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/def7abe3ba0d31c2a19bdf4615f044e0e2707a15
