### ISSUE TITLE
Entity unique field

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#332]
Hi, can we add this option to an entity field

**Comment by yurikuzn** [comment]
Hi, Only in metadata manually
"unique": true

**Comment by ayman-alkom** [comment]
great, I will test it

**Comment by ayman-alkom** [comment]
it works thanks

**Comment by ayman-alkom** [comment]
@yurikuzn in fact it is working but not as friendly validation, instead **Bad server Response** made

**Comment by ayman-alkom** [comment]
if you want I can do a PR for it, or let know if you will do it

**Comment by yurikuzn** [comment]
If you made the message user friendly would be good if you show how.

**Comment by ayman-alkom** [comment]
Why you dont like PRs?

**Comment by yurikuzn** [comment]
No problems with PRs but we can merge only those that meet coding style, have no potentials problems and when we really sure we need this feature.

**Comment by donavynelliott** [comment]
Every entity has a unique ID already, what would be the purpose of generating a second unique ID?

**Comment by ayman-alkom** [comment]
@donavynelliott sometimes we need unique names
@yurikuzn I may do it and show you how I did, for now closing the issue

**Comment by yurikuzn** [comment]
@ayman-alkom If you have it done please make PR or provide the link to commit so I could take a look. Thanks.
