### ISSUE TITLE
Is there a way I can have Tasks include a duration, and therefore appear in the hourly section of Calendar?

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#335]
The task entity has the dateEnd & dateStart fields, which both include times. However, in the Calendar they appear as all day events.

**Comment by donavynelliott** [comment]
In the timelime tab of the Calendar, tasks are laid out hourly.

**Comment by yurikuzn** [comment]
application/Espo/Modules/Crm/Resources/metadata/clientDefs/Calendar.json

Try to remove Task from allDayScopeList. Not tested.

**Comment by donavynelliott** [comment]
I did this. It changed the color off the task. Does this have something to do with Task not having a duration field?

**Comment by yurikuzn** [comment]
It's not caused by not having duration field. I've tried to do what I described in my previous comment and it worked out. Clear cache after change.

**Comment by yurikuzn** [comment]
Task doesn't have duration field. You will need to replicate it from Meetings if you want to have it.

**Comment by donavynelliott** [comment]
It was because I commented out the 'allDayScopeList' key instead of removing the 'task' value. Thank you.
