### ISSUE TITLE
Emails not importing emails from iPhone mail client

### ISSUE THREAD

**Issue by Whrealty** [espocrm/espocrm#336]
Emails not importing emails from iPhone mail client

Note the emails Do import from the iPad Mail client app

Espo.ERROR: EmailAccount ***************** (Import Message w/ zend-mail): [0] Invalid header value detected [] []

**Comment by yurikuzn** [comment]
You need to install mailparse extension (it's pecl extension) for your php.

**Comment by Whrealty** [comment]
i did run perc install to install mailparse with successful install and added the extension to my php.ini 
then restart services

but when i run php -m
i get 

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by yurikuzn** [comment]
Maybe php for CLI have another php.ini.

**Comment by Whrealty** [comment]
1 step forward 2 steps back :) mailparse is up and running

i don't see any errors in the espo log but the email still don't get imported from the iPhone mail client 
Note: i am not having no issues with any other mail clients at this time will be testing over the next few days

Note 2: it would seem not to be a big issue the IOS device is a iPhone 7 10.2 but i am only having the issue with this one device
