### ISSUE TITLE
Need to trim all input fields before submit

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#34]
It's possible to add whitepsace at the end of fields like name, lastname, etc

This messes with searching when the full name is used

eg
```
first_name = 'John ';
last_name = 'Smith';
```
Perform a search for ```John Smith```, and the contact will not show. Suggest trimming all inputs by default. Not sure where best to do this.

**Comment by yurikuzn** [comment]
It's reasonable to trim when search by main text filter.

**Comment by alasdaircr** [comment]
Much better to not add whitespace at the beginning / end of values into the database in the first place

**Comment by yurikuzn** [comment]
Aready fixed for person names, emails, phone numbers.
