### ISSUE TITLE
How to deal with deleted records

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#341]
does we have a way to list them and remove, or even a clean up service as schedule job

**Comment by yurikuzn** [comment]
No such ability. They are not removed.

**Comment by yurikuzn** [comment]
You can create additional cleanup job like application/Espo/Jobs/Cleanup.php that will delete old removed records from db.

**Comment by ayman-alkom** [comment]
thanks for the replay, I will try to do that
