### ISSUE TITLE
General error: 1366 Incorrect integer value: '' for column 'opted_out'

### ISSUE THREAD

**Issue by bosonno** [espocrm/espocrm#347]
latest version

HTTP HY000
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'opted_out' at row 1

?entryPoint=subscribeAgain&id=...

https://github.com/espocrm/espocrm/blob/c17fb9ab1e6732c3829b6128a981c3e4d7f62154/application/Espo/Modules/Crm/EntryPoints/SubscribeAgain.php

**Comment by yurikuzn** [comment]
What mysql version do you have?

**Comment by bosonno** [comment]
5.7.9

**Comment by bosonno** [comment]
4.3.0

Didn't know there is a 4.3.1 already.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/1975d16f3a5032abd901f05aefa3a2e2cdf6c709

**Comment by bosonno** [comment]
works. thank you.
