### ISSUE TITLE
Special chars in email

### ISSUE THREAD

**Issue by goodkiller** [espocrm/espocrm#36]
When e-mail contains ö, ä, ü, ß or are in different charset, then InboundEmail cut e-mail content half and does not display content after special chars.

There are also refrerence: http://forum.espocrm.com/bug-reports/3693-special-signs-in-emails?routestring=forum/bug-reports/3693-special-signs-in-emails

**Comment by yurikuzn** [comment]
What is character encoding of those email?

I tried
`
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable 
`
that works correctly.

**Comment by goodkiller** [comment]
Accept-Language: et-EE
Content-Language: et-EE
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
acceptlanguage: et-EE
Content-Type: text/plain; charset="iso-8859-15"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

**Comment by alasdaircr** [comment]
this looks like outlook - if so which version?

**Comment by alasdaircr** [comment]
See this too https://github.com/espocrm/espocrm/issues/2

The way emails are decoded in Espo is a bit confusing.

**Comment by goodkiller** [comment]
It's not outlook, I'm unable to determinate what client is used but seems like it's problem with iso-8859-15 only.

**Comment by yurikuzn** [comment]
http://forum.espocrm.com/bug-reports/3693-special-signs-in-emails?routestring=forum/bug-reports/3693-special-signs-in-emails
