### ISSUE TITLE
Missing link (to return) in the title of the administration screens

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#360]
Precisely that. I attach captures to make it look. Some menu items present the link and others do not.

Las pantallas en las que falta en enlace son las siguientes:

- Schedule jobs
- Users
- Teams
- Roles
- Group Emal Accounts
- Personal Email Accounts
- Email Filters
- Email Templates
- Portals
- Portal Usars
- Portal Roles
- Import

To see screenshot go to: [http://forum.espocrm.com/...of-the-administration](http://forum.espocrm.com/forum/bug-reports/25743-lack-link-to-return-in-the-title-of-the-screens-of-the-administration)

**Comment by yurikuzn** [comment]
There are obstacles with this. Some of these locations can be reached from not admin page and by not admin users.

**Comment by PanuWeb** [comment]
It is true. Then you would have to look for some to put a "back" button to return to the previous screen from which it was accessed.

That is the problem with which I am. When accessing for example "Portals" I can not go back to the Administration, the only way is to use the "previous navigatior button" or again "Menu> Administration".

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/cc9ed3f365380aea50ba38bbd5f2607535cf5563

**Comment by PanuWeb** [comment]
Thanks a lot. It is much appreciated.
