### ISSUE TITLE
Fault to rebuild database schema.

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#361]
How can I fix a problem like this, does export and import the database cause such this error?

`Fault to rebuild database schema. Details: An index with name 'idx_795fd9bbb03a8386' was already defined on table 'attachment'. [] []`

**Comment by yurikuzn** [comment]
It shouldn't have happened w/ import or export. Not sure what it is. It usually happens when index were added to schema after records already existed in db.
