### ISSUE TITLE
Not translated items on Opportunities by Lead Source dashlet

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#365]
In particular "Opportunities by Lead Source" and "Sales by Month"

Here you can see the captures: [http://forum.espocrm.com/forum/bug-reports/25819-i-can-not-translate-the-dashboard-graphics](http://forum.espocrm.com/forum/bug-reports/25819-i-can-not-translate-the-dashboard-graphics)

**Comment by yurikuzn** [comment]
Did you try to reset preferences or create new user to check if it will be translated there.

**Comment by PanuWeb** [comment]
I am testing it on a new installation and solves the problem with the months, but with the source of the lead is maintained

**Comment by PanuWeb** [comment]
New screenshots

[http://forum.espocrm.com/forum/bug-reports/25819-i-can-not-translate-the-dashboard-graphics?p=25847#post25847](http://forum.espocrm.com/forum/bug-reports/25819-i-can-not-translate-the-dashboard-graphics?p=25847#post25847)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/a8a1acdbd0baad4cd24defe92b42995ce7ed5c7f
