### ISSUE TITLE
Entity-less module namespace not included in unify

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#37]
Hi I'm working on an extension which runs hooks, but does not add a new entity type.

If I do not create a fake entity such as
```
<modulename>/Resources/metadata/entityDefs/Placeholder.json
{
	"entity": false,
	"layouts": false,
	"tab": false,
	"acl": false,
	"module": "<modulename>",
	"stream": false,
	"customizable": false,
	"importable": false
}
```

then the namespace is never included during a Rebuild, and the hooks are not added to `hooks.php`. Should I be doing something differently, or does the unify stage need changed to handle this situation?

**Comment by tmachyshyn** [comment]
Hi,

Please move the file to this location <modulename>/Resources/metadata/**scopes**/Placeholder.json

**Comment by alasdaircr** [comment]
aye yes that was a typo, it *is* in scopes :)

**Comment by alasdaircr** [comment]
I was just checking that there was no other way to do this without declaring a scope this way

**Comment by tmachyshyn** [comment]
If you want to use hooks you have to declare a scope in such way.

**Comment by alasdaircr** [comment]
Great - thank you for confirming that.

**Comment by yurikuzn** [comment]
Will it work if hook for some scope is located in another module than that scope belongs to?

**Comment by alasdaircr** [comment]
Not sure - but I don't really understand the difference between the terms scope and module.

**Comment by alasdaircr** [comment]
Looks like when I had a Common hook from a custom module, the built-in Common hooks are lost. Need to check this against master though, so I'll report back.

**Comment by yurikuzn** [comment]
Module is directory name where code & resources are grouped.
Scope is more specific item. It could be Account, Calenar, Notification. Some of them could have their own entity, some - not (like Calendar or Stream).

Maybe that was one of bugs Taras fixed recently.

**Comment by alasdaircr** [comment]
Ah ok that is a lot clearer. Well to answer your question, the scope can be anything, like I showed earlier. There just needs to be one declared in order for the module to be recognized - which then allows hooks to be registered.

**Comment by yurikuzn** [comment]
Will will fix it so that it won't be needed to define scope. It was a mistake. Thanks.

**Comment by yurikuzn** [comment]
Fixed.
