### ISSUE TITLE
Dates not sorting in correct order

### ISSUE THREAD

**Issue by donavynelliott** [espocrm/espocrm#377]
![capture](https://cloud.githubusercontent.com/assets/16009956/22158374/c7bf5732-def0-11e6-95a1-2370caafc7c5.PNG)

**Comment by yurikuzn** [comment]
It's because there are mix of date and datetime fields. It's not easy to make it sorted properly. Problem with timezone, that date field doesn't have but datetime field does have.

**Comment by yurikuzn** [comment]
I think if system timezone (Administration > Settings) matches user's timezone sorting should be proper. But it will work only for new tasks.

**Comment by donavynelliott** [comment]
I did check that my timezone was the same as the system timezone. After that I updated the date values to have times. The sorting is now in the correct order.
