### ISSUE TITLE
Only admin can post to API

### ISSUE THREAD

**Issue by Eragon666** [espocrm/espocrm#380]
Hi,

I am trying to setup EspoCRM. Everything seemed to be working fine until I tried it with another (non-admin) user.

I am getting a 403 error, when I promote the user to admin everything can be changed.

The log message:

> [2017-01-24 20:38:15] Espo.ERROR: API [POST]:/:controller, Params:Array (     [controller] => Case ) , InputData: {"status":"New","priority":"Normal","type":"","teamsIds":["58865e5c7d5fc714f"],"teamsNames":{"58865e5c7d5fc714f":"Technische Commissie"},"name":"test","accountName":null,"accountId":null,"contactsIds":[],"contactsNames":{},"description":""} -  [] []
> [2017-01-24 20:38:15] Espo.ERROR: Display Error: , Code: 403 URL: /crm/api/v1/Case [] []

I already tried all steps on this page:
https://www.espocrm.com/blog/apache-server-configuration-for-espocrm/

My apache2.conf:

> <Directory />
>         Options FollowSymLinks
>         AllowOverride None
>         Require all denied
> </Directory>
> 
> <Directory /usr/share>
>         AllowOverride None
>         Require all granted
> </Directory>
> 
> <Directory /var/www/>
>         Options Indexes FollowSymLinks
>         AllowOverride None
>         Require all granted
> </Directory>
> 
> <Directory /var/www/html/crm/>
>         AllowOverride All
> 
>         <Limit GET POST PUT DELETE HEAD OPTIONS PATCH>
>                 Order allow,deny
>                 Allow from all
>         </Limit>
> </Directory>

Is there something I missed?

**Comment by yurikuzn** [comment]
Check users permission (applied via Roles). Access button on user detail view. It's better to ask such questions on our forum http://forum.espocrm.com/.

**Comment by Eragon666** [comment]
Thanks, I posted it on the forum: [http://forum.espocrm.com/forum/installation-and-upgrade-help/26064-403-error-for-api-calls-from-none-admin-users](url)
