### ISSUE TITLE
Error in emails with emojis

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#381]
Original post: [http://forum.espocrm.com/forum/general/25692-error-in-emails-with-emojis](http://forum.espocrm.com/forum/general/25692-error-in-emails-with-emojis)

Hello everyone. How are you?

I have a problem: I can not correctly see the emails when they contain emojis, either in the body or in the subject. Did that happen to anyone else? Or is it just me?

Screenshots: [https://postimg.org/gallery/2zdaggf1e/](https://postimg.org/gallery/2zdaggf1e/)

Thanks!

**Comment by yurikuzn** [comment]
Switching collation in database to utf8mb4 for name and body columns should work out.

**Comment by yurikuzn** [comment]
But may affect on searching performance.

**Comment by PanuWeb** [comment]
Ok, I try it and I'll let you know.

**Comment by donavynelliott** [comment]
@PanuWeb Any update on this? I've been wanting to do the same

**Comment by PanuWeb** [comment]
Hi @donavynelliott 
I regret not posting anything before, but I really had not tried it (it's not a urgent problem).
Now I did tests and I published them in this issue: [#648](https://github.com/espocrm/espocrm/issues/648)
