### ISSUE TITLE
Campaign: Emails Doubled

### ISSUE THREAD

**Issue by lorenzopozzoli** [espocrm/espocrm#391]
When I send massive emails in a campaign after two hours and ten minutes of campaign the remaining emails are sent twice, and after 4 hours and twenty minutes are sent three times.

Is there a way to fix this problem?

**Comment by yurikuzn** [comment]
How much emails are supposed to be sent per hour? Check the parameter Administration > Outbound Emails > Max count of emails sent per hour

**Comment by lorenzopozzoli** [comment]
The "Max count of emails sent per hour " parameter is equal to 25'000.

This problem has occurred in a campaign with 9,874 recipients when the last 1382 received a double email  for a total of 11'256 emails sent.

**Comment by yurikuzn** [comment]
Ok, I will investigate. This problem won't occur if "Max count of emails sent per hour" could be sent withing 1 hour. 25000 is too much -- sending process is slow enough.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/4b24491fe4e4fa584df018c38e8988de9965f554
