### ISSUE TITLE
does textFilterUseContainsForVarchar deprecated

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#396]
[here](https://github.com/espocrm/espocrm/blob/9a918e5d971c0154ea930c3e4adba2349a433b1d/application/Espo/Core/SelectManagers/Base.php#L1325)

I wanted to make `$expression = '%' . $textFilter . '%';` for all text field because it is not applied but found some conditions may need updated.
I also suggest the `strlen($textFilter) >= self::MIN_LENGTH_FOR_CONTENT_SEARCH` to be outside the for loop for performance

**Comment by ayman-alkom** [comment]
I fixed it as the following, and it works, https://github.com/espocrm/espocrm/pull/397

**Comment by yurikuzn** [comment]
It's not deprecated.

**Comment by ayman-alkom** [comment]
how can I use it then?
