### ISSUE TITLE
Sorting by status is not working in cases list

### ISSUE THREAD

**Issue by schillermann** [espocrm/espocrm#401]
I've the espocrm version 4.4.1

**Comment by yurikuzn** [comment]
I can't reproduce. I've tested and it worked.

**Comment by yurikuzn** [comment]
It's sorted by oeder of items of status field.

**Comment by yurikuzn** [comment]
You can change the order in Entity Manager by re-ordering status field options.

**Comment by schillermann** [comment]
You can see my problem here in the screenshot http://fs5.directupload.net/images/170208/gl86xl8y.png

If I click on status again the sort order don't change.

**Comment by yurikuzn** [comment]
Can you make a screenshot of Administration > Entity Manager > Case > Fields > Status > Options.

**Comment by schillermann** [comment]
![espocrm-entity](https://cloud.githubusercontent.com/assets/13864946/22783048/4e240fc8-eeca-11e6-8e06-aaa0c50cd8c8.jpg)

**Comment by yurikuzn** [comment]
What mysql version do you have?

**Comment by schillermann** [comment]
mysql  Ver 15.1 Distrib 10.0.27-MariaDB, for debian-linux-gnu (x86_64)
and ngnix

**Comment by yurikuzn** [comment]
There used such syntax for sorting by enum filds in EspoCRM:
```
 ORDER BY FIELD(column_name, 'Vaule_1', 'Value_2', 'Value_3');
````

**Comment by schillermann** [comment]
I dont no.
How can i figure out that?
You're the expert. :-)

**Comment by yurikuzn** [comment]
Can you please check whether sorting by status doesn't work for leads, meetings, calls either?

**Comment by schillermann** [comment]
The sort function runs in Leads and Tasks, only not in Cases.
== Lead call
https://my-address.com/api/v1/Lead?maxSize=20&offset=0&sortBy=status&asc=true
https://my-address.com/api/v1/Lead?maxSize=20&offset=0&sortBy=status&asc=false

== Case call
https://my-address.com/api/v1/Case?maxSize=20&offset=0&sortBy=status&asc=false&where%5B0%5D%5Btype%5D=bool&where%5B0%5D%5Bvalue%5D%5B%5D=onlyMy&where%5B1%5D%5Btype%5D=primary&where%5B1%5D%5Bvalue%5D=open
https://my-address.com/api/v1/Case?maxSize=20&offset=0&sortBy=status&asc=true&where%5B0%5D%5Btype%5D=bool&where%5B0%5D%5Bvalue%5D%5B%5D=onlyMy&where%5B1%5D%5Btype%5D=primary&where%5B1%5D%5Bvalue%5D=open

**Comment by yurikuzn** [comment]
I don't know what it could be. Did you import cases into crm before?

**Comment by schillermann** [comment]
No i've not imported the data.
The response list from the url is always the same when i click on status:
https://my-address.com/api/v1/Case?maxSize=20&offset=0&sortBy=status&asc=false&where%5B0%5D%5Btype%5D=bool&where%5B0%5D%5Bvalue%5D%5B%5D=onlyMy&where%5B1%5D%5Btype%5D=primary&where%5B1%5D%5Bvalue%5D=open

Is that helpful for you?

**Comment by yurikuzn** [comment]
Still no clue what it could be. Did you make any customizations for Case entity?

**Comment by schillermann** [comment]
Under Administration » Entity Manager » Case » Fields "Is Sorted (alphabetically)" was checked. In the demo version of espocrm "Audited" is checked. I've activate "Audited" and disabled "Is Sorted (alphabetically)" now it's work.
Thanks for your great job.

**Comment by yurikuzn** [comment]
There is an issue with indeed.
