### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by JeroennC** [espocrm/espocrm#402]
Hi, I am trying to run the integration tests with phpunit. All integration tests are failing because of the absence of a file: 'tests/integration/config.php'.

I have attempted to use other config files in this place. This however caused the tests not to be executed but rather phpunit exits silently.

Can anyone help me with the correct config file or perhaps some instructions on running the integration tests? Thanks!

**Comment by yurikuzn** [comment]
Hi,

1. Create separate database intended for tests.
2.  Create tests/integration/config.php with contents:
```
<?php
return [
    'database' => [
        'driver' => 'pdo_mysql',
        'host' => 'localhost',
        'dbname' => 'DATABASE_NAME',
        'charset' => 'utf8mb4',
        'user' => 'USER',
        'password' => 'PASSWORD'
    ]
];
```

**Comment by JeroennC** [comment]
That fixed it! Thank you for the quick response.
