### ISSUE TITLE
format/parse phone numbers

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#406]
into unique international format using libraries like Google libphonenumber ( --> https://github.com/giggsey/libphonenumber-for-php).
This is required when phone is searching for contact on incoming call.
So input '+49 (0711) 1234567' should be saved as '+49 711 1234567'
Optional: additional save in E164 format ('+497111234567') which is not as easy readable but the same given by the incoming call.

**Comment by hi-ko** [comment]
By the way: same library can be used to get 

- the number type (mobile, fixed line)
- TimeZone
- GeoLocation

**Comment by kunalgrover05** [comment]
Also, would it be possible to add phone number validations? I can currently enter any invalid phone number field which makes it hard to rely on the data entered.

**Comment by laxminarayan-uc** [comment]
E.164 format would be great to have. It is much more reliable when looking up programmatically.

**Comment by laxminarayan-uc** [comment]
BTW, people still looking for this can use the "numeric" field that contains only the digits from the phone number.

**Comment by hi-ko** [comment]
only partial. people enter phone numbers sometimes with international prefix - sometimes without. Same for city prefix. If you want to use these numbers for matching e.g. incoming calls or to at least _relate_ to an entity with the call records from a phone system you can't rely on numbers if they are not always in E164 format.

**Comment by laxminarayan-uc** [comment]
Yeah, I missed mentioning my technique is not a clean solution.

**Comment by yurikuzn** [comment]
Mostly resolved by https://github.com/espocrm/espocrm/issues/2896

**Comment by hi-ko** [comment]
whoow, great!
Thanks @yurikuzn
