### ISSUE TITLE
HTML entities in email subject

### ISSUE THREAD

**Issue by uok** [espocrm/espocrm#407]
Hello,

If a task name contains an unicode character the notification email subject is sent with HTML entities, e.g.
`ö` (German umlaut) becomes `&ouml;` 
`'` (apostrophe) is sent as `&#039;` 
In the body everything is displayed correctly. 

All databases are set to utf8 and the characters are stored correctly.
A possible cause seems to be the htmlizer class which is also run on the email subject.

**Comment by yurikuzn** [comment]
Hi,

I can't reproduce. In original contents `ö` is represented as `=C3=B6?=`.

**Comment by yurikuzn** [comment]
Problem was with some templates. But assignment template was correct.

https://github.com/espocrm/espocrm/commit/c68f3eb44d5527b1bb457b282dca543082c35990
