### ISSUE TITLE
Email not parsing variables

### ISSUE THREAD

**Issue by bosonno** [espocrm/espocrm#41]
When composing a new email from a template without focusing or changing the body textarea field the variables inside curly braces don't get parsed.

**Comment by bosonno** [comment]
It seems the account should be selected before selecting a template for the variables to get parsed.

**Comment by yurikuzn** [comment]
Can you describe with more details what you do? I just tried:
1. Compose Email
2. Select Account in Parent field
3. Select Template with {Account.name} 
It worked out fine.

**Comment by bosonno** [comment]
To reproduce:
1. Compose Email
3. Select Template with {Account.name} 
2. Select Account in Parent field

**Comment by yurikuzn** [comment]
Got it. It is designed that way so you need to have parent selected before. Maybe it's reasonable to make it to work how you described you need. I will think.

**Comment by bosonno** [comment]
Simple solution could be to disable template selection when account field is empty

**Comment by alasdaircr** [comment]
Please don't do that.

Just have all the template vars refresh when a relationship is changed (e.g. changing the selected account).

It's not an expensive process, and solves this sort of user misunderstanding.
