### ISSUE TITLE
Import on multicore system

### ISSUE THREAD

**Issue by de1eted** [espocrm/espocrm#410]
When VM use multicore CPU, import by crone start many times. As result we have 4 duplicated records on 4 core VM.

**Comment by yurikuzn** [comment]
Maybe your cron.php is executing more frequently than 1 time per minute. It's not supported at this moment.

**Comment by tmachyshyn** [comment]
Are you sure that you set only one cron line in your crontab?

**Comment by yurikuzn** [comment]
How much time import took? minutes or hours?

**Comment by de1eted** [comment]
15 or 30 min (not shure).
