### ISSUE TITLE
Import/export multi-enum fields

### ISSUE THREAD

**Issue by de1eted** [espocrm/espocrm#411]
Import multi-enum fields work only on Telephone field. Export not work on any multi-enum fields.

**Comment by abi2** [comment]
Any updates on this?

Thanks

**Comment by yurikuzn** [comment]
* Multi-enum export/import is supported. 
* Export of multiple phone numbers/email addresses is not supported.
* Import of multiple email addresses is not supported.
* Import of multiple phones is supported, w/ phoneNumberOffice, phoneNumberHome etc. columns.

**Comment by yurikuzn** [comment]
Import/export of multiple email addresses and phone numbers is planned for future.

**Comment by clk-jkn** [comment]
What is the current Status of this? Importing multiple phone numbers works, but sadly not being able to import multiple phone numbers for a contact is preventing us from switching.
Thanks in advance, and sorry if i hijack this Issue.

**Comment by yurikuzn** [comment]
Import multiple email address will be available in the next version.

**Comment by clk-jkn** [comment]
That is great to hear, thanks a lot!

**Comment by xzk394622889** [comment]
> Import multiple email addresses will be available in the next version.

Export multiple email addresses is unavailable. （Just only export a primary Email.）

**Comment by mfliorko-insoftex** [comment]
I'm interested to export/import contacts with multiple email addresses.
Actually, I want to be able to add new email addresses to an existing contact identified by profile URL.

Example:

A contact data in EspoCRM before import:
Firstname, Lastname, ProfileURL1, name1@domain1.com

I import CSV with data:
Firstname, Lastname, ProfileURL1, name2@domain2.com

Contact data after the import:
Firstname, Lastname, ProfileURL1, name1@domain1.com; name2@domain2.com

Is it possible to do it in the current EspoCRM version?

**Comment by rabiibrahimi** [comment]
@mfliorko-insoftex 
Yes it is possible, just you need to map each email to a proper email e,g email - john@gmail.com email1 - jenny@gmail.com
see attache
![Uploading Screenshot 2023-11-23 at 21.25.50.png…]()
d screenshot.

**Comment by mfliorko-insoftex** [comment]
Thank you for the hint, @rabiibrahimi. It's good to know.

How can it be applied in my example from my previous post?
Before import a contact may already contain some email addresses (assuming they are stored in "Email", "Email 2", etc.). Or the contact can have no emails yet. Or it can contain two email addresses (in "Email" and "Email 2").
I don't know how many email addresses are already stored in the contact.

When I import the same contact, the new data can contain new email addresses of the same contact. I want all email addresses to me merged into one list.

Case 2:
Before import: Firstname1, Lastname1, <<no email>>
Import data: Firstname1, Lastname1, name1@gmail.com
After import: Firstname1, Lastname1, name1@gmail.com

Case 2:
Before import: Firstname1, Lastname1, name1@gmail.com
Import data: Firstname1, Lastname1, name1@company1.com
After import: Firstname1, Lastname1, name1@gmail.com, name1@company1.com

Case 3:
Before import: Firstname1, Lastname1, name1@gmail.com, name1@company1.com
Import data: Firstname1, Lastname1, name2@company2.com
After import: Firstname1, Lastname1, name1@gmail.com, name1@company1.com, name2@company2.com

Case 4:
Before import: Firstname1, Lastname1, name1@gmail.com, name1@company1.com, name2@company2.com
Import data: Firstname1, Lastname1, name1@gmail.com
After import: Firstname1, Lastname1, name1@gmail.com, name1@company1.com, name2@company2.com

**Comment by rabiibrahimi** [comment]
best way is to export existing contacts sort them out using excel vlookup and then upload new file to update all existing contacts.
