### ISSUE TITLE
Searching Accounts and Contacts: no results

### ISSUE THREAD

**Issue by bosonno** [espocrm/espocrm#42]
Searching gives no results when query does not match beginning of string. It is not possible to search within a string.

**Comment by yurikuzn** [comment]
You can add % to the beginning of your search phrase. Or fix in \Espo\Core\SelectManagers\Base.

**Comment by bosonno** [comment]
Expected result is searching in every part of the string. Should be default behavior. There are strings which could contain %. Example: 100% Fresh Company. Searching for 100% gives unwanted results.
