### ISSUE TITLE
Last Viewed & Action History

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#423]

**Comment by emillod** [comment]
This is function only for Advandced pack? Or free users can also use this?

**Comment by yurikuzn** [comment]
This repository is not for advanced pack. So it's out-of-the-box feature.

**Comment by emillod** [comment]
So how can i activate this in my instance?

**Comment by yurikuzn** [comment]
It's available inside main menu in the top-right corner .

**Comment by emillod** [comment]
Thanks a lot! I have version 4.5.1 hah 😄
