### ISSUE TITLE
Dynamic logic logical operators bug

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#433]
Adding making field visible check:
someLinkField equal to someValueId
OR
someLinkFieldequal to someOtherValueId2
..etc

as a result:
1. Does not work when someLinkField is hit to one of the values
2. In FIeld view 'AND' is written instead of 'OR' that specified while editing conditions.

If I leave only one check without OR and condition is hit - it works and field becomes visible.

Espo ver 4.4.1

**Comment by yurikuzn** [comment]
I can't reproduce.

**Comment by yurikuzn** [comment]
Maybe you use incorrect construction like
```
- AND
    |
    OR
         |
         FIELD
         |
         OR
             |
             FIELD
```

instead of

```
- AND
    |
    OR
         |
         FIELD
         |
         FIELD
```

**Comment by rutkas** [comment]
Hello, yes, I was trying to use (cond) OR (cond) like this or similar:
![2017-03-03](https://cloud.githubusercontent.com/assets/14265370/23529923/2f8f3bac-ffa8-11e6-809e-3c5e68f9a651.png)
Now I understood that logical operator sets itself between all elements inside of its group and made it working by setting like this:
![2017-03-03 1](https://cloud.githubusercontent.com/assets/14265370/23530149/355e832a-ffa9-11e6-81c2-930f26c37004.png)

And it is working now.. can be closed now, thanks for the hint! 
The project is really lack of documentation
