### ISSUE TITLE
Lead convert does not set default value of probability field

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#434]
I have posted about this bug on espo forum but did nit get any response, so dublicating it here:

populateDefaults is not done when converting lead to opportunity, and therefore probability field is blank by default while default stage is selected.
need to select ANOTHER stage, then select previous stage back again to fill the probability field. this field is controlled by populateDefaults while creating opportunity directly without lead convertion

**Comment by yurikuzn** [comment]
Fixed here https://github.com/espocrm/espocrm/pull/416
