### ISSUE TITLE
After update from 4.3.1 to 4.4.1 i got ambigous column

### ISSUE THREAD

**Issue by mrpiagg** [espocrm/espocrm#437]
I got this error after update when i try to open Meeting or Call.

Espo.ERROR: API [GET]:/:controller, Params:Array (     [controller] => Meeting ) , InputData:  - SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'date_start' in field list is ambiguous [] []
Espo.ERROR: Display Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'date_start' in field list is ambiguous, Code: 23000 URL: /api/v1/Meeting?maxSize=20&offset=0&sortBy=dateStart&asc=false [] []

**Comment by yurikuzn** [comment]
That mysql version do you have?

**Comment by mrpiagg** [comment]
5.6.28-0ubuntu0.15.04.1

mysql Ver 14.14 Distrib 5.6.28, for debian-linux-gnu (x86_64) using EditLine wrapper

**Comment by mrpiagg** [comment]
Fix: http://forum.espocrm.com/forum/bug-reports/26824-update-4-4-1?_=1488450051141

In application/Espo/Modules/Crm/Resources/metadata/entityDefs/Meeting.json
change
TIMESTAMPDIFF(SECOND, date_start, date_end)
to
TIMESTAMPDIFF(SECOND, meeting.date_start, meeting.date_end)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/1c31a6689fa247a61e004f10082ce91e4150895e
