### ISSUE TITLE
datepicker update and yy -> yyyy auto conversion

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#438]
It's a good idea to update datepicker and also moment.js libs to fresh ones. For example I was lack of a nice feature assumeNearbyYear that converts 2 digit year to 4 digit.

This is good when the date is dd.mm.yyyy format as by default. And when you enter the date manually in edit field of the date you do no need to enter FULL year. For example if I enter 03.03.17 it sets 03.03.1017 date but agree everyone needs 03.03.2017 to be set when typing 03.03.17, so you need always to put extra symbols each time for entering date manually.
the first part to fix this is to update datecpicker to have this feature. assumeNearbyYear - and set it when initializing it. I have loaded fresh bootstrap-datepicker to my espo and it really works.

the second part to fix the year problem is to update field value to make correct date values stored in database. I have done this by customizing date field in my espo system like this:

```
Espo.define('custom:views/fields/date', 'views/fields/date', function (Dep) {

    return Dep.extend({

        parseDate: function (string) {
           var date = this.getDateTime().fromDisplayDate(string);
           if ((date == null) || (date == '')) {
              var fixedDate = date;
           } else {
              var mDate = this.getDateTime().toMomentDate(date);
              if (mDate.year()<1000) {
                 mDate.add(2000,'year');
              }
              var fixedDate = mDate.format(this.getDateTime().internalDateFormat)
           }
           return fixedDate;
        },
...
```

Also I needed to copy entire afterRender function to set the new option 
```
                var options = {
                    format: this.getDateTime().dateFormat.toLowerCase(),
                    weekStart: this.getDateTime().weekStart,
                    autoclose: true,
                    todayHighlight: true,
                    assumeNearbyYear: true,
                };
```
and a small hack for loading fresh datepicker:

```
        afterRender: function () {
           if ( (window.datepicker_loaded != undefined) && (window.datepicker_loaded) ) {
              this.afterRenderCode(); // moved all the afterRende code to seperate func
           } else {
              window.datepicker_loaded = true;
              $.getScript( "../../extra-libs/bootstrap-datepicker.js", function( data, textStatus, jqxhr ) {
                 this.afterRenderCode();
              }.bind(this));
           }
        },
```
The last tweak is not very clear but it is working withot modifying the espo original files/libs

So If you could update the datepicker lib and set year patches to the view (assumeNearbyYear: true,) and parseDate update -  it would be great iprovement/fix for dates.

Moment.js has also new features and can be updated I suppose. Maybe new moment.js can be used in parseDate func to automatically update the year field yy->yyyy for storing more easility that I have done

`YYYY from version 2.10.5 supports 2 digit years, and converts them to a year near 2000 (same as YY`

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/315

**Comment by yurikuzn** [comment]
Done.
