### ISSUE TITLE
Common IMAP aacount

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#439]
It could be useful if I can set that generic IMAP account that will be avaialbale for all users. Just like main single SMTP account can be set for everyone. For example I have a 'support' imap account that is used by all managers. I can not use it in ESPO right now, because imap settings are user specific only my database will be messed and filled with duplictes if I create same imap accounts for each user for one account. When sending emails from espo they are all stored in ESPO mail database and available for all users in "All" group of emails. that is good but not enough. common inbox/sent, etc imap folders would be better for that, to allow also for reading common mailbox/replying in espo, etc.

**Comment by donavynelliott** [comment]
I couldn't agree more. This is the implication I got from the name group
email account but was disappointed.

**Comment by rutkas** [comment]
yea, imap looks very very strange in espo. Just tried to add user imap account linking to one of my mail accounts. Set the sync start date 01.01.2015 to load more mails. Also selected INBOX, Sent monitoring to have sents be uploaded to espo. And I see that only some messages are loaded. my inbox has about 300 mails and only 44 loaded. also Some Sent messages are came to the inbox of espo.
I thought that imap feature here is just like a simple mail client that displays imap folder content and puts sent mails to sent.. but nope.. its a very strange thing...

**Comment by yurikuzn** [comment]
There is group email account. You can setup it so that all emails will be fall into INBOX of users of specified team.

In SENT folder you see all emails that was sent from YOUR email address.

It's all documented. If some messages are not loaded that could because you haven't installed mailparse extension. It's documented.

**Comment by yurikuzn** [comment]
There was also bug in 4.4.1 with group accounts https://github.com/espocrm/espocrm/issues/431
