### ISSUE TITLE
Sorting icon is misused

### ISSUE THREAD

**Issue by bosonno** [espocrm/espocrm#44]
&lt; means small to big
&gt; means big to small

&lt; expects A-Z not Z-A
&lt; expects 1970-01-01 till 2015-04-18 not 2015-04-18 till 1970-01-01

**Comment by yurikuzn** [comment]
You are not right. It was discussed on forum previously.

**Comment by yurikuzn** [comment]
http://forum.espocrm.com/bug-reports/2967-date-sort-shows-caret-in-incorrect-position?routestring=forum/bug-reports/2967-date-sort-shows-caret-in-incorrect-position
