### ISSUE TITLE
PHP path in Windows installation incorrect

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#440]
After installing EspoCRM-4.5.0, the install wizard said to create a scheduled task to run this command:

```C:\php\php.exe -f C:\Repositories\EspoCRM-4.5.0\cron.php```

However, that's not the path to php on my system. The correct path is C:\Xampp\php\php.exe. Is that instruction hard-coded or did it actually think the path it presented was correct?

**Comment by grzegorzgie** [comment]
Man, 
Use app dir to send command...
C:\WebServ\php\php.exe -f "C:\WebServ\httpd\crm\cron.php"

U have XAMPP server: 
C:\Xampp\php\php.exe - > C:\Xampp\php\php.exe -f "C:\WebServ\httpd\crm\cron.php"

Save it as bat and run xd

**Comment by bandtank** [comment]
I'm not asking how to do it. The path provided by the installation wizard is wrong, which seems like a bug.

**Comment by yurikuzn** [comment]
That path is returned by php.

**Comment by bandtank** [comment]
There is no php installation at the location it specified:

![image](https://cloud.githubusercontent.com/assets/1170415/23555236/5b4d23c0-ffe5-11e6-817b-d487dc69e889.png)

From phpinfo:

![image](https://cloud.githubusercontent.com/assets/1170415/23555537/8e3ec2f6-ffe6-11e6-88be-f1913912afae.png)

I can't find any other references to php on my machine. How does the installer determine the path?

**Comment by yurikuzn** [comment]
CLI and webserver's php can be separated. And webserver doesn't know anything about CLI.
https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/ScheduledJob.php#L159

**Comment by bandtank** [comment]
There is no other php on my system. I just showed you that with the ls command in my last post. It's impossible for that path to have resolved to a php binary.

**Comment by tmachyshyn** [comment]
The path is set to the prefix used in configure (Linux equivalent: ./configure --prefix <path>). The default path on windows is C:\php. You cannot change it without recompiling PHP.
Create a test script:

<?php
echo PHP_BINDIR;

**Comment by tmachyshyn** [comment]
We will try to fix this issue for Windows.

**Comment by tmachyshyn** [comment]
Due to a bug in PHP ( https://bugs.php.net/bug.php?id=61044&edit=1 ) PHP_BINDIR does not correctly point to the PHP executable under Windows, particularly when PHP is installed as part of XAMPP etc.
PHP_BINARY also does not work correctly under Windows (points to Apache httpd).

**Comment by bandtank** [comment]
I found two answers on stackoverflow that help with this issue.

[Answer 1](http://stackoverflow.com/a/3889630/1030576) - This function worked for me in Windows and Linux:

![image](https://cloud.githubusercontent.com/assets/1170415/23558956/cc368448-fff2-11e6-8b89-00d933a1fcc2.png)

[Answer 2](http://stackoverflow.com/a/24267710/1030576) - Use the [PhpExecutableFinder](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/PhpExecutableFinder.php) class.

**Comment by bandtank** [comment]
This is what I see when I install using the newest commit (9b2324755b70d00f7b0f1598cee9b065f51dfbea):
`C:\xampp\apache\bin\httpd.exe -f C:\Repositories\psecrm\cron.php`

Is that what you expect to see?

**Comment by bandtank** [comment]
This is fixed as far as I can tell.
