### ISSUE TITLE
Only one Account shown in List view for Contacts

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#445]
I assigned two Accounts (Clients in my app) to a Contact:
![image](https://cloud.githubusercontent.com/assets/1170415/23618213/dd538fd0-024c-11e7-87ab-9d1d1984f37d.png)

However, only the first one is shown in the Contact list view:
![image](https://cloud.githubusercontent.com/assets/1170415/23618225/ed6fc910-024c-11e7-8585-391efc9e0570.png)

Is this a setting somewhere or is it a bug?

**Comment by yurikuzn** [comment]
It's how it was designed. You can customize so that it will load accounts LinkMultiple field 'account' for list view. It was covered on forum. You can use search.

**Comment by yurikuzn** [comment]
http://forum.espocrm.com/forum/developer-help/21530-upddate-a-listview-including-a-linkmulti-field

**Comment by bandtank** [comment]
It should be obvious by now that I'm using the search. I can't find every single issue especially when none of it is documented. You could save all of your potential customers a lot of time by actually writing some of this in the documentation or at least explaining how to use things in the release. For someone who is new, your method of communicating is extremely lacking. I spent several hours looking through the forums for all of the issues I've posted and didn't find the link you just posted. Try not being rude to people who pay you.

**Comment by yurikuzn** [comment]
Sorry. I didn't meant to be rude when suggested using search. I often use it.

But I found your posts on the forum offending. I have very littte of time during the day for forum. Rude posts with claims to developers can flip me over. It's easier to ignore and proceed working.

**Comment by bandtank** [comment]
I've been posting with very little opinion other than the huge security hole in the email functionality thread, which is actually still a fact instead of an opinion. Not disclosing that every user can see every email is extremely bad. If you want to ignore your customers, that's your choice, but interpreting someone pointing out a flaw in your design as rude only hurts you, not me.

I write software for a living and regardless of how people post, I always treat the feedback as positive because they're taking time out of their day to improve my product. I've already posted tutorials about how to fix things that you should have explained in the documentation. Instead of getting pissed off, you should really be thanking me, but whatever. I'll just buy other software and move along since you can't be professional about your own product and support.
