### ISSUE TITLE
Row size too large exception SQLSTATE[42000]

### ISSUE THREAD

**Issue by tannakartikey** [espocrm/espocrm#447]
I am using [Real Estate Extenstion](https://www.espocrm.com/extensions/real-estate/) 

After adding approx 150 fields of different types I get the following error. I need to add around 80 more fields. Is there any way to overcome the limitation?

`Server side error 500: Error while rebuilding database. See log file for details.`

```Espo.ALERT: Rebuild database fault: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs' in /var/www/html/kavasa-crm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:699```

I could add text field but after some time that also stopped.

Here is my [RealEstateProperty.json.txt](https://github.com/espocrm/espocrm/files/823626/RealEstateProperty.json.txt) file.
(Extension is converted to txt so that I can attach it on Github)

**Comment by tannakartikey** [comment]
Is maxLength parameter supposed to set varchar size in the database? If not, is there any way to limit the length?

I changed many fields' maxLength parameter to a smaller length in file `custom/Espo/custom/Reources/metadata/entityDefs/RealEstateProperty.json`

After rebuilding there was no change in the database. It is taking default value mentioned in the code, which is 255.

**Comment by yurikuzn** [comment]
maxLength will affect on length only if field is being created or value increased. If decreased then we do nothing to avoid losing any data in db. You need to set maxLength and set desiered column length in database manually.

**Comment by yurikuzn** [comment]
I've never encountered with such situation before. You can try do split your big entity to separate entities. But this can be difficult if you really need data be edited on the single form. 
I'd try to increase memory allocation for your db.

**Comment by tannakartikey** [comment]
It's actually the maximum MySQL can handle.
https://dev.mysql.com/doc/refman/5.7/en/column-count-limit.html

I might try removing the table and firing rebuild script than doing it
manually.
It should create tables again from entitiyDefs with smaller varchar value,
right?

**Comment by yurikuzn** [comment]
Yes it should.

**Comment by tannakartikey** [comment]
I performed the following steps to solve it:
1. Changed maxLength to smaller values wherever possible in the file: `custom/Espo/custom/Reources/metadata/entityDefs/RealEstateProperty.json`
2. Deleted the table `real_estate_property`
3. Run `php rebuild.php`

This created the table again with smaller varchar values and resolved the problem for now.
