### ISSUE TITLE
issue with Decimal Data Type.

### ISSUE THREAD

**Issue by atapatel** [espocrm/espocrm#45]
Hello @yurikuzn 
When we create a field with decimal data type and we add those field in listing layout. it wan't display data grid. but when i checked my Firebug > Network tab it shows me an error that 
> http://espocrm-local.com/client/src/views/fields/decimal.js?_=1429527135864 

does not exist

**Comment by yurikuzn** [comment]
Hi

How you added decimal field? There is no such field type in EspoCRM.

**Comment by atapatel** [comment]
i have created this field while creating custom extension.

**Comment by yurikuzn** [comment]
It could be syntax error in your descimal.js file.

**Comment by atapatel** [comment]
descimal.js file is not there in src/views/fields/ folder

**Comment by yurikuzn** [comment]
I don't understand. We have no decimal field in EspoCRM. Is it your custom type of field?

**Comment by atapatel** [comment]
Yes. the mysql one support it and your Doctrine DBAL library also support decimal field.

**Comment by yurikuzn** [comment]
You can use existing int field.

**Comment by atapatel** [comment]
can i used float field instead of decimal field?

**Comment by yurikuzn** [comment]
I meant float. Right. You can.

**Comment by yurikuzn** [comment]
You can use Entity Manager in Admin panel to create your entities or customize existing ones.
