### ISSUE TITLE
Preferences: Storing in database instead of filesystem

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#451]

**Comment by mr-jingles** [comment]
Hi yurikuzn,
I come from a magento development background and I love the possibility how you can store  preferences/configurations into files in parallel to the database. To be more exact there is a hierarchy between configuration files and database. The database comes first and the xml files will be read second. As far as I am concerned the file approach suits much better into a continuous integration process with deployment to different servers! ;) 
Best Regards

**Comment by bandtank** [comment]
When I try a fresh install with this commit included in the codebase, the install hangs at the database creation step. The only thing I see in the log is the following statement:

```
2017-04-07 04:12:54] Espo.WARNING: E_WARNING: Invalid argument supplied for foreach() 
{
    "code":2,
    "message":"Invalid argument supplied for foreach()",
    "file":"C:\\Repositories\\psecrm\\application\\Espo\\Core\\Utils\\Database\\Schema\\Converter.php",
    "line":431,
    "context":{
        "entityList":["Preferences"],
        "ormMeta":{
            "ActionHistoryRecord":{
```

**Comment by yurikuzn** [comment]
It's not finished yet.
