### ISSUE TITLE
Enter button event when editing filters

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#452]
It would be much better if 'Enter' event work when adding/editing some additional in whole search panel without need to click the "search" button. Users always try to press enter to apply after typing additonal filter text and nothing happens.

Unfortunately there's no way to customize search panel via "custom" folders without patching core files.

Something like the following can be added to the afterRender (ONCE) search panel to fix this issue:

```
$('div.search-container').keypress(function(e){
    if (e.which == 13){
        $('button.search').click();
    }
});
```

**Comment by donavynelliott** [comment]
Ideally the enter button should also update any fields currently being edited.

**Comment by bandtank** [comment]
+1

Does the code snippet you posted work? If so, I'd like to add it to my code base. Which file should I edit?

**Comment by rutkas** [comment]
If you are interested, here is my full solution:

1. Creating the custom view with function that adds this event, of course in htdocs/client/custom/src/views/after-render-everywhere.js:

```
Espo.define('custom:views/after-render-everywhere', 'views/fields/base', function (Dep) {

    return Dep.extend({
        afterRenderEverywhere: function () {
//           console.log("everywhere");
           if ( (window.search_panel_patched != undefined) && (window.search_panel_patched) ) {
//              console.log("already patched");
           } else {
              if ( $('div.search-container').find('button.search') ) {
                 window.search_panel_patched = true;
                 $(document).keypress(function(e){
                    if (e.which == 13) {
                       var $searchContEl = $('div.search-container');
                       if ( ($searchContEl.length) && ($searchContEl.find(':focus').length > 0 ) ) {
                          $searchContEl.find('button.search').click();
                       }
                    }
                 });
              }
           }
        },
    });

});

```

2. Then we need to find where to call this magic function, I did not find any "clear solution", the one way is to patch the main espo code (outside customs), but I had another idea. You can customise field type views. For example I have added this function call in varchar and date custom field types, these fields are using everywhere in objects, thats why I called the view with our function "after-render-everywhere"

This code for varchar:

```
Espo.define('custom:views/fields/varchar',['views/fields/varchar','custom:views/after-render-everywhere'], function (Dep,AfterRenEverywhere) {

    return Dep.extend({

        afterRender: function () {
            Dep.prototype.afterRender.call(this);
            AfterRenEverywhere.prototype.afterRenderEverywhere.call(this);
        },

    });

});

```

Now our function is called when renderiing all objects that have varchcar fields in list. Almost all, I have also added date in such a way, cause I have some simple objects  without varchar in list but with createdAt. Event added, only custom folders are patched. Of course it is much easier to patch main Espo for that but such changes can be lost after Espo update, so I prefer to use only "custom"

**Comment by bandtank** [comment]
Love it. Thanks.

**Comment by rutkas** [comment]
Yes, correct, sorry, forget to mention, custom view for field should be declared there:
htdocs/custom/Espo/Custom/Resources/metadata/fields/varchar.json:
```
{
   "view": "custom:views/fields/varchar"
}
```

**Comment by alasdaircr** [comment]
I worked this up a while ago, is in a PR called fast filtering.

Search applies as any filter is modified (including hitting return in a text field).

See #294

**Comment by yurikuzn** [comment]
Ctrl+Enter supported now.
