### ISSUE TITLE
Entity Manager -> Link Field showing only amountCurrency, not the amountValue

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#463]
Entity Manager -> Link Field showing only amountCurrency, not the amountValue as option.

I'm creating a entity field Linked with another Entity, but, from currency fields, it is only giving the option to link the amountCurrency, no option of amountValue. 

Just saw that this problem is not with Link fields, the currency value is not allowed (not showing as an option) to dynamic Logic too. Even the own entity fields. Currency is not being showed as an option on the Dynamic Logic Formula..

**Comment by yurikuzn** [comment]
> Entity Manager -> Link Field showing only amountCurrency, not the amountValue as option.
I don't understand.

**Comment by rodrigoscoelho** [comment]
Look at the attached image, it only show the AMOUNT CURRENCY, not the Amount value as option. Foreign Field.
![image](https://cloud.githubusercontent.com/assets/6912410/24049286/4e935494-0b0a-11e7-98b1-0da9ad7d6ab7.png)

**Comment by yurikuzn** [comment]
Only Varchar and Enum are supported for Foreign fields.

**Comment by rodrigoscoelho** [comment]
Any possibility to improve this?

thanks for the answer Yuri...

**Comment by yurikuzn** [comment]
You can do it manually in custom entityDefs. Choose any field then edit metadata file and specify another field. Not sure, maybe it will work out.

**Comment by rodrigoscoelho** [comment]
Thanks Yuri, I will try. But, if it work, why not allow to do it from
inside the program, as already is done for some field types?

Would it be possible?

Thanks

**Comment by yurikuzn** [comment]
There were some technical issues.

**Comment by rodrigoscoelho** [comment]
It worked when made manually, but I would like to know which options we
have more for view.
I'm still using
"view": "views/fields/foreign-varchar",
but the field is not formatted as a currency value. Which more options of
foreign-???? we have?

Thanks.

**Comment by yurikuzn** [comment]
T=Only -varchar and -enum.

**Comment by rodrigoscoelho** [comment]
Did you think in open other possibilities of field type, but only as
READONLY? maybe that way you will spread the options and keep the
compatibility.
