### ISSUE TITLE
EspoCRM is creating files in CACHE folder as an non-existent user

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#464]
EspoCRM is creating files in CACHE folder as an non-existent user, sometimes it is created as the Apache2 user, but sometimes it is creating as a non-existent one. It shows numbers on the username and group permissions.

**Comment by yurikuzn** [comment]
Maybe you have cron run under another user.

**Comment by yurikuzn** [comment]
Also in data/config.php you can specify desirable params:
```
    'defaultPermissions' => [
        'dir' => '0775',
        'file' => '0664',
        'user' => 'USER_NAME',
        'group' => 'GROUP_NAME'
    ],
```

**Comment by rodrigoscoelho** [comment]
Thanks,
It was the default permission. :D

Please close it.  (maybe it would be a good idea to document it)
