### ISSUE TITLE
Possible issues

### ISSUE THREAD

**Issue by fleetcaptain** [espocrm/espocrm#468]
Hello EspoCRM team,
I was testing EspoCRM recently and found what appear to be some potential security issues. How should I report them so they can be evaluated and fixed if verified?
Thanks,
Carl

**Comment by yurikuzn** [comment]
Hi Carl,

You can write here or via our contact form at https://www.espocrm.com/contacts/.

**Comment by fleetcaptain** [comment]
Thanks Yuri, I went to the site and submitted the contact form.

**Comment by alasdaircr** [comment]
If there are issues could you perhaps push a security release before the next planned upgrade?

**Comment by asusk323** [comment]
test

**Comment by yurikuzn** [comment]
It's already released in 4.5.1. See milestone for this issue.
