### ISSUE TITLE
tab order on login page is wrong

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#471]
I can't do a comparison from the EspoCRM repository to my repository to create a pull request, so I'll post the code here. Basically, the tab order is wrong. The tab should move from the username input field to the password input field and then to the login button, but it goes to the forgot password link instead. It's obvious why if you look at the template in client/res/templates/login.tpl. Either reverse the order of the elements or add a tabindex to each element:
```
<div class="form-group">
  <label ...
  <input ... tabindex="1">
 </div>
<div class="form-group">
  <label ...
  <input ... tabindex="2">
</div>
<div>
  <a ... tabindex="4">...</a>
  <button ... tabindex="3">...</button>
</div>
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/a7982acc8f1651aa85039ab31f0e4d2fe0577cf3
