### ISSUE TITLE
Field of type Array created with empty options attribute; blocking addition of free text values from Entity Form

### ISSUE THREAD

**Issue by josh9383** [espocrm/espocrm#472]
I recently upgraded to 4.5.0 and figured out that newly added Array fields which are without default options, are generated with empty options attribute. This blocks addition of user defined values via GUI forms as it assumes there are predefined values present and it only prompts to select an item from the empty list.

In order to proceed, I had to manually remove it from def at : 
custom\Espo\Custom\Resources\metadata\entityDefs

snippet for ref:
        "mixedValues": {
            "type": "array",
            "required": false,
            "noEmptyString": false,
            **"options": [],**
            "audited": false,
            "readOnly": false,
            "tooltip": false,
            "isCustom": true
        },

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/7a2b563cd48847bd35b79bb8caadf9d1e045e2d0
