### ISSUE TITLE
entity list not updating after quick list creation

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#475]
When I create a new row with the quick create list, the new row doesn't appear until a manual page refresh is performed or an unknown amount of time passes. Eventually, the row will show up, but the tab has to be deselected and then selected again.

As an example, I have an entity called Job and, when I make a new row with the 'Create Job' button in the Jobs tab, everything works fine. However, when I create a new row with the quick list button, the list of Jobs does not update unless I refresh the page or wait quite a while. See the following [video](https://youtu.be/8-POtxTRIpE).

I have tried with and without a cache; it happens in either case. I deleted my database and reinstalled the app in a new directory to make sure there weren't any bad files from development causing problems.

In case it matters, I use a hook to change fields in the new row using the beforeSave and afterSave methods. Here are the hooks if you want to look at them: [hooks.zip](https://github.com/espocrm/espocrm/files/886164/hooks.zip)

**Comment by alasdaircr** [comment]
You should always call ``parent::beforeSave($entity)`` in a ``beforeSave`` hook. I usually call at the end.

**Comment by alasdaircr** [comment]
Not sure about ``afterSave``

**Comment by bandtank** [comment]
When I do that, I get a bad response error. I tried putting it before and after my code in both hooks (beforeSave and afterSave). It doesn't work in any configuration.

This happens with all entities. If it was only the entities with a custom hook, I'd be more inclined to think something I did caused it, but that's not the case.

**Comment by alasdaircr** [comment]
Hi lets not talk about the hooks then in this issue. You should also have a untouched copy of espo where you check that your own code isn't causing a bug to appear.

When I tested this, creating an entity using Quick Create also doesn't refresh the list view. Presumably it's an easy fix.

**Comment by bandtank** [comment]
I only brought up the hooks to make sure everyone knew they were modified. I agree they don't seem to be an issue.

I tested this with a fresh checkout of 4.5.0 and the same thing happens just like it did for you.

**Comment by bandtank** [comment]
@alasdaircr could you please post some code where you call `parent::before<...>` in a hook? Every time I try it, I get a bad server response error in the browser. I've tried it with beforeSave, afterSave, beforeRelate, and afterRelate.

**Comment by alasdaircr** [comment]
Not here no. this is a bug report about a core bug.

**Comment by hdijkema** [comment]
I've got a similar situation. When I update different record using record\update, the hooks get nicely called (beforeSave, afterSave, etc.); however, the records are not updated in the view. And when I try to call parent::beforeSave(), it results in an error:

```
    public function beforeSave(Entity $entity, array $options = array())
    {
        $options['hook'] = 'beforeSave';
        $this->executeFormula($entity, $options);
        parent::beforeSave($entity, $options);
    }
```

```
2020-05-03 14:15:01] Espo.ERROR: Uncaught Exception Error: "Call to undefined method Espo\Core\Hooks\Base::beforeSave()" at /data/www/crm/application/Espo/Hooks/Common/Formula.php line 120 {"exception":"[object] (Error(code: 0): Call to undefined method Espo\\Core\\Hooks\\Base::beforeSave() at /data/www/crm/application/Espo/Hooks/Common/Formula.php:120)"} []
```

**Comment by beppe9000** [comment]
that is because some customization surfaces are not real oop inheritance: often the original class does not actually have the method
