### ISSUE TITLE
parent entity modal selection issue

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#476]
When I pick a parent entity from a modal during the creation of a child entity, the modal won't go away immediately after the page is loaded. New child entity creation after the first attempt works as expected. Does this have something to do with the cache?

Here's a [video](https://youtu.be/BHbEFBpb79w). There are no errors in the console. Clicking cancel on the modal will hide it and everything still works as expected, so I don't know what would be causing this. Any advice would be greatly appreciated.

**Comment by yurikuzn** [comment]
Any javascript errors in browser console ?

**Comment by yurikuzn** [comment]
Do you have dynamic form logic making job field read-only if it's filled in?

**Comment by bandtank** [comment]
Thanks. That was it. I can work around it by making the read-only logic check another field.

**Comment by yurikuzn** [comment]
I will check this. Maybe it's really a bug.

**Comment by bandtank** [comment]
FYI - there are no errors in the console or on the server.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/8059669a21a3d5ded73770a7909e0d1514ba85cb
