### ISSUE TITLE
Add contacts or organisations to a campaign

### ISSUE THREAD

**Issue by bastians** [espocrm/espocrm#48]
It is not possible to add contacts or organisations to a campaign. I can only add leads and opportunies. Is that right? Is that correct?

![bild 007](https://cloud.githubusercontent.com/assets/863722/7410757/3c675cb6-ef32-11e4-9183-f98f3f5a8382.png)

**Comment by yurikuzn** [comment]
Possible. Layout Manager > Campaign > Relatioships.

**Comment by bastians** [comment]
Aaah, thanks :)
