### ISSUE TITLE
Duplication checking while editing the contact

### ISSUE THREAD

**Issue by tannakartikey** [espocrm/espocrm#482]
Hello,

I did duplication check while creating the contact for email and phone number as described by @yurikuzn in (this post)[http://forum.espocrm.com/forum/general/569-duplicate-checking].

It works well while creating the contact but does not work while editing the contact.

Is it a bug or intended behavior? In any case, how to achieve if I want to check it before editing the contact.

Thanks.

**Comment by yurikuzn** [comment]
Hello,

https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/Record.php#L85

Set `protected $checkForDuplicatesInUpdate = true;` in your Service class.

**Comment by tannakartikey** [comment]
@yurikuzn Thanks.
