### ISSUE TITLE
Record List dashlet

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#484]
Ability to specify:
* Entity Type
* Primary Filter
* Bool Filters

**Comment by bandtank** [comment]
I left a comment on the commit, but I thought I'd write it here instead.

I'm not able to specify any filters other than "Followed" and "Only My" for additional filters. The only filter I have in primary filter is "All". It would be extremely useful to be able to select one or more fields from the entity as filters. How can that be setup?

**Comment by yurikuzn** [comment]
You can create filters like "Only My" by coding. You need to sepecify filter implementation in SelectManager class and add filter in metadata > clientDefs. We don't plan to add filters into this dashlet.

**Comment by bandtank** [comment]
Ok, thanks.

**Comment by yurikuzn** [comment]
Also added ability to define layout for dashlet.
