### ISSUE TITLE
Chrome Deprecated / Subresource requests whose URLs contain embedded credentials

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#485]
`VM3747:491 Subresource requests whose URLs contain embedded credentials (e.g. 'https://user:pass@host/') are deprecated, and will be blocked in M59, around June 2017. See https://www.chromestatus.com/feature/5669008342777856 for more details.`

Deprecated warning in js file:

Espo.define(
    'app',
    ['ui', 'utils', 'acl-manager', 'cache', 'storage', 'models/settings', 'language', 'metadata', 'field-manager', 'models/user', 'models/preferences', 'model-factory' ,'collection-factory', 'pre-loader', 'view-helper', 'controllers/base', 'router', 'date-time', 'layout-manager', 'theme-manager']

in function 
initUserData: function (options, callback) {

on line 493:
`                xhr.send('');`

So as they promise it will stop working around this June.

**Comment by yurikuzn** [comment]
If we pass auth token through header instead of URL it will force users to re-enter user/password to be able to access attachments (including inline images). We have serious problem here.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/73b84d720a8832470c6c07c8b2e1a5683f666079

**Comment by rutkas** [comment]
I just updated the new files for test, and reporting that deprecated message is gone, but new errors appeared after patch. The original 4.5.1 ver did not have these errors.
I noticed such errors when refreshing the pages with stat dashlet (flotr) on it:

```
Uncaught The target container doesn't exist
_setEl @ VM22931:27
Graph @ VM22931:27
draw @ VM22931:27
drow @ VM22928:81
(anonymous) @ VM22929:102
VM22931:27 Uncaught The target container doesn't exist
_setEl @ VM22931:27
Graph @ VM22931:27
draw @ VM22931:27
drow @ VM22928:81
(anonymous) @ VM22929:102
```

![image](https://cloud.githubusercontent.com/assets/14265370/24818862/dd487d7c-1bea-11e7-8102-54dbffed3fd8.png)

**Comment by rutkas** [comment]
Sorry, just discovered that this bug also eppears on the 4.5.1 ver, seems not related to this patch.. I will test more

**Comment by yurikuzn** [comment]
I can't reproduce. Can you provide steps need to be done to get the error?

**Comment by rutkas** [comment]
Looks like not only Chrome related. Tried Edge browser, it shows these errors too. How to reproduce:

- Add separte the button (Tab) for dahslets, i have there:
Sales by month dashlet, calendar, tasks, call and feeds
- Refresh the page
- Click on the dashlet tab button several times with opened browser console
After some clicks such error messages appearing

If there's no flotr-based dashlet on the current tab - there are no errors.

**Comment by rutkas** [comment]
I searched web for this error in flotr2, this can happen if: clientWidth pf element is 0 or/and if we try to draw chart on a hidden element. If this error is not on each click, maybe there is a case when sometimes container is not visible yet before drawing the chart ?
People recommend for use 'show' event to draw

**Comment by rutkas** [comment]
More tests.. I decided to try the fix auth patch again and I have also noticed that, when I apply this patch for Chrome deprecated auth by copying fixed Auth.php and app.js to 4.5.1 espo - flotr exceptions that I reported appearing on EVERY update of the page with charts. That's why I noticed it after this patch for the first time.. And on original 4.5.1 (and 4.5.0 too) these flotr errors are appearing sometimes, not on each refresh as I mentioned before.
