### ISSUE TITLE
How to create field like in TASKS

### ISSUE THREAD

**Issue by emillod** [espocrm/espocrm#486]
Hello.
I want to create new module, but i can't create field to choose records from many modules.
For example in Tasks i have field where i can choose Account, contact, lead, case and etc, but i don't know how to create that one.

**Comment by donavynelliott** [comment]
if you go to yourinstallurl.net/#Admin/entityManager and click on Create Entity at the top I think that is what you're looking for.

**Comment by emillod** [comment]
No no no, i already done this, i have my own Entity, but now i have problem with create this field http://i.imgur.com/UNHN9af.png

**Comment by donavynelliott** [comment]
You need to create a relationship under Entity Manager.
![image](https://cloud.githubusercontent.com/assets/16009956/24806176/d910b95e-1b68-11e7-89b6-353b9da5e132.png)

**Comment by emillod** [comment]
Hmm can you tell what kind of relationship? Because i already try, but i cant create this field... Hmm maybe i'll try again..

**Comment by bandtank** [comment]
You can't create a parent/child relationship in the Relationships area. You have to edit the code manually.

Add the following to `custom/Espo/Custom/Resources/metadata/entityDefs/<entity>.json`:
```
"<fieldname>": {
    "type": "linkParent",
    "entityList": [
        "Account",
        "Contact",
        "..."
    ],
    "notStorable": true,
    "required": true,
    "audited": false,
    "readOnly": false,
    "tooltip": false
},
```

**Comment by emillod** [comment]
@bandtank 
Thanks for your comment. Are you sure, this path is correct? 
> custom/Espo/Custom/Resources/metadata/entityDefs/<entity>.json:

Because in my FTP i have just: `custom/Espo/Custom/`

**Comment by bandtank** [comment]
You have to create the path if it doesn't exist already. The custom directory is intended to redefine custom entities, relationships, definitions, etc. If nothing exists in `custom`, the files in `application` will be used without modification.

**Comment by emillod** [comment]
> custom/Espo/Custom/Resources/metadata/**entityDefs**/.json:

as ``entityDefs`` and ``<entity>`` you want me to write my Entity name?

**Comment by bandtank** [comment]
You only replace <entity>. entityDefs is the name of the folder and that has to stay the same.

**Comment by emillod** [comment]
OK, i already added but nothing happened..
![parent](https://cloud.githubusercontent.com/assets/17282191/24806966/cc1ffd60-1bb6-11e7-8002-cca007fdaf13.PNG)

**Comment by bandtank** [comment]
- Add a new field:
![image](https://cloud.githubusercontent.com/assets/1170415/24807097/263154f4-1b74-11e7-800b-e4e73266fcf0.png)

- `Administration -> Clear Cache`
- `Entity Manager -> <entity> -> Fields`
-`testfield123` should now be visible. If not, try a hard refresh (Ctrl+F5)

**Comment by emillod** [comment]
In this file i have another fields, and when i paste this code:
``        "parentpaczka": {
            "type": "linkParent",
            "entityList": [
                "Account",
                "Contact",
            ],
            "notStorable": true,
            "required": true,
            "audited": false,
            "readOnly": false,
            "tooltip": false
        },``
clear cache, and open fileds menager in browser, all fields hide. 
I don't know way. In this file there are two sections ``fields`` and ``Links`` in which section i should paste this codE?

**Comment by bandtank** [comment]
You want to put it in the `fields` section. Sorry, I forgot to mention that. If you want to zip up your project and send it to me, I can fix it for you and send it back.

**Comment by emillod** [comment]
Is there any chance to fix this without sending project? I have a lot of confidential data in this script..

**Comment by bandtank** [comment]
I'm not sure what else to tell you at this point. Can you remove the confidential stuff first?

**Comment by emillod** [comment]
Hmm this is a lot of work 👎 
Is there any chance that i'll send you just *.json file?

**Comment by bandtank** [comment]
Yeah, we can start with that.

**Comment by emillod** [comment]
[file.zip](https://github.com/espocrm/espocrm/files/906093/file.zip)

**Comment by emillod** [comment]
Password: FD2Kj57VC26x

**Comment by bandtank** [comment]
You have a syntax error, which is what is causing the fields to disappear in the entity manager. Remove the extra comma.

![image](https://cloud.githubusercontent.com/assets/1170415/24808143/f5812498-1b77-11e7-9263-7344f619eab1.png)

**Comment by emillod** [comment]
shiiiiiit haha :D 
G! Thanks 😃

**Comment by emillod** [comment]
I have one more question, is there any way to create field with radio box or checkbox?

**Comment by bandtank** [comment]
A field of type `boolean` will give you a checkbox. Unfortunately, I don't think there's a way to make a radio button. If there is, I haven't seen it yet.

**Comment by emillod** [comment]
I need to create this field in code?

**Comment by bandtank** [comment]
![image](https://cloud.githubusercontent.com/assets/1170415/24808410/d1a2cd3c-1b78-11e7-8f4e-b553a3097517.png)

**Comment by emillod** [comment]
Ahhh yes, but here i can just check or unchek, right? I can't create many checkbox with many checkboxes and other names?

**Comment by bandtank** [comment]
I don't understand what you're trying to achieve. Can you draw a picture?

**Comment by emillod** [comment]
I mean for example i have Question **Do you havea a smartphone ?** and checkboxes: 1. Yes, 2. No, 3. Android, 4. Apple

**Comment by bandtank** [comment]
I would ask that question with two fields and use logic to hide one of the questions.

![image](https://cloud.githubusercontent.com/assets/1170415/24808894/edf26cb6-1b7a-11e7-865a-08175a49174c.png)

![image](https://cloud.githubusercontent.com/assets/1170415/24808896/f148b654-1b7a-11e7-9699-5b0238cef116.png)

[Here's how it looks](https://youtu.be/86PkCYaAC5o&hd=1).

**Comment by emillod** [comment]
I know those options. How can i find option to create radio box? Or where ?

**Comment by emillod** [comment]
It's not just me, a lot of users espoCRM want this option in espo..

**Comment by bandtank** [comment]
I don't know. Sorry. I'm not one of the developers of this project.

**Comment by emillod** [comment]
OK, thanks 😄

**Comment by emillod** [comment]
How to add items from other entity to History? 
http://i.imgur.com/rV68kWZ.png

**Comment by yurikuzn** [comment]
1. Create Event-type entity in entity manager.
2. Administration >Settings > History Entity List.

**Comment by emillod** [comment]
OK, but i already have entity with many fields in Base Plus

**Comment by emillod** [comment]
Can i change this type to event? And can i still use this entity with old fields without losing any data?

**Comment by yurikuzn** [comment]
You can remove it and create with same field set. Database data is not removed with entity type removal.

**Comment by orbMing** [comment]
> I don't know. Sorry. I'm not one of the developers of this project.

hi sir. sorry for interrupting. i'm basically new into espocrm. do you know if there is any chance for me to create custom button?
