### ISSUE TITLE
Radio box fields

### ISSUE THREAD

**Issue by buzzard10** [espocrm/espocrm#487]
Is there any chance to create new type field?
I mean radio buttons and checkbox fields.

**Comment by bandtank** [comment]
You can make a new field type on your own, but I'm not exactly sure how to do radio buttons. Can't you achieve the same thing with the `enum` type already?

**Comment by bandtank** [comment]
Here's a [thread](http://forum.espocrm.com/forum/general/867-adding-new-field-to-addresses) with some information about modifying existing fields.

Here are the files I changed/added to make a new field type that looks very similar to the base address field:
[0001-extra-PSE-address-fields-added.zip](https://github.com/espocrm/espocrm/files/907609/0001-extra-PSE-address-fields-added.zip)

**Comment by yurikuzn** [comment]
We haven't this field type planned. You can create your custom field based on enum field.

**Comment by yurikuzn** [comment]
Chechbox is available as bool field.

**Comment by dangnh9998** [comment]
hi, i want to change style for radio button and checkbox in espo crm, but background-color not working, any one can help me plz
