### ISSUE TITLE
Change query for child object selection

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#488]
I have a parent-child relationship in a custom entity that needs to only allow certain children to be selected. Everything works correctly except I'm able to select a child that already has a boolean set, which shouldn't be allowed. In the picture, the first arrow is the user clicking the "Revision Of" selection arrow, which loads a list of entities. Several of the entities have a field called "isRevision" that is set to true, which should not be allowed to be selected. I want the list of Projects to be queried with "isRevision=false". How do I accomplish this?

![image](https://cloud.githubusercontent.com/assets/1170415/24811826/f4e93180-1b84-11e7-9545-158a526a7b06.png)

Also, typing in the "Revision Of" box should not allow projects with "IsRevision=true" to populate in the suggestion area:

![image](https://cloud.githubusercontent.com/assets/1170415/24811986/94914e2a-1b85-11e7-8e5e-3747e283a6a9.png)

**Comment by yurikuzn** [comment]
Example:
https://github.com/espocrm/espocrm/blob/master/client/modules/crm/src/views/case/fields/contact.js#L33

You will need this:
```
        getSelectFilters: function () {
                return {
                    'account': {
                        type: 'equals',
                        field: 'isRevision',
                        value: false
                    }
                };
        },
```

But user will be able to reset the filter and select any record.

**Comment by yurikuzn** [comment]
This is only for popup. For autocomplete there is no imlemented hook. You will need to specify proper query here: https://github.com/espocrm/espocrm/blob/master/client/src/views/fields/link.js#L193

**Comment by bandtank** [comment]
Thanks for the help so far. I'm working on implementing the changes, but nothing I've tried has worked in the autocomplete box yet. Should I be putting the query terms in the `where` array? Is there an example of the format for that?

I knew this wouldn't work, but it's the only thing I know to try at the moment:

![image](https://cloud.githubusercontent.com/assets/1170415/24830120/e108bd80-1c3c-11e7-81b8-c6c92eaad667.png)

I found an example of `where` being added to a url in `client/modules/advanced/src/views/report/reports/grid1.js`:

`var exportUrl = '?entryPoint=reportAsCsv&id=' + this.model.id + '&where=' + encodeURIComponent(JSON.stringify(where));`

but I still don't know what to put in `where` or if I should be using `encodeURIComponent` or `JSON.stringify`.

**Comment by yurikuzn** [comment]
I'd create filter in select manager class and make `getSelectPrimaryFilterName` method in view class to return filter name.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/client/src/views/fields/assigned-user.js#L47
https://github.com/espocrm/espocrm/blob/master/application/Espo/SelectManagers/User.php#L56

**Comment by bandtank** [comment]
Thanks. I'm guessing I'm close, but it's not quite working. Here are my changes:

![image](https://cloud.githubusercontent.com/assets/1170415/24830407/c63bccf8-1c42-11e7-859c-fe2d674ac390.png)

The browser console shows this: `Project?sortBy=name&maxCount=7&primaryFilter=revision`

The EspoCRM log does not show the `got here` log statement and the MySQL log doesn't show anything in the `WHERE` statement about `hasRevision` (or `has_revision`, which is the actual field name).

**Comment by bandtank** [comment]
I figured out that the `SelectManager` class I created is not being called. I added log statements in `Base` as well as my new class called `Project`, but only `Base` is being called as seen below:

![image](https://cloud.githubusercontent.com/assets/1170415/24830628/3b789830-1c47-11e7-9b21-2df81329320b.png)

![image](https://cloud.githubusercontent.com/assets/1170415/24830655/9300f372-1c47-11e7-9006-66637bf39061.png)


![image](https://cloud.githubusercontent.com/assets/1170415/24830651/88d76f70-1c47-11e7-8e43-bf3074e82ba4.png)

**Comment by bandtank** [comment]
I'm wondering if I put the file in the wrong place. I'm not sure where it should go in `custom` because there are multiple folders called `SelectManagers` in `application`.

**Comment by yurikuzn** [comment]
It should be placed in custom or in module namespace (if it belongs to module)
`custom/Espo/Custom/SelectManagers/Project.php`

Also needs clearing cache.

**Comment by bandtank** [comment]
Ahhh perfect. That was it. I am going to post a question on the forums in the next week or two about the file structure to see if we can get it documented. Maybe that already exists, but it would help me quite a bit if I understood where to put everything. It would prevent a lot of questions like this I think. I'll write what I know and then ask for help with the rest.

**Comment by bandtank** [comment]
I can't get the custom filter to fire. I'm assuming this is also a path problem, but I can't tell for sure. I tried to create a custom view for one field in the Project entity in two places as follows:

![image](https://cloud.githubusercontent.com/assets/1170415/24892249/58d83bb8-1e38-11e7-8958-d8d771801ceb.png)

Neither function is called, so I don't know what I'm doing wrong. You can see the path to each file in the tree as well as the namespace in each file. I tried to follow what you wrote here as well as [here](https://github.com/espocrm/documentation/blob/master/development/custom-views.md), but I have obviously done something wrong.

I know the function is called in link.js because I added debug statements:

![image](https://cloud.githubusercontent.com/assets/1170415/24892292/a1f5943a-1e38-11e7-865c-d36ed913e525.png)

which produces this:

![image](https://cloud.githubusercontent.com/assets/1170415/24892296/ace803c8-1e38-11e7-9d1a-f60ad0982d13.png)

**Comment by yurikuzn** [comment]
Javascript module name should be in hyphen ('views/.../project-revision-parent').
Custom view for fields you should specify in metadata > entityDefs > Project > fields > projectRevisioParent > view.

https://github.com/espocrm/espocrm/blob/master/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Account.json#L160

**Comment by bandtank** [comment]
Ok, thanks, that worked. For anyone else who finds this, here's what I did:

The override for the filter function returns a string:

![image](https://cloud.githubusercontent.com/assets/1170415/24911085/fc26acde-1e86-11e7-89d2-4923b7c153d0.png)

and here is where it needs to go:

![image](https://cloud.githubusercontent.com/assets/1170415/24911107/178e0508-1e87-11e7-9cf4-01af594cc09e.png)

The `revision` filter is defined in a custom `selectManager` for my `project` entity here:

![image](https://cloud.githubusercontent.com/assets/1170415/24911186/57f08e04-1e87-11e7-805f-d82f1559073b.png)

Note the name of the class method: `filterRevision`. That's the name of the filter returned by the custom view with the word filter appended to the front and a `ucfirst()` on the filter name. I return the field and value I want as my filter and then it works.

I also modified a core file called `search.js` because I don't want my users to be able to reset the filter:

![image](https://cloud.githubusercontent.com/assets/1170415/24911298/b2d605b0-1e87-11e7-9b09-2dfb4e94a375.png)

With that code, the filter will be stuck on `revision` when the user clicks the reset button, which is a business rule for my company to never allow the behavior that would otherwise be possible.

You should see the returned string in the filter box once this is all done:

![image](https://cloud.githubusercontent.com/assets/1170415/24911362/e1dc6174-1e87-11e7-865b-0a76ac21f4a1.png)

**Comment by bandtank** [comment]
This no longer works. Something changed I think, which has caused the behavior to be unexpected. When I click the up arrow to link to a parent project, I am presented with a modal that has the filter correctly set to 'revision' and the results reflect 'hasRevision = false'. However, if I click search or reset, the filter no longer applies to the results even though it is still set to 'revision'.

I did some debugging and here's what I found. In `client/src/views/record/search.js`, I added some console statements:

```
251         selectPreset: function (presetName, forceClearAdvancedFilters) {
252             var keepRevision = (this.primary == 'revision' && this.entityType == 'Project') ? true : false;
253             console.log("primary = " + this.primary);
254             console.log("preset = " + this.presetName);
255             console.log("presetlocal = " + presetName);
256             console.log("entity type = " + this.entityType);
257             console.log("keepRevision = " + keepRevision);
258
259             var wasPreset = !(this.primary == this.presetName);
260
261             this.presetName = presetName;
262
263             var advanced = this.getPresetData();
264             //this.primary = (keepRevision ? 'revision' : this.getPrimaryFilterName());
265             this.primary = this.getPrimaryFilterName();
266
267             console.log("-----");
268             console.log("primaryFilterName = " + this.getPrimaryFilterName());
269             console.log("primary = " + this.primary);
270             console.log("preset = " + this.presetName);
271
272             var isPreset = !(this.primary === this.presetName);
273
274             if (forceClearAdvancedFilters || wasPreset || isPreset || Object.keys(advanced).length) {
275                 console.log("=====");
276                 this.removeFilters();
277                 this.advanced = advanced;
278             }
279
280             console.log("+++++");
281             console.log("primary = " + this.primary);
282             console.log("preset = " + this.presetName);
283             this.updateSearch();
284             this.manageLabels();
285
286             this.createFilters(function () {
287                 this.render();
288             }.bind(this));
289             this.updateCollection();
290         },
```

Here's the result:

```
primary = null
preset = revision
presetlocal = revision
entity type = Project
keepRevision = false
-----
primaryFilterName = null
primary = null
preset = revision
=====
+++++
primary = null
preset = revision
```

I upgraded to 4.8.2 and this started happening, but I don't know which version I was on and I don't have any console statements from that version. I was expecting primary to be set to 'revision' as it was before. If I manually set primary to be 'revision' when presetName is 'revision', it seems to work as expected. However, search still sometimes returns the wrong records and I can't figure out why.

**Comment by yurikuzn** [comment]
Hi,
This is the method with the fix:
```
        loadSearchData: function () {
            var searchData = this.searchManager.get();
            this.textFilter = searchData.textFilter;

            if ('presetName' in searchData) {
                this.presetName = searchData.presetName;
            }

            var primaryIsSet = false;
            if ('primary' in searchData) {
                this.primary = searchData.primary;
                if (!this.presetName) {
                    this.presetName = this.primary;
                }
                primaryIsSet = true;
            }

            if (this.presetName) {
                this.advanced = _.extend(Espo.Utils.clone(this.getPresetData()), searchData.advanced);
                if (!primaryIsSet) {
                    this.primary = this.getPrimaryFilterName();
                }
            } else {
                this.advanced = Espo.Utils.clone(searchData.advanced);
            }
            this.bool = searchData.bool;
        },
``

**Comment by bandtank** [comment]
Thanks.
