### ISSUE TITLE
Charts (FLOTR2) "Uncaught The target container doesn't exist", ".. must be visible"

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#489]
Sometimes exceptions are thrown to browser log when drawing dashlets with flotr charts:

```
Uncaught The target container doesn't exist
Uncaught The target container must be visible
```

**Comment by yurikuzn** [comment]
Couldn't reproduce yet.

**Comment by rutkas** [comment]
Here's example on demo at your server. I do not know why but your server gives such error rarely, maybe it is much faster or maybe I have more data. Anyway, click on "New tab" that I created very fast many times and once you get this error I hope:

![image](https://cloud.githubusercontent.com/assets/14265370/24854431/1f7b061c-1de7-11e7-9786-c5bc8bf44776.png)

Also I had another exception content, only once, still on the same demo at the same place:

![image](https://cloud.githubusercontent.com/assets/14265370/24854620/cae98e92-1de7-11e7-8151-c809d694b62b.png)

**Comment by rutkas** [comment]
FF too:

![image](https://cloud.githubusercontent.com/assets/14265370/24854777/5e7ffe2a-1de8-11e7-9294-fb0444b8da01.png)

**Comment by yurikuzn** [comment]
This might fix the issue, but not sure https://github.com/espocrm/espocrm/commit/08bca7daf772cf5e98a70701085f3df65e0c57f7

**Comment by rutkas** [comment]
Not almost, but I have modified a little to check also if the element is hidden, and now it is fixed:

`
if (!$container.size() || !$container.is(":visible")) return;
`

Please update the patch and include it to the nearest releases

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/a6541f6f21e9a608aa4bbb25cb184dc18be21db3
