### ISSUE TITLE
error on setting filter on two values in Multiple Enum

### ISSUE THREAD

**Issue by mgielda** [espocrm/espocrm#49]
I am testing out EspoCRM and while the features are great, I sometimes run into bugs like the one described below.

I created a multiple enum called 'tag'. I added it to the Accounts list view, then to Filters for Accounts.

All worked fine so far.

Then I tried setting  filter with two values. Things went very wrong, to the point where my Accounts tab does not show at all.

In the browser console, I see:
Error: Option 'multiple' is not allowed for Select2 when attached to a <select> element.
TypeError: this.$advancedFiltersPanel is undefined

This is a serious bug, since even removing "tag" from available filters in the Administration pane did not help, so I am practically unable to see my list of Accounts.

**Comment by yurikuzn** [comment]
Hi 

Thank you. I will look.

For tags you shouldn't use multiple enum field. It's more proper to add new entity and create many-to-many relationship. But need to create linkMultiple field manually to be able to use it in filters.

**Comment by mgielda** [comment]
Ah, thank you for the blazingly fast response. Now I need to fix my Accounts tab anyway :)

I did create a Tag entity with many to many relationship and indeed it works like a charm! Question is, how do I create a linkMultiple for filtering?

**Comment by yurikuzn** [comment]
create field 
"tags": {
   "type": "linkMultiple"
}
custom/Espo/Custom/Resources/metadata/entityDefs/Account.json

**Comment by yurikuzn** [comment]
Don't forget to clear cache after the change.

**Comment by mgielda** [comment]
Thanks! Will test it out tomorrow and let you know if everything works on our side.
