### ISSUE TITLE
Error 403 in Administration section

### ISSUE THREAD

**Issue by emillod** [espocrm/espocrm#490]
Hi all
after i install ESPO in local network, on Centos with CWP 7, i cant change theme.
After i try to change anything in section Preferences, i have error 403 

Any ideas?

**Comment by yurikuzn** [comment]
Hi,

Did you install from git repository?

**Comment by yurikuzn** [comment]
Stable version is avalable here https://www.espocrm.com/download/. Master is not a development branch and is not stable.

**Comment by emillod** [comment]
No, i downloaded this package from website.
Is there any chance, that is problem in permissions?

**Comment by yurikuzn** [comment]
Check data/logs for errors. Maybe permissions.
