### ISSUE TITLE
Ability to define any hook name

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#492]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/82ddd2e5629cb96f32a1b80203d45bf7d4826c0e

**Comment by bandtank** [comment]
Are the old hooks still available? beforeSave, afterSave, etc.?

**Comment by yurikuzn** [comment]
Yes, they are available. Any public method in hook class will be used as a hook. Hook is called by code. If there multiple hooks then they ordered by order property https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Hooks/Base.php#L47.
