### ISSUE TITLE
How to create entity which allows multiple contact selection?

### ISSUE THREAD

**Issue by tannakartikey** [espocrm/espocrm#495]
Hello,

I have created a custom entity named 'Corp. Contacts'. But it is not allowing me to add more than one contact. I want to add more than one contact and mark one of it as primary.

Do I need to make any changes to any file or my configuration in Entity Manager is wrong.

Please find the image below for the reference with the disabled button highlighted in red.

![image](https://cloud.githubusercontent.com/assets/422544/24895033/cdc43d32-1eab-11e7-8b3c-ce21986d27ef.png)

**Comment by yurikuzn** [comment]
Hi,

I don't understand the problem. You can't add more than one phone number? Button should be grayed out once you type the phone number allowing to add more. Do you get any js errors?

**Comment by tannakartikey** [comment]
Oh, yes. Sorry.
The button gets activated only after adding the first number. I was trying to add the number while the field was empty.
