### ISSUE TITLE
MS Edge error when using charts

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#496]
Noticed such console errors while updating pages with charts in Edge browser (I think IE too):

![image](https://cloud.githubusercontent.com/assets/14265370/24905504/e045a2dc-1ebc-11e7-9a70-6ea933c29c9a.png)

On my installation I have pathes to the file in these 404 XHR errors in console logs:
https://mydomain.com/client/gridstack.min.map

It looks like this file is missing

UPD: Errors only in Edge, nothing in IE

**Comment by yurikuzn** [comment]
This error doesn't have an effect on working.

**Comment by rutkas** [comment]
Yes, but it is an error.. that is like a spot in the eyes for such a good code as Espo really is ;)
Maybe this map file can be included to install to prevent such errors?
