### ISSUE TITLE
How to achieve contact type for custom entities?

### ISSUE THREAD

**Issue by tannakartikey** [espocrm/espocrm#497]
Hello,

I want to achieve the functionality as given in Opportunity module by default in the custom entities created by me. What files I have to edit for that can you please suggest?

![image](https://cloud.githubusercontent.com/assets/422544/24908069/533764a0-1edc-11e7-9176-c45389a80aee.png)

So far I followed the steps from the Opportunity entity. 
 - Created fields under Contact for corpAccountRole.
 - Created relationship between Contact and corpAccount (many-to-many)
 - Created relationship between corpAccount and Contact (many-to-many)
 - Rebuild the database
 - Cleared the cache

It has not worked yet.

Thanks.

**Comment by bandtank** [comment]
Where did you put all of the files? It could be a namespace or path issue.

**Comment by bandtank** [comment]
Can you post the modifications you made to each file as well? Ideally, you'd be able to show this from a git log in something like Sourcetree or Github GUI that would make the changed lines easy to see.

**Comment by tannakartikey** [comment]
I had made this through CRM's GUI. Is it unachievable from CRM's GUI? I
will try with files then.

**Comment by bandtank** [comment]
I doubt this can be done in the GUI, but I'm not sure.

**Comment by tannakartikey** [comment]
Do you know the concept how to achieve this? I will try it through files then.

**Comment by bandtank** [comment]
In the entityDef file for your custom entity, you need to have a field in the `fields` section line `contacts` in `Opportunity.json` as well as a custom view most likely:

![image](https://cloud.githubusercontent.com/assets/1170415/24910576/662e566a-1e85-11e7-95c8-429e44c24cfc.png)

In the same file, you need to have a link in the `links` section for the same field that has the `foreign` value updated to match your entity:

![image](https://cloud.githubusercontent.com/assets/1170415/24910620/8655243c-1e85-11e7-94af-fc0ab53a8011.png)

In `Contact.json` you see the role field in the `fields` section as follows:

![image](https://cloud.githubusercontent.com/assets/1170415/24910667/b3856084-1e85-11e7-91a6-6bc4f47816cd.png)

and a link to `Opportunity` in the `links` section as follows:

![image](https://cloud.githubusercontent.com/assets/1170415/24910708/db0d36fe-1e85-11e7-8c66-5df036510d7a.png)

I'm guessing that should be enough. The other things you need to add will populate automatically once you are able to view this relationship in the GUI editor. There are other files that will need things like definitions and translations, but I don't usually do that manually because I don't know where it all goes.

**Comment by tannakartikey** [comment]
I installed a new instance of Espo.

Took reference from your comments and the code.

Replicate Contacts from Opportunity to Case module. Now, in GUI I see that all the options of Opportunity module and Case module are similar. But in view, I am getting some error.

Error:

```
Uncaught TypeError: Cannot read property 'forEach' of null
    at n.getJQSelect (eval at _execute (http://localhost/espo/client/espo.min.js?r=1491210575404:16:26553), <anonymous>:123:26)
    at n.addLinkHtml (eval at _execute (http://localhost/espo/client/espo.min.js?r=1491210575404:16:26553), <anonymous>:150:30)
    at n.addLink (eval at _execute (http://localhost/espo/client/espo.min.js?r=1491210575404:16:26553), <anonymous>:112:22)
    at eval (eval at _execute (http://localhost/espo/client/espo.min.js?r=1491210575404:16:26553), <anonymous>:135:38)
    at Array.forEach (native)
    at n.eval (eval at _execute (http://localhost/espo/client/espo.min.js?r=1491210575404:16:26553), <anonymous>:134:36)
    at n.<anonymous> (http://localhost/espo/client/espo.min.js?r=1491210575404:5:22581)
    at n.<anonymous> (http://localhost/espo/client/espo.min.js?r=1491210575404:4:28262)
    at _ (http://localhost/espo/client/espo.min.js?r=1491210575404:5:23086)
    at m (http://localhost/espo/client/espo.min.js?r=1491210575404:5:22878)
```

Git diff:
```
diff --git a/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Case.json b/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Case.json
index 0f0bb50..e0283b2 100644
--- a/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Case.json
+++ b/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Case.json
@@ -42,13 +42,12 @@
         "lead": {
             "type": "link"
         },
-        "contact": {
-            "type": "link",
-            "view": "crm:views/case/fields/contact"
-        },
         "contacts": {
             "type": "linkMultiple",
-            "view": "crm:views/case/fields/contacts"
+            "view": "crm:views/case/fields/contacts",
+	    "column": {
+		    "role":"caseRole"
+	    }
         },
         "inboundEmail": {
             "type": "link",
@@ -114,16 +113,17 @@
             "entity": "Lead",
             "foreign": "cases"
         },
-        "contact": {
-            "type": "belongsTo",
-            "entity": "Contact",
-            "foreign": "casesPrimary"
-        },
         "contacts": {
             "type": "hasMany",
             "entity": "Contact",
             "foreign": "cases",
-            "layoutRelationshipsDisabled": true
+	    "additionalColumns": {
+                "role": {
+                    "type": "varchar",
+                    "len": 50
+                }
+            }
+
         },
         "meetings": {
             "type": "hasChildren",
diff --git a/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Contact.json b/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Contact.json
index 639e41d..7718e9d 100644
--- a/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Contact.json
+++ b/application/Espo/Modules/Crm/Resources/metadata/entityDefs/Contact.json
@@ -126,6 +126,12 @@
             "disabled": true,
             "options": ["", "Decision Maker", "Evaluator", "Influencer"]
         },
+	"caseRole": {
+            "type": "enum",
+            "notStorable": true,
+            "disabled": true,
+            "options": ["", "Decision Maker", "Evaluator", "Influencer"]
+        },
         "acceptanceStatus": {
             "type": "varchar",
             "notStorable": true,
@@ -235,12 +241,6 @@
             "entity": "Opportunity",
             "foreign": "contacts"
         },
-        "casesPrimary": {
-            "type": "hasMany",
-            "entity": "Case",
-            "foreign": "contact",
-            "layoutRelationshipsDisabled": true
-        },
         "cases": {
             "type": "hasMany",
             "entity": "Case",
diff --git a/client/modules/crm/src/views/case/fields/contacts.js b/client/modules/crm/src/views/case/fields/contacts.js
index 077ede4..5ed21ee 100644
--- a/client/modules/crm/src/views/case/fields/contacts.js
+++ b/client/modules/crm/src/views/case/fields/contacts.js
@@ -26,12 +26,10 @@
  * these Appropriate Legal Notices must retain the display of the "EspoCRM" word.
  ************************************************************************/
 
-Espo.define('crm:views/case/fields/contacts', 'views/fields/link-multiple-with-primary', function (Dep) {
+Espo.define('crm:views/case/fields/contacts', 'views/fields/link-multiple-with-role', function (Dep) {
 
     return Dep.extend({
 
-        primaryLink: 'contact',
-
         getSelectFilters: function () {
             if (this.model.get('accountId')) {
                 return {
@@ -39,7 +37,7 @@ Espo.define('crm:views/case/fields/contacts', 'views/fields/link-multiple-with-p
                         type: 'equals',
                         field: 'accountId',
                         value: this.model.get('accountId'),
-                        valueName: this.model.get('accountName')
+                        valueName: this.model.get('accountName'),
                     }
                 };
             }
```

Attaching the diff file if you want to apply it to your instance.
[diff.patch.txt](https://github.com/espocrm/espocrm/files/913479/diff.patch.txt)

**Comment by bandtank** [comment]
What are you trying to do exactly? Are you trying to leave Opportunity as is and add the functionality to the Case module to make the Contacts field look exactly like it does in Opportunities? That's what I think you're trying to do, but that's not at all what the code you posted will accomplish.

**Comment by bandtank** [comment]
Try this:

![image](https://cloud.githubusercontent.com/assets/1170415/24915069/654a9bb0-1e93-11e7-9b37-12521e74f8e3.png)

![image](https://cloud.githubusercontent.com/assets/1170415/24915079/6e3004ae-1e93-11e7-93ce-f0acb93549d1.png)

**Comment by tannakartikey** [comment]
Great. It worked! Many thanks.

But this is just the halfway. Now I will try it on the custom module.

**Comment by b1f17773** [comment]
Great! Thanks @bandtank
