### ISSUE TITLE
Send Call Invitations: error 500

### ISSUE THREAD

**Issue by zedar187** [espocrm/espocrm#50]
If I try to send invitations to users, I get an "error 500" message. It's just an test call without any info except name, time and duration. The test users both have activated smtp mail accounts but no imap configured.

EspoCRM error log states:
```
[2015-05-12 11:55:09] Espo.ERROR: E_RECOVERABLE_ERROR: Object of class stdClass could not be converted to string {"file":"*fullpathtoespocrm*/application/Espo/Modules/Crm/Business/Event/Invitations.php","line":77} [] // <-- this line is repeated 14 times
[2015-05-12 11:55:09] Espo.ERROR: API [POST]:/:controller/action/:action, Params:Array
(
    [controller] => Call
    [action] => sendInvitations
)
, InputData: {"id":"5551e6f8ba3cb8783"} - See http://pobox.com/~djb/docs/smtplf.html.
 [] []
[2015-05-12 11:55:09] Espo.ERROR: Display Error: See http://pobox.com/~djb/docs/smtplf.html.
, Code: 500 URL: /api/v1/Call/action/sendInvitations [] []
```

The users get a notification in espocrm: "Email received from empty address; Invitation to call 'testcall' ". Now I can see the invitation in the email tab; but with status "archived", sent date "none", from "none", but with a filled body (subject, begin, action-buttons, attachment call.ics).

Edit: EspoCRM is configured with an outbound email account with the checkbox "anybody can use" activated.

Edit2: Sending testmails as well as "user assigned you a lead"-mails work fine. 

The server is running debian wheezy with plesk 11.5 (apache 2.2, php 5.4, qmail, cron activated) with espocrm 3.2.2.

**Comment by skynet** [comment]
Do we have any support on this? thank you.

**Comment by skynet** [comment]
Great.
