### ISSUE TITLE
EntityCollection method rewind() sets wrong position after unsetting first elements

### ISSUE THREAD

**Issue by yunga91** [espocrm/espocrm#510]
Hello,

`EntityCollection` method `rewind()` sets wrong internal position in case after unsetting elements from container beginning and count of remaining elements lower than minimum index in container.

For example, we have collection from 3 elements, with indexes 0, 1, 2 respectively. So after unsetting first two elements and calling `rewind()`, internal position will point to index 1, not to 2.

**Comment by yurikuzn** [comment]
>  internal position will point to index 1, not to 2.
Shouldn't it be 0 after rewind?

**Comment by yunga91** [comment]
It should be 2. It should point to first existing element of container.

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/e4d0fbaf375cf5169eccb8ef5e6df39defb79fb2

**Comment by yunga91** [comment]
thanks a lot

**Comment by yurikuzn** [comment]
There could still be issues. We will test.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/ef7eaa925f775c1727cb73875b9bec0fbc0ee04f
