### ISSUE TITLE
Documents don't automatically link to parent via Relationship Panel 'Create' Action

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#511]
If you click the create button on the Documents panel of an entity, the parent should be set to the current entity by default.

Instead the choice is empty.

![screen shot 2017-04-21 at 12 30 47](https://cloud.githubusercontent.com/assets/7381617/25275727/a54b9086-268e-11e7-9778-59ece464a08e.png)

**Comment by yurikuzn** [comment]
Document doesn't have Parent link.
Does your documents relationship panel represents parent link?

**Comment by alasdaircr** [comment]
Ah - I must have forgot I added the parent field sorry about that.

I don't understand why there's a many-to-many link between documents and leads, contacts, accounts etc. Usually a document would only relate to one entity is that not right? Documents such as invoice wouldn't link to two accounts for instance.

**Comment by bandtank** [comment]
I added a one to many for documents because most documents will be that way. Many to many is useful sometimes, though. Blank forms, instructions, etc. can apply to multiple entities and multiple instances of entities.

**Comment by alasdaircr** [comment]
@yurikuzn can you remind me how to get this working? What is the client function that pre-populates fields in the quick create dialog?

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/client/modules/crm/src/views/opportunity/detail.js#L40

**Comment by alasdaircr** [comment]
Thanks very much. This is what I needed in each of the entites which are valid parents for documents.

```js
relatedAttributeFunctions: {
    'documents': function () {
        var data = {};
            data['parentType'] = this.model.urlRoot;
            data['parentId'] = this.model.get('id');
            data['parentName'] = this.model.get('name');
        return data;
    }
},
```
