### ISSUE TITLE
Text box should resize when in edit mode

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#512]
When a text box is edited it should snap around the length of the content, up to the viewport size

Currently the editable area is smaller than the displayed area due to scroll bar and other styling.

![screen shot 2017-04-21 at 12 40 58](https://cloud.githubusercontent.com/assets/7381617/25276032/214d98b8-2690-11e7-8678-6e0193ba7bf8.png)

![screen shot 2017-04-21 at 12 41 04](https://cloud.githubusercontent.com/assets/7381617/25276037/24cc1fd2-2690-11e7-8a95-3311e2638810.png)

Also - it shouldn't be able to horizontally resize the textbox, which you can currently (Chrome 57)

**Comment by bandtank** [comment]
Isn't this a configuration setting? The horizontal resize may be an issue, but I would expect the vertical size to match the setting for the field in the Entity Manager.

**Comment by alasdaircr** [comment]
Ah you're right it's the "Number of rows of textarea" setting. shame it's not responsive to the content but adjusting that will do for now
