### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#515]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/e0ebb44e648494051a4e05c2268ee888bcbdd3d9

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/db893859c235e6be731563fccb5e261fc0587443

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/8b9a0f1437f37add48fb0f34b3fa122bc8d227b6

**Comment by alasdaircr** [comment]
Brilliant, very happy about this!

**Comment by yurikuzn** [comment]
Thank you for contribution.
