### ISSUE TITLE
portal in nginx get error '404 Not Found'

### ISSUE THREAD

**Issue by irvatoDev** [espocrm/espocrm#519]
### portal in nginx get error '404 Not Found'
![nginx_config](https://cloud.githubusercontent.com/assets/7011863/25401652/88163f36-2a0b-11e7-83db-4cf0578a342f.png)
![portalconfig](https://cloud.githubusercontent.com/assets/7011863/25401653/8816ebca-2a0b-11e7-9b7d-b635e387ffc9.png)
![portallink](https://cloud.githubusercontent.com/assets/7011863/25401654/88194bea-2a0b-11e7-9b45-91beee1639d4.png)

**Comment by yurikuzn** [comment]
There mast be rules for portal added to config that represents rules in
api/v1/portal-access/.htaccess
portal/.htaccess

Unfortunately I'm not specialist. We will be able to do it later. Any help is appreciated.

**Comment by alasdaircr** [comment]
Add this:
```
        location /api/v1/portal-access {
                if (!-e $request_filename){
                        rewrite ^/api/v1/(.*)$ /api/v1/portal-access/index.php last; break;
                }
        }
```
below the existing location ``/api/v1`` block

**Comment by alasdaircr** [comment]
``sudo nginx -t``
then if config valid
``sudo service nginx reload``

**Comment by irvatoDev** [comment]
tank you guys.

fixed

```nginx


location / {
        #try_files $uri $uri/ =404;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /portal/ {
        try_files $uri $uri/ /portal/index.php?$query_string;
    }

   location /api/v1/portal-access {
        if (!-e $request_filename){
                rewrite ^/api/v1/(.*)$ /api/v1/portal-access/index.php last; break;
        }
   }
```

**Comment by bandtank** [comment]
Make sure to close the issue when it is resolved. Thanks for posting your solution.

**Comment by alasdaircr** [comment]
I found that I didn't need the ``/portal/`` line as index.php is tried automatically. But YMMV.

**Comment by irvatoDev** [comment]
Removed /portal/ get "not found page" from app
