### ISSUE TITLE
Not sending email campaign after update

### ISSUE THREAD

**Issue by bosonno** [espocrm/espocrm#520]
Current Espo version 4.6.0

Log:

Espo.INFO: CronManager: Stop cron running, too frequent execution.

**Comment by yurikuzn** [comment]
Can't reproduce. We tried and it worked.

**Comment by bandtank** [comment]
Without seeing the cron script, it's hard to know what the problem might be. Has anything been added or is it the default cron script? Post it here. Also, have you verified that cron is working correctly? Try a different script with basic commands and see if that works.

**Comment by bosonno** [comment]
/#ScheduledJob
Send Mass Emails	Send Mass Emails	Active	*/15 * * * *

Crontab
*/15 * * * * /usr/local/bin/php -f /var/www/html/cron.php > /dev/null 2>&1

Above is unchanged since previous Espo version.

Table email_queue_item is not populated.
Test emails do have status sent.

**Comment by bosonno** [comment]
Made a test campaign. Overnight both the test and the campaign that wouldn't send are both sent.
