### ISSUE TITLE
Admin note set to non-null value after installation

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#526]
I've seen this a number of times, but I have been ignoring it until recently. When I install EspoCRM, the admin user that's created during installation has a note that's set to `[object Object]`. I think a field must be incorrectly set to an object somewhere and the reflection of the type is turned into literal text, which is then stored in the note field. However, the text isn't in the database.

Immediately after installation:
![image](https://cloud.githubusercontent.com/assets/1170415/25496449/40a3e6a6-2b3e-11e7-986a-961a778f7a3d.png)

Edit mode:
![image](https://cloud.githubusercontent.com/assets/1170415/25496456/487ca2a0-2b3e-11e7-83d2-5efbd4f5c72d.png)

Database:
![image](https://cloud.githubusercontent.com/assets/1170415/25496489/6885e462-2b3e-11e7-87d9-64061a804a26.png)

I appended the letter 'a' to the field and then saved it, which wrote the whole string to the database:
![image](https://cloud.githubusercontent.com/assets/1170415/25496559/9cff46ac-2b3e-11e7-8990-99d0d017569c.png)

![image](https://cloud.githubusercontent.com/assets/1170415/25496538/90f885e4-2b3e-11e7-9a2f-c3461cd07fc3.png)

I don't know where to look to fix this, so I thought I'd post the details.

**Comment by yurikuzn** [comment]
This might be a conflict with existing `notes` link. Try to give another name to this field.

**Comment by bandtank** [comment]
That was it. Thanks.
