### ISSUE TITLE
Potencial security breach - Streams not being filtered as set in rules

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#530]
Even a user not being allowed to see other users' streams(set in rules), they are being showed on the streams tab or on the streams dashboard.

**Comment by rodrigoscoelho** [comment]
Sorry, not flows but Streams..... When you see flows, I mean stream

**Comment by yurikuzn** [comment]
User Permission restricts an acess to stream panel. But the user will see any stream records of onother user if one has an access to stream of record one is following.

**Comment by rodrigoscoelho** [comment]
I didn't understand. I can't restrict access to stream panel. And, even
when not restricted, it should show only the streams of permitted objects
or objects where the users is part of the team (when specified this way on
the rules)

Email enviado usando um celular....

Em 29 de abr de 2017 02:56, "Yuri Kuznetsov" <notifications@github.com>
escreveu:

User Permission restricts an acess to stream panel. But the user will see
any stream records of onother user if one has an access to stream of record
one is following.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/espocrm/espocrm/issues/530#issuecomment-298149430>, or mute
the thread

**Comment by yurikuzn** [comment]
There is column 'Stream' in Roles. It controls access to stream. "User Permission" controls an access to user's panel on detail view of Users.

**Comment by rodrigoscoelho** [comment]
Hi Yuri,

As you can see on the picture below, I set the Stream permission for TEAM
on Opportunities, for example. Only TEAM.
[image: Inline image 1]

But as you can see on the Picture BELOW, the user can see STREAMS of All
opportunities, even the ones he is not part of the group.

All the stream posts below are from Opportunities that the user is not part
of the group.

[image: Inline image 2]

If I tried to click on one of these opportunities, it gives me
[image: Inline image 3]

Am I doing something wrong with the permissions? I think this is a leak of
information. People without access to some areas are being capable to read
streams posted in opportunities that he is not part of.

**Comment by yurikuzn** [comment]
Images are not visible.

**Comment by yurikuzn** [comment]
Have user Followed those opportunities before you restricted an access?

**Comment by yurikuzn** [comment]
Can you see that user as a follower of those opportunities (right panel)?

**Comment by rodrigoscoelho** [comment]
Yes, he was a follower before. That's the problem?

**Comment by rodrigoscoelho** [comment]
I changed his access after. If part of the group and follower once, He will
be with access forever?

**Comment by yurikuzn** [comment]
If you reassign opportunity to another user or change team bad followers should be unfollowed by cron in few minutes. I belive. We don't catch user role changing to unfollow. It's too dofficult and can take resources. We planned to implement scheduled job that will unfollow users but there is a problem when database is big.

**Comment by rodrigoscoelho** [comment]
Ok, understood. What about reports.

I shared a report that SHOWS ALL OPPORTUNITIES for this user, even him not
being part of the group of that opportunity. The main problem is that if
this user click on the opportunity link from the report, it can open the
opportunity, but a message of ACCESS DENIED appears on the top of screen.
If he tries to refresh the page, the ACCESS DENIED PAGE appears.

**Comment by yurikuzn** [comment]
The data of opportunity was taken from the report and the page could be displayed w/o accessing to backend. And then system found out that user doesn't have an access to that record. I don't see any problem here.
