### ISSUE TITLE
Reports (advanced Package) not allowing to use Opportunities fields from Emails

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#531]
As you can see on the image below, I was trying to create a report to show all emails where the Origin (source) is opportunities where the team X is assigned. The problem is that it only shows Subfields related to Accounts, Projects, and others I created. The Opportunities fields are not shown as option to be used as filter or something else.

![image](https://cloud.githubusercontent.com/assets/6912410/25555641/6b1765c2-2cc2-11e7-9e05-4f7f2b9e47e2.png)

**Comment by yurikuzn** [comment]
This repository is not for advanced pack features.

**Comment by rodrigoscoelho** [comment]
So, where is it?

**Comment by yurikuzn** [comment]
Email doesn't have link direct link w/ opp. I think it's not possible to make such a report w/o direct link,

**Comment by yurikuzn** [comment]
You should have an access to our customer portal where you can create cases related to extensions you bought. Also you can create topic on our forum at Extensions category.

**Comment by yurikuzn** [comment]
As a workeround: you can create relationship w/o opp and fill opportunityId field with a formula by taking it from parentId field.

**Comment by rodrigoscoelho** [comment]
Ok, the only thing I didn't understand is WHY my created object AIMSUN, that is not linked with emails, appears as an option, as you can see below

![image](https://cloud.githubusercontent.com/assets/6912410/25555701/e33c1718-2cc3-11e7-978a-0d4a997dfa5e.png)

**Comment by yurikuzn** [comment]
I think you should check whether relationship exists in Entity Manager. Have you checked?

**Comment by rodrigoscoelho** [comment]
Just checked, no relationship. Weird.

**Comment by rodrigoscoelho** [comment]
I just created the opportunity relation, as you instructed. As you can see, no Aimsun relation..

![image](https://cloud.githubusercontent.com/assets/6912410/25555732/a1d0a860-2cc4-11e7-9e65-6bc48c44137f.png)

**Comment by yurikuzn** [comment]
Maybe relationship exists but defined only in emails entityDefs but not in aumsun entityDefs. In this case it won't be displayed in Entity Manager.
