### ISSUE TITLE
JS error: cannot use 'in' operator to search for 'fields' in null

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#537]
In the last few days, I merged espocrm/master into my repository and started getting this error:

![image](https://cloud.githubusercontent.com/assets/1170415/25926570/46a87fb6-35ad-11e7-9bf4-adbf16bfc85b.png)

I've seen it a few different places, but the only thing I can do to reproduce it repeatedly is to access the Preferences page. I can't figure out where the error is, so I can't help debug without a tip about where to look. I realize the features in the most recent commits may not be fully done yet, but I like to pull so I can test features.

**Comment by yurikuzn** [comment]
Did you run clearing cache? There must be code line indication where the error occurred in the top-right corner.

**Comment by bandtank** [comment]
Sorry, I forgot to include that piece. Here's the line and the code:

![image](https://cloud.githubusercontent.com/assets/1170415/25950238/7489cdd0-3617-11e7-8d3c-e9f31f3cf987.png)

**Comment by bandtank** [comment]
I saw that you committed something about not allowing fields with numbers. Is it possible I have a bad field name in the database or something?

**Comment by yurikuzn** [comment]
No. It's not related to that. Maybe you have something nulled in metadata. Can you console.log(this.name) before the error occurs please? Or print `this` somehow in debugger. Would be good to know which entity type it is.

**Comment by bandtank** [comment]
I added `console.log(this);` to `src/model.js` after searching for the function. Here's what happened:

![image](https://cloud.githubusercontent.com/assets/1170415/25951612/711d3da4-361b-11e7-899d-ca7e39c69113.png)

Here's the expanded object:

![image](https://cloud.githubusercontent.com/assets/1170415/25951676/9d6de624-361b-11e7-9371-c50e32009121.png)

**Comment by yurikuzn** [comment]
Do you have any customization in entityDefs for Settings entity?

**Comment by bandtank** [comment]
Good call. When I merged the changes, I didn't notice the missing brace. After adding a brace, everything works fine. Thanks.

![image](https://cloud.githubusercontent.com/assets/1170415/25953391/6acec972-3620-11e7-9a04-7ac4e40f6179.png)
