### ISSUE TITLE
Missing 'convert' label in en_US langauge

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#539]
See screenshot: [http://forum.espocrm.com/forum/bug-reports/28100-i-can-not-translate-convert-to-convert-a-lead](http://forum.espocrm.com/forum/bug-reports/28100-i-can-not-translate-convert-to-convert-a-lead)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/326970bcd4d5575258406105e207e5f5aea47f0e
