### ISSUE TITLE
Question: How to integrate custom server side business logic in ESPO CRM.

### ISSUE THREAD

**Issue by atapatel** [espocrm/espocrm#54]
Hi Espocrm team,
Can you please help me out with how can i create a custom server side business logic in ESPO CRM. my requirement is as below.

we have created custom module as per tutorial suggested on blog. now we wants to import record in our entity. but we need to add some business validation rule before custom import. so can u please tell me how can we achieve it.

**Comment by yurikuzn** [comment]
Hi

You'd better ask such questions on our forum. When you use Import Hooks beforeSave and afterSave are invoked. You should create such hooks.
