### ISSUE TITLE
Field Manager: Fields not sorted alphabetically in Add Field dropdown

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#540]
It is sorted by the ID of the field (in English) and not by the tag in translated (Spanish)

See screenshot: [http://forum.espocrm.com/forum/bug-reports/28102-not-sorted-alphabetically](http://forum.espocrm.com/forum/bug-reports/28102-not-sorted-alphabetically)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/9411bce8b0653858e4d213a03b561373b7358de5
