### ISSUE TITLE
Issue with PhpMimeMailParser library and PHP7

### ISSUE THREAD

**Issue by igorhim** [espocrm/espocrm#543]
There is an issue with the cron job "Check Group Email Accounts".
When it comes to PhpMimeMailParser library, php script is completely crashing with server error 500.
PHP version: 7.0.14-nmm1
I have temporary solved the issue by hardcoding $parserType to 'ZendMail'.

**Comment by yurikuzn** [comment]
Hi,

Would be helpful to know what exactly occur.

ZendMail is buggy. Since 4.6.0 version we use MailMimeParser by default.

**Comment by yurikuzn** [comment]
We've been using PhpMimeMailParser for year w/o problems on php7. Maybe issue is with MailMimeParser?

**Comment by igorhim** [comment]
It is shared hosting with php-fpm.
So, Unfortunately I couldn't catch the error to the php error log due to php-fpm specific.
Probably it is PhpMimeMailParser, because $parserType contains it's class name.

**Comment by yurikuzn** [comment]
I'd recommend to switch to MailMimeParser instead of ZendMail. You can specify it in `data/config.php` w/o hacking code.
```
'emailParser' => 'MailMimeParser',
```

**Comment by igorhim** [comment]
Thanks for the advice. I'll do that.
