### ISSUE TITLE
Too many database queries

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#549]
I have two instances of the site running for production and development. The development site is open in a single browser tab and the production site is open in three browser tabs. This is the MySQL log:

![image](https://cloud.githubusercontent.com/assets/1170415/26451638/2cd5c8a0-411a-11e7-8c77-e8f41f4e7f5e.png)

I filtered the list to only show the select queries on the preferences table, but there are more. Every five seconds, each tab queries the database twice for the exact same information. Preferences don't need to be queried that often as they should be cached. When my users are actively on the site, the performance of the server degrades noticeably and it's a 16 core Xeon with SSDs. I have roughly 80 users and my database has never struggled in the past.

Similarly, creating a new record for the account entity used more than 70 queries, many of which were duplicated. Is this behavior known?

**Comment by yurikuzn** [comment]
How could we cache preferences in application? Any suggestions? They are fetched each time when user loads the page. We might cache them in client-side but does it worth? Then we will need to control whether cached preferences is actual. 

MySQL has own cache so I don't think that accessing to preferences is a problem that causes performance problem. Maybe something else?

**Comment by yurikuzn** [comment]
Can you log only queries executing slowly. I believe problem caused by them.

**Comment by bandtank** [comment]
The way I've always done this is to query for preferences during login or when the preferences are changed, which allows me to store them on the client.

The queries in the picture aren't being generated by page loads. The browsers are sitting there doing nothing and the queries are still happening every five seconds.

**Comment by yurikuzn** [comment]
So client-side cache won't change the situation in this case because preferences are fetched for backend needs. Maybe when notifications being checked but not sure.

**Comment by bandtank** [comment]
I see. I'll look into it more.

**Comment by jneto81** [comment]
Why not store the preferences in the user session ?  

Can we configure the 5 seconds check from the frontend to backend ?

**Comment by yurikuzn** [comment]
Session may turn out even slower than a single db query to small cached table.

If preferences are ferched on notification check maybe it's possible not to load them at all. I will check. It could be that they are fetched in cron.

data/config.php
```
'notificationsCheckInterval' => 30, // seconds
```

https://github.com/espocrm/espocrm/blob/master/application/Espo/Modules/Crm/Resources/metadata/app/popupNotifications.json#L4

**Comment by yurikuzn** [comment]
I've managed to decrease loading of dependencies 
https://github.com/espocrm/espocrm/commit/3cfca9845a1fd0b8515814ad31be5cd803bd5378

It should decrease accessing to file system as well as to database.
