### ISSUE TITLE
HTML text field shows undefined when not editing

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#55]
Hello

I found the solution to the problem posed in this forum [thread](http://forum.espocrm.com/developer-help/2738-html-text-field-shows-undefined-when-not-editing?routestring=forum/developer-help/2738-html-text-field-shows-undefined-when-not-editing)

"Undefined" is displayed because the system can not find the cambo "body".

They have to change line [113](https://github.com/espocrm/espocrm/blob/master/frontend/client/src/views/fields/wysiwyg.js#L113)  of the `client/src/views/fields/wysiwyg.js` file

```javascript
var body = this.model.get('body');
```
to
```javascript
var body = this.model.get(this.name);
```
Greetings!

**Comment by yurikuzn** [comment]
Thanks
