### ISSUE TITLE
Usernames with @ aren't mentioned correctly in streams

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#555]
[Bug report on the forum](http://forum.espocrm.com/forum/bug-reports/28388-mentioning-a-user-in-stream-uses-email-address-instead-of-username)

In a nutshell, if a user's name is `Test Test` with a username of `test@test.com`, typing `@Test Test` to mention the user in a stream will cause the username to change to `test@test.com`.

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/f474137b9195fe2b426a00243ad38632f4671f15

**Comment by bandtank** [comment]
This doesn't appear to be fixed. See the attached video.
[mentions.zip](https://github.com/espocrm/espocrm/files/1687735/mentions.zip)

**Comment by yurikuzn** [comment]
I think it's how it was designed from the beginning. Not configurable.
