### ISSUE TITLE
Replace all loadSmth-methods with loaders to get an ability to override them by custom loaders

### ISSUE THREAD

**Issue by PatchRanger** [espocrm/espocrm#563]
## Problem
I want to enable error monitoring for my EspoCRM installation by Rollbar service.
The integration is pretty simple: I just need to push additional handler into the internal `Monolog` class.
But all of the classes (`Application`, `Container`) are harcoded - and I can't inject my custom workaround as a new dependency.

## Reason
There is no way to extend the way it works for loadSmth-methods (e.g., `loadLog`). In other words, I can't integrate it with Rollbar without hacking.

## Solution
Let's turn all loadSmth-methods (including `loadLog`) into `\Espo\Core\Loaders` classes. It will give an ability to override them by creating the corresponding class in `\Espo\Custom\Core\Loaders` namespace (e.g., `\Espo\Custom\Core\Loaders\Log`) with required tweaks.

**Comment by PatchRanger** [comment]
@yurikuzn If you're not already working on it, I am going to provide a pull-request soon.

**Comment by yurikuzn** [comment]
Not sure if we will accept pull requests. It's very core of the application. I will look into this later.

**Comment by PatchRanger** [comment]
@yurikuzn Ok, I understood, thank you. Please keep in mind the purpose of the proposed changes: I need a way to extend `Logger` with Rollbar functionality. If you'll point a clean way to do it without touching application core - that would solve the issue & eliminate the need of such pull-request.
