### ISSUE TITLE
Turn EspoCRM into composer library to get upgrades via composer along with an ability to use custom index.php and .htaccess 

### ISSUE THREAD

**Issue by PatchRanger** [espocrm/espocrm#566]
## Problem
Upgrade via UI is handsome - though it is quite problematic to make upgrades given you have development workflow based on git: you need to upgrade all of your environments manually and separately.

## Reason
There is no change transition.

## Solution
Let's switch to composer-based upgrade.
I mean there should be a way to trigger and apply upgrades programmatically - which also serves as a basement for UI task.
Composer has such functionality: [scripts](https://getcomposer.org/doc/articles/scripts.md).

This change would put entire EspoCRM into `vendor` subfolder - which in turn gives an opportunity to have custom `index.php` and `.htaccess` files without need to "hack" original files.

Turning into library is a normal practice during the way from "script" to "framework": look at [Yii](https://github.com/yiisoft/yii2), [Zend](https://github.com/zendframework/zendframework) - they are all available as composer library.

**Comment by yurikuzn** [comment]
It might be not easy to do for EspoCRM.

**Comment by PatchRanger** [comment]
@yurikuzn I understand) This issue doesn't have any estimates or milestones - as it really looks not easy. But I want it to be manifested as a long-term aim. In my view it would ease building enterprise-level development workflow basing on EspoCRM.
