### ISSUE TITLE
Add environment-specific configuration overriding defaults in global configuration and ignored by git

### ISSUE THREAD

**Issue by PatchRanger** [espocrm/espocrm#567]
## Problem
There is no way to have global configuration with reasonable defaults (which is versioned by git) - together with environment-specific tweaks (which are ignored by git).

## Reason
For now we do not have a mechanism of including (if exists) environment configuration, which overrides global values.

## Solution
We should adapt something similar to [what Yii currently has](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md).

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/2916
