### ISSUE TITLE
Unable to import entity related values 

### ISSUE THREAD

**Issue by logicplus** [espocrm/espocrm#569]
Hello, 

We have discovered an error while importing entity related values 
file : /application/Espo/Services/import
line: 575
if ($field == $relation . 'Name' && !$entity->has($relation . 'Id') && array_key_exists($relation, $relDefs)) {

it should be : 

if ($field == $relation . 'Name' && $entity->has($relation . 'Id') && array_key_exists($relation, $relDefs)) {

Hope this help.

**Comment by yurikuzn** [comment]
Hi,

Expected logic:
If no id of related specified but specified name then try to find related record by name.
