### ISSUE TITLE
I can not use a custom view in modal windows

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#57]
This is due to an error in the [detail.js](https://github.com/espocrm/espocrm/blob/master/frontend/client/src/views/detail.js) file, line [214](https://github.com/espocrm/espocrm/blob/master/frontend/client/src/views/detail.js#L214).

At line [213](https://github.com/espocrm/espocrm/blob/master/frontend/client/src/views/detail.js#L213) view is defined (custom or default), but the variable at line 214 is not used. Please replace this

```javascript
this.createView('quickCreate', 'Modals.Edit', {
```
for this
```javascript
this.createView('quickCreate', viewName, {
```

Greetings!

**Comment by yurikuzn** [comment]
Thanks
