### ISSUE TITLE
Click on "Call, Tasks, Meeting" and don't work...

### ISSUE THREAD

**Issue by valessiobrito** [espocrm/espocrm#58]
Click on #Call #Tasks #Meeting and don't work...

::1 - - [15/Jul/2015:09:51:59 -0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) (internal dummy connection)"
10111 - valessio [15/Jul/2015:09:52:00 -0300] "GET /crm/api/v1/Notification/action/notReadCount 1HTTP/1.1" 200 350 "http://domain.tdl/crm/" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"

**Comment by yurikuzn** [comment]
I can't reproduce.

**Comment by valessiobrito** [comment]
I'm using the version repo git _master_

**Comment by yurikuzn** [comment]
Maybe was a temporary issue. You should use stable branch to have the stable version.
