### ISSUE TITLE
Losing search data after navigating back to list view

### ISSUE THREAD

**Issue by barwi** [espocrm/espocrm#582]
Data of the 2nd filter lost after using back browser button.
Steps to repeat (more details in the attachment below):

1) Set 1st filter in contacts & press Search.
2) Set 2nd filter & press Search again.
3) Click on link to show contact details page.
4) Press Back button in browser navigation panel – search results is cached.
5) Click Search button again without changing any filters – results are unexpected, actually 2nd filter has been lost.
6) Reload page F5 with no any changes, surprisingly 2nd filter is empty.

[Lost filter content.docx](https://github.com/espocrm/espocrm/files/1129096/Lost.filter.content.docx)

**Comment by yurikuzn** [comment]
Thanks for reporting. This fix must help https://github.com/espocrm/espocrm/commit/94c2b9dedad9ae5cd93390fb04b9ac473fd33951
