### ISSUE TITLE
XSS in title field from accounts

### ISSUE THREAD

**Issue by naxonez** [espocrm/espocrm#59]
Hi,

Recently y found this XSS in the title field in the accounts settings when you try to create a new account.

Regards.
![asd](https://cloud.githubusercontent.com/assets/7959568/9274604/89286e74-4297-11e5-9ed8-1d8638880134.png)

**Comment by yurikuzn** [comment]
Hi, 

Thanks, fixed here https://github.com/espocrm/espocrm/commit/ba5bd60931cb7f131072357a1563a86db196db0e
