### ISSUE TITLE
Unable to update (memory limit)

### ISSUE THREAD

**Issue by trsrm** [espocrm/espocrm#61]
I'm trying to apply an update from v3.4.2 to v3.5.0.
And receive following error:
>Bad server response:
>Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 13227209 bytes) 
>in ...Espo/Core/Upgrades/Actions/Base/Upload.php on line 49

**Comment by yurikuzn** [comment]
Try to increase memory limit.

**Comment by trsrm** [comment]
Sure, but this is impossible on my shared hosting account.

**Comment by yurikuzn** [comment]
1. Move your instance to another server.
2. Upgrade.
3. Move back.
