### ISSUE TITLE
Inactive Role Changes

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#610]
Hello,

Thanks for merging those changes & the role filtering ones too! Couple of things I'm noticing:

1. In the Contact relationship Panel of an Account, Inactive roles appear in the list with strikethrough. This is OK, however you might want to consider sorting them by `account_active,name` in order that the active contacts of a company appear higher up in the list. For large companies this would save having to click 'Show More' more times than neccessary.

2. When an inactive role is set as primary (or the only one) for a contact, the company name is not displayed as strike through in the Contact list view. (here Emma Larson's Perfectiko role is inactive).

![screen shot 2017-08-09 at 12 10 54](https://user-images.githubusercontent.com/7381617/29118940-0ef8b45a-7cfc-11e7-9fd1-5eef4c7e00d7.png)

**Comment by alasdaircr** [comment]
You might even want to have a toggle for Inactive Contacts in the Account -> Contact Relationship panel.

As you can see even with a tiny company, this is starting to get messy:
![screen shot 2017-08-09 at 12 18 01](https://user-images.githubusercontent.com/7381617/29119151-ea44faa0-7cfc-11e7-8290-c05ab5975e90.png)

**Comment by yurikuzn** [comment]
Hi,

Good idea w/ filters. https://github.com/espocrm/espocrm/issues/612

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/616
