### ISSUE TITLE
RFC: [Metadata] limit  by ACL & dump with <layout> 

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#617]
Hi, I wonder if it make sense that we got the whole layout as a part of Metadata service, instead of making a separate request for every layout.
also I wonder if it is better to get the metadata parts filtered by ACL

**Comment by yurikuzn** [comment]
Hi,

I don't see a problem there. Layouts are cached in frontend.

Some metadata are hidden from frontend. The most of metadata is used in frontend.

**Comment by ayman-alkom** [comment]
> Some metadata are hidden from frontend. The most of metadata is used in frontend.

for example if the user not has access to entity XXX, then XXX fields not has to be returned with the metadata service

**Comment by ayman-alkom** [comment]
another example:
in the portal if I am a portal user, I can overview all the structure of the tables witch may I protected it by ACL.
making the returned scopes and client defs ... etc filtered by the ACL maybe a good idea

**Comment by yurikuzn** [comment]
I need to investigate how difficult to implement. But idea is good.

**Comment by ayman-alkom** [comment]
when you want I can try to do it

**Comment by yurikuzn** [comment]
1st problem I see. If admin enables access to certain scope,, user will need to re-login to have updated metadata loaded.

**Comment by ayman-alkom** [comment]
I saw a variable cacheTimestamp, that used to update the cached data or getting from the cache, we may depend on this variable, updating it when we update the ACL

**Comment by ayman-alkom** [comment]
so the front-end will force update the cached metadata, I guess

**Comment by yurikuzn** [comment]
Yes. But this requires major changes in critical parts.

**Comment by yurikuzn** [comment]
Maybe it will work with current code. Need to test.

**Comment by yurikuzn** [comment]
Seems there shouldn't be a problem since metadata is re-loaded on clear cache.

**Comment by ayman-alkom** [comment]
I suggest to divide the problem to two parts:
- the first is to limit the metadata content by ACL
- the second to detect the change on ACL and force the frontend to reload the metadata

may the second part not very important like the first one, but will be better if it done

**Comment by yurikuzn** [comment]
Actually 2nd part is very important.

**Comment by yurikuzn** [comment]
Will be added for 5.7.
