### ISSUE TITLE
Update stale data for all dependent actions inside each Workflow in case if related entity is updated

### ISSUE THREAD

**Issue by PatchRanger** [espocrm/espocrm#620]
### Problem
Currently `actions` structure inside Workflow entity has data, which tends to become stale each time the related entity is updated.

I can think of 2 cases:
- Workflow, which triggers another Workflow: `workflowName` inside `actions` is stale after the related Workflow is updated.
- The same situation is for actions of type `sendEmail`: they have `emailTemplateName`, which becomes stale after EmailTemplate is updated.

It makes UI to show stale data - which is inconvinient and confusing.

### Reason
There is no mechanism to update such data. Please consider creating such mechanism.

**Comment by PatchRanger** [comment]
@yurikuzn Could you elaborate a bit: what do you mean by "invalid"? Do you agree that current structure of actions leads to staled data after updating related entity? Don't you think that it would be better to avoid such situations? I don't insist to implement it ASAP - I just want it to be accepted as a feature request.

**Comment by yurikuzn** [comment]
Advanced pack features is out of scope of this repository.
