### ISSUE TITLE
Should block 'Updates' / 'Sends' while uploading an attachment

### ISSUE THREAD

**Issue by alasdaircr** [espocrm/espocrm#621]
Hello there,

It's possible to hit 'Send' while still uploading an attachment to an email.

It's also possible to click 'Update' while uploading an attachment to a post.

Would be great if this could be improved in the UI.

**Comment by bandtank** [comment]
Yes, this is a pain sometimes. It has caused many problems for us.

**Comment by alasdaircr** [comment]
Would be fairly easy to fix I think.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/759
