### ISSUE TITLE
Next/Previous buttons on calendar dashlet

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#629]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/88135f93fe9b75cd4c5229d9673148f5f98b9f25

**Comment by sebdoido** [comment]
Awesome ! You rock !!

**Comment by sebdoido** [comment]
some feedback: 
when using "month" display, it could be great to have a label to display the current display month (even if it's a small date-format like 08/2017).

In attachment how it's displayed.
We can be lost easily when using prev/next button and don't know which month is display (the weekn number is useful in that case to avoid to get lost).

What do u think about adding an extra label to display the current month ?
In week mode, it could be displayed in the "colum name" (format "dd/mm")
<img width="1167" alt="capture d ecran 2017-08-21 a 13 26 52" src="https://user-images.githubusercontent.com/19854046/29517256-9203c3a4-8674-11e7-9347-d00d5733f78d.png">
<img width="1169" alt="capture d ecran 2017-08-21 a 13 23 48" src="https://user-images.githubusercontent.com/19854046/29517257-92052866-8674-11e7-9dcf-61d520037b2e.png">

**Comment by yurikuzn** [comment]
I'll think about it.

**Comment by sebdoido** [comment]
thanks :)

**Comment by yurikuzn** [comment]
Done here: https://github.com/espocrm/espocrm/commit/cc3ba89ab3012825dca5b546e7e0b03213eea40c

**Comment by sebdoido** [comment]
Thanks Yuri!
That's excellent!

IMHO, i think we should display that title for both month or *week*
I made a test to check how it could be displayed

<img width="1169" alt="capture d ecran 2017-08-21 a 14 42 41" src="https://user-images.githubusercontent.com/19854046/29519874-3ee248de-867f-11e7-8f1d-9b62b90ff1d1.png">

What do you think about it ?

**Comment by sebdoido** [comment]
In `client/modules/crm/src/views/dashlets/calendar.js `
line 74
https://github.com/espocrm/espocrm/commit/cc3ba89ab3012825dca5b546e7e0b03213eea40c#diff-cecc8f870a5a0b58c381381d28be9f42R74

I think you should use 
`if (mode !== 'agendaDay' && mode !== 'basicDay') {`

or... always display the title :) 
IMO, even on "agendaDay" or "basicDay", it's not a problem to display the title i guess

<img width="1171" alt="capture d ecran 2017-08-21 a 15 05 57" src="https://user-images.githubusercontent.com/19854046/29520643-436d75c4-8682-11e7-810e-ea02c0feac0d.png">
<img width="1179" alt="capture d ecran 2017-08-21 a 15 05 37" src="https://user-images.githubusercontent.com/19854046/29520644-436f46f6-8682-11e7-9455-499e1962df56.png">
<img width="1175" alt="capture d ecran 2017-08-21 a 15 05 24" src="https://user-images.githubusercontent.com/19854046/29520645-4386c614-8682-11e7-9449-d06973e6a2da.png">

**Comment by yurikuzn** [comment]
You need to run `grunt` command.

**Comment by sebdoido** [comment]
Perfect, thx !

**Comment by loreahlie11** [comment]
I'm having the same spacing issue, but I don't think I have grunt installed?  I'm not sure what I need to do to be able to run grunt command to fix this issue.  Any additional insight or recommendations?

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm#how-to-build
