### ISSUE TITLE
PHP Fatal error:  Call to a member function emergency() on null

### ISSUE THREAD

**Issue by mrpiagg** [espocrm/espocrm#630]
Dear all,
after upgrade from 4.7.2 to 4.8.1 i get two errors:

**error 1:** PHP message: PHP Fatal error:  Call to a member function error() on null in /var/www/crm/application/Espo/Core/Utils/Json.php on line 75" while reading response header from upstream, client: x.x.x.x, server: xxxxxxxxx.com, request: "GET /api/v1/Activities/action/popupNotifications HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxxxxxxx.com", referrer: "https://xxxxxxxxx.com/"

**error 2:** PHP message: PHP Fatal error:  Call to a member function emergency() on null in /var/www/crm/application/Espo/Core/Utils/File/Unifier.php on line 171" while reading response header from upstream, client: x.x.x.x, server: xxxxxxxxx.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxxxxxxx.com"

If i comment out $GLOBALS['log']->error('Json::decode():' . $error); in Json.php and $GLOBALS['log']->emergency('Syntax error in '.Utils\Util::concatPath($paths)); in Unifier.php page loads normally.

Server is Ubuntu 15.04 with Nginx and php-fpm5.

Regards, Egi

**Comment by yurikuzn** [comment]
Thanks

**Comment by mrpiagg** [comment]
This issue is fixed or not? Even if i change files Container.php and Log.php i still get mentioned errors.

**Comment by mrpiagg** [comment]
Now i have replaced all files in application\Espro\Core with latest version from github and CRM works as expected.

**Comment by yurikuzn** [comment]
So we can close this issue.
