### ISSUE TITLE
Question related to EspoCRM GPL License

### ISSUE THREAD

**Issue by coooolers** [espocrm/espocrm#642]
Th Espo CRM source code files displays the following ..  

The interactive user interfaces in modified source and object code versions of this program must display Appropriate Legal Notices, as required under Section 5 of the GNU General Public License version 3.

In accordance with Section 7(b) of the GNU General Public License version 3, these Appropriate Legal Notices must retain the display of the "EspoCRM" word.

Kindly consider this scenario ... I want to modify the Espo CRM code and would like to offer the modified version as "Software as a Service" on the Internet.

So kindly explain what do I need to do so that the GPL Licensing instruction is not violated.

Pl. reply soon.

Thanks

**Comment by yurikuzn** [comment]
Arranged through emails.

**Comment by lixaotec** [comment]
@yurikuzn can you provide the info @coooolers requested?

Is it possible for me to change Espo CRM at my needs and sells it to a costumer? And later providing him the modified code so he can custom at his needs with their team? 

Thank you

**Comment by yurikuzn** [comment]
Yes. There are a lot of information about GPLv3 on internet.
