### ISSUE TITLE
Can't push a contact to Google Contacts 

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#646]
The push to Google Contacts option only is available if listing contacts and selecting one or more, asking to push them to google.
Why don't we have an option to, when editing a contact, ask to push it??

**Comment by yurikuzn** [comment]
Hi,

This repository is not covers features of advanced pack. Could you please create a topic on our forum or on our customer portal.

Thanks

**Comment by rodrigoscoelho** [comment]
Yuri, that's the only way you see it. I don't know how to inform a bug for the Advanced Pack. 

I hope you will take care of it. Wrong Place, Real Bug.

**Comment by yurikuzn** [comment]
You should have an access to customer portal. Bug is already fixed.

Please. Don't create issues related to advanced pack in the repository.
