### ISSUE TITLE
prefixing for modules

### ISSUE THREAD

**Issue by micha-nerdlichter** [espocrm/espocrm#647]
I created a plugin "Foo" to define a custom field type. In my `files/client/modules/foo/src/views/fields/time.js` I have defined the view with a prefix `foo:`:
```
Espo.define('foo:views/fields/time', 'views/fields/base', function (Dep) {
    return Dep.extend({
        type: 'int',
        editTemplate: 'foo:fields/time/edit',
        ...
```
I can create a field of this type in an entity and add it to my layout. But as soon as I want to create a new instance of my entity type, ESPO stops with a js error because it tries to load the view `views/fields/time` instead of `foo:views/fields/time`. So it looks for the file in `client/src/views/...` instead of `client/modules/foo/src/views/...`. Why is the prefix lost?

As soon as I copy all my files directly to the core-paths, everything works fine. But doesn't this whole module-mechanism and the prefixing exist to prevent that? Were there any changes in the module loading mechanism? The extension https://github.com/ayman-alkom/EspoDataGrid shows the same errors in `4.8.1`.

**Comment by yurikuzn** [comment]
https://github.com/ayman-alkom/EspoDataGrid/blob/master/files/application/Espo/Modules/Kobit/Resources/metadata/fields/dataGrid.json#L6

I tried and it worked. Maybe need to clear cache.

**Comment by micha-nerdlichter** [comment]
Of course I did a rebuild and cleared the cache. Looks like there is an issue with lower vs uppercase in namespaces and directories. You tried this under windows? I'm on linux, so I had to rename `files/client/modules/Kobit` to `files/client/modules/kobit`, then it worked.
Still trying to figure out why this works - whereas my plugin looses it's namespace. I'll dig deeper...

**Comment by yurikuzn** [comment]
All characters as well as folder/file names should be in lower case.

**Comment by yurikuzn** [comment]
Can you provide your entityDefs > fields > time.json file contents?

**Comment by micha-nerdlichter** [comment]
Ah, I figured it out. There were two problems in my files:
1. the view in `files/application/Espo/Modules/Foo/Resources/metadata/fields/time.json` has to point to `foo:admin/field-manager/fields/time/default`, whereas the `Espo.define` in `client/modules/foo/src/views/admin/field-manager/time/default.js` has to point to `foo:views/admin/field-manager/fields/time/default`. Otherwise Espo doubles the view-folder in the path and tries to locate the file in `client/modules/foo/src/views/views/...`.
2. The `time.json` has to contain the entry `"view": "foo:views/fields/time"`, otherwise Espo tries to locate the view in the `client/src/views/fields` folder.

All this is so confusing... but thanks for your help.

> All characters as well as folder/file names should be in lower case.
Yes, the folders in `client`. All the folders in `application` are uppercase. And in https://github.com/ayman-alkom/EspoDataGrid/tree/master/files/client/modules the `Kobit` folder is uppercase, so it won't work in linux.
