### ISSUE TITLE
Email import not working with special characters

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#648]
Many people are using emoji and EspoCRM cuts email part after emoji in our case.

Is there way to debug this problem?

Classic mail client - Roundcube - displays emails with emojis printed out.

This is original string:

" mail 😀"

**Comment by yurikuzn** [comment]
You can change the collation of body column of email table to utf8mb4. The same for name column (email subject).

**Comment by david-strejc** [comment]
OK - will try this

**Comment by PanuWeb** [comment]
Hello! same error but the solution does not work.

![emoji01](https://user-images.githubusercontent.com/110789/33404050-9f818f18-d541-11e7-8f25-33f965c83e2c.png)
![emoji02](https://user-images.githubusercontent.com/110789/33404051-9fa27192-d541-11e7-80d1-d61fba5820d5.png)
![emoji03](https://user-images.githubusercontent.com/110789/33404052-9fcf8e98-d541-11e7-9f83-b9d01edbe64c.png)
![emoji04](https://user-images.githubusercontent.com/110789/33404053-a0048454-d541-11e7-9379-8df7466c9d14.png)

Original issue: [#381](https://github.com/espocrm/espocrm/issues/381)

**Comment by PanuWeb** [comment]
(I think I closed the issue without wanting to ...)

Now that I think about it, it partially solves the problem: it no longer cuts the text, but the emiji is not seen anyway.
