### ISSUE TITLE
Cant change some spanish language words

### ISSUE THREAD

**Issue by josephballester** [espocrm/espocrm#65]
Language available in spanish is with the spain pronunciation.  Im latin and some words sounds weird in my spanish language.  I change the words i dont like in the es_ES directory but words remains unchanged.  

Why this happen?

**Comment by yurikuzn** [comment]
Clear cache.

You can create new language for your region. Separated from es_ES.

**Comment by josephballester** [comment]
Thanks  When finished. I contact you to upload the language.

**Comment by josephballester** [comment]
by the way. how i create .json files?  Can you tell me about a tutorial i
can read for this?

thanks

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/README.md

How to make a translation
