### ISSUE TITLE
Firefox v52 issue #2 (mouse hover, click  events not working in flotr charts)

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#656]
on latest firefox 52.0.2 mouse move and click events not working at flotr2 charts.

I have also checked demos at [http://www.humblesoftware.com/flotr2/#!basic-bars](http://www.humblesoftware.com/flotr2/#!basic-bars) and there mouse events not working too in the latest firefox. Looks like flotr2 problem.. but maybe someone has soluttion or workaround to fix it ?

**Comment by yurikuzn** [comment]
Seems to be working on FF 56.0

**Comment by rutkas** [comment]
I forgot to mention that the devices where I test it have touch screens. I remember such bug in Chrome - when device has touch scr - mouse events are not working, but touch events worked. and this bug can be avoided by removing this feature in chromse system settings. In firefox now no mouse and no touch events working and I donna know system settings in firefox to turn off touchscreen support.

**Comment by rutkas** [comment]
I have found a workaround for this issue, caused by flotr2 bug that does not handle both mouse and touch events correctly, need to turn off touch events in FF:

go to [about:config](about:config), and set dom.w3c_touch_events.enabled to 0
