### ISSUE TITLE
More precise mass email sending limit

### ISSUE THREAD

**Issue by matthijsthoolen** [espocrm/espocrm#662]
Our mailprovider uses an algorithm/limit for send messages in a timespan. The number of send emails at the same time is roughly 40. But we can send batches of 40 mails every few minutes. 

At this moment the only setting in Espo CRM is max email send within an hour. It would be nice if this can be set more precise. (e.g. send 5 mails in a minute/5minutes/15minutes/hour etc.)

This is most useful for sending out newsletters/campaigns to a large groups of users.

**Comment by yurikuzn** [comment]
I will think about implementing this. Thanks,

**Comment by Mi-Sp** [comment]
Since its been such a long time, I dare asking: Is there any plan to implement this enhancement in the near future? Are there any known workarounds? Thanks!

**Comment by arkadywtf** [comment]
I think a workaround for this would be copying `processSending` method from MassEmail class to a custom directory and modifying a threshold value:
https://github.com/espocrm/espocrm/blob/3e6bc02256914a583292f7a3e7b94d0e6db61817/application/Espo/Modules/Crm/Services/MassEmail.php#L267

**Comment by yurikuzn** [comment]
Parameter max number per batch: https://github.com/espocrm/espocrm/issues/2930

**Comment by rabiibrahimi** [comment]
I think it would be even better to add some configuration to the mass email e.g sending days (users can select which days the mass email should sending emails) and timespan when to send email e.g between 8 am and 6 pm only Tuesday. 

This would really enhance the campaign management as sometimes you want to schedule campaigns to be sent in different times to serve different puposes.

**Comment by yurikuzn** [comment]
But we have Start Date in the Mass Email. This should be enough for define when to send.

**Comment by rabiibrahimi** [comment]
Yes but when sending mass emails you wouldn't want to send emails during weekend e.g so it would be nice to add this options to choose which dates to send emails through and time also.

**Comment by yurikuzn** [comment]
For all mass emails in the system it's possible with crontab notation for the scheduled job: `10,30,50 * * * 1-6`.
