### ISSUE TITLE
Width and Height of the navlinks are sometimes zero

### ISSUE THREAD

**Issue by Tahngarth90** [espocrm/espocrm#665]
Hello dear community. 
Iam using Mozilla Firefox 56.0.1 (64-Bit) and saw, that the navlinks were not shown. So I've pressed F12 to look up, if the navlinks in the ESPO crm are still in the code or not.

As I could see, the navlinks are in the code but the width and also the height of them is zero.
Furthermore I've tested the crm in Microsoft Edge and Google Chrome, where this issue wasn't caused. 

What could cause this issue?
Thank you in advance.

PS: In the user preferences, the custom menu checkbox is unchecked.

**Comment by yurikuzn** [comment]
Please let us know if the issue still persists.
