### ISSUE TITLE
Layout manager UI issue

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#668]
When moving things in the Layout Manager, there seems to be a bug related to removing and adding fields from a panel. If a field is expanded to be full width and you remove it by deleting a whole sub-panel before trying to add it back, it will be fullwidth even if you drag it into a half width box. As a result, the UI will get messed up.

You can avoid the issue by first removing the field from the sub-panel. After doing it that way, adding it into another sub-panel as half or full width will work as expected.

[Video of issue](https://www.youtube.com/watch?v=N-YcdmMHof0)

This always happens to me in Chrome. I haven't checked other browsers.

**Comment by yurikuzn** [comment]
Thank you for reporting. Here is the fix: https://github.com/espocrm/espocrm/commit/987b838856dd94d2516883f6ade67d15d78e00f9.
