### ISSUE TITLE
delete or add a field in the address field of contacts screen

### ISSUE THREAD

**Issue by josephballester** [espocrm/espocrm#67]
In the contact input screen is a field named Address.  Using the layout manager under the contact tab, i can see only the Address Field. But when i try to create a new contact, i can see Streee, City, State, Postal Code and Country Fields.

![addressfield](https://cloud.githubusercontent.com/assets/12039062/11002635/60e6d30e-8484-11e5-8735-f3e9d8493c69.jpg)

How i can add, change or edit the content of address field or content or whatever it si.

**Comment by yurikuzn** [comment]
It's not supported. You need customize files.
