### ISSUE TITLE
Foreign field: Supporting Date and DateTime types

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#671]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/08da60b1b0337515be0efb39fe5fe3da6bf40751

**Comment by ayman-alkom** [comment]
I wonder if we can support the image field  type too

**Comment by yurikuzn** [comment]
Image is already a foreign. It will be foreign of foreign. Tricky.
