### ISSUE TITLE
Fetching Emails of ALL users

### ISSUE THREAD

**Issue by shahzadsrhives** [espocrm/espocrm#674]
Hello Espo Team,

Here is a bug in email module, when i click  on 'All' tab , CRM fetch all emails even those emails which are linked with other user.
Should be just current logged in user emails.

**Comment by yurikuzn** [comment]
Hi,

It's not a bug. You should configure roles for users to restrict them access to emails of other users.

**Comment by shahzadsrhives** [comment]
Thanks For reply.

**Comment by yurikuzn** [comment]
There is also ACL Strict Mode in Administration settings. It disables an access by default for regular users.

**Comment by shahzadsrhives** [comment]
not fixed this issue with Roles.
that's a bug , i have created roles and applied permissions on (email Read = 'own', created='own', Edit= 'own', Delete = 'own') for specific user but still i can see other users emails in email module when i click on 'All' option.
Thanks

**Comment by shahzadsrhives** [comment]
and also ACL Strict Mode is checked from Administration settings but still issue
.

**Comment by yurikuzn** [comment]
I tested and it works. Maybe that emails are related to user somehow.
