### ISSUE TITLE
Missing side panel icons

### ISSUE THREAD

**Issue by shahzadsrhives** [espocrm/espocrm#675]
Hello Everyone,
     I hope you are doing well, Actually i have perform upgrade from 4.0.0 to 4.8.3 and after that facing a issue with side panel, i have selected "Espo W/Side panel" theme from admin but crm missing side panel icons.Can you you specify that if i am missing some thing.

Before update 

![icons](https://user-images.githubusercontent.com/30517681/32209816-17db136c-be2c-11e7-8065-24a1a7353520.PNG)

After upgrade

![image](https://user-images.githubusercontent.com/30517681/32209645-0f17c6e0-be2b-11e7-84f5-315bc1a04925.png)

Thanks

**Comment by yurikuzn** [comment]
Hi,

You have some 3rd party customization. EsporCRM haven't had icons ever.
