### ISSUE TITLE
Bad server response on Knowledge Base detail view

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#676]
I upgraded from 4.8.2 to 4.8.3 a few minutes ago and I started seeing errors in the Knowledge Base. I'm not sure if there are errors in other places, but I'm definitely seeing them there. I noticed there are no longer teams associated with my KB articles and there should be. Here's what I see in the Chrome debugger when I try to open a KB article:

![image](https://user-images.githubusercontent.com/1170415/32307133-88e8318e-bf44-11e7-856d-37884c2cc8f0.png)

Note: the article successfully opens, but it looks like the ACL is no longer being applied as other users can see articles that aren't assigned to them.

Maybe I accidentally messed something up in my installation, but it started very recently, so it seems like it was caused by the upgrade.

The articles do successfully load, but there are now ellipses ("...") in several fields: categories, portals, and teams.

![image](https://user-images.githubusercontent.com/1170415/32307429-00582818-bf46-11e7-86cb-e22537f9131e.png)

**Comment by bandtank** [comment]
It's coming from `client/src/app.js`:

```
$(document).ajaxError(function (event, xhr, options) {
    if (xhr.errorIsHandled) {
        return;
    }
    var statusReason = xhr.getResponseHeader('X-Status-Reason');

    switch (xhr.status) {
        case 0:
            if (xhr.statusText == 'timeout') {
                Espo.Ui.error(self.language.translate('Timeout'));
            }
            break;
        case 200:
            Espo.Ui.error(self.language.translate('Bad server response'));
            console.error('Bad server response: ' + xhr.responseText);
            break;
        case 401:
            if (!options.login) {
                if (self.auth) {
                    self.logout();
                } else {
                    Espo.Ui.error(self.language.translate('Auth error'));
                }
            }
            break;
        case 403:
            if (options.main) {
                self.baseController.error403();
            } else {
                var msg = self.language.translate('Error') + ' ' + xhr.status;
                msg += ': ' + self.language.translate('Access denied');
                Espo.Ui.error(msg);
            }
            break;
        case 404:
            if (options.main) {
                self.baseController.error404();
            } else {
                var msg = self.language.translate('Error') + ' ' + xhr.status;
                msg += ': ' + self.language.translate('Not found');
                Espo.Ui.error(msg);
            }
            break;
        default:
            var msg = self.language.translate('Error') + ' ' + xhr.status;
            if (statusReason) {
                msg += ': ' + statusReason;
            }
            Espo.Ui.error(msg);
    }

    if (statusReason) {
        console.error('Server side error '+xhr.status+': ' + statusReason);
    }
});
```

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/c8089bfc32b7452c978e1d3d6fffef1f31f48e4b
