### ISSUE TITLE
Issues with time in my timezone

### ISSUE THREAD

**Issue by emillod** [espocrm/espocrm#679]
Hello,
I'm from Poland. I also define correct my timezone in settings, but when i'm adding something from API i have wrong hour.
Now i added new task - 22:24, in espo i have 21:24, but time of create task i have correct - 22:24.
I also check time in my server - everything correct. Something wrong in script? I don't know. Any ideas?

**Comment by yurikuzn** [comment]
Hi,

Backend operates with UTC datetimes. So you need to convert to UTC
