### ISSUE TITLE
Bounced status Not working in email campaigns

### ISSUE THREAD

**Issue by shahzadsrhives** [espocrm/espocrm#683]
Hello support,
   i am using 4.8.3 EspoCRM .
I have configured my email on EspoCRM (outbound, preferences, personal account) and also configured cron job, 

1:  I can see my email campaigns status like open, sent but can't see about bounced email status on right sidebar of campaigns.

2: one thing is, i am running campaigns.  when i create campaign and after that setup mass email then by default EspoCRM set sending email (From Email) as i configured in outbound email. If i am sending campaigns with that configured email (outbound configured email) then campaign delivered but if i am using other email address as i configured in preferences (configured email different from outbound email) then i will sent test email and EspoCRM showing success popup but email can't delivered.

Please correct me if i am missing some thing in configuration or that's a bug in our CRM.

Thanks

**Comment by yurikuzn** [comment]
Hi,

1. Bounced can be caught if there is a Group Email Account that monitors mailbox from which emails are sent.

2. It depends on your SMTP server whether it support using different email address or not. In future we will implement an ability to send from different SMTP.

**Comment by shahzadsrhives** [comment]
Hi,

1: I have configured group email account but still not updated bounced option at campaign status bar.

2: We send campaigns email through same smtp just changed email account in from field.

e.g when i create mass email in campaign then auto selected **From Address** field value which email address is outbound configured email.if i replace this email with my preferences email then email not sent.
You can see attached image .its explain what i am saying.

![campaigns_issue](https://user-images.githubusercontent.com/30517681/32647262-26bb2cb2-c612-11e7-9d56-59083ce435c0.png)

**Comment by yurikuzn** [comment]
2. It depends on your SMTP server whether it allows using different email address or not. In future we will implement an ability to send from different SMTP.

**Comment by shahzadsrhives** [comment]
Thanks yurikuzn,
But my 1 point is still pending.so can guide me accordingly ?

**Comment by yurikuzn** [comment]
I don't know what the cause. Can you provide bounced email content?

**Comment by shahzadsrhives** [comment]
Original Message Headers
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=NETORGFT1945665.onmicrosoft.com; s=selector1-legitclaims-co-uk;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version;
 bh=Wmip4LLqkf08NeJZVbSmlP9TfJvI/ZLoZ1bPl4pNwlY=;
 b=OvqTmV+Z7PKZSYYiqUCe9g1/MbKKuJ5QFPFVxer/9TrRH0RcDAc9EWmRrXjssGiTfCuK3z967CSQICRe9bOai5AjB6hHTnriZ+DsYuV695G1oSQJPYIgI0cgACzXwfpkRWCQLHIgSnOJIBkMz5+j1r3wnA2vwKD025DS7GGOIHw=
Authentication-Results: spf=none (sender IP is )
 smtp.mailfrom=example@outlook.com; 
Received: from admin (18.220.103.184) by
 VI1PR0501MB2416.eurprd05.prod.outlook.com (2603:10a6:800:67::20) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256) id 15.20.197.13; Fri, 10
 Nov 2017 12:15:31 +0000
Date: Fri, 10 Nov 2017 12:15:05 +0000
From: =?UTF-8?Q?Shehryar=20Shaukut?= <example@outlook.com>
Sender: <example@outlook.com>
To: reciever@outlook.com
Subject: =?UTF-8?Q?Respected=20Mr=20Crofts:=20Looking=20forward=20to=20your=20?=
 =?UTF-8?Q?response=20on=20the=20offer=20from=20Legit=20Claims?=
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_31deb4c8746eae0a68a0161cdef7090a"
Message-ID: <Lead/591ebbda84df709d4/1510316105/5246@espo>
X-Originating-IP: [18.220.103.184]
X-ClientProxiedBy: CY4PR20CA0010.namprd20.prod.outlook.com
 (2603:10b6:903:98::20) To VI1PR0501MB2416.eurprd05.prod.outlook.com
 (2603:10a6:800:67::20)
Return-Path: shehryar.shaukut@legitclaims.co.uk
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: ab60a8c9-89c4-4c7c-fa74-08d52834bcf7
X-Microsoft-Antispam:
	UriScan:;BCL:0;PCL:0;RULEID:(22001)(4534020)(4602075)(4603075)(4627115)(201702281549075)(2017052603258);SRVR:VI1PR0501MB2416;
X-Microsoft-Exchange-Diagnostics:
	1;VI1PR0501MB2416;3:4bsrQSAivaX7xNH7mTYEq0MH4aj/0baQjZByHTSPkSRg9Tj4mmoeFW/OBwEP0+BfDPFMUqMyN1O4hQ5eeKEy0agtG8gOhwRVf+IRnKg+zCZC0ozYYqIj1zjmk7ZlIN3br9yvdKSIoQ3SPPxKxs2+JPf2/ACw2PpOVvQ1dcLaK2Xv5lsOCzVbJsMEWgvbWAmBjR8Cx+NxYU+dkjQlzFuOKctUTKR3BDisD/u6OD9zYnpAhiLXKmED2/IhlNu4xbcc;25:hDYuDw9chM6ZdFGTPhV/w0ksjo6xpIvu0GtzkHdnPx5wJDHJ1AxZXbZFj7G6yjidnVYwHAn2HVeleOFlpdPYPA6jsfKrOu91+SfYB5ZhF2SJpM5CTb3Tl+O10KajUsTZdGQdhIQpUMOga50bbEftzxaKYLWFEo0Opf7Fd6CsRo61lC0cksPF+gtkf0LfAq6/3DeYr0GoGH2lhGGYqZ8v2zN1zHzzUbPcN2iB7f4cSf6PKebCBqDkn4rChRrzPFXE/y64Ebg+VRW5zK6erEq1qhtTct8Xjk9vwLAAMG9v3IQntzja0fWDysa+FpwjVG2MvWn29brHn1TYhMIB7P0llnFGiVo6NCK/W+tfAqqezU4=;31:OO71StIhhynEFuc4DbuwflSlSvnORUvS3k92bjORPbDmQi88q98CefYksx9FPD632RJIC1wJdnLNuMDd/iWng+/08GeXZKAdn+jgOJzxOBMhNlks0VKOzmgpAqRAhHG4MJHwieLqP+LYWun+JRf+4rTvxDEPIOZ58hBefQj2lBZ//YFtwG6CKCQ+NY+VF+NQaxDQ4JDZRu1SP3CJEtBfGzHZzUMHO01Mefsz9S3/8E8=
X-MS-TrafficTypeDiagnostic: VI1PR0501MB2416:
X-Exchange-Antispam-Report-Test: UriScan:;
X-Microsoft-Antispam-PRVS:
	<VI1PR0501MB2416B7F962B482B546F4F35CC7540@VI1PR0501MB2416.eurprd05.prod.outlook.com>
X-Exchange-Antispam-Report-CFA-Test:
	BCL:0;PCL:0;RULEID:(100000700101)(100105000095)(100000701101)(100105300095)(100000702101)(100105100095)(6040450)(2401047)(8121501046)(5005006)(93006095)(93001095)(3231021)(100000703101)(100105400095)(3002001)(10201501046)(6041248)(20161123564025)(20161123558100)(20161123555025)(201703131423075)(201703061421075)(20161123562025)(20161123560025)(2016111802025)(6043046)(6072148)(201708071742011)(100000704101)(100105200095)(100000705101)(100105500095);SRVR:VI1PR0501MB2416;BCL:0;PCL:0;RULEID:(100000800101)(100110000095)(100000801101)(100110300095)(100000802101)(100110100095)(100000803101)(100110400095)(100000804101)(100110200095)(100000805101)(100110500095);SRVR:VI1PR0501MB2416;
X-Microsoft-Exchange-Diagnostics:
	1;VI1PR0501MB2416;4:Sr2bhwLpjgW1eR0IBC+xZJdZ9x8i8slFZqp/09vvw0X7jfx6U2Ih7DKwTG9m8BonnxJAf9RM5PRFo3+dRkWZH2Ch5Zw46zyu0xhUDfuCAM3XncbWJSHHAHvJdMF4GjJxm/DvpLoXM1ZZVwWWAwvJUFCsGUjb6Kip0nujX0gjOU37NICSxkGAcP1xGwc+HKvQ6mXSSgZ+xOr5qFYvetIaEzavOao1uTSkSfCcWsGpcx4vncmjokNKVjxToGeyIZvtfHhztRyXRPziYBZVUN0iRA==
X-Forefront-PRVS: 0487C0DB7E
X-Forefront-Antispam-Report:
	SFV:NSPM;SFS:(10009020)(7916004)(376002)(346002)(189002)(199003)(53936002)(66066001)(105586002)(8656006)(606006)(50986999)(74482002)(16586007)(9686003)(84326002)(2351001)(6496005)(8676002)(19619215002)(508600001)(81166006)(236005)(25786009)(81156014)(8936002)(6306002)(305945005)(5660300001)(5890100001)(86362001)(3846002)(54356999)(6392003)(7846003)(7736002)(733005)(33716001)(6116002)(68736007)(6486002)(42882006)(2361001)(106356001)(15974865002)(97736004)(861006)(2906002)(6666003)(6916009)(16526018)(966005)(101416001)(413944005)(189998001)(105646017)(14444003);DIR:OUT;SFP:1101;SCL:1;SRVR:VI1PR0501MB2416;H:admin;FPR:;SPF:None;PTR:InfoNoRecords;MX:1;A:1;LANG:en;
Received-SPF: None (protection.outlook.com: legitclaims.co.uk does not
 designate permitted sender hosts)
X-Microsoft-Exchange-Diagnostics:
	=?us-ascii?Q?1;VI1PR0501MB2416;23:V5/5suDrzMmZvTGvbt2rUFhICCV2QM5oLL/7ktH?=
 =?us-ascii?Q?/n9Lop8lX9AEsIiw402U1IYIv6dSXCv0ob15urc9hgVH7zkIRWqybvAMKRDd?=
 =?us-ascii?Q?X39gIJ8c9XsXy+I9EQDTDNz/gjI+1j+hnrNM7NnFGQ9PSBCKFHnf0Ie73S+V?=
 =?us-ascii?Q?SAFnGPwzkEQvlq6JNe/7qSo83+i+4+En1KA2QoXwrUv530JMdKASajSEJoJP?=
 =?us-ascii?Q?WlNofFE5w5925eXbM0amRwJBL2Dwa+pxQyifno/IuP/pRTyHIUtTOCwywAV/?=
 =?us-ascii?Q?9hTFaewltfAsN0o1LFoJOFJQbJZURdUN3/GmM7lhK5Iq1FMWAVmAx4VJxRGh?=
 =?us-ascii?Q?mU2rv9boJPcPeB5P5kBfcg8EaBY3Qn2qA8riEeJXYkoR6JZS0qxuS5L29S48?=
 =?us-ascii?Q?/zKXYjtQaJ1RddoV4DcXS50PujN34Y/rVzq3v+pmVgHSxf+A/74SuXMP+KUZ?=
 =?us-ascii?Q?lbe9NkDkM6DEP+5IrnKZnwqgWARrAoDs40SfwuIAheX3Ve2WbcUxcgzY052c?=
 =?us-ascii?Q?ujGbl8I43847eFtpaA6X4aJcUbRL9gP8MgIjFzcZQUSA+76nPcgztoVVAVSn?=
 =?us-ascii?Q?sr35gTvhIIO2Q9zyrGF3sa+fmPAg8l5PmgO6TK6xQ49E/Wd4u7mc/whuPWvI?=
 =?us-ascii?Q?jm+SQb1XofsTBAnP9vECwZzWowXurLqJ0lw0s1IdpZ3btLCL+WIG8iB5xhqq?=
 =?us-ascii?Q?91TS429xbBGreQm8uOkLXLkjq+i2sRbPphNeHReybKfDb5T78GVEEjOXwQCl?=
 =?us-ascii?Q?t838HlQAanzdQ/XermrYzp8mVbEeJwckaBTVN7+/oecTPyFy2gqTM86d4cYE?=
 =?us-ascii?Q?NSSLc2fEZ6L2+lzrHAc9eIm5fgBwiw12kutPpq0BkWXT5I9xosinz79VTMxq?=
 =?us-ascii?Q?QshcNOm60QiPrnpS0v09ecZ6pTRUq4ihbJHq6SRg5sfexQOcLLYcFwB9ny6n?=
 =?us-ascii?Q?OufaUKK0KTXi6N9KcEWOZ3AoLaSsKbC+QPpIbcJZFbia16XzSfRB0w0mIpp/?=
 =?us-ascii?Q?4pL3SaZi+7Q+QhECtTMbMZhNKCkynELjV6l+c9ZFRNIqZlLldILCCAZy6T+H?=
 =?us-ascii?Q?4zw532K3Yk7AfXYGrZpLf1TiOkJkIu/CW60Lf3Q2Bb7Au+oPz2qyVR5lpEYM?=
 =?us-ascii?Q?BQV7kmcqzdnSkhbSNP6AhPx1J/jQ42xgxl/WhnP2hRaw01rIQMmnUln6aPr0?=
 =?us-ascii?Q?WvXnruARIrSwmh9fPP64Lav7d5GZa6OzMcZ/K25BZvLVVKvE7EPHcYhwKqYy?=
 =?us-ascii?Q?Ng7oGg1zGyvVRrH9KCLHR+3MbLJbl993xqXKSWCds?=
X-Microsoft-Exchange-Diagnostics:
	1;VI1PR0501MB2416;6:oSp/thnputyWG5iB2D/xZzhQYUjXbrBYAvCnCPgRXssgvcVSBEV2ckjEbxJDncGWWhggCEq+iECDx/fuBiPQsevsRGzqbtwX9Z9oVi1vRd1IkQwyZSDQTXJ1FxMdDPpMYW+glmil6X8nlmxdzHhXUodkAQ5LqcDkFCBdfFqXTqUaWb31B2GhkY7RSzzhID9ANVTXHvkeZOGhLEWyKJ3he70K6ijsiah3Op/sG05TR5M3DsSNtPwXWbP8CRBwBcjiH3M8vW7FLtqtR12w/iiwEQ8eoUer0Lxwa+RQrLWiynpt6ZsSwjNFX5PIx9gDy3zG0YiO1Mxz5j9iLlGmXcOKx4hIQbF09RFQ9hk+otakaVg=;5:7yvBzMGF839s9cH+sNMuAJ0q8Qx/wDPypMrf10z6aTqrWm5BDtWX3TAptiNR0vCulifzBIC3kBqoTxkLxZ7tnmx7CPDoIyTfHkutWpFjXlazjwswucWDrigtxYfqQaPTZL9PCy/5Nfsy/n4+FnevOf16hgAa9hlYOIJ4M7JZAQs=;24:5eJhnhk4HCQ+kXpPesnQyb8pyUL9ARvJCpcVJ3Ae7vk6EbFCl2ylmCyqshbgVv+UeGqyXg1JubBZwMxD83RMy8HSIL4JClBpvBCCXrf9n+Q=;7:oSxT9DQ0BmtNya3GulRtvi77GbmpyXwxiBDA53RLskDk92L0+PGjhBjKOYioTiUjj5P4JjFVvEDONHC85zDbOO3H9Zj7mgcyuLImagkXn24hLOnHTJTH+Qlgh20Pq/fKb9Xt0IP/dVSoLCrthCrb2Mjs6PwVuLHd6wNyrERlVeFS1BUsh/3L2KkNui4V7UorzYz0mlWt2CIpf95G+/XU7TlkYDHDaCU7RLPiT1dqF2xygfEli/zEzk5rrayhSNsr
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
X-OriginatorOrg: legitclaims.co.uk
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 10 Nov 2017 12:15:31.0790 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id:
	ab60a8c9-89c4-4c7c-fa74-08d52834bcf7
X-MS-Exchange-CrossTenant-FromEntityHeader: Hosted
X-MS-Exchange-CrossTenant-Id: a187c6f9-8bcc-4f76-959a-4f01f429b90c
X-MS-Exchange-Transport-CrossTenantHeadersStamped: VI1PR0501MB2416

**Comment by yurikuzn** [comment]
Could you attach it as file please.

**Comment by yurikuzn** [comment]
Here is the place where bounced message detected: https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/InboundEmail.php#L313

Here is where processed: https://github.com/espocrm/espocrm/blob/master/application/Espo/Services/InboundEmail.php#L674

Seems email you provided doesn't match conditions to be parsed as a bounced.

**Comment by yurikuzn** [comment]
Also it doesn't contain X-QueueItemId header that is used to correspond bounced email with the sent email.

**Comment by shahzadsrhives** [comment]
can you guide me how we configure this id in our crm ?

**Comment by yurikuzn** [comment]
It should be in email response. But email that you provided seems to be standard bounced email. I don't know how to handle this.

**Comment by shahzadsrhives** [comment]
Thanks for reply

**Comment by yurikuzn** [comment]
I corrected myself: " email that you provided seems to be not a standard bounced email".

**Comment by beppe9000** [comment]
#1560 should solve this
