### ISSUE TITLE
change Stream title to Comment

### ISSUE THREAD

**Issue by josephballester** [espocrm/espocrm#69]
The module where a person post a comment with any attachment has a title named STREAM.
Can i change that word (STREAM) to COMMENT?

Thanks.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/i18n/en_US/Global.json

Change Stream to Comment there.

**Comment by josephballester** [comment]
already change it but still showind the word STREAM. I make it using jsoneditoronline.org.

What im doing wrong.

**Comment by yurikuzn** [comment]
Clear Cache.
