### ISSUE TITLE
Refused to execute script from ...

### ISSUE THREAD

**Issue by mrbinr** [espocrm/espocrm#697]
Hello,
After installtion, when i start espocrm i have a blank page with only the footer displayed and in firebug this error : 

`Refused to execute script from 'http://my_domain/client/espo.min.js?r=1510692890' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Maybe something wrong in my configuration ?
I'm using php-fpm 5..6 with nginx 1.10.3

Thanks 
Best Regards 
Pascall

**Comment by yurikuzn** [comment]
Hi Pascall,

This can be file permissions issue https://github.com/espocrm/documentation/blob/master/administration/server-configuration.md#required-permissions-for-unix-based-systems

For such types of issues it's better to ask for help on our forum: http://forum.espocrm.com/

**Comment by mrbinr** [comment]
Hi,
I think it's not a permission issue because i have seen ```espo.min.js``` was missing in ```client``` folder
so i've launch grunt again and then client folder was still the same, so i've renamed it and create symbolic link from ```folder build/EspoCRM-4.8.4/client/``` in which ```espo.min.js``` was present, to ```client/``` and voilà, login page appears.

Strange think ...

**Comment by yurikuzn** [comment]
I'd recommend to install the stable version from https://www.espocrm.com/download/. Did you try it?

**Comment by mrbinr** [comment]
Stable version isn't 4.8.4 ? if yes, it's the version which i'm using...

**Comment by mrbinr** [comment]
Ok i've download version in link above and it works, but previous behaviour is strange.

Thanks for your help.
Best Regards
Pascall
