### ISSUE TITLE
Preset filters not working in IE

### ISSUE THREAD

**Issue by Jacobite89** [espocrm/espocrm#701]
When selecting a E-Mail Template there is following error in the Console from IE11.

Object doesn't support property or method 'find'
File: eval code (269), Row: 112, Colum: 17

wich is following part:
```
if (this.presetName) {
	var hasPresetListed = this.presetFilterList.find(function (item) {
		var name = (typeof item === 'string') ? item : item.name;
		if (name === this.presetName) {
			return true;
		}
	}, this);
	if (!hasPresetListed) {
		this.presetFilterList.push(this.presetName);
	}
}
```

**Comment by yurikuzn** [comment]
Hi,
Do you have any customization done for Email Templates?

**Comment by Jacobite89** [comment]
added only e-mail templates and for now i comment out this part.

according to this page the IE doesn't support this method
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility

**Comment by yurikuzn** [comment]
I forgot, We don't support IE browser.
