### ISSUE TITLE
upgrade installed correctly but 404 page not found occur

### ISSUE THREAD

**Issue by josephballester** [espocrm/espocrm#71]
I just upgrade from 7.4. to 8.  Everything works great.  Upgrade completed successfully, but when accesing the page this happen....

![2015-11-24_101656](https://cloud.githubusercontent.com/assets/12039062/11369274/6c3a9e02-9294-11e5-98fe-1d27b6c0a2d7.jpg)

Already clean the cache.   I commit the biggest mistake.  Dont run a backup.

**Comment by yurikuzn** [comment]
It's just a file permission issue. check permissions of index.php,
