### ISSUE TITLE
Improvement in the graphic representation of checkboxes

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#714]
This is just a suggestion.

I find it interesting that the current checkboxes are changed by some version of switchs / toggles / etc.

Not only to improve the user interface, but also the user experience because the checkboxes are very small and requires much precision to activate or deactivate them.

Attached some images

Regards!

![usuarios del portal](https://user-images.githubusercontent.com/110789/33241885-bdf44eac-d2aa-11e7-8441-48fe7a110757.png)

![edit user](https://user-images.githubusercontent.com/110789/33241904-2d7bf22a-d2ab-11e7-970b-8f04fe08913e.png)

**Comment by bandtank** [comment]
Some of my users have a hard time clicking the checkboxes as well. It's partially because they're incompetent and partially because they can't see very well. Larger boxes would be a good improvement in UX if done correctly.

**Comment by yurikuzn** [comment]
We will need translations of On/Off for all supported languages.

**Comment by loreahlie11** [comment]
I would love inline checkboxes.  The checkbox underneath the text is confusing for users when there are several in a row.  I've tried to modify the styling by modifying css, but adding a class to the element seems to break the forms.  I can get it to look great, but it also disables saving. 

Perhaps instead of text a check icon?

**Comment by PanuWeb** [comment]
@yurikuzn Yes I know. It is very difficult to translate that.

**Comment by bandtank** [comment]
@loreahlie11 I've had similar issues with users getting confused. I worked around that by making things easy to understand via Layout Manager.

How do we submit translations?

**Comment by yurikuzn** [comment]
We have an account on poeditor where people can contribute to translations: https://poeditor.com/join/project/gLDKZtUF4i

**Comment by yurikuzn** [comment]
Or opt to not to use on/off captions like iOS does:
![ios7_switches](https://user-images.githubusercontent.com/1006792/35531408-9123deca-053f-11e8-86f2-60466fc8bcfe.png)

**Comment by bandtank** [comment]
@yurikuzn I like that idea a lot, actually. It's clear and ubiquitous. It's also less work to implement.

**Comment by PanuWeb** [comment]
It is a good idea.

I think the biggest problem with translating the titles "on/off" is that they change their meaning according to the context. Or so it is in Spanish, at least.

@yurikuzn and in the list how would you show them?

**Comment by yurikuzn** [comment]
Not sure how to display in detail and list views.

**Comment by yurikuzn** [comment]
Regarding detail/list views:

* Texts on/off/yes/no can be inappropriate in a certain context, as @PanuWeb mentioned. 
* Using the same switch, like on edit view, will make users want to click it.

**Comment by bandtank** [comment]
I don't think it's any more or less likely to be clicked than a checkbox. People are familiar with toggle switches like that in GUIs at this point.

**Comment by PanuWeb** [comment]
Anyway, a checkbox is currently shown in list or detail mode (in gray), which sometimes users also try to click.

Another important point in terms of accessibility is the red/green (off/on) colors since people with color blindness often confuse these colors.

**Comment by yurikuzn** [comment]
Improved in v7.3.
