### ISSUE TITLE
New feature - email planner

### ISSUE THREAD

**Issue by buzzard10** [espocrm/espocrm#718]
It would be great if you implement some feature to plan emails. For example i'll create some e-mail for client and plan sending for another day/hour :)

**Comment by PanuWeb** [comment]
Yes, very usefull. I posted same in [http://forum.espocrm.com/forum/feature-requests/9062-possibility-of-deferring-sending-emails](http://forum.espocrm.com/forum/feature-requests/9062-possibility-of-deferring-sending-emails)

**Comment by emillod** [comment]
@PanuWeb thanks! 
They already have something like "create archive e-mail" with date and etc, co maybe they can create this function in short time
