### ISSUE TITLE
Documents: "Move to folder" in actions menu

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#723]
![documentos](https://user-images.githubusercontent.com/110789/33409355-ce241698-d559-11e7-8d9c-b80d440f34b1.png)

**Comment by yurikuzn** [comment]
It's possible to use mass update.

**Comment by PanuWeb** [comment]
Uuu! I changed 20 documents one by one. Hahaha. I'm sorry and thank you!
