### ISSUE TITLE
Entity manager: Add link to go back en titile path

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#729]
![1011a](https://user-images.githubusercontent.com/110789/33529189-d57e2984-d84b-11e7-8f00-10d0d78e85f6.png)
![1011b](https://user-images.githubusercontent.com/110789/33529190-d59fd05c-d84b-11e7-88f6-63421d052e5d.png)

**Comment by yurikuzn** [comment]
There is no such a url.

**Comment by PanuWeb** [comment]
You're right, but then the field edit form can appear in a pop-up window like when you edit relationships:

![entidades](https://user-images.githubusercontent.com/110789/33529705-68a6d61e-d853-11e7-84a0-50463f4e2df2.png)

**Comment by yurikuzn** [comment]
Maybe this is a good option.  I have hundreds of TODOs for EspoCRM with much higher priority. Not sure when I get time for this.

**Comment by PanuWeb** [comment]
No problem! It happens to me that I can not dedicate all the time I would
like to collaborate (as to solve it on my own) so I just leave these issues.

When they can, they solve it. Neither is life or death, just that these
days I was making many changes in the entity manager and it was tedious to
go to the "back" button of the browser to return, or return to the
administrator and enter back to the end.

Regards!

Mauricio Panuncio
Te. +54 03404 15508109
Sarmiento 1798 (S3013CUJ)
San Carlos Centro - Santa Fe - Argentina
m@panuweb.com
panuweb.com

2017-12-04 3:34 GMT-03:00 Yuri Kuznetsov <notifications@github.com>:
