### ISSUE TITLE
Using objects for controller actions data instead of associative array

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#733]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/939ead833cd2308153af6c3228777eaa3da50d07

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/4a3a13414bb1cb640ffe247758e66d94db8d0fd7

**Comment by bandtank** [comment]
Does this change custom controller actions? I use custom actions and I'm not sure if this commit will cause my current actions to need to switch to associate arrays.

**Comment by yurikuzn** [comment]
Yes. You will need to switch from associative array to objects. Or add `$data = get_object_vars($data);`

**Comment by bandtank** [comment]
Thanks

**Comment by yurikuzn** [comment]
We added `if (is_object($data)) $data = get_object_vars($data);`  to the first line of action methods we would like to have backward and forward compatibility.

**Comment by bandtank** [comment]
Is this right?
```
 9   public function postActionData($params, $data, $request) {
10     if(is_object($data)) {
11       $data = get_object_vars($data);
12     }
13     ...
14   }
```

**Comment by yurikuzn** [comment]
Yes.
