### ISSUE TITLE
LDAP support for hierachies

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#74]
We tested the LDAP support (against MS Active Directory) and found some limitations which prevent us from using this feature in real live. Maybe it is a misconfig/misunderstanding from my side - maybe the functionallity is not yet implemented as we expect. We only get it running if the users are stored in the same ou.

# User name
username attribute should be configurable (e.g. for Active Directory it is samAccountName not CN)

# tree search
at the moment the user search and bind for the end user for auth is done in the base DN only but most organisations have their users in a tree of OUs. I tried to work around this restriction by switching from Account Canonical Form=Dn to Principal but I was not able to succesfully authenticate as user principle name (e.g. paul.smith@mycompany.lan)
So either Espo requires to search for the user first or we need to get the principal auth working

# Login Filter by group membership
It is quite uncommon to expect special attributes on the user objects for filtering allowed users. Best practice is using group memberships (object: grouOfNames attirbutes on user object: memberOf). Is there a way to configre this?

# Enhancements
Another nice feature (but not that urgent): sync users, groups and group memberships from LDAP
Users should have an unique external attribute to be used as foreign key to sync with (e.g.SID or employeeID)

**Comment by tmachyshyn** [comment]
Yes, it can be implemented if you provide an expert in MS Active Directory. Because most of tests have been made on OpenLDAP.

**Comment by hi-ko** [comment]
Excellent. Let's work in it. I've no PHP skills but can providence everything you need from MS AD and samba4 AD. Yuri has my contact details.

**Comment by hi-ko** [comment]
OK partly solved it for myself:

- Username issue is fixed by #159
- Treesearch is possible by using Principal instead of DN or Username
- Loginfilter works by putting full ldap filter using memberof template (in the example the user has to be member of group A or group B): 

     `(&(objectCategory=Person)(|(memberOf=CN=team1,OU=groups,OU=mycompany,DC=mycompany,DC=intra)(memberOf=CN=team2,OU=groups,OU=mycompany,DC=mycompany,DC=intra)))`

So the ticket can be closed If you accept my pull request and I create a new one focusing on LDAP _Sync_
