### ISSUE TITLE
Throwing an error in custom hook doesn't prevent save in GUI

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#742]
If you create a custom hook that calls the beforeSave event to stop an entity from being saved, it doesn't seem to work unless the entity is new. For example:

```
  8 class NewThing extends \Espo\Core\Hooks\Base
  9 {
 10   public function beforeSave(Entity $entity, array $options = array())
 11   {
 12     if ($entity->isNew()) {
 13       throw new Error("stop here");
 14     } else {
 15       throw new Error("also stop here");
 17     }
 18   }
 19 }
```

When I try to save a new Thing, I see "stop here" in the GUI, the Thing is not created, and the GUI stays in edit mode. That works well. However, if the Thing already exists and now you are trying to modify it, the "also stop here" error will be shown, but the GUI doesn't stay in edit mode; it goes to read mode, which makes it look like the changes were saved. The changes do not save as a result of throwing an error, which I confirmed by looking at the database, but the GUI changing back to read mode is confusing. If an error is thrown, I think the GUI should stay in edit mode until the GUI validation and PHP hook validation pass like what happens when the entity is new.

**Comment by yurikuzn** [comment]
A mode is switched from 'edit' to 'detail' right after Save is clicked, before response is received.  It's possible to catch an error with a handler since this commit: https://github.com/espocrm/espocrm/commit/40414a0f1720e08449eac8c206b6a4ae5f11d77d

**Comment by bandtank** [comment]
Are you saying to throw a new `Conflict` instead of an error to cause the GUI to show the error? I'm not sure I understand. I was hoping there was a way to prevent the switch from 'edit' to 'detail'. Are you saying that isn't possible or that I'm doing it the wrong way?

**Comment by yurikuzn** [comment]
I meant that now it's possble at least catch a Conflict error and run js code like:

```php
 throw new Conflict(json_encode(['reason' => 'someError', 'data'=> $data])); 
```

custom view detail.js:
```js
    errorHandlerDuplicate: function (data) {
        this.setEditMode(); // back to edit mode        
        this.model.set(data.attributes); // set some attributes returned from backend
    }
```

**Comment by bandtank** [comment]
I see what you're saying now. I'll see if I can figure out how to implement this and then I'll post my workarounds in this topic. Thanks.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/edb52e253b90bce3b8da7784f5d3ed3e502079de

**Comment by bandtank** [comment]
@yurikuzn Does your commit cause the form to go back to edit mode if an error is throw from PHP without any custom JS workarounds?

**Comment by yurikuzn** [comment]
Yes. It goes back to edit if save wasn't succeed (Exception thrown).

**Comment by bandtank** [comment]
Awesome. Thanks for implementing this. It will be a huge help.
