### ISSUE TITLE
Colorpicker type isn't an option - why?

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#744]
I noticed a colorpicker type in the [code](https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/metadata/fields/colorpicker.json). Why can't it be created? It would be really useful.

**Comment by yurikuzn** [comment]
There is no way to utilize it w/o an addtional coding. You can enable it by setting notCreatable to false https://github.com/espocrm/espocrm/blob/master/application/Espo/Resources/metadata/fields/colorpicker.json#L26
