### ISSUE TITLE
Various settings - case processing

### ISSUE THREAD

**Issue by Blognase** [espocrm/espocrm#748]
Hello everybody,
if I edit from a case and there click on answers, then the email mask appears where I can enter the answer.

There I can also choose whether the answer should be sent via the personal email address or the group mailbox.

I would like to set the following:
- Sender email address: always the group mailbox
- The field cc should always be empty, I do not want to receive a copy of the email.

Where can I set this accordingly?

Many Thanks!

**Comment by yurikuzn** [comment]
These behaviours are not configurable.

**Comment by yurikuzn** [comment]
At Preferences you can unceck "Email Reply to all by default". But this will be applied only to own user account.

**Comment by yurikuzn** [comment]
For such questions please use our forum: http://forum.espocrm.com/

https://github.com/espocrm/espocrm/blob/master/CONTRIBUTING.md#issues

**Comment by Blognase** [comment]
Since 02.01.2018 I wait for my posts to be shared in the forum at EspoCRM. Unfortunately, three contributions from me have not yet been released.

**Comment by yurikuzn** [comment]
Sorry, our forum moderator is on vacation. Have just approved your post.
