### ISSUE TITLE
Reopen case after email retrieval

### ISSUE THREAD

**Issue by Blognase** [espocrm/espocrm#749]
Hello everybody,

I have the following problem:
If a case has been closed and the customer responds to the e-mail again, then the case remains closed and the system sets the e-mail directly to archive.
How can I stop it from reopening the case? So I need a typical help desk function or an eMail ticket system, wherever an incoming email the case is set to open again.

Many Thanks

**Comment by yurikuzn** [comment]
Hi,

There is no such an option.

**Comment by Blognase** [comment]
And how can I hear when a customer replies to a processed ticket and the damil employee has left?
Or is there an email ticket system which works very well with espo so that I do not have to enter the data twice?

**Comment by Sloff** [comment]
Would this be possible to setup with the new BPM included in the advanced features extension?

**Comment by yurikuzn** [comment]
It's possible with workflow.
