### ISSUE TITLE
Ajax Failed after clicking install

### ISSUE THREAD

**Issue by RichardNY2014** [espocrm/espocrm#75]
![2015-12-19_0753](https://cloud.githubusercontent.com/assets/5921205/11913063/b1f54876-a625-11e5-9271-25890592fd2a.png)

Console log as shown above. All data was entered correctly. But cannot seem to move forward after clicking install. I did some internal debugging on the error above and noticed 

![2015-12-19_0756](https://cloud.githubusercontent.com/assets/5921205/11913079/f8951c5c-a625-11e5-83b6-0421e103e0a7.png)

Not sure if this has anything to do with it.

Thanks guys.

**Comment by RichardNY2014** [comment]
Thank you guys for giving this some attention. However, I have summed it all up to being I needed to create my database initially WITH a `user` table. Now this just would bring me to the next question of how would I know the correct schema for this table?

**Comment by yurikuzn** [comment]
Hi.

If table is created it shoulb be populated with a schema upon installation. If your user permitted of course..

**Comment by Mysticsam** [comment]
I have still this problem. At the database configuration i get "Ajax failed" and i cant move forward.

**Comment by tmachyshyn** [comment]
Please open a web browser console and see what the request returns.
