### ISSUE TITLE
Check Personal Email Accounts scheduled job logging error if there is no any email account

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#757]
When deleting a personal email account the following error keeps displaying in the "Check Personal Email Accounts" scheduled job

![screenshot-2018-1-15 check personal email accounts](https://user-images.githubusercontent.com/7330170/34929689-1035b896-f9ce-11e7-8796-2675a38dcfb7.png)

**Comment by Sloff** [comment]
It seems that deleting and re-adding the scheduled job removes the recurring error message

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/14de81520b8018947a6f4ff344bf1e5da7f66efa
