### ISSUE TITLE
Report 'Columns' doesn't list all entity fields

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#770]
I have an entity called Projects that has the following fields:

```
1435         "projectEngineers": {
1436             "type": "hasMany",
1437             "relationName": "projectEngineers",
1438             "foreign": "projectsEng",
1439             "entity": "User",
1440             "audited": true,
1441             "isCustom": true
1442         },
1443         "projectManagers": {
1444             "type": "hasMany",
1445             "relationName": "projectManagers",
1446             "foreign": "projectMan",
1447             "entity": "User",
1448             "audited": true,
1449             "isCustom": true
1450         },
```

I am trying to build a report that lists the values of that field, but it doesn't work presumably because it is a 'hasMany' relationship. Is there a way to load the values of these fields in the report? Both fields are available in Runtime Filters and Filters, but I need both fields to also be shown in the report as Columns.

I know I may be able to build a custom report to do this, but I can't figure out how to get started with that.

**Comment by yurikuzn** [comment]
Sorry, but this repository is only for out-of-the-box features.  Could you create a topic on the forum.

**Comment by bandtank** [comment]
Yes, I’ll do that. I wasn’t sure if it was a bug.
