### ISSUE TITLE
Reports being sent even when with Empty Data

### ISSUE THREAD

**Issue by rodrigoscoelho** [espocrm/espocrm#771]
Hi, The reports are being sent via email even when without any data (empty). and the option to only send when having information is enabled. 
![image](https://user-images.githubusercontent.com/6912410/35218780-0b980a30-ff57-11e7-86f9-292e02e67e57.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/531#issuecomment-298167857
