### ISSUE TITLE
Suppressing email create dupplicate view and response to "empty email" filters

### ISSUE THREAD

**Issue by vdbemden** [espocrm/espocrm#782]
Hi there, 
I tried recently to add an email address to a user and filter then on remaining empty email adresses.
Surprisingly this last user remained in the "empty email" filter.
After research, i was able to detect that the bug is linked to delete an email.
With the current DB architecture, when an email is deleted, it is marked as deleted in the "email_address" but not in "entity_email_address" .
This leads to the bug i mentioned here above.
Updating the cross table status "deleted" resolved it.

In the same way, deleting email in a contact and adding another leads to bugs. When searching the contact, the displayed total count it twice.

**Comment by yurikuzn** [comment]
Hi,

Is it possible to reproduce the issue using UI?

**Comment by vdbemden** [comment]
Could not reproduce it...
Maybe the 5.0.3 update did the trick, although i don't see any closed issue which could possibly resolve it...
Looking at the db, the line in the cross table is now deleted when I delete the user mail
