### ISSUE TITLE
Report export doesn't seem to work - xlsx and csv files empty

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#785]
Version 5.0.3

I tried to export a report to xlsx and csv as well as via email, none of which worked. The report runs without any issues as seen below. The CSV shown in the same picture is empty except for the worksheet name, which is missing a digit (it should be 2018-01-30), and the word Total in A2. I don't see any errors in the log or console.

![image](https://user-images.githubusercontent.com/1170415/35590167-36f8cbc0-05c3-11e8-984b-732e7db58121.png)

Here is the definition of the report:

![image](https://user-images.githubusercontent.com/1170415/35590210-5bef8888-05c3-11e8-9407-ba1d462ceaaf.png)

Here is the empty email:

![image](https://user-images.githubusercontent.com/1170415/35590264-84af808e-05c3-11e8-9f3f-ff2369de47b6.png)

And here is how the Excel document looks:

![image](https://user-images.githubusercontent.com/1170415/35590316-b06afdc0-05c3-11e8-9ba4-34b0a9a2dac6.png)

**Comment by yurikuzn** [comment]
This repository only for out-of-the-box features. Please use forum or our customer portal.

**Comment by bandtank** [comment]
I'm not sure what you mean. This is an out of the box feature that doesn't work. It's not a custom report and none of the export options work.

**Comment by yurikuzn** [comment]
Advanced Pack is out of scope of this repository. Here is no code of advanced pack.

**Comment by yurikuzn** [comment]
http://forum.espocrm.com/forum/extensions/34287-report-export-doesn-t-seem-to-work-xlsx-and-csv-files-empty
