### ISSUE TITLE
can't create entity after 5.0.4 upgrade

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#787]
I upgraded to 5.0.4 a few minutes ago and I can't create one of my entities. Here's the log:

edit: nevermind - there's nothing in the log that's relevant to this.

Here's the console:

![image](https://user-images.githubusercontent.com/1170415/35689131-0956e22e-0730-11e8-8c18-2ca3afcb850d.png)

**Comment by bandtank** [comment]
![image](https://user-images.githubusercontent.com/1170415/35689837-a068db3a-0731-11e8-804c-abfaa17967c2.png)

**Comment by bandtank** [comment]
I added a debug statement to show this.selected and here is what happened when I loaded the page and then tried to save a new entity. It looks like `[]` isn't a real array for some reason.

![image](https://user-images.githubusercontent.com/1170415/35690512-54c6f2d2-0733-11e8-9b2e-2823a5c86b73.png)

**Comment by bandtank** [comment]
The entity is actually being created correctly, so something is going wrong after it saves. I use custom hooks for this entity and everything is happened as expecting. I used the log to verify that the hook isn't dying unexpectedly. The hook creates a unique number, which populates correctly in the GUI once the project has saved. I also use formulas for this entity and nothing looks wrong there either. I'm a loss. My other entities don't seem to have any issues.

**Comment by yurikuzn** [comment]
Maybe server returns a non-array value. 
https://github.com/espocrm/espocrm/blob/master/client/src/views/fields/array.js#L90

**Comment by bandtank** [comment]
How do I debug this? I'm not sure where to look or what could be wrong. The name of my entity is something like '18-0123-D1' and in the database everything looks good. I had been working on a few other changes to my entities via the GUI (all of my changes were in custom/Espo/Custom/), but I stashed everything and I'm working from 5.0.4 now with no updates or modifications to my entities from 5.0.3. I'm not sure what could be wrong.

**Comment by yurikuzn** [comment]
```
console.log(this.model.get(this.name));
```
right before the line I posted above.

**Comment by bandtank** [comment]
Ok, I found the problem with your advice. You're right - I tried to copy something from one entity to another and for some reason the issue didn't show up until today. I found a column in the database with `[]` as the value and then I found the problem in my hook.

You are a lifesaver Yuri. Thank you so much.
