### ISSUE TITLE
Chat integration

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#790]
Can someone integrate LiveHelperChat like twilio/AMI integration. Having an ability to open new cases based on chats would be pretty cool and useful. Not everyone would want to open support tickets/cases using emails. Some people might want immediate response by the support.

LiveHelperChat is open source chat application
Website: https://livehelperchat.com/
Github: https://github.com/LiveHelperChat/livehelperchat

Features required:
1. Live Helper Chat integration
2. Ability to open cases/support tickets from the chat

**Comment by imbhat** [comment]
Also other CRM's like Zoho/Suite CRM have these kind integration which does a lookup in contacts by email and associates the contact.

**Comment by SandyUala** [comment]
Any update?

**Comment by tomaspar** [comment]
if anyone could do https://help.islonline.com/19804 integration.
