### ISSUE TITLE
Print to PDF for all entity types

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#792]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/5060918087be99b869a8ab4ab32af8d9b3462724

**Comment by emillod** [comment]
@yurikuzn How can i activate this function in espo after update ?

**Comment by yurikuzn** [comment]
It's acrivated. User needs to have an access to Template entity type. If there any template then the action will appear in menu.

**Comment by emillod** [comment]
Now i created template for task here: http://demo.espocrm.de/advanced/
And i don't see any changes in Menu. Can you describe how to assign user to template?

**Comment by cmediade** [comment]
Tryed it with local installation and it works well:
1. updated EspoCRM to 5.0.5
2. clear cache & rebuild
3. update AdvancedPack to 1.30.6
4. clear cache & rebuild
5. create template for own entitiy (localhost/#Template // Quotes / Template)
6. clear cache & rebuild
7. print pdf is available on local entity
7.1 same on contacts or wherever you want. thx a lot!

5.1 > for faster finding: create userdefined menu on your preferences and add templates.

**Comment by emillod** [comment]
Ah so this function is only for AdvancedPack?

**Comment by Sloff** [comment]
@emillod this is not an AdvancedPack only feature, if you create a Template for an Entity, that Entity will gain a print to pdf option. 

Note that you might need to rebuild, clear cache, refresh your browser in order to see the new function after creating the template

**Comment by emillod** [comment]
Wooooo!!!! 
## Great ! Thanks!

**Comment by emillod** [comment]
@yurikuzn do you plan to implement function "sent e-mail" for all entities like with print to pdf? 👍

**Comment by yurikuzn** [comment]
Not sure yet.

**Comment by vdbemden** [comment]
Hi, 
I'm fond of this new functionnality !
Everything is working great except one thing i can't do.
When I use a placeholder for a field with many-to-many relationship I can't show anything except the Ids.

I.E. It seems that the template loads correctly the Ids but then I don't know how to retrieve special informations like the name of each Ids.

**Comment by yurikuzn** [comment]
Hi,

It's not supported.

**Comment by vdbemden** [comment]
Should it be done in the futur?
Or could you give me at least the file where it could be implemented?

Anyway, Thx again for your great work :)

**Comment by yurikuzn** [comment]
Not sure yet. Code is here: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Htmlizer/Htmlizer.php

**Comment by vdbemden** [comment]
Looking at the code, one last question came : 
Why does the placeholder "$relationIds" works while "$relationNames" doesn't work?
This placeholder is shown in the available placeholders and the names are loaded by default when you view the entity.
Moreover, everywhere in the code, "$relationIds" and "$relationNames" are both used.
Any idea?

**Comment by yurikuzn** [comment]
Sorry, I have no time to look into this.

**Comment by bojkic** [comment]
@vdbemden did you find a solution?

**Comment by vdbemden** [comment]
If I remember well, I dug into the code and wrote some sort of patch but I didn't clean it enough to post it here
For now, I'm on holidays for two weeks. If you want, I can check it when I'm back at work

**Comment by vdbemden** [comment]
Well then, I patched the code with the following : 
`if (
                    !empty($relationDefs[$relation]['type'])
                    &&
                    ($entity->getRelationType($relation) === 'manyMany')
                ) {
                    $relatedEntities = $entity->get($relation."Ids");
                    foreach ($relatedEntities as $relatedId) {
                        $relatedEntity = $this->getEntityManager()->getEntity($entity->getRelationParam($relation, "entity"), $relatedId);
                        if (!$relatedEntity) continue;
                        if ($this->getAcl()) {
                           if (!$this->getAcl()->check($relatedEntity, 'read')) continue;
                        }

                        $data[$relation."Names"] .= $relatedEntity->get('name').","; //$this->getDataFromEntity($relatedEntity, true);
                    }
                }
`

(Insert it after line 185 in Htmlizer)

This could be cleaned and maybe merged with the previous if but I didn't have the time to work on it.
