### ISSUE TITLE
Calendar: Ability to disable creation event on same timeslot

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#793]
# Needs improvement in *espo calendar*

## Problem

Currently, two meetings/calls/task can be scheduled for a member in calendar, where in fact, a person cannot attend two meetings/calls at the same time. 

## Suggestion

1. It would be helpful if only one event can be scheduled for a person in a given time frame. If someone tries to schedule a second event for the same person, then the calendar should not allow the scheduler to schedule the event (meeting/call).
2. If first suggestion cannot be implemented because concurrent events are necessary as a use case, can you at least provide a settings option in **Administrator** saying *don't allow scheduling two events at same time frame*. If it is checked then, it shouldn't allow the suggestion no. 1.

**Note**: Please let me know if it is already present.

**Comment by bandtank** [comment]
1) This won't work because concurrent meetings represent a valid use case for many businesses.
2) This makes sense to me as an alternative.

**Comment by imbhat** [comment]
Hey,

Thanks for the quick response. Getting the alternative up and running sounds good to me.

**Comment by bandtank** [comment]
Yuri will probably weigh in at some point to speak to how hard this would be to implement. A setting would be nice, but it could be difficult. I'm not sure yet.

**Comment by yurikuzn** [comment]
Hi,

I need to analyze this first and then let you know.

**Comment by imbhat** [comment]
Thanks yuri.

**Comment by brianpunzalan** [comment]
We tried it before by having conflicting events but we had problems on using the Google Calendar integration. Its hard to control the events from outside source and prevent from conflicting.

**Comment by imbhat** [comment]
Can you allow this feature only when events are created internally on espocrm. You can't help when things are scheduled in Google Calendar, i understand. But when events are scheduled from espo calendar can you make sure that there aren't any conflicting events that are already present in the calendar.

**Comment by yurikuzn** [comment]
With a new `userIsBusy` function and API before-save script it will be possible to check whether the range is free for a user and show an error otherwise. https://github.com/espocrm/espocrm/issues/2720 https://github.com/espocrm/espocrm/issues/2724
