### ISSUE TITLE
Predefined filter views needed

### ISSUE THREAD

**Issue by imbhat** [espocrm/espocrm#794]
## Problem

In a particular label like Lead, filtering can be done with All, Actual, Converted, Only My, Followed which is really good. However, it would be really helpful if admin can define a custom view with filters set. 

For example, say I want to filter the leads by `status=new` only. Right now, I have to use the filters on the right side of the search. But if the administrator can create a custom view on the left side of the search, then the non technical person (who is layman) doesn't have to be bothered by filtering using the filter list and selecting values. 

The idea here is that the non tech team should just get the filtered data in a button click rather than sit a filter things. The administrator is the one who should configure these things so that the non tech team spend their time doing what they are supposed to do rather than spend time on filtering.

**FYI**: In general, the non technical teams find it difficult to do things like applying filters.

**Comment by bandtank** [comment]
It's possible via code, but being able to define filters in the GUI would certainly be a lot easier.

**Comment by imbhat** [comment]
Hey,

Thanks for the quick response. Can I expect this to be present in the next release or something.

Also just as a note, the filter doesn't have to be just status, it can be any field like source or custom fields also.

**Comment by bandtank** [comment]
Unfortunately, I'm not a developer for this project, but I contribute as often as I can. I'm supporting your idea because it's good and if there's a way for me to help, I will. There are bigger fish to fry, but this would be a really nice addition.

I've created many filters via code to get around this and it works perfectly fine, but it's not as quick. I'd probably have 10x as many filters if they could be defined via GUI.

**Comment by imbhat** [comment]
Can you please share the work around code done by you for this. I am a developer and I can do the same. However, I don't have any knowledge in the framework. So, I need some help.

**Comment by yurikuzn** [comment]
I think we will do it in future.

Example for task entity:
https://github.com/espocrm/espocrm/blob/master/application/Espo/Modules/Crm/Resources/metadata/clientDefs/Task.json#L64
https://github.com/espocrm/espocrm/blob/master/application/Espo/Modules/Crm/SelectManagers/Task.php#L96

**Comment by imbhat** [comment]
Thanks for the quick response. I will do it for now.
