### ISSUE TITLE
Workflow should allow adding multiple condition blocks

### ISSUE THREAD

**Issue by imbhat** [espocrm/espocrm#796]
# Problem

Right now in workflow conditions, you can add one condition only.

For example,

```php
if (condition is met) {
    // do this action
}
```

However, there are scenarios where you need multiple conditions...

For example,

```php
if (status is new and is assigned to User) {
    // send lead assignment notification
} else if (status is follow up and is assigned to User) {
   // create an event
}
```

Right now this can be achieved by adding two workflows. However there are times when you can't achieve it even with two workflows.

For example,

```php
if (number % 3 == 0 and number % 5 == 0) {
  // do something
} else if (number % 3 == 0) {
  // do something
} else if (number % 5 == 0) {
  // do something
} else {
  // do something
}
```

There are two reasons why we need this
1. If we create one separate workflow for each condition maintaining it becomes very difficult.
2. It makes more sense when you group conditions belonging to same category, more manageable and simpler.

**Comment by yurikuzn** [comment]
Sorry, this repository is not for features of advanced pack. Please use forum or customer portal.
