### ISSUE TITLE
[ Entity manager ] [ Phone ] data type is missed

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#80]
I wanted to add a Phone filed to my new entity, but I noticed that Phone is missed from the field type list.

**Comment by ayman-alkom** [comment]
It is exist by default when my created Entity extended from Person, whereas not exists when extended from the Base Entity.
This may be a convention!

**Comment by yurikuzn** [comment]
You can add phone field manually in entityDefs of your custom entity.
