### ISSUE TITLE
Date Time always less than the real time with 2 hours

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#81]
I noticed that the time is always less than the correct time by two hours, 
my TimeZone is `Europe/Istanbul` and it is set in the settings of EspoCRM

````php
    date_default_timezone_set('Europe/Istanbul');
    echo date("D M d, Y G:i a");           //Wed Dec 30, 2015 12:20 pm
    //but the now in Espo is 10:20 pm
````

**Comment by yurikuzn** [comment]
In backend EspoCRM operates with GMT time. In frontend it converts into local timezone set in Preferences. Check your timezone in Preferences (not Settings).
