### ISSUE TITLE
Sort on Lead name does not work

### ISSUE THREAD

**Issue by tvld** [espocrm/espocrm#815]
- Currently: Clicking on the arrow in Lead > Name does not do any sorting. 
- Expected: Sort like in Account and Contact
- Espo Version 5.0.5

![screenshot from 2018-02-27 20-38-55](https://user-images.githubusercontent.com/986182/36750920-038fe730-1bff-11e8-8ce0-767891e8729c.png)

**Comment by yurikuzn** [comment]
Can't reproduce. Clicking on the 'Name' does sorting.

**Comment by tvld** [comment]
Oops, it's so simple to reproduce. You would like a recorded screen?

**Comment by tvld** [comment]
![issuesort](https://user-images.githubusercontent.com/986182/36751634-0255a2f4-1c01-11e8-8a34-100885d7fd3a.gif)

**Comment by yurikuzn** [comment]
It's not simple to reproduce.

**Comment by yurikuzn** [comment]
Do these leads have empty Name field?

**Comment by tvld** [comment]
Sorry when I said "simple to reproduce", I meant for myself )))
And.. yes...you are right. ``Name`` is empty, but ``Account Name`` is not.

**Comment by tvld** [comment]
![screenshot from 2018-02-27 21-11-53](https://user-images.githubusercontent.com/986182/36752287-e537c4c0-1c02-11e8-81b2-99b4a46ee580.png)

**Comment by yurikuzn** [comment]
It sorts by person name only. Recetly it would show 'None' in the list view when Name is empty, but we made it to show Account Name if Person Name is empty. Unfortunately, there are some technical constraints to sort by both fields.

**Comment by tvld** [comment]
Clear, thank you. Thinking... maybe in that case maybe turn label into ``Account Name / Name``? In that way it's slightly more logical that sort would not work if ``name`` is empty?

**Comment by yurikuzn** [comment]
If account name is epmty then it shows email address. If email address is empty it shows phone number. Not so simple.

**Comment by tvld** [comment]
What about creating a "shadow field", that you use to sort? The  ``shadowSortField =Name+AccountName+Email+Phone``. In that way you dont have to meddle with new indexes or whatever, although you do need to update the field each time the record changes... 

_PS - Just three days ago got familiar with Espo of which one day lost with fighting Docker for optimal containers, so maybe I am not yet of much help..._

**Comment by loreahlie11** [comment]
It would probably be easier for you to use a hook and fill name with account name if name is empty.  That way the filtering would work as intended.  I have to do this with one of my custom entities.
