### ISSUE TITLE
Hide/Show panels multiple condition don't work properly

### ISSUE THREAD

**Issue by imbhat** [espocrm/espocrm#816]
# Problem-1

**When custom panel is created, name field is not create for the panel in detail.json**

See espocrm forum Post by @theBuzzyCoder here: https://forum.espocrm.com/forum/developer-help/31810-show-hide-panels for exact details.

# Problem-2

**Hide/Show panels multiple condition don't work properly** 

custom/.../clientDefs/Lead.json

```json
{
    "formDependency":{
        "source":{
            "map":{
                "Website":[
                    {
                        "action":"show",
                        "panels": [
                            "formFill"
                        ]
                    }
                ],
                "Email": [
                    {
                        "action":"show",
                        "panels": [
                            "data"
                        ]
                    }
                ]
            },
            "default":[
                {
                    "action":"hide",
                    "panels": [
                        "formFill"
                    ]
                },
                {
                    "action":"hide",
                    "panels": [
                        "data"
                    ]
                }
            ]
        }
    }
}
```

#### Steps for reproducing error

- Create a lead with source, say Call. Now, formFill and data panel doesn't show up.
- Change source to website, formFill shows up
- Next Change source to Email, formFill and data shows up.

**FYI**: I know source is read-only field. But this condition can be used for other fields as well like status or any custom field.

**Comment by yurikuzn** [comment]
Hi, 

1. It's already must be fixed.

2. formDependency is a deprecated feature. Try using dependencyLogic or dependencyHandler (very new feature, not documented yet).

**Comment by imbhat** [comment]
Hi @yurikuzn,

Can you please tell me, how can I use it for panels. I know how to use it for fields.

Thanks

**Comment by yurikuzn** [comment]
There is no documentation yet. Sorry, I have no time. Very busy.

**Comment by imbhat** [comment]
My bad. I figured it out

```json
{
    "formDependency":{
        "source":{
            "map":{
                "Website":[
                    {
                        "action":"show",
                        "panels": [
                            "formFill"
                        ]
                    }
                ],
                "Email": [
                    {
                        "action":"show",
                        "panels": [
                            "data"
                        ]
                    }
                ]
            },
            "default":[
                {
                    "action":"hide",
                    "panels": [
                        "formFill",
                        "data"
                    ]
                }
            ]
        }
    }
}
```

**Comment by aminsaki** [comment]
God, gather this thing correctly
