### ISSUE TITLE
Make espocrm available in packagist.org

### ISSUE THREAD

**Issue by theBuzzyCoder** [espocrm/espocrm#818]
# Problem

Cannot add espocrm as a package in composer.json

# Solution

Add name and description in "composer.json". Add submit it to packagist.org

**Comment by theBuzzyCoder** [comment]
Hi,

I can do this.

**Comment by yurikuzn** [comment]
Hi,

We will do it. Thanks.

**Comment by theBuzzyCoder** [comment]
Hi,
Once you are done with it, please let me know via comment. Awaiting for this! 

Also, want to know if I can contribute to this project. Already signed the agreement in espocrm/cla

Thanks

**Comment by yurikuzn** [comment]
Yes, you can contribute.

**Comment by yurikuzn** [comment]
I'm not sure where I will do it. I have a lot of work to do.

**Comment by theBuzzyCoder** [comment]
The code is already the in pull request #819. I have tested it in my machine. It should work.
