### ISSUE TITLE
Printing an Entity

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#824]
Hi

I need the ability to print a Case, with its Stream. Is this possible with templates?

Kind regards

**Comment by yurikuzn** [comment]
Hi,
No.

**Comment by Sloff** [comment]
Could you point me to the file(s) that I can use to add this logic?

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Htmlizer/Htmlizer.php
