### ISSUE TITLE
Stream Permission

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#825]
Hi 

How can I setup a Role so that someone can view the stream on a Case, but cannot delete stream entries?

Kind regards

**Comment by yurikuzn** [comment]
Hi,

Do you mean cannot delete own Posts? It's no supported. 

But now users can remove other notes from stream apart from posts. It's a bug that will be fixed.

**Comment by Sloff** [comment]
So someone can delete their own Posts, but shouldn't be able to delete another person's Posts?

**Comment by yurikuzn** [comment]
Regaular user can't delete Posts created by other users.
