### ISSUE TITLE
&nbsp; is shown in case emails

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#827]
Hi

When someone created a case with an email, everything renders fine, except for `&nbsp;` which is actually shown as `&nbsp;` within the stream, but when navigating to the email itself, everything is shown fine, the `&nbsp;` characters are rendered as whitespace

**Comment by yurikuzn** [comment]
Hi,

We don't have such an issue.

**Comment by Sloff** [comment]
As an example, here is a recent case that was created: 
![image](https://user-images.githubusercontent.com/7330170/37396072-89934a48-2780-11e8-9dd0-241919e18c9c.png)

When navigating to the email by clicking on the link, everything looks perfect

**Comment by yurikuzn** [comment]
It could be that email client sends a bad body plain.

**Comment by Sloff** [comment]
Wouldn't it then look the same on the email view?

**Comment by Sloff** [comment]
For example, here is the text from the stream:
![image](https://user-images.githubusercontent.com/7330170/37400577-01fd6cb8-278e-11e8-878d-e29faaca87ee.png)

And here is the exact same text on the email view:
![image](https://user-images.githubusercontent.com/7330170/37400612-229589ce-278e-11e8-8b28-98669fa9da2a.png)

**Comment by yurikuzn** [comment]
Email view displays html version (if exists), stream view displays text-plain.

**Comment by Sloff** [comment]
I understand, with that in mind I've gone through the cases again, I think it happens when people send the mails from an older version of Outlook

**Comment by Sloff** [comment]
@yurikuzn I examined the database entry of one of these emails, it looks like there is no `body_plain` entry, only a `body`, and all the `&nbsp;` characters that are being displayed are wrapped within `<o:p>` tags.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/823c46a6df814b6f655277ee8f9102f8e32dc93a
