### ISSUE TITLE
Let's talk about security in EspoCRM

### ISSUE THREAD

**Issue by buzzard10** [espocrm/espocrm#832]
Hello guys
I think Espo is great, but You should consider few things about security. 
1. Two steps verification for login screen (Google Authenticator, codes in e-mail, DUO security, anything)
2. Logs for bad logins - Espo should log every single request from login screen
3. Captcha for login screen - Without captcha, bots can attack using brute force method without any knowledge of espo administator
4. Blocking bad logins by IP - same thing like in point 3
5. Login tokens - even if i turn on notifications about new tokens, if anyone try to connect by API, i don't have any alert
6. Logs for API - I think there should be any logs who and when tried to connect using API
7. White list for API - I think also that before anyone try to connect by api to Espo, He should add his IP to white list in the first place

I see potential in Espo. Really, i can move all information about company to Espo, but we should have more security options. In few months in EU We'll be have new law regarding to data processing and security, those thing above should be good shield/firewall for our data.

**Comment by yurikuzn** [comment]
Hi,

4, - for now it can be achieved by server configuration;

6, 7 - EspoCRM frontend uses api, it's api-based application, so everything works only through API, The issue that is Auth Token is not created. when someone connects to API manually, is another issue, that we need to fix.

**Comment by emillod** [comment]
@yurikuzn thanks for reply :) 
I know that EspoCRM uses api and that everything works only througn API, but if someone use URL to hack EspoCRM, i.e. http://demo.espocrm.de/advanced/api/v1/Task?maxSize=20&offset=0&sortBy=createdAt&asc=false - He can skip all security shields and check passwords without alerting administrators. In my personal opinion it's really big issue. 

About point 4 - can you give me more details?

**Comment by yurikuzn** [comment]
It depends on your server. For apache; https://httpd.apache.org/docs/2.4/howto/access.html

**Comment by emillod** [comment]
@yurikuzn yep, We have apache and we already knew about block by ip and etc but it's not good solution if You give access your customers to crm panels.

**Comment by fodinabor** [comment]
Any interest in getting a module using secsign 2FA or have that integrated into the codebase?

**Comment by emillod** [comment]
@fodinabor 
I'm thinking about implementing something more like duo security

**Comment by fodinabor** [comment]
yeah well.. I did finish the SecSign stuff already.. so if you're interested...

**Comment by emillod** [comment]
Can You share with us hire you implemented SecSign? Maybe it will be helpful to implement another mechanism

**Comment by fodinabor** [comment]
Sure, just browse over here:
https://github.com/fodinabor/EspoSecSignAuth

**Comment by emillod** [comment]
Wow! Great! 
I need to check how it works. What if someone try to log in using API manually? He also need to pass second verification process?

**Comment by fodinabor** [comment]
hmm... the best way currently would be to gain an auth token for the user and just use that in the the ESPO-AUTHORIZATION header
Though I'm not sure what the best way to gain the Auth Token would be..

**Comment by emillod** [comment]
@fodinabor
What do You think about other points from my list? 
And also do You consider develop other providers 2FA i.e. Google authenticator or like I mentioned above duo security?

**Comment by fodinabor** [comment]
1. Not really right now.. this was somewhat like contract work (that' why I chose SecSign).. though I might if I have time and there's demand for that... I think you could easily turn that extension into a general 2FA Extension

2. #838 works on that I think

3. I personally would not use a captcha.. takes another click.. but not be a too big issue to implement that as well.. would use reCaptcha with explicit rendering approach: https://developers.google.com/recaptcha/docs/display#explicit_render

4. is best done at webserver / os level and not in webapps

5. uses Auth Tokens.. 
an approach that could work but would require some redesign of the Auth logic: use Auth Tokens with a rather limited (idle/)lifespan and have an explicit mechanism for logging in with an API token. this logging in would generate an Auth Token again which you use for Authorization of the real api calls again - could be done by extension as well I think

**Comment by emillod** [comment]
@fodinabor thanks for details. 🥇

**Comment by tomaspar** [comment]
What is current status of security approach? What is most secure way to go with ESPO public for clients login, but still have safe data in it?

**Comment by emillod** [comment]
It's hard to say. I think that better approach then just public espo is using API, for example:
I created simple html dashboard for my clients. They can open login page, fill e-mail address, and after that system checking if this e-mail is assigned to someone in espo. After that system sending e-mail to that client with safe URL, which will confirm that my client really want to log in. 
After that my client have access to all informations which i want that he have.
I think it's better than just providing directly access to espo, but maybe i'm wrong.. :)

**Comment by bandtank** [comment]
It's not better, but it's not worse either. It's probably unnecessary since
logging into Espo via API is not limited by providing a different link.
Access to the Espo instance in any capacity is enough. With that said,
there's nothing wrong with using basic authentication to login to Espo.

I have built multiple sites using Espo's API and basic authentication as
the login mechanism. The username and password fields are presented to the
user, which are then used to send a POST request to Espo's API. I store the
token in localStorage and I remove it when it expires or when the users
logs out. This is a really typical design pattern.

**Comment by emillod** [comment]
@bandtank maybe your approach is better, i don't know. In custom apps which i created myself i can add another layers of security like captcha, block for ip and etc. Espo don't have anything like this..

**Comment by bandtank** [comment]
You can do that with basic auth as well. You just have to do it before you
send the request on your custom page. I include a captcha before I present
the login form if the IP address is not recognized. You can also build a
custom endpoint in PHP very easily if you need more features for login.

**Comment by yurikuzn** [comment]
You can also create API user (with a specific role) and use more secure HMAC auth. Using HTTPS connection is a necessity in any case.

**Comment by tomaspar** [comment]
Anyone use  native ESPO portals? why not? I need ir for help-desk, KB  and PO processing in one place. something like self-service.

T
