### ISSUE TITLE
Charset issues after updating from 5.0.5 to 5.1

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#837]
Charset issues after updating from 5.0.5 to 5.1.

```
[2018-03-19 10:33:47] Espo.ERROR: API [GET]:/:controller/action/:action, Params:Array (     [controller] => Activities     [action
] => popupNotifications ) , InputData:  - SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLI
CIT) and (utf8mb4_general_ci,IMPLICIT) for operation 'like' [] []
[2018-03-19 10:33:47] Espo.ERROR: Display Error: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_c
i,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation 'like', Code: HY000 URL: /api/v1/Activities/action/popupNotifications
[] []
```

and when opening a call:
```
[2018-03-19 10:36:32] Espo.ERROR: API [GET]:/:controller/:id, Params:Array (     [controller] => Call     [id] => 5aad3b1493f49dd6
d ) , InputData:  - SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_gene
ral_ci,IMPLICIT) for operation 'like' [] []
[2018-03-19 10:36:32] Espo.ERROR: Display Error: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_c
i,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation 'like', Code: HY000 URL: /api/v1/Call/5aad3b1493f49dd6d [] []
```

and stream problem:
```
[2018-03-19 10:38:05] Espo.ERROR: API [GET]:/Stream, Params:Array ( ) , InputData:  - SQLSTATE[HY000]: General error: 1267 Illegal
 mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation 'like' [] []
[2018-03-19 10:38:05] Espo.ERROR: Display Error: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_c
i,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation 'like', Code: HY000 URL: /api/v1/Stream?maxSize=10&offset=0&sortBy=num
ber&asc=false [] []
```

**Comment by rutkas** [comment]
My configuration has many stored functions, procedures and triggers in the database, after removing the utf8mb4 from function argumements - errors dissapered. I have checked the database - some text rows have utf8_unicode collate, the others - utf8mb4_unicode, the 'preferences' table has utf8_general collate. there are three different collates present in the database. mysql reported Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for the confusion between utf8mb4 and utf8 types, however default connection collate was unicode and not general. I think it would be much better if all database varchar fileds had one single collate, and of course utf8mb4_unicode_ci that is default and universal.

**Comment by yurikuzn** [comment]
All collumns and tables that we have in our tests invironments are unicode.

**Comment by rutkas** [comment]
All of the collations that I described - are unicode, but they are different.

![untitled-1](https://user-images.githubusercontent.com/14265370/37655026-c7214b6e-2c4c-11e8-8120-ac239d437bb1.png)

the difference between utf8mb4_unicode_ci and utf8_unicode_ci:
[https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci](https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci)

And also prefs table had old utf8_general_ci collation, that is also unicode (since it is utf) but differs. Why prefs table ? I remember this table was added about half a year ago in one of updates, when prefs were mnoved from file to database... maybe the database collation default was utf8_general_ci in that versions, and table was added without specifying exact collation, and default db collation was used. and rows were created with tables default collation. 
And also all the tables in the database has utf8_unicode_ci default collate differ from utf8mb4_unicode that is set to default for database now.

**Comment by yurikuzn** [comment]
There is a reason why we need to keep utf8_unicode_ci for index columns.

What's the problem to have both utf8_unicode_ci and utf8mb4_unicode_ci? We tested and didn't have any problems.

**Comment by yurikuzn** [comment]
I also recommend to change all tables to InnoDB. SInce 5.1.0 it's default.

We could not convert MyISAM to InnoDB in upgrade script because there would be a risk to lose data.

**Comment by rutkas** [comment]
I use triggers and functions in the espo database (it was little easier for me to implement some specific functions instead of customising espo api). Before 5.1 I had to specify utf8mb4 exact charset for each varchar argument in stored procedures, I did that in past to get rid of these collate mix errors. But after updating to 5.1 errors appeared again, and after experiments I found that removing charset for varchar arguments helps (but this failed with old espo releases). sometimes in stored procedures I get value from one row then from another, combine them, thats why mixing collations can cause problems..
what is the reason in keeping utf8_unicode? as I understand utf8mb4 is modern.

**Comment by yurikuzn** [comment]
Size limits,

If you have your tables in InnoDB and MySQL 5.7 then you can change all indexed collumns to utf8mb4,

**Comment by rutkas** [comment]
I'm using mysql 7.1. I would like to migrate on InnoDB and change to utf8mb4 everywhere. But how to do these two steps better and ... automatically ?

**Comment by yurikuzn** [comment]
Sorry, I'm not a specialist in this area. Make a backup and change it using phpmyadmin.

5.7 - is the latest MySQL version. There is no 7.1 version.

**Comment by rutkas** [comment]
sorry, I was thinking about php7.1

**Comment by rutkas** [comment]
So I can not use utf8mb4 everywhere if use this mysql ver ?

**Comment by yurikuzn** [comment]
No. Need 5.7 + InnoDB.
