### ISSUE TITLE
Row actions not clickable on mobile devices

### ISSUE THREAD

**Issue by voluse** [espocrm/espocrm#840]
Hi;

When you want to use row actions on bootstrap XS view you can not click actions which are listed.

When you click the arrow for row action, options appear like view, quick edit etc. But when you want to click one of these options, they are not clickable and options disappear.

EspoCRM: 5.1.1
Browser: Safari Mobile

Thanks!

**Comment by yurikuzn** [comment]
Hi,

Odd that in the mobile device emulation it works. Fix: https://github.com/espocrm/espocrm/commit/ee8608469e364fdb8dd8803afdaa654913e0eee6.

Thanks
