### ISSUE TITLE
Issue with uploading files - bug?

### ISSUE THREAD

**Issue by emillod** [espocrm/espocrm#844]
Hello.
From time to time we're observing problems with attaching files to tasks.
We saved some logs. 
> [2018-03-20 16:44:36] Espo.ERROR: API [GET]:.*, Params:Array ( ) , InputData:  -  [] []
> [2018-03-20 16:44:36] Espo.ERROR: Display Error: , Code: 404 URL: /?entryPoint=image&id=5aa1335341a674cda&size=medium [] []
> [2018-03-20 16:44:36] Espo.ERROR: Uncaught Exception Slim\Exception\Stop: "" at /home/user/domains/example.com/public_html/vendor/slim/slim/Slim/Slim.php line 1022 {"exception":"[object] (Slim\\Exception\\Stop(code: 0):  at /home/user/domains/example.com/public_html/vendor/slim/slim/Slim/Slim.php:1022)"} []
> [2018-03-20 17:07:49] Espo.ERROR: API [GET]:.*, Params:Array ( ) , InputData:  -  [] []
> [2018-03-20 17:07:49] Espo.ERROR: Display Error: , Code: 404 URL: /?entryPoint=image&id=5ab13d0b3759eb2bd&size=medium [] []
> [2018-03-20 17:07:49] Espo.ERROR: Uncaught Exception Slim\Exception\Stop: "" at /home/user/domains/example.com/public_html/vendor/slim/slim/Slim/Slim.php line 1022 {"exception":"[object] (Slim\\Exception\\Stop(code: 0):  at /home/user/domains/example.com/public_html/vendor/slim/slim/Slim/Slim.php:1022)"} []

Description:
1. I attached photo to task
2. I saw thumbnail of photo in EspoCRM
3. I saved task
4. My coworker open that task and saw icon of broken file instead of photo.
5. After i reload website i saw that image disappeared

**Comment by yurikuzn** [comment]
Hi,
Never encountered this yet.

**Comment by ayman-alkom** [comment]
I can confirm this issue, I solved it by comment some unlink command in php files
I think that clean_up related.
try to deactivate clean up job for one week and see if the problem will still occurs

**Comment by ayman-alkom** [comment]
https://github.com/espocrm/espocrm/search?l=PHP&q=unlink%28&type=&utf8=%E2%9C%93

**Comment by emillod** [comment]
Of course i can check your solution but i think devs should consider to fix that in official repo. Because it can be really big issue for companies which don't know yet about that problem.

**Comment by ayman-alkom** [comment]
in fact I just noticed this issue in one placed where I had made a lot of customization
so the issue may not clear enough for dev to start with

**Comment by ayman-alkom** [comment]
but if you tried just to disable the clean up and the issue solved then the issue may be clear enough

**Comment by emillod** [comment]
Thanks @ayman-alkom for details. I'll try this :) !

**Comment by yurikuzn** [comment]
What scheduling for Cleanup jon do you have?

**Comment by yurikuzn** [comment]
Does it happen with the standard 'attachments' field? Any other fields were affected?

**Comment by ayman-alkom** [comment]
In my case it happened with image column type on custom entities

**Comment by ayman-alkom** [comment]
note that the image saved in the attachments table and then deleted by the clean up or something else

**Comment by yurikuzn** [comment]
@emillod, could you check whether the record with id = '5aa1335341a674cda' exists in the table 'attachment' ?

**Comment by emillod** [comment]
@yurikuzn thanks for reply.
1. Cleanup we setup in cron for: 
1 1 * * 0 |  
2. I don't know if this connected, but in past we lost some PDF which was attached to entity record, and when we tried to find that PDF in folder with attachments we find that file but with different ID.
3. We have this problem only with fields attachments, but in more then one entity. Not only in tasks, but also in cases and some other entities. 
4. Sure, but i need time for that to log in :)

**Comment by yurikuzn** [comment]
It doesn't look like it was deleted by the cleanup job. Also it doesn't look like it was unlinked by EspoCRM application. What server do you use? Is it your server or a hosting provider?

**Comment by ayman-alkom** [comment]
in my case the serve is apache by wamp on windows

**Comment by emillod** [comment]
Same here. Apache for www server + I'm using hosting provider.

**Comment by yurikuzn** [comment]
It seems that the file was never stored. Could it be?

**Comment by yurikuzn** [comment]
Could you check your server's error log. Maybe there was a problem with file permissions.

**Comment by ayman-alkom** [comment]
> It seems that the file was never stored. Could it be?

maybe

> Maybe there was a problem with file permissions

no because the most of files in my case go well, and some not

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/18304fb7105ab20a22869a58b3fb16677a2482f7

If the file is not stored it will return an error.

**Comment by ayman-alkom** [comment]
and the record will not saved, doesn't it?

**Comment by yurikuzn** [comment]
It happens while uploading an attachment, before the Save button gets clicked.

**Comment by emillod** [comment]
Hello. Thanks for replies. 
In my case error is after i save record and reload website.

**Comment by yurikuzn** [comment]
Are you sure that attachment was stored? I'm not sure.

**Comment by yurikuzn** [comment]
This https://github.com/espocrm/espocrm/issues/888 could be the cause.
