### ISSUE TITLE
Cron jobs timezone

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#847]
I noticed that cron jobs are started at incorrect time and looks like it is a timezone issue. My timezone iz GMT+2,  I set job to run at 20 15 * * * but it runs at 17:20 instead of 15:20

**Comment by yurikuzn** [comment]
It's not supported. You need to make a convertation manually.

**Comment by bandtank** [comment]
Cron jobs run on UTC time. I was confused about this as well, but it actually makes things a little easier once you realize that’s how it works.

**Comment by rutkas** [comment]
I udnerstand that I can set the job time in UTC. But after time changes from Winter to Summer time in my zone - 1hour offset will appear for the job... and I will need to adjust job running time twice a year, right ?

**Comment by yurikuzn** [comment]
Unfoerunately yes, Maybe if future we will add an option to apply timezone. Now we have no such an ability. Some technical constraints.

**Comment by tvld** [comment]
Well... before you do a lot of work: https://www.independent.co.uk/news/world/europe/eu-end-daylight-savings-time-zones-member-states-europe-a8203446.html

**Comment by yurikuzn** [comment]
Done: https://github.com/espocrm/espocrm/issues/2936
