### ISSUE TITLE
Unable to log inn

### ISSUE THREAD

**Issue by KonradHolubek** [espocrm/espocrm#853]
Hi, 

I was able to install EspoCRM on my server but when I get to the login page I am unable to make my first log inn. I get the message "bad combination of user/password". When I try to recover my password I get "user/email combination was not found".

I checked my mysql database and I can see that the (admin) user has been created and I am sure my user and password is correct.

The only error message I can see is in the web console : "[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (user, line 0)"

Please help because I am stuck and I cannot start using the platform. 

PS : I'm testing the service so I'm currently using HTTP to access it

Thank you,

Konrad

**Comment by tvld** [comment]
Is this not a message for the Espo Forum?  https://forum.espocrm.com/
Maybe I am wrong but it does not seem like a bug but configuration issue ?

**Comment by KonradHolubek** [comment]
Hi

Thank you for getting back to me. Yes it is... but for some reason I am unable to post on the forum that is why I did it through the contact form. Can you please help me with this configuration issue ?

Konrad

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tvld** [comment]
You would need to subscribe to the forum. It also took some time for me to figure it out. But after that, people are very willing to help.
About your issue, I would not know. It could be something to do with the web server your are using... Are you running behind a proxy? Do you get the normal Espo login screen? 100% sure no caps lock or something?

**Comment by tvld** [comment]
You could also try to clear complete browser cache...
