### ISSUE TITLE
Editor wrongly insert 'http://' in links with {optOutUrl} fields

### ISSUE THREAD

**Issue by tvld** [espocrm/espocrm#855]
Trying to add {optOutUrl} to write a nicely formatted unsubscribe line. For example _"You can click [here ]({optOutUrl} )if you dont like any more emailsfrom us."_

The problem is that if I select "here" and press ctrl-K or the link symbol, and paste "{optOutUrl}" in the popup field, Espo then saves the link with "http://" 

Wrong: in the email clients then get a link such as ``http://https://mysite.com/....``
Expected: dont add 'http://' in front of {} fields...

![screenshot from 2018-03-26 15-28-30](https://user-images.githubusercontent.com/986182/37909146-7003fe2c-310a-11e8-806d-5fcd19a645c7.png)

**Comment by tanyalei** [comment]
Hello Tom,
for uptOut don't use this Link option. 
Select **Code view** mode and write 
`<a href="{optOutUrl}">hier</a>`

**Comment by tvld** [comment]
Ok, it's a work-around that works. Thank you ))
