### ISSUE TITLE
Email Notifications: Configurable note types to notify about

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#860]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/ed762c9be3f433f4e3221148bbba01283479f437

**Comment by rodrigoscoelho** [comment]
thanks Yuri.
_______________________________________









Rodrigo Sírio Coelho

Diretor

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807







On Mon, Apr 2, 2018 6:48 AM, Yuri Kuznetsov notifications@github.com  wrote:
ed762c9
