### ISSUE TITLE
HTML entities not being decoded

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#867]
`&npsp;` characters are now correctly being converted into spaces within the `getBodyPlain` function of `Espo/Entities/Email.php`, but other HTML entities such as `$amp;` are not displayed correctly. 

I believe the [html_entity_decode](https://secure.php.net/manual/en/function.html-entity-decode.php) function will correct this. 

I can implement this, I''m just unsure if any flags are needed for the function or if this might cause other issues

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/espocrm/commit/66e4b89d1addfb9bfd2b5e4fb3148f555cf45d99

**Comment by Sloff** [comment]
Awesome, thank you

**Comment by Sloff** [comment]
@yurikuzn could I implement something like [this](https://github.com/RobQuistNL/SimpleHtmlToText/blob/master/src/Parser.php)? Then all HTML entities will be converted and the email will be shown as Markdown, which could improve ease of reading a mail within the stream

**Comment by yurikuzn** [comment]
This logic should not be in Email entity class.

**Comment by Sloff** [comment]
Where would be the best place to add this logic?
