### ISSUE TITLE
Template editor and {{#each bug

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#875]
adding table in template for PDF rendering with item enumerator:
```
<table><tbody>
<tr><td></td></tr>
{{#each itemList}}
<tr><td>
{{item}}
</td></tr>
{{/each}}
</tbody></table>
```
after saving template renderer moves {{#each itemList}} and {{/each}} before the beginning of the table, that gives incorrect result after editing template again.
the result is :
```
{{#each itemList}}
{{/each}}
<table><tbody>
<tr><td></td></tr>
<tr><td>
{{item}}
</td></tr>
</tbody></table>
```

**Comment by yurikuzn** [comment]
You can use 
```
 <!-- {{#each itemList}} --> 
```

**Comment by yurikuzn** [comment]
https://github.com/espocrm/documentation/blob/master/user-guide/printing-to-pdf.md#each-iterator

**Comment by rutkas** [comment]
thanks

**Comment by rutkas** [comment]
By the way, the same is for `#if`, is it better to place them instiade of html comment too `<!-- {{#if}} -->` ?

**Comment by yurikuzn** [comment]
The problem with wysiwyg lib.
