### ISSUE TITLE
PDF parser and text fields

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#879]
PDF parser (pdf service) does not process multiline (text) fields correctly. text field wth
```
line 1
line 2
```
is rendered to pdf as:
`line 1<br/>line 2`

**Comment by yurikuzn** [comment]
https://github.com/espocrm/documentation/blob/master/user-guide/printing-to-pdf.md

{{{ ... }}}

**Comment by yurikuzn** [comment]
Triple braces needed.

**Comment by rutkas** [comment]
Thank you.
