### ISSUE TITLE
Possibility of downloading all attachments, compressed in zip

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#880]
As other email managers do, it would be convenient that in the attachments you have the possibility to download them all compressed as zip.

**Comment by rodrigoscoelho** [comment]
Better than that, it would be great to have a possibility to save a
attachment as a Espocrm document.

Em Sáb, 21 de abr de 2018 13:40, Mauricio Panuncio <notifications@github.com>
escreveu:

**Comment by PanuWeb** [comment]
Yes, that too.

I thought about it because one client sent me 20 images and I had to download them one by one. I did not need to keep them in Espo but it is also a good idea.

**Comment by o-data** [comment]
This is very old, almost 4 years soon so not sure if you two are still around and using EspoCRM.

It possible to save Attachment as a Document now, although it is tedious as you have to do it for each attachment.

There is no "save all" option yet still, so you have to rely on a Web browser extension when it come as many attachment. We trying to get our client to upload it on our Temporary "cloud" storage through a Public Link (can be password/require login). Using Filerun and Nextcloud for this, but most still just fall back on Email attachment as it is more convenient.

**Comment by Kharg** [comment]
Hi @PanuWeb and @rodrigoscoelho
I just released an extension allowing this.
https://github.com/Kharg/download-all-attachments/releases/latest

**Comment by yurikuzn** [comment]
Implementing it might be not as simple as it may seem. There can be multiple big attachments in one email. Users would be able to abuse server resources usage. We would need some mechanism of preventing it.
