### ISSUE TITLE
Tasks: 'Complete' button on the quick view

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#881]
As it exists in the complete form, it would be very useful if the "mark as completed" button appeared on the small form when viewing / editing a task.

I use it a lot when I'm in the calendar, I click on the task (the small form opens) and I have to edit it, then change the status manually to complete and save the task. So all the time. If the button appeared, it would save me the steps: I open, click on the button and it closes automatically. Simple, fast and easy.

Regards!

**Comment by yurikuzn** [comment]
Missed this one. Thanks.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/9b8c6bef99bed5f2ef8bf1f52cadc5aa31559a4f
