### ISSUE TITLE
Improvement in the preview of attached images in emails

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#882]
It would be interesting to add arrows to go through the images (back and forth) as a gallery and the ability to download them directly

**Comment by PanuWeb** [comment]
Yeah that's right. But what I propose is to move forward and backward, very useful for when I'm comparing two images to decide which one to download.

On the other hand, the link opens the image in the same Espo window, this makes it necessary to use the back button of the browser to load Espo again. It also does not force the download only shows the image in the browser (Chrome) and then you have to right click download image.

Another inconvenient that I am seeing is that by clicking on the image to advance, not only advances through the attached images but also embedded in the email (as the signature of the sender) something that I do not want.

Perhaps what I propose in #880 and #883 added to this give rise to an attachment viewer (of any type of attachment) something like an attachment slideshow. If possible, a preview is shown, but a detail of the metadata of the attachment. In all cases a download button. Also in the lower part of the email (or on another side, just the same), there may be a button that says "See all attachments" and others that say "Download all attachments".

That's the idea.

Regards

**Comment by yurikuzn** [comment]
Now it's possible to go back and forward using keyboard arrows. Having to right-click to download I don't find as an inconvenience.
