### ISSUE TITLE
Add double opt in for email addresses

### ISSUE THREAD

**Issue by bosonno** [espocrm/espocrm#886]
Add possibility to place a link (like unsubscribing) in email template which registers timestamp and ip address and status double opt in with value true.

**Comment by bosonno** [comment]
To comply with GDPR...

GDPR stands for the General Data Protection Regulation and is effective as of May 25th, 2018. GDPR replaces national privacy and security laws that previously existed within the EU with a single, comprehensive EU-wide law that governs the use, sharing, transfer and processing of any personal data that originates from the EU.

**Comment by michelrothgaenger** [comment]
@yurikuzn Even though this is a bit older, I would appreciate an update. Especially for all users in Europe this function would be elementary. A possibility to ask new contacts for consent to data storage by clicking on an opt-in link would be the cleanest fulfillment of the GDPR requirements.

**Comment by yurikuzn** [comment]
It's implemented in the [lead capture](https://docs.espocrm.com/administration/web-to-lead/#lead-capture) feature.

**Comment by michelrothgaenger** [comment]
Thank you for the quick reply.
