### ISSUE TITLE
Removing attachments on duplicated record deletes original files

### ISSUE THREAD

**Issue by mybaldbird** [espocrm/espocrm#888]
Need an entity with an 'Attachment Multiple' field.

1. Create a record and upload an attachment.
2. Duplicate the record, but don't save yet.
3. Delete the attachment on the creation page.
4. Now save the new record.

At this point if you navigate back to the original record and click the attachment you will get a 404 error. If you check the file system, you can see the file is not there.

**Comment by yurikuzn** [comment]
Thank you for reporting. Fix: https://github.com/espocrm/espocrm/commit/0f0060f0f6c42437eddcac50e6ba09f802bd939e

**Comment by yurikuzn** [comment]
Tests: https://github.com/espocrm/espocrm/commit/b7d43edf22f8770c231b632f66c5aff729adfe73
