### ISSUE TITLE
Chart Not Showing Data

### ISSUE THREAD

**Issue by axeforeverjumo** [espocrm/espocrm#891]
I installed EspoCRM copying from github and placed it in my server. But when I tried to use the "Sales per month" I have not data, same in "Opportunities by Stage".
![captura](https://user-images.githubusercontent.com/32218686/39629846-c566aa7e-4fad-11e8-9054-bd026ff62bd0.PNG)

Can someone help to what to do. I didn't do anything else maybe I need previous steps.

**Comment by yurikuzn** [comment]
You need to have Opportunities with stage = Closed Won in the date range defined the dashlet options.
