### ISSUE TITLE
Mailer deletes attachment files

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#896]
I have been wondered during a year, where are sometimes my espo attachemnt files gone from disk and now it looks like the reason is found.
When clicking on the email address and attaching a document OR using 'send in email' (knowledge-base-helper) mechanism from document, then  after clicking on the "X" at the bottom of the mail compose view near the file name to remove attachment from the email - the file IS DELETED from the \data folder. as a result we have 404 when trying to access that doc file. File is lost.

**Comment by yurikuzn** [comment]
This seems to be the same: https://github.com/espocrm/espocrm/issues/888

**Comment by rutkas** [comment]
Yes, just checked this bug on 5.2.1 and it is fixed.
