### ISSUE TITLE
TcPdf and cyrillic file names

### ISSUE THREAD

**Issue by rutkas** [espocrm/espocrm#905]
TcPdf does not support cyrillic file names by default, cuts cyr symbols and as a result we have incorecct file name. But this can be easily patched:

in htdocs/vendor/tecnickcom/tcpdf/tcpdf.php:
`$name = preg_replace('/[^a-zA-Z0-9_\.-]/', '', $name);`
change to:
`$name = preg_replace('/[^a-zA-Z0-9а-яА-Я_\.-]/', '', $name);`

And now we can succesfully create pdf attachements with cyrillic symbols.

I propose to make this patch permanent in Espo distribution

**Comment by yurikuzn** [comment]
Must be already fixed.
