### ISSUE TITLE
Email attachments discarded when Template selected

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#906]
Hi, I'm experiencing this bug on the latest version (5.2.2)

When forwarding an email with attachments, as soon as I select an email template, all of the attachments are removed and not sent when the email is sent

**Comment by yurikuzn** [comment]
Thanks for reporting. Fix: https://github.com/espocrm/espocrm/commit/a4054f5273ecce26dc247eb03a46b7a72281a34c.
