### ISSUE TITLE
Email Attachments Tab or identification of emails with attachments

### ISSUE THREAD

**Issue by Cri00** [espocrm/espocrm#919]
It would be really helpful to have a tab of emails (maybe in the History panel) with attachments divided in 2 categories: received and sent. Now, users have to open each email to see which one has an attachment.

Another option would be to have an icon for emails that have attachments, like a paper clip.

Thanks!

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/918
