### ISSUE TITLE
Textarea "Number of rows" not working as expected

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#925]
Hi

When editing the a textarea's "Number of Rows" field, the only values that seem to work are 1 and 2. I need to set it to a bigger value, such as 10.

**Comment by yurikuzn** [comment]
Hi,

It's how it's designed. It's the max number of rows the textarea will be expanded if you fill it with a text.

**Comment by Sloff** [comment]
I understand, thank you!
