### ISSUE TITLE
support multiple locations (and departments) for accounts

### ISSUE THREAD

**Issue by hi-ko** [espocrm/espocrm#931]
as enhancement to #930 an account should contain n departments and locations where
  - a department has an exclusive relationship (1:n)
  - a location has a non exclusive relationship (n:m)

Conctacts should relate to a location

**Comment by hi-ko** [comment]
departments could be easily implemented by adding a custom entity but for large organisations it would be necessary to give different ACLs, Workflows depending on the account's business unit, so it would be also a valuable feature to have a flag to mark an account as e.g. a business unit for another existing account (which is not a separate legal entity). This comment could be seen as a separate feature request.

**Comment by tomaspar** [comment]
It's really actual improvement for many bigger organisations relationship managment.

**Comment by yurikuzn** [comment]
This would be quite a breaking change. I suggest creating 1:m relationship with a custom entity of an Account template type that will serve for storing addresses.
