### ISSUE TITLE
Add composer/installers in require of composer.json

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#939]
This package allows to specify installer-paths in extra's of composer.json.

This very helpful when espocrm has to be installed in a very specific folder through custom composer.json.

For example,
Folder structure

**myCrm**/
  - composer.json
  - espocrm/
  - vendor/
    - directories of espocrm requires

**Comment by karthik-uc** [comment]
Any updates on this?

https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

**Comment by karthik-uc** [comment]
Hi @yurikuzn,

So, here's my use-case. 

Right now, I downloading the source using 

`wget -O /app/espocrm.zip https://github.com/espocrm/espocrm/archive/5.4.5.zip`

and then building it. I have my own custom extensions build each having their own `composer.json` file which I have to manually copy. 

Now, I want to write one `composer.json` for my CRM app where I include all the packages and I say 
- espocrm should go here (some path),
- espo-extension-1 should go here (some other path),
- espo-extension-2 should go here (some other path). 

Then I want to build it and deploy it. The Gruntfile you guys have written, which is awesome by the way, will copy my extensions without any sweat. It's the composer which is struggling to find all composer.json files it has to install. Otherwise, I have manually do it one by one.

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/espocrm/espocrm"
        },
        {
            "type": "git",
            "url": "https://github.com/abc/ext-1"
        },
        {
            "type": "git",
            "url": "https://github.com/abc/ext-2"
        }
    ],
    "require": {
        "espocrm/espocrm": "5.4.5",
        "abc/ext-1": "*",
        "abc/ext-2": "*"
    },
    "extra": {
         "installer-paths": {
                "espocrm/espocrm": "some-path-which-is-not-vendor",
                "abc/ext-1": "espocrm/application/Espo/Modules/ModuleName/Providers/Ext-1",
                "abc/ext-2": "espocrm/application/Espo/Modules/ModuleName/Providers/Ext-2"
         }
    }
}
```

Right now, it's putting espocrm directly to vendor dir. And in your bootstrap.php and several other places you have hard-coded `require_once vendor/autoload.php`

You're more than welcome to suggest better solution if you find one!

**Comment by yurikuzn** [comment]
So the problem is that espocrm is installed in `vendor` directory but you need it to be installed into `espocrm` directory. What about vendor files of epsocrm itself. Where they will be installed?

**Comment by karthik-uc** [comment]
Using vendor-dir, one can specify where it should go!

this is my composer.json

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/karthik-uc/espocrm"
        }
    ],
    "require": {
        "espocrm/espocrm": "dev-staging"
    },
    "extra": {
        "installer-paths": {
            "espocrm": ["espocrm/espocrm"]
        }
    },
    "config": {
        "vendor-dir": "espocrm/vendor"
    }
}
```

**Comment by yurikuzn** [comment]
And you don't have any problems with this? Everything works fine?

**Comment by karthik-uc** [comment]
no. my above solution has problems. The vendor dir is created first and then overwritten by espo repo. need to figure out a way to make espo repo clone first and then vendor

**Comment by karthik-uc** [comment]
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/karthik-uc/espocrm"
        }
    ],
    "require": {
        "espocrm/espocrm": "dev-staging"
    },
    "extra": {
        "installer-paths": {
            "espocrm": ["espocrm/espocrm"]
        }
    },
    "scripts": {
        "post-install-cmd": [
            "cp -r vendor espocrm",
            "rm -rf vendor"
        ],
        "post-update-cmd": [
            "cp -r vendor espocrm",
            "rm -rf vendor"
        ]
    }
}
```

Well, this is my working solution

**Comment by karthik-uc** [comment]
I am planning to use this as it doesn't require `composer/installer` package!

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/espocrm/espocrm"
        }
    ],
    "require": {
        "espocrm/espocrm": "5.4.5"
    },
    "config": {
      "vendor-dir": "espocrm/vendor"
    },
    "scripts": {
        "post-install-cmd": [
            "cp -r espocrm/vendor/espocrm/espocrm espocrm",
            "rm -rf espocrm/vendor/espocrm/espocrm"
        ],
        "post-update-cmd": [
            "cp -r espocrm/vendor/espocrm/espocrm espocrm",
            "rm -rf espocrm/vendor/espocrm/espocrm"
        ]
    }
}
```
