### ISSUE TITLE
Add Case Number to text search field

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#941]
Hi

I see [here](https://github.com/espocrm/espocrm/blob/a4c15992a952cc80945783017a60f305bbeceb6c/client/src/views/admin/entity-manager/modals/edit-entity.js#L272) that it should be possible to add a number to the text search box, but I'm unable to add the Case Number field. Could number fields be added, or is there a reason that they're excluded?

Kind regards

**Comment by yurikuzn** [comment]
Hi,

Because case doesn't have a number-type field.

**Comment by Sloff** [comment]
I assumed the `number` referred to the `Number (auto-increment)` field type, because I am also unable to add `float` or `integer` fields to the text search box

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/954
