### ISSUE TITLE
Can't upgrade - version mismatch issues

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#944]
I was running 5.2.4 with advanced pack 1.31.7 when I attempted to upgrade both EspoCRM and the advanced pack. I upgraded the advanced pack first to 1.32.4 and then I tried to upgrade EspoCRM to 5.2.5. However, EspoCRM now shows version 5.0.1 in About and Upgrade. I don't see any changes to the underlying files other than the files in the advanced extension upgrade file.

The version was set to 5.0.1 in the config file after the advanced extension upgrade, so I changed it back to 5.2.4 and then I was able to install the 5.2.5 upgrade to EspoCRM. The version is now set back to 5.0.1 after successfully completing the 5.2.5 upgrade. It looks like my data/config.php file has been changed quite a bit as well.

I'm not sure where to put this because I know this repository is only for issues with EspoCRM, but it seems like a code problem that could be in either place (EspoCRM or the advanced pack).

**Comment by yurikuzn** [comment]
It's unlikely that problem in EspoCRM or advanced pack code.

**Comment by yurikuzn** [comment]
Can be something in environment.

**Comment by bandtank** [comment]
This has happened every time I've upgraded recently, but I agree it likely isn't related to Espo or extensions. I will close this for now because I don't have enough information. Next time I upgrade, I will save the state of my virtual machine so I can perform the upgrade multiple times. Maybe I will be able to figure out what's happening and then I'll let you know.
