### ISSUE TITLE
Custom Report Export Bug

### ISSUE THREAD

**Issue by gundogduyakici** [espocrm/espocrm#953]
I have a custom report. It's work but export xls file not working.The results are zero. 
The example you are preparing does not work when exporting the report. "Leads by Last Activity"

Try this;
http://demo.espocrm.com/advanced/?#Report/view/001

**Comment by yurikuzn** [comment]
This repository is not for features from advanced pack.

**Comment by gundogduyakici** [comment]
Okay, How am I going to solve this problem?

**Comment by yurikuzn** [comment]
Please contact via the customer portal or forum.
