### ISSUE TITLE
Support Array in foreign field

### ISSUE THREAD

**Issue by Oakyden** [espocrm/espocrm#964]
Hi

I wanted to do something like add a "department" field to Account (bespoke list per account)  and then add a foreign field in Contact to log which department that contact works for. However, it looks like pretty much only varchar fields appear as available foreign fields?

Thanks,
Alan

**Comment by yurikuzn** [comment]
Hi Alan,

Unfortunately not supported. Only varchar, enum, int, and few other are supported.

**Comment by Oakyden** [comment]
OK thanks. I don't suppose this will come any time in future?

**Comment by yurikuzn** [comment]
Not sure, it needs to be investigated.

**Comment by yurikuzn** [comment]
Unfortunately, there are some obstacles.

**Comment by yurikuzn** [comment]
Already supported.
