### ISSUE TITLE
Use Numeric Format doesn't respect the date format

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#967]
The new `Use Numeric Format` setting on Date-Time fields does not respect the date format selected within the settings, for example:

![image](https://user-images.githubusercontent.com/7330170/42653518-f58b878a-8615-11e8-95c8-ca53fbb3f80f.png)

![image](https://user-images.githubusercontent.com/7330170/42653544-0bf07b66-8616-11e8-99b1-4469008ff6e7.png)

**Comment by yurikuzn** [comment]
In preferences

**Comment by Sloff** [comment]
You are correct, thank you!
