### ISSUE TITLE
Show phone numbers in linked entity

### ISSUE THREAD

**Issue by xanthos84** [espocrm/espocrm#970]
hi everyone!

i am not so experienced in coding, and everything i have found in my research was not working with the newest version - but maybe I am also a little bit to unexperienced to know where to put the correct stuff.

So I want to show phone numbers from Contact entity in the Cases entity.
And I am stuck.. maybe someone can let me know how to do this.

Thank you

**Comment by rabiibrahimi** [comment]
you can try foreign fields, it allows you to create field in case and use phone number of contact. see https://docs.espocrm.com/administration/fields/#foreign
