### ISSUE TITLE
No Horizontal Scroll Bar on Emails (Chrome)

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#972]
Hi

When an email is wider than the space no vertical scroll bar is present on Chrome and I can't see all the content of the email. It is there on Firefox though, so it might be something Chrome specific. 

Kind regards

**Comment by yurikuzn** [comment]
Hi,

Could you provide original content or body html of that email?

**Comment by Sloff** [comment]
Hi, as requested:
```html
<html><head><link type="text/css" rel="stylesheet" href="client/css/espo/hazyblue-vertical-iframe.css?r=1531532582">

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css" style="display:none;"><!-- P {margin-top:0;margin-bottom:0;} --></style>
</head>
<body dir="ltr">
<div id="divtagdefaultwrapper" style="font-size:12pt;color:#000000;font-family:Calibri,Helvetica,sans-serif;" dir="ltr">
<p style="margin-top:0;margin-bottom:0"><img size="16449" contenttype="image/png" style="width: 1287px; height: 294.412px;" id="218997_rs|3" tabindex="0" data-outlook-trace="F:1|T:1" src="?entryPoint=attachment&amp;id=5b4ccf16684eae7d5" width="350" height="80"><br>
</p>
<p style="margin-top:0;margin-bottom:0"><br>
</p>
</div>
</body></html>
```

Any image or table with a width that's more than what is available should cause this as well.

**Comment by Sloff** [comment]
For reference:

Firefox:
![image](https://user-images.githubusercontent.com/7330170/42772764-ba2aa2a2-892b-11e8-8a01-50c9adfb16fe.png)

Chrome:
![image](https://user-images.githubusercontent.com/7330170/42772856-f3155c2e-892b-11e8-9cc5-d77008ebc33d.png)

**Comment by yurikuzn** [comment]
So you mean horizontal scroll bar, not vertical?

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/e8d75808ef21485aea55b6d7b7c80e3a2d3823f9
https://github.com/espocrm/espocrm/commit/56f8e68599b12bcd96b9ec3dd1067411cb0af20d
