### ISSUE TITLE
UI small improvement suggestion

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#973]
Hi Yuri, if you are interested with like this UI improvements I will be happy to make PRs for them

new 
<img width="360" alt="screen shot 2018-07-16 at 5 43 44 pm" src="https://user-images.githubusercontent.com/2862528/42765209-29dfb472-8920-11e8-9c3c-bbfc414b965d.png">
original 
<img width="378" alt="screen shot 2018-07-16 at 5 48 02 pm" src="https://user-images.githubusercontent.com/2862528/42765312-6d9b6814-8920-11e8-89b0-717d97d09d94.png">

**Comment by bandtank** [comment]
I like it.

**Comment by yurikuzn** [comment]
Sorry I don't, since it doesn't conform to style of other field types.

**Comment by ayman-alkom** [comment]
In fact I take care about this point, but I agree that changes like these may cause some unexpected behaviors on UI.
When you need any help  I will be glad to share you my experience in UI development.
