### ISSUE TITLE
Show attachments in the upper part of email

### ISSUE THREAD

**Issue by Cri00** [espocrm/espocrm#988]
Hello!

When adding attachments to an email, even if there is an ”attach file” button in the styling bar at the start of the email, you still have to scroll down to the end of the email to see if the files have been truly attached. The problem is that if you have a long discussion (many replies) and click the attach file in the upper bar, you still have to scroll down to the end to see if it was attached. So, maybe it would be a good idea to show in the upper part too when attachments have been added to the email.

Thanks!

**Comment by yurikuzn** [comment]
Already resolved (partially) with attachments in the side panel.

**Comment by yurikuzn** [comment]
Alert with names of uploaded files will be shown. https://github.com/espocrm/espocrm/commit/47735aaa0bb38acef142960fb5886637f766d6d9
