### ISSUE TITLE
Email Folders: Only 20 are shown

### ISSUE THREAD

**Issue by Sloff** [espocrm/espocrm#989]
I have more than 20 email folders as shown here:
![image](https://user-images.githubusercontent.com/7330170/43455640-d675c158-94c0-11e8-8cd8-370454f10301.png)

But when viewing the folders on the email screen, only 20 are shown, as can be seen here:
![image](https://user-images.githubusercontent.com/7330170/43455673-f5b6172a-94c0-11e8-9c24-b693f1861ae2.png)

Also when I want to move an email to a folder, only 20 are displayed:
![image](https://user-images.githubusercontent.com/7330170/43455717-11f72870-94c1-11e8-85e9-3ad1075a67bd.png)

**Comment by Sloff** [comment]
Version 5.3.4

**Comment by yurikuzn** [comment]
Thanks for reporting.

Fix: https://github.com/espocrm/espocrm/commit/32d47db15a58e3cca4abe2e5d48ec2550cb3197c

**Comment by Sloff** [comment]
I've updated to the latest version (5.3.6), the issue is resolved on the email folder view:
![image](https://user-images.githubusercontent.com/7330170/43682597-bc47c594-9879-11e8-99b3-e80e6c0d6ce6.png)

But it's still not resolved on the "Move email to folder view":
![image](https://user-images.githubusercontent.com/7330170/43682604-fbfbf390-9879-11e8-85b0-3084c28a073a.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/304d216b0eb42cbe1607dc789782e17b79f36f71
