### ISSUE TITLE
Textfilter issue?

### ISSUE THREAD

**Issue by pauladiniz** [espocrm/espocrm#991]
Here's what I need: I need to type and filter the registered companies on Leads. I changed the search.js code, but it will only filter people's name, not companies.
Am i changing the right file?

This is my code:

`events:` {
            'keyup input[name="textFilter"]': function (e) {
                var that = this;

                loading = true;`

                setTimeout(function() {
                    if (loading) {
                        that.search();
                    }

                    loading = false;
                }, 1000);
                
            }**`

**Comment by m-hcb** [comment]
I think this is the default behavior. Otherwise, to achieve what you want, you will have to override the backend code too.
