### ISSUE TITLE
Widening interface boundaries/view on big monitors

### ISSUE THREAD

**Issue by bandtank** [espocrm/espocrm#995]
Is it possible to widen the UI to accommodate large monitors? I could get a lot of use out of a much larger dashboard, for example. See below. Nothing I've tried has worked except modifying the classes manually, which doesn't look good. This isn't really an issue, but I can't tag it has a question.

![untitled](https://user-images.githubusercontent.com/1170415/43585169-a4fefefc-9621-11e8-9e43-78192d943b0f.png)

**Comment by yurikuzn** [comment]
Do you mean just increasing max-width of #content div?

**Comment by bandtank** [comment]
Yes, that's what I meant. Let me try your change to see how it looks.

**Comment by bandtank** [comment]
Is there any harm in widening it further specifically in my installation? My users all have very large monitors, so I could edit the max width setting and then check for changes during updates. I'd like to set it to 3500.

**Comment by yurikuzn** [comment]
3500 is too much for my thinking. It's reasonable zoom-in in browser.

You can change css as you want if you build from a forked repository.

**Comment by bandtank** [comment]
The native resolution of our monitors is 3840x2160, which is why we would like to widen the page width. I will look into building my own css to accomplish this. Thanks.

**Comment by yurikuzn** [comment]
It's supposed to use zoom with high resolutions. Font is too small otherwise. Most modern web applications won't be widened to fit full screen.

**Comment by bandtank** [comment]
The DPI, not resolution, is what's important. We are using 43" monitors and the text looks perfect when widened to 3500px because the DPI is the same as a smaller monitor with a lower resolution.

Here is how EspoCRM looks on our screens:

![2018-08-02_09-54-42](https://user-images.githubusercontent.com/1170415/43596855-ab29aa90-963d-11e8-9edb-a58523ed6e22.png)

Most of the apps we use are full screen even on our big monitors at 3840x2160 and they work well in scenarios with two big monitors, e.g. 7680x2160. See some examples here:

![2018-08-02_09-53-45](https://user-images.githubusercontent.com/1170415/43596568-e0ff1840-963c-11e8-869c-b3bf6d4a022a.png)
![2018-08-02_09-54-04](https://user-images.githubusercontent.com/1170415/43596569-e115d72e-963c-11e8-8a0a-f072dac99c15.png)
![2018-08-02_09-54-20](https://user-images.githubusercontent.com/1170415/43596570-e12d70c8-963c-11e8-8afd-2cfd4fd86e62.png)
![2018-08-02_09-54-29](https://user-images.githubusercontent.com/1170415/43596571-e141cd02-963c-11e8-8d04-255b20fa8cdc.png)
![2018-08-02_09-56-22](https://user-images.githubusercontent.com/1170415/43596572-e1553f7c-963c-11e8-9ab6-31698cdc5aeb.png)
![2018-08-02_09-57-52](https://user-images.githubusercontent.com/1170415/43596573-e168268c-963c-11e8-993a-75d335d604f6.png)
![2018-08-02_10-01-08](https://user-images.githubusercontent.com/1170415/43596574-e1814aa4-963c-11e8-9304-d6e7c6e0030a.png)
![2018-08-02_10-02-10](https://user-images.githubusercontent.com/1170415/43596575-e1a1cffe-963c-11e8-9388-2c3d806cb6de.png)

**Comment by rodrigoscoelho** [comment]
I have exactly the same problem here.

Using a wide monitor.





_______________________________________




*Rodrigo Sírio Coelho*

*Engenharia*

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807

2018-08-02 13:20 GMT-03:00 Anthony Andriano <notifications@github.com>:

**Comment by rodrigoscoelho** [comment]
Example below

![image](https://user-images.githubusercontent.com/6912410/43597464-85412306-9658-11e8-86b3-706b0c272549.png)

**Comment by yurikuzn** [comment]
The first example you provide is that what I meant. It's not widened, otherwise forms would look ugly.

**Comment by bandtank** [comment]
Is it possible to arrange panels in a form like dashlets? That would be really nice if it's not hard to do. Otherwise, lists, reports, and dashboard views could benefit from being widened even if forms can't. Just a thought.

**Comment by yurikuzn** [comment]
It would require overhaul. Not simple.

**Comment by bandtank** [comment]
Ok, maybe some other time then. Making forms dynamic like dashlets would be a great feature if that is ever able to be implemented.

**Comment by yurikuzn** [comment]
I though about moving bottom panels to the right if width increases a defined threshold.

**Comment by bandtank** [comment]
Do you mean the relationship panels? That would be extremely nice. Some of our forms are very long.

**Comment by yurikuzn** [comment]
Yes. But only if width is wide enough, so that panels on the right won't be too narrow.
